### ISSUE TITLE
Difference between best_model and final_model 

### ISSUE THREAD

**Issue by DecentMakeover** [flairNLP/flair#1005]

**Comment by BernierCR** [comment]
These names are confusing. Final model means the last model, from the last epoch. Best Model means the model which has the best performance on the validation set.

**Comment by alanakbik** [comment]
Yes we could change this, any suggestions for names? Perhaps we should not write out the final model and only write out the best model?

**Comment by DecentMakeover** [comment]
yes, i think that makes sense, the final-model does seem redundant.
