### ISSUE TITLE
Optimizers for the SequenceTagger model

### ISSUE THREAD

**Issue by mauryaland** [flairNLP/flair#1008]
Hi! I wonder if you have done some experiments with the optimizers available in flair such as SGDW and AdamW? In the [EXPERIMENTS section](https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md), it seems that the default SGD is always apply. Is it because it converges fast enough without taking too much memory?

On the same  topic, a new optimizer called [RAdam](https://arxiv.org/abs/1908.03265) shows some good improvements and has a [PyTorch implementation](https://github.com/LiyuanLucasLiu/RAdam). Could it be a good idea to integrate it to flair?

Thanks for your clarifications.

**Comment by alanakbik** [comment]
Yes we pretty much always use normal SGD but testing RAdam would definitely be interesteing!
