### ISSUE TITLE
Hyperparameter tuning logging

### ISSUE THREAD

**Issue by BernierCR** [flairNLP/flair#1028]
Hello. I can't seem to get much information out of the hyperparameter tuning. I tried using tee to get a full training log, but it resulted in just the tail end of the output being saved. Where did the rest of the training information go? Tee should have saved the entire set of training runs. 

Also, at the end, all it says is which one is best. I want to save the performance of each model. What if they are all almost the same and only different in the 3 or 4th decimal place? That's something I need to know. 

Any ideas on how to get better logging? 

Thanks

**Comment by alanakbik** [comment]
Good points - we are looking at hyperparameter selection methods right now and in particular looking at switching over to [Tune](https://ray.readthedocs.io/en/latest/tune.html) library which supports many different hyperparameter selection algorithms. We might end up refactoring the current hyperparameter process, so better logging is something we definitely should add while we do it.
