### ISSUE TITLE
mini_batch_size

### ISSUE THREAD

**Issue by BernierCR** [flairNLP/flair#1040]
My intuition is that we should basically use as large a batch as we can without getting CUDA OOM errors. Is that true? 

For my language model, GPU utilization is 100%, going nicely. It doesn't seem to need larger batches.

For my TextClassifier model, GPU utilization is lower. And I get it won't get high. But would a larger batch size be faster? This particular model is smaller and hence even with a large mini_batch_size, I'm only using less than 10% of GPU RAM. I feel like the smaller batches might just be wasting GPU resources. But I'm not sure if it really works like that. 

Any ideas?

**Comment by pommedeterresautee** [comment]
Depending of the algo you use, you may have some CPU bottleneck and batch won't change anything. Do you see one CPU core all the time at 100? If this is the case, you need to rework the algo, sometimes there are optimization opportunities. More scientific way to proceed is to just profile the training.
Regarding batch size, bigger is not always the best, size has a regularization effect. Last papers on the subject recommends a size evolving during the training. Check Spacy code, they have a little tool for that, which I think is agnostic to algo, it s just to prepare the batches.

**Comment by BernierCR** [comment]
Oh, the CPU, thanks for the reminder. When doing the language models I increased the number of workers, but didn't do so for the regular models. So that could explain some of the difference. 

I have also maybe noticed an accuracy effect just now. Not sure, will have to experiment with batch sizes. Thanks for the assurance that batch sizes could have such an effect. 

And thanks for that recommendation. I can't right go too far off the beaten path this week, but that's a for sure checkout and maybe get added to the backlog thing.
