### ISSUE TITLE
Using EMLO and Fasttext embeddings 

### ISSUE THREAD

**Issue by Dragon615** [flairNLP/flair#1058]
Hi,
I noticed in the following issue: [issue](https://github.com/zalandoresearch/flair/issues/308#issue-390627597) that It's possible to combined ELMO embeddings with Fasttext embedding to train a sequence tagging model.  
I have a question regarding combining or using ELMO with Fasttetx or Flair embeddings. It's not clear to me which embedding should be used when training your model. So, if I have a word like "play" appears in multiple contexts, ELMO will produce an embedding for each word in each context, while Fasttext has its own way in producing the embeddings based on the sub-word information for the word "play". Can someone explain to me briefly how to use both fasttext and ELMO embeddings? Also, are you fine-tuning the pre-trained embeddings while training your models?
Sorry if my questions look silly :|

Thanks in advance for your help!

**Comment by alanakbik** [comment]
Hi @Dragon615 you can combine any embeddings you like by using the `StackedEmbeddings` class as described [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_3_WORD_EMBEDDING.md#stacked-embeddings). So to combine ELMo and FastText, you could do something like this: 

```python
# create a StackedEmbedding object that combines ELMo and FastText
embeddings = StackedEmbeddings([
    ELMoEmbeddings(),
    FastTextEmbeddings('path/to/fasttext/model.bin'),
])
```

Most embeddings in Flair will not get fine-tuned themselves, but are fine-tuned via a reprojection layer that sits on top of the embedding layer. Which embeddings or embedding combination makes sense always depends on your downstream task. For sequence labeling, we use `FlairEmbeddings` in combination with `WordEmbeddings` a lot, though others have reported great results with various transformer embeddings. An overview of all embeddings supported in Flair is [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md).
