### ISSUE TITLE
What preprocessing for standard word embeddings?

### ISSUE THREAD

**Issue by lucaventurini** [flairNLP/flair#1061]
Hello,

I've read several times in the issues here that the "suggested approach" with preprocessing and Flair is to leave the text untouched (cases, tokens, punctuations, etc...).

However, some "classic" word embeddings often require to use the same kind of preprocessing that it was used to compute them, for example fasttext wikipedia embeddings are all lowercased.

Is it currently possible to stack
* Flair embeddings of the original text
* Word embeddings of lowercased/tokenized/preprocessed text
?

**Comment by alanakbik** [comment]
Hi @lucaventurini for all embeddings you should not do any preprocessing. All preprocessing is handled in the respective embeddings class. So for instance if you use `WordEmbeddings`, you don't need to lowercase since this class has internal heuristics that do this for you if necessary.

**Comment by lucaventurini** [comment]
Hi @alanakbik thank you. Could you point me to the lines of code that have these heuristics? I wasn't able to find it, even if I had a vague remembering that I had read about it 😅

**Comment by alanakbik** [comment]
The code block for WordEmbeddings starts [here](https://github.com/zalandoresearch/flair/blob/5583815305a44d98dec2d0e9e54bead89dcb1910/flair/embeddings.py#L320). Essentially, it first looks if the word as-is exists in the word embeddings file, otherwise it tries the lowercased version and if this is not found it tries replacing all numbers with 0.

**Comment by lucaventurini** [comment]
Ok, I see now.

I was wondering if it'd make sense to experiment with this, but I see that this behavior it's not easily customizable.

For example, I was thinking of these words that probably don't get embed like in the original:
* urls, as / were not splitted in the original wiki preprocessing, so an url became something like //github com/
* words followed by a comma or apostrophes in the news embeddings
* words of emojis, as they appear only as single tokens in the embeddings
* tokenization of different languages with different tokenizers within the crawl embeddings

just to mention a few examples. Are some of them already covered maybe?

**Comment by alanakbik** [comment]
@lucaventurini good points - such things are not covered by the heuristics, though many recent embeddings implicitly handle such cases by going to the subword or character-level. For instance, `FlairEmbeddings` decompose everything into characters and so should be able to deal with emojis and urls (provided such things were seen in the training data for the embeddings) and strange tokenization.

**Comment by lucaventurini** [comment]
@alanakbik and were urls and emojis seen, in the case of the pre-trained flair available? and if yes, I guess they were seen un-processed, right?

So if I process text anyway to try to "help" the classic word embeddings, I'd probably end up "spoiling" the flair ones, that have most probably never seen a url split like //github com/ , for example.

**Comment by pommedeterresautee** [comment]
Source to train Flair LM are listed there: https://github.com/zalandoresearch/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md
Most LM are Wikipedia based, but there are also other sources (news, web, etc.).

Even it has never seen github.com (which is never true as github is on Wikipedia), it may have understood the meaning of http:// and .com suffix... because the many web addresses it has met during its learning.

**Comment by lucaventurini** [comment]
@pommedeterresautee thank you for the sources.

> Even it has never seen github.com (which is never true as github is on Wikipedia), it may have understood the meaning of http:// and .com suffix... because the many web addresses it has met during its learning.

Yes, I agree on this. My initial point was that I would have liked to preprocess text in a way that also classic word embeddings can embed, for example, urls. But If I do so, http://github.com will become //github com (in the example of fasttext wiki embeddings), and I doubt that flair has ever learnt to see a com preceded by a space, or a url stripped like this.
