### ISSUE TITLE
Scalable hyperparameter selection with Ray Tune

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1067]
[Ray Tune](https://ray.readthedocs.io/en/latest/tune.html) is a framework for hyperparameter selection that supports running processes in parallel across multiple CPUs/GPUs and has connectors to a number of hyperparameter selection frameworks such as Hyperopt and Bayesopt. 

As discussed in #563 with @myaldiz and @richardliaw it would be interesting to add support for this framework and potentially replace the current hyperparameter selection classes based on Hyperopt with this more general framework. For this, we need to slightly refactor the model trainer and the checkpointing mechanism.

**Comment by richardliaw** [comment]
I can help review if you want! Just let me know when you open the PR.

**Comment by alanakbik** [comment]
@richardliaw thanks a lot - I'll let you know when it's ready!
