### ISSUE TITLE
How to add Stopwords for flair NER

### ISSUE THREAD

**Issue by nh111** [flairNLP/flair#1069]
How to add Stopwords to flair NER, as sometimes it is picking which are not correct.

**Comment by pommedeterresautee** [comment]
There is no easy way to exclude stop words. You can of course do it in a post inference process (would be easy to check the `List[Token]` in `Sentence` class). However, to really solve it cause, you need to find the real cause:

* the dataset is too small -> you need more train data
* some tags include stop words and some others don't -> you need to clean your existing train data (happened most of the time)
