### ISSUE TITLE
How can I train own PooledFlair embedding, Word2vec, FastText, ...?

### ISSUE THREAD

**Issue by quancq** [flairNLP/flair#1071]
How can I train own PooledFlair embedding, Word2vec, FastText, ...? How can I load pre trained word2vec by gensim library to train ner model?

**Comment by alanakbik** [comment]
Hello @quancq here is information on [how to train your own Flair embeddings](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md).

To load your own gensim embeddings, check out [this documentation](https://github.com/zalandoresearch/flair/blob/master/resources/docs/embeddings/CLASSIC_WORD_EMBEDDINGS.md) (information given at bottom of that page).

**Comment by quancq** [comment]
@alanakbik I read [Tutorial 9: Training your own Flair Embeddings](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md). I confused about train PoolFlair embedding?

**Comment by pommedeterresautee** [comment]
Pooling is a way to use several embeddings together. Among the embeddings you can use with pooling, there are Word2vec, etc.
Pooling offers a little boost in accuracy against a drop in speed. You may prefer simple stacking (technically it s more a concatenation) to pooling to keep your inference fast.

**Comment by quancq** [comment]
@alanakbik I dont understand how to train own PoolFlair embedding. According tutorial 9, I must fine tuning PoolFlair embedding from exist model, but my dictionary different with dictionary of pretrained model. @pommedeterresautee PoolFlair which i refer is [Pooled Contextualized Embeddings for Named Entity Recognition](https://www.aclweb.org/anthology/N19-1078)

**Comment by pommedeterresautee** [comment]
If I am not mistaking, `PooledFlairEmbeddings` replaces `StackedEmbeddings` to train a NER for instance (like in Tutorial 7), but has no meaning to train a LM (purpose of Tutorial 9).

**Comment by alanakbik** [comment]
@quancq the `PooledFlairEmbeddings` are a pooled variant of `FlairEmbeddings`, so any language model can be used for both. If you follow the steps in the tutorial to train your own LM you can both use it for `PooledFlairEmbeddings` and `FlairEmbeddings` embeddings, all you have to do is use the appropriate constructor.

**Comment by quancq** [comment]
@alanakbik  thanks. How to load ELMo trained by alliennlp linrary and construct ELMoEmbedding instance in flair?

**Comment by quancq** [comment]
Construct ELMoEmbeddings with 2 argument: ``options_file`` and ``weight_file`` ?
