### ISSUE TITLE
Adding New Embeddings

### ISSUE THREAD

**Issue by sanja7s** [flairNLP/flair#1085]
Hi and thank you so much for this amazing library. Would it be possible to add new embeddings into it: clinicalBERT?

https://github.com/EmilyAlsentzer/clinicalBERT

Is it something we can do ourselves once we download the respective embeddings? I would be happy to help if you could point me how to with adding these.

**Comment by sanja7s** [comment]
Ok, @stefan-it, I have another question -- I tried to reproduce the same steps as you suggested for clinicalBERT to add BioBERT from here

https://github.com/naver/biobert-pretrained

I think I did everything in the same way, but I now do get this error:

`    self.__embedding_length += embedding.embedding_length
  File "/home/xxx/anaconda3/envs/flair_CLONE/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertEmbeddings' object has no attribute 'embedding_length'
`

Could you help me -- is there any simple suggestion on how to resolve this?
This is the structure of the new embedding file:

`
._bert_config.json
biobert_model.ckpt.data-00000-of-00001
biobert_model.ckpt.index
 biobert_model.ckpt.meta
config.json
 ._vocab.txt
 vocab.txt
`

By comparison with clinicalBERT, I see it is missing which seem pytorch related

`
graph.pbtxt
pytorch_model.bin
`

Is it perhaps the problem? Is there still a way to make these embeddings work with Flair?

Many thanks!

**Comment by stefan-it** [comment]
Hi @sanja7s,

unfortunately, the BioBERT authors only provide the TensorFlow checkpoints. But that's no problem, we just need to convert them into PyTorch-compatible weights. For that reason, install the latest version of `pytorch-transformers` (like: `pip install --upgrade pytorch-transformers).

Download and extract a BioBERT model (I used *BioBERT v1.0 (+ PubMed 200K + PMC 270K)* for testing). First, rename the `biobert_v1.0_pubmed_pmc` to `bert-base-biobert-cased` (for better naming).

```bash
mv biobert_v1.0_pubmed_pmc bert-base-biobert-cased
cd bert-base-biobert-cased
```

For the next steps: make sure that you have a recent TensorFlow version installed (needed to convert the TF checkpoints), Conversion can be started with:

```bash
pytorch_transformers bert biobert_model.ckpt bert_config.json pytorch_model.bin
```

Last output should show something like:

```bash
INFO:pytorch_transformers.modeling_bert:Initialize PyTorch weight ['bert', 'pooler', 'dense', 'bias']
INFO:pytorch_transformers.modeling_bert:Initialize PyTorch weight ['bert', 'pooler', 'dense', 'kernel']
Save PyTorch model to pytorch_model.bin
```

Last step: rename the configuration file:

```bash
mv bert_config.json config.json
```

Then BioBERT could be loaded and used in `BertEmbeddings`:

```python
from flair.data import Sentence
from flair.embeddings import BertEmbeddings

embeddings = BertEmbeddings("/tmp/bert-base-biobert-cased")  # adjust path here

sentence = Sentence("Hemoglobin H inclusions can only be visualized with supravital stains and not Wright or Romanowsky stains.", use_tokenizer=True)

embeddings.embed(sentence)

for token in sentence.tokens:
  print(token.embedding)
```

**Comment by sanja7s** [comment]
God bless you, @stefan-it! It worked again like a charm.
Cheers!
