### ISSUE TITLE
Flair Language Model not using multiple CPU cores

### ISSUE THREAD

**Issue by aashay96** [flairNLP/flair#1122]
While Finetuning the LM model, the Language Trainer module is not making use of all the underlying CPU cores even with num_workers parameter being present.

To Reproduce - 
 from flair.data import Dictionary
from flair.embeddings import FlairEmbeddings
from flair.trainers.language_model_trainer import LanguageModelTrainer, TextCorpus

language_model = FlairEmbeddings('multi-forward').lm
is_forward_lm = True
dictionary: Dictionary = language_model.dictionary

corpus = TextCorpus('corpus/',
                    dictionary,
                    is_forward_lm,
                    character_level=True)

trainer = LanguageModelTrainer(language_model, corpus)

trainer.train('resources/taggers/language_model',
              sequence_length=50,
              mini_batch_size=500,
              learning_rate=20,
              patience=10,
              num_workers=4,
              use_amp=True,
              checkpoint=True)

*Expected behavior*- 
The library should be using all the underlying CPU cores

Screenshots

<img width="571" alt="Screenshot 2019-09-18 at 12 36 55 PM" src="https://user-images.githubusercontent.com/8274603/65123521-0eda5680-da11-11e9-8e3d-9aa70177a5f7.png">

Environment (please complete the following information):
 - OS : Linux:
 - Version: flair-0.4.3

**Comment by pommedeterresautee** [comment]
The num worker parameter is for the DataLoader not the algo itself (cf. https://github.com/zalandoresearch/flair/blob/568b6902b5574b019bdba1605163fd06ae86c2bd/flair/trainers/language_model_trainer.py#L308). So it s not surprising that you are using only one core. 

I have not checked but may be setting this option would make pytorch to distribute computation on many cores: 
https://pytorch.org/docs/master/torch.html#torch.set_num_threads
