### ISSUE TITLE
What words i should use unknown words in using POS tagger?

### ISSUE THREAD

**Issue by hayata-yamamoto** [flairNLP/flair#1127]
A clear and concise description of what you want to know.

I want to know what symbol means "Not symbol" in making SequenceTagger.

In my case, I'm using SequenceTagger for punctuation task. I should declare a label which means not symbol after that. For example, "I want to know flair." => ["non", "non", "non", "non", "Period"]

In this case, what words I should use to represent nothing?

**Comment by alanakbik** [comment]
You could use "O" (as in 'out'), which is the standard tag in NER for representing things that are not an entity.

**Comment by hayata-yamamoto** [comment]
@alanakbik 
Thanks!

Although I'm not familiar to NER, Should I care of <unk> tag in SequenceTagger? Looking at your answer, <unk> tag is not always needed, but <unk> tag must be included in the supervised label like <START> and <STOP>.
