### ISSUE TITLE
Pre-train model URL seems to be unavailable

### ISSUE THREAD

**Issue by aRookieMan** [flairNLP/flair#1129]
I am using FlairEmbedding, but the following URL seems to be unavailable :
https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings-v0.4.1/big-news-forward--h2048-l1-d0.05-lr30-0.25-20/news-forward-0.4.1.pt

Ohter URLs are unavailbale. Do you have some backup?

**Comment by alanakbik** [comment]
Does this error still persist? I can reach the URL. Is this maybe a problem in your network?
