### ISSUE TITLE
Predicting against a flair-embedding trained model is >10x slower than predicting against glove/en trained

### ISSUE THREAD

**Issue by tombburnell** [flairNLP/flair#1152]
Predicting 1000 articles takes <1m using glove/en based trained model and approx 10mins using flair news-forward/news-backward based model.

Is this to be expected?

**Comment by pommedeterresautee** [comment]
Hi, very last version on master branch should be much faster. It is expected to have a large difference between pre-computed embeddings like FastText, and contextual embeddings like Flair LM. In Flair LM, the representation of a token depends of its context. So you can't recycle embeddings. To compute them you use some RNN (GRU or LSTM, it s a parameter in master branch version).

**Comment by alanakbik** [comment]
@tombburnell also, Flair embeddings are more costly to produce than GloVe embeddings, so depending on your GPU setup it will be much faster to just use regular embeddings.

**Comment by tombburnell** [comment]
@pommedeterresautee Are there instructions for using the github version?

**Comment by alanakbik** [comment]
@tombburnell you can install current master branch in a new environment like this: 

```console
pip install --upgrade git+https://github.com/zalandoresearch/flair.git
```

**Comment by tombburnell** [comment]
Thanks @alanakbik . Also, are you familiar with the issues I'm having in https://github.com/zalandoresearch/flair/issues/1094

Thanks, Tom
