### ISSUE TITLE
List of language

### ISSUE THREAD

**Issue by orko19** [flairNLP/flair#1158]
Hi
Where can I check the list of language you created models for?

Thanks

**Comment by stefan-it** [comment]
Hi @oren1k ,

for Flair Embeddings just check out the following documentation:

https://github.com/zalandoresearch/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md#flair-embeddings

For NER, PoS tagging or classification models:

https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md#list-of-pre-trained-sequence-tagger-models

**Comment by oren1k** [comment]
@stefan-it Thanks!
Is there a way to get the following measures of similarity after loading an embedding?
1. Given a sentence, get the probability for a word Meaning P("Desk" | "The mouse is on the") and it's rank?
2. Frequency of the word in the vocab
3. Probability for a given sentence

Thanks!

**Comment by krzynio** [comment]
@oren1k

Look at this:
https://github.com/zalandoresearch/flair/pull/531
