### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by Hansen06** [flairNLP/flair#1161]
A clear and concise description of what you want to know.
ConnectionError: HTTPSConnectionPool(host='s3.eu-central-1.amazonaws.com', port=443): Max retries exceeded with url: /alan-nlp/resources/models/common_characters (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001580AC31F60>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by djxprogrammer** [comment]
I have met the same question just like u. I locate the error, and find a url "https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models-v0.4" . I tried to open this url in my browser but failed. So, I guess it is the problem of network, VPN is needed.

**Comment by secain** [comment]
Same problem. Is there any way to solve it now?
