### ISSUE TITLE
GPT-2 XL Model

### ISSUE THREAD

**Issue by gittb** [flairNLP/flair#1166]
Would it be possible to also include the new 774M param model for the GPT-2 embedding?

Here is the release: https://openai.com/blog/gpt-2-6-month-follow-up/

**Comment by stefan-it** [comment]
Hi @gittb,

this is already possible with the latest `master` version of Flair, just use:

```python
from flair.embeddings import OpenAIGPT2Embeddings

embeddings = OpenAIGPT2Embeddings(pretrained_model_name_or_path="gpt2-large")
```

I already did some NER experiments with the large GPT-2 model, see [here](https://github.com/stefan-it/flair-experiments/blob/master/conll2003-ner-english/README.md#experiments) :)

**Comment by gittb** [comment]
Great work with the NER! Thank you for the fast response.

**Comment by gittb** [comment]
Hello! Update, Could we possibly add the 1.5B param version now as well? Hugging face already has it out as the param 'gpt2-xl'

**Comment by stefan-it** [comment]
Hi @gittb,

this is also possible with flair. You just need to install the latest `transformers` version and pass the `gpt2-xl` to the `OpenAIGPT2Embeddings` object :)

**Comment by alanakbik** [comment]
All huggingface transformer models can now be used in Flair using the new `TransformerWordEmbeddings` and `TransformerDocumentEmbeddings` classes. See #1494. This is part of master branch and will be in the next Flair version.
