### ISSUE TITLE
Hash embeddings

### ISSUE THREAD

**Issue by carljohanrehn** [flairNLP/flair#1172]
I have added hash embeddings using the hashing trick and would like to create a pull request for this feature. 

This code snippet explains how the suggested feature could be used:

from flair.embeddings import HashEmbeddings

word_embedding = HashEmbeddings()
sentence = corpus.train[0]
word_embedding.embed(sentence)

for token in sentence:
    print(token)
    print(token.embedding)

**Comment by alanakbik** [comment]
@carljohanrehn this is great - we'd appreciate a PR for this!

**Comment by carljohanrehn** [comment]
I've created a branch on my fork. What is the procedure for doing a PR?
It's my first PR on GitHub. Can I simply press the button?

FYI, I intend to extend this feature with a more advanced approach.

**Comment by alanakbik** [comment]
Yes, you'd start a PR by pressing the button and specifying the master branch of this repo as target. With a PR, you typically write a short description of what it does and provide a code snippet on how to use (like you did above). 

A PR will also automatically trigger travis unit tests to make sure it doesn't break anything.
