### ISSUE TITLE
Multiple CPU usage

### ISSUE THREAD

**Issue by wongdarrell** [flairNLP/flair#1175]
Hi, 
I just downloaded the flair library, and tried to generate embedding vector assignments for a set of 300 comments (up to 2000 chars, multiple sentences in each comment). Observing the CPU usage performance in Windows, I see that all 4 cpus are being used at once in this call:

 [document_embeddings.embed(sentences2[i])  for i in range(0, len(df))]

My question is: Is there any way to control the number of cpus the program chooses to use? I am going to move up to a 56 core server, and I do not want to consume all 56 cpus, as it is a shared system.
Same question if I eventually move to a gpu-based system. If I have more than one gpu, can I control how many can participate?
Thanks

**Comment by pommedeterresautee** [comment]
Did you tried `torch::set_num_threads` ?

**Comment by wongdarrell** [comment]
Thank you. It worked.
