### ISSUE TITLE
TokenEmbeddings like Bert and Elmo are always static. That prevents finetuning.

### ISSUE THREAD

**Issue by berfubuyukoz** [flairNLP/flair#1184]
Hi Flair folks! (@alanakbik, @tabergma or @stefan-it since I recognize your names :)) 

I wonder if there is any deliberate reason for why **BertEmbeddings** and **ElmoEmbeddings** do not have **fine_tune** argument like **FlairEmbeddings** does:

```
class FlairEmbeddings(TokenEmbeddings):
    def __init__(self, model, fine_tune: bool = False, chars_per_chunk: int = 512):
```

 Lack of this argument prevents finetuning those embeddings. After first epoch is done, **_add_embeddings_internal** method is not called since **static_embeddings** argument is **True** for Bert and Elmo. (Related lines of Embeddings.embed below:)

```
if not everything_embedded or not self.static_embeddings:
    self._add_embeddings_internal(sentences)
```

Adding the same mechanism of FlairEmbeddings' to Bert and Elmo (and maybe also to other TokenEmbeddings sub classes which are potentially dynamic) could be beneficial. 

Sorry for poor formatting... My first issue! 
Have a nice weekend!

**Comment by stefan-it** [comment]
Hi @berfubuyukoz,

yeah, fine-tuning of e.g. BERT models is currently not possible. Implementation would require to write a bit more code (compared to the Flair Embeddings fine-tuning implementation) but I can point you to that fine-tuning implementation, that will be integrated into [Transformers](https://github.com/huggingface/transformers) (formerly: PyTorch-Transformers) very soon:

https://github.com/huggingface/transformers/pull/1275

With that implementation it is very easy to fine-tune a NER model with BERT. With a recent GPU you can fine-tune a NER model for English (CoNLL-2003) in ~3 minutes per epoch.

You can easily use that code for fine-tuning + you can use that fine-tuned model again with Flair (just pass the fine-tuned model path to the `BertEmbeddings` class).

**Comment by berfubuyukoz** [comment]
Hi @stefan-it, thank you for your response! 

So it takes a bit more than setting **static_embeddings** to **True** for finetuning eg. Bert @ flair right now, right? 

As I understand BertModel's parameters' **requires_grad** is **True** by default in transformers code. So I supposed it would work. 

But then with **static_embeddings** = **True**, I finetuned distilbert-base-uncased on binary text classification data (using flair) and got very low results indeed (macro-averaged f-score dropped from 0.68 to 0.43 through epoch 3). 

Thank you for sharing the neat NER example! <3
