### ISSUE TITLE
MongoDataset for reading text classification data from a Mongo database

### ISSUE THREAD

**Issue by carljohanrehn** [flairNLP/flair#1186]
I have implemented a MongoDataset class in Flair for reading text classification data from a Mongo database collection using queries.

Let me know if you are interested in this feature.

The following simple example shows how the MongoDataset class could be used:

query = {'Län': "Stockholms län"}

kwargs = {
    'host': 'localhost',
    'port': 27017,
    'database': 'rosenberg',
    'collection': 'book',
    'text_field': 'Beskrivning',
     'categories_field': ['Län', 'Härad', 'Tingslag', 'Församling', 'Plats']
}

train_dataset: MongoDataset = MongoDataset(query, **kwargs)

**Comment by pommedeterresautee** [comment]
Hi, by curiosity, why did you introduce a binding between Flair and mongo? Why not just extract batch of texts from Mongo and predict with the existing API?

**Comment by carljohanrehn** [comment]
Good question. 

I have been using Mongo in a related project for quite some time now and think it is a very convenient way of extracting data; it is also very fast. It offers flexibility in how you split and create your data sets by using queries.

**Comment by carljohanrehn** [comment]
Will do...

**Comment by alanakbik** [comment]
Was added in #1192
