### ISSUE TITLE
add multi task models

### ISSUE THREAD

**Issue by kilian-gebhardt** [flairNLP/flair#119]
It would be great to have multi task models in flair, i.e., a model that has task-specific components to predict the respective outputs but shares the input layer and the BiLSTM layer across tasks. 
See for instance https://github.com/jsalt18-sentence-repl/jiant/blob/c456df58cb6afad457048639c122d5e0b49d52c4/src/models.py#L526

potential advantages: 
- better results due to transfer learning
- faster inference if multiple tasks shall be performed on the same input

**Comment by alanakbik** [comment]
Yeah that would be great! We ran some initial experiments in this direction with a naive multi-task learning approach and while it works we noted a small drop in F1 vis-a-vis models that were trained for only one task. But I think there are lots of things that could be tried to improve this. So if you do experiments in this direction, we'd be happy to hear your progress!
