### ISSUE TITLE
cosine similarity between 2 sentence embeddings

### ISSUE THREAD

**Issue by fatimabs** [flairNLP/flair#1195]
my goal is to embedd two sentence using flair, then use cosine similarity between them in order to compare this 2 sentence/
This is my code:
`import torch
from flair.data import Sentence
from flair.embeddings import WordEmbeddings

# load word embeddings
embeddings = WordEmbeddings('glove')

# some example sentence
sentence = Sentence('I love Berlin')
text = Sentence('I don't love Berlin')
# embed sentences
embeddings.embed(sentence)
embeddings.embed(text)

# make one tensor of all word embeddings of a sentence
sentence_tensor = torch.cat([token.embedding.unsqueeze(0) for token in sentence], dim=0)
text_tensor = torch.cat([token.embedding.unsqueeze(0) for token in text], dim=0)
#cosine similarity
cos = torch.nn.CosineSimilarity(dim=0, eps=1e-6)
score = cos(text_tensor, sentence_tensor)
`
but if the sentences have a different lenght i get an error , how can i solve this problem ?

**Comment by djstrong** [comment]
You have to use a `DocumentEmbeddings`.

**Comment by 0x01h** [comment]
```python
import torch
from flair.data import Sentence
from flair.embeddings import XLMEmbeddings

embedding = XLMEmbeddings(pooling_operation="mean", use_scalar_mix=True)

sentence = Sentence(['The Hofbräuhaus is a beer hall in Munich .'])
embedding.embed(sentence)
sentence[0].embedding
```

When you try to use word embeddings while your sentences have different number of words, then you will get error calculating cosine similarity due to the different lengths of vectors. Instead of word embeddings, use sentence embeddings to get same length of sentence vectors. You may run one of the sentence embedding transformer for your problem.

**More examples:** https://github.com/zalandoresearch/flair/blob/master/resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md

**Comment by fatimabs** [comment]
@0x01h  thanks for your response

when running my code:
`flair_embedding_forward = FlairEmbeddings('my_best-lm.pt')
embedding = PooledFlairEmbeddings(flair_embedding_forward)
sentence = Sentence('طفرت من عينها دمعة فتحت الباب دون أن تكترث بالممرضة التي حاولت منعها')
embedding.embed(sentence)
sentence[0].embedding
in_1 = Sentence('مدخل البيت')
in_2 = Sentence('من الكتاب القسم يجمع مسائل من جنس واحد')
embedding.embed(in_1)
embedding.embed(in_2)
sentence_embedd = torch.mean(torch.cat([token.embedding.unsqueeze(0) for token in sentence], 0))
in_1_embedd = torch.cat([token.embedding.unsqueeze(0) for token in in_1], 0)
in_2_embedd = torch.cat([token.embedding.unsqueeze(0) for token in in_2], 0)
cos = torch.nn.CosineSimilarity(dim=0, eps=1e-6)
score1 = cos(sentence_embedd, in_1_embedd)
score2 = cos(sentence_embedd, in_2_embedd)
print(float(score1))
print(float(score2))`

i have this error
ValueError: only one element tensors can be converted to Python scalars

**Comment by fatimabs** [comment]
@0x01h thanks for your response

I still have the same problem 
this is my code

```
embedding = XLMEmbeddings(pooling_operation="mean", use_scalar_mix=True)
sentence = Sentence('طفرت من عينها دمعة فتحت الباب دون أن تكترث بالممرضة التي حاولت منعها')
embedding.embed(sentence)
sentence[0].embedding

in_1 = Sentence('مدخل البيت')
in_2 = Sentence('من الكتاب القسم يجمع مسائل من جنس واحد')
embedding.embed(in_1)
embedding.embed(in_2)


sentence_embedd = torch.cat([token.embedding.unsqueeze(0) for token in sentence], 0)

in_1_embedd = torch.cat([token.embedding.unsqueeze(0) for token in in_1], 0)
in_2_embedd = torch.cat([token.embedding.unsqueeze(0) for token in in_2], 0)

cos = torch.nn.CosineSimilarity(dim=0, eps=1e-6)

score1 = cos(sentence_embedd, in_1_embedd)
score2 = cos(sentence_embedd, in_2_embedd)
print(float(score1))
print(float(score2))
```
RuntimeError: The size of tensor a (13) must match the size of tensor b (2) at non-singleton dimension 0

**Comment by djstrong** [comment]
Use some `DocumentEmbeddings`, e.g. `DocumentPoolEmbeddings` (https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md).

@0x01h wanted to solve the problem by taking embedding for the first token:
```
sentence_embedd = sentence[0].embedding
```
It may be ok if some contextualized embeddings are used as XLMEmbeddings, bot not Glove.

**Comment by fatimabs** [comment]
so how can i use some contextualized embeddings are used as XLMEmbeddings, because i still have the same error even with embedding the first token 
```

embedding = XLMEmbeddings(pooling_operation="mean", use_scalar_mix=True)
sentence = Sentence('طفرت من عينها دمعة فتحت الباب دون أن تكترث بالممرضة التي حاولت منعها')
embedding.embed(sentence)
sentence[0].embedding

in_1 = Sentence('مدخل البيت')
in_2 = Sentence('من الكتاب القسم يجمع مسائل من جنس واحد')
embedding.embed(in_1)
embedding.embed(in_2)


#sentence_embedd = torch.cat([token.embedding.unsqueeze(0) for token in sentence], 0)
sentence_embedd = sentence[0].embedding
sentence_embedd = torch.cat([token.embedding.unsqueeze(0) for token in sentence], 0)

in_1_embedd = in_1[0].embedding
in_1_embedd = torch.cat([token.embedding.unsqueeze(0) for token in in_1], 0)

in_2_embedd = in_2[0].embedding
in_2_embedd = torch.cat([token.embedding.unsqueeze(0) for token in in_2], 0)

cos = torch.nn.CosineSimilarity(dim=0, eps=1e-6)

score1 = cos(sentence_embedd, in_1_embedd)
score2 = cos(sentence_embedd, in_2_embedd)


print(float(score1))
print(float(score2))
```

**Comment by djstrong** [comment]
You haven't deleted `...torch.cat([token.embedding.unsqueeze(0) for token in...` lines.

**Comment by fatimabs** [comment]
thanks a lot
what about replace 
`embedding = XLMEmbeddings(pooling_operation="mean", use_scalar_mix=True)`
with 
```
flair_embedding_forward = FlairEmbeddings('best-lm.pt')
embedding =  PooledFlairEmbeddings(flair_embedding_forward)
```

the goal behind is to test different embeddings and calculate the similarity between 2 sentences.
