### ISSUE TITLE
Feidegger corpus

### ISSUE THREAD

**Issue by yosipk** [flairNLP/flair#1197]
The [Feidegger corpus](https://github.com/zalandoresearch/feidegger) is a corpus of parallel image-text data of dresses and their descriptions in German language. For each dress there are up to 5 crowdsourced descriptions. The corpus provides also the train/dev/test splits.

It would be cool to have it integrated in Flair so one can experiment with various image-text tasks, e.g. retrieving images with text descriptions or learning grounded text representations.

**Comment by alanakbik** [comment]
Feidegger was added to Flair a while back :)
