### ISSUE TITLE
Logging performance on the (subset) of train set

### ISSUE THREAD

**Issue by yosipk** [flairNLP/flair#1198]
Flair currently supports logging performance measures only on the development set, while the performance on the train set is assessed only via loss. This loss is a) an average of losses over all train batches in an epoch, b) is a proxy for performance measure (e.g. accuracy for classification). 

In addition to this information, it would also be good to have the information about the performance of the model on the train set, to assess behavior of the model, i.e. to see if the model is over-fitting. However, since the train set is usually big, we could estimate this performance on the subset of the training data.

**Comment by alanakbik** [comment]
Was added a while back.
