### ISSUE TITLE
Initialization for mini_bach_chunk_size in trainer.py to None

### ISSUE THREAD

**Issue by yosipk** [flairNLP/flair#1216]
Currently the `mini_batch_chunk_size` is set to 32 in trainer.py. However, if `mini_batch_size` is changed and `mini_batch_chunk_size` is set to it's default initializer, the training won't proceed as in previous versions (and as expected). The behavior will be in most cases still the same, but the learning may be slower. In some cases, however, this will lead even to different behavior of the model. 

It would be therefore good to initialize `mini_batch_chunk_size=None`.

**Comment by alanakbik** [comment]
PR merged a while back
