### ISSUE TITLE
DocumentPoolEmbeddings and StackedEmbeddings differences?

### ISSUE THREAD

**Issue by 0x01h** [flairNLP/flair#1218]
Hi,

We are working on a *semantic search similarity* problem, so we need to get **decent** sentence vectors of titles for this problem. We trained a **FastText** model for a *specific* domain which is working fine. Moreover, we want to improve this **FastText** model using another sentence embeddings like Bert's `bert-base-cased-finetuned-mrpc` to achieve understanding of contexts which **FastText** can't do well. I've already tried `DocumentPoolEmbeddings` with FastText and Bert's `bert-base-cased-finetuned-mrpc` it seems okay, but

- Is there any observable difference between `DocumentPoolEmbeddings` and `StackedEmbeddings` methods in **Flair**?
- Which one do you suggest for *semantic similarity search problem* to get appropriate sentence vectors?

Thank you!

**Comment by mustfkeskin** [comment]
Hi @0x01h 

Stacked embedding concatenate different embeddings like [glove, fasttext, other_embeddings]
PoolEmbeddings use pointwise  (min, max, mean) pooling operation different embeddings. Like CNN pooling operation.

You can also look source code.

https://github.com/zalandoresearch/flair/blob/53d3f0afcb1000c79326ce7cd84b99e3e806f5e2/flair/embeddings.py
