### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by OguzKircicek** [flairNLP/flair#1219]
A clear and concise description of what you want to know.
hi , my code normalized, although I still get the error out of memory cuda.  What should I do? 

tagger: SequenceTagger = SequenceTagger(hidden_size=16,
                                            embeddings=embeddings,
                                            tag_dictionary=tag_dictionary,
                                            tag_type=tag_type)
        
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

trainer.train("", 
                  mini_batch_size=1,
                  max_epochs=5)

**Comment by alioz1967** [comment]
I would first check what nvidia-smi command returns. If the GPU memory is near full, you need to shut down those processes to free the GPU memory.

**Comment by OguzKircicek** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.94 GiB total capacity; 4.19 GiB already allocated; 9.00 MiB free; 1.08 GiB cached)  I have 8 gb gpu memory but not working.

**Comment by alanakbik** [comment]
@OguzKircicek the OOM error is probably coming from the word embeddings. Which embeddings are you using? Could you paste the code?

**Comment by OguzKircicek** [comment]
I CUDA problem solved but I have Fasttext .vec file but I can't import Fastext Embeddings. I received this error fasttext wrong file format. How do I solve?

embeddings= FastTextEmbeddings("../embeddings/tr_fasttext.vec")

**Comment by alanakbik** [comment]
@OguzKircicek you need to follow the steps in this tutorial to convert the file to gensim format and then load with `WordEmbeddings` object (not `FastTextEmbeddings`): 

https://github.com/zalandoresearch/flair/blob/master/resources/docs/embeddings/CLASSIC_WORD_EMBEDDINGS.md

**Comment by OguzKircicek** [comment]
@alanakbik  Thank you.I solved. I have one more question, I want it to be randomly selected for my  train and test set.
