### ISSUE TITLE
Training a Text Classification Model meet "GRU" key error

### ISSUE THREAD

**Issue by hazardwayne** [flairNLP/flair#1223]
**Describe the bug**
KeyError: 'GRU'

**To Reproduce**
Following the tutorial at https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md, i encountered KeyError: 'GRU' when predicting.

**Expected behavior**
I have updated flair version,  directly restoring model raises with this error, but about 2 months ago everything is ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/45623193/67078424-d9698a00-f1c3-11e9-9bdb-6ca93de881f1.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: centos
 - Version [e.g. flair-0.3.2]: flair-0.4.2 with error

**Additional context**

**Comment by alanakbik** [comment]
@hazardwayne could you try this with Flair 0.4.4? This was just released.
