### ISSUE TITLE
Trainable layers for transformers

### ISSUE THREAD

**Issue by isarth** [flairNLP/flair#1234]
Is it possible to make the layers of bert and other models trainable?

**Comment by stefan-it** [comment]
Hi @isarth,

fine-tuning of a BERT model is currently not possible in flair (only a "feature-based" approach, like it's called in the BERT paper).

But with the latest version of [Transformers](https://huggingface.co/transformers/examples.html#named-entity-recognition) it is possible to fine-tune a model on a NER dataset.

After fine-tuning you could pass that model into flair if you want :)

**Comment by aychang95** [comment]
Hi @isarth,

There's an open source library here https://github.com/Novetta/adaptnlp built atop Flair called **AdaptNLP** that let's you fine-tune language models like BERT with a [ULM-FIT](https://arxiv.org/abs/1801.06146) approach.

The fine-tuner provides some straightforward built-in layer freezing methods for your convenience in fine-tuning the language model.

The library is still in its early beta development, but tries to incorporate an approach that works seamlessly with Flair.  Feel free to leave any issues or requests in regards to what you're trying to do!

**Comment by alanakbik** [comment]
As of Fair 0.5, transformer embeddings are fine-tuneable through Flair and the recommended way to [train text classifiers](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-text-classification-model-with-transformer). So closing this issue but feel free to reopen with more comments.
