### ISSUE TITLE
OneHotEmbeddings vs glove embeddings

### ISSUE THREAD

**Issue by prashantbudania** [flairNLP/flair#1235]
Why are OneHotEmbeddings so slow (to train) vs glove embeddings? I am using OneHotEmbeddings to create a dictionary of words and initializing the embeddings. Then I replace the embedding matrix with pre-trained embeddings from glove (that way I can finetune glove embeddings and I don't want to use a linear transformation layer in between). But using the default implementation of glove is ~3-4 times faster than using OneHotEmbeddings. Am I doing anything wrong?

**Comment by JoyHuYY1412** [comment]
> Why are OneHotEmbeddings so slow (to train) vs glove embeddings? I am using OneHotEmbeddings to create a dictionary of words and initializing the embeddings. Then I replace the embedding matrix with pre-trained embeddings from glove (that way I can finetune glove embeddings and I don't want to use a linear transformation layer in between). But using the default implementation of glove is ~3-4 times faster than using OneHotEmbeddings. Am I doing anything wrong?

Hi, sorry to bother, but did you successfully running this? 
I meet the  

> ImportError: cannot import name 'TransformerEncoderLayer
My pytorch is 1.1.0 and python is 3.6.8. But I haven't seen any related issue here. Do you have any idea?
Thank you so much.

**Comment by alanakbik** [comment]
@prashantbudania yes the one hot embeddings might be slower, especially if you have a large corpus and so a large embedding matrix. The difference is that one hot embeddings are learned during training, whereas glove embeddings in our implementation are fixed.  

@JoyHuYY1412 this question is being discussed in #1236
