### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 32 in sequence argument at position #1 'tensors'...I got this error when i try to train custom model using flair embeddings. Can someone please look into it where i am getting wrong..

### ISSUE THREAD

**Issue by daamanmehta** [flairNLP/flair#1240]

**Comment by robertoptonova** [comment]
Might be related to my issue: https://github.com/zalandoresearch/flair/issues/1229#issue-509614892

**Comment by Solid7** [comment]
Might be related: https://github.com/zalandoresearch/flair/issues/1229#issue-509614892

**Comment by dmnmht** [comment]
@Solid7  thanks for the response.  Yes, #1299 (comment) it helps
