### ISSUE TITLE
Building wheel for dartsclone (setup.py) ... error during installation

### ISSUE THREAD

**Issue by avio11** [flairNLP/flair#1243]
During execution of command line "pip instal flair" installation was unsuccesfull and "Building wheel for dartsclone (setup.py) ... error" message appeared.

I tried installing the flair in an anaconda environment with python3.6.9 and pytorch version 1.3.0.

Below is an image of the command prompt showing the error:
![image](https://user-images.githubusercontent.com/38444874/67510015-95b2cc80-f66a-11e9-9f3b-14ab39c02f32.png)

Environment:
 - Ubuntu 18.04.3
 - python 3.6.9
 - pytorch 1.3.0

**Comment by sruefer** [comment]
I found a way to fix it, here are the steps (for Windows 10):

1) download the offline installer vs_buildtools.exe from the link on this page: https://www.scivision.dev/python-windows-visual-c-14-required/
2) Follow the installation instructions from this page: https://maofeichen.com/misc/2019/06/20/python-windows-cpp-14-required.html
3) Restart Windows
4) Run Anaconda prompt: pip install dartsclone
5) Install Pytorch
6) Install flair

I had no more installation errors like this and I could import flair on my test code.

**Comment by tsu3010** [comment]
Hi,
Facing this same issue on a Mac as well for Flair 0.4.4. Was previously on Flair 0.4.3 and ran into this error while trying to upgrade! Would be great to know if there is a fix for this.

**Comment by azikatti** [comment]
Facing the same issue on Mac for latest flair 0.4.4

**Comment by selinacho** [comment]
Same issue here

**Comment by yrinkel** [comment]
Same issue both on Windows 10 and MacOS Catalina, Flair 0.4.4

**Comment by mauriziodipierro** [comment]
hi ther! i'm facing the same issue on ubuntu 18.04

**Comment by klimentij** [comment]
same issue when trying to install in a container on Google Cloud Run

`  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I./csrc/include -I/usr/local/include/python3.7m -c dartsclone/_dartsclone.cpp -o build/temp.linux-x86_64-3.7/dartsclone/_dartsclone.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for dartsclone`

**Comment by klimentij** [comment]
`pip install flair==0.4.3` fixed the issue for me
