### ISSUE TITLE
 New TypeError with flair 0.4.4 in `token.embedding.numpy()`

### ISSUE THREAD

**Issue by khituras** [flairNLP/flair#1253]
Hi there,
by updating from flair 0.4.3 to 0.4.4 I get an issue when retrieving the numpy array of the token embeddings. My code looks as follows:

    sentence = Sentence("some text")
    tagger.predict(sentence, embedding_storage_mode = embeddingStorageMode)
    for i, token in enumerate(sentence.tokens):
                 embeddings.append((sid, i+1, token.embedding.numpy()))

The `token.embedding.numpy()` part causes the error `TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.` with flair 0.4.4. It doesn't with 0.4.3. Following the advice and doing `token.embedding.cpu().numpy()` doesn't really help. The error would not be raised but instead the program would just hang and not continue.

Did you change the embedding representation somehow and do you have a hint how I could retrieve the array without this issue? I just want the embeddings as some array, I don't really care what the underlying data structure is.

Thanks!

**Comment by alanakbik** [comment]
@khituras thanks for reporting this. I am seeing some curious behavior for this code if execute on a machine with CUDA: 

```python
tagger: SequenceTagger = SequenceTagger.load('ner')
sentence = Sentence("some text")
tagger.predict(sentence, embedding_storage_mode = 'cpu')
for i, token in enumerate(sentence.tokens):
    print(token.embedding.device)
```

It's printing `cuda:0` as device, even though this code should give us CPU embeddings. I have to check up on this.

**Comment by alanakbik** [comment]
Update: The output is correct according to our new logic. The embeddings only get stored on CPU memory, but when we request them using `token.embedding`, it automatically gets put on CUDA if available. 

This code works for me: 

```python
tagger: SequenceTagger = SequenceTagger.load('ner')
sentence = Sentence("some text")
tagger.predict(sentence, embedding_storage_mode = 'cpu')
for i, token in enumerate(sentence.tokens):
    print(token.embedding.cpu().numpy())
```

**Comment by khituras** [comment]
Thank you for looking into this. I realized that the issue with the hanging is not in the flair part. When I run your code, I get the following message:
`You are inferring on GPU with parameter 'embedding_storage_mode' set to 'cpu'.This option will slow down your inference, usually 'none' (default value) is a better choice.`

This is the reason why my application hangs: It reads flair output on stdin and does not expect this output. Is there a possibility to suppress it? Thanks!
