### ISSUE TITLE
Spanish CoNLL-2002 official results

### ISSUE THREAD

**Issue by aconneau** [flairNLP/flair#1255]
What is the official result of Flair on the Spanish CoNLL-2002 dataset?
Couldn't find it [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md#conll-03-named-entity-recognition-german).

Thank you!
Alexis

**Comment by alanakbik** [comment]
Hi @aconneau we haven't done experiments on Spanish CoNLL-02, but would be happy to post numbers if someone in the community does the experiments!

**Comment by stefan-it** [comment]
@aconneau I'll add the results in my [experiments](https://github.com/stefan-it/flair-experiments) the next days.

I already did some experiments with the recently added NER fine-tuning code in 🤗/Transformers, see them [here](https://github.com/stefan-it/fine-tuned-berts-seq#spanish) :)

**Comment by stefan-it** [comment]
@aconneau without hyper-parameter tuning and using the default parameters (as used in the English CoNLL training example):

| Embeddings | Run 1 | Run 2 | Run 3 | Run 4 | Run 5 | Avg.
| -- | -- | -- | -- | -- | -- | --
| Flair Embeddings (Test) | 85.1 | 86.21 | 86.44 | 86.41 | 85.92 | 86.016
| Word Embeddings + Flair Embeddings (Test) | 86.8 | 87.52 | 87.63 | 87.29 | 87.7 | 87.388

**Comment by stefan-it** [comment]
Btw: just found your ["Unsupervised Cross-lingual Representation Learning at Scale"](https://arxiv.org/abs/1911.02116) paper - really great work, I'm excited to integrate XLM-R in Flair!
