### ISSUE TITLE
Weight the embeddings of a sentence with TF IDF

### ISSUE THREAD

**Issue by robinalexandre** [flairNLP/flair#1263]
Hi there,

First, thanks for your library!

I am trying to use Flair for Question-Answering task, and to improve my results, I would like to weight the embeddings thanks to the TFIDF. Right now, some words are just like "useless" but are still incorporate in the embeddings of a sentence. I would like to know if there is a way to include the TFIDF in the computational of the sentence embeddings and if not, how can I achieve that?

Thanks a lot,
Alex

**Comment by alanakbik** [comment]
Hello @robinalexandre we currently don't support this in Flair, but would welcome a code contribution :) Something like this could be supported in a dedicated `DocumentEmbeddings` class.
