### ISSUE TITLE
Output size of ELMo document embeddings

### ISSUE THREAD

**Issue by hannesjansson** [flairNLP/flair#1265]
When running the medium size ELMo embeddings I get the output size 1536 per token. Why is that? 

According to https://allennlp.org/elmo the output size should be 256 per embedding. I understand ELMo outputs three vectors and that you concatenate these. Then the output size should be 3*256=768. What am I missing?

**Comment by stefan-it** [comment]
Hi @hannesjansson ,

I think that's because the output of the 2 ELMo layers is concatenated, but at the moment I can't find the corresponding code snippet in `allennlp` library (we just pass weights and option file to the ELMO api). I'll investigate that further and report back here.
