### ISSUE TITLE
AttributeError using de-offensive-language 

### ISSUE THREAD

**Issue by lisaran** [flairNLP/flair#1272]
I tried to use the TextClassifier with '_de-offensive-language_':

```
classifier = TextClassifier.load('de-offensive-language')

sentence = Sentence('Das gefällt mir nicht.')

# predict has a Bug
classifier.predict(sentence)

```
I get the following Error:en-sentiment
```
....
  File "<...>/python3.7/site-packages/flair/embeddings.py", line 518, in _add_embeddings_internal
    if self.field == "text":
  File "<...>/python3.7/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'OneHotEmbeddings' object has no attribute 'field'
```
Any ideas how to fix this? With _en-sentiment_ it works fine.

Thanks for your help.

**Comment by lisaran** [comment]
The following fix helped:
`# predict has a Bug
classifier.document_embeddings.embeddings._modules['list_embedding_0'].field = "text"
classifier.predict(sentence)`

It seems that in flair 0.4.4 _OneHotEmbeddings_ have an attribute _field_ which is missing in the pretrained model.

**Comment by matip** [comment]
I can confirm that the bug still exists in flair 0.6.0 - luckily the fix still works, too

**Comment by alanakbik** [comment]
@lisaran and @matip thanks for reporting this and sorry for the delay. I'll put in a PR to fix this shortly!
