### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'corpus' while loading checkpoint

### ISSUE THREAD

**Issue by anuragkumar95** [flairNLP/flair#1278]
This bug comes up while loading an old checkpoint. Below is the whole trace
I1118 13:18:59.126918 139740913571648 file_utils.py:39] PyTorch version 1.3.1 available.
I1118 13:18:59.150430 139740913571648 modeling_xlnet.py:194] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
2019-11-18 13:18:59,205 read text file with 80675 lines
2019-11-18 13:19:46,619 read text file with 100000 lines
Traceback (most recent call last):
  File "LanguageModel.py", line 41, in <module>
    trainer = ModelTrainer.load_checkpoint(checkpoint, corpus)
  File "/home/anurag/anaconda3/lib/python3.7/site-packages/flair/trainers/trainer.py", line 562, in load_checkpoint
    model.corpus = corpus
AttributeError: 'dict' object has no attribute 'corpus'

I trained a language model. This happens after I load an old saved checkpoint.
I am using Ubuntu 18.04
Flair version- 0.4.4

I think this error is related to this: https://github.com/zalandoresearch/flair/issues/1087

**Comment by lucaventurini** [comment]
I can confirm this, but I'm not sure it's about loading an *old* checkpoint.

In my case, the error occurs while loading a "final-model.pt", while I can correctly load a "checkpoint.pt" from the same training, made with v0.4.4.

Maybe we can't resume training from a final model? @alanakbik

**Comment by sohna03** [comment]
Hi @anuragkumar95, were you able to find a solution to this? Running into the exact same problem.

**Comment by alanakbik** [comment]
@sohna03 can you give more details on this error and paste an example script?

**Comment by sohna03** [comment]
Example script:

`from flair.trainers import ModelTrainer
trainer = ModelTrainer.load_checkpoint('best-model.pt', corpus)

# trainer = ModelTrainer(classifier, corpus)

# 7. start the training
trainer.train(TRAIN_DIR,
              learning_rate=0.001,
              mini_batch_size=4,
              anneal_factor=0.5,
              patience=2,
              max_epochs=40,
              checkpoint=True) `


Error: 
Traceback (most recent call last):
  File "social_media_RoBERTa.py", line 120, in <module>
    trainer = ModelTrainer.load_checkpoint('best-model.pt', corpus)
  File "/data/python/anaconda3/envs/roberta_env/lib/python3.6/site-packages/flair/trainers/trainer.py", line 579, in load_checkpoint
    model.corpus = corpus
AttributeError: 'dict' object has no attribute 'corpus'

**Comment by djstrong** [comment]
Has `best-model.pt` checkpoint data or it is only a model?

**Comment by sohna03** [comment]
Ahh you got it. However, I can't seem to find the checkpoint.pt file after training a sentence classifier. Do you know how I can output the checkpoint.pt files during training?

**Comment by djstrong** [comment]
Probably, there is no sense for checkpoint when training have finished correctly. 
`train(checkpoint=True)`
