### ISSUE TITLE
Training on NER using BERT embeddings

### ISSUE THREAD

**Issue by krsrv** [flairNLP/flair#1279]
When I use BERT embeddings training a flair model on a custom NER dataset, is the model trained end-to-end, i.e., does it include fine-tuning the BERT embeddings as well? And which layers of BERT are used in the model?

**Comment by djstrong** [comment]
No, BERT embeddings are not fine-tuned. Default is to take last 4 layers of BERT.

**Comment by stefan-it** [comment]
Hi @krsrv ,

at the moment you can use the awesome Hugging Face implementation for NER fine-tuning:

https://github.com/huggingface/transformers/tree/master/examples/ner

After fine-tuning a model, you can directly load it into Flair :)

**Comment by alanakbik** [comment]
We are also preparing a PR that will allow fine-tuning of transformers both for classification and sequence labeling to happen through Flair. We're testing it currently but it should be added soon.

**Comment by djstrong** [comment]
Handling more than 512 subtokens would be helpful (at least for prediction).

**Comment by alanakbik** [comment]
Fine tuning was added in Flair 0.5, and support for longer sequences in transformers in 0.5.1.
