### ISSUE TITLE
Loading A GPU trained tagger on a CPU - triggers an assertion error

### ISSUE THREAD

**Issue by xijianlim** [flairNLP/flair#1283]
I've trained a SequenceTagger model on google colab's GPU runtime ( obviously to save alot of time). When loading the saved-gpu-based model onto a CPU device, im getting this assertion error:

_AssertionError: Torch not compiled with CUDA enabled_

Ive tried using the following work arounds to see if flair will read on CPU:

_import flair, torch
flair.device = torch.device('cpu')_

To no avail. Is there a work around on this?

**Comment by stefan-it** [comment]
Hi @xijianlim ,

is this error still up-to-date? I would recommend using the latest version of PyTorch :)
