### ISSUE TITLE
Train , Test , Validation cross validation split

### ISSUE THREAD

**Issue by OguzKircicek** [flairNLP/flair#1284]
A clear and concise description of what you want to know.
Hi  @alanakbik  

I want to train , test and validation cross validation split my data but didn't see documentation. What a path ?

**Comment by OguzKircicek** [comment]
Ok. I found. 

I analyzed source code. 

train_length = len(train)
            dev_size: int = round(train_length / 10)
            splits = random_split(train, [train_length - dev_size, dev_size])
            train = splits[0]
            dev = splits[1]

**Comment by myeghaneh** [comment]
> Ok. I found.
> 
> I analyzed source code.
> 
> train_length = len(train)
> dev_size: int = round(train_length / 10)
> splits = random_split(train, [train_length - dev_size, dev_size])
> train = splits[0]
> dev = splits[1]

can you elaborate your response, I still do not know how to do cross-validation using flair ?
