### ISSUE TITLE
How can I know the download link about the pre-embedding files directly?

### ISSUE THREAD

**Issue by BUGwf** [flairNLP/flair#1286]
I want to download the ebeddings firstly and then reload it  again.But I just can know the link by the information of network connection error,So Can you tell me the download link of the embedding files?Thank you!

**Comment by stefan-it** [comment]
Hi @BUGwf ,

you can find the S3 links for the Flair Embeddings here:

https://github.com/flairNLP/flair/blob/master/flair/embeddings.py#L1856
