### ISSUE TITLE
Is there a way to train your model on two GPUs (in case gpu 0 runs out of memory,we could use gpu 1)?

### ISSUE THREAD

**Issue by Nabeelhasan** [flairNLP/flair#1287]
I am training a NER model on a 60 MB dataset using bertEmbeddings and FLairEmbeddings,when i train this model my gpu memory increases exponentially and eventually my gpu runs out of memory and i get the error CUDA OUT OF MEMORY TRIED TO ALLOCATE 71 MB............ I have two GPUs in my system,i want to know if there exist a way to use the second GPU i,e gpu 1 if gpu 0 runs out of memory. 
To get rid of this error i tried to reduce the batch size to 8 and set embeddings_in_memory to False and i had almost completed one Epoch with these changes but in the 9th iteration i got an error that said cuda out of memory. 
All sort of recommendations are welcomed.

**Comment by lucaventurini** [comment]
Hi, maybe you can try reducing further the mini_batch_chunk_size, see #1138 .

Also, in latest version you have to set the parameter embedding_storage_mode (#891), not embeddings_in_memory.

**Comment by Nabeelhasan** [comment]
Hi luca, i am training my model on a smaller dataset now and it is working well so far.
And i tried to use embedding_storage_mode with the trainer method but it threw an errorr saying No attribute named embedding_storage_mode while embeddings_in_memory worked fine.I think it is an issue with the documentation. Thanks for helping :)
