### ISSUE TITLE
ColumnCorpus and labels

### ISSUE THREAD

**Issue by antgr** [flairNLP/flair#1288]
Hi,
I have two related questions:

1) I have a dataset that has the following format:
(for sequence labeling)
```
I	O	O	N	a: 1	Sent: 1	Doc: 001
am	O	O	N	a: 1	Sent: 1	Doc: 001
```
I want to use a subset of the columns as labels for my training.
I defined 
```columns = {0: 'text', 1: 'A', 2: 'B', 3: 'C', 4: 'D', 5: 'E', 6: 'F'}```
I also defined
```
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt')
```
but when I call
```print(corpus.train[0].to_tagged_string('A'))```,
 I do not see any tagging. I see only the sentence, and not any tagging.
What I understand is that by tagging we mean the labels for each word in the sentence.

2) Also, even if the above was working, how could I separate text from labels? For example if I would like to build my custom SequenceTagger, I would like to handle separately the text and the labels.
 Is the above struct Corpus only for using it with flairs classes, as the SequenceTagger?

To give you more context, what I would like to test, is to use embeddings from flair, and then build a regular pytorch model (maybe as a next step I would also like to extend a flair abstract class to build my custom Sequence Tagger).

Could you help me with my questions? Thanks a lot!

**Comment by stefan-it** [comment]
Hi @antgr ,

the dataset format should be correct for the `ColumnCorpus` class.

Here you can find a complete example for training a model for sequence tagging. You just need to replace the `corpus` instance.

Another change: try to use `tag_type = "A" if you want to use this field for label information.

I hope this helps!
