### ISSUE TITLE
.vec extension word embedding 

### ISSUE THREAD

**Issue by OguzKircicek** [flairNLP/flair#1290]
Hi, 

I have a word embedding .vec extension but it's not import. This method using : WordEmbeddings(example.vec)  , I read .bin extension format but I didn't .vec extension format.

**Comment by stefan-it** [comment]
Hi @OguzKircicek ,

could you try this workaround here:

https://github.com/flairNLP/flair/pull/682#issuecomment-487033416

Does this help to load the word embeddings?
