### ISSUE TITLE
encoding error while loading WIKINER_RUSSIAN

### ISSUE THREAD

**Issue by santoshboina** [flairNLP/flair#1291]
I am trying to load russian NER labelled data 'WIKINER_RUSSIAN' into Flair.
But getting some encoding error during loading.
My System spec:
Flair: 0.4.3
Python: 3.8.0

![image](https://user-images.githubusercontent.com/13539449/69625081-dc318780-106b-11ea-8060-cf841ae795d4.png)

**Comment by stefan-it** [comment]
Hi @santoshboina ,

could you try to use the latest version from `master` 🤔

I got it running with:

```python
In [2]: ru_corpus = flair.datasets.WIKINER_RUSSIAN()                                                                                                                                                                                                                                                          
2019-11-26 12:20:11,585 https://raw.githubusercontent.com/dice-group/FOX/master/input/Wikiner/aij-wikiner-ru-wp3.bz2 not found in cache, downloading to /tmp/tmpsxh4xad0
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7856559/7856559 [00:00<00:00, 54409426.05B/s]
2019-11-26 12:20:11,778 copying /tmp/tmpsxh4xad0 to cache at /home/stefan/.flair/datasets/wikiner_russian/aij-wikiner-ru-wp3.bz2
2019-11-26 12:20:11,784 removing temp file /tmp/tmpsxh4xad0
2019-11-26 12:20:16,692 Reading data from /home/stefan/.flair/datasets/wikiner_russian
2019-11-26 12:20:16,692 Train: /home/stefan/.flair/datasets/wikiner_russian/aij-wikiner-ru-wp3.train
2019-11-26 12:20:16,692 Dev: None
2019-11-26 12:20:16,692 Test: None
```

If that's not working, I guess it has something to do with encoding on Windows. Maybe we need to add utf-8 explict. as input encoding in the dataset reader...

**Comment by santoshboina** [comment]
I have tried installing latest version but I am follwing issue:
![image](https://user-images.githubusercontent.com/13539449/69626929-a1315300-106f-11ea-8349-4944291d15d9.png)

**Comment by stefan-it** [comment]
I think you need to update your PyTorch version to at least 1.2 (related to this [issue](https://github.com/zalandoresearch/flair/issues/1236)) :)

**Comment by santoshboina** [comment]
Yes ,using PyTorch 1.3 and Flair 0.4.4. But still I am facing encoding issue while loading WIKINER_RUSSIAN dataset

**Comment by ziavra** [comment]
@stefan-it 
i got the same error on windows.
flair: 0.5
torch: 1.5.0+cpu

yes, adding explicit encoding in `_download_wikiner` fixed this issue
```python
with bz_file as f, open(
....
encoding="utf-8"
)
```
