### ISSUE TITLE
Question on Merging Corpus

### ISSUE THREAD

**Issue by lazysjb** [flairNLP/flair#1292]
I wanted to know if their is a util in Flair that lets it merge the `Corpus`.
For example, I might have labels from the original CoNLL03 file (in train / dev / test files) and have my own additional labels in separate file (in train / dev / test files). 
I guess I can merge the file itself and create a `Corpus` object, but I was wondering if I have 2 `ColumnCorpus` objects if there is a way to merge them easily.

Thank you!

**Comment by alanakbik** [comment]
Hi @lazysjb you could try using the `MultiCorpus` object. Essentially, you load your two corpora and then pass them to the `MultiCorpus` to use them as a single one. You can find documentation [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#the-multicorpus-object).
