### ISSUE TITLE
Are the embedding models trainable or not ?

### ISSUE THREAD

**Issue by PradyumnaGupta** [flairNLP/flair#1302]
According to other issues that I read regarding whether the transformer embedding models available are trainable or not, it has been informed that the transformer architectures like bert,xlnet etc. are not trainable. But if I print the number of parameters with requires_grad=True corresponding to the tagger model with BertEmbeddings then 125757484 parameters show up? Please explain this !!

```
from flair.data import Corpus
from flair.datasets import WNUT_17
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings,BertEmbeddings
from typing import List

corpus: Corpus = WNUT_17().downsample(0.1)
tag_type = 'ner'
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
embedding_types: List[TokenEmbeddings] = [
    BertEmbeddings(),
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)


from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)
count_parameters(tagger)
```

Output-

`125757484`

**Environment:**
Google Colab

**Comment by djstrong** [comment]
In methods `_add_embeddings_internal` there is `with torch.no_grad():`, so it is stated dynamically.
The trainable parameters count method is not reliable in this case.

**Comment by falcaopetri** [comment]
I was also trying to estimate the number of trainable parameters, and I lost some time trying to understand the huge value I was getting. Then I found this issue.

Is the info about this dynamically set no_grad documented somewhere? 
And is there any reliable way to calculate the number of trainable parameters?

**Comment by teoML** [comment]
@djstrong , @falcaopetri  I also need to estimate the parameters only of the sequence tagger - how to do it? I could not understand how to do it reading this discussion.

**Comment by falcaopetri** [comment]
@teoML, if I remember correctly, I ended up using [model.named_parameters()](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.named_parameters) to print the name and the size of each parameter/layer. I didn't need to know exactly the number of parameters, so I did a manual check and added up only those parameters that where probably trainable.

Probably something like this (I haven't checked this snippet), and then manually adding some of the param sizes.
```python
for name, param in model.named_parameters():
  if param.requires_grad:
    print(name, param.numel())
```

But I agree that there should be a straightforward way to get the correct number of trainable parameters.

**Comment by djstrong** [comment]
@falcaopetri That's the easiest solution.
@teoML You can count all parameters for SequenceTagger and subtract all parameters of Embeddings.

**Comment by teoML** [comment]
@djstrong  how to count all the parameters for SequenceTagger ? Do you mean manually?

**Comment by djstrong** [comment]
No
