### ISSUE TITLE
GPT 2 subwords mapping 

### ISSUE THREAD

**Issue by isarth** [flairNLP/flair#1305]
While` running GPT2 default Embeddings, the name of the model while printing comes out as "0-gpt2-medium" which goes then uses  **_build_token_subwords_mapping** and not **_build_token_subwords_mapping_gpt2** function in embeddings.py file. Isn't this a bug?

Because of this:
`               if "gpt2" in name or "roberta" in name:
                        token_subwords_mapping = _build_token_subwords_mapping_gpt2(
                        sentence=sentence, tokenizer=tokenizer
                ) `
           ` else:
                       token_subwords_mapping = _build_token_subwords_mapping(
                       sentence=sentence, tokenizer=tokenizer
                )`
with GPT2Embeddings() --> name == "0-gpt2-medium" so it goes into else condition

**Comment by stefan-it** [comment]
Hi @isarth , I tested that locally (using the latest `master` version of Flair) and the `gpt2` function is used. However, I think this issue is related to https://github.com/zalandoresearch/flair/issues/1221.

I'm working on that (but due to upcoming ACL deadline, it can be delayed) 😅
