### ISSUE TITLE
Error with transformers 2.2.0

### ISSUE THREAD

**Issue by lucaventurini** [flairNLP/flair#1306]
**Describe the bug**
Function predict raises the following exception with transformers 2.2.0, on a model with bert embeddings. With previous transformers version everything is fine.

```python
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 200, in predict
    scores = self.forward(batch)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 82, in forward
    self.document_embeddings.embed(sentences)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 90, in embed
    self._add_embeddings_internal(sentences)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 2701, in _add_embeddings_internal
    self.embeddings.embed(sentences)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 171, in embed
    embedding.embed(sentences)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 90, in embed
    self._add_embeddings_internal(sentences)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 2109, in _add_embeddings_internal
    all_encoder_layers = self.model(all_input_ids, attention_mask=all_input_masks)[
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in call
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/modeling_bert.py", line 673, in forward
    if self.config.is_decoder:
AttributeError: 'BertConfig' object has no attribute 'is_decoder'
```

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux
 - Version: flair 0.4.4

**Comment by stefan-it** [comment]
Hi @lucaventurini, could you provide a code snippet for reproducing that error 🤔 I'll check it then :)

**Comment by lucaventurini** [comment]
Hi @stefan-it , thank you for your reply.

The following code:

```python
from flair.data import Sentence
from flair.models import TextClassifier

flair_model = "final-model.pt"

classifier_loaded = TextClassifier.load(flair_model)

sentences = [Sentence(sent, use_tokenizer=True) for sent in ["Hi!"]]

classifier_loaded.predict(sentences)
```
should fail if you try to load a model trained with bert embeddings (which I hope you have, I don't have one to share).

The traceback is:
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-5-414e0ebac4ba> in <module>()
      8 sentences = [Sentence(sent, use_tokenizer=True) for sent in ["Hi!"]]
      9 
---> 10 classifier_loaded.predict(sentences)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/models/text_classification_model.py in predict(self, sentences, mini_batch_size, embedding_storage_mode, multi_class_prob, verbose, use_tokenizer)
    198                     continue
    199 
--> 200                 scores = self.forward(batch)
    201                 predicted_labels = self._obtain_labels(
    202                     scores, predict_prob=multi_class_prob

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/models/text_classification_model.py in forward(self, sentences)
     80     def forward(self, sentences) -> List[List[float]]:
     81 
---> 82         self.document_embeddings.embed(sentences)
     83 
     84         text_embedding_list = [

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py in embed(self, sentences)
     88 
     89         if not everything_embedded or not self.static_embeddings:
---> 90             self._add_embeddings_internal(sentences)
     91 
     92         return sentences

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py in _add_embeddings_internal(self, sentences)
   2699 
   2700         # embed words in the sentence
-> 2701         self.embeddings.embed(sentences)
   2702 
   2703         lengths: List[int] = [len(sentence.tokens) for sentence in sentences]

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py in embed(self, sentences, static_embeddings)
    169 
    170         for embedding in self.embeddings:
--> 171             embedding.embed(sentences)
    172 
    173     @property

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py in embed(self, sentences)
     88 
     89         if not everything_embedded or not self.static_embeddings:
---> 90             self._add_embeddings_internal(sentences)
     91 
     92         return sentences

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py in _add_embeddings_internal(self, sentences)
   2107         self.model.to(flair.device)
   2108         self.model.eval()
-> 2109         all_encoder_layers = self.model(all_input_ids, attention_mask=all_input_masks)[
   2110             -1
   2111         ]

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

~/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask)
    673         # - if the model is an encoder, make the mask broadcastable to [batch_size, num_heads, seq_length, seq_length]
    674         if attention_mask.dim() == 2:
--> 675             if self.config.is_decoder:
    676                 batch_size, seq_length = input_shape
    677                 seq_ids = torch.arange(seq_length, device=device)

AttributeError: 'BertConfig' object has no attribute 'is_decoder'
```

**Comment by amitpatel7351382949** [comment]
i tried one of the older version of transformers and it worked...
but i don't remember that version....
please let us know if somebody tries...

**Comment by agusgun** [comment]
Installing `transformers==2.0.0` works for me

**Comment by nullphantom** [comment]
> **Describe the bug**
> Function predict raises the following exception with transformers 2.2.0, on a model with bert embeddings. With previous transformers version everything is fine.
> 
> ```python
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 200, in predict
>     scores = self.forward(batch)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/models/text_classification_model.py", line 82, in forward
>     self.document_embeddings.embed(sentences)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 90, in embed
>     self._add_embeddings_internal(sentences)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 2701, in _add_embeddings_internal
>     self.embeddings.embed(sentences)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 171, in embed
>     embedding.embed(sentences)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 90, in embed
>     self._add_embeddings_internal(sentences)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/flair/embeddings.py", line 2109, in _add_embeddings_internal
>     all_encoder_layers = self.model(all_input_ids, attention_mask=all_input_masks)[
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in call
>     result = self.forward(*input, **kwargs)
>   File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/transformers/modeling_bert.py", line 673, in forward
>     if self.config.is_decoder:
> AttributeError: 'BertConfig' object has no attribute 'is_decoder'
> ```
> 
> **Environment (please complete the following information):**
> 
> * OS [e.g. iOS, Linux]: Linux
> * Version: flair 0.4.4

Hi, are you still facing this issue?
try to downgrade the transformers to v2.0.0

**Comment by sohna03** [comment]
Hi, when I downgrade to transformers v2.0.0, and replicating @lucaventurini's code, I receive the following error. Are there any workarounds besides downgrading?

`     22 from torch.nn import TransformerEncoderLayer, TransformerEncoder
     23 
---> 24 from transformers import (
     25     AlbertTokenizer,
     26     AlbertModel,

ImportError: cannot import name 'AlbertTokenizer'`
