### ISSUE TITLE
Are NER models thread safe?

### ISSUE THREAD

**Issue by edsvisinditus** [flairNLP/flair#1307]
Hi,

Is it safe to use the same instantiation of a model to tag text in multiple threads at the same time?

If I for example create an instance of the SequenceTagger like this:
tagger = SequenceTagger.load('ner')

Can I then safely run the following code in multiple threads at the same time?:
tagger.predict(... some text ...)

Thank you in advance.

**Comment by severinsimmler** [comment]
I'd say this depends on _how_ you use multiple threads in Python. If you use the `threading` module, then yes, I think you can predict in multiple threads, if you use `multiprocessing`, then no, because multiple processes do not share the same memory, i. e. each process must load the model.
