### ISSUE TITLE
outsourcing embeddings to sqlite database at inference stage?

### ISSUE THREAD

**Issue by timnon** [flairNLP/flair#1309]
Deploying e.g. the `multi-ner-fast`-model easily eats up some gig of memory just for one process. Most of this memory is probably used to hold the word embeddings of the underlying pytorch model. Has there been some thinking about outsourcing this to e.g. an sqlite database (or maybe this is already possible?). Similar to what is done in the python package magnitude. Since the inference takes anyway a few seconds, looking up some word vectors from an indexed database wouldnt add much to the inference time, but would decrease the memory consumption to almost nothing. Also, multiple processes could share the database (maybe then not a sqlite).

**Comment by Hellisotherpeople** [comment]
This would be excellent as magnitude does inference faster than Flair due to the internal sqlite database representation.

**Comment by timnon** [comment]
Just found a little problem in this approach: the e.g. NER-tagger in flair is heavily based on its own embedding, which are context-sensitive on a character-level, and so not just lookups of word vectors. These seem to be the ones that make the NER-tagger work so well (compared to other ones). So i basically stopped this approach. It would be interesting to see how a NER-tagger which only uses word lookups performs in comparison (basically the old standard), need to check if there is such a flair-model. In this case, building on the following snippet would allow to simply replace the `.embbedings`-attribute of a tagger with some external storage in a db:
```
from flair.models import SequenceTagger
import sqlite3
from tqdm import tqdm

class DbEmbedding():
    def __init__(self,filename='tmp.db'):
        db = sqlite3.connect(filename)
        self.db = db
    def load(self,embedding,table='embedding'):
        db = self.db
        k = embedding.vector_size
        vocab = list(embedding.vocab.keys())
        db.execute(f"DROP TABLE IF EXISTS {table};")
        db.execute(f"CREATE TABLE {table}(word text,{','.join('v'+str(i)+' float' for i in range(k))});")
        vectors_it = ( [word]+embedding.get_vector(word).tolist() for word in vocab )
        db.executemany(f"INSERT INTO {table}(word,{','.join('v'+str(i) for i in range(k))}) \
        values ({','.join(['?']*(1+k))})", tqdm(vectors_it))
        db.execute(f"CREATE INDEX {table}index ON {table}(word);")
        db.commit()
        return self
    def get_vector(self,word='house'):
        db = self.db
        cursor = db.cursor()
        cursor.execute(f"SELECT * FROM embedding WHERE word='{word}';")
        return list(cursor)

tagger = SequenceTagger.load('multi-ner-fast')
embeds = tagger.embeddings.embeddings

db_embeds = list()
for i,embed in enumerate(embeds[:2]):
    print(embed)
    db_embed = DbEmbedding().load(embed.precomputed_word_embeddings,table=f'embedding_{i}')
    db_embeds.append(db_embed)
```

**Comment by timnon** [comment]
Tested with `multi-ner-fast`, and the memory consumption goes down from 5gig to 700mb when only removing the WordEmbeddings! here is some project to follow this idea: https://github.com/timnon/flair-db-word-embeddings

The goal is to include this directly in flair, any advice where to put such a postprocessing utility function is welcome!

**Comment by alanakbik** [comment]
This feature was added to Flair in #1315
