### ISSUE TITLE
Is there a way to use bert embeddings in text classification?

### ISSUE THREAD

**Issue by murhafh** [flairNLP/flair#1310]
Is it possible to use bert-embeddings to generate a document embeddings and train a text classifier? 

I have the following that works with regular word embeddings:

```
word_embeddings = [WordEmbeddings('glove')]


document_embeddings = DocumentRNNEmbeddings(
    word_embeddings,
    hidden_size=512,
    reproject_words=True,
    reproject_words_dimension=256,
    rnn_type= 'LSTM'
)
```

But if change the word_embeddings to use BertEmbeddings I get a runtime error 
`Token indices sequence length is longer than the specified maximum sequence length for this model`

**Comment by DecentMakeover** [comment]
correct me if i'm wrong , but instead of `word_embeddings = [WordEmbeddings('glove')]` if you pass `word_embeddings = [BertEmbeddings()]` should work fine

**Comment by severinsimmler** [comment]
BERT is, other than classic word embeddings, restricted to a maximum input sequence of 512 tokens. This means you are not able to process documents longer than 512 tokens _by design_. You have to segment your documents into appropriate chunks to use BERT embeddings.
