### ISSUE TITLE
Multi-label classification: Better way of adding label-less sentences to training data

### ISSUE THREAD

**Issue by MichaelHintz** [flairNLP/flair#1313]
Hi, 
In one of our multi-label classification use cases, we have data points that should not receive a label at all.

Our training data might look as follows:
```
__label__A __label__B Text1
__label__C Text2
Text3
__label__A Text4
Text5
```
Flair currently skips lines not beginning with \_\_label\_\_, so we are adding a dummy label to line 3 and 5:
```
__label__A __label__B Text1
__label__C Text2
__label__Dummy Text3
__label__A Text4
__label__Dummy Text5
```
This way, Text3 and Text5 are considered as well for training and the classification results are very good already.

However, I see 2 issues with this:
1. The criteria for no label/dummy label are quite easy, so the dummy label gets a high f1-score, which inflates the overall f1-score for the model.
2. The performance of assigning the Dummy label influences the training process. This does not seem right to me. We are only interested in the models performance on labels A,B,C.

To solve this, I just removed https://github.com/zalandoresearch/flair/blob/2d6e89bdfe05644b4e5c7e8327f6ecc6b834ec9e/flair/datasets.py#L1111-L1114
and changed https://github.com/zalandoresearch/flair/blob/2d6e89bdfe05644b4e5c7e8327f6ecc6b834ec9e/flair/datasets.py#L1151 to 

```
if text:
```

At least for our data, this is working without any issues and for our most important category, the f1-score increased by 1.5pp 

I would assume the constraints that I removed were added for a reason, but if some stable solution for this could be found, that would be great

**Comment by alanakbik** [comment]
Hi @MichaelHintz sorry for not responding earlier. This makes sense - care to do a PR for this?
