### ISSUE TITLE
lemmatization with Flair

### ISSUE THREAD

**Issue by mariaBio** [flairNLP/flair#1319]
Dear flair developers!

First of all, thank you so much for making such a useful and powerful tool available!

I would like to ask please if there is a way to lemmatise a corpus using one of your pre-trained models (e.g., French, Dutch, multi-ling). 

Thank you very much for your help!
Maria

**Comment by pommedeterresautee** [comment]
If you want to perform some task with Flair (like classif or NER) you don't need to lemmatize first, LM kind of learn the meaning of words... So what you ask is not possible and not needed for tasks when using a LM.

**Comment by mariaBio** [comment]
Thank you very much for your reply!
I actually wanted the step as a pre-processing for another task, such as topic modelling, where the vocabulary reduction could be handy. But thank you again!

**Comment by pommedeterresautee** [comment]
Ok, if you are doing LDA stuff, clearly Flair and LM in general won’t help.
Better to check spacy which implements those things.

**Comment by mariaBio** [comment]
Thank you! Yes, that's what I planned to do - just checked if Flair would be an alternative due to its better performance in POS and NER. Thank you again for your feedback!
