### ISSUE TITLE
Extract hidden sequences and states from POS tagging? 

### ISSUE THREAD

**Issue by giuseppegambino** [flairNLP/flair#1324]
Hi community, 
My question is whether it is possible to extract the trained tensor from POS tagging for each phrase like ? 

I post a script to be clearer:
"""
from flair.models import SequenceTagger
from flair.embeddings import Sentence

tagger = SequenceTagger.load('pos')

sentence = Sentence('George Washington went to Washington .')

tagger.predict(sentence)

print(sentence.to_tagged_string())
"""
There is a way to do something like this?  "print(sentence.get_tensor)"  ?

The desired output should be the hidden states/sentences of the neural network used for your pos tagging model in a form of a tensor.

**Comment by rishab-32** [comment]
Hi, I have a similar query. Were you able to resolve this, if yes can you please help me by sharing the way to extract the tensor?

**Comment by stefan-it** [comment]
Hi @giuseppegambino ,

you could try to use the following code:

```python
for token in sentence.tokens:
  print(token.embedding)
```

That will return the embedding for each token in your sentence.
