### ISSUE TITLE
Create corpus from offset annotated data

### ISSUE THREAD

**Issue by RonRademaker** [flairNLP/flair#1331]
Hello, I have an annotated dataset for named entity recognition that has been annotated using offsets, for example:

Text: `New year start on January 1st`
Annotation: `type: DATE, start: 18, end: 29` (= January 1st)

How do I load this in a Corpus for custom training? My texts are not tokenized.

**Comment by djstrong** [comment]
You can load texts to Flair (`Sentence`) and then find annotated tokens and label them (`Token.add_tag`) or prepare tokenized NER like format.

**Comment by RonRademaker** [comment]
Thanks!
