### ISSUE TITLE
UnboundLocalError: local variable 'token' referenced before assignment

### ISSUE THREAD

**Issue by somumu** [flairNLP/flair#1338]
Hello, I am working on flair and trying to train custom text classification model. I had trained it on a dataset and it worked fine but when i use the same code for training on another dataset(twitter dataset) it gives me 'UnboundLocalError: local variable 'token' referenced before assignment' .

corpus = NLPTaskDataFetcher.load_classification_corpus(Path('./'), test_file='twittr_test.csv', dev_file='twittr_dev.csv', train_file='twittr_train.csv')

I am getting error in running above line of code.

Any help would be appreciated, thank you.

**Comment by alanakbik** [comment]
Hi @somumu is your corpus correctly formatted? The `NLPTaskDataFetcher` is deprecated, you should use `flair.datasets` instead. In particular, if your training data is in CSV format, you should use the `CSVClassificationCorpus`. 

Check out [this tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset) for more information on how to load CSV files.

**Comment by somumu** [comment]
Thank you , problem solved by using CSVClassificationCorpus.

**Comment by alanakbik** [comment]
Great!
