### ISSUE TITLE
How to get sentence representation from bert/albert

### ISSUE THREAD

**Issue by omerarshad** [flairNLP/flair#1343]
Bert/Albert gives token embeddings. How to get sentence embedding without using flair's document embedding. How to get actual sentence embedding from bert output?

**Comment by stefan-it** [comment]
Hi @omerarshad ,

if you don't want to use the Document embedding class from Flair, you could e.g. use the [Sentence Embeddings](https://github.com/UKPLab/sentence-transformers) repo.

It does support various Tranformer-based models to create sentence embeddings :)

**Comment by alanakbik** [comment]
@stefan-it thanks for the link, very interesting project. Perhaps we could also expose these models through Flair by creating DocumentEmbeddings classes for them.

**Comment by omerarshad** [comment]
@alanakbik  Thanks, i am already using that.

**Comment by alanakbik** [comment]
Sentence transformers was added in Flair. 0.5.1!
