### ISSUE TITLE
Prioritizing classes and precission/recall for sequence tagger

### ISSUE THREAD

**Issue by klasocki** [flairNLP/flair#1344]
Following @apohllo 's idea, I implemented two ways of prioritizing precission/recall during training

- Using [F-beta ](http://www.marcelonet.com/snippets/machine-learning/evaluation-metrix/f-beta-score) as the evaluation metric, has impact on logging and annealing schedule

- Adding class weights to cross-entropy loss, enabling class prioritization (e.g less weight to errors on 'O' tag if we want more recall). Works only if using standard loss - no CRF

I'll submit a pull request in case you'd want to include these changes in your library :)

**Comment by alanakbik** [comment]
New version of flair released that contains this feature - thanks again @klasocki!
