### ISSUE TITLE
Control sequence length

### ISSUE THREAD

**Issue by moh55m55** [flairNLP/flair#1346]
Thanks for the great repo. I am just wondering if it is possible to control the maximum sequence length when using document or sentence embeddings. I did not find it in the docs. 
Thanks

**Comment by alanakbik** [comment]
@moh55m55 good point and something we should add to the docs. In general, maximum sequence length mostly depends on the word embeddings you use. If you use any of the transformer embeddings (BERT, ALBERT etc.), there is a hard maximum length of 512 subtokens (each word will automatically be split into one or multiple subtokens). 

For all other embeddings, including `FlairEmbeddings`, there is no hard maximum. Especially the non-contextualized embeddings such as `WordEmbeddings` or `BytePairEmbeddings` scale to infinite lengths. `FlairEmbeddings` in particular were built to scale to arbitrarily long sequences (by internally chunking overlong sequences), but if you use GPU, the limit is GPU memory in that the whole embedded sequence must fit into memory.

**Comment by moh55m55** [comment]
Thanks
