### ISSUE TITLE
ModuleNotFoundError: No module named 'flair'

### ISSUE THREAD

**Issue by somumu** [flairNLP/flair#1348]
Hello,
I am trying to work on flair. Under virtual environment I ran the following commands on jupyter notebook:

from flair.data import Corpus
from flair.datasets import ClassificationCorpus

But non of the flair related commands are working it gives always one error:
ModuleNotFoundError: No module named 'flair'

I have already installed flair and torch but still its not running on jupyter notebook.

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux 64-bit
 - Version [e.g. flair-0.3.2]: flair ==0.4.3
torch==1.1.0

Kindly help, 
Thank you.

**Comment by djstrong** [comment]
`! pip install flair` in notebook

**Comment by Shourya-Srivastava2000** [comment]
does not work even after pip
