### ISSUE TITLE
Getting empty labels : No output of sentiment

### ISSUE THREAD

**Issue by somumu** [flairNLP/flair#1350]
Hello,
I am using flair for sentiment analysis. I have trained a custom text classification model on twitter dataset. When I use the model it gives me the sentiment of the sentences but for some sentence it gives no sentiment i.e. no labels. 

sen5 = Sentence('Go there and walk')
classifier.predict(sen5)
print(sen5.labels)
Output : [neutral (0.538922905921936)]

sen5 = Sentence('Go there and bring')
classifier.predict(sen5)
print(sen5.labels)
Output : [ ]

Is it because of corpus or something else. Kindly do let me know.

Any help would be appreciated...
Thank you
Somya

**Comment by alanakbik** [comment]
@somumu this bevahior is possible if you init the `TextClassifier` with `multi_label=True`. In this case, it can predict several labels at once, or none at all. 

```python
model = TextClassifier(embeddings, label_dict, multi_label=True)
```

If you know that each data point gets exactly one label, like in your case where each data point is either POSITIVE, NEGATIVE or NEUTRAL, then you should init like this:

```python
model = TextClassifier(embeddings, label_dict, multi_label=False)
```

The above-described behavior cannot happen then. In the current version of Flair, `multi_label` is set automatically, so you just do: 

```python
model = TextClassifier(embeddings, label_dict)
```

Everything should work automatically.
