### ISSUE TITLE
Extracting tensor or vector from sequence labeling model bilstm layer before crf is applied?

### ISSUE THREAD

**Issue by rishab-32** [flairNLP/flair#1354]
Hi, is there any way we can extract the output tensor or vector for each token from the sequence labeling model Bi-Lstm layer before CRF is applied to it?

**Comment by stefan-it** [comment]
Hi @rishab-32 ,

I think you can just call the `embedding` function for each token after you applied the `embed()` function on a specific sentence:

```python
from flair.data import Sentence
from flair.embeddings import CamembertEmbeddings

embedding = CamembertEmbeddings()

sentence = Sentence("J'aime le camembert !")
embedding.embed(sentence)

for token in sentence.tokens:
  print(token.embedding)
```

This will return the embedding for each token in the sentence. I hope this helps :)
