### ISSUE TITLE
Min how many utterances required for each NER training

### ISSUE THREAD

**Issue by deepankar27** [flairNLP/flair#1357]
I want to train a new model with a new NER. 
But no where I found what is the minimum number of utterances required to train a new NER/Entity.
Like Spacy expects at least 5 utterances for a new entity. Likewise how many sample sentences/utterances needs to supplied for Flair NER model?

**Comment by djstrong** [comment]
There is no required minimum, but the accuracy depends on it.

**Comment by dheerajmitra** [comment]
@deepankar27  have you got any solution of that

**Comment by deepankar27** [comment]
> @deepankar27 have you got any solution of that

I haven't used it.. I would suggest give a try & track the precision/recall improvement to derive your required threshold.
