### ISSUE TITLE
Is it possible to export a SequenceTagger model to TensorFlow 

### ISSUE THREAD

**Issue by vadimar** [flairNLP/flair#1367]
I'd like to run a trained SequenceTagger model using TensorFlow. Would it be possible to export its inner graph to protobuf file format which TensorFlow can understand?

**Comment by severinsimmler** [comment]
+1

I would also be interested in how to _use_ the transferred model, i.e. how to translate tokens into vectors etc.

**Comment by alanakbik** [comment]
Haven't tried this, but if someone in the community has, please share your experience :)
