### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by ralphmueller** [flairNLP/flair#1370]
I get the following error when installing flair with Python3 / pip3. Any suggestions?

ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
tiny-tokenizer depends on SudachiDict_core@ https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20190927.tar.gz

**Comment by djstrong** [comment]
Resolved in https://github.com/flairNLP/flair/issues/1327

**Comment by ralphmueller** [comment]
Thanks, works.

**Comment by alanakbik** [comment]
We just released flair 0.4.5 where this should be fixed!
