### ISSUE TITLE
Create Dataset from JSON file, string, or stream

### ISSUE THREAD

**Issue by carljohanrehn** [flairNLP/flair#1373]
I've implemented a JSONDataset, see https://github.com/carljohanrehn/flair/blob/mongo/flair/datasets.py

This feature can be seen as an alternative (or a complement) to the MongoDataset.

For instance, we can now do:

```
from flair.datasets import JSONDataset

train_dataset: JSONDataset = JSONDataset('data.json', 'text', ['category1', 'catgeory2', 'category3'])

with open('data.json', encoding='utf8') as f:
    data_json = f.read()

train_dataset: JSONDataset = JSONDataset(data_json, 'text', ['category1', 'catgeory2', 'category3'])

import io

data_stream = io.StringIO(data_json)

train_dataset: JSONDataset = JSONDataset(data_stream, 'text', ['category1', 'catgeory2', 'category3'])
```

Please, let me know if you're interested in this feature. I can do a pull request and provide a description on how to use the JSONDataset.

**Comment by alanakbik** [comment]
Hello @carljohanrehn sure we'd appreciate a PR! Thanks!
