### ISSUE TITLE
how to save text classification model by a different name other than best-model.pt

### ISSUE THREAD

**Issue by somumu** [flairNLP/flair#1381]
Hello,
I am training custom text classification model but it always gets saved as best-model.pt
classifier = TextClassifier.load('./best-model.pt')
I run the same custom text classification for different type of datasets and it is always saved as best-model.pt. How will I differentiate between models then ? Please help as i am working on multiple datasets.

Any help would be appreciated..

**Comment by alanakbik** [comment]
@somumu if you use the `ModelTrainer` to train, then you can specify the result folder that stores all experiment files. You can specify a different folder for each experiment.

```python
# [..] define experiment 1, then train and store in folder 'memory-tagger'
trainer = ModelTrainer(memory_tagger, corpus)

trainer.train('resources/taggers/memory-tagger')


# [..] define experiment 2, then train and store in folder 'baseline-tagger'
trainer = ModelTrainer(baseline_tagger, corpus)

trainer.train('resources/taggers/baseline-tagger')
```

**Comment by somumu** [comment]
I am passing classifier in ModelTrainer
classifier = TextClassifier(document_embeddings, label_dictionary=corpus.make_label_dictionary(), multi_label=True)
trainer = ModelTrainer(classifier, corpus)
