### ISSUE TITLE
DocumentPoolEmbeddings unexpected result 

### ISSUE THREAD

**Issue by moh55m55** [flairNLP/flair#1387]
Hello all,
I am trying to embed a sentence using both  DocumentPoolEmbeddings and StackedEmbeddings. 
It seems that the DocumentPoolEmbeddings with "mean pooling" gives the same dimension as StackedEmbeddings. 

DocumentPoolEmbeddings: 
```
from flair.embeddings import RoBERTaEmbeddings,Sentence,DocumentPoolEmbeddings, BertEmbeddings,StackedEmbeddings
sentence = Sentence('People have predicted his demise so many times , and the US has tried to hasten it on several occasions .')
embedding_roberta = RoBERTaEmbeddings(layers='-1')
embedding_bert= BertEmbeddings(layers='-1')
document_embeddings = DocumentPoolEmbeddings([embedding_bert,embedding_roberta],pooling="mean")

print(sentence.get_embedding().shape)
print(sentence[2].embedding.shape) # printing the embed size of the third token 
```
## Result:
torch.Size([1536])
torch.Size([1536])

```
document_embeddings = StackedEmbeddings([embedding_bert,embedding_roberta])
print(sentence.get_embedding().shape)
print(sentence[2].embedding.shape)
```
## Result :
torch.Size([1536])
torch.Size([1536])

Shouldn't the StackedEmbeddings is just the concatenation ( i.e. torch.Size([1536])) whereas the DocumentPoolEmbeddings of (bert and roberta) is the mean pooling (i.e.   768) . 

Am I understanding the two approaches correctly or there is something wrong?

**Comment by djstrong** [comment]
It is ok. Document embedding is a mean of token embedding, so the size is the same.

`DocumentPoolEmbeddings([embedding_bert,embedding_roberta])` is the same as `DocumentPoolEmbeddings(StackedEmbeddings([embedding_bert,embedding_roberta]))`

**Comment by moh55m55** [comment]
I see, thanks.  what if I want to do mean pooling between (embedding_bert, embedding_roberta) instead of concatenation. That is taking the mean between the (embedding_bert : sentence.get_embedding()) and (embedding_roberta: sentence.get_embedding()) in DocumentPoolEmbeddings class.

**Comment by djstrong** [comment]
It is not supported (because token embeddings usually have different sizes). I did not see such approach in papers.

**Comment by djstrong** [comment]
What do you want to do with such sentence embedding?

**Comment by moh55m55** [comment]
Yes, I agree tokens have different sizes, But as of bert and roberta they do have the same size ,so experimenting some pointwise operations is worth it. I actually got the best result of combining bert and roberta. 

What do you want to do with such sentence embedding? I just want to do some kind of sequence classification. 

Thanks
