### ISSUE TITLE
Implications of calculating the embeddings in collate_fn

### ISSUE THREAD

**Issue by marcelgwerder** [flairNLP/flair#1390]
I found that calling `emeddings.embed(batch)` in a custom collate function significantly speeds up my training when using `num_workers=0`. I'm assuming because it makes use of threading when it is part of the dataloader:

```python
class MyCollator(object):
    def __init__(self, embeddings):
        self.embeddings = embeddings
    def __call__(self, batch):
        self.embeddings.embed(batch)
      
        return batch
```

I'm wondering if this comes with any negative side effects I'm not fully aware of. Any input on whether this is a safe thing to do? I guess this is related to #889.

**Comment by alanakbik** [comment]
Sounds interesting and sorry for the late reply. Are you using this only to embed sentences or is this part of the training run? Could you give some more info on this?

**Comment by marcelgwerder** [comment]
I think this was a false alarm, I got confused by the timing logs in the trainer that did not include the embedding part anymore.
