### ISSUE TITLE
How to prepare text corpus for training custom language model

### ISSUE THREAD

**Issue by sudharsan2020** [flairNLP/flair#1391]
I've referred the training custom embedding from Flair. It has mentioned **Character based training data**. Can anyone share the links for any tutorials to **prepare the training data for custom language model?**

**Comment by djstrong** [comment]
Have you read tutorial https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md#preparing-a-text-corpus ?

**Comment by sudharsan2020** [comment]
I've read that tutorial.But I am not sure whether the input corpus text is like **tokens** or **characters** of the original text. I've trained gensim based word embeddings. Is it similar to the input which is a **list of tokens**?

**Comment by djstrong** [comment]
It should be the same type of text as it will be passed later in some tasks. Usually, it is raw text without preprocessing. However, pretrained embeddings for English are whitespace tokenized.

**Comment by sudharsan2020** [comment]
ok thanks for the reply.I understood.

**Comment by miguelwon** [comment]
Is there any common rule for the raw text file? One doc or one sentence per line?
