### ISSUE TITLE
Convert .md tutorial to .py easily

### ISSUE THREAD

**Issue by Contractfit** [flairNLP/flair#1392]
While wanting to try out the tutorials, I noticed they were in markdown format, ".md". 
As I am not aware of an easy tool to convert markdown to python, and I was unwilling to copy paste code blocks, I created a quick and dirty script to convert the .md to .py files. 

Maybe it helps others as well. 
[md_to_py.py.zip](https://github.com/flairNLP/flair/files/4122922/md_to_py.py.zip)

**Comment by severinsimmler** [comment]
Please copy-paste the source code here or refer to a GitHub repository.

**Comment by hackazaq** [comment]
`import os
import re

root = os.path.dirname(os.path.abspath(__file__))  # directory flair/resources/docs
mds = [os.path.join(root, file) for file in os.listdir(root) if file.split(".")[-1] == "md"]


def comment_all_lines(md):
    return "\n".join(["€#" + line if not line.startswith("#") and line else line for line in md.split("\n")])


def convert_md(md):
    console_parts = re.finditer("#This should print:.+?```console(?P<console>(.*?))```", md, re.S)
    for i, match in enumerate(console_parts):
        uncomment_console = re.sub("€#", "    #", match.group("console"))
        md = md.replace(match.group(), uncomment_console)

    code_parts = re.finditer("#```python(?P<code>(.*?))```", md, re.S)
    for i, match in enumerate(code_parts):
        uncomment_code = re.sub("€#", "", match.group("code"))
        md = md.replace(match.group(), uncomment_code)
    md = re.sub("```", "", md)
    md = re.sub("€", "", md)
    return md


for md in mds:
    md_text = open(md, "r").read()
    md_text2 = comment_all_lines(md_text)
    md_text3 = convert_md(md_text2)
    new_path = md.replace(".md", ".py")
    with open(new_path, "w") as f:
        f.write(md_text3)`

**Comment by hackazaq** [comment]
> Please copy-paste the source code here or refer to a GitHub repository.

import os
import re

root = os.path.dirname(os.path.abspath(file)) # directory flair/resources/docs
mds = [os.path.join(root, file) for file in os.listdir(root) if file.split(".")[-1] == "md"]

def comment_all_lines(md):
return "\n".join(["€#" + line if not line.startswith("#") and line else line for line in md.split("\n")])

def convert_md(md):
console_parts = re.finditer("#This should print:.+?console(?P<console>(.*?))", md, re.S)
for i, match in enumerate(console_parts):
uncomment_console = re.sub("€#", " #", match.group("console"))
md = md.replace(match.group(), uncomment_console)

code_parts = re.finditer("#```python(?P<code>(.*?))```", md, re.S)
for i, match in enumerate(code_parts):
    uncomment_code = re.sub("€#", "", match.group("code"))
    md = md.replace(match.group(), uncomment_code)
md = re.sub("```", "", md)
md = re.sub("€", "", md)
return md

for md in mds:
md_text = open(md, "r").read()
md_text2 = comment_all_lines(md_text)
md_text3 = convert_md(md_text2)
new_path = md.replace(".md", ".py")
with open(new_path, "w") as f:
f.write(md_text3)
