### ISSUE TITLE
Additional features for text classification

### ISSUE THREAD

**Issue by quadrupole** [flairNLP/flair#1395]
Is there a straightforward way to incorporate additional features into a text classification task with flair? For example let's say I am doing sentiment analysis on tweets, but for each tweet I also know the time of day at which it was posted, encoded as floating point number. I wish to incorporate this feature along with the flair embedding for the tweet to classify tweets into several categories, but I am not sure if there is a straightforward way of doing this with the current flair text classifier API?

**Comment by djstrong** [comment]
Probably no. You can add this feature as a tag to each token and then append Embedding on this tag.

**Comment by pommedeterresautee** [comment]
An approach which often works well is to bucketize your feature (for instance morning, afternoon, night for hour), and just add it to the text (at start or end, doesn’t seem to matter). Not perfect but most of the time you get most of the added value from the new signal without making your code more complex.

**Comment by owilsby** [comment]
Thanks for the input! The bucketizing of the numerical feature and adding this to the input text is interesting, and something I will try. However, I wish to be a bit more general, maybe I want to incorporate any number of extra continuous features and not bucketize these, in a general text classification task.  It seems then that there is no easy way to incorporate these extra features into flairs current classification API?

**Comment by djstrong** [comment]
The simplest way is to do this to each token and write custom Embedding class to support continuous values, e.g.:
```
class ValueEmbeddings(TokenEmbeddings):
    """Value embeddings."""

    def __init__(
        self,
        field: str 
    ):

        super().__init__()
        self.name = "value"
        self.static_embeddings = True
        self.field = field

        self.__embedding_length = 1

    @property
    def embedding_length(self) -> int:
        return self.__embedding_length

    def _add_embeddings_internal(self, sentences: List[Sentence]) -> List[Sentence]:

        one_hot_sentences = []
        for i, sentence in enumerate(sentences):

            context_idxs = [
                t.get_tag(self.field).value
                for t in sentence.tokens
            ]

            one_hot_sentences.extend(context_idxs)

        embedded = torch.tensor(one_hot_sentences, dtype=torch.float).to(
            flair.device
        )

        index = 0
        for sentence in sentences:
            for token in sentence:
                embedding = embedded[index]
                token.set_embedding(self.name, embedding)
                index += 1

        return sentences

    def __str__(self):
        return self.name
```
