### ISSUE TITLE
Difference between final-model.pt and best-model.pt 

### ISSUE THREAD

**Issue by sawankumar94** [flairNLP/flair#1396]
Hello All! I am using Flair for mutliclass text classification in Python. I want to know 

a) Why there are two models, final-model.pt and best-model.pt ? 

b) Which one should i use for prediction post training ? 

c) What is the significance of both?

Please help!

**Comment by djstrong** [comment]
You should use a development data and the best-model is a model with the best score on development data. It is not necessarily a model after last step of training (final-model). You should use best-model.
