### ISSUE TITLE
Trying to find out the created NER tags

### ISSUE THREAD

**Issue by rajrohan** [flairNLP/flair#1397]
We trained a Hindi NER model with the following corpus "[https://github.com/UniversalDependencies/UD_Hindi-HDTB]". When testing with a sample text(as shown in the attached image), the created NER-Tags is not comprehensible. 
>>> sentence = Sentence("""रामायण काल में भगवान राम के पुत्र कुश की राजधानी कुशावती को 483 ईसा पूर्व बुद्ध ने अपने अंतिम विश्राम के लिए चुना ।""")
>>> tagger = SequenceTagger.load('/home/sarthak/projects/flair/resources/taggers/example-ner/best-model.pt')
2020-01-29 17:11:48,454 loading file /home/sarthak/projects/flair/resources/taggers/example-ner/best-model.pt
>>> tagger.predict(sentence)# make a sentence
[Sentence: "रामायण काल में भगवान राम के पुत्र कुश की राजधानी कुशावती को 483 ईसा पूर्व बुद्ध ने अपने अंतिम विश्राम के लिए चुना ।" - 24 Tokens]
>>> for entity in sentence.get_spans('ner'):
...     print(entity)
... 
आदि-span [1]: "रामायण"
तब-span [2]: "काल"
तब-span [3]: "में"
तब-span [4]: "भगवान"
तब-span [5]: "राम"
तब-span [6]: "के"
तब-span [7]: "पुत्र"
तब-span [8]: "कुश"
तब-span [9]: "की"
तब-span [10]: "राजधानी"
तब-span [11]: "कुशावती"
तब-span [12]: "को"
तब-span [13]: "483"
तब-span [14]: "ईसा"
तब-span [15]: "पूर्व"
तब-span [16]: "बुद्ध"
तब-span [17]: "ने"
तब-span [18]: "अपने"
तब-span [19]: "अंतिम"
तब-span [20]: "विश्राम"
=-span [21]: "के"
चाह-span [22]: "लिए"
राजनीतिक-span [23]: "चुना"
मदनलाल-span [24]: "।"

We want to see all the NER-Tags which are supposed to be created by this model. Can anyone please guide me to find the NER-Tags??
Thanks in advance.

![WhatsApp Image 2020-01-29 at 18 13 55](https://user-images.githubusercontent.com/20280562/73381814-aeb0c680-42c6-11ea-8241-80bf2c1d698a.jpeg)

**Comment by alanakbik** [comment]
Hi @rajrohan try printing the tag_dictionary. I.e.: 

```python
from flair.models import SequenceTagger

# load the NER tagger
tagger: SequenceTagger = SequenceTagger.load('ner')

print(tagger.tag_dictionary)
```

You create this dictionary after reading the corpus. If the dictionary is not correct, this may mean that the corpus is not correctly read.

**Comment by rajrohan** [comment]
Hi, @alanakbik Thanks for the quick response.
I think the corpus is not being processed properly when I am using the UD_Hindi dataset. The data-sets given in the examples have a 2 column format (1 column with words and another with the respective tags, CoNLL-03) while the UD_Hindi data set has a completely different format. After training with the UD_Hindi Dataset, we are getting tags that are very vague and make no sense. To replicate this issue we tried training an English model with UD_English data set, and got similar vague results, as shown below:
**POS** output:
`George <a> Washington <I> went <and> to <a> Washington <I> . <and>`

**NER** output:
`Sentence: "George Washington went to Washington" - 5 Tokens
The following NER tags are found:
problem-span [1]: "George"
when-span [2]: "Washington"
and-span [3]: "went"
be-span [4]: "to"
.-span [5]: "Washington"`
As per my understanding, I think there is a problem while the dictionary processing, from the given data-sets. Can you please suggest, the way to process the UD data-sets. 
If this is not the problem, can you please tell me where I am wrong and the correct way forward.

Thanks in advance.

**Comment by alanakbik** [comment]
@rajrohan does this error still persist? if so, could you paste your full training code? There is probably an issue with reading the training data.

**Comment by rajrohan** [comment]
Sample input:
## sent_id = dev-s1
## text = रामायण काल में भगवान राम के पुत्र कुश की राजधानी कुशावती को 483 ईसा पूर्व बुद्ध ने अपने अंतिम विश्राम के लिए चुना ।
1	रामायण	रामायण	PROPN	NNPC	Case=Nom|Gender=Masc|Number=Sing|Person=3	2	compound	_	Vib=0|Tam=0|ChunkId=NP|ChunkType=child|Translit=rāmāyaṇa
2	काल	काल	PROPN	NNP	Case=Acc|Gender=Masc|Number=Sing|Person=3	23	obl	_	Vib=0_में|Tam=0|ChunkId=NP|ChunkType=head|Translit=kāla
3	में	में	ADP	PSP	AdpType=Post	2	case	_	ChunkId=NP|ChunkType=child|Translit=meṁ
4	भगवान	भगवान	NOUN	NNC	Case=Nom|Gender=Masc|Number=Sing|Person=3	5	compound	_	Vib=0|Tam=0|ChunkId=NP2|ChunkType=child|Translit=bhagavāna
5	राम	राम	PROPN	NNP	Case=Acc|Gender=Masc|Number=Sing|Person=3	7	nmod	_	Vib=0_का|Tam=0|ChunkId=NP2|ChunkType=head|Translit=rāma
6	के	का	ADP	PSP	AdpType=Post|Case=Acc|Gender=Masc|Number=Sing	5	case	_	ChunkId=NP2|ChunkType=child|Translit=ke
7	पुत्र	पुत्र	NOUN	NN	Case=Acc|Gender=Masc|Number=Sing|Person=3	8	nmod	_	Vib=0|Tam=0|ChunkId=NP3|ChunkType=head|Translit=putra
8	कुश	कुश	PROPN	NNP	Case=Acc|Gender=Masc|Number=Sing|Person=3	10	nmod	_	Vib=0_का|Tam=0|ChunkId=NP4|ChunkType=head|Translit=kuśa
9	की	का	ADP	PSP	AdpType=Post|Case=Acc|Gender=Fem|Number=Sing	8	case	_	ChunkId=NP4|ChunkType=child|Translit=kī
10	राजधानी	राजधानी	NOUN	NN	Case=Acc|Gender=Fem|Number=Sing|Person=3	11	nmod	_	Vib=0|Tam=0|ChunkId=NP5|ChunkType=head|Translit=rājadhānī
11	कुशावती	कुशावती	PROPN	NNP	Case=Acc|Gender=Fem|Number=Sing|Person=3	23	obj	_	Vib=0_को|Tam=0|ChunkId=NP6|ChunkType=head|Translit=kuśāvatī
12	को	को	ADP	PSP	AdpType=Post	11	case	_	ChunkId=NP6|ChunkType=child|Translit=ko
13	483	483	PROPN	NNPC	Case=Nom|Gender=Masc|Number=Sing|Person=3	15	compound	_	Vib=0|Tam=0|ChunkId=NP7|ChunkType=child|Translit=483
14	ईसा	ईसा	PROPN	NNPC	Case=Nom|Gender=Masc|Number=Sing|Person=3	15	compound	_	Vib=0|Tam=0|ChunkId=NP7|ChunkType=child|Translit=īsā
15	पूर्व	पूर्व	PROPN	NNP	Case=Nom|Gender=Masc|Number=Sing|Person=3	23	obl	_	Vib=0|Tam=0|ChunkId=NP7|ChunkType=head|Translit=pūrva
16	बुद्ध	बुद्ध	PROPN	NNP	Case=Acc|Gender=Masc|Number=Sing|Person=3	23	nsubj	_	Vib=0_ने|Tam=0|ChunkId=NP8|ChunkType=head|Translit=buddha
17	ने	ने	ADP	PSP	AdpType=Post	16	case	_	ChunkId=NP8|ChunkType=child|Translit=ne
18	अपने	अपना	PRON	PRP	Case=Acc|Gender=Masc|PronType=Prs	20	nmod	_	Vib=0|Tam=0|ChunkId=NP9|ChunkType=head|Translit=apane
19	अंतिम	अंतिम	ADJ	JJ	Case=Acc	20	amod	_	ChunkId=NP10|ChunkType=child|Translit=aṁtima
20	विश्राम	विश्राम	NOUN	NN	Case=Acc|Gender=Masc|Number=Sing|Person=3	23	obl	_	Vib=0_के_लिए|Tam=0|ChunkId=NP10|ChunkType=head|Translit=viśrāma
21	के	के	ADP	PSP	AdpType=Post	20	case	_	ChunkId=NP10|ChunkType=child|Translit=ke
22	लिए	लिए	ADP	PSP	AdpType=Post	20	case	_	ChunkId=NP10|ChunkType=child|Translit=lie
23	चुना	चुन	VERB	VM	Aspect=Perf|Gender=Masc|Number=Sing|VerbForm=Part|Voice=Act	0	root	_	Vib=या|Tam=yA|ChunkId=VGF|ChunkType=head|Stype=declarative|Translit=cunā
24	।	।	PUNCT	SYM	_	23	punct	_	ChunkId=BLK|ChunkType=head|Translit=.

# Please find the Script below:
corpus = flair.datasets.UD_HINDI()
corpus.make_tag_dictionary('ner')
corpus.make_tag_dictionary('upos')
from flair.data import Corpus
from flair.datasets import ColumnCorpus

# define columns
columns = {0: 'text', 1: 'pos', 2: 'ner'}

# this is the folder in which train, test and dev files reside
#data_folder = '/Users/rohanraj/.flair/datasets/ud_hindi/'
data_folder = '/home/rohanraj9931111104/.flair/datasets/ud_hindi/'
# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='hi_hdtb-ud-train.conllu',
                              test_file='hi_hdtb-ud-test.conllu',
                              dev_file='hi_hdtb-ud-dev.conllu')
from flair.data import Corpus
from flair.datasets import WNUT_17
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings
from typing import List

# 1. get the corpus
corpus: Corpus = corpus.downsample(0.1)
print(corpus)

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary.idx2item)

# 4. initialize embeddings
embedding_types: List[TokenEmbeddings] = [WordEmbeddings('glove')]
embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# 5. initialize sequence tagger
from flair.models import SequenceTagger
tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import ModelTrainer
trainer: ModelTrainer = ModelTrainer(tagger, corpus)

# 7. start training
trainer.train('/home/rohanraj9931111104/.flair/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=100
             )

**Comment by rajrohan** [comment]
Hi, @alanakbik Thank you for the support. I had an issue with the data itself as you suggested. It is not possible to build the NER Model with this input [https://github.com/UniversalDependencies/UD_Hindi-HDTB ](URL).
Assumption: There are no NER tags available only the POS model can be possible. 

To Build NER Model for HINDI Data must be prepared in column format.
EX(Sample data): 
`शैक्षणिक	JJ	B-NP	o	o	o
स्तर	NN	I-NP	o	o	o
पर	PSP	I-NP	o	o	o
गांधी	NNP	B-NP	B-PERSON	B-INDIVIDUAL	o
जी	RP	I-NP	I-PERSON	I-INDIVIDUAL	o
एक	QC	B-NP	o	o	o
औसत	NN	I-NP	o	o	o
छात्र	NN	B-NP	o	o	o
रहे	VM	B-VGF	o	o	o
.	SYM	I-VGF	o	o	o

4	QC	B-BLK	o	o	o
सिंतबर	NNPC	I-BLK	B-MONTH	o	o
]	SYM	I-BLK	o	o	o
]	SYM	B-NP	o	o	o
1888	NNP	I-NP	B-YEAR	o	o
.	SYM	I-NP	o	o	o

लंदन	NNP	B-NP	B-LOCATION	B-PLACE	B-NATION`

`from flair.data import Corpus
from flair.datasets import ColumnCorpus

columns = {0: 'text', 1: 'pos', 2: 'ner',3:'netag1',4:'netag2',5:'netag3'}
data_folder = '../data/Hindi_NER/'

corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt'
                             )`

I was able to build the NER Model for the Hindi Language With small Input data.
Sample Output ('NER')(IOB tags): 
`रामायण <B-NP> काल <I-NP> में <I-NP> भगवान <B-NP> राम <I-NP> के <I-NP> पुत्र <I-NP> कुश <B-NP> की <I-NP> राजधानी <B-NP> कुशावती <I-NP> को <I-NP> 483 <B-NP> ईसा <I-NP> पूर्व <I-NP> बुद्ध <B-NP> ने <I-NP> अपने <B-NP> अंतिम <I-NP> विश्राम <B-NP> के <I-NP> लिए <B-NP> चुना <I-NP> । <I-NP>`
