### ISSUE TITLE
Embed the POS information when training NER model

### ISSUE THREAD

**Issue by kirunijah** [flairNLP/flair#1400]
Hi, the developers of Flair, I am really thankful that you guys make this very easily used library for neural NER task. 

Currently I am working on my language's NER task and I am wondering if I can include (or embed) the POS tag information when my NER model is trained, to increase the supervision of the context of the sentence (I am thinking the model could also learn the context of the NER tag based on the POS tag).

Thank you very much for your help!

**Comment by djstrong** [comment]
Yes, by adding "tags" with POS to tokens and appending `OneHotEmbeddings(field='name_of_tag')`.

**Comment by falcaopetri** [comment]
Should this be documented under [`resources/docs/embeddings`](https://github.com/flairNLP/flair/tree/4ce32c774b4dc5a8bfc0559441a1c8da4f06131d/resources/docs/embeddings)?

**Comment by alanakbik** [comment]
@falcaopetri good point, just added this to the documentation!
