### ISSUE TITLE
Ignore .swp files when loading a dataset

### ISSUE THREAD

**Issue by falcaopetri** [flairNLP/flair#1401]
After some tests where I successfully loaded a dataset, I suddenly started to get exceptions complaining about wrong UTF-8 encoding. It took me a while to realize that FlairDataset was trying to load vi's `.train.txt.swp` file.

I would like to suggest that files with `.swp` extensions should be ignored when trying to [find train/dev/test files](https://github.com/flairNLP/flair/blob/e22e01fe524ca6bcf0d545f1f5efecbc55ff88a8/flair/datasets.py#L3250).

https://github.com/flairNLP/flair/blob/e22e01fe524ca6bcf0d545f1f5efecbc55ff88a8/flair/datasets.py#L3262-L3266

**Comment by falcaopetri** [comment]
Could you check out my PR suggestion?

**Comment by alanakbik** [comment]
@falcaopetri thanks for adding this!
