### ISSUE TITLE
Flair for Hindi dataset

### ISSUE THREAD

**Issue by somumu** [flairNLP/flair#1405]
Hello everyone,
I have trained a custom text classification model on English dataset(twitter) now I have to do the same for Hindi dataset. Please do let me know the process for training the model on Hindi dataset. Is there any embedding for Hindi also as like in Spanish ?
FlairEmbeddings('spanish-forward-fast')
Can I make a model for Hindi with good f1-score ?
 As I tried to train the model on Hindi dataset with the same process I did for English dataset but I got f1-score=0.0

Kindly help me with this question.

**Comment by rajrohan** [comment]
Hi @somumu, You can load the FlairEmbeddings model Hindi. 
FlairEmbeddings('hi-forward')
FlairEmbeddings('hi-backward')
Please find more info here:  https://github.com/flairNLP/flair/issues/614

**Comment by alanakbik** [comment]
@somumu there are also Hindi word embeddings trained with FastText that are included. Check [here](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/CLASSIC_WORD_EMBEDDINGS.md). You can load them with: 

```python
# Hindi embeddings trained with Wikipedia
hindi_wikipedia_embeddings = WordEmbeddings('hi')

# Hindi embeddings trained with Web crawls
hindi_webcrawl_embeddings = WordEmbeddings('hi-crawl')
```

**Comment by somumu** [comment]
Thank you so much @alanakbik and @rajrohan for your help. Problem is solved :)
