### ISSUE TITLE
wrong import in example in release notes 0.4.5

### ISSUE THREAD

**Issue by timnon** [flairNLP/flair#1407]
The import 
```
from WordEmbeddingsStore import WordEmbeddingsStore
```
in the release notes for release 0.4.5 and issue #1315 is wrong. As in the docstring, it should be:
```
from flair.inference_utils import WordEmbeddingsStore
```
Just to make sure that nobody gets frustrated when trying

**Comment by alanakbik** [comment]
@timnon thanks for spotting this! Just fixed it!
