### ISSUE TITLE
still issues when loading some models on Win 10

### ISSUE THREAD

**Issue by dcavar** [flairNLP/flair#1408]
Using the newest Flair and torch on Win 10 I still get this error for (other models worked):
tagger = SequenceTagger.load('frame-fast')
or
tagger = SequenceTagger.load('frame')

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-20-02fe8d2768ba> in <module>
----> 1 tagger = SequenceTagger.load('frame-fast')
      2 
      3 sentence_1 = Sentence('George returned to Berlin to return his hat .')
      4 sentence_2 = Sentence('He had a look at different hats .')
      5 

c:\program files\python37\lib\site-packages\flair\nn.py in load(cls, model)
     84             # see https://github.com/zalandoresearch/flair/issues/351
     85             f = file_utils.load_big_file(str(model_file))
---> 86             state = torch.load(f, map_location=flair.device)
     87 
     88         model = cls._init_model_with_state_dict(state)

c:\program files\python37\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    527             with _open_zipfile_reader(f) as opened_zipfile:
    528                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
--> 529         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    530 
    531 

c:\program files\python37\lib\site-packages\torch\serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    700     unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    701     unpickler.persistent_load = persistent_load
--> 702     result = unpickler.load()
    703 
    704     deserialized_storage_keys = pickle_module.load(f, **pickle_load_args)

c:\program files\python37\lib\pathlib.py in __new__(cls, *args, **kwargs)
   1023         if not self._flavour.is_supported:
   1024             raise NotImplementedError("cannot instantiate %r on your system"
-> 1025                                       % (cls.__name__,))
   1026         self._init()
   1027         return self

NotImplementedError: cannot instantiate 'PosixPath' on your system

**Comment by severinsimmler** [comment]
I'd say this error is raised because the model has been trained on a UNIX-based OS and you are trying to load it on Windows.

**Comment by dcavar** [comment]
> 
> 
> I'd say this error is raised because the model has been trained on a UNIX-based OS and you are trying to load it on Windows.

Models are platform independent, pickled Python objects should be, too.
I train on Linux and run on Macs or Win10, or even embedded systems without a problem. This is an old issue, potentially related to the model size or, as it says in the log, to PosixPaths. The old error talking about that issue was closed and this is why I posted again.

Needless to say, frame loads just fine on Ubuntu and even on the Win10 Linux Subsystem. I'll test OSX later.

**Comment by alanakbik** [comment]
Hi @dcavar this is probably the same issue as #1052 and only affects trained models that use `BytePairEmbeddings`. These embeddings have a special serialization mechanism that does not seem to travel well across different OS. I am looking into setting up a better testing environment to spot such errors, but realistically it will be a while before we'll fix this. 

In the meantime, on thread #1052 @eurekaqq posted a workaround - does this work for you?

**Comment by dcavar** [comment]
Thanks!

It works just fine on Linux, but I'll try the portion of code later on a Win10 box later. It would be good, if it would work on both. I teach with that and many students seem to be on Win10. :-)
