### ISSUE TITLE
High memory/swap when embedding with BERT

### ISSUE THREAD

**Issue by BeWe11** [flairNLP/flair#1409]
**Describe the bug**
I'm embedding sentences using the `BertEmbeddings` class. I'm performing a single `.embed` call on a list of around 3000 `Sentence` objects. While the embeddings are being calculated, my swap increases by a huge amount, starting from almost nothing to around 50 GB. If I extract the embeddings afterwards as numpy arrays, the total size of the embeddings is around 15 MB.

**To Reproduce**
```python
from flair.embeddings import BertEmbeddings, Sentence

embedder = BertEmbeddings(
    "bert-base-german-dbmdz-uncased",
    layers="0,1,2,3,4,5,6,7,8,9,10,11,12",
    use_scalar_mix=True,
    pooling_operation="first",
)
sentences = ["Ich suche drei Kisten Cola."] * 3000
flair_sentences = [Sentence(sentence) for sentence in sentences]
embedder.embed(flair_sentences)
```

**Expected behavior**
I'm not sure if this is an expected byproduct of using the BERT embedder. Is there some place inside the embedding code that caches large intermediate objects during a `.embed` call? My current workaround is to split the sentences into chunks and perform multiple `.embed` calls in parallel.

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: MacOS
 - Version [e.g. flair-0.3.2]: flair-0.4.5

**Comment by alanakbik** [comment]
Hello @BeWe11 a bit late, but we've added a new implementation of transformer embeddings that seems to be more memory-effective. I can run your code on my laptop with no big memory buildup. This implementation is already in master branch and will be part of the next release. 

There, you can set the `batch_size` in the embeddings object. 

```python
embedder = TransformerWordEmbeddings(
    "bert-base-german-dbmdz-uncased",
    layers="all",
    use_scalar_mix=True,
    pooling_operation="first",
    batch_size=256,
)
```

If all you want is the sentence representation as given by the CLS token, you can use the `TransformerDocumentEmbeddings` class instead.

**Comment by BeWe11** [comment]
Thanks @alanakbik !
