### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by chaitanyasaikrishna** [flairNLP/flair#1411]
Hello everyone,
I want to train the ner model on custom data using glove embeddings .when i am trying to use the trained ner model on custom data after proper annotation but i got F1-score=0.0.

My entities are like:
1.name 
2.address 
3.Date

**Comment by Wickky** [comment]
Can you show me your evaluation matrics?
And your annotated corpus as sample.
I would like to check whether it is correct format.

**Comment by girijesh97** [comment]
Hi, @Wickky I have submitted an issue with my sample data. Can you please check how can I achieve my target. That would be really helpful. Thanks
