### ISSUE TITLE
CSVClassificationCorpus loaded 0 sentences

### ISSUE THREAD

**Issue by GodSaveTheDucks** [flairNLP/flair#1412]
Hi everyone,
I am trying to load a custom csv corpus, I have added my `test.csv` `train.csv` and `dev.csv` in my data folder and have loaded it as shown : 
 `corpus : Corpus = CSVClassificationCorpus(data_path, column_name_map,skip_header = True, delimiter = ',') print (corpus)`
This shows : 
`Reading data from /data 
Train : /data/train.csv
Dev : /data/dev.csv
Test : /data/test.csv
Corpus : 0 train + 0 dev + 0 test_sentences`
I've mapped column_name_map to the data and label column in my CSV file.

**Comment by severinsimmler** [comment]
Could you provide a snippet from your data files?

**Comment by GodSaveTheDucks** [comment]
Please read "|" as a column delimiter.
| text | label_topic |
| ----- | -------------- |
| The provisions of Schedule 12 specifically relating to Danish, the law is governed by Danish law. All other provisions of this Agreement are governed by Section 21.4 of the Agreement. | law is governed by Danish law |

**Comment by GodSaveTheDucks** [comment]
Sorry, the column associations were incorrect. My bad
