### ISSUE TITLE
Improve performance for loading not-in-memory corpus

### ISSUE THREAD

**Issue by david-westreicher** [flairNLP/flair#1414]
To be removed, once it is done: Please add the appropriate label to this ticket, e.g. feature or enhancement.

**Is your feature/enhancement request related to a problem? Please describe.**
When loading a big corpus that doesn't have to stay in memory, i have to wait a long time until the corpus can be accessed. The problem is that sentences of the corpus are unnecessarily built while parsing.

**Describe the solution you'd like**
Please see the attached PR for a possible solution to the problem. #1413 

**Additional context**
Here are some timing measurements from before:
```
 %time corpus = ColumnCorpus('output', {0: 'text', 1: 'ner'}, train_file='train.txt', dev_file='dev.txt', test_file = 'test.txt', in_memory=False)
2020-02-06 17:30:45,151 Reading data from output
2020-02-06 17:30:45,151 Train: output/train.txt
2020-02-06 17:30:45,151 Dev: output/dev.txt
2020-02-06 17:30:45,151 Test: output/test.txt
CPU times: user 8min 41s, sys: 2.11 s, total: 8min 43s
Wall time: 8min 44s
```
And after applying the PR:
```
%time corpus = ColumnCorpus('output', {0: 'text', 1: 'ner'}, train_file='train.txt', dev_file='dev.txt', test_file = 'test.txt', in_memory=False)
2020-02-06 17:19:35,175 Reading data from output
2020-02-06 17:19:35,175 Train: output/train.txt
2020-02-06 17:19:35,175 Dev: output/dev.txt
2020-02-06 17:19:35,175 Test: output/test.txt
CPU times: user 30.7 s, sys: 609 ms, total: 31.3 s
Wall time: 31.3 s
```

**Comment by djstrong** [comment]
Looks ok, but the condition should not be so hacky (non_empty_sentence).

**Comment by david-westreicher** [comment]
Thank your for the feedback 😀
I tried a different approach with saving the state into a boolean.

**Comment by alanakbik** [comment]
PR was merged a while back, so closing this issue! Thanks again!
