### ISSUE TITLE
SpanBERT Embeddings

### ISSUE THREAD

**Issue by avinsit123** [flairNLP/flair#1415]
SpanBERT embeddings are currently used by many researchers in their models. However, Flair doesn't support SpanBERT Embeddings making it difficult for flair users to work with SpanBERT.

I wish to integrate SpanBERT Embeddings onto flair. Have a fair understanding of the TokenEmbeddings class in flair and I also have the pre-trained author weights for SpanBERT. 

I have personally created a SpanBERT Embedding class for a research project of my own. Would like to open source it so that further researchers can use it.

**Comment by stefan-it** [comment]
Hi @avinsit123 ,

this is possible, because the SpanBERT weights/models are available from the Hugging Face model hub, just have a look here: https://huggingface.co/SpanBERT

To use SpanBERT with Flair, just use:

```python
from flair.data import Sentence
from flair.embeddings import BertEmbeddings

embeddings = BertEmbeddings(bert_model_or_path="SpanBERT/spanbert-base-cased")

sent = Sentence("Berlin and Munich are nice cities .")
embeddings.embed(sent)

for token in sent.tokens:
  print(token.embedding) 
```

Please let me know, if you have further questions!
