### ISSUE TITLE
CPU vs. GPU embedding storage?

### ISSUE THREAD

**Issue by dcavar** [flairNLP/flair#1420]
Although I set:

embeddings_storage_mode='gpu'

I get this feedback:

Embeddings storage mode: cpu

Why is that?
Thx!
DC

**Comment by alanakbik** [comment]
Hi @dcavar that is strange and should not happen. Can you post a full snippet to reproduce?

**Comment by saulodspedro** [comment]
Isn't that going to happen if GPU is not available?
Maybe try on Python:
```
import torch
torch.cuda.is_available()
```
It should return `True` if it is available
