### ISSUE TITLE
Resolve tag with lower scores

### ISSUE THREAD

**Issue by basque21** [flairNLP/flair#1426]
Hi,

I trained a custom NER model (working well, thanks!), but I was wondering if it is some threshold to resolver the tags. All of them are with high scores, and maybe there is some way to get also the tags with a lower score?

Thanks!

**Comment by RonRademaker** [comment]
I'm also looking for this, did you find a way to do this?

**Comment by basque21** [comment]
No, no solution yet, sorry.

**Comment by falcaopetri** [comment]
I'm not sure if that's what you mean, but check out `all_tag_prob` flag in `SequenceTagger.predict()`:

https://github.com/flairNLP/flair/blob/4ce32c774b4dc5a8bfc0559441a1c8da4f06131d/flair/models/sequence_tagger_model.py#L294-L295

With it set to `True`, you can then do:

```python
for token in sentence:
    print(f"{token} {token.get_tag('ner')} {token.get_tags_proba_dist('ner')} \n\n")
```

Note that this slows down prediction (#1016).
