### ISSUE TITLE
Offer ability to download models from pip (same as Spacy)

### ISSUE THREAD

**Issue by alexcombessie** [flairNLP/flair#1427]
Hi,

First of all, thanks for the great work. Really useful.

I am working on a project to package flair models as a Dataiku plugin. In other words, an extension which can be installed on external Linux servers which I do not manage.

In this context, I am looking for a simple and secure way for the server admins to download models. Right now I understand the models are hosted on S3. I can devise a solution where I ask the server admin to manually download the models from S3. It is not ideal as it introduced a manual action for the admin. Executing the built-in `load` functions is possible but not a great option either. The reason is that the code would be executed as the end-user (impersonation), so it would create multiple copies of the models for each user. I cannot grant end-users the ability to write to a central shared location, as that would violate security. 

So ideally, models should be downloaded centrally in a single location, without manual interventions for the server admin.

Spacy has devised a distribution mechanism which solves my particular case: they distribute their models through pip, using GitHub release mechanism (https://github.com/explosion/spaCy#download-models). I find that quite an elegant and simple solution, in addition to the regular 'cached loading from S3' way.

Is this something you may want to add in the future?

Thanks again,

Alex

**Comment by alexcombessie** [comment]
Hi there,

Apologies for the followup, do you have any thoughts or long term plans on this topic?

Thanks,

Alex

**Comment by alanakbik** [comment]
@alexcombessie thanks for the pointer and apologies for the delay in responding. We're very interesting in improving the mechanism for serving models - for instance, there's been a lot of problems with users in some countries to get the models from s3. I'll take a look at how SpaCy does it!

**Comment by alexcombessie** [comment]
Great, that's good to hear. Let me know if I can help, I am open to contributing!

**Comment by alexcombessie** [comment]
Hi @alanakbik,

I hope all is well and you're safe at home!

Any chance this may get looked at in a future release?

Cheers,

Alex

**Comment by alanakbik** [comment]
Hi @alexcombessie yes life in quarantine, hope you're also well :)

We have a huge feature backlog so from our side it would probably take some time to get looked at. If you'd be interested in helping, for instance by helping us set this up for a small set of models, that would probably speed things up a lot!

**Comment by alexcombessie** [comment]
Same, quite a big backlog on my side at Dataiku, so I understand your situation. I can't formally commit, but if I do find the time between now and summer, I will try!
