### ISSUE TITLE
errors with BERT and RoBERTa embeddings

### ISSUE THREAD

**Issue by tvdermeer** [flairNLP/flair#1432]
A clear and concise description of what you want to know.

this is done in a google colab environment with torch 1.4.0 and flair 0.4.5

Hi, I was trying to compare different dutch embeddings (flair, fasttext, BERT and RoBERTa) on the following code: 

`from flair.data import Corpus` 
`from flair.datasets import CONLL_03_DUTCH`
`from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings, FlairEmbeddings, PooledFlairEmbeddings, BertEmbeddings, RoBERTaEmbeddings`
`from typing import List`

```
corpus: Corpus = CONLL_03_DUTCH()

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

# initialize embeddings
embedding_types: List[TokenEmbeddings] = [
    #WordEmbeddings('nl'), # the fasttext embedding for Dutch
    #FlairEmbeddings('nl-forward'), # the Flair embedding for dutch
    #FlairEmbeddings('nl-backward'), # the Flair embedding for dutch but backwards 
    #BertEmbeddings(bert_model_or_path='bert-base-dutch-cased')
    RoBERTaEmbeddings(pretrained_model_name_or_path= 'pdelobelle/robBERT-base')
]

embeddings = BertEmbeddings(bert_model_or_path='bert-base-dutch-cased')

# initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type)

# initialize trainer
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

trainer.train('resources/taggers/example-ner',
              train_with_dev=True,  
              max_epochs=1)
```
adapted from source: https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md

this worked perfectly for the fasttext and flair embeddings... However the BERT embeddings gave the following error message: RuntimeError: CUDA error: device-side assert triggered. 

![Screenshot_bert_1](https://user-images.githubusercontent.com/16362123/74667555-c2ec3300-51a3-11ea-8f8c-2cebcc00cc09.png)
![Screenshot_bert_2](https://user-images.githubusercontent.com/16362123/74667556-c384c980-51a3-11ea-93b3-b1edcd2e329e.png)

i'll attach screenshots of the output

for the RoBERTa embeddings i got the following error-message: IndexError: index 0 is out of bounds for dimension 0 with size 0

![screenshot_roberta_error](https://user-images.githubusercontent.com/16362123/74667365-743e9900-51a3-11ea-8752-bb45b8043ecc.png)

Hopefully this is clear enough and I would gladly take any help I can get!

Thanks in advance!

**Comment by kjans123** [comment]
Hi @tvdermeer, I was having very similar issues, but they were fixed when I truncated my input sentences to less than or equal to 512. I'd forgotten that Bert and Roberta both have a 512 limit on input sequences.
