### ISSUE TITLE
Unable to load best-model.pt on different machine.

### ISSUE THREAD

**Issue by sgoede** [flairNLP/flair#1434]
Hi,

I am trying to load a saved text classification model. This works on my own machine. However, when I let my colleague clone my environment the code fails to execute.  See error code below.

I presume that the model is saved with at least some references to my cached embeddings folder. The issue remains with the latest Flair release.

Any help is greatly appreciated. 

TextClassifier.load('best-model.pt')

PermissionError: [Errno 13] Permission denied: '/home/my_username/.flair/embeddings/nl/nl.wiki.bpe.vs100000.model'

**Comment by sivachaitanya** [comment]
can you elaborate on how did you solved by setting permissions to my user folder's .flair cache path right, - I'm having similar problem when loading the model from folder inside my docker container

**Comment by sgoede** [comment]
It was solved by setting read permission for other users on the particular cached file from the .flair folder in the home folder, also it was needed to set these permissions in all top folders preceding it, up untill root. or '.' .

However, since you want to run it in Docker, this is an unwanted situation. Check if you can download the file within the container itself en cache it from there. The Huggingface integration in Flair should make this possible.
