### ISSUE TITLE
Dependency tree

### ISSUE THREAD

**Issue by sipkecastelein** [flairNLP/flair#1436]
Hi!

For our project, we get all the dependency tags, but we can't seem to make a tree out of it. The value of get_head() is None for every token. Is there a way to get the head from the dependency?

Kind regards,

Sipke

**Comment by djstrong** [comment]
Please elaborate.

**Comment by mkomor** [comment]
Hello!

We are trying to identify dependencies in our text. We are training a model on a dutch corpus UD_DUTCH that includes dependencies. Please see the simplified code:

````
# predict dependencies
DEPtag_type = 'dependency'
DEPtag_dictionary = corpus.make_tag_dictionary(tag_type=DEPtag_type)

DEPtagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=DEPtag_dictionary,
                                        tag_type=DEPtag_type,
                                        use_crf=True)

DEPtrainer: ModelTrainer = ModelTrainer(DEPtagger, corpus)

DEPtrainer.train(...)

````

We use `token.get_tag("dependency").value` to extract the dependency per token.
Our problem is that we get the dependency but not the relation to which word this dependency connects (what is the head for this token?). In the table below you can see word and matching dependency in one row extracted with `get_tag("dependency").value`.

```
Amsterdam | nsubj
is | cop
de | det
hoofdstad | nsubj
```

Now we don't have a link that `nsubj` dependency actually connects "Amsterdam" with "is" (see our source: https://universaldependencies.org/treebanks/nl_alpino/nl_alpino-dep-nsubj.html). Is there a way to extract this information? We tried get_head but it returns None.

Thanks a lot in advance!

**Comment by djstrong** [comment]
Thanks. Flair does not support dependency parsing.

**Comment by alanakbik** [comment]
@mkomor yes, with sequence tagging you can only predict "word-level" tags, i.e. tags that hold for one word (such as part-of-speech, named entity or even dependency type like you did). But sequence tagging cannot predict connections that hold between two words, so like @djstrong wrote it cannot predict dependency connections. For this, we would need a special dependency model which currently is not part of Flair - but we'd be happy if someone from the community added it :) 

Another possibility is to follow this paper on formulating [parsing as sequence tagging](https://www.aclweb.org/anthology/N19-1077.pdf) - we've never tried doing this but if this works one could use the existing sequence tagging model and perform dependency parsing.

**Comment by alanakbik** [comment]
Closing this for now, though we might revisit in the future if/when we add dependency parsing to Flair!
