### ISSUE TITLE
Still get 'GRU' object has no attribute '_flat_weights_names'

### ISSUE THREAD

**Issue by janetlauyeung** [flairNLP/flair#1437]
I was using flair in one of our parsers, and I got the following error:

-     'GRU' object has no attribute '_flat_weights_names'

It seems that it was resolved about a month ago (https://github.com/flairNLP/flair/issues/1377), but I still keep getting this error message. Does anyone know what's going on and have any insights into this? 

Most appreciative! 

<img width="1206" alt="Screen Shot 2020-02-19 at 10 52 10 PM" src="https://user-images.githubusercontent.com/33011322/74899285-79017980-536a-11ea-9436-c43ee9bc6ba4.png">

**Comment by lamhoangtung** [comment]
Having the same problem but for `LSTM`. Pytorch `1.6.0` and latest flair

**Comment by alanakbik** [comment]
Can you share code to reproduce the error?

**Comment by janetlauyeung** [comment]
I solved this by using a previous version of torch: torch == 1.4.0, and the flair version is 0.4.5. Hope this can help!
