### ISSUE TITLE
Targeted Sentiment Analysis? (or Aspect-Based Sentiment Analysis)

### ISSUE THREAD

**Issue by snosrap** [flairNLP/flair#1445]
Flair is great for assessing the sentiment of a sentence or document.

Is there a recommended approach for performing **targeted sentiment analysis** (that is, assessing the sentiment associated with a _particular entity_ in a sentence)?

* This would be useful for online reviews, where different sentiments are expressed about different attributes of the product/service ("the atmosphere was noisy, but the food was great"). See the [SemEval-2014 Task 4 dataset](http://alt.qcri.org/semeval2014/task4/).

* This would also be useful for clinical text, where doctors frequently express different sentiments about medical conditions a patient may or may not have ("Pt denies dyspnea and chest pain, but does endorse palpitations"). The [n2b2 2010 Relations dataset](https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/) focuses on this use case. [BioScope](https://rgai.inf.u-szeged.hu/node/105) is another dataset that focuses on the sentiment associated with  biomedical entities.

Would appreciate your thoughts.

**Comment by alanakbik** [comment]
@whoisjones can you check out the BioScope dataset?
