### ISSUE TITLE
data preparation for custom NER training

### ISSUE THREAD

**Issue by girijesh97** [flairNLP/flair#1448]
Hi All,

I have data like this

{
  "id": 1458,
  "text": "This is the text",
  "meta": {},
  "annotation_approver": null,
  "labels": [
    [
      index_number_start,
      index_number_end,
      "label_1"
    ],
    [
      index_number_start,
      index_number_end,
      "label_2"
    ],
    [
    index_number_start,
      index_number_end,
      "label_3"
    ]
}

where I have an annotation label and its index value. Now, I want to create a custom NER model but I am facing some issues to create the required data format for the training using Flair. 

For eg. label_1 is "White House is big". I want to create tags like this "White" - "B-PLC", "House" - "I-PLC", O, O.
How can I do it based on index value? Also, How can I convert this kind of data for training a custom NER model using Flair.

**Comment by prakashwarbler** [comment]
its json format so u can easily pick the entity and separate it with tagging scheme.  you can write a separate code for this. easy one try it. understand the rules of BIO scheme u can write the code
