### ISSUE TITLE
Language model for Malayalam using Flair Embedding

### ISSUE THREAD

**Issue by aiswaryas-qb** [flairNLP/flair#1456]
I have found that there are no flair embedding models available for the Malayalam language currently.  I have trained a forward and backward language model for Malayalam language and would like to add it to Flair repository.  I am adding the perplexity and validation loss details for both models below.

ml-forward model :
Validation Loss - 1.33
Validation Perplexity - 3.74
Validation Loss on test -  1.16
Validation Perplexity on test - 3.2

ml-backward model:
Validation Loss - 1.32
Validation Perplexity - 3.74
Validation Loss on test  -  1.15
Validation Perplexity on test - 3.16

**Comment by alanakbik** [comment]
Hello @aiswaryas-qb thanks for offering to share your model! 

Probably easiest would be to send me the model files and I will add them to our fileserver and add the download logic. Alternatively, if you prefer to host the model yourself, you could also do a PR that adds the download logic to the FlairEmbeddings class.

**Comment by aiswaryas-qb** [comment]
Hi, @alanakbik Thank you for the quick response. Please let me know how to send you the model files. Will a google drive link be enough?

**Comment by alanakbik** [comment]
Yes, that works - I'll download the models then and put them online!

**Comment by aiswaryas-qb** [comment]
Hi @alanakbik, I have hosted the models and have changed the code accordingly. I have raised a PR against this issue. Thank You

**Comment by alanakbik** [comment]
PR was merged, so closing the issue. Thanks again @aiswaryas-qb!
