### ISSUE TITLE
Why Pooled flair results not better than flair only

### ISSUE THREAD

**Issue by abeermohamed1** [flairNLP/flair#1459]
@alanakbik 

I managed two experiments one using PooledFlairEmbeddings and another one using FlairEmbeddings. why FlairEmbeddings give me better results than pooled one?

any help appreciated.

**Comment by alanakbik** [comment]
It may depend on the problem. In our paper, we found for instance that pooled embeddings don't outperform regular Flair embeddings on WNUT-17. What kind of data are you using and how big are the differences?

**Comment by abeermohamed1** [comment]
Thank you @alanakbik  for the explanation I am using Arabic NEWS Dataset Flair only is better by around 2 percentage.
