### ISSUE TITLE
Deployment in AWS Lambda function

### ISSUE THREAD

**Issue by DannyYCCheng** [flairNLP/flair#1460]
I am trying to deploy a script as a Lambda function in AWS, however the Python packages and model exceed the size limited allowed (250MB). Are there any tricks for deployment in this case?

**Comment by girijesh97** [comment]
You may have to look for something else like flask or django to create an application. Lambda has limitations of size so you can't load all packages. Another approach would be to train your model locally and pickle and then consume it in Lambda.
