### ISSUE TITLE
ner tags prediction on large text with flair-bert

### ISSUE THREAD

**Issue by girijesh97** [flairNLP/flair#1461]
Hi, 
I have a custom NER model with flair using Bert embedding.
I am getting a good F1 score during my training. But, when I am trying to predict the NER tags on my data I am getting the following error.

> RuntimeError: index out of range: Tried to access index 512 out of table with 511 rows. at C:\w\1\s\tmp_conda_3.6_100715\conda\conda-bld\pytorch_1579082902617\work\aten\src\TH/generic/THTensorEvenMoreMath.cpp:418

I read a few issues and found that it is an issue of text length since my text is of `3189` in length. So, I split my text in chunks less than or equal to size of 512.

Using the following line of code.

`tr = textwrap.wrap(txt, 512)`
And then tried to predict tags using following line of code.

```
for i in tr:
    sentence = Sentence(i)
    model.predict(i)
    print(sentence.to_tagged_string())
    print()
```

But the model is not able to predict any tags.

Please help me if doing anything wrong in the above approach or how can I generate NER tags on the long text. As I am using BERT in my embedding layer.

**Comment by alanakbik** [comment]
Hi @girijesh97 it looks like you're not calling predict on the `sentence`, but on `i`. Try changing the line to `model.predict(sentence)`!

**Comment by girijesh97** [comment]
Oh!, that's my bad. Thanks for correcting me.
