### ISSUE TITLE
Is there a plan to create a C4 dataset for German and train various models on that?

### ISSUE THREAD

**Issue by engrsfi** [flairNLP/flair#1462]
Is there a plan to create a C4 dataset for German and train various models on that?

C4 dataset is the cleaner version of the common crawl and can be very useful in creating better embeddings using the existing flair supported models. It's used in Google's T5 model. I asked a question about it in T5 repo and here is the suggestion to create one. The question/answer is described in the following issue.

https://github.com/google-research/text-to-text-transfer-transformer/issues/116

If others are interested, I could help in creating the dataset.

**Comment by stefan-it** [comment]
Hi @engrsfi ,

this sounds very interesting. I did some preliminary with the OSCAR corpus for German (it is also based on CommonCrawl) and can be downloaded (in a shuffled version) from:

https://traces1.inria.fr/oscar/

The deduplicated version has a total size of 145G. But I had one problem with the corpus: it contains rubbish text, urls... so it has to be cleaned (at the some point I got a ppl of > 1000 during training Flair embeddings).

I think with good preprocessing and cleaning steps the OSCAR corpus is a good start for training new Flair embeddings for German!

**Comment by alanakbik** [comment]
@engrsfi @stefan-it sound really interesting - it would be great to train better Flair embeddings for German on such datasets. So any contributions would be very welcome!

**Comment by engrsfi** [comment]
@stefan-it  I looked at the oscar dataset so basically language detection and deduplication is already done there. 

So the main challenge is to decide what do we call rubbish or bad quality. Once we have that then we can adapt the code with relevant preprocessing steps. 

Note: I just know very basic German :)

**Comment by stefan-it** [comment]
Just came up with the following idea: we could iterate over each line in the dataset, use the current Flair Embeddings for German and calculate the ppl for that line. If it's over a specific threshold, the line is not going to be used in the filtered training dataset.

I will look for interesting examples and post them here :)

**Comment by alanakbik** [comment]
@stefan-it that could be a great idea for "bootstrapping" a good text corpus - would be interested to see if this works! The German Flair embeddings would need to be trained over as topically diverse a corpus as possible (but all clean text) for this to work best.

**Comment by engrsfi** [comment]
@stefan-it  Great.

Is it possible to share a very small sample of this oscar dataset (A few MBs maybe)? I would like to look at some of it and see if I can come up with some preprocessing steps besides the filtering based on the high ppl. I am not sure at which level the language detection is applied in this dataset (sentence level or web-page level).  However, I work with German crawled data and most of the time the web-page language is German but it still contains phrases/words in other languages. 

Moreover, sometimes there are just random words from header, footer or navigation panels in the mix of the main body text. I was wondering if filtering out such words/phrases and a proper sentence detection with a minimum sentence length would help improve the resultant embeddings.
