### ISSUE TITLE
GUI not sending the correct path in video analysis

### ISSUE THREAD

**Issue by cineguerrilha** [flairNLP/flair#1465]
**Describe the bug**
launch_DLC

after training and evaluating network, seting video path

**To Reproduce**
Steps to reproduce the behavior (e.g. which model did you train? what parameters did you use? etc.).

just load the video in analyse_video tab
**Expected behavior**

**Screenshots**
    128     start_path=os.getcwd() #record cwd to return to this directory in th
e end
    129
--> 130     cfg = auxiliaryfunctions.read_config(config)
    131     trainFraction = cfg['TrainingFraction'][trainingsetindex]
    132

~\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\utils\auxiliaryfunctions.p
y in read_config(configname)
    111     """
    112     ruamelFile = ruamel.yaml.YAML()
--> 113     path = Path(configname)
    114     if os.path.exists(path):
    115         try:

~\Anaconda3\envs\DLC-GPU\lib\pathlib.py in __new__(cls, *args, **kwargs)
   1020         if cls is Path:
   1021             cls = WindowsPath if os.name == 'nt' else PosixPath
-> 1022         self = cls._from_parts(args, init=False)
   1023         if not self._flavour.is_supported:
   1024             raise NotImplementedError("cannot instantiate %r on your sys
tem"

~\Anaconda3\envs\DLC-GPU\lib\pathlib.py in _from_parts(cls, args, init)
    667         # right flavour.
    668         self = object.__new__(cls)
--> 669         drv, root, parts = self._parse_args(args)
    670         self._drv = drv
    671         self._root = root

~\Anaconda3\envs\DLC-GPU\lib\pathlib.py in _parse_args(cls, args)
    651                 parts += a._parts
    652             else:
--> 653                 a = os.fspath(a)
    654                 if isinstance(a, str):
    655                     # Force-cast str subclasses to str (issue #21127)

TypeError: expected str, bytes or os.PathLike object, not list

**Environment (please complete the following information):**
windows 7

**Additional context**
it is just a string problem c:\\blabla instead c:\blabla

the non gui command works just fine

In [11]: deeplabcut.analyze_videos(cf,[v1], save_as_csv=True)
Using snapshot-100000 for model C:\Users\sanja\Documents\DLC\r1-a1-2020-03-03\dl
c-models\iteration-0\r1Mar3-trainset95shuffle1
Initializing ResNet
INFO:tensorflow:Restoring parameters from C:\Users\sanja\Documents\DLC\r1-a1-202
0-03-03\dlc-models\iteration-0\r1Mar3-trainset95shuffle1\train\snapshot-100000
INFO:tensorflow:Restoring parameters from C:\Users\sanja\Documents\DLC\r1-a1-202
0-03-03\dlc-models\iteration-0\r1Mar3-trainset95shuffle1\train\snapshot-100000
Starting to analyze %  C:\Users\sanja\Documents\DLC\64286.mp4
Loading  C:\Users\sanja\Documents\DLC\64286.mp4
Duration of video [s]:  612.0 , recorded with  50.0 fps!
Overall # of frames:  30600  found with (before cropping) frame dimensions:  192
0 1080
Starting to extract posture
 27%|█████████?                           | 8262/30600 [15:25<49:29,  7.52it/s]

**Comment by alanakbik** [comment]
@cineguerrilha we don't yet support video analysis in Flair, so this was probably mistakenly posted here. Closing the issue, but feel free to reopen if this is related to Flair.
