### ISSUE TITLE
Bert/Roberta Errors

### ISSUE THREAD

**Issue by kjans123** [flairNLP/flair#1466]
Anytime I try to document embed any Bert or Roberta word embedding, I receive CUDA errors. This is very similar to issue #1432 

Relevant code is below:

```
word_embeddings = [XLMRobertaEmbeddings('xlm-roberta-large')]

document_embeddings: DocumentRNNEmbeddings = DocumentRNNEmbeddings(word_embeddings,
                                                                     hidden_size=512,
                                                                     reproject_words=False,
                                                                     reproject_words_dimension=512,
                                                                       bidirectional=True,
                                                                   )


import torch
embeds = []
for ii,i in enumerate(df_c['CMR_TEXT'].values):
    sent = Sentence(i)
    embed = document_embeddings.embed(sent)

    embeds.append(sent.get_embedding().cpu().data.numpy())
    del sent
    del embed
    torch.cuda.empty_cache()
    print(ii)
embeds = np.array(embeds)
np.save('xlm-rob.npy',embeds)
```

With Flair embeddings, the loop performs normally and I can save out any array of document embedding for use in another TF/Keras neural net.

Here are the last few lines of the error trace:
![image](https://user-images.githubusercontent.com/35381053/76102693-5e501700-5f9e-11ea-9577-afbb88791b2a.png)

**Environment (please complete the following information):**
 - OS: Windows 10 (Anaconda)
 - Version: flair 0.4.5

I have tried this on two separate GPU's (1080 Ti and RTX 2080). Both give CUDA errors.

The loop works 12 times and then errors out, regardless if Bert or Roberta embeddings are used.

**Comment by kjans123** [comment]
Closing this issue. I'd forgotten about the 512 sequence limit on Bert and Roberta. Modified this one line of code:
```
sent = Sentence(i[:512])
```
works perfectly now

**Comment by djstrong** [comment]
You are limiting to 512 characters - it is safe, but the limit is 512 subtokens (about 500 words).
