### ISSUE TITLE
Can't run PooledFlairEmbeddings  - unexpected keyword argument 'pool'

### ISSUE THREAD

**Issue by abhisaarsharma** [flairNLP/flair#1470]
**Describe the bug**
I ran into the 'cpu+0' issue described [here](https://github.com/flairNLP/flair/issues/1388) and i did pip install --upgrade git+https://github.com/flairNLP/flair.git so i am on the latest flair version. I am trying to reproduce the state of the art NER results but the given examples are not running.

**To Reproduce**
Run the [CoNLL-03 Named Entity Recognition (Dutch)](https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md)  example

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8f56cacc0e14> in <module>
     16 embedding_types: List[TokenEmbeddings] = [
     17     WordEmbeddings('nl'),
---> 18     PooledFlairEmbeddings('dutch-forward', pool='mean'),
     19     PooledFlairEmbeddings('dutch-backward', pool='mean'),
     20 ]

~\AppData\Local\Continuum\anaconda3\lib\site-packages\flair\embeddings.py in __init__(self, contextual_embeddings, pooling, only_capitalized, **kwargs)
   2107         if type(contextual_embeddings) is str:
   2108             self.context_embeddings: FlairEmbeddings = FlairEmbeddings(
-> 2109                 contextual_embeddings, **kwargs
   2110             )
   2111         else:

TypeError: __init__() got an unexpected keyword argument 'pool'

**Expected behavior**
Expected behavior is reproducing the SOTA results.

**Screenshots**

**Environment (please complete the following information):**
 - OS [Windows]:
 - Version [flair-0.4.5, torch 1.4.0]

**Additional context**

**Comment by abhisaarsharma** [comment]
It seems that the parameter is changed from 'pool' to 'pooling' in PooledFlairEmbeddings.

Please update your documentation when you get a chance, thanks and closing this.

**Comment by djstrong** [comment]
Glad you solved this. Please make pull request with updated document.

**Comment by alanakbik** [comment]
@abhisaarsharma thanks for spotting this - just updated the docs!
