### ISSUE TITLE
Faster CPU inference time: model for 'ner-fast'

### ISSUE THREAD

**Issue by abhisaarsharma** [flairNLP/flair#1474]
I have GPU training capabilities but i wanted to reduce inference time for custom NER models using flair. The tradeoff between 'ner-fast' and 'ner' seems reasonable but can you share the settings/process for creating the faster model (ner-fast)?

I am aware of some suggestions from the opened issues like mini-batching, trying fast FlairEmbeddings/BPE but i was interested to know the exact settings too.

Are there any other strategies for fast inference with FlairEmbeddings on a CPU? Can we have < 10 ms inference per moderate length sentence (< 50 words) on a Cpu?

Thanks,
Abhisaar.

**Comment by alanakbik** [comment]
Hi @abhisaarsharma the 'ner-fast' model uses smaller language models; our standard models have 2048 hidden states and the smaller ones only 1024, which is why they run faster especially on CPU. You could try training even smaller models, say with 512 states, but that would reduce accuracy more.

**Comment by abhisaarsharma** [comment]
Thanks for your reply Alan. I don't know if this is another mismatch in documentation but the [experiments page](https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md) claims it got the sota using much lessed - 256 hidden states.

So am i correct in assuming that the 'ner-fast' model is made with this stacked embedding configuration with 1024 hidden states?

embedding_types: List[TokenEmbeddings] = [
    WordEmbeddings('glove'),
    FlairEmbeddings('news-forward-fast'),
    FlairEmbeddings('news-backward-fast')
]

Thanks,
Abhisaar.

**Comment by alanakbik** [comment]
These are different models: The NER model is built on top of the language model. The NER model does indeed use 256 hidden states, but the language model uses 1024 in the case of 'ner-fast' and 2048 in the case of 'ner'! The language models get loaded as part of the FlairEmbeddings.

**Comment by abhisaarsharma** [comment]
Thanks for your reply!

**Comment by ManyaWadhwa** [comment]
Hey! Is there any paper/resource that I can refer to for looking at the performance trade offs between the ner and ner-fast?  Thanks!

**Comment by alanakbik** [comment]
@ManyaWadhwa there is no paper, but @marcelmmm is currently comparing some models with and without quantization (which increases speed on CPU). The results will be posted in issue #1815.
