### ISSUE TITLE
Non-Euclidean Word Embeddings Evaluation

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1486]
There are some recent papers that compute classic word embeddings in non-Euclidean spaces, namely: 

- [Poincaré GloVe: Hyperbolic Word Embeddings](https://arxiv.org/abs/1810.06546) - embeddings in hyperbolic space
- [Spherical Text Embedding](https://github.com/yumeng5/Spherical-Text-Embedding) - embeddings in spherical space

Both papers evaluate on some intrinsic word embeddings tasks (like WordSim, SimLex, etc.), but we were curious to see if these embeddings help when used in a downstream NLP tasks. Luckily, both papers release embeddings for English trained over a Wikipedia dump, so we plugged them into our default NER architecture on CoNLL-03 to see how they fare. Here are the results, averaged over three runs: 

| Approach                                   | Size  | F1            |
|--------------------------------------------|-------|---------------|
|*Vanilla GloVe models* | ||
| Vanilla GloVe                              | 100D  | **78.62 +- 0.56** |
| Vanilla GloVe + init trick                 | 100D  | 77.93 +- 0.40 |
|*Poincaré GloVe models* | ||
| Poincaré GloVe (cosh-dist-sq)              | 100D  | 70.45 +- 0.53 |
| Poincaré GloVe (cosh-dist-sq) + init trick | 100D  | 71.08 +- 0.38 |
| Poincaré GloVe (dist-sq)                   | 100D  | 71.82 +- 0.21 |
| Poincaré GloVe (dist-sq) + init trick      | 100D  | 74.55 +- 1.14 |
| Poincaré GloVe (cosh-dist-sq)              | 50x2D | 71.22 +- 0.20 |
| Poincaré GloVe (cosh-dist-sq) + init trick | 50x2D | 72.26 +- 0.83 |
|*Spherical models* | ||
| Spherical embeddings                       | 50D   | 73.75 +- 0.78 |
| Spherical embeddings                       | 100D  | 75.90 +- 0.48 |
| Spherical embeddings                       | 200D  | 76.69 +- 0.30 |
| Spherical embeddings                       | 300D  | **77.79 +- 0.33** |

(We deactivated the CRF layer, so results are lower than usual, but the point is to compare them with each other and vanilla "Euclidean" GloVe not to get new state-of-the-art scores.)

When used as drop-in replacements, it seems that none of these embeddings reach the scores of vanilla GloVe, which probably makes sense since our architecture does not leverage hyperbolic space. 

The spherical embeddings work better, in particular with more dimensions. From 50D to 300D we always see a good jump in F1, though even at 300D it does not yet approach a 100D vanilla GloVe. It might be interesting to try a 500D spherical embedding here to see if this improves even further.

**Comment by marcelmmm** [comment]
I got the following results using spherical embeddings up until dimension 500 with the same architecture and corpus (CoNLL-03) :

| Size  | F1 |
| ------------- | ------------- |
| 50D  | 72.24 +- 2,25  |
| 100D  | 76,75 +- 1,07  |
| 200D  | 79,82 +- 0,63 |
| 300D  | 80,29 +- 0,69  |
| 400D  | 81,16 +- 0,40  |
| 500D  | 81,04 +- 0,79  |

We probably have one or two different parameters since my results for 50D-300D are different.
However, one can see another good jump in the F1-score from 300D to 400D. From 400D to 500D it does not increase anymore.
