### ISSUE TITLE
Are flair named entity recognition models MIT-licensed?

### ISSUE THREAD

**Issue by alexcombessie** [flairNLP/flair#1487]
Hi,

Thanks for the good work. I have an important question as I am considering using flair in one of my apps, for named entity recognition.

 Sometimes, python packages have different licenses as the deep learning models they use. So I prefer to be safe and ask 😀 .

Looking at https://github.com/flairNLP/flair/blob/a1ef91a691a9f882fb0d0bd48d04b570f6b0079b/flair/models/sequence_tagger_model.py#L863, can I assume that all models in https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models are MIT Licensed?

Cheers,

Alex

**Comment by alanakbik** [comment]
Flair as a whole is MIT licensed, but I am not sure exactly what this means for models trained over datasets that have different licenses (happy to hear advice if anyone in the community knows). If you want to make 100% sure, probably best would be to acquire licenses for the respective training datasets (if necessary, many data sets are open).

**Comment by alexcombessie** [comment]
Hi Alan,

Thanks for your answer.

From my understanding, models do not inherit automatically the license of the training datasets. Legally speaking, they are standalone "artefacts" with their own license. 

For these NER models, are they trained by your team or by other researchers?

Cheers,

Alex

**Comment by djstrong** [comment]
Models may be considered as derivative works (e.g. language models may be capable of recreation of corpus fragments).

**Comment by alanakbik** [comment]
Most NER models were trained by us, except for the Danish, French and Dutch models.

**Comment by alexcombessie** [comment]
For the models trained by your team, are you ok to consider these as MIT license?

For others you mentioned, do you have contact or hints I could use to determine the license?

Regarding the question of whether models are inherently derivative work, I was not able to find a definitive answer in my research, even speaking to lawyers. That's why I contact directly model makers :) Would you be able to share some information on this topic? I am not a lawyer but interested in the legalese.

**Comment by alanakbik** [comment]
The work we did I am happy to consider MIT licensed, just as @djstrong mentioned I am not sure if models are considered derivative work on the datasets, in this case you would probably need to acquire the datasets to be sure. The Danish models were trained by @AmaliePauli (their data set is free I think), French was trained by @mhham (see #238) and Dutch by @stefan-it (see #224).

**Comment by alexcombessie** [comment]
thanks!

**Comment by alexcombessie** [comment]
Good morning!

@AmaliePauli @mhham @stefan-it would you be able to confirm the licenses of your models, please?

I am writing on this thread to try and centralize information so it can benefit others.

Hope it helps,

Alex

**Comment by AmaliePauli** [comment]
Hi Alex, 
Yes, we also consider the models as MIT license. 
Amalie

**Comment by stefan-it** [comment]
@alexcombessie I always use MIT for my trained models :)

**Comment by alexcombessie** [comment]
@AmaliePauli @stefan-it thanks, that's super helpful!

**Comment by alexcombessie** [comment]
Bonsoir @mhham,

I hope all is well in lockdown. By any chance, would you be able to confirm that the French Flair model is MIT-Licensed as well?

Cheers,

Alex

**Comment by alexcombessie** [comment]
Hi @mhham, Any chance you may look into my question? Thanks, Alex
