### ISSUE TITLE
Training time too slow for each epoch

### ISSUE THREAD

**Issue by Wickky** [flairNLP/flair#1489]
I am using flair to train NER and I tested training using stacked embeddings with bytepair and bert. The problem is one epoch takes around 7 hours. Is it because of very different sentence lengths in the training set?

**Comment by alanakbik** [comment]
Does your machine have a GPU? Whats the size of the NER dataset?

**Comment by Wickky** [comment]
Now the issue is solved by sorting length of the training data.
