### ISSUE TITLE
Add Fine-Tunable Transformers to Flair

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1492]
We currently support word embeddings from Huggingface's various transformer models (BERT, XLM, etc.), but two important features are missing: (1) we don't yet support sentence embeddings extracted directly from the transformer model using the [CLS] token and (2) the transformers currently are not fine-tuneable via Flair. This is a shame since transformers really shine when sentence embeddings are directly extracted from a fine-tuned transformer. 

So with this issue, we want to add

- [x] The ability to get sentence embeddings directly from transformers, by adding new DocumentEmbeddings classes
- [x] The ability to fine-tune all transformer word and document embeddings classes

**Comment by djstrong** [comment]
Supporting longer texts (more than 512 subtokens) would be helpful (at least for prediction). My research show that processing paragraphs rather than sentences decreases error by 10%.

**Comment by alanakbik** [comment]
Yes good point - what is the 'standard' way of working around the 512 subtoken limitation of transformers? I guess easiest would be to truncate the text to max length 512, but maybe there is a better way?

**Comment by djstrong** [comment]
I have in mind sequence tagging so truncating in prediction mode is unacceptable. The text should be divided into splits with some overlapping context and then reconstructed.
For text classification there are some truncating strategies.

**Comment by alanakbik** [comment]
Thanks - yes for `TransformerWordEmbeddings` an overlapping segment strategy should be doable and sounds like the best approach. For `TransformerDocumentEmbeddings` we require a strategy that outputs a single embedding for a text of arbitrary length so maybe truncation is the way to go here.

**Comment by alanakbik** [comment]
Just for reference, some truncation strategies are evaluated [in this paper](https://arxiv.org/pdf/1905.05583.pdf).

**Comment by alanakbik** [comment]
Fine-tuning now part of Flair 0.5.
