### ISSUE TITLE
RuntimeError: Expected object of backend CUDA but got backend CPU

### ISSUE THREAD

**Issue by MarcelCode** [flairNLP/flair#1496]
**Describe the bug**

```
/usr/local/lib/python3.6/dist-packages/flair/embeddings.py in embed(self, sentences)

   3149                 )
   3150 
-> 3151             word_embeddings_tensor = torch.cat(word_embeddings, 0).to(flair.device)
   3152 
   3153             sentence_states = word_embeddings_tensor

RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 61 in sequence argument at position #1 'tensors'
```

**To Reproduce**
I used Google Colab and followed the tutorial you linked on your website:
[How to build a text classifier with Flair](https://towardsdatascience.com/text-classification-with-state-of-the-art-nlp-library-flair-b541d7add21f)

You can use this Notebook for testing: 
[jupyter notebook](https://colab.research.google.com/drive/13n-nGSHdNDpNbX0Ndz5-83uWNmeGhOAD)

For the dataset:
You can download it [here](https://www.kaggle.com/uciml/sms-spam-collection-dataset) 

**Expected behavior**
I expect it to run and it should create a file called "best-model.pt"

**Environment (please complete the following information):**
 - Google Colab
 - Version: 'flair-0.4.5'

It would be really nice if someone could help me. I want to compare different frameworks and do not have a gpu at home.
Thanks in Advance!

**Comment by alanakbik** [comment]
Hello @MarcelCode, this code uses deprecated data loader classes - the entire `NLPTaskDataFetcher` has been deprecated for a while now. You can now read the data in one of two ways: 

1. Use your script to convert to FastText format (as you are currently doing) and read train.csv, dev.csv and test.csv like this: 

```python
corpus = ClassificationCorpus(
    Path('path/to/your/data/folder'),
    train_file='train.csv',
    test_file='test.csv',
    dev_file='dev.csv',
    # set encoding to latin-1 (necessary for this dataset)
    encoding='latin-1',
)
```

2. Read the `spam.csv` file directly - no conversion needed in this case: 

```python
 corpus = CSVClassificationCorpus(
    Path('fath/to/your/data/folder'),
    train_file='spam.csv',
    column_name_map={0: 'label', 1: 'text'},
    encoding='latin-1',
    skip_header=True,
)
```

I just added the ability to set the encoding to the datasets now, so you need to install the current flair version from master branch in order for the above code to work: 

```console
pip install --upgrade git+https://github.com/flairNLP/flair.git
```

**Comment by MarcelCode** [comment]
Hello @alanakbik 
Thank you so much for your fast reply. Its working.
Next Time I'll read the documentation ;-)
