### ISSUE TITLE
TypeError: add_label() missing 1 required positional argument: 'value' for make_label_dictionary() in CSVClassificationCorpus

### ISSUE THREAD

**Issue by mossadhelali** [flairNLP/flair#1498]
**Describe the bug**

The system throws an error at line 909 in datasets.py because sentence.add_label() is missing the label_type argument.
This happens when in_memory=False

**To Reproduce**
1. Make a CSVClassificationDataset corpus with in_memory=False
2. run corpus.make_label_dictionary('label_type')

**Environment (please complete the following information):**
- latest flair version installed with `pip install --upgrade git+https://github.com/zalandoresearch/flair.git`
-pytorch 1.4

**Comment by alanakbik** [comment]
@mossadhelali thanks for reporting this! Just pushed a fix to master branch - does it work now?

**Comment by mossadhelali** [comment]
@alanakbik Yes, it is working now. Thanks!
