### ISSUE TITLE
details about pre-trained web-crawls FastText embeddings

### ISSUE THREAD

**Issue by Pzoom522** [flairNLP/flair#1500]
Hi, much thanks for this wonderful repo!  You have briefly described the FastText embeddings @ "web crawls" [here](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/CLASSIC_WORD_EMBEDDINGS.md):

> You can also always use FastText embeddings over Web crawls

Could you please provide more training details (e.g., __domain of the web crawls__, preprocessing pipeline you used, core hyper-parameters, etc)? I just can't find them in your listed papers...

**Comment by alanakbik** [comment]
Hello @Pzoom522 we used the FastText models available on the FastText website:
-  The [crawl vectors](https://fasttext.cc/docs/en/crawl-vectors.html) were trained over CommonCrawl and Wikipedia. They state there that these models were trained using CBOW with position-weights, in dimension 300, with character n-grams of length 5, a window of size 5 and 10 negatives. 
- The [wiki vectors](https://fasttext.cc/docs/en/pretrained-vectors.html) were trained only over Wikipedia.

You can probably contact the authors to get more details on their training procedure.

**Comment by Pzoom522** [comment]
Thanks for ur reply! 😃
