### ISSUE TITLE
Best way to compare ground truth to predictions for custom metrics with pretrained model?

### ISSUE THREAD

**Issue by ngreenwald89** [flairNLP/flair#1501]
I am trying to do partial match evaluation metrics for an NER model I trained. So I'm trying to compare the truth for a token to the prediction. However, when you run inference on a sentence, the prediction spans seem to overwrite the truth spans, accessed through `sentence.get_spans('ner')`. My hacky solution is to make a `deepcopy` of the sentences I'm running through inference, to save the true spans. Is there a better solution?

`gt = [deepcopy(s) for s in corpus.test]`
 `pred = tagger.predict(corpus.test)`
 `for i in range(len(gt)):`
`    gt_spans = gt[i].get_spans('ner')`
`    pred_spans = pred[i].get_spans('ner')`
`    # compare spans`

**Comment by alanakbik** [comment]
Hello @ngreenwald89 - a potential alternative is to use the procedure we use in the `SequenceTagger.evaluate()` method. Here we give the predicted tags a different identifier, like 'predicted_ner', then gold tag and predicted tag can be accessed separately: 

```python
# load tagger and change tag type name
tagger = SequenceTagger.load('ner')
tagger.tag_type = 'predicted_ner'

# predict tags
pred = tagger.predict(corpus.test)

# evaluate
for i in range(3):
    gold_spans = pred[i].get_spans('ner')
    predicted_spans = pred[i].get_spans('predicted_ner')

    # compare spans
```

**Comment by ngreenwald89** [comment]
Thank you, this works.

**Comment by PieterDujardin** [comment]
@ngreenwald89 
Hi, I myself am also looking to get the predictions out (preferably in a y_pred list) so I can run custom metrics on them. I was wondering if you could share the code that allowed you to get the predictions out,
meaning the implementation of '#compare spans'?
Thanks!

**Comment by ngreenwald89** [comment]
@PieterDujardin I have not yet finished the implementation of custom metrics, so I don't know how helpful this will be. But here's some code to get the predictions out, and span attributes you can work with:
```
y_pred  = tagger.predict(corpus.test)
for y in y_pred:
  pred_spans = y.get_spans('predicted_ner')
  for pred_span in pred_spans:
    pred_text = pred_span.text
    pred_tokens = pred_span.tokens
    pred_indexes = [t.idx for t in pred_tokens]
    # use these to compare to gold_spans
```

**Comment by PieterDujardin** [comment]
@ngreenwald89 
Thanks! I spent an hour now trying to construct the y_pred list, but I don't think I will manage to do it any time soon. Let me know if you succeed!
