### ISSUE TITLE
empty corpus when using CSVClassificationCorpus

### ISSUE THREAD

**Issue by tvdermeer** [flairNLP/flair#1505]
Hi, just as described above, i try to create a corpus from three files (dev, test and train.csv). However the method returns an empty corpus file. In the screenshot I've shown the code and below i show the csv is actually existing and working as intended. 

If anyone has any ideas, please share and thanks in advance!

![image](https://user-images.githubusercontent.com/16362123/78116837-27d2b400-7405-11ea-92a0-ea78bf25bf4a.png)

**Comment by alanakbik** [comment]
Hi @tvdermeer - can you try changing the column_name_map to 
```python
column_name_map = {0: 'text', 1: 'label'}
```
in the map, label names need to be prefixed by 'label'.

**Comment by tvdermeer** [comment]
Thanks @alanakbik, new challenges but this works perfectly now!
