### ISSUE TITLE
Add Biomedical NER data sets

### ISSUE THREAD

**Issue by leonweber** [flairNLP/flair#1513]
This issue tracks the progress of integrating the [HUNER](https://github.com/hu-ner/huner) data – a collection of 34 biomedical NER data sets – into flair.

- [x] BioCreative 2 Gene Mention
- [x] BioInfer
- [x] Biosemantics
- [x] CDR 
- [x] CellFinder
- [x] CEMP
- [x] CHEBI 
- [x] CHEMDNER
- [x] CLL
- [x] DECA
- [x] FSU-PRGE 
- [x] GELLUS 
- [x] GPRO
- [x] IEPA
- [x] JNLPBA
- [x] Linneaus
- [x] Loctext 
- [x] miRNA 
- [x] NCBI disease 
- [x] OSIRIS
- [x] S800
- [x] SCAI chemicals
- [x] SCAI disease
- [x] Variome

**Comment by alanakbik** [comment]
Biomedical datasets and models added in #1790 - thanks @mariosaenger and @leonweber!
