### ISSUE TITLE
WordEmbeddingsStore: add an alternative backend to sqlite based on lmdb

### ISSUE THREAD

**Issue by oterrier** [flairNLP/flair#1514]
The new WordEmbeddingsStore added in 0.4.5 is great to reduce the size of the generated models on the disk but it comes with a runtime performance penalty.

I propose to add an alternative backend to sqlite based on the well known LMDB memory database which is notoriously faster as proved here:
http://symas.com/mdb/microbench/

My proposal is just to add an additional **backend** parameter to the static methods of the original class with 'sqlite' as default value and 'lmdb' as alternative value

```from WordEmbeddingsStore import WordEmbeddingsStore
from flair.models import SequenceTagger
import pickle

tagger = SequenceTagger.load('multi-ner-fast')
WordEmbeddingsStore.create_stores(tagger, backend='lmdb')
pickle.dump(tagger,open('multi-ner-fast-headless.pickle','wb'))

...

tagger = pickle.load(open('multi-ner-fast-headless.pickle','rb'))
WordEmbeddingsStore.load_stores(tagger, backend='lmdb')


```

Best regards

Olivier

**Comment by alanakbik** [comment]
@oterrier sounds great - we very much welcome a contribution!

**Comment by oterrier** [comment]
Pull request added #1515
