### ISSUE TITLE
POS Tagger model for Malayalam Language

### ISSUE THREAD

**Issue by sabiqueqb** [flairNLP/flair#1521]
I have found that there is no POS Tagger model available for the Malayalam language currently. I have trained a model for UPOS Tagging and XPOS Tagging  for Malayalam language and would like to add it to Flair repository. 

The model has trained with more than 30000 sentences and have the average accuracy as follows:
* UPOS Model - 87%
* XPOS Model - 83%

**Comment by alanakbik** [comment]
Hello @sabiqueqb thanks - we'd appreciate the contribution! Would you like to host the model yourself or should we host it on our servers? If the former, you could put in a PR for the new model. If the latter, if you send me the model, I'll put it onto our server and add the PR!

**Comment by sabikla** [comment]
Thank you @alanakbik  for your quick response. I will host the model and will open a PR with the required changes.

**Comment by sabiqueqb** [comment]
Thank you @alanakbik for the quick response. I will host the model and will open a PR with the required changes.

**Comment by sabiqueqb** [comment]
Hi @alanakbik, I have hosted the models and have changed the code accordingly. I have raised a PR (https://github.com/flairNLP/flair/pull/1522) against this issue. Thank You

**Comment by alanakbik** [comment]
Malayalam models are now part of Flair 0.5, just released. Thanks @sabiqueqb!
