### ISSUE TITLE
How does stacking work when One-Hot embeddings are trained on POS ?

### ISSUE THREAD

**Issue by teoML** [flairNLP/flair#1542]
Hello everyone! I am experimenting with NER and I would like to use POS-tags as additional features. I saw that there was already a discussion about a similar problem one year ago and the solution was to create a OneHotEmbedding for the POS tag and then include these POS-embeddings using stacked embeddings. However, what I can not understand is - how is the final word vector created? I mean, when we stack embeddings, as far as I was able to understand it, we concatenate the vectors for the particular word and the resulted vector is further processed. 
In the case of word-based embeddings we can look-up the corresponding word and just take its vector representation according to the model (Word2vec,glove, etc) and concatenate the vectors. But how is this performed when the embeddings are actually the POS-tags ? In the POS-embedding case I would have POS-tags in the dictionary and not words, so actually finding the corresponding POS-vector for a word is not possible. I would be really happy if someone could clarify this for me. Thanks in advance!

**Comment by djstrong** [comment]
POS embeddins have different space than word embeddings.

**Comment by alanakbik** [comment]
Hello @teoML you can only use POS vectors if you know the POS tag of each word. Some datasets, like CoNLL have the POS tag annotated, or you could run a tagger first to generate POS tags for each word. The lookup is then the same as for each word, just that now it always uses the associated POS tag (instead of the word text) to look up a vector.

**Comment by teoML** [comment]
@alanakbik,  @djstrong  - thank you for the fast replies.  I am using the CONLL dataset , so I actually have the POS-tags. However I do not know how to use both, POS-tags and Tokens simultaniously to perform NER.  Could you give me a clue or a short snippet?  Thank you!

**Comment by djstrong** [comment]
Add `OneHotEmbeddings(field='pos')`.

**Comment by teoML** [comment]
@djstrong , I implemented the embedding and stacked it on top of the flair embeddings like that:
```
pos_embeddings = OneHotEmbeddings(corpus=corpus, field='pos_tag')

# initialize embeddings
embedding_types: List[TokenEmbeddings] = [
    FlairEmbeddings('mix-forward'),
    FlairEmbeddings('mix-backward'),
    pos_embeddings
] 
embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)
```
the rest is the same as in your tutorial. However, the final evaluation result with and without the POS-tags was almost the same. Of course, this could be because of the fact that POS- information is to some extent already in the flair-embeddings.
But just to make sure - am I doing something wrong during the stacking ? 

Thanks!

**Comment by djstrong** [comment]
It looks ok.

**Comment by alanakbik** [comment]
Yes, POS information is strongly represented in Flair embeddings so it is unlikely to make much of a difference. Also, datasets like CoNLL-03 do not have gold POS tags, so there are many wrongly assigned POS tags in the training data that could introduce errors as well.

**Comment by teoML** [comment]
@alanakbik  I tagged the dataset using the Flair POS-tagger, not the original CoNLL-03 annotation :)

**Comment by alanakbik** [comment]
Ah yes, then its likely not to add much additional information over using Flair embeddings directly.

**Comment by RatulGhosh** [comment]
Hi,
I'm training a NER on a custom dataset. The data are coming from documents, so along with the token, I'm also using additional features like the x and y coordinates. The data is in the following format:
text x_coordinate y_coordinate tag
I am using OneHotEmbeddings similar to the one mentioned above by @djstrong 

During prediction how should I pass those additional features? Any help would be appreciated.
