### ISSUE TITLE
Balto-Slavic NER

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1543]
There is a [Shared Task on Balto-Slavic NER](http://bsnlp.cs.helsinki.fi/shared_task.html) that provides NER training data for Bulgarian, Czech, Polish and Russian. It would be good to integrate these datasets into Flair and train NER systems with this data.

**Comment by adamjankaczmarek** [comment]
I think, I will be able to help with that. I was one of the participants and I should still have somewhere the data in CoNLL format (2 columns: `text` and `ner`) alongside with the conversion script. There is also a [2017 edition of the Shared Task](http://bsnlp-2017.cs.helsinki.fi/shared_task.html) with seven languages (however without Bulgarian), with slightly different tagging scheme (`PER`, `LOC`, `ORG` and `MISC` - covering more or less the 2019's `EVT` and `PRO`) if you are interested.

**Comment by alanakbik** [comment]
Awesome, yes that would be very much appreciated. It would be great to include the other languages as well!
