### ISSUE TITLE
Pretrained POS tagger on PTB

### ISSUE THREAD

**Issue by ZhaofengWu** [flairNLP/flair#1546]
Hi, your README refers to a PTB POS model that gets 97.85 accuracy, but from [the tutorial page](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md) it seems that the only English model released is trained on Ontonotes. I wonder if the PTB model is released? Thanks!

**Comment by alanakbik** [comment]
Hello @ZhaofengWu yes we only released the model on Ontonotes since it is bigger and covers more domains. I will likely train some more PTB models soon, so I can share them with you if you like.

**Comment by ZhaofengWu** [comment]
That'd be great. Thanks!
