### ISSUE TITLE
Support Pipeline

### ISSUE THREAD

**Issue by rodriguesfas** [flairNLP/flair#1549]
I would like to know if it has pipeline support. I want to process many sentences with a pipeline like this: tagger = SequenceTagger.load ("pos-fast", "ner-fast", "chunk-fast", "frame-fast") is not possible? Do you have another way?

**Comment by djstrong** [comment]
They probably share a language model so it would be helpful to merge models, but it is not possible now.

**Comment by alanakbik** [comment]
Yes, currently you would have to load and run the taggers separately. I agree that better pipeline options would be good - we'll look into it.

**Comment by alanakbik** [comment]
This functionality was added in the latest Flair release. You can use it like this: 

```python
# load tagger for POS, chunking, NER and frame detection
tagger = MultiTagger.load(['pos', 'upos', 'chunk', 'ner', 'frame'])

# example sentence
sentence = Sentence("George Washington was born in Washington")

# predict
tagger.predict(sentence)

print(sentence) 
```
