### ISSUE TITLE
Save checkpoint every N epochs

### ISSUE THREAD

**Issue by WiraDKP** [flairNLP/flair#1551]
I am fine-tuning a flair embedding. It is quite resourceful to save a model for each epoch (`epoch_1.pt, epoch_2.pt, ...`). Is there a way to turn this off? or maybe to save a model every N epochs?

I have tried `checkpoint = False`, but it still saves a model for each epoch.

Here is the sample code I am using
```
lm = FlairEmbeddings('xx-forward').lm
corpus = TextCorpus("corpus/", lm.dictionary, lm.is_forward_lm, character_level=True)
trainer = LanguageModelTrainer(lm, corpus)
trainer.train("output", 10, checkpoint=False)
```

**Comment by alanakbik** [comment]
Currently not since the text corpora we work with to train language models are typically huge to end of epoch does not happen often. Is the corpus you use for fine-tuning very small?

**Comment by WiraDKP** [comment]
Thank @alanakbik for the reply.

Yes, I am using small data for fine tuning, and also thanks, I see the reasoning behind it now. 
On the other hand, what is the difference between checkpoint.pt and those models for each epoch? Are there a reason to save all the models?

**Comment by alanakbik** [comment]
The checkpointing is in case somehow the training process gets interrupted, so that you can resume from the last training state. We saved the models at each epoch for reference, but yes strictly speaking its not necessary.

**Comment by WiraDKP** [comment]
Ok, I think we could let it be for now. Thank you @alanakbik for the reasoning and explanation.
