### ISSUE TITLE
Unable to load trained NER model using bytepair embedding

### ISSUE THREAD

**Issue by vinayakkailas** [flairNLP/flair#1563]
i tried to load the best trained model outside of my training environment to do the prediction. But i am getting path error. It seems like the trained model also freeze the local path where embeddings are stored. The path showing in the error is the local path of training instance.

<img width="1177" alt="Screenshot 2020-05-01 at 10 29 16 AM" src="https://user-images.githubusercontent.com/22210445/80783356-1c56e200-8b97-11ea-91b1-cf7d014eb426.png">

**Comment by alanakbik** [comment]
That looks like a bug. Do you know where the model is downloaded to, i.e. which folder?

**Comment by alanakbik** [comment]
I think this is the same issue as #1483

**Comment by alanakbik** [comment]
@vinayakkailas @abhisaarsharma I just pushed a commit that I think fixes the issue. Could you test this on your setups? Its in branch https://github.com/flairNLP/flair/tree/GH-1563-serializable-bpe

**Comment by Wickky** [comment]
I faced the same error ever after cloning new flair package. Do I need to train new model to be effective?

**Comment by alanakbik** [comment]
Yes and you would need to use this specific branch since the fix is not yet merged to master.

**Comment by Wickky** [comment]
@alanakbik 
Can't I use already trained model?
Because it took several days to train.
I got error when I copied my model to some other machine. 
It's fine as long as I use the same machine for inference that I trained on.

**Comment by WiraDKP** [comment]
Hi @alanakbik ,
I have tried the branch, retrain the model with it, and tried the trained model on other machine, which also use the branch. Unfortunately, It does not work.

Machine for training: ubuntu
Machine for inference: mac osx

Here is some images on the error
<img width="781" alt="image" src="https://user-images.githubusercontent.com/33952122/83487482-4f153280-a4d5-11ea-9524-684b670f3acb.png">

<img width="533" alt="image" src="https://user-images.githubusercontent.com/33952122/83487525-63592f80-a4d5-11ea-86a5-dc77ecf34e38.png">

**Comment by WiraDKP** [comment]
Hi @vinayakkailas @Wickky @alanakbik,

I have found a workaround. Instead of using the default cache_dir to save the byte pair embedding, simply provide our own directory to save the embedding

```
BytePairEmbedding("en", cache_dir="my_byte_pair/")
```
Hence, it won't be OS dependent.
I have tried this and it works best for my purpose.

Hope it helps. Thanks

**Comment by GuillaumeDD** [comment]
Hi @alanakbik ,

I encounter a similar problem with byte pair embeddings. I am currently trying the proposed fix https://github.com/flairNLP/flair/tree/GH-1563-serializable-bpe. Here are my observations.

First, on the training side of the model, setting `flair.cache_root = 'train_resources/'` is NOT taken into account by the`BytePairEmbeddings` class which invariably uses the default directory to download the BPE files namely `$HOME/.flair/`. In other words:
```python
flair.cache_root = 'train_resources/'
# ...
BytePairEmbeddings('fr')
# BPE files are stored into `$HOME/.flair/embeddings/LANG/`
```
is not equivalent to:
```python
BytePairEmbeddings('fr', cache_dir='train_resources/')
# BPE files are stored into `train_resources/`
```

Then, on the tagger side (model usage on a different machine than the training machine), setting `flair.cache_root = 'resources/'` and loading the model `best-model.pt` seem to do the trick : 
- BPE files are not downloaded anymore
- the BPE model is deserialized in the specified `flair.cache_root` directory (e.g., in my case using french BPE the following directories and file get created : `resources/embeddings/fr/fr.wiki.bpe.vs100000.model`)

**Comment by alanakbik** [comment]
@GuillaumeDD interesting observation (and sorry for the late reply). This must have something to do with the constructor argument using a global variable, see https://github.com/flairNLP/flair/blob/19241fa6ae88e3e2fa2152cadddd0a56497bfff8/flair/embeddings/token.py#L1562 

Maybe the variable is somehow pre-loaded so it does not use the overwritten `flair.cache_root`. I'll try to fix this.
