### ISSUE TITLE
TransformerDocuementEmbedding does not take flair.device

### ISSUE THREAD

**Issue by junhua** [flairNLP/flair#1567]
By setting `flair.device = torch.device('cuda:0;)`, it throws an error saying `expected device cpu  but got device cuda:0`. I have to explicitly set `TextClassifier(...).to(torch.device('cuda:0')` to make it happen

**Comment by alanakbik** [comment]
Hm that should not happen since the `TextClassifier` moves itself to flair.device when calling the constructor. Can you post a full code example to reproduce?

**Comment by junhua** [comment]
There:

```
import torch
from torch.optim.adam import Adam

from flair.datasets import CSVClassificationCorpus, ClassificationCorpus
from flair.data import Corpus
from flair.embeddings import (WordEmbeddings, FlairEmbeddings, TransformerDocumentEmbeddings )
from flair.models import TextClassifier
from flair.trainers import ModelTrainer

flair.device = torch.device('cuda:0')
flair.cache_root = './cache'

document_embeddings = TransformerDocumentEmbeddings('bert-base-uncased', use_scalar_mix=True)

corpus: Corpus = ClassificationCorpus(data_folder,
                                          test_file='test.txt',
                                          dev_file='val.txt',
                                          train_file='train.txt')

label_dict = corpus.make_label_dictionary()

classifier = TextClassifier(document_embeddings, 
                                label_dictionary=label_dict, 
                                multi_label=False))

trainer = ModelTrainer(classifier, corpus, optimizer=Adam, use_tensorboard=True)

trainer.train(result_folder,
                  max_epochs=200, 
                  embeddings_storage_mode='gpu',
                  learning_rate = 1e-3,
                  mini_batch_size = 32,
    )
```

**Comment by alanakbik** [comment]
Thanks! Can you also verify that your GPU is visible? 

Does the following print out True?
```python
import torch
print(torch.cuda.is_available())
```

**Comment by junhua** [comment]
Yes - I've been training using Flair's document embedding and text classification for multiple tasks..

**Comment by alanakbik** [comment]
Hello @junhua thanks for sharing the script - the error comes from setting `use_scalar_mix=True`. This option should only be used if not fine-tuning document transformer embeddings. But since you are fine-tuning, you should use `use_scalar_mix=False`. 

Still, we have to change this so that this error does not occur. I'll investigate and do a PR.
