### ISSUE TITLE
MemoryError when loading ‘en-sentiment’

### ISSUE THREAD

**Issue by 87bdharr** [flairNLP/flair#1568]
Hey, when loading the ‘en-sentiment’ dataset into a TextClassifier object, I keep getting a memory error:

![image](https://user-images.githubusercontent.com/45598743/80868492-ded77f00-8c92-11ea-85eb-224d2c28cefb.png)

I suspect this may be because of the size of the dataset being loaded. I have taken a look at issue 351 but don’t see an immediate answer.

**Environment (please complete the following information):**
 - OS: ipadOS
 - Version flair 0.4.5

**Comment by alanakbik** [comment]
Hm strange, maybe the model is too large for your memory setup. Can you try this one: 
```python
TextClassifier.load('de-offensive-language')
```

**Comment by 87bdharr** [comment]
> Hm strange, maybe the model is too large for your memory setup. Can you try this one: 
> 
> ```python
> 
> TextClassifier.load('de-offensive-language')
> 
> ```
> 
> 

The offensive language one seems to load fine:
![image](https://user-images.githubusercontent.com/45598743/80870767-91faa500-8ca0-11ea-9c4f-844bb5987ff2.png)

My ipad is probably not suited for the other dataset then

**Comment by stefanievonk** [comment]
How do you know how much memory is needed to load a model into memory?
