### ISSUE TITLE
CRF feature function

### ISSUE THREAD

**Issue by teoML** [flairNLP/flair#1573]
Hello! My question is: how does the CRF decoder works like and particularly - what is the feature function ?
As far as I know, in a CRF model  each feature function has the arguments:
1. a sentence s
2. the position of a word in the sentence
3. the label of the current word
4. the label  of the previous word

How is the feature function  of the CRF layer implemented in flair ?

**Comment by alanakbik** [comment]
This CRF was impemented a long time back by my colleague @blythed who can probably more details.
