### ISSUE TITLE
Extreme memory usage on GPU server when using FLAIR NER model

### ISSUE THREAD

**Issue by igormis** [flairNLP/flair#1574]
I have trained a NER model with FLAIR, which occupies around 2GB of memory, when loaded. However, when I infer the RAM usage on the GPU server with CUDA 10.2 constantly grows and it reached 20GB after 18 hours of responses. This is strange, as it should clean the RAM memory after the response? Is there any command to do that?
I am just loading the model using
`model = SequenceTagger.load('./nlu_en/final-model.pt')` 
and predict using:
```
sentence = Sentence(text)
model.predict(sentence)
predict_dict=sentence.to_dict(tag_type='ner')
```

**Comment by djstrong** [comment]
Could you post whole code for prediction?

**Comment by igormis** [comment]
```
from flair.models import SequenceTagger
from flair.data import Sentence
import time
import json
import re
# load the model you trained
model = SequenceTagger.load('./nlu_en/final-model.pt')
def tag_span(data):
	sentence = Sentence(text)
	model.predict(sentence)
	predict_dict=sentence.to_dict(tag_type='ner')
	entities = predict_dict['entities']
	new_entities=[]
	for entity in entities:
		if entity['type']=='ticker':
			continue
		e={}
		e['start']=entity['start_pos']
		e['end'] = entity['end_pos']
		e['value']=entity['text'].replace("'s", "").replace("`s", "").replace("’s", "")
		e['entity'] = entity['type']
		new_entities.append(e)
	d['entities']=new_entities
	d['text']=predict_dict['text']
	return d
```
And I am using `PooledFlairEmbeddings` while training the model

**Comment by igormis** [comment]
@djstrong IN addition I am using this version of FLAIR (as @mauryaland suggested):
`pip install --upgrade git+https://github.com/flairNLP/flair.git `
because the fix has been merged after the last release.
As this branch is using GPU for inference, only the word dictionary is kept on CPU memory in the new version (as @alanakbik  suggested).

**Comment by igormis** [comment]
@alanakbik this is the issue that I am facing when executing the tag_span() function as a POST method in a gunicorn server, any ideas from where the memory leak could come? it increased the usage from 4.8GB to around 6.5GB for several hours, it seems that some data is kept.

**Comment by alanakbik** [comment]
Yes, PooledFlairEmbeddings have a memory that grows over time. It records previous mentions of words. So each time, a new word is encountered, the memory is expanded to collect knowledge on this word. See [our paper](http://alanakbik.github.io/papers/naacl2019_embeddings.pdf) for details. 

For long-running applications you therefore need lots of memory. Generally, PooledFlairEmbeddings are not optimized, so for actual applications we always suggest using normal FlairEmbeddings.

**Comment by alanakbik** [comment]
Closing issue, but feel free to reopen if you have more questions.

**Comment by igormis** [comment]
Hi @alanakbik I solved the problem by switching to FlairEmbedding, however with the new model trained with Glove and FlairEmbeddings, I have again memory leaks on the GPU, the modes still increases in GPU memory when inferring.
![image](https://user-images.githubusercontent.com/6599037/101183226-8238aa00-364f-11eb-8a95-ddbe025270e6.png)
I am using FLair==0.5 and PyTorch==1.6.
Any help on this?

**Comment by alanakbik** [comment]
It it a slow continuous increase or does it sometimes suddenly jump? If its the latter, it could be that a very long sentence occurs in the data - in such cases it will reserve more memory to accommodate the long sentence and not let it go again.

**Comment by igormis** [comment]
Yes it is a sudden jump of 100 MB (more or less) and it does not release the memory after this, so in a certain period it can grow. However I cut the input text before inference to 4096 characters (so the text is between 1 and 4096 characters, which is not so long?). I doing the cutting using this line
`output = nlu.tag_span_token(data[:4095])`
 Is there any hints on how to release the memory?

**Comment by alanakbik** [comment]
I think there are some torch commands you could try for releasing GPU memory. Haven't used them though so not sure how well they work.

**Comment by igormis** [comment]
I was wondering if `embeddings_storage_mode` would help?

**Comment by andy311p** [comment]
@igormis can you share your solution? i am facing the same problem...

**Comment by igormis** [comment]
@andy311p currently I am trying this command:

**Comment by igormis** [comment]
@andy311p  it solves the problem, the model grows during prediction afterward it reduces to its original size
