### ISSUE TITLE
How to find the number of trainable parameters?

### ISSUE THREAD

**Issue by teoML** [flairNLP/flair#1601]
Hi !I have a more specific question and it is - how to find out (calculate) the number of trainable weights in the default BiLSTM-CRF ? I am somehow confused and would be grateful for any help!

**Comment by alanakbik** [comment]
There is a code snippet listed in #1302. Maybe this works for you? You should use simple WordEmbeddigs instead in this code snippet because otherwise it will count the BERT model parameters.

**Comment by teoML** [comment]
@alanakbik  I still can not understand how to find the number of trainable params... The snippet in the link gives me a really big number 27 129 115 (when I use flair embeddings).

**Comment by djstrong** [comment]
27M may be right.
