### ISSUE TITLE
Can i know how DocumentPoolEmbedding works?

### ISSUE THREAD

**Issue by hsysfan** [flairNLP/flair#1609]
I wanna know DocumentPoolEmbedding's logic for using it

Im using it in my research. but i cant find how DocumentPoolEmbedding works in any documents.

assume that there are some sentences with different size.

I want use DocumentPoolEmbedding for calculating cosine similarity with different 2 seneteces.

how does DocumentPoolEmbedding work in 2 sentences with different sizes?

padding? or mean of all word vectors?

I saw some results have 300 dimension

but i cant understand how DocumentPoolEmbedding makes the result

thank you for reading

**Comment by petulla** [comment]
Did you look at the [tutorial?](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_5_DOCUMENT_EMBEDDINGS.md) It has a description of the math.

**Comment by hsysfan** [comment]
you mean "pooling" part?

i read it all already but i cant understand it.

i will read one more time.

thank you for answer. petulla.
