### ISSUE TITLE
Use new Hugging Face datasets library

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#1615]
Hi,

Hugging Face released a new awesome library: `datasets`. It contains "Datasets and evaluation metrics for natural language processing":

https://github.com/huggingface/datasets

I'm currently working on integrating some NER datasets.

So the main aim would be to use the `datasets` library instead of writing own dataset classes in Flair :)

**Comment by stefan-it** [comment]
I will start on integrating the GermEval 2014 dataset into `nlp`.

Then the next step will be to use this dataset from `nlp` instead of our own:

https://github.com/flairNLP/flair/blob/f41ee042c603177da6a36734d93f11bb95b7b563/flair/datasets/sequence_labeling.py#L579

class.

**Comment by alanakbik** [comment]
Awesome!

**Comment by stefan-it** [comment]
GermEval 14 is now available (latest `master` version of `nlp`) - WNUT 17 is on its way. So I'll think about a nice integration of it into Flair.

I'm not sure if it's ready for the upcoming 0.5 release of Flair, because there are discussions about the name `nlp`, see [this issue](https://github.com/huggingface/nlp/issues/138) 😅

**Comment by alanakbik** [comment]
Oh yes makes sense to change the name to something more specific ;)
