### ISSUE TITLE
Training NER for new language 

### ISSUE THREAD

**Issue by rockiram** [flairNLP/flair#1619]
I want to do NER for tamil language. I understood how to train the language model. 
1.How to extract the POS tag for tamil language? 
2.If I want to train POS tagger model seperately, please suggest me some reference?

**Comment by alanakbik** [comment]
Check out [this tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-sequence-labeling-model) how to train a POS tagger.

**Comment by rockiram** [comment]
Thank you!! My issue is solved.
