### ISSUE TITLE
Keyphrase Extraction Dataset

### ISSUE THREAD

**Issue by whoisjones** [flairNLP/flair#1621]
There are 3 datasets available for keyphrase extraction via sequence labeling from IIIT-Delhi:
[Keyphrase Datasets](https://github.com/midas-research/keyphrase-extraction-as-sequence-labeling-data)

I would like to add all three sets to the sequence labeling functionality of flair.

- [x] [Inspec](https://github.com/midas-research/keyphrase-extraction-as-sequence-labeling-data/tree/master/Inspec) 

- [x] [SemEval-2017](https://github.com/midas-research/keyphrase-extraction-as-sequence-labeling-data/tree/master/SemEval-2017) 

- [x] [Processed SemEval-2010](https://github.com/midas-research/keyphrase-extraction-as-sequence-labeling-data/tree/master/processed_semeval-2010) 

<img width="1121" alt="keyphrase-stats" src="https://user-images.githubusercontent.com/38491117/82667075-65023800-9c37-11ea-9584-5a26420f064f.png">

**Comment by whoisjones** [comment]
Stats of corpora:

INSPEC files:
`{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 4423,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 137086,
            "min": 1,
            "max": 172,
            "avg": 30.993895546009497
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 2080,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 65221,
            "min": 1,
            "max": 339,
            "avg": 31.35625
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 2032,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 64258,
            "min": 1,
            "max": 206,
            "avg": 31.623031496062993
        }
    }
}`

SEMEVAL 2017:
`{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 2305,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 63013,
            "min": 1,
            "max": 142,
            "avg": 27.33752711496746
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 764,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 21267,
            "min": 2,
            "max": 113,
            "avg": 27.836387434554975
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 386,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 10872,
            "min": 1,
            "max": 117,
            "avg": 28.16580310880829
        }
    }
}`

SEMEVAL 2010:
`{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 882,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 23293,
            "min": 1,
            "max": 92,
            "avg": 26.409297052154194
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 749,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 19919,
            "min": 4,
            "max": 85,
            "avg": 26.594125500667555
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 98,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 2629,
            "min": 7,
            "max": 57,
            "avg": 26.8265306122449
        }
    }
}`

**Comment by whoisjones** [comment]
`--------------------------------------------------
INSPEC DATA
--------------------------------------------------
{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 1000,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 141508,
            "min": 15,
            "max": 557,
            "avg": 141.508
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 500,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 67300,
            "min": 23,
            "max": 384,
            "avg": 134.6
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 500,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 66291,
            "min": 16,
            "max": 330,
            "avg": 132.582
        }
    }
}`

**Comment by whoisjones** [comment]
Stats of the datasets in flair:

```
--------------------------------------------------
INSPEC DATA
--------------------------------------------------
{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 1000,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 141508,
            "min": 15,
            "max": 557,
            "avg": 141.508
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 500,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 67300,
            "min": 23,
            "max": 384,
            "avg": 134.6
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 500,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 66291,
            "min": 16,
            "max": 330,
            "avg": 132.582
        }
    }
}
--------------------------------------------------
SEMEVAL2017 DATA
--------------------------------------------------
{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 350,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 65318,
            "min": 65,
            "max": 350,
            "avg": 186.62285714285716
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 100,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 22031,
            "min": 102,
            "max": 389,
            "avg": 220.31
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 50,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 11258,
            "min": 137,
            "max": 399,
            "avg": 225.16
        }
    }
}
--------------------------------------------------
SEMEVAL2010 DATA
--------------------------------------------------
{
    "TRAIN": {
        "dataset": "TRAIN",
        "total_number_of_documents": 882,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 23096,
            "min": 1,
            "max": 92,
            "avg": 26.1859410430839
        }
    },
    "TEST": {
        "dataset": "TEST",
        "total_number_of_documents": 749,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 19919,
            "min": 4,
            "max": 85,
            "avg": 26.594125500667555
        }
    },
    "DEV": {
        "dataset": "DEV",
        "total_number_of_documents": 98,
        "number_of_documents_per_class": {},
        "number_of_tokens_per_tag": {},
        "number_of_tokens": {
            "total": 2826,
            "min": 9,
            "max": 85,
            "avg": 28.836734693877553
        }
    }
}
```

**Comment by pommedeterresautee** [comment]
You may also check Ms Marco from Microsoft (keyphrase extraction task).
https://microsoft.github.io/msmarco/

The dataset is big and of very high quality.
