### ISSUE TITLE
plot_weights figsize referenced before assignment

### ISSUE THREAD

**Issue by cod3licious** [flairNLP/flair#1622]
`# figsize = (16, 16)` in [line 125 of Plotter.plot_weights](https://github.com/flairNLP/flair/blob/master/flair/visual/training_curves.py#L125) should be uncommented or the if statement below should be changed, otherwise this can throw `UnboundLocalError: local variable 'figsize' referenced before assignment`.

**Comment by alanakbik** [comment]
Oha yes, care to do a PR? ;)
