### ISSUE TITLE
Batch at get_representation is evaluated in a wrong order?

### ISSUE THREAD

**Issue by bratao** [flairNLP/flair#1630]
Hello, I´m trying to understand the Flair embedding. During my debug, I found something unexpected to me. 

At the function `get_representation()` on `language_model.py`, it chunks every sentence in a batch every `chars_per_chunk`
Consider a batch with two sentences of length 6
["THIS IS A FIRST LONG STRING",
"NOW THAT IS A DIFFERENT ONE"]

Considering chars_per_chunk to be 3. The output is processed as:
batch 1 = ["THIS IS A", "NOW THAT IS"]
batch 2 = ["FIRST LONG STRING", "A DIFFERENT ONE"]

However in this way, every sub-sequence is using a hidden state from a unrelated sentence. 
I would expect this instead:

batch 1 = ["THIS IS A", "FIRST LONG STRING"]
batch 2 = ["NOW THAT IS", "A DIFFERENT ONE"]

There is a motivation that the batching is done this way? @alanakbik

**Comment by djstrong** [comment]
It is not working like this. Did you run this code or only read?

**Comment by bratao** [comment]
That is true. My bad @djstrong .
I didn't now knew that Pytorch LSTM can work with per batch parallel hidden states.
