### ISSUE TITLE
Is there anyway to use the flair with dkpro?

### ISSUE THREAD

**Issue by pidugusundeep** [flairNLP/flair#1631]
there are several existing annotators with dkpro but is there a way I could use flair as a tagger to get NER in dkpro?

**Comment by alanakbik** [comment]
Would be interested in this as well. If someone has a working example, please share :)

**Comment by pidugusundeep** [comment]
@alanakbik  Have you worked on dkpro earlier?

**Comment by alanakbik** [comment]
A bit but quite a while ago. Still, I'd be interested if integration is possible.

**Comment by pidugusundeep** [comment]
I was able to integrate with https://github.com/dkpro/dkpro-cassis. I would be willing to know if there is any alternative way.
