### ISSUE TITLE
Q. Do we have to set `embeddings` in the SequenceTagger Class?

### ISSUE THREAD

**Issue by Kyubyong** [flairNLP/flair#1641]
Hi, according to the explain [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md), I guess we need to set the `embeddings` parameter to any of the prebuilt ones. I want to know if we can skip it. In my work, we don't have any prebuilt token/word embeddings.

**Comment by djstrong** [comment]
You can not skip it, but you can use OneHotEmbeddings - they will be learned from scratch.

**Comment by alanakbik** [comment]
You could also try a combination of `OneHotEmbeddings` and `CharacterEmbeddings` - both will be learned from scratch during model training.
