### ISSUE TITLE
Changing embedding size

### ISSUE THREAD

**Issue by mustafa-yavuz** [flairNLP/flair#1658]
I d like to know if its possible to change the vector size of document embedding. I already tried `news-forward-fast` and `news-backward-fast` which have 2098 embedding sizes. Is it possible to change a parameter somewhere to make it like 300 ?  As far as i know, vector size is a parameter for most of the text-to-vector mappings. Thank you.

**Comment by alanakbik** [comment]
Do you mean in the `DocumentPoolEmbeddings`? In the `DocumentPoolEmbeddings` you can only control this behavior by choosing smaller embeddings. Are you interested in the vectors themselves or are you using these embeddings to train a model?
