### ISSUE TITLE
Better model format for portability

### ISSUE THREAD

**Issue by qiuwei** [flairNLP/flair#166]
Hi, first of all, a massive thanks for the great library!

At the moment I am trying to integrate flair with Allennlp. I needed to reimplement the language model to expose some compatible interfaces. However, the pretrained language models are coupled with your implementation(It seems torch load requires the exact directory structure)

I am wondering whether you could provide a more portable format for sharing the pre-trained models? Just like what Elmo or openai-transformer-lm did.

Thanks in advance!

**Comment by alanakbik** [comment]
Hi @qiuwei - that's great, thanks!

The `LanguageModel.load_language_model()` method only loads the state dictionary of the trained LM, together with the vocabulary dictionary and the model parameters. So I do not believe we require any specific directory structure. Still, we'll check out the Elmo and openai implementations - if there's a good format that enables better portability that would be great and we'd be happy to include it into the next release!

**Comment by alanakbik** [comment]
Oh I see - yeah we'll definitely look into this, probably already for the next release. Of course, any help is always appreciated :)

**Comment by qiuwei** [comment]
@alanakbik I have come up with a workaround to this issue.
We can save the models in three parts:
1 . a file which contains the dictionary, which simply mirrors the idx2tem inside the Dictionary
2. a json file which describes the language model init parameters, such as is_forward_lm, hidden_size, etc
3. the actual state_dict 
This would make it possible to reuse the pre-trained models with even Tensorflow.

**Comment by alanakbik** [comment]
@qiuwei this sounds great! Is this something you'd be interested to add in a PR with the release-0.4 branch?

**Comment by qiuwei** [comment]
@alanakbik Sure, I will have a look at this during the weekend.
