### ISSUE TITLE
Add support for Sentence Transformers

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1660]
The [sentence transformers](https://github.com/UKPLab/sentence-transformers) library has great pre-trained models to produce embeddings for entire sentences. 

We should add a new `DocumentEmbeddings` class to support these embeddings in Flair.

**Comment by shameelct** [comment]
This commit does not cover contextual word embedding as in other transformer model support right? Any plans to add that?

**Comment by alanakbik** [comment]
Not sure if I understand - can you elaborate?

**Comment by shameelct** [comment]
The following is how a BERT embedding can be used in Flair to obtain contextual word embedding as far as I understand:
from flair.data import Sentence

```
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')
sentence = Sentence('The grass is green .')
bert_embedding.embed(sentence)
for token in sentence:
print(token)
print(token.embedding)
```

Is there a way to obtain contextual word embedding from Sentence Transformer using Flair.

**Comment by alanakbik** [comment]
Sentence transformers are trained to give an embedding for the whole sentence, so getting single word embeddings is currently not possble through Flair. For words, regular transformer embeddings will probably be better.

**Comment by shameelct** [comment]
Cool thanks
