### ISSUE TITLE
Not able to download the new datasets of flair 

### ISSUE THREAD

**Issue by DivyaGupta1989** [flairNLP/flair#1664]
While trying to download the dataset using the command mentioned below, I am not able to do so: sentiment_140 = flair.datasets.SENTIMENT_140()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-5e8cfec20052> in <module>
----> 1 sentiment_140 = flair.datasets.SENTIMENT_140()

AttributeError: module 'flair.datasets' has no attribute 'SENTIMENT_140'

**Comment by alanakbik** [comment]
Are you sure you're on version 0.5?

**Comment by DivyaGupta1989** [comment]
Yes.. version is 0.5 only

**Comment by alanakbik** [comment]
@DivyaGupta1989 thanks for reporting this! This is a bug - we didn't add the new datasets to the `datasets.__init__.py` file. You can still load them like this: 

```python
from flair.datasets.document_classification import SENTIMENT_140
sentiment_140 = SENTIMENT_140()
```

I'll also put in a PR to fix this!

**Comment by DivyaGupta1989** [comment]
It worked. Thank you so much for your help

**Comment by alanakbik** [comment]
PR merged - thanks again for reporting this!
