### ISSUE TITLE
ColumnDataset class with in_memory==True opens input table every time a new __get_item__ is done is made.

### ISSUE THREAD

**Issue by allenciox** [flairNLP/flair#1669]
To be removed, once it is done: Please add the appropriate label to this ticket, e.g. feature or enhancement.

**Is your feature/enhancement request related to a problem? Please describe.**
So the ColumnDataset class implements __get_item__ method as opening and closing the input data every time it is called.  Shouldn't it open the table only once and keep its handle available?  Or is it a problem to implement it that way?

**Describe the solution you'd like**
Obviously you don't know when trainer is going to start calling __get_item__ to get samples in a batch, and when it is going to stop.  I suggest having a file_handle attribute, and initially setting it to None on instantiation of the class.   Then it checks to see if there is already a file_handle attribute set when it is called, and only open the file when that is the case.  Then create a __del__ method that closes the table to make sure it is properly closed when the class instance is garbage-collected. 

 

**Additional context**
I did check the efficiency of this code:
%%timeit
for samp in range(999) :
            with open(file, encoding='utf-8') as f:
                pos=line_offset[random.randint(0,len(line_offset)-1)]
                f.seek(pos)

compared to this:

%%timeit
with open(file, encoding='utf-8') as f:
     for samp in range(999) :
                pos=line_offset[random.randint(0,len(line_offset)-1)]
                f.seek(pos)

The second variiant is 50 times as fast as the first one with a 62 MB file.  So opening and closing tables often exerts a huge cost.

I don't know if there are other reasons why having a file handle would be a problem, for instance, having multiple processors doing data loading.  Please let me know if that is why this is being done this way.

**Comment by alanakbik** [comment]
Hi @allenciox there is multiprocessing involved in which the get_item() method is called by multiple workers at the same time to speed up the disk reads. This unfortunately means that the file handle has to be contained in the method - otherwise the seeks from multiple processes would cause problems.

**Comment by allenciox** [comment]
Wouldn't it be possible, however, for there only to be handles for each worker, rather than each request?

**Comment by alanakbik** [comment]
I'm not sure if this is possible with the `DataLoader` methods in torch, but if possible that would be great!
