### ISSUE TITLE
How to decode a word embedding to a word token?

### ISSUE THREAD

**Issue by junhua** [flairNLP/flair#1670]
Does Flair allow decoding a word embedding vector to a word token?

**Comment by alanakbik** [comment]
Not sure if I understand. Could you provide an example of what you want to do?

**Comment by junhua** [comment]
Say I have an word embedding vector [0.3, 1.5, ...] and I want to convert it to a word token 'hi'

**Comment by alanakbik** [comment]
Oops sorry for the late reply - this is currently not implemented in Flair. You could look at `gensim` which I think has such functionality to retrieve the nearest words to a vector.
