### ISSUE TITLE
How to store intermediate embeddings for later cosine similarity comparison.

### ISSUE THREAD

**Issue by brinew27** [flairNLP/flair#1673]
Hi all,

I'm trying to use Flair to calculate sentence embeddings for reddit posts, then use cosine similarity to compare with a user's entered text.

Calculating the embeddings is obviously the longest part of the process, and so I'm wanting to loop through the reddit posts, calculate sentence level embeddings, then save the embeddings (ie back to the dataframe that is storing the posts), so that later when a user enters a sentence, I only calculate the embeddings for their text, then can just iterate through the stored reddit embeddings and calculate cosine similarities to find the most similar post.

My question is, what's the best method to store these embeddings alongside the reddit posts in my dataframe so that they can be pulled back together for comparison? When I do:

```python
for sentence in string2array:
        sentenceobject = Sentence(sentence)
        embeddings.embed(sentenceobject)
        print(sentenceobject)
```

Each embedded sentence comes back as "Sentence: "I'm at home i can't sleep"   [− Tokens: 6]" which doesn't seem like a format that can be saved to a dataframe column for later quick retrieval. Is there a best practice for this type of thing or a better approach?

Thanks!

**Comment by alanakbik** [comment]
Hi @brinew27 you could save only the text (as a string) and the embedding of each sentence:

```python
for sentence in string2array:
    sentenceobject = Sentence(sentence)

    text = sentenceobject.to_plain_string()
    embedding = sentenceobject.embedding

    print(text)
    print(embedding)
```

The embedding is a PyTorch tensor that you could convert to a numpy array or a list.
