### ISSUE TITLE
How to prepare dataset for longer text?

### ISSUE THREAD

**Issue by jtnimma** [flairNLP/flair#1702]
I am parsing documents which are not proper english sentences and length more 1000 chars. Below is the sample data 
*******
Account Number: 12345
Contact Name: Lisa
Adress:
yyyyyyy
xxxxxxx
Ref: nnnnn
long text here with proper sentences.
********
I can't make sentences so can i keep whole document as one sentence and separate with \n\n for the next document in the train.txt?

**Comment by alanakbik** [comment]
What task do you want to do with this data? Train a language model, or text classification?

**Comment by jtnimma** [comment]
I want to train NER model to extract account numbers and company name which is in the long text. 
This is the first time i am using this API.  Can you also clarify me one more thing. I am creating training data files for ner:  train.txt, test.txt, dev.txt with 2 columns, word and label. Usually we give train and test dataset. why do we need to give dev dataset?

**Comment by alanakbik** [comment]
You can find instructions on how to format the data [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-your-own-sequence-labeling-dataset) and how to train a model [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-sequence-labeling-model). 

A dev dataset is not necessary. If none is provided, it will be sampled automatically from the train data. If you set the option `train_with_dev=True` on the `ModelTrainer`, you will not use a dev set.

**Comment by jtnimma** [comment]
i did understand the format of the NER dataset from your tutorials. I am trying to understand does flair work well without sentence boundaries like my dataset which contains documents without proper sentences. Each document vary from 1000 chars to 4000 chars. So i just want to separate each document with a new line. is that alright?.

**Comment by alanakbik** [comment]
Ah yes I think that would work. The only problem is that the sequence labeling format does not support newlines in documents, so you might miss an important feature. But given how regular the dataset is, maybe the newlines do not matter so much, so you can definitely try without.
