### ISSUE TITLE
Changing embedding storage mode to GPU when using optimizer

### ISSUE THREAD

**Issue by lfdharo** [flairNLP/flair#1704]
When looking for the hyper-parameter optimizations for a textclassifier, it is not possible to change the default behavior of using 'cpu' storage mode to 'gpu' storage mode which could speed up the process.

**Comment by alanakbik** [comment]
Do you mean using the hyperparameter selection methods? This part of the code is currently not maintained since we want to refactor it completely, but when we do we'll definitely include the option of setting storage mode.

**Comment by lfdharo** [comment]
Right. When I'm using the hyperparameter selection there are some default parameters we cannot set. I guess we can just modify it in the code.

**Comment by alanakbik** [comment]
That would be best for now! But we'll keep it in mind when we rebuild the hyperparameter selection methods.
