### ISSUE TITLE
Q. Can we get more than one prediction value in the text classification task?

### ISSUE THREAD

**Issue by Kyubyong** [flairNLP/flair#1705]
Hi, I guess by default, classifiers return the best prediction result and its score.
I wonder if we can get more than that, that is, top n values. For example,

>>> print(sentence.labels)
["dog (0.5)", "cat (0.3)", duck (0.2)]

**Comment by alanakbik** [comment]
Hi @Kyubyong yes, if you set `multi_class_prob=True` you get all classes and their confidence, e.g.:

```python
tagger.predict(sentence, multi_class_prob=True)
```

**Comment by Kyubyong** [comment]
@alanakbik Thanks!!
