### ISSUE TITLE
Reproducing "Contextual String Embeddings for Sequence Labeling"

### ISSUE THREAD

**Issue by xuhdev** [flairNLP/flair#1708]
Currently the [experiment page](https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md) only shows how to reproduce the latest state-of-the-art results (which I believe corresponds to "Pooled Contextualized Embeddings for Named Entity Recognition"). Can someone confirm that the following code would correspond to the approach that is used in "Contextual String Embeddings for Sequence Labeling"?

```python
from flair.data import Corpus
from flair.datasets import CONLL_03
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings, FlairEmbeddings
from typing import List
import torch

# 1. get the corpus
corpus: Corpus = CONLL_03(base_path='resources/tasks')

# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary.idx2item)

# initialize embeddings
embedding_types: List[TokenEmbeddings] = [

    # GloVe embeddings
    WordEmbeddings('glove')
    ,
    # contextual string embeddings, forward
    FlairEmbeddings('news-forward')
    ,
    # contextual string embeddings, backward
    FlairEmbeddings('news-backward')
]

embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=False)

# initialize trainer
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

trainer.train('resources/taggers/akbik2018-ner', mini_batch_size=32, max_epochs=150,
              train_with_dev=True)
```

**Comment by pascalhuszar** [comment]
There are several different setups in the paper. The best one for English is: `PROPOSED+WORD+CHAR` 
So i would guess the embeddings types as: 
```

    # GloVe embeddings
    WordEmbeddings('glove')
    ,
    # Character embeddings
    CharacterEmbeddings(),
    ,
    # contextual string embeddings, forward
    FlairEmbeddings('news-forward')
    ,
    # contextual string embeddings, backward
    FlairEmbeddings('news-backward')
```
Glove was mentioned in **Stacking Embeddings.** and **'new- '** is the 1M corpus. These should be right. The `CharacterEmbeddings(),` is just a guess, based on `[...]+`**CHAR**

**Comment by alanakbik** [comment]
Yes that is the correct code to reproduce our experiments. I'm planning to re-write this section in the documentation to make a distinction between current best setup and published setups.

**Comment by xuhdev** [comment]
@alanakbik I'm confused. I believe there are two papers:

- Akbik, et al. 2018, Contextual String Embeddings for Sequence Labeling
- Akbik, et al. 2019, Pooled Contextualized Embeddings for Named Entity Recognition

I thought the [experiment page](https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md) describes Akbik 2019 and https://github.com/flairNLP/flair/issues/1708#issuecomment-648012846 describes Akbik 2018?

**Comment by alanakbik** [comment]
Yes that's the case. Use `FlairEmbeddings` for the 2018 paper and `PooledFlairEmbeddings` for 2019.

**Comment by xuhdev** [comment]
If you can point out where you would like to add those instructions, I'm happy to make a PR.
