### ISSUE TITLE
Model Accuracy

### ISSUE THREAD

**Issue by AndyZhaoly** [flairNLP/flair#1710]
Hi 

I am just wondering why is flair always predict extreme negative or positive sentiments?  Is there any potential mistakes I have done with loading/using the pre-trained model?

<img width="1044" alt="Screen Shot 2020-06-22 at 6 33 48 PM" src="https://user-images.githubusercontent.com/26240706/85350799-f2df7600-b4b6-11ea-82f9-ab84717050a6.png">

**Comment by alanakbik** [comment]
Hi @AndyZhaoly the value is the confidence of the estimation, not the severity of the sentiment. If you get high confidence scores it simply means that the model is confident that something is negative, but it does not tell you _how_ negative it is.
