### ISSUE TITLE
Which strategy to use for CUDA: Out Of Memory ERROR due to large training data size?

### ISSUE THREAD

**Issue by plc-dev** [flairNLP/flair#1715]
I'm currently running into the CUDA OOM error for training data sizes over ~10.000 sentences for a NER task.
I am using the BERT multilingual cased model, although I shifted to the distilled version in the hopes of reducing the needed memory with no success thus far.

Also I am using the in_memory=False flag when initializing the Corpus, which still results in the same error.

The other parameters I know of currently that might reduce memory is the mini_batch_size and embeddings_storage_mode.
I incrementally set the batch size to lower values, but even a value of 2 doesn't seem to help the issue.
And the storage mode is set to "None", although this should only affect regular RAM usage and not the VRAM of the GPU right?

I've also tried truncating the maximum length of the sentences even further, where the maximum amount is now 350 tokens, as tokenized by the BERT tokenizer.

Are there any other ways to counter this issue? 

I thought about slicing my full training set (~120.000 sentences/110 MB) into subsets that fit into the maximum amount of sentences I've experienced so far (around the 10.000 mark) and incrementally train the model, but I'm uncertain what side effects that might introduce, besides potential overfitting to each subset and "unlearning" of previous subsets.

Sorry if this is a potential duplicate, I've sifted through previous issues with similar descriptions but found no solution thus far.

**Comment by alanakbik** [comment]
Hello @plc-dev it looks like you are following all the right steps. You're right that setting the storage mode from "cpu" to "none" only affects CPU memory. As does in_memory=False by the way.

You could try a `mini_batch_chunk_size` of 1 and try a higher `mini_batch_size`, but if even mini batches of size 2 do not work, there is maybe little hope here. 

You could try filtering your corpus not by token length, but by number of characters as this more directly correlates to the amount of subtokens the different BERT models will give you. In the master branch there is a method to filter long sentences that you could try on your data: 
```python
corpus.filter_long_sentences(250)
```

Maybe it fits in memory then?
