### ISSUE TITLE
ELMoEmbeddings checkpoint pickling error with Flair0.4.5

### ISSUE THREAD

**Issue by sankaran45** [flairNLP/flair#1723]
Google colab by default has torch 1.5.1 and when i install allennlp and try ELMoEmbedding after 1st epoch this error occurs. This occurs with Flair 0.5 and if i go back to Flair 0.4.5 this works just fine. 

/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_save(obj, f, pickle_module, pickle_protocol)
    441     pickler = pickle_module.Pickler(f, protocol=pickle_protocol)
    442     pickler.persistent_id = persistent_id
--> 443     pickler.dump(obj)
    444 
    445     serialized_storage_keys = sorted(serialized_storages.keys())

AttributeError: Can't pickle local object 'ELMoEmbeddings.__init__.<locals>.<lambda>'

**Comment by alanakbik** [comment]
I believe this is already fixed in master branch, see #1692. Will be part of the upcoming release.
