### ISSUE TITLE
type object 'TextClassifier' has no attribute 'load_from_file'

### ISSUE THREAD

**Issue by qijunhui** [flairNLP/flair#1728]
from flair.models import TextClassifier
from flair.data import Sentence

classifier = TextClassifier.load_from_file("./best-model.pt")
sentence = Sentence("Hi. Yes mum, I will...")
classifier.predict(sentence)
print(sentence.labels)

**Comment by alanakbik** [comment]
This was changed a few flair version ago. You should now use 
```python
classifier = TextClassifier.load("./best-model.pt")
```
