### ISSUE TITLE
ELMoEmbeddings not working

### ISSUE THREAD

**Issue by Alea4jacta6est** [flairNLP/flair#1729]
Hello! I have the same bug trying to use ELMoEmbeddings, I guess the reason might be in the new release of allennlp library, am i right?
```UnboundLocalError: local variable 'allennlp' referenced before assignment```

_Originally posted by @Alea4jacta6est in https://github.com/flairNLP/flair/issues/597#issuecomment-652643892_

**Comment by alanakbik** [comment]
Hello @Alea4jacta6est you have to install `allennlp` by running `pip install allennlp`.

**Comment by Alea4jacta6est** [comment]
![image](https://user-images.githubusercontent.com/26580860/86453309-3db68480-bd26-11ea-8ff0-781d299f3b4f.png)
You can see at the screen that i just 
`Successfully installed allennlp-1.0.0 jsonnet-0.16.0 jsonpickle-1.4.1 overrides-3.0.0 tensorboardX-2.0 tokenizers-0.7.0 transformers-2.11.0`

**Comment by alanakbik** [comment]
Hmm just updated to the latest `allennlp` locally and it still works. Can you try running a python shell and doing `import allennlp` - does this work?

**Comment by AlphaCaprice** [comment]
Yep, I have the same issue. Have the latest `allennlp` installed.

**Comment by alanakbik** [comment]
Ok I see the issue now. Looks like something has changed in 1.0 that breaks our code.

It also seems the latest `allennlp` is incompatible with `transformers` 3.0. They specify `transformers>=2.10,<2.11`as requirement.

**Comment by alanakbik** [comment]
It looks like support for the `ELMoEmbedder` class was removed in allennlp 1.0, see https://github.com/allenai/allennlp/issues/4384. 

They suggest installing an earlier version, i.e. `pip install allennlp==0.9.0`.

**Comment by stefan-it** [comment]
@alanakbik I will update the install command with this fixed 0.9.0 version for `ELMoEmbeddings` in a PR now :)
