### ISSUE TITLE
How large to make val/test files for embeddings training?

### ISSUE THREAD

**Issue by petulla** [flairNLP/flair#1730]
Hi

The train folder seems like it will be much larger than the test/val files, if I understand the instructions? I'll be training on many gb of text. I'm wondering if there's a recommended test/val data size for LM fine-tuning/training.

**Comment by alanakbik** [comment]
Yes, we typically put most of our data into different train chunks. The test/val chunks can be small. For orientation, you can check out the [1 billion word corpus](https://opensource.google/projects/lm-benchmark).
