### ISSUE TITLE
AttributeError: 'CharLMEmbeddings' object has no attribute 'chars_per_chunk'

### ISSUE THREAD

**Issue by qijunhui** [flairNLP/flair#1731]
from flair.data import Sentence
from flair.models import SequenceTagger

sentence = Sentence("I love Berlin .")

tagger = SequenceTagger.load("/home/hadoop/.flair/models/en-ner-conll03-v0.2.pt")

tagger.predict(sentence)

####
Also, can the model download link be provided?

**Comment by alanakbik** [comment]
The old models from flair 0.2 no longer work, you should use the newest ones. Can you do `SequenceTagger.load('ner')` instead?
