### ISSUE TITLE
Document pool embedding

### ISSUE THREAD

**Issue by fatimabs** [flairNLP/flair#1737]
Dear all, 
i want to embedd a sentence using Flair, i used the class DocumentPoolEmbedding, i just need to know how it works especially with the words that have more than one vector. It is the mean of all vectors of the words containing the sentence ?

**Comment by alanakbik** [comment]
Yes, the pooling does a mean over all word vectors in the sentence.

**Comment by fatimabs** [comment]
thanks a lot for your response, 
but what is the main difference between document pool embedding and stacked embedding for sentence embedding?

**Comment by alanakbik** [comment]
Stacking concatenates all embeddings of a word into one long vector. Sentence pooling does a mean over all word embeddings in the sentence.
