### ISSUE TITLE
Recommended way to remove OOV tokens

### ISSUE THREAD

**Issue by artdgn** [flairNLP/flair#1742]
Hi, and thanks for this great package :+1:  .

I've been using the pre-trained sentiment analysis models, and I've noticed that out of vocabulary words have sometimes quite a big influence on the score, and for low scores even the resulting polarity.

Can you recommend a way to sanitize OOV token before making the predictions? I've tried looking around in docs, issues, and the code and didn't find an obvious lead.

Some examples:

```python
import flair

# fast model
fast = flair.models.TextClassifier.load('sentiment-fast')

fast.predict(flair.data.Sentence('this is a curious sentence'))
> result: POSITIVE (0.6022)

# with some random token
fast.predict(flair.data.Sentence('nvadjkfv: this is a curious sentence'))
> result: NEGATIVE(!) (0.5592)

# default model
slow = flair.models.TextClassifier.load('sentiment')

slow.predict(flair.data.Sentence('this is a curious sentence'))
> result: POSITIVE (0.907)

# with some random token
slow.predict(flair.data.Sentence('nvadjkfv: this is a curious sentence'))
> result: POSITIVE (0.9877)

# a different random token
slow.predict(flair.data.Sentence('opaopepr: this is a curious sentence'))
> result: POSITIVE (0.7859)
```

Note: I've tried using `use_tokenizer=True`, and it helps with some issues, but in all those cases above, it has no effect (presumably because the token is OOV and is encoded at character level, which doesn't make sense in those cases).

**Comment by artdgn** [comment]
For whoever is interested / having similar issue, how to get to the vocabulary seems to depend on the model and embeddings used (and there's no API for it AFAIS. Yet? PR?)

Sample workaround code I've found to work for the current pretrained sentiment analysis models (does seem to help with my data):

#### Extracting it:
```python
# for 'sentiment-fast' RNN model
raw_vocab = (model.document_embeddings.embeddings.embeddings[0]
             .precomputed_word_embeddings.index2word)

# for 'sentiment' Transformer model
raw_vocab = list(self.model.document_embeddings.tokenizer.vocab.keys())
```

#### Filtering with it:
```python 
# basic filtering of various non words
word_re = re.compile(r'[a-z A-Z]{2,}')
vocab_filt = [w for w in vocab_raw if word_re.fullmatch(w)]

# for faster filtering - store this somewhere on your objects
vocab = set(vocab_filt)

# filtering the sentences before running them through model.predict()
for sent in sentences:
    sent.tokens = [t for t in sent.tokens if t.text in vocab]

model.predict(sentences, use_tokenizer=True)
```

--------

#### Would still of course be happy to hear any ideas about this OOV issue from other people more familiar with the package.

**Comment by alanakbik** [comment]
Hello @artdgn thanks for sharing this method. The current fast sentiment model has no handling for OOV words - I guess OOV words were commonly negative words in the training data so maybe the model now assumes that any OOV word means that a sentence is negative. Once the serialization issues with the byte pair embeddings are fixed (another embedding type in Flair) maybe we can retrain this model to get better with such words. 

The slow model on the other hand has handling of oov words (BERT splits words into subtokens) so it works better here.

**Comment by artdgn** [comment]
Hi @alanakbik, thanks for looking into this, I do have some questions about your interpretations above:

> .. I guess OOV words were commonly negative words in the training data so maybe the model now assumes that any OOV word means that a sentence is negative. ...

Doesn't the different impact of different OOV words make this an unlikely explanation? Wouldn't it make more sense in this case for all OOV words to have similar impact?

-------------

> The slow model on the other hand has handling of oov words (BERT splits words into subtokens) so it works better here.

Why do you consider a difference of 0.987 vs 0.785 due to a random difference as "it works better here", is it because the resulting polarity is the same? It would still make a big difference on any downstream handling of the score (as 0.987 is very close to full certainty).

-------------
This is not to criticize the resulting models at all, I think it's tremendously helpful to have powerful models working out of the box.

But wouldn't you agree that for being useful "in the wild", some OOV sanitization methods are needed for both models (perhaps even more so for the "slow" model due to the smaller vocabulary of just 32K tokens) given those examples?

**Comment by alanakbik** [comment]
Hello @artdgn yes however the oov words are handled differently in the two models. In your example on the fast tagger, the oov causes polarity to go negative. So it could be that this model has learned that oov tokens indicate that something negative. So in this case it may make sense to have some approach to deal with oov tokens outside the model.

The other (slower) model handles oov tokens differently by splitting them into subwords and trying to make sense of them. That is generally the better approach, so it works better in your examples. Ideally, at least for the BERT model, no sanitation should be required.

**Comment by artdgn** [comment]
Thanks @alanakbik I see your point, although it's quite possible that with these particular examples the transformer didn't flip polarity, but with another random set it would. Even in these examples the difference in the probability scores is similar in magnitude, and is actually larger for the transformer (0.9877 - 0.7859 = 0.2 for transformer, and 0.6022 - (1 - 0.5592) = 0.16 for RNN), although the ratio of the scores is larger for the RNN (25% vs. 36%). 

I think the more important question is whether you think in the model / embeddings APIs it could be useful to have a vocabulary property? And perhaps for Sentences / Corpuses in could be valuable to accept a vocabulary parameter for sanitisation just as they accept a tokeniser parameter for tokenising?
