### ISSUE TITLE
Incorrect corpus name for swedish

### ISSUE THREAD

**Issue by bohanzhou** [flairNLP/flair#1750]
Hello,

First of all, thank you for this awesome library 😄 

I want to inform you that the instructions for loading the swedish corpus (#1652) is incorrect in the release notes for version 0.5.1
In the release notes it is stated that you load the corpus with `corpus = SWEDISH_NER()`. However the correct way should be `corpus = NER_SWEDISH()`  

Hopefully this will save time for others trying to find the problem

**Comment by alanakbik** [comment]
Ah oops, thanks for reporting this - just corrected it!
