### ISSUE TITLE
Choosing how to choose tag_type for custom tagging system

### ISSUE THREAD

**Issue by Michael95-m** [flairNLP/flair#1754]
Hello, I'd like to ask about how to choose parameter **tag_type** for custom sequence labeling training task . For my sequence labeling task, there are only two tags, B (begin tag) and I (inner tag). Currently I choose '**ner**' for tag_type in this  training task. But in my mind, are there any options about tag_type for this kind of task??

**Comment by djstrong** [comment]
Tag_type is a name of column with tags if you have more features.

**Comment by Michael95-m** [comment]
@djstrong the reason why I ask for this question is that I'd like to know what should I give tag_type for my task.(eg. POS or NER) But my case is neither POS nor NER, just chunking of the word. When I give the 'chunk' to tag_type, it gets some error.

**Comment by Michael95-m** [comment]
@djstrong By your answer, I think it doesn't matter the value of tag_type. It's just the name of the column. Am I right??

**Comment by djstrong** [comment]
Yes.

**Comment by Michael95-m** [comment]
Thanks for your kind answer @djstrong
