### ISSUE TITLE
Is it possible to create something like sense2vec using flair?

### ISSUE THREAD

**Issue by santoshbs** [flairNLP/flair#1755]
I am new to flair and would like to make use of this wonderful implementation for my research. I see great value in contextually-keyed word vectors that explosion's sense2vec python implementation provides. Given the greater accuracy of flair, I am keen to use flair instead of spacy + sens2vec. Is it possible for me to create word2vec embeddings of latest Wikipedia corpus with pos and ner tags, and then use these word embeddings to make queries such as return all words that are most similar to 'Elon_Musk|PERSON',  'University_of_Michigan|ORGANIZATION', or 'London|PROPN'? 

Thank you!
sbs

**Comment by alanakbik** [comment]
Interesting idea - yes that should be possible. You can run the Flair 'pos' and 'ner' models to tag a Wikipedia dump and then use sense2vec to train and visualize the vectors.

**Comment by petulla** [comment]
@santoshbs how would you convert the word2vec embeddings to sense2vec embeddings though? as alanakbik mentions, you might be able to modify the first step in sense2vec training. you'd just need to convert the flair spans to spacy Docs. I'm wondering if you could just use the [spacyTokenizer](https://github.com/flairNLP/flair/blob/871f43377ab2245c7a32c426360cf21f12f405b4/resources/docs/TUTORIAL_1_BASICS.md) to do as much.

**Comment by santoshbs** [comment]
Thank you @alanakbik  and @petulla. I am not sure how to do what you are suggesting. I still don't know how to mix flair with sense2vec.

**Comment by petulla** [comment]
Which part is confusing? I'd read the training steps for sense2vec and take a look at my comment.

**Comment by santoshbs** [comment]
Thanks, @petulla . I am not sure how to get the whole wiki corpus decorated with ner tags using flair. I see that for each sentence I can print the entities and their tags. But is there a way using which I can read the corpus and add flair identified entity tags to the text in the corpus?
