### ISSUE TITLE
reduce memory usage by sharing embeddings between multiple classifiers

### ISSUE THREAD

**Issue by mondor** [flairNLP/flair#1757]
A clear and concise description of what you want to know.
Hi there,

Thank you for sharing this wonderful library to the world. I have a question regarding using this library for inferencing. 

We have multiple classifiers running on the same inferencing API server, all the classifiers were loaded into memory when the application starts, all classifiers were using the same embedding. 

In order to minimise the memory usage on the server, is there anyway we can share the embeddings between multiple classifiers? 

```python
word_embeddings = [WordEmbeddings('en'), BytePairEmbeddings('en')]

classifier1 =  TextClassifier(
        DocumentRNNEmbeddings( 
                word_embeddings,
                hidden_size=128,
                reproject_words=True,
                reproject_words_dimension=128
        ), 
        label_dictionary=[a, b],
        multi_label=True
) 
classifier1.load_state_dict(torch.load(...))

classifier2 =  TextClassifier(
        DocumentRNNEmbeddings( 
                word_embeddings,
                hidden_size=128,
                reproject_words=True,
                reproject_words_dimension=128
        ), 
        label_dictionary=[c, d, e, f, g],
        multi_label=True
)
classifier2.load_state_dict(torch.load(...))

classifier3 =  TextClassifier(
        DocumentRNNEmbeddings( 
                word_embeddings,
                hidden_size=128,
                reproject_words=True,
                reproject_words_dimension=128
        ), 
        label_dictionary=[h,i,j,k],
        multi_label=True
) 
classifier3.load_state_dict(torch.load(...))
 
```

If I am understanding it correctly, the embeddings weight is static, non-trainable, and they are not saved into the classifier's checkpoint file, whereas the RNN layer (DocumentRNNEmbeddings) and Fully connected layer are uniquely to each classifier. Would loading the classifiers this way reduce the memory foot print for this API server?

Appreciate your helps.

**Comment by alanakbik** [comment]
Hello @mondor this might work. Perhaps this would be a simpler alternative: 

```python
classifier1 =  TextClassifier.load('your/first/model')

classifier2 =  TextClassifier.load('your/second/model')
classifier2.document_embeddings.embeddings = classifier1.document_embeddings.embeddings

classifier3 =  TextClassifier.load('your/third/model')
classifier3.document_embeddings.embeddings = classifier1.document_embeddings.embeddings
```

Essentially, your giving the embeddings of the first model to all other models. Haven't tested it though. Does it work for you?

**Comment by alanakbik** [comment]
We've added an implementation for multiple SequenceTagger to the master branch that follows this strategy of re-using embeddings to save memory and do faster inference. See #1791 for more details!
