### ISSUE TITLE
Training Custom NER Model

### ISSUE THREAD

**Issue by sayak1711** [flairNLP/flair#1760]
I want to train a custom ner model. I have followed this tutorial for the same: https://medium.com/thecyphy/training-custom-ner-model-using-flair-df1f9ea9c762
But I want to know how do I tell flair which base model to use? I want to keep both the ner-onotonotes knowledge and the new ners I provide in dataset?

**Comment by jtomek** [comment]
I have exactly the same question. I would like to add a category "KPIs" that would recognize "Revenue", "EBIT", etc...

**Comment by jtomek** [comment]
I bought prodi.gy. It works.

**Comment by vrunm** [comment]
@sayak I am also trying something similar. Is there any way to specify the base model?
