### ISSUE TITLE
GPU use when using "upos-fast" tagger

### ISSUE THREAD

**Issue by jinyongyoo** [flairNLP/flair#1773]
Hi, I'm currently trying to use `SequenceTagger.load("upos-fast")` to do part-of-speech tagging. I purposely chose the fast version because I'm using GPU for another job, but I'm seeing GPU usage by flair. Is this suppose to happen, and if so, is there a way to force flair to not use GPU. 

Also, I think this might have been suggested by other people, but is it possible to allow users to specify which GPU they want to use for their models?  Global `flair.device` is quite limiting for cases where I'm trying to use multiple GPUs.

**Comment by j-heinze** [comment]
It is possible using `flair.device`. You can specify cpu usage: `flair.device = torch.device('cpu')`. And you can specify which cuda gpu (in this case 5) to use: `flair.device = torch.device('cuda:5')`.  
I am also interested in potential drawbacks while switching on the fly though. I hope this helps.

```Python
flair.device = torch.device('cpu')
pos_taggerEN = SequenceTagger.load('pos')
flair.device = torch.device('cuda:0')
taggerEN = SequenceTagger.load('ner-ontonotes')

sentences = [Sentence(sent, use_tokenizer=True) for sent in split_single(data['corpus'])]

#Call the flair.device again before using the tagger.
flair.device = torch.device('cpu')
pos_taggerEN.predict(sentences)
```
