### ISSUE TITLE
Is TransformerDocumentEmbeddings sentence length is limited to 512 tokens? 

### ISSUE THREAD

**Issue by olanag1** [flairNLP/flair#1774]
Hello, 

In the class _TransformerDocumentEmbeddings__ in the method __add_embeddings_to_sentences_ there is an indication that the sentence is truncated up to 512 tokens (max_length=512). 

> 
             # subtokenize sentences

            for sentence in sentences:
                # tokenize and truncate to 512 subtokens (TODO: check better truncation strategies)
                subtokenized_sentence = self.tokenizer.encode(sentence.to_tokenized_string(),
                                                              add_special_tokens=True,
                                                              max_length=512,
                                                              truncation=True,
                                                              )

So, is only 512 tokens are taken into account in order to calculate the sentence embeddings ? Or the whole document is divided on the sequences of 512 tokens and then all the document is parsed to get the final embedding? I mean, in the case if the document is longer than 512 tokens.

Another question, how the token is determined, is it a character, word, sub-word ? 

Thank for your help :)
And thanks for a developer team, very useful library :)

**Comment by Moiddes** [comment]
I wanted to ask the same question, since `allow_long_sentences=True` was added as a flag to `TransformerWordEmbeddings`, is it possible to transfer this behaviour to TransformerDocumentEmbeddings?
I'm generating DocumentEmbeddings using `TransformerDocumentEmbeddings` in order to represent the Sentence using the CLS-Token and with `DocumentPoolEmbeddings` and `TransformerWordEmbeddings` in order to represent the sentence using mean pooling. It would be very helpful to be able to use longer sequences with both strategies.

**Comment by djstrong** [comment]
For `TransformerDocumentEmbeddings` the text is truncated to 512 (usually) subtokens. It is not trivial to add `allow_long_sentences`.

**Comment by stefan-it** [comment]
I think we should allow to set a user-defined value (constructor?!). because e.g. the [LongFormer](https://arxiv.org/abs/2004.05150) model supports a sequence length up to 4096 subtokens.

**Comment by GDBSD** [comment]
I getting an error "_Token indices sequence length is longer than the specified maximum sequence length for this model"_ . I attempt to truncate the sentence with the code block below. How can I truncate the sentence so as not to get this error?

        raw_text = raw_text.translate(str.maketrans('', '', string.punctuation))
        text_list = raw_text.split()
        text_list = text_list[0:500]
        raw_text = ' '.join(text_list)
        sentence = Sentence(raw_text)
        tagger.predict(sentence)

**Comment by alanakbik** [comment]
@GDBSD the maximum length refers to "subtokens", meaning a single word might be split into several subtokens. So if you limit your text to 500 words, some of them might be split, taking the total over 512. To be completely sure that subtokenization does not take you over 512, you could truncate your text to 512 characters.

**Comment by GDBSD** [comment]
Got it - thanks.
