### ISSUE TITLE
GloVe embeddings type

### ISSUE THREAD

**Issue by maximrus23** [flairNLP/flair#1779]
Hi, 
Which type of pre-trained embeddings is going out of the box when you specify 'glove'? Is there a way to specify how many dimensions to use?

**Comment by alanakbik** [comment]
Hi @maximrus23 we package the 100 dimensional embeddings of GloVe trained over gigaword and wikipedia, made available on their web site. The other embeddings are not pre-packaged in Flair, but you can download them manually and load them with the WordEmbeddings class.
