### ISSUE TITLE
How to do chunking?

### ISSUE THREAD

**Issue by losiu97** [flairNLP/flair#1781]
As one of benchmarks you cite:
Chunking | English | Conll-2000 | 96.72 (F1) | 96.36 (Peters et al., 2017)
However, i cannot find any way to simply apply chunking to a document using Flair (it is I think not described in the docs)

**Comment by youssefavx** [comment]
I am also wondering how to go about this. Would love any help whatsoever.

**Comment by parajain** [comment]
Check this:
https://gist.github.com/parajain/8ea763737aa99719e8d32df1a6cc2d16

**Comment by losiu97** [comment]
Thank you, but it would still be nice to have this functionality described in documentation

**Comment by youssefavx** [comment]
Fantastic! Thank you so much, really appreciate it.

**Comment by parajain** [comment]
@alanakbik Do you think it would be fine to have an example directory where it is easier to add examples? That can later be transferred into documentation if needed?
I looked at the tutorial section and I am not sure if adding a small snippet would be a good idea.
