### ISSUE TITLE
Fail to download DANE() dataset

### ISSUE THREAD

**Issue by maziyarpanahi** [flairNLP/flair#1782]
**Describe the bug**
The command `flair.datasets.DANE()` fails with 403 status code

**To Reproduce**
```python
import flair.datasets

flair.datasets.DANE()
```
**Expected behavior**
It should download the Danish NER datasets in train, dev, and test.

**Screenshots**
![image](https://user-images.githubusercontent.com/5762953/88786970-774aa600-d193-11ea-8ba7-88b37b0347ff.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: macOS Catalina
 - Version [e.g. flair-0.3.2]: 0.5.1

**Additional context**

**Comment by alanakbik** [comment]
@maziyarpanahi thanks for reporting this - I am getting the same error.

**Comment by maziyarpanahi** [comment]
Thanks @alanakbik for the follow-up. I hope you don't mind me making a PR for this: https://github.com/flairNLP/flair/pull/1800

**Comment by maziyarpanahi** [comment]
Will be fixed in the next release, thanks @alanakbik for merging the PR.
