### ISSUE TITLE
Multiple word single entity for NER usecases

### ISSUE THREAD

**Issue by zaowad** [flairNLP/flair#1783]
I am preparing my data to feed in the columncorpus module just like CoLL2003 NER dataset. But I don't want to put entity on each and every word. Sometime I want an entity  to span multiple words. How do I do that? A little urgent.

**Comment by alanakbik** [comment]
You can use BIO encoding, like in the example [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-your-own-sequence-labeling-dataset).
