### ISSUE TITLE
MultiTagger for Multiple Sequence Tagging Models

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1791]
With the upcoming biomedical Flair release ("hunflair") comes a new object called `MultiTagger` with which multiple different `SequenceTagger` can be chained. 

This tasks monitors the optimization of this model, namely: 
- If two models use the same static embedding, only one of them should be kept in memory
- If two models use the same static embedding, only one of them should be applied during prediction

The idea is to enable us to load several models at once, like this: 

```python
# load tagger for POS, chunking, NER and frame detection
tagger = MultiTagger.load(['pos', 'upos', 'chunk', 'ner', 'frame'])

# example sentence
sentence = Sentence("George Washington was born in Washington")

# predict
tagger.predict(sentence)
```

**Comment by alanakbik** [comment]
Added in #1790

**Comment by shenron9155** [comment]
I have a custom flair LM model and a few classifiers that use the same LM embdeddings. Is there an equivalent MultiClassifier? So that the embeddings are reused per inference.
