### ISSUE TITLE
Impact of entity length

### ISSUE THREAD

**Issue by ivankrstev7** [flairNLP/flair#1795]
Hello!
I am having a NER task with 13 entities, the training is going pretty well with reaching f1-score of about 0.65 in the 15-th epoch, but then it just converges to that amount and i noticed that most of the entities have a great score, but my "EVENT" entity, which happens to be longer than the others is doing terrible! So, my questions are:
1) Could the number of words in the entity affect the model?
2) Would increasing the loss_weight for that entity be a good idea?

**Comment by alanakbik** [comment]
Hello @ivankrstev7 that's hard to answer without seeing the data, but it could be that the EVENT type is less regular than something like PER so it is more difficult to recognize for the model. If the entity is longer, then it probably also is more difficult to recognize. 

You could try setting the loss_weights. I don't have much experience with this, but I'd be interested to hear if this helps.
