### ISSUE TITLE
What does label_subtopic mean and how is it used by CSVClassificationCorpus?

### ISSUE THREAD

**Issue by samru-rai** [flairNLP/flair#1798]
The example code in [Tutorial 6: Loading Training Data](https://github.com/flairNLP/flair/blob/03bf48b31994991de8be7a94a509f10c138bedc5/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset ) shows the following code.
```
# column format indicating which columns hold the text and label(s)
column_name_map = {4: "text", 1: "label_topic", 2: "label_subtopic"}

# load corpus containing training, test and dev data and if CSV has a header, you can skip it
corpus: Corpus = CSVClassificationCorpus(data_folder,
                                         column_name_map,
                                         skip_header=True,
                                         delimiter='\t',    # tab-separated files
```
My question is, what is label_subtopic and how is it used in the context of CSVClassificationCorpus ?

**Comment by alanakbik** [comment]
Hello @samru-rai this example is if you have more than one label for a data point. Then you can define multipe label columns and all labels in these columns will get added.
