### ISSUE TITLE
Location of downloaded models and embeddings

### ISSUE THREAD

**Issue by codechannel** [flairNLP/flair#1799]
How to locate the path of the downloaded models/embeddings?

While running the following code for the first time, flair downloads the models.
````
from flair.models import SequenceTagger
from flair.embeddings import TransformerDocumentEmbeddings

tagger_ner = SequenceTagger.load('de-ner') # location available
embedding = TransformerDocumentEmbeddings('bert-base-uncased')
````

Am using Ubuntu 18.04. and can locate ner, pos models under ~/.flair/models, but ~/.flair/embeddings/ does not have bert.

**Comment by alanakbik** [comment]
The transformer models are downloaded to a folder that the huggingface library creates. I think that's typically `.cache/torch/transformers`

**Comment by codechannel** [comment]
How can I load the model from a different folder `~/dbert_models/transformers` and using `TransformerDocumentEmbeddings`?

Is there something as follows?
local_path_dbert = ~/dbert_models/transformers/
`dbert_model = TransformerDocumentEmbeddings(local_path_dbert)`

**Comment by albertovilla** [comment]
By the way, I think the location has been changed to `.cache/huggingface/transformers`, the `.cache/torch` folder is empty. There is something a bit annoying, the files in that folder have no meaningful names, for example, one of them is named `1cf090f220f9674b67b3434decfe4d40a6532d7849653eac435ff94d31a4904c.d4d29047141693194a1c377423a9a58b3ffdd39ed177b3a9b2ac9bce9e6638d9.json` so unless you open the file it is impossible to know what's the model behind.
