### ISSUE TITLE
BytePairEmbeddings unable to recognize init parameter during loading of Custom embedding

### ISSUE THREAD

**Issue by Rajesh-Mundotiya** [flairNLP/flair#1812]
I have trained Hindi BPE model using Sentencepiece and word2vec embedding (convert it into Gensim format) as explained in tutorial docs. When I tried to load it into BytePairEmbeddings according to [doc](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/BYTE_PAIR_EMBEDDINGS.md), it shows the errors. The loading script and error is ---

embeddings_word = BytePairEmbeddings(model_file_path='Embedding/BPE/hin.bpe.1000.model', embedding_file_path='Embedding/hin.word2vec.100.gensim')

TypeError: __init__() got an unexpected keyword argument 'model_file_path'

My system configuration is:
OS: Ubuntu
Flair: 0.5.1
Python: 3.7

**Comment by alanakbik** [comment]
I believe this features is only active in the master branch, i.e. not if you install through pip. We will release 0.6 shortly, where it will be included. In the meantime, you could try the master branch if that works for you!

**Comment by Rajesh-Mundotiya** [comment]
Thank you so much for quick response.
Could you please share the installation process from master branch.

**Comment by alanakbik** [comment]
```console
pip install --upgrade git+https://github.com/flairNLP/flair.git 
```

**Comment by Rajesh-Mundotiya** [comment]
Thank you once again
