### ISSUE TITLE
Hunflair FSU Corpus update

### ISSUE THREAD

**Issue by khituras** [flairNLP/flair#1816]
@leonweber Great work regarding the BioNLP corpora and models in flair 0.6! I just have one remark. The https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_CORPORA.md references the FSU PrGe Corpus from the CalBc project which was not officially released in that form. There is now an updated publication and resource that exhibits more annotation levels and should be used in the future: http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.564.pdf

Thanks for the great work, I will probably use some of those models in my own!

**Comment by leonweber** [comment]
Thanks for letting us know! We will add the ProGene Corpus and mention in the documentation of FSU PrGe that it was superseded by ProGene.

**Comment by khituras** [comment]
Great, thank you! Perhaps you can even change it in the paper? The old reference was always just a fallback.
