### ISSUE TITLE
HUNFLAIR paper reference is a placeholder

### ISSUE THREAD

**Issue by khituras** [flairNLP/flair#1817]
On the page https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR.md the link to the paper is just a placeholder link at the moment.

**Comment by leonweber** [comment]
Thanks for reporting this! We will update the links as soon as our arXiv submission is published, which should be in the next couple of days.

**Comment by khituras** [comment]
I see. Looking forward to it, this will be an interesting read!
