### ISSUE TITLE
Sharing Flair models

### ISSUE THREAD

**Issue by khituras** [flairNLP/flair#1818]
Already some time ago I trained LMs and Gene/Protein recognition models (described in the second half of http://www.lrec-conf.org/proceedings/lrec2020/pdf/2020.lrec-1.564.pdf) and even published them on Zenodo (https://zenodo.org/record/3698568).
I always meant to feed them back to Flair directly and apologise for not already having done so.
Would the Flair team be interested to integrate those resources? What would you need from to do it?

**Comment by alanakbik** [comment]
Hello @khituras this is great, we'd very much appreciate a contribution! 

If you host the model yourself, you can integrate with a PR like [this one](https://github.com/flairNLP/flair/pull/1687/files). Essentially, you add a line to the `fetch_model` method of the `SequenceTagger` that points to the URL where the model is located: https://github.com/flairNLP/flair/blob/1a12954860cddf6f9f8f8a25e71e9b2d56b4f05e/flair/models/sequence_tagger_model.py#L970

Alternatively, we can also host the model for you. In this case, we'll put the model on our server and do the PR ourselves. Let me know which option you prefer!

**Comment by khituras** [comment]
Hi @alanakbik  - I'm afraid I don't have some good place to host the models permanently. So it would be helpful if you could do it. How can I best give them to you? There would be a forward LM and a backward LM. With regards to final gene/protein tagging models, there are actually 10 models trained on different splits of the same data. Since we also used fasttext embeddings, each model has a size of 15G. How should we deal with this? Select one model? Upload them all and add the individual evaluation results for each?

**Comment by alanakbik** [comment]
Hi @khituras sorry for the late reply! At 15 GB the models are a bit too large to be shipped with Flair - from our servers it would take too long to download this much data. We had a similar problem with our original Hunflair models, but then retrained with smaller word embeddings to keep them at around 1 GB. Would re-training be an option for you? We've included the smaller embeddings in Flair.

Alternatively, we could just put in a link in the documentation to your work to point out that these models exist and that they can be obtained by contacting you?

**Comment by julien-c** [comment]
Hi @khituras, chiming in before this is too stale, to say that as your model is a `SequenceTagger`, from `v0.7` of Flair you can host your model on the huggingface.co model hub (upload it using git and git-lfs) and thanks to @stefan-it load it inside Flair with `tagger = SequenceTagger.load("username/model_id")`

Flair models currently on huggingface.co: https://huggingface.co/models?filter=flair

code (hopefully self-documented 😁) inside Flair that loads models from hf.co: https://github.com/flairNLP/flair/blob/930385787b75ec1a5320243655e92b1c95a20d53/flair/models/sequence_tagger_model.py#L1107-L1123

**Comment by julien-c** [comment]
There's no size cap (storage is cheap these days) and we host multiple models in the [11+ B params range](https://huggingface.co/models?search=t5-11b) 😱, including some from @Rostlab for protein modeling: https://huggingface.co/Rostlab/prot_t5_xl_bfd

The only caveat is that for files larger than 5GB you need to use a custom LFS transfer agent that's currently bundled in `transformers` (it will be spun off to its own package in the future), via `transformers-cli lfs-enable-largefiles ` (see rudimentary doc [here](https://github.com/huggingface/transformers/blob/ec07da65e25562040581febaf9b400a462962961/src/transformers/commands/lfs.py#L40-L55))

**Comment by alanakbik** [comment]
Hi @khituras yes we are working together so that Flair models will be distributed through the HF model hub! There's a larger PR coming and some testing still required, by with Flair 0.8 everything should be working. Then, you can share models simply by uploading to HF model hub! 

You could even test now as @julien-c mentioned, since we snuck in preliminary integration for sequence labeling models to Flair 0.7. If you're interested in beta-testing this, let us know ;) Otherwise by 0.8 everything should be stable.
