### ISSUE TITLE
Ner output 

### ISSUE THREAD

**Issue by Kivin1** [flairNLP/flair#1820]
Hi,

I am following the guideline using ner tag, the code as below:
sentence = Sentence('George Washington went to Washington .')
tagger.predict(sentence)
sentence.to_dict(tag_type='ner')

The output format i would like to have is as bwlow, cuz i need the confidence value.
{'text': 'George Washington went to Washington .',
    'entities': [
        {'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'type': 'PER', 'confidence': 0.999},
        {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'type': 'LOC', 'confidence': 0.998}
    ]}

However, what i get now is:
{'text': 'George Washington went to Washington .', 'labels': [], 'entities': [{'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'labels': [PER (0.9968)]}, {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'labels': [LOC (0.9994)]}]}

Is there any problem for my code and i remember earlier i use the same code, it was able to give the correct output.

**Comment by codechannel** [comment]
````
sentence = Sentence('George Washington went to Washington .')
tagger_ner.predict(sentence)

for span in sentence.get_spans():
    entities = span.to_dict()
    print(entities)
    for labl in entities['labels']:
        print(labl.to_dict())
````
you can then change the 'key' from 'value' to 'type'
