### ISSUE TITLE
Universal dependency training corpus

### ISSUE THREAD

**Issue by tonytan48** [flairNLP/flair#1826]
Hi,
Thank you for your great work on such easy-to-use tool.
I was just refering to the trained POS tagger and I noticed that the UPOS tag type model was trained on ontonotes. I downloaded the model and used the model. It seems that it is trained on Ontonotes 4.0.

But as far as I know, Ontonotes 4.0 only follows the penn treebank tagging scheme. May I know how does flair obtain its pos tag training corpus?

'upos' | Part-of-Speech Tagging (universal) | Ontonotes | 98.6 (Accuracy)
-- | -- | -- | --

**Comment by alanakbik** [comment]
Hello @tonytan48 I think I mapped the POS tags to UPOS tags using simple mapping tables (NN -> NOUN etc.). Not 100% sure though since this was a long while back.

**Comment by tonytan48** [comment]
> Hello @tonytan48 I think I mapped the POS tags to UPOS tags using simple mapping tables (NN -> NOUN etc.). Not 100% sure though since this was a long while back.

Hi, Thank you for the prompt reply. I think I have found the table provided for mapping the penntreebank tags to UD tags. I am trying to reproduce the experiment of UPOS training. As ontonotes actually exceeds the original 664K english UD treebank. By any chance you have the original training corpus for the mapped ontonotes 4.0 corpus or the conversion script? If so could you help to send me?  I will provide you the LDC liscence etc. Sincerely thanks for your help.

**Comment by tonytan48** [comment]
@alanakbik Hello, I looked some of the statistics with the tagset conversion table in UD website:https://universaldependencies.org/tagset-conversion/en-penn-uposf.html. I found that directly converting ontonotes' penn treebank tags may cause some problems: there are some rare keys that are diffrent in the conversion table: Penn Treebanks  'ADD' 'NFP' and 'XX' are not covered in the table. 'XX' can be treated as 'X' for UD. Whereas 'NFP' corresponds to multiple possible values for UD tagset keys and 'ADD' is not mentioned in the UD tagset. Maybe during the conversion, these rare keys shall be paid more attention to.

**Comment by tonytan48** [comment]
@alanakbik A direct lookup may not suffice. I tried to convert using the lookup table by UD website, the AUX UD tag is missing as it maps to multiple Penn POS tags. Hence context aware conversion is required. I suppose you used the converter provided by Stanford CoreNLP?https://github.com/stanfordnlp/CoreNLP/blob/master/data/edu/stanford/nlp/upos/ENUniversalPOS.tsurgeon.


Anyway I am a PhD student and I am curious on the differences and implications of these two tag scheme,.

**Comment by alanakbik** [comment]
Interesting, thanks for the link! I have to dig up my old code (if I can find it :D) - if is it doing simple lookup I may need to re-do the conversion.

**Comment by tonytan48** [comment]
@alanakbik thank you for the prompt reply
