### ISSUE TITLE
Error when loading trained model

### ISSUE THREAD

**Issue by lucaventurini** [flairNLP/flair#1827]
When I load a model trained (on a different machine) with TransformerDocumentEmbeddings, the script fails with the following error:

`Not found: "/root/.cache/torch/transformers/0c370616ddfc06067c0634160f749c2cf9d8da2c50e03a2617ce5841c8df3b1d.309f0c29486cffc28e1e40a2ab0ac8f500c203fe080b95f820aa9cb58e5b84ed": No such file or directory Error #2 `

Apparently, it's looking for some file in cache from transformers, even if I expected the model to contain everything needed for the prediction.

The workaround is to call again, before the loading,
`_ = TransformerDocumentEmbeddings('xlm-roberta-base')`
but you need to know which pre-trained model was used in the training, in this case 'xlm-roberta-base'.

**Comment by alanakbik** [comment]
I think the problem is that it serializes a path specific to the machine it was trained on. I am seeing a similar error. What transformers version are you running? I think it might work with the current transformers.

**Comment by alanakbik** [comment]
Correction: I think the error persists even with the most current version.
