### ISSUE TITLE
CUDA out of memory error when very long word is passed to NER model.

### ISSUE THREAD

**Issue by ugurcanozalp** [flairNLP/flair#1829]
Hello. I have a string consisting of just one repeated character 'a' (300.000 times). The problem is that when I try to find NER in this string model just hangs and never finishes the process. 

**Describe the bug**
Hello. I have a string consisting of just one repeated character 'a' (300.000 times). The problem is that when I try to find NER in this string ner model (en-ner-conll03-v0.4) stucks and throws cuda out of memory error after a long time. When I debugged the code, I realized that this model uses LanguageModel module (in flair/models/language_model) and divides sentences into chunks to get smaller sentences (in get_representation method of LanguageModel class, defaults to 512 chars). However, it seems that this is not able to resolve memory problem.

**To Reproduce**
```
from flair.tokenization import SegtokSentenceSplitter
from flair.models import SequenceTagger
file = 'aas.txt' # A file containing character a 300k times
with open(file,'r') as f:
    text = f.read()

tagger = SequenceTagger.load('ner')
splitter = SegtokSentenceSplitter()
textobjs = splitter.split(text)
tagger.predict(textobjs)
```

RuntimeError: CUDA out of memory. Tried to allocate 2.29 GiB (GPU 0; 5.93 GiB total capacity; 2.56 GiB already allocated; 2.07 GiB free; 2.78 GiB reserved in total by PyTorch)

**Expected behavior**
I expect to get conventional result, finished process with no entities found.

**Environment (please complete the following information):**
 - OS [Ubuntu 18.04]:
 - Version [flair-0.6]:

**Comment by debjyoti003** [comment]
I am also facing the same issue. Is there any update on this?
