### ISSUE TITLE
Training on my own corpus

### ISSUE THREAD

**Issue by dabasmoti** [flairNLP/flair#1835]
Hi,
I want to train "flair embeddings" on my own data for document embeddings.
I have ~2M of long document.
I find for info about how shoukd i organize the data for traing but i didnt find an answer.
Should i append all the document's text to 1 file(or split it for reasonible number depend on hardware).?
Should i need to append each document and add the "SEP" sign?
Thanka

**Comment by alanakbik** [comment]
Yes you should put your data in a few training splits as indicated [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md). We normally organize our corpus into 20 or 100 training splits, each containing lots of documents/sentences. and each with about 50 MB size. 

We normally just use the default separator (newline), but you can use a custom separator to delimit document boundaries in our text file. In this case you need to add the `document_delimiter` field when you train on this data: 

```python
language_model = LanguageModel(
    dictionary,
    is_forward_lm=True,
    [..]
    document_delimiter="[SEP]"
)
```

**Comment by dabasmoti** [comment]
Thanks
