### ISSUE TITLE
How to use OneHotEmbeddings during prediction

### ISSUE THREAD

**Issue by RatulGhosh** [flairNLP/flair#1844]
Hi,

I'm training a NER on a custom dataset. The data are coming from documents, so along with the token, I'm also using additional features like the x and y coordinates. The data is in the following format:
`text x_coordinate y_coordinate tag`
I am using OneHotEmbeddings similar to the one mentioned above by @djstrong 

During prediction how should I pass those additional features? Any help would be appreciated.

_Originally posted by @RatulGhosh in https://github.com/flairNLP/flair/issues/1542#issuecomment-685455972_

**Comment by VigneshBaskar** [comment]
Hi @RatulGhosh! Did you find a solution?

**Comment by RatulGhosh** [comment]
@VigneshBaskar not yet!

**Comment by alanakbik** [comment]
You would need to make sure that the words in the sentences you predict on are also annotated with these features. So you would need to call the [add_tag()](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_1_BASICS.md#adding-labels-to-tokens) function of each word to set the coordinates. Then it should work automatically.
