### ISSUE TITLE
Strange observation for Sentiment Analysis

### ISSUE THREAD

**Issue by happypanda5** [flairNLP/flair#1846]
**Describe the bug**
I have a strange observation for Sentiment Analysis task. I gave it text which include both positive & negative polarity sentences but the score is overwhelmingly positive.

**To Reproduce**
import flair
flair_sentiment = flair.models.TextClassifier.load('en-sentiment')
sentence = "I am very happy. I am also very sad"
s = flair.data.Sentence(sentence)
flair_sentiment.predict(s)
sentiment = s.labels
print( sentiment )

_output is:_ 
_[POSITIVE (0.996)]_

**Expected behavior**
Given that the text contains "very happy" and "very sad", I expect the score/confidence of sentiment to be much lower (maybe around 0.5)

**Environment (please complete the following information):**
Google colab

**Comment by alanakbik** [comment]
It could be that the model never sees such examples in the training data - this is often the problem with constructed examples. If you sentence-split the data, does the model work?

**Comment by happypanda5** [comment]
makes sense
