### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by Tauseef87** [flairNLP/flair#1856]
Hi,
Getting error while loading ner for tagger = SequenceTagger.load('ner')
ValueError: I/O operation on closed file

**Comment by alanakbik** [comment]
Maybe the model wasn't fully downloaded or otherwise corrupted during download. You could try deleting the downloaded file (`~/.flair/models/en-ner-conll03-v0.4.pt`) and running the code again.
