### ISSUE TITLE
Are we able to define new path for pre-trained transformer when loading trained TextClassifier in a different environment?

### ISSUE THREAD

**Issue by raytxz** [flairNLP/flair#1859]
Hi,

After training a TextClassifier using pre-trained transformer from huggingface, I wanted to deploy it in another environment. However, I ran into issues in the new environment when I tried to load the saved model from earlier training. It was complaining about the pre-trained transformer was not found at the path in my training environment.

A work around would be to copy the pre-trained transformer into the deployment environment at the same path as the training environment. But this is not ideal. Is there a way for me to define a new path for the pre-trained transformer during the loading of the trained model?

**Comment by alanakbik** [comment]
Hi @raytxz which transformer model are you using? Could you paste the error message?

**Comment by raytxz** [comment]
Hi @alanakbik I am using bert-base-cased.

Below is the error message.
OSError: Can't load '/path/to/folder/bert-base-cased'. Make sure that: - '/path/to/folder/bert-base-cased' is a correct model identifier listed on 'https://huggingface.co/models' - or '/path/to/folder/bert-base-cased' is the correct path to a directory containing a 'config.json' file.

**Comment by raytxz** [comment]
This seems to be the same issues as #1747 . The workaround suggested by @CourtVision works for me too. 

This was what I did:
`
from flair.data import Sentence
from flair.embeddings import TransformerDocumentEmbeddings
from flair.models import TextClassifier
import torch

# Load the trained model and save it in a different way
classifier = TextClassifier.load('<path to trained model>/best-model.pt')
data_folder = 'data'
corpus: Corpus = ClassificationCorpus(data_folder,test_file='test.txt',dev_file='dev.txt',train_file='train.txt')
label_dict = corpus.make_label_dictionary()
torch.save({
    "state_dict":classifier.state_dict(),
    "label_dict":label_dict
},"<path to save new model>/modified-model.pt")

# Loading the modified model
document_embeddings = TransformerDocumentEmbeddings('<path to pretrained transformer>/bert-base-cased', fine_tune=True)
model_dict = torch.load('<path to save new model>/modified-model.pt')
classifier = TextClassifier(document_embeddings,label_dictionary=model_dict['label_dict'])
classifier.load_state_dict(model_dict['state_dict'])
classifier.eval()

# Predict with the modified model
text = 'Text to predict on.'
sentence = Sentence(text)
classifier.predict(sentence)
`
I think when we deploy models, it is common to be in a different environment from the training environment. Might be good to have a feature in the future to allow for defining a different location for the transformer when loading back a trained model.

**Comment by alanakbik** [comment]
Thanks for the details @raytxz! We recently pushed a change to master that should deal with the problems of serializing the tokenizer (that was affecting for instance the xlm-roberta models in the linked issues), but it looks like this is a different issue. Also, we found a weird issue that is specific to models trained with torch 1.5.1 and transformers 3.1, but otherwise with the fix training and loading models on different machines seemed to work. 

To help us reproduce this error could you: 
- share a minimal script to train the model
- let me know which torch / transformers versions you use on each machine? 

Thanks a lot!
