### ISSUE TITLE
Handle data with zero-width characters

### ISSUE THREAD

**Issue by lvaleriu** [flairNLP/flair#1860]
Can you please explain why in the Sentence `add_token` method you ignore tokens that have zero-width characters?

I've override this method in a CustomSentence implementation and allowed for such tokens ('\n', '\n\n', etc, etc.) but when training I get the following error (already mentioned in some issues): 

`shape '[x, y, z]' is invalid for input of size w.`

I'd like to train a sequence tagger (NER) on an aligned text where the alignement has importance for the NER.

How could I do that? Is there a way to replace them by special characters?

**Comment by alanakbik** [comment]
Hi @lvaleriu did you find an answer to your question?

**Comment by lvaleriu** [comment]
Hi @alanakbik. Yes, I've implemented a custom Spacy based Tokenizer, a custom Sentence and a custom TransformerWordEmbeddings.

And this gives better results on aligned texts as I've hoped.
