### ISSUE TITLE
Best Configuration for training Penn Treebank POS tags with Ontonotes Corpus

### ISSUE THREAD

**Issue by tonytan48** [flairNLP/flair#1867]
Hi, 
Thank you for your great work on flair embeddings. May I know if  there is a best known configuration for training the penn treebank tagset using all ontonotes corpus? I have them in CoNLL2012 NER format.  It seems there is only one best known configuration for POS tagging in Experiments doc.

**Comment by alanakbik** [comment]
Hello @tonytan48 the combination of Flair embeddings and extvec embeddings is the best known for POS tagging and should work well for ontonotes as well. In many cases, we just use the Flair embeddings alone, for instance if you check the embeddings of the POS model we ship with this code:

```python
# load POS model trained over ontonotes
tagger = SequenceTagger.load('pos')

# print embeddings we used
print(tagger.embeddings)
```

you see that we only used Flair embeddings and no word embeddings. This model gets an accuracy of 98.19. I am not sure if adding word embeddings further increases this.
