### ISSUE TITLE
Macro/Micro F scores in the Sequence tagger model

### ISSUE THREAD

**Issue by yusiZou** [flairNLP/flair#1868]
Hello,

In the Sequence tagger model,  (./flair/models/sequence_tagger_model.py), when the `evaluate` function computes the scores, it does the following:

line 576: `macro_f_score = round(metrics.fbeta_score(y_true, y_pred, beta=self.beta, average='micro'), 4)`
line 577: `micro_f_score = round(metrics.fbeta_score(y_true, y_pred, beta=self.beta, average='macro'), 4)`

Why is macro f score taking parameter `average=micro` and vice-versa?

Thank you in advance for your answer!

**Comment by alanakbik** [comment]
@yusiZou thanks for spotting this! The variable names are flipped, but the printout is also flipped: 

```python
        detailed_result = (
                "\nResults:"
                f"\n- F-score (micro) {macro_f_score}"
                f"\n- F-score (macro) {micro_f_score}"
                f"\n- Accuracy {accuracy_score}"
                '\n\nBy class:\n' + classification_report
        )
```

So the two errors cancel each other out and the final printout is correct, but we will correct the variable names!
