### ISSUE TITLE
Any option to reduce Flair module size?

### ISSUE THREAD

**Issue by code-crusher** [flairNLP/flair#1869]
**Description:**
1. Installing Flair in the docker image is taking up too much space, below is my Docker layer for Flair:
<img width="537" alt="Screenshot 2020-09-17 at 03 05 02" src="https://user-images.githubusercontent.com/6625740/93395047-d7f08800-f892-11ea-97f6-7812ca4e0427.png">

Is there an option to reduce the included modules or have a light version where we are only using specific modules? 

2. Minor, but post image builds, running the first time also downloads assets, is there a better to pre-load assets being by flair in the image? For eg: `https://nlp.informatik.hu-berlin.de/resources/models/sentiment-curated-fasttext-rnn/sentiment-en-mix-ft-rnn.pt`. This just increases the deployment times. 

Thanks a ton!

- Vatsal

**Comment by alanakbik** [comment]
Hello @code-crusher the biggest dependency by far is the torch package at some 1.4 GB. I am not sure if there is any way to get around it, unless you are inferencing on CPU only. In this case you could install a torch version without the GPU stuff, which is much smaller. See here: https://discuss.pytorch.org/t/reducing-docker-size-with-pytorch-model/78991

**Comment by code-crusher** [comment]
@alanakbik thank you! That does make sense. Currently, I'm using a base image with everything Flair prebuilt, which is working fine. 

I would still prefer to use only CPU version only. Is there any python way to bypass flair's Pytorch installation and use mine? I can only see `install flair -> uninstall pytorch -> install my version`.

**Comment by code-crusher** [comment]
Oh nvm, doing 
```
RUN pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

# flair installation
RUN pip install flair==0.6
```

worked like a charm.
