### ISSUE TITLE
Polish language support

### ISSUE THREAD

**Issue by dkajtoch** [flairNLP/flair#187]
Hi,
Thanks for a great package! I ma not sure if the current version has support for Polish language. I can see word embedding, but 'ner' tagger is unavailable. Are you planning to develop methods for Polish?

**Comment by alanakbik** [comment]
Hi @dkajtoch, yes Polish is one of the main languages we are currently looking at and want to add to the project very soon. We've already added the character LM embeddings that [(Borchmann et. al, 2018)](https://github.com/applicaai/poleval-2018) computed to the project, and in a recent branch also FastText embeddings for Polish. 

I am hoping that very soon we can also add pre-trained models for Polish NER and PoS tagging, but of course any help is appreciated :)

**Comment by dkajtoch** [comment]
Thanks @alanakbik! It would be great to collect all the pieces in one place. They are now scattered around the web http://clip.ipipan.waw.pl/LRT

**Comment by dkajtoch** [comment]
One more thing @alanakbik. Are you going to use supervised learning approach to POS tagging and NER? If so, how do you get high quality learning material?

**Comment by dkajtoch** [comment]
Great news @alanakbik! Sorry, but I do not have much experience with polish datasets either. Maybe, the resources you provided are good starting point.

**Comment by maciej-zalewski** [comment]
Hi @alanakbik, firstly - great work! Flair is an amazing tool. However I have a problem with Polish language and I hope that maybe you could give me some advice. 

In Readme.md you claim that NER in Polish is supported and you achive very good results:
![polish_lang_flair](https://user-images.githubusercontent.com/43313417/54342527-faba3480-463c-11e9-9038-e2a2b0dcc3da.jpg)

but you do not provide an explanation in "Best Configurations per Dataset" page and in the "Tutorial 2: Tagging your Text" page you say that "The NER models are trained over 4 languages (English, German, Dutch and Spanish) and the PoS models over 12 languages (English, German, French, Italian, Dutch, Polish, Spanish, Swedish, Danish, Norwegian, Finnish and Czech)."

afaic this should mean that Polish is supported only for PoS and I should not seek a great succes with it with NER; how is this high score (86.6) achived then? Please bear with me here, as I am a beginner in NLP. I would be grateful if you could help me here :)

**Comment by maciej-zalewski** [comment]
@alanakbik Sorry to bother you again, but I've just realised, that the answer was in front of me all the time; https://github.com/applicaai/poleval-2018 provides an explanation :)

**Comment by alanakbik** [comment]
Hi @maciej-zalewski great, the authors put a lot of details into their repo and paper, and will probably be happy to provide all other details you need!
