### ISSUE TITLE
Why my NER model refuse to continue the training when I load from the check point

### ISSUE THREAD

**Issue by TTThanos** [flairNLP/flair#1873]
![image](https://user-images.githubusercontent.com/63569348/93777021-d0e0c580-fc56-11ea-9c64-96e798acc12d.png)
![image](https://user-images.githubusercontent.com/63569348/93777056-db9b5a80-fc56-11ea-8bc2-5ba162c1091a.png)

**Comment by TTThanos** [comment]
Rather than continue to train another 30 epochs, it just outputs the result.....

**Comment by alanakbik** [comment]
Can you try setting `max_epochs` to 60? Maybe it remembered the epoch number from the first training run.
