### ISSUE TITLE
[Feature / Request] Pytorch XLA / TPU support

### ISSUE THREAD

**Issue by robinvanschaik** [flairNLP/flair#1892]
As of today [PyTorch / XLA is now generally available on Google Cloud TPUs](https://medium.com/pytorch/pytorch-xla-is-now-generally-available-on-google-cloud-tpus-f9267f437832). 

**What does this mean?**
It means that you can use [Pytorch XLA](https://pytorch.org/xla/release/1.6/index.html) to accelerate training jobs with [Google Cloud TPUs](https://cloud.google.com/tpu) on Google Cloud Platform (paid) but also on [Colab](https://colab.research.google.com/) (free), and [Kaggle](https://www.kaggle.com/docs/tpu)(free). 

The fact that this hardware is available on Colab and Kaggle means that these hardware gains are also accessible to those outside of the walled garden of Google Cloud Platform.

**Describe the solution you'd like**
Given that Flair runs on Pytorch, it means that that training jobs could be further accelerated by making use of this hardware; similar to how CUDA support is currently handled in Flair. 
Furthermore, the documentation [shows](https://pytorch.org/xla/release/1.6/index.html#running-models-on-xla-devices) how existing code can be adapted.

**Additional context**
[Here](https://github.com/pytorch/xla) is the XLA repo. 
[Here](https://pytorch.org/xla/release/1.6/index.html) is documentation that explains enabling Pytorch XLA.
[Here](https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/getting-started.ipynb#scrollTo=Iz6Y5t-cC5Cm) is a Google Colab that explains the Pytorch XLA framework. 
Google [claims](https://cloud.google.com/tpu) that ResNet-50 trains 27 times faster and 38% cheaper than running the same training job on 8 V100 GPUs.  

**Additional remarks**
I would love to work on this, but I fully recognise that I am not yet skilled enough to tackle such an extensive topic alone.

**Comment by aditya-malte** [comment]
This is an important feature really
