### ISSUE TITLE
size of crawl vocabulary 

### ISSUE THREAD

**Issue by Hsaeno** [flairNLP/flair#1900]
Hello，I want to know something about the size of crawl vocabulary.
I notice that the vocabulary size of crawl provided by Flair  is 1M, but the [https://fasttext.cc/docs/en/english-vectors.html](url) and 
[https://fasttext.cc/docs/en/crawl-vectors.html](url)  provides  2M.
I wonder whether flair has changed or used an old version for crawl embedding. Is it convenient to provide details? 
Thank you for your answer!

**Comment by alanakbik** [comment]
Hello @Hsaeno we only use the most common 1 million words of each FastText embedding in the packaged embeddings. We do this to limit the size of the embedding files which can be very big.

**Comment by Hsaeno** [comment]
@alanakbik OK, I get it ! Thank you very much :)
