### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch>=1.1.0 

### ISSUE THREAD

**Issue by Shashwat1001** [flairNLP/flair#1904]
Whenever I try to install this flair package I am getting this below error. How can I solve this error?

Error is as follows:-

ERROR: Could not find a version that satisfies the requirement torch>=1.1.0 (from flair==0.6.1) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.1.0 (from flair==0.6.1)

**Comment by kunalkharsadia** [comment]
anything on this. I am also facing the same issue.

**Comment by Shashwat1001** [comment]
No buddy. I didn't find a solution. If you find something do let me know.

**Comment by kunalkharsadia** [comment]
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe


downloaded and installed vc_redist.x64.exe, restarted system. upgraded tensorflow and all set. try it on yourself to see if this works for you.

**Comment by rjogallagher17** [comment]
What version of python are you guys using for this? I am getting this error on 3.8.6. I tried to follow @kunalkharsadia suggestion but after installing the C++ redistributable, restarting, and upgrading tensorflow, I still get the same error as described in the issue title.

**Comment by rjogallagher17** [comment]
Turns out I had to make sure I updated pytorch as well and this allowed the installation to go through. I would suggest checking your version of pytorch and seeing if you can upgrade it prior to installing flair for the environment you're working in.
