### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by abhipn** [flairNLP/flair#1905]
I have trained a model on another machine but when I try to load the trained model onto google colab I am getting, 

It took almost 24 hours to train the model, is there any way I can fix this issue? I'm sure it is related to some dependency version mismatch but I just can't figure out which one?

Here's my training  code,
```
embedding_types = [
    TransformerWordEmbeddings('distilbert-base-cased', allow_long_sentences=True, fine_tune=True, batch_size=8),
    FlairEmbeddings('news-forward-fast', fine_tune=True)
]

embeddings : StackedEmbeddings = StackedEmbeddings(
                             embeddings=embedding_types)

trainer : ModelTrainer = ModelTrainer(tagger, corpus, torch.optim.Adam)
trainer.train('/taggers/flair-ner',
              learning_rate=0.0001,
              mini_batch_size=8,
              max_epochs=100,
              num_workers=4,
              min_learning_rate=0.00001) 
```

Here's the error,

`
tagger = SequenceTagger.load('models/flair/best-model.pt')`
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-0fa565b989ff> in <module>
----> 1 tagger.predict(Sentence(content))

~/env/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py in predict(self, sentences, mini_batch_size, all_tag_prob, verbose, label_name, return_loss, embedding_storage_mode)
    367                     continue
    368 
--> 369                 feature = self.forward(batch)
    370 
    371                 if return_loss:

~/env/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py in forward(self, sentences)
    606     def forward(self, sentences: List[Sentence]):
    607 
--> 608         self.embeddings.embed(sentences)
    609 
    610         names = self.embeddings.get_names()

~/env/lib/python3.8/site-packages/flair/embeddings/token.py in embed(self, sentences, static_embeddings)
     69 
     70         for embedding in self.embeddings:
---> 71             embedding.embed(sentences)
     72 
     73     @property

~/env/lib/python3.8/site-packages/flair/embeddings/base.py in embed(self, sentences)
     58 
     59         if not everything_embedded or not self.static_embeddings:
---> 60             self._add_embeddings_internal(sentences)
     61 
     62         return sentences

~/env/lib/python3.8/site-packages/flair/embeddings/token.py in _add_embeddings_internal(self, sentences)
    857         # embed each micro-batch
    858         for batch in sentence_batches:
--> 859             self._add_embeddings_to_sentences(batch)
    860 
    861         return sentences

~/env/lib/python3.8/site-packages/flair/embeddings/token.py in _add_embeddings_to_sentences(self, sentences)
    906             # method 2:
    907             # transformer specific tokenization
--> 908             subtokenized_sentence = self.tokenizer.tokenize(tokenized_string)
    909             if len(subtokenized_sentence) == 0:
    910                 empty_sentences.append(sentence)

AttributeError: 'NoneType' object has no attribute 'tokenize'
```

**Comment by aneuraz** [comment]
Hi @abhipn, I have the exact same error. 
Have you solved this ? 
thanks

**Comment by abhipn** [comment]
> Hi @abhipn, I have the exact same error.
> Have you solved this ?
> thanks

If I remember correctly, using `torch 1.5.1` solved the issue for me.

**Comment by Rasmitha23** [comment]
Hi @abhipn,

I am getting this error and I have torch version 1.6.0. Should I change torch version to 1.5.1?

Hi @aneuraz ,

How did you solve this issue?

**Comment by abhipn** [comment]
@Rasmitha23 I think after changing the torch version, it worked. Do try it out.

**Comment by aneuraz** [comment]
@Rasmitha23 During the training of the model, I would define the path to the langage model using an absolute path. Then, when I tried to use the model on another machine, the language model could not be found anymore. To solve it, I used relative path when defining the model and then put the language model in the exact same relative path on the inference machine. Not a completely satisfying solution but it does the trick

**Comment by Rasmitha23** [comment]
@abhipn thanks for replying, I tried that but still getting the same error
@aneuraz thanks for replying.

**Comment by abhipn** [comment]
@abhipn oh, I really cant recall how I fixed it, I am pretty sure its a dependency issue. One thing you could try would be to use conda to install flair and its dependencies (or) create a seperate venv and install flair and try it out.

**Comment by schelv** [comment]
@Rasmitha23 
For me this issue was caused by the transformers library (silently) not being able to download some files (a config.json and a vocab.txt) to a .cache directory. This was because it did not have write permission there.
Setting the `PYTORCH_TRANSFORMERS_CACHE` env variable to a directory with enough permissions fixed the issue for me.

Perhaps this is also the cause of https://github.com/flairNLP/flair/issues/2011?
