### ISSUE TITLE
pretrained model with native pytorch support

### ISSUE THREAD

**Issue by dhruvsakalley** [flairNLP/flair#1908]
A clear and concise description of what you want to know.
We are trying to productionize an NER model developed using the embedding layer for flair. How can one get the flair pretrained embedding model converted to a native pytorch implementation? (hopefully without reverse engineering the entire flair abstractions) 
<br>
This is crucial if we were to employ some lean techniques to build say lambda functions from these models.
If you have equivalent tensorflow saved models that would be perfect.
Thanks for the help.
Dhruv

**Comment by dhruvsense** [comment]
This issue is partly addressed by a sagemaker issue: https://github.com/aws/sagemaker-python-sdk/issues/852
