### ISSUE TITLE
ModuleAttributeError: 'TextClassifier' object has no attribute 'embed'

### ISSUE THREAD

**Issue by azizcu** [flairNLP/flair#1910]
new_clf = TextClassifier.load('model/final-model.pt')
sentence = Sentence('all authors contributed to the final manuscript .')
new_clf.embed(sentence)

how can i find embedding feature from object "TextClassifier" ?

actually how can i fine tune BERT,RoBERTa,GPT2 with flair and how can i extract feature?

**Comment by robinvanschaik** [comment]
Hi @azizcu, 

I was also looking into this for something else.

I took a look at (https://github.com/flairNLP/flair/blob/master/flair/models/text_classification_model.py), and the `forward` computes the embeddings, but returns the scores as well. 

As such, you we can basically take the `forward` and take what you need.

```Python
from flair.models import TextClassifier
from flair.data import Sentence
import torch

if torch.cuda.is_available():
    device = torch.device("cuda:0")
else:
    device = torch.device("cpu")


sentences = [Sentence("hello world."), Sentence("all authors contributed to the final manuscript .")]

model_path = "./model/final-model.pt"

classifier = TextClassifier.load(model_path)


def get_embeddings(classifier, sentences):

    sentence_embeddings = classifier.document_embeddings.embed(sentences)

    embedding_names = classifier.document_embeddings.get_names()

    text_embedding_list = [
                sentence.get_embedding(embedding_names).unsqueeze(0) for sentence in sentences
            ]

    text_embedding_tensor = torch.cat(text_embedding_list, 0).to(device)

    return text_embedding_tensor


model_embeddings = get_embeddings(classifier, sentences)
```

returns the following:
```
print(model_embeddings)
tensor([[ 0.0145, -0.5964,  1.9803,  ..., -0.2521, -0.1048,  0.3182],
        [-1.0069,  0.0688,  0.8902,  ..., -0.8872,  0.8790, -0.2874]])
```

However, I am not 100% sure if this is correct, as I may be overlooking something. Still, could be a good start, right?
