### ISSUE TITLE
Sentence object with pre-tokenized text

### ISSUE THREAD

**Issue by KDercksen** [flairNLP/flair#1916]
Dear Flair team,

I was wondering what the best approach is to use Flair with pre-tokenized text. My data is, broadly speaking, already in the form `(["Hi", ",", "how", "are", "you", "Mr.", "President", "?"], ["O", "O", "O", "O", "O", "B-PER", "L-PER", "O"])` for entity tagging. As far as I can see, `Sentence` does not have functionality for this out of the box. Do I just populate the `tokens` list manually starting from an empty sentence, or how should I go about this?

Thanks for your awesome work!

**Comment by KDercksen** [comment]
I think the most elegant way is the following:
```python
text, labels = ["Hi", ...], ["O", ...]

# join tokens with whitespace, then split on whitespace
sentence = Sentence(" ".join(text), use_tokenizer=False)

# add labels
for token, label in zip(sentence, labels):
    token.add_tag("ner", label, confidence=1.0)
```

Assuming there are no whitespace tokens in the original list, this should work fine.

**Comment by AAnirudh07** [comment]
It still works three years later! Thank you

**Comment by helpmefindaname** [comment]
I just want to point out, that the `Sentence` also directly accepts tokens, hence `Sentence(tokens)` should be more elegant than `Sentence(" ".join(tokens), use_tokenizer=False)`
