### ISSUE TITLE
Weird import error

### ISSUE THREAD

**Issue by Avee-81** [flairNLP/flair#1919]
Hello there

I am facing very weird kind of error with the Flair library. I am using Colab and two days back, everything was working fine for me. Suddenly, importing Flair has started giving me some error and as soon as I import flair, the program just stops. I also tried importing flair in the Colab notebook and it shows the same thing. As soon as I import flair, the notebook crashes and I have to start it again.

I am currently using flair 0.6.1. Can somebody tell what is wrong here and why is this happening?

**Comment by helpmefindaname** [comment]
Can you please share the error you were talking about?

does it work when you import torch directly?
does the error still occur when you restart the session?

**Comment by GaurangSharma44** [comment]
> Can you please share the error you were talking about?

For me, while importing flair or SequenceTagger, etc, the code block doesn't finish successfully. It gets stuck here..
![Flair Import Stuck](https://user-images.githubusercontent.com/43086300/97775103-2ebdd280-1b5e-11eb-9050-6265068e56aa.PNG)

**Comment by helpmefindaname** [comment]
The output you're seeing is just a bunch FutureWarnings. Those just mean that the current version of tensorboard won't run with future versions of numpy, however it still runs on the current one so you can ignore it.

What is more important is to check where it get's stuck. You can do a kernel interrupt, so you get the stacktrace which rather leads you to the original problem (it should look similar to the picture below)
![image](https://user-images.githubusercontent.com/26192135/97788237-cef41580-1bb7-11eb-8a6e-f5db9d643a93.png)
