### ISSUE TITLE
Training a custom fast model

### ISSUE THREAD

**Issue by Mohammad-Asad-Ali** [flairNLP/flair#1921]
Hello, 

I was wondering if its possible for us to train a custom model (ZSL classifier) and have a fast version (CPU friendly) of it? If its possible could be please suggest the steps. Thanking you in advance!

**Comment by stefan-it** [comment]
Hi @Mohammad-Asad-Ali ,

these "fast" models normally have a dimension size of 1024 instead of 2048. You can specify it here:

```python
language_model = LanguageModel(dictionary,
                               is_forward_lm,
                               hidden_size=1024,
                               nlayers=1)
```

as `hidden_size` parameter when training new Flair Embeddings from scratch :)
