### ISSUE TITLE
Finetuning transformer models.

### ISSUE THREAD

**Issue by M-I-Dx** [flairNLP/flair#1927]
I am using the RoBERTa transformer model implementation for the task of sentiment analysis. During training I have set `TransformerDocumentEmbeddings` parameters as `fine_tune=True` and `layers="-1"`. I am interested in knowing what happens during the training process. What layers of the model get trained (or finetuned) and what layers do not. Also what does `layers="-1"` stands for?

**Comment by djstrong** [comment]
All layers are trained and output from last layer is taken to form embeddings.
