### ISSUE TITLE
Traininh flair LM causes Error -in sampling distribution for next character a tensor of dimension 0 is produces

### ISSUE THREAD

**Issue by mahdiyeh-xx** [flairNLP/flair#1929]
Hello All,
I am training flair LM on my data. the following error is reported after first epoch:
Traceback (most recent call last):
  File "flair_lm.py", line 35, in <module>
    max_epochs=10)
  File "/home/ubuntu/code/flair-venv/lib/python3.6/site-packages/flair/trainers/language_model_trainer.py", line 451, in train
    log.info(self.model.generate_text())
  File "/home/ubuntu/code/flair-venv/lib/python3.6/site-packages/flair/models/language_model.py", line 349, in generate_text
    prob = decoder_output[word_idx]
IndexError: too many indices for tensor of dimension 0

Actually in sampling phase a tensor with size 0 is produced: 
               # try sampling multinomial distribution for next character
                try:
                    word_idx = torch.multinomial(word_weights, 1)[0]
                except:
                    word_idx = torch.tensor(0)

                print(word_idx)

**Comment by stefan-it** [comment]
Hi @mahdiyeh-xx ,

could you provide a more detailed code snippet and the used Flair and PyTorch version? You should also check, that you're using the right folder structure when training Flair Embeddings:

https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md#preparing-a-text-corpus
