### ISSUE TITLE
Origin of the Japanese embeddings

### ISSUE THREAD

**Issue by nikolito** [flairNLP/flair#1956]
Hello, I have tried Japanese NER with Flair. It works pretty nice.
So, I'd like to know the origin of Japanese Embeddings just for my research.
What sites did Japanese forward and backward embeddings derive from?
And how did they tokenize the crawled data?
According to some threads, [the embeddings](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md) were added by @frtacoa and maybe @minh-agent.

**Comment by alanakbik** [comment]
@nikolito which dataset did you train the NER with?

**Comment by nikolito** [comment]
@alanakbik I use a Japanese dataset in a specific field. (sorry for unclear replay)

**Comment by frtacoa** [comment]
hi @nikolito , we created the embeddings out of of the Japanese Wikipedia dump file from [2018/12/20](https://dumps.wikimedia.org/jawiki/20181220/) (seems not available anymore).
As for the tokenization, we followed the procedure explained [here](https://hironsan.hatenablog.com/entry/japanese-text8-corpus).
Regards!

**Comment by nikolito** [comment]
Hi, @frtacoa, I appreciate your helpful reply!
