### ISSUE TITLE
IMPORTANT: (30.08.2020) We moved our models to a new server. Please update your Flair to the newest version!

### ISSUE THREAD

**Issue by ulf1** [flairNLP/flair#1960]
When calling `tagger = SequenceTagger.load('ner')` I get the follwoing error message

```
OSError: HEAD request failed for url https://nlp.informatik.hu-berlin.de/resources/models/ner/en-ner-conll03-v0.4.pt with status code 503.
```

It's seems to related to the warning

```
IMPORTANT: (30.08.2020) We moved our models to a new server. Please update your Flair to the newest version!
```

My flair version is `flair==0.6.1.post1` what seems to be the latest version on pypi.

How to fix the error mentionend above?

**Comment by alanakbik** [comment]
Hello @ulf1 I just tested and it seems to work? Maybe the server was temporarily offline.

**Comment by ulf1** [comment]
thx it works now.
it seemed to be some sort connection problem as you said.
