### ISSUE TITLE
Regarding the Hunflair Multi Tagger for NER

### ISSUE THREAD

**Issue by tahmedge** [flairNLP/flair#1962]
Hi, I would like to know how the Hunflair Multi Tagger was trained. 

Were the five district models used for the tagging of a sentence when the Multi Tagger was loaded? Or the Multi Tagger is just one single model?

**Comment by mariosaenger** [comment]
Hi @tahmedge !

Indeed, the HunFlair MultiTagger actually consists of five different models, i.e. a distinct NER model for each entity type. So the MultiTagger is merely a wrapper which allows you to conveniently run predictions with these five models using a single method call. For details of the training procedure please refer to our paper:

https://arxiv.org/abs/2008.07347

Don't hestitate to contact us if you have any questions.

Best,
Mario

**Comment by tahmedge** [comment]
Thanks for your reply. I have another query, since the NER tagger is not 100% accurate, how did Hunflair tackle the conflict if the same token/entity is tagged by multiple taggers. Suppose, token T in Sentence S is tagged by both Gene and Disease taggers.

**Comment by mariosaenger** [comment]
You are totally right - such phenomena can occur. We don't provide a fixed strategy to resolve resp. handle such conflicts / ambiguity and the users are able to choose their own approach. The MultiTagger returns all predicted spans of all five models and doesn't check (or remove) overlapping spans. However, overlaps should (hopefully) only occur rarely.

**Comment by tahmedge** [comment]
Thanks a lot for the clarification.
