### ISSUE TITLE
Down loading embeddings returns redirect error for Alan NLP

### ISSUE THREAD

**Issue by LukasDauterman** [flairNLP/flair#1969]
I am trying to load flair embeddings and I keep getting the following error:

`OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/glove.gensim.vectors.npy with status code 301.`

The status code indicates a permanent redirect.

I SSH into the machine that is exhibiting this issue, so there is no network issues that I can think of.

The code that produces this issue for me :
```
embedding_types: List[TokenEmbeddings] = [
    WordEmbeddings('glove'),
    FlairEmbeddings('news-forward-fast'),
    FlairEmbeddings('news-backward-fast')
]
```
![image](https://user-images.githubusercontent.com/3969402/98983559-cb289300-24d5-11eb-8706-27732164b0aa.png)
![image](https://user-images.githubusercontent.com/3969402/98983606-ded3f980-24d5-11eb-9256-830b6583ce59.png)

But this doesn't work and throws the error, and I get similar errors for all the different embeddings.

Environment:
 - OS : linux
 - Python: 3.7
- Flair: 0.4.5 (have to use this version)
- Using visual studio code and remote ssh.

This is running in a VM in Azure resources, but can't give more details than that.

I have tried looking for where I can download the models, but it has a similar issue, shows a redirect error:

![image](https://user-images.githubusercontent.com/3969402/98983742-1478e280-24d6-11eb-8c6b-55694438fdea.png)

**Comment by alanakbik** [comment]
Hello @LukasDauterman the bucket was unfortunately taken offline, which is why you need to use a newer version of Flair where the new bucket is used. 

As a workaround, you could install current Flair in a different virtual environment, execute this code once so that the models are downloaded, then go back to using Flair 0.4.5.

**Comment by alanakbik** [comment]
Alternatively, you could manually download the models from here: https://nlp.informatik.hu-berlin.de/resources/

**Comment by LukasDauterman** [comment]
I ended up updating to the current version and that fixed the issue, but required some code changes.

**Comment by bhardwaj1230** [comment]
Hello,

I am still facing this issue, with flair==0.7

OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt with status code 301.
