### ISSUE TITLE
Why 'TransformerDocumentEmbeddings' fine_tune=True crashes python?

### ISSUE THREAD

**Issue by codechannel** [flairNLP/flair#1972]
I am trying to get document embeddings using distillbert-base-german-cased model with fine_tune=True and only using CPU. 
The code crashes randomly inside the loop. 
It works fine if embeddings of a text are computed individually outside the for loop.

For example, the code will crash at a random idx = 2000 inside the loop, but if embeddings are computed outside using all_text[2000] it works as intended. Any suggestions or ideas on how to deal with it?

Here is the code:
```
from flair.data import Sentence
from flair.embeddings import TransformerDocumentEmbeddings

dbert_model = TransformerDocumentEmbeddings('distilbert-base-german-cased', fine_tune=True, batch_size=1)

all_text = ['some_text_0', 'some_text_1', ..., 'some_text_30000']

for idx, text in enumerate(all_text):
    sentence = Sentence(text)

    dbert_model.embed(sentence)

    all_text_embd[idx] = sentence.get_embedding().detach().numpy()
```

**Comment by stefan-it** [comment]
Hi @codechannel ,

could you try to set  `fine_tune` to `False` -> this should only be necessary/used when you're actually training document embeddings (not for evaluating/predicting) :hugs:

**Comment by codechannel** [comment]
Hi @stefan-it 

The embeddings obtained with `fine_tune=True` achieve much better results as compared to `fine_tune=False`.
Since `fine_tune=True` outside a for-loop, it is unclear to me why would the code crash randomly if embeddings are computed within the loop.

I am guessing that `TransformerDocumentEmbeddings` does not release the memory when it is within the loop. 
Is there a way to find what could be happening? I have tried using signal-alarm and try-except error, but it did not help.

**Comment by codechannel** [comment]
Hi @alanakbik @nreimers 

I saw your comments about `fine_tune` on this issue https://github.com/flairNLP/flair/issues/1769, 
perhaps you may have an idea why `fine_tune=True` crashes the code when used within a for-loop.

**Comment by nreimers** [comment]
@codechannel 
Sounds like that it is an issue with memory, when you run in a loop. I also had sometimes strange pytorch memory exceptions, that pytorch tried to access illegal addresses.

Sadly I don't know how to fix it. Maybe try a different pytorch version and see if it also happens there?

**Comment by codechannel** [comment]
If someone is looking for a solution, the answer is in subprocess.
1. Create subprocess which reads the model and computes embeddings
2. Convert numpy to text and use `print(text_embedding)` to return the embedding
3. Format string back to numpy in the main file

`compute_embedding_subprocess.py`
```
import sys
from flair.data import Sentence
from flair.embeddings import TransformerDocumentEmbeddings

# Use the right model as per requirement
dbert_model = TransformerDocumentEmbeddings('distilbert-base-german-cased', fine_tune=True)

input_text = str(sys.argv[1])
sentence = Sentence(input_text)
dbert_model.embed(sentence)
text_embedding = sentence.get_embedding().cpu().detach().numpy()

# make sure to free memory by setting it to None
dbert_model = None
del dbert_model
del sentence

print(text_embedding)
```

`main.py`
```
import numpy
import subprocess

input_text = "Some piece of text whose embedding needs to be computed. Subprocesses are slow but they are a work around to the memory leak issue. Feel free to comment a better a solution."

cmd = ["python", "compute_embedding_subprocess.py", input_text]

out = subprocess.run(cmd, capture_output=True, text=True)

out_string = out.stdout

out_string = out_string.replace(']', '')
out_string = out_string.replace('[', '')

text_embedding = numpy.fromstring(out_string,
                                      dtype=float,
                                      sep=' ')
```
