### ISSUE TITLE
Fix handling of multi-words in Universal Dependencies corpora

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#1980]
The 2.7 update of universal dependencies changes the markup of some words such as English contractions that are now handled as multi-words (see discussion [here](https://github.com/UniversalDependencies/UD_English-EWT/issues/108)). 

As discovered by @wuqi0704, this causes some errors in Flair, since we currently require the `SpaceAfter=No` marker to set correct whitespaces.

To reproduce: 

```python
# load English UD
corpus = UD_ENGLISH()

# print sentence 41
print(corpus.dev[41].to_plain_string())
```

This prints:
~~~
We 've moved on.
~~~

But it should print:

~~~
We've moved on.
~~~

**Comment by stefan-it** [comment]
Parsing CoNLL-U format could be so easy... I'm not very convinced that this kind of annotation is a good idea...

Maybe we can add a "SpaceAfter=No" in a kind of pre-processing step :thinking:
