### ISSUE TITLE
Tutorial 8 - Optimizers - not working with Flair 0.6.1

### ISSUE THREAD

**Issue by danmaxis** [flairNLP/flair#1982]
**Describe the bug**
I'm trying to run the Optimizer Tutorial (number 8), but in the second training gives me an invalid input size error. 
`job exception: shape '[8, 14, 4096]' is invalid for input of size 794624`

**To Reproduce**
Run the script parts sequentially in the "Selecting Hyper Parameters" section. (I'm using in my jupyter notebook). Very much like described in issue #1340 but in local instance.

**Expected behavior**
I presume it would finish execution without any errors, while generating best model files.

**Screenshots**
It is just like isse #1340 Although it happens in my local instance, 

**Environment (please complete the following information):**
 - OS: Windows 10 19042.630
 - Flair Version : 0.6.1.post1
- cudatoolkit:11.0.221
- pytorch: 1.7.0 - py3.8_cuda110_cudnn8_0
- Python Version: 3.8.5

**Additional context**
It is just like isse #1340 Although it happens in my local instance,

**Comment by alanakbik** [comment]
Hello @danmaxis the hyperparameter selection methods are currently being completely rebuilt. So the current code is no longer maintained and will be replaced with a new version. We will push a beta release of this possibly as early as next week (@whoisjones).

**Comment by danmaxis** [comment]
This is nice to know! Thanks

**Comment by gunturbudi** [comment]
Hello @alanakbik, 
I found the same issue with the hyperparameter optimization. Is there any update on the development?

Thanks!

**Comment by alanakbik** [comment]
Our most recent development here is in the branch GH-2001-Hyper-Opt, see also #2002. If you'd like to try be an early tester, you could check out the branch and run the hyperparameter optimization from there!
