### ISSUE TITLE
Token attribute "idx" not equal to position in sentence.

### ISSUE THREAD

**Issue by daniellobrunello** [flairNLP/flair#1986]
Not sure if this is a bug or in some way a feature for later use of the token indices.
There was something going on with the `__get_item__` method in the Sentence class (see #107).  

Slicing the sentence returns the correct token:
```python
Sentence("He likes apples .")[0] = Token: He
```
Anyway, the `idx` attribute of the token `Token: He` is `1`. 
Taking this index to retrieve the token from the sentence would yield `Token: likes`. 

I would expect the token index to be equal to its position in the sentence (whilst starting to count from 0). 

I'm running `flair 0.6.1.post1`.

_If_ this behavior is not wanted, then probably the issue lies here: 

`Sentence.add_token(.)`:
```python
# set token idx if not set
token.sentence = self
if token.idx is None:
    token.idx = len(self.tokens)
```
should be something like
```python
# set token idx if not set
token.sentence = self
if token.idx is None:
    token.idx = len(self.tokens) - 1
```
Or do this before adding the token to `self.tokens`

**Comment by alanakbik** [comment]
Hello @daniellobrunello this is in fact intended to mirror the way token ids are usually given in linguistic annotation. For instance, the universal depedencies corpora always start counting at 1.

**Comment by daniellobrunello** [comment]
Thank you for the quick response.  
[Universal Dependencies](https://universaldependencies.org/) for interested ones.
