### ISSUE TITLE
model.predict returns error

### ISSUE THREAD

**Issue by igormis** [flairNLP/flair#1990]
**Describe the bug**
I am using trained sequence_tagger_model trained with bert-multilingual embeddings and flair multilingual parameters, where I set fine_tune=True. However sometimes it throws an error:
```
 File "/app/nlu_ml_v2.py", line 97, in tag_span
web_nlu_ml.1.ryu06t0cj1wl@ip-172-31-84-5    |     model.predict(sentence)
web_nlu_ml.1.ryu06t0cj1wl@ip-172-31-84-5    |   File "/usr/local/lib/python3.6/dist-packages/flair/models/sequence_tagger_model.py", line 369, in predict
web_nlu_ml.1.ryu06t0cj1wl@ip-172-31-84-5    |     feature = self.forward(batch)
web_nlu_ml.1.ryu06t0cj1wl@ip-172-31-84-5    |   File "/usr/local/lib/python3.6/dist-packages/flair/models/sequence_tagger_model.py", line 637, in forward
web_nlu_ml.1.ryu06t0cj1wl@ip-172-31-84-5    |     self.embeddings.embedding_length,
web_nlu_ml.1.ryu06t0cj1wl@ip-172-31-84-5    | RuntimeError: shape '[1, 4, 5632]' is invalid for input of size 20992
```

**To Reproduce**
sequence_tagger_model trained with bert-multilingual embeddings and flair multilingual parameters, where I set fine_tune=True

**Expected behavior**
it should work all the time

**Screenshots**

**Environment (please complete the following information):**
 - OS [Ubuntu]
 - Version [flair==0.6.0]
 - Torch = 1.6.0
 - Python=3.6

**Additional context**

**Comment by alanakbik** [comment]
Hi @igormis that's strange - can you check which sentences are affected? Could it be only very long ones?

**Comment by igormis** [comment]
but I am doing `sentence = Sentence(text[:4095])` before `model.predict(sentence)` and I have used allow_long_Sentences=True while training. I trained the model using Flair 0.6.1, PyTorch 1.7.1 and now I am using Flair 0.6.0 and Pytorch 1.6.0

**Comment by igormis** [comment]
and i tried with text with more than 5500 characters (>> 512) and it works.

**Comment by igormis** [comment]
Hi @alanakbik :), Using flair==0.6.1.post1 and torch==1.7.0+cu101 for training, here is the code for training:
```
embedding_types: List[TokenEmbeddings] = [
    FlairEmbeddings('multi-forward'),
    FlairEmbeddings('multi-backward'),
    TransformerWordEmbeddings('bert-base-multilingual-cased', pooling_operation='first_last',fine_tune=True, batch_size=8, layers='-1', use_scalar_mix=True, allow_long_sentences=True)
]
embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# 5. initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

# 7. start training

trainer.train('resources/taggers/example-ner',
              train_with_dev=True,
              patience=1,
              max_epochs=100)
```

**Comment by igormis** [comment]
Here is a sample of the output:
![image](https://user-images.githubusercontent.com/6599037/100379976-32862d00-3016-11eb-9cac-1e117574cfa3.png)

**Comment by igormis** [comment]
The inference code:
```
model = SequenceTagger.load('./nlu_ml_new/final-model.pt')
sentence = Sentence(text, use_tokenizer=True)
output =  model.predict(sentence)
predict_dict=output.to_dict(tag_type='ner')
```

**Comment by igormis** [comment]
And here is the error pattern:
```
RuntimeError: shape '[1, 57, 5632]' is invalid for input of size 319488
RuntimeError: shape '[1, 24, 5632]' is invalid for input of size 133632
RuntimeError: shape '[1, 3, 5632]' is invalid for input of size 15360
```

**Comment by igormis** [comment]
Can it be that the version on training must be the same as during inference? Now I am using: flair @ git+https://github.com/zalandoresearch/flair.git@be2272f1e3e55ff65fa8477ded16510e72787f58

**Comment by igormis** [comment]
@alanakbik it did not help, still I have the same error on model.predict...:(

**Comment by igormis** [comment]
@alanakbik I debug the input as I receive a lot of tweets in foreign languages (RU-Cyrilic, French, Chinese and so on) and the problem are the sentences of the following type:
- Des bulletins imprimés en Chine en plus 🤮🤮🤮
Whereas the model.predict function well on the following sentence
- Des bulletins imprimés en Chine en plus
So the emoticon are creating the bug... Any help on this?

**Comment by igormis** [comment]
The byte encoded request is decoded using 
`text = request.get_data().decode('utf-8')`
and this text is sent to the
`sentence = Sentence(text, use_tokenizer=True)` and then
` output =  model.predict(sentence)`

**Comment by igormis** [comment]
Some other samples:
- ¿Pelotones de fusilamiento? ¿Electrocución? Prepárense que lo que viene va a ser grandioso🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳M
- омг кажется всё - таки хуан вень и юань вместе 🥲🤎🤎🤎🤎
- Vois n’avez jamais eu une envie de meurtre ? Allez à la Poste ! 🤬🤬

**Comment by alanakbik** [comment]
Aha interesting ... could you try just embedding one of these problematic sentences to see if it throws the error? Then we can get a minimal code snippet to reproduce the error.

**Comment by igormis** [comment]
Yes it throws. I am sending:
- омг кажется всё - таки хуан вень и юань вместе - everything works
- омг кажется всё - таки хуан вень и юань вместе 🤎🤎🤎🤎 - the same error is thrown in forward function

**Comment by alanakbik** [comment]
@igormis this is likely a problem with the encoding of the emojis and the flair embeddings. However, unfortunately I cannot reproduce the error since the way the emojis are pasted in the issue works for me: 

```python
from typing import List

from flair.data import Sentence
from flair.embeddings import TokenEmbeddings, FlairEmbeddings, TransformerWordEmbeddings, StackedEmbeddings

embedding_types: List[TokenEmbeddings] = [
    FlairEmbeddings('multi-forward'),
    FlairEmbeddings('multi-backward'),
    TransformerWordEmbeddings('bert-base-multilingual-cased',
                              pooling_operation='first_last',fine_tune=True, batch_size=8, layers='-1',
                              use_scalar_mix=True, allow_long_sentences=True)
]
embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

embeddings.embed(Sentence("Vois n’avez jamais eu une envie de meurtre ? Allez à la Poste ! cursing_facecursing_face"))
```

Could you share the problematic sentences in such a way so I can "break" this snippet?
