### ISSUE TITLE
List of tags

### ISSUE THREAD

**Issue by PedroMTQ** [flairNLP/flair#1993]
Is there a list of the tags (with tag description) for each tagger available in flair?
I'm particularly interested in the ner and hunflair tagger

**Comment by mariosaenger** [comment]
Hi @PedroMTQ 

to the best of my knowledge there is no such list available. You can get the tag list of a tagger by running:
```python
ner_tagger = SequenceTagger.load("ner")
print(ner_tagger.tag_dictionary)
```  
In case of HunFlair, the tagger consist of multiple distinct taggers (one for each entity type). So you may run:
```python
for name, tagger in hunflair_tagger.name_to_tagger.items():
    print(name)
    print(tagger.tag_dictionary)
``` 
However, this will only give you the tags without a detailed description. For the latter, I think you really have to consult the gold standard data sets the models are trained on. For HunFlair, please refer to our arxiv paper (https://arxiv.org/pdf/2008.07347.pdf) as well as the list of biomedical NER data sets:

 https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_CORPORA.md

**Comment by PedroMTQ** [comment]
Thanks, I was also curious about the pos tagger, I can see the list with tag_dictionary.get_items() but is there an explanation of what each tag means?
it has these tags:
['<unk>', 'O', 'UH', ',', 'VBD', 'PRP', 'VB', 'PRP$', 'NN', 'RB', '.', 'DT', 'JJ', 'VBP', 'VBG', 'IN', 'CD', 'NNS', 'NNP', 'WRB', 'VBZ', 'WDT', 'CC', 'TO', 'MD', 'VBN', 'WP', ':', 'RP', 'EX', 'JJR', 'FW', 'XX', 'HYPH', 'POS', 'RBR', 'JJS', 'PDT', 'NNPS', 'RBS', 'AFX', 'WP$', '-LRB-', '-RRB-', '``', "''", 'LS', '$', 'SYM', 'ADD', 'NFP', '<START>', '<STOP>']

I can see that some of them are similar to the standard nltk tagging (i.e. https://stackoverflow.com/questions/15388831/what-are-all-possible-pos-tags-of-nltk) , but some of them aren't... 

Also, could you please consider adding an iteration method to tag_dictionary?

**Comment by mariosaenger** [comment]
What do you mean with iteration method? Actually you can iterate through the list of tags via:
```python
for tag in ner_tagger.tag_dictionary.item2idx.keys():
    print(tag)
```

@alanakbik Do you have a nice overview of the used tag set at hand? According to the documentation page the tagger is trained on Ontonotes.
