### ISSUE TITLE
HunFlair dependency model download？

### ISSUE THREAD

**Issue by YaoXinZhi** [flairNLP/flair#1998]
Can i download the dependent model of HunFlair directly, such as "https://nlp.informatik.hu-berlin.de/resources/models/hunflair_smallish_models/cellline/hunflair-celline-v1.0.pt" and put it in the designated directory to avoid Does the code download automatically, because the file is too big to download. 
  If I download the model separately, which folder should I put in? The code points to a temporary file "/tmp/tmpiid78e3d".

**Comment by mariosaenger** [comment]
Hi @YaoXinZhi ,

I'm afraid I can't get your problem exactly :-( Is your tmp directory (resp. hard drive) too small to store the models? In principle you are also able to download the models manually and save them in a custom directory. You can then load the Flair models by specifying the exact file location.  For example, for HunFlair:
```python
hunflair_tagger = MultiTagger.load([
    "<your-model-path>/hunflair-celline-v1.0.pt",
    "<your-model-path>/hunflair-chemical-full-v1.0.pt",
    "<your-model-path>/hunflair-disease-full-v1.0.pt",
    "<your-model-path>/hunflair-gene-full-v1.0.pt",
    "<your-model-path>/hunflair-species-full-v1.1.pt"
])
```
This could maybe a workaround?

**Comment by YaoXinZhi** [comment]
My problem is solved, thank you.
