### ISSUE TITLE
HunFlair model save path.

### ISSUE THREAD

**Issue by YaoXinZhi** [flairNLP/flair#1999]
I noticed that if you run the tool under windows system, the model will be downloaded to the system disk (C drive) by default, and it will be downloaded to the root directory (non-working directory) by default in Linux, but the model size exceeds 5G, which makes the system Running slowly, maybe there are other ways to improve it ?

**Comment by mariosaenger** [comment]
Hi @YaoXinZhi 

thanks for noticing. However, I can't reproduce it on my system (linux) exactly. In my setting the files will be stored in the Flair cache directory `/home/<user>/.flair/models` (and not in the root directory). Can you specify more details of your setup (i.e. os, python and flair version)?

Moreover, you should be able to specify a custom cache directory by setting the environment variable `FLAIR_CACHE_ROOT`. I think this is the most simple way to change the location of Flair models and data sets. Have you tried this?

**Comment by YaoXinZhi** [comment]
My problem has been solved, thank you.

**Comment by alanakbik** [comment]
Did @mariosaenger's answer help or did you solve it a different way?

**Comment by YaoXinZhi** [comment]
Yes, I solved the problem by changing the environment variables `FLAIR_CACHE_ROOT` , sorry for the late reply.

**Comment by nbosc** [comment]
Hi, is this solution still valid in 2025?
