### ISSUE TITLE
Model storage location

### ISSUE THREAD

**Issue by YaoXinZhi** [flairNLP/flair#2000]
https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/data/linkers/2020-10-09/umls/tfidf_vectors_sparse.npz not found in cache, downloading to C:\Users\ADMINI~1\AppData\Local\Temp\tmp6jy2sdhy

Can you tell me the path where the model is stored (searched)? When the model needs to be downloaded, it will be convenient for users to download the model and put it into this folder. Thanks

**Comment by whoisjones** [comment]
All downloads will be stored in your home directory in a .flair folder, i.e. on a linux machine ~/.flair/embeddings.

`# global variable: cache_root
cache_root = os.getenv('FLAIR_CACHE_ROOT', Path(Path.home(), ".flair"))`

**Comment by YaoXinZhi** [comment]
My problem is solved, thank you.
