### ISSUE TITLE
AttributeError: module 'tensorflow_core.keras.activations' has no attribute 'swish'

### ISSUE THREAD

**Issue by ishan42d** [flairNLP/flair#2005]
I am very new to this flair package but belive that it can help me resolve the current challenges I am facing right now. I am just trying to get some basics right and while using the following code:

from flair.data import Sentence
sentence = Sentence('The grass is green.')
print(sentence)

**I got this error:**
AttributeError: module 'tensorflow_core.keras.activations' has no attribute 'swish'

Can someone explain this to me why is this happening? TF is already there on my system and I am not sure why I am getting this error

**Comment by whoisjones** [comment]
Hi @ishan42d, you're code is working just fine. Here's my print out:
`Sentence: "The grass is green ."   [− Tokens: 5]`
Flair is built up on PyTorch, not on TensorFlow - so i guess it is rather another error on your side and nothing related to flair. You might wanna look at this issue here which seems more related to your problem: [Issue](https://github.com/huggingface/transformers/issues/7333)

**Comment by ishan42d** [comment]
@whoisjones : Thank you so much! Let me look into this.

**Comment by ishan42d** [comment]
Reinstalling Tensorflow helped actually! PyTorch was running fine and was not the issue, TF was. Closing this issue

**Comment by rafelps** [comment]
Hi, I had the same exact problem, which I can reproduce by just doing:
```
from flair.data import Sentence
flair_sentence = Sentence('hello')
```

However, looking at the repo it seems there is nothing about TF nor Keras. Do you have any insight of why this is happening? Maybe some cross-imports?

By the way, as mentioned, the issue can be resolved by changing TF version. The question is: Why a TF error?

Thanks for your work and support!

**Comment by whoisjones** [comment]
As mentioned in this issue, your problem arises from using transformers (which we are using in flair) and this is not compatible with TF versions >= 2.1

**Comment by rafelps** [comment]
> As mentioned in this issue, your problem arises from using transformers (which we are using in flair) and this is not compatible with TF versions >= 2.1

It makes a lot of sense now! Flair uses PyTorch but it has a "far" requirement with TF through transformers.

Thank you very much!
