### ISSUE TITLE
Train a NER using BILUO or IOB Tags ? 

### ISSUE THREAD

**Issue by wahid18benz** [flairNLP/flair#2016]
Hi,

I have a dataset which is already in BILUO schema, should I transform it to IOB format before running my training Flair NER model ? does Flair NER accept both format ? if yes  which one is better ?

Thank you,
Wahid

**Comment by helpmefindaname** [comment]
Hi @wahid18benz Flair supports the BIO schema and the BIOES. You can do a 1 to 1 conversion by replacing L-tags with E-tags and U-tags with S-tags. Besides that, BIOES and BILOU are exactly the same.

**Comment by wahid18benz** [comment]
So clear, thank you @helpmefindaname
