### ISSUE TITLE
When training chinese dataset for ner task, RuntimeError: The size of tensor a (640) must match the size of tensor b (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by xiaomao979** [flairNLP/flair#2023]
My dataset ignore the pos but only focus on ner
```
袁 N O
希 N O
治 N O
1 N O
9 N O
4 N O
6 N O
年 N O
生 N O
， N O
湖 N O
北 N O
汉 N O
阳 N O
人 N O
。 N O
二 N B
级 N I
演 N I
员 N I
。 N O
```
I used the bert-base-chinese to achieve embedding, my code is
```
# -*- coding: utf-8 -*-

from flair.data import Corpus
from flair.datasets import ColumnCorpus
from flair.embeddings import TokenEmbeddings, WordEmbeddings, StackedEmbeddings
from flair.embeddings import TransformerWordEmbeddings


# define columns
columns = {0: 'text', 1: 'pos', 2: 'ner'}

# this is the folder in which train, test and dev files reside
data_folder = 'dataset'

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus('dataset', columns,
                              train_file='flair_train_small.txt',
                              test_file='flair_test_small.txt',
                              dev_file='flair_dev_small.txt')


# 2. what tag do we want to predict?
tag_type = 'ner'

# 3. make the tag dictionary from the corpus
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print(tag_dictionary)

# 4. initialize embeddings
# bert-base-chinese
# embedding_types = TransformerWordEmbeddings('bert_base_chinese')
embedding_types = [

    TransformerWordEmbeddings('bert_base_chinese'),
]


embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

# 5. initialize sequence tagger
from flair.models import SequenceTagger

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type,
                                        use_crf=True)

# 6. initialize trainer
from flair.trainers import ModelTrainer

trainer: ModelTrainer = ModelTrainer(tagger, corpus)

# 7. start training
trainer.train('output_ch',
              learning_rate=0.1,
              mini_batch_size=4,
              max_epochs=30)
```
my first run is successful, but due to the RAM, i stop the first and wait the english version finish. However, when the second, the error is weird
```
RuntimeError: The size of tensor a (609) must match the size of tensor b (512) at non-singleton dimension 1
```

and everytime the error is changing, for the next try, the error is 
```
RuntimeError: The size of tensor a (664) must match the size of tensor b (512) at non-singleton dimension 1

```
it is soooooo weird
Thank you very much if i can get help from you!!!

**Comment by whoisjones** [comment]
Hi @xiaomao979, it is not clear to me what you are exactly doing. I am not able to reproduce, you have some errors in your code, i.e. `TransformerWordEmbeddings('bert_base_chinese')` is not a model on huggingface. can you provide detailed explanation of your training procedure?

**Comment by xiaomao979** [comment]
> Hi @xiaomao979, it is not clear to me what you are exactly doing. I am not able to reproduce, you have some errors in your code, i.e. `TransformerWordEmbeddings('bert_base_chinese')` is not a model on huggingface. can you provide detailed explanation of your training procedure?

‘bert_base_chinese’ is a file which contains config.json, pytorch_model.bin and vocab.txt, I download from the https://huggingface.co/bert-base-chinese and rename bert_base_chinese.

**Comment by xiaomao979** [comment]
> Hi @xiaomao979, it is not clear to me what you are exactly doing. I am not able to reproduce, you have some errors in your code, i.e. `TransformerWordEmbeddings('bert_base_chinese')` is not a model on huggingface. can you provide detailed explanation of your training procedure?

if i directly use bert-base-chinese, the error is 
```
ValueError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.
```

**Comment by whoisjones** [comment]
Do you have an internet connection on your machine? Do you apply any preprocessing to your data? Your issue looks like some tensor shapes are not matching. Can you also provide your full data (or at least large enough) to reproduce?

However, if you use a local model, please do so as huggingface documentation suggests:
```from transformers import AutoTokenizer, AutoConfig, AutoModel
tokenizer = AutoTokenizer.from_pretrained("bert-chinese-base")
config = AutoConfig.from_pretrained("bert-chinese-base", output_hidden_states=True)
model = AutoModel.from_pretrained("bert-chinese-base", config=config)
```

Store it to memory:
```
tokenizer.save_pretrained('./local_model_directory/')
model.save_pretrained('./local_model_directory/')
```

Then load via TransformerWordEmbedding class:
```
from flair.embeddings import TransformerWordEmbeddings
local_model = TransformerWordEmbeddings("./local_model_directory/")
```

**Comment by olanag1** [comment]
Hi, I have the same error, trying to train TARS with scibert (published oh huggingface transformers) model. 

Here is the code : 
`from flair.models.text_classification_model import TARSClassifier
from flair.trainers import ModelTrainer

# 3. create a TARS classifier
tars = TARSClassifier(task_name='francis', label_dictionary=corpus.make_label_dictionary(), document_embeddings='allenai/scibert_scivocab_uncased')

# 4. initialize the text classifier trainer
trainer = ModelTrainer(tars, corpus)

# 5. start the training
trainer.train(base_path=data_folder+'francis_model', # path to store the model artifacts
              learning_rate=0.02, # use very small learning rate
              mini_batch_size=16,
              mini_batch_chunk_size=1, # optionally set this if transformer is too much for your machine
              max_epochs=10, # terminate after 10 epochs
              train_with_dev=True
              )`


And here is the error : 
`RuntimeError                              Traceback (most recent call last)
<ipython-input-6-30cb2dfc9073> in <module>
     18               mini_batch_chunk_size=1, # optionally set this if transformer is too much for your machine
     19               max_epochs=10, # terminate after 10 epochs
---> 20               train_with_dev=True
     21               )

~/src/anaconda3/lib/python3.7/site-packages/flair/trainers/trainer.py in train(self, base_path, learning_rate, mini_batch_size, mini_batch_chunk_size, max_epochs, scheduler, cycle_momentum, anneal_factor, patience, initial_extra_patience, min_learning_rate, train_with_dev, monitor_train, monitor_test, embeddings_storage_mode, checkpoint, save_final_model, anneal_with_restarts, anneal_with_prestarts, batch_growth_annealing, shuffle, param_selection_mode, write_weights, num_workers, sampler, use_amp, amp_opt_level, eval_on_train_fraction, eval_on_train_shuffle, save_model_at_each_epoch, **kwargs)
    371 
    372                         # forward pass
--> 373                         loss = self.model.forward_loss(batch_step)
    374 
    375                         # Backward

~/src/anaconda3/lib/python3.7/site-packages/flair/models/text_classification_model.py in forward_loss(self, data_points)
    788         sentences = self._get_tars_formatted_sentences(data_points)
    789 
--> 790         return self.tars_model.forward_loss(sentences)
    791 
    792     def _transform_tars_scores(self, tars_scores):

~/src/anaconda3/lib/python3.7/site-packages/flair/models/text_classification_model.py in forward_loss(self, data_points)
    142     ) -> torch.tensor:
    143 
--> 144         scores = self.forward(data_points)
    145 
    146         return self._calculate_loss(scores, data_points)

~/src/anaconda3/lib/python3.7/site-packages/flair/models/text_classification_model.py in forward(self, sentences)
     95     def forward(self, sentences):
     96 
---> 97         self.document_embeddings.embed(sentences)
     98 
     99         embedding_names = self.document_embeddings.get_names()

~/src/anaconda3/lib/python3.7/site-packages/flair/embeddings/base.py in embed(self, sentences)
     58 
     59         if not everything_embedded or not self.static_embeddings:
---> 60             self._add_embeddings_internal(sentences)
     61 
     62         return sentences

~/src/anaconda3/lib/python3.7/site-packages/flair/embeddings/document.py in _add_embeddings_internal(self, sentences)
     94 
     95         for batch in sentence_batches:
---> 96             self._add_embeddings_to_sentences(batch)
     97 
     98         return sentences

~/src/anaconda3/lib/python3.7/site-packages/flair/embeddings/document.py in _add_embeddings_to_sentences(self, sentences)
    142 
    143             # put encoded batch through transformer model to get all hidden states of all encoder layers
--> 144             hidden_states = self.model(input_ids, attention_mask=mask)[-1] if len(sentences) > 1 \
    145                 else self.model(input_ids)[-1]
    146 

~/src/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/src/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, output_attentions, output_hidden_states, return_dict)
    836 
    837         embedding_output = self.embeddings(
--> 838             input_ids=input_ids, position_ids=position_ids, token_type_ids=token_type_ids, inputs_embeds=inputs_embeds
    839         )
    840         encoder_outputs = self.encoder(

~/src/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

~/src/anaconda3/lib/python3.7/site-packages/transformers/modeling_bert.py in forward(self, input_ids, token_type_ids, position_ids, inputs_embeds)
    199         token_type_embeddings = self.token_type_embeddings(token_type_ids)
    200 
--> 201         embeddings = + position_embeddings + token_type_embeddings
    202         embeddings = self.LayerNorm(embeddings)
    203         embeddings = self.dropout(embeddings)

RuntimeError: The size of tensor a (613) must match the size of tensor b (512) at non-singleton dimension 1inputs_embeds `
