### ISSUE TITLE
Train Custom Flair Embeddings with list of list of tokens

### ISSUE THREAD

**Issue by shenron9155** [flairNLP/flair#2028]
A clear and concise description of what you want to know.
Is the `Corpus` function supported while training the flair embeddings? My data is already tokenized in a list and I am unable to save it so that I can leverage the `TextCorpus` function. My current approach is to use the `SentenceDataset` with `Sentence(tokens, use_tokenizer = False)` for each sentence and then use `Corpus`. However I get the error: `'SentenceDataset' object has no attribute size`. I also prefer to use the same token format as when I get to the task specific problem my tags matches up.

**Comment by whoisjones** [comment]
Hi @shenron9155, what are you doing exactly? If you doing sequence labeling you might wanna check out the `ColumnCorpus` object, described here in our [documentation](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md).

**Comment by shenron9155** [comment]
@whoisjones I am training a custom LM model and loading my data from an API. Ideally I would want to train the char LM model using a generator so I dont need to save all the data in memory then to a file.
