### ISSUE TITLE
Train over entire dataset

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#2033]
For various reasons, we might want to have a `Corpus` that does not define all three splits (train/dev/test). For instance, we might want to train a model over the entire dataset and not hold out any data for validation/evaluation. 

This issue tracks the progress of adding this functionality to Flair.

**Comment by afi1289** [comment]
Hello, 
I am trying to train a model for NER using all training data (2418 sentences). However, after creating corpus I see that the model will receive only 1958 sentences for training, 242 for testing and 218 for validation. That means that ```Corpus``` will define all three splits (train/dev/test) implicitly.

````
# get the corpus
corpus: Corpus = ColumnCorpus(data_folder, columns,
                             train_file = 'train.txt')
````
Check training data:
````
print(len(corpus.train))
Output: 1958
````
Check testing data:
`````
print(len(corpus.dev))
Output: 218

print(len(corpus.test))
Output: 242
`````
Thanks in advance!

**Comment by alanakbik** [comment]
@afi1289 if you set sample_missing_splits=False it will not sample and leave everything in the train file: 

```python
# get the corpus
corpus: Corpus = ColumnCorpus(data_folder, columns,
                             train_file = 'train.txt', sample_missing_splits=False)
```

However, this feature is currently only in master branch, so if you install through pip you don't yet have it until the next release.
