### ISSUE TITLE
Three Class Sentiment Model from Pretrained Model

### ISSUE THREAD

**Issue by Rasmitha23** [flairNLP/flair#2036]
The transformer bases pretrained sentiment model which flair offers currently is a two-class sentiment model i.e., it predicts only POSITIVE and NEGATIVE classes. Is there a way I can make it into 3-Class and fine-tune it?

One of the ideas I have is to add one mode node (for neutral class) in the last layer of the pre-trained model and initialize all the weights to this node randomly and fine-tune the entire network with some data? 

Can I do something like this using flair? Are there any other ways I can do this?

**Comment by alanakbik** [comment]
Yes, there are several ways to do it: You could retrain the entire model with 3 classes. The current model was trained mostly with Amazon reviews which could have between 1 and 5 stars, mapped to POSITIVE and NEGATIVE. You could for instance keep 3-star reviews and treat them as neural, though I am not sure if this would work well since 3 star reviews are somewhat irregular in their "tone". 

You can change the mapping like this: 

```python
# map stars to labels (binary, you would need to map some to NEUTRAL)
label_name_map: Dict[str, str] = {
                '1.0': 'NEGATIVE',
                '2.0': 'NEGATIVE',
                '3.0': 'NEGATIVE',
                '4.0': 'POSITIVE',
                '5.0': 'POSITIVE',
            }

# load corpus with mapped label names
corpus= AMAZON_REVIEWS(filter_if_longer_than=50, label_name_map=label_name_map, memory_mode='partial', split_max=50000, fraction_of_5_star_reviews=12)
```

You could also load the current model and replace the last linear layer and with a randomly initialized layer with 3 outputs. You would also have to replace the tag dictionary. Then you could fine-tune on a new task. 

Or you use TARS. It may be able to already give you neutral as it is. For instance like this 

```python
# 1. Load our pre-trained TARS model for English
tars = TARSClassifier.load('tars-base')

# 2. Prepare some test sentences
sentences = [Sentence("I am so glad you like burritos!"), Sentence("Burritos are ok."), Sentence("I hate burritos.")]

# 3. Predict zero-shot for classes "positive", "negative" and "neutral" and print results
labels = ["positive sentiment", "negative sentiment", "neutral sentiment"]

for sentence in sentences:
    tars.predict_zero_shot(sentence, labels)
    print(sentence) 
```

Check out the [tutorial for more info on TARS](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md) and how to fine-tune it.

**Comment by Rasmitha23** [comment]
Thank you @alanakbik 
I am working on a no internet access machine. When I run tars = TARSClassifier.load('tars-base') I was getting an error as it tries to download the tars-base.pt model from https://nlp.informatik.hu-berlin.de/resources/models/tars-base/. I downloaded it manually and put it in .flair/models/. 
Now it is able to access the model but it is still trying to download something else from the internet. Can you please help me figure out what is being downloaded and where it will store this, so that I can manually download it and put it in that specific folder. Thank you! 
Attaching the screenshot
![image](https://user-images.githubusercontent.com/12725119/102757371-3e57db80-4397-11eb-9fcf-6259a787bed6.png)

**Comment by kishaloyhalder** [comment]
Hi @Rasmitha23 

Let me try to pitch in here. Seems like the kernel is not able to find the file. Could you please make sure you have restarted the kernel after placing the `.pt` file inside `.flair/models` directory? If that does not work as well, then try loading using the path to the `.pt` file:
```python
tars = TARSClassifier.load('path/to/tars-base.pt')
```

Let us know if that helps. 

with regards,
Kishaloy

**Comment by Rasmitha23** [comment]
Thank you Kishaloy for replying. I am still getting the same error. When i run the same thing on a machine which has internet access. It seems like the code is downloading three files. 
One is the tars-base.pt. I am not sure about the other two.
Screenshot from the machine with internet access. 
![image](https://user-images.githubusercontent.com/12725119/102769922-56385b00-43a9-11eb-81ab-ccba142c4dfe.png)

**Comment by kishaloyhalder** [comment]
Hi @Rasmitha23 

Yes, I realized looking at your previous screenshot that the code *was* able to find `tars-base.pt` file and retracted my comment.

Looks like it is trying to download the pre-trained tokenizer files(?). Anyway, are you able to use the model now?

with regards,
Kishaloy

**Comment by alanakbik** [comment]
Hi all, our serialization logic at the moment does not serialize the transformer tokenizers. So each time you load the model they are re-loaded, meaning first time the tokenizer is downloaded, then it is loaded. This means that without internet connection you unfortunately currently cannot load TARS unless you already loaded it before once with an internet connection. 

This is something I am currently in the process of refactoring, but there's lots of issues to consider so I cannot say when refactoring will be done!

**Comment by Rasmitha23** [comment]
Thank Kishaloy and @alanakbik 

Where would this tokenizer be saved when its downlaoded? If I can identify this file I can copy it to the same location on no-internet access machine and it should work right? Can you let me know where can I find this downloaded file?

**Comment by kishaloyhalder** [comment]
Hi @Rasmitha23 

These files are coming from the transformers package. In my setup, I can find them inside my home directory at `.cache/torch/transformers/`. You could try copy pasting the associated files there, but I am not sure unfortunately if that would work. Good luck!

with regards,
Kishaloy

**Comment by daniel-perez-garcia** [comment]
Hi @alanakbik 
is it possible for you guys to provide the domain I need to whitelist if I am pulling the files from behind a Virtaul Network?
