### ISSUE TITLE
TARSClassifier crashes

### ISSUE THREAD

**Issue by ashokxnarang** [flairNLP/flair#2043]
**Describe the bug**
TARSClassifier crashes. 

Was folllowing the Tutorial 10 (https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md) , Use Case 2 (Use Case #2: Classify Text With Very Little Training Data (Few-Shot).

Stack Trace:
("train_few_shots_tars.py is my own file with the code from the Tutorial)

2020-12-26 21:38:02,067 Testing using best model ...
Traceback (most recent call last):
  File "train_few_shots_tars.py", line 75, in <module>
    train_with_dev=True,
  File "C:\Python37\lib\site-packages\flair\trainers\trainer.py", line 616, in train
    final_score = self.final_test(base_path, mini_batch_chunk_size, num_workers)
  File "C:\Python37\lib\site-packages\flair\trainers\trainer.py", line 664, in final_test
    embedding_storage_mode="none",
  File "C:\Python37\lib\site-packages\flair\models\text_classification_model.py", line 342, in evaluate
    target_names=target_names, zero_division=0)
TypeError: classification_report() got an unexpected keyword argument 'zero_division'

**To Reproduce**
Run Tutorial 10  Use Case #2: Classify Text With Very Little Training Data (Few-Shot)

**Expected behavior**

Training on TARSClassifier and prediction should complete successfully.

**Screenshots**
Please refer Stacktrace above.

**Environment (please complete the following information):**
Python v3.7, flair v0.7, Windows 10.

**Additional context**
N.A.

**Comment by kishaloyhalder** [comment]
Hi @ashokxnarang 

Thanks for reaching out! This error is coming from `sklearn`. Seems like you have an older version installed in your setup. Could you please upgrade it and try again (refer [here](https://github.com/flairNLP/flair/issues/1722#issuecomment-683788616)). Good luck!

with regards,
Kishaloy

**Comment by ashokxnarang** [comment]
Thanks a lot Kishaloy ! That indeed  was the problem. Was on scikit-learn
0.21 . An upgrade to 0.24 fixed the problem.

Regards
Ashok
