### ISSUE TITLE
OSError: HEAD request failed for url

### ISSUE THREAD

**Issue by bhardwaj1230** [flairNLP/flair#2048]
**Describe the bug**
Script:
from flair.data import Sentence
from flair.models import SequenceTagger
#make a sentence
sentence = Sentence('I love Berlin .')
#load the NER tagger
tagger = SequenceTagger.load('ner')

Error:
OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt with status code 301.

**To Reproduce**
tagger = SequenceTagger.load('ner')

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux (CUDA=10.1, Tesla V100 GPU)
 - Version [e.g. flair-0.3.2]: flair==0.7 

**Additional context**

**Comment by alanakbik** [comment]
You probably have an old version of Flair installed. Can you share the output of the following code: 

```python
import flair
print(flair.__version__)
```
