### ISSUE TITLE
Unpickling error: wrong torch version.

### ISSUE THREAD

**Issue by vedangj044** [flairNLP/flair#2049]
**Describe the bug**
The torch version described in requeirements.txt is 1.1.0, but I am facing the following error with torch version 1.3.0 while importing the `en-sentiment` model.

`UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.`

**To Reproduce**
1. Force install torch==1.3.0
2. Run `flair.models.TextClassifier.load("en-sentiment")`

**Expected behavior**
The model should be loaded.

**Screenshots**
Please have a look at the following google colab notebook, which contains the traceback and also the fix for this issue.
[Link](https://colab.research.google.com/drive/1LIxvkBnYAwP62f6kiNyErBTXJCm7PHEn?usp=sharing)

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Debian 9
 - Version [e.g. flair-0.3.2]: 0.7

**Additional context**
This issue can be fixed using torch version 1.5.0 or above, Should I submit a PR for it?

**Comment by alanakbik** [comment]
Interesting, thanks for spotting this and providing the notebook! Yes, we'd appreciate a PR!
