### ISSUE TITLE
Error installing Flair on Kaggle notebook

### ISSUE THREAD

**Issue by harshpatel1014** [flairNLP/flair#2053]
I tried installing flair in Kaggle's notebook.
However, while installing flair some dependencies issues occur.

I cannot figure out which libraries are causing dependency issues.
Any idea how to install flair on the Kaggle environment.
Thank You

**Comment by jackhanslope** [comment]
I was having a similar issue. I solved it by uninstalling the `typing` package: 
```
pip uninstall --yes typing
pip install flair
```

**Comment by harshpatel1014** [comment]
Thanks

**Comment by TechnoRahmon** [comment]
> I was having a similar issue. I solved it by uninstalling the `typing` package:
> 
> ```
> pip uninstall --yes typing
> pip install flair
> ```

this does not work with me

after installing flair, 

I am trying to import it 

```
import flair
```
and got error :
```
ModuleNotFoundError: No module named 'botocore.compress'
```

**Comment by helpmefindaname** [comment]
Hi @TechnoRahmon 
as flair is never importing `botocore.compress`,
can you please post the full stack trace?
also, can you please post the versions of all libraries mentioned in the stack trace (e.g. `pip show flair`, ..., `pip show botocore`)?

**Comment by TechnoRahmon** [comment]
actually, I can see that this issue it only happened with me in Kaggle, I tried Colab it has not issues,
I found the fix finally, where I had to install a specific version of `botocore=1.32.4`  and upgrade `boto3 aiobotocore`

here is the command : 
```python
!pip install botocore==1.32.4
!pip install --upgrade boto3 aiobotocore
!pip install flair
```
this  works fine with me and I used `flair` successfully :)
