### ISSUE TITLE
'ner-ontonotes-fast'  Architecture

### ISSUE THREAD

**Issue by Akshaysharma29** [flairNLP/flair#2054]
Hi team, 
Thanks for such wonderful repo. I want to know the architecture of the model  'ner-ontonotes-fast'  and is it bert based or something else?
Thanks

**Comment by alanakbik** [comment]
It's based on Flair embeddings (so it doesn't use BERT). You can find the script used to train it [here](https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md#ontonotes-named-entity-recognition-english).
