### ISSUE TITLE
How to replace , LSTM with CNN in Character Embeddings class ?

### ISSUE THREAD

**Issue by KushalVijay** [flairNLP/flair#2055]
I want to use CNN instead of LSTM in Character Embeddings class here [link](https://github.com/flairNLP/flair/blob/4aa77cbc62720a8f0e5a595ab264f82aaaad10dc/flair/embeddings/token.py#L263)

I'm using this Character Embeddings along with other embedding using StackedEmbeddings. So require help how to integrate Character Embeddings with CNN or how to integrate Custom Embeddings with pre-trained model since I also have a pretrained CNN model

Please help!

**Comment by bernardoleite** [comment]
Hey!

Did you find a solution to this problem?

Thanks in advance.
Regards
