### ISSUE TITLE
Keep newline in Sentence for sequence tagging prediction

### ISSUE THREAD

**Issue by geniki** [flairNLP/flair#2069]
**Describe the bug**
I'd like to keep the newline character `\n` when doing sequence tagging prediction (keeping it during training seems easier because of the different code paths).
https://github.com/flairNLP/flair/blob/master/flair/data.py#L605 This line removes the newline character after the text has been tokenised. Given that `flair` is very flexible in terms of tokenisation, I think this last-minute modification of tokens is unwelcome. If I wanted to have run `.strip()` on my tokens, I should have done it during tokenisation.

I understand I can replace `\n` with another unused character and then swap them back later but it'd be cleaner if we can avoid that.

**To Reproduce**
`Sentence(["hello", "\n"])`, not using a tokeniser because the text is already tokenised. 

**Expected behavior**
I expect two tokens but I get only one.

**Environment (please complete the following information):**
 - OS: Linux
 - Version: flair 0.7

**Comment by alanakbik** [comment]
@geniki good point! I'll put in a PR for this.

**Comment by geniki** [comment]
Many thanks for the quick response @alanakbik. This really helps.

I noticed that `SpacyTokenizer` [here](https://github.com/flairNLP/flair/blob/d66b016fa6d755f9016cab4efab5b7e75aaef721/flair/tokenization.py#L50) also has `.strip()` hardcoded so changing the tokens given by spacy. I'm not sure whether you'd like to change this as well. It's much easier to handle thanks to the change you already made but might be unexpected if people don't step through the code.
