### ISSUE TITLE
Model size in deployment 

### ISSUE THREAD

**Issue by Michael95-m** [flairNLP/flair#2071]
I'd like to ask some advice for flair model **deployment**.  I have a sequence tagger model with size around **230 MB** ( I used word2vec and bytepair embedding ). Currently, I used **flask** and **uwsgi** server for deployment. The problem is that this uwsgi process takes around over **1 GB**  in memory. What I need is that I want to **reduce memory** usage. Are there any **techniques** to reduce this memory usage or any new **deployment** tactics?

**Comment by robinvanschaik** [comment]
Hi @Michael95-m, 

I am a big fan of FastAPI over Flask. 

However, I saw [this benchmark](https://www.appdynamics.com/blog/engineering/a-performance-analysis-of-python-wsgi-servers-part-2/)
which may help you out in your choice.
