### ISSUE TITLE
Huge difference in performance score when looking at the output after a model is finished training and when using the evaluate function?

### ISSUE THREAD

**Issue by EdanToledo** [flairNLP/flair#2078]
Im working on a NER model in dutch for a specific domain and after training a model the output at the end says the following:

```
Results:
- F1-score (micro) 0.5714
- F1-score (macro) 0.4831

By class:
SymProp    tp: 13 - fp: 25 - fn: 21 - precision: 0.3421 - recall: 0.3824 - f1-score: 0.3611

SymRel     tp: 3 - fp: 3 - fn: 7 - precision: 0.5000 - recall: 0.3000 - f1-score: 0.3750

Symptom    tp: 46 - fp: 19 - fn: 18 - precision: 0.7077 - recall: 0.7188 - f1-score: 0.7132

```

But when i use the evaluate function using this code:

```
from flair.models import SequenceTagger

tagger = SequenceTagger.load('/content/flairmodels/ner/final-model.pt')


result, score = tagger.evaluate(corpus.test, mini_batch_size=1, out_path=f"predictions.txt")

print(result.detailed_results)
```

i get these crazy good results:

```
Results:
- F1-score (micro) 0.9580
- F1-score (macro) 0.9520
By class:
SymProp    tp: 48 - fp: 3 - fn: 4 - precision: 0.9412 - recall: 0.9231 - f1-score: 0.9320
SymRel     tp: 17 - fp: 0 - fn: 2 - precision: 1.0000 - recall: 0.8947 - f1-score: 0.9444
Symptom    tp: 72 - fp: 2 - fn: 1 - precision: 0.9730 - recall: 0.9863 - f1-score: 0.9796


```
granted i know its a very small dataset, im very confused in the large disparity between performance. Any explanation would be helpful.

**Comment by alanakbik** [comment]
Hello @EdanToledo this should not happen since the evaluate method is also called after training is complete. So the numbers should be identical. 

Are you downsampling the corpus? If so, this would explain different numbers since the downsampling is not deterministic. You would get different numbers every time, especially if you downsample to a very small sample.

**Comment by EdanToledo** [comment]
Thanks for the quick response. I'm not downsampling but I'm using google colab and i feel maybe due to some connection issue the corpus reshuffled, but even if this was on the training set, it shouldnt be this good correct?

**Comment by alanakbik** [comment]
It's a really high number, but depending on the difficulty of the problem it could be correct. 4-class NER for English for instance goes up to 94 F1 score over a huge test sample. 

You can try inspecting the `predictions.txt` that is generated and compare it to the `test.tsv` file that is generated during training. These files record the predictions. You could also load the model yourself and do some predictions with sentences you type in yourself to see if the predictions make sense.

**Comment by afi1289** [comment]
Hello @EdanToledo 
Unfortunately, I have the same problem. Using ```evaluate``` function returns better results. Did you find why??
