### ISSUE TITLE
How to print accuracy or F1 score in every epoch

### ISSUE THREAD

**Issue by abeermohamed1** [flairNLP/flair#2080]
Hello, I appreciate your help with the below question.
Currently, the below only is displayed (train_loss_history). For SequenceTagger  I need to print the accuracy or F1 score as well to use it in pyplot 

2020-03-27 15:19:00,766 epoch 150 - iter 120/128 - loss 0.56220125 - samples/sec: 58.56

and for the list 

 'train_loss_history': [1.1647640503942966,
  1.4817853784188628,
  1.566203641705215,
  1.7279450315982103,
  2.125648947432637,
  1.614249327685684,
  1.5095471823588014,
  1.3308049449697137,
  1.3301355633884668,
  1.2886016678530723,
  1.1256465977057815,

**Comment by afi1289** [comment]
Hi,
did you find a solution?
