### ISSUE TITLE
Custom Input Features

### ISSUE THREAD

**Issue by alejandrojcastaneira** [flairNLP/flair#2082]
One of the greatest strengths of the Flair library is that it allows you to freely combine multiple different types of textual embeddings.

**Is your feature/enhancement request related to a problem? Please describe.**

As day to day more and more stylish content is released, that is, the textual information available online includes multiple dimensions like fonts, color, style, positioning, etc., where some of them can have a direct impact on predictions. Perhaps, the possibility to combine some of these properties or even customized ones as input to the models could be another amazing feature in the library.

**Describe the solution you'd like**

Some options would be, if we could attach together to the different words embedding available within the StackedEmbeddings class, for example, a vector with the (x, y) coordinates of each word within the document, or a normalized scalar for the font size, a one-encoding for the font type or style, or perhaps even the input of some CNN with the information of the pixels of the word, etc.

**Comment by alanakbik** [comment]
Hello @alejandrojcastaneira - I think that's a good idea and something we should add to Flair. Do you have any publicly available datasets that we could use to guide to development of this feature? The datasets that we're looking at are text-only, so it would help to get a better idea of such features and how we need to support them!

**Comment by alejandrojcastaneira** [comment]
Hello @alanakbik, thank you for the quick reply! so far the publicly available datasets which combine text and multimodal features that I have seen are: [The DocBank Dataset](https://doc-analysis.github.io/docbank-page/ ) and [FUNSD](https://guillaumejaume.github.io/FUNSD/) datasets, which are used to form understanding of recipes and invoices.
