### ISSUE TITLE
[Question] Load MIT movie corpus with extra labels?

### ISSUE THREAD

**Issue by afi1289** [flairNLP/flair#2098]
Hello, 
I am trying to load simple MIT movie corpus for NER task. However, I the output contains labels which starts with **E** and **S** such as ``E-SONG``, ``S-ACTOR`` etc.. Although the original dataset contains data with ``BIO format``.
````
from flair.datasets import MIT_MOVIE_NER_SIMPLE
# load simple movie NER corpus
corpus_MIT = MIT_MOVIE_NER_SIMPLE()
print(corpus_MIT)
print(corpus_MIT.make_tag_dictionary('ner'))
````
The output:
````
Corpus: 8797 train + 978 dev + 2443 test sentences
Dictionary with 52 tags: <unk>, O, B-ACTOR, E-ACTOR, S-YEAR, S-TITLE, B-GENRE, I-GENRE, E-GENRE, B-DIRECTOR, E-DIRECTOR, S-GENRE, B-SONG, I-SONG, E-SONG, S-ACTOR, B-PLOT, I-PLOT, E-PLOT, S-PLOT, B-CHARACTER, E-CHARACTER, S-RATING, B-RATINGS_AVERAGE, E-RATINGS_AVERAGE, B-TITLE, E-TITLE, S-SONG, I-TITLE, B-RATING
````
Could someone explain this point to me please?
Thanks in advance!

**Comment by ambuje** [comment]
Hi, 

I am also getting extra tags in my dataset. Did you find a way how to tackle this thing?

Thank you
