### ISSUE TITLE
AttributeError: can't set attribute  in TextRegressor prediction

### ISSUE THREAD

**Issue by azizcu** [flairNLP/flair#2124]
from flair.models.text_regression_model import TextRegressor
from flair.data import Sentence
classifier = TextRegressor.load('/content/model/final-model.pt')
sentence = Sentence('I love my country')
predictions = classifier.predict(sentence)

2021-03-02 03:05:25,923 loading file /content/model/final-model.pt
2021-03-02 03:05:28,009 Using REGRESSION - experimental
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-26f0c6155998> in <module>()
      3 classifier = TextRegressor.load('/content/model/final-model.pt')
      4 sentence = Sentence('I love my country')
----> 5 predictions = classifier.predict(sentence)
      6 # results

/usr/local/lib/python3.7/dist-packages/flair/models/text_regression_model.py in predict(self, sentences, mini_batch_size, embedding_storage_mode)
     67 
     68                 for (sentence, score) in zip(batch, scores.tolist()):
---> 69                     sentence.labels = [Label(value=str(score[0]))]
     70 
     71                 # clearing token embeddings to save memory

AttributeError: can't set attribute

model is loaded perfectly but i can not make prediction from the model. please explain with a example how can i get the prediction?

**Comment by alanakbik** [comment]
Hello @azizcu this is fixed in master branch (see #2067) and is part of the upcoming release of Flair 0.8!
