### ISSUE TITLE
sentence.to_dict(tag_type='ner') doesn't convert entities labels to dictionary

### ISSUE THREAD

**Issue by morningcloud** [flairNLP/flair#2135]
Hi,
When calling [to_dict(tag_type='ner')](https://github.com/flairNLP/flair/blob/2fde64610244c7706cef68c882b9ce0e96261d2d/flair/data.py#L873) of [Sentence](https://github.com/flairNLP/flair/blob/2fde64610244c7706cef68c882b9ce0e96261d2d/flair/data.py#L529) object, the returned dictionary contains flair.data.Label datatype in the 'label' key for the entities instead of the dictionary representation of it to be able to get the tag type and confidence accordingly.

This can be resolved by changing the code [here](https://github.com/flairNLP/flair/blob/2fde64610244c7706cef68c882b9ce0e96261d2d/flair/data.py#L435) from `"labels": self.labels,` to `"labels": [l.to_dict() for l in self.labels],`

Following is an example of the output I am getting when calling sentence.to_dict(tag_type='ner'):

`{'text': 'George Washington went to Washington .', 'labels': [], 'entities': [{'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'labels': [PER (0.9968)]}, {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'labels': [LOC (0.9994)]}]}`

But I am expecting to get the following:

`{'text': 'George Washington went to Washington .', 'labels': [], 'entities': [{'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'labels': [{'value': 'PER', 'confidence': 0.9968]}, {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'labels': [{'value': 'LOC', 'confidence': 0.9994}]}]}`

**Comment by codechannel** [comment]
https://github.com/flairNLP/flair/issues/1820#issuecomment-678962971

**Comment by morningcloud** [comment]
Thanks for the reply. However, the answer suggested in #1820 seems like a workaround to me as we have to reiterate through the entities to call the .to_dict() of each label.

If you look at the [sentence.to_dict()](https://github.com/flairNLP/flair/blob/2fde64610244c7706cef68c882b9ce0e96261d2d/flair/data.py#L880) implementation is already doing the suggested fix to call `.to_dict()` of each label but this is at the sentence level. Therefore, I think doing the same for the entity level looks like a valid solution to be able to call `sentence.to_dict()` to get the dictionary output directly instead of looping through `sentence.get_spans()`.

**Comment by codechannel** [comment]
It is a work around. I agree with you, `to_dict()` should handle it. :)

**Comment by wiertz** [comment]
I can see why this may not be a top priority, but it is certainly an issue that should be closed imO...
