### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by GladiatorX** [flairNLP/flair#2136]
I am training a custom text classification model,

My csv file is stored in the format specified i.e (sep='\t', index = False, header = False)
data_fst/train.csv
data_fst/dev.csv
data_fst/test.csv

when I run this code
```
data_folder_fst = 'data_fst/'
corpus_fst: Corpus = ClassificationCorpus(data_folder_fst)
stats = corpus_fst.obtain_statistics()
print(stats)
```
I get
> {
>     "TRAIN": {},
>     "TEST": {},
>     "DEV": {}
> }

While when I fit the data I get

> Corpus: "Corpus: 0 train + 0 dev + 0 test sentences"
> ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by alanakbik** [comment]
The `ClassificationCorpus` is only for data stored in FastText format. If you have a CSV you need to use `CSVClassificationCorpus`.

See [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-a-text-classification-dataset) for more details.
