### ISSUE TITLE
The `multi-X-fast` embeddings appear to be missing

### ISSUE THREAD

**Issue by tadejmagajna** [flairNLP/flair#2140]
While reviewing [documentation](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md) I noticed that `multi-X-fast` should be one of the available `FlairEmbeddings `, but they appear to be missing.

For example, when running:
```python
from flair.embeddings import FlairEmbeddings
FlairEmbeddings("multi-forward-fast")
```
I get:
```
ValueError: The given model "multi-forward-fast" is not available or is not a valid path.
```
This happened both on 0.7 and 0.8 versions of Flair.

Given that [here](https://github.com/flairNLP/flair/blob/69d7c7d523b9111956d6fecd781d0b4654a4b13a/flair/embeddings/token.py#L412) a version called `multi-v0-forward-fast` does exist, but no other similar versions exist in Flair's [model index](https://flair.informatik.hu-berlin.de/resources/embeddings/flair/), I would presume the model dictionary key simply needs to be renamed in the code from `multi-v0-forward-fast` to `multi-forward-fast`. Unless there is a v1 version that was never uploaded.

Happy to open a PR for this.

**Comment by alanakbik** [comment]
Hello @tadejmagajna thanks for spotting this! You're right, we don't have a "v1" for the fast model. A PR with your fix would be very much appreciated!
