### ISSUE TITLE
Dutch ner 95,25 F1 score

### ISSUE THREAD

**Issue by schelv** [flairNLP/flair#2142]
The dutch ner score listed in the readme is very high.
How was it calculated? What script was used to make the predictions? and what script was used to compute the score?
The score listed in the paper is lower.

**Comment by alanakbik** [comment]
Hi @schelv thanks to the new model hub you can find the model and the script that was used to train it here: https://huggingface.co/flair/ner-dutch-large

If you scroll down to "Training: Script to train this model" you see a script that if you run in the newest version of Flair should reproduce this number. (There is a updated version of the arXiv paper with slightly different numbers currently under submission.)

**Comment by schelv** [comment]
I ran the script and the results are similar. 👍

What puzzles me is that the results are better than a model that uses the monolingual [RobBERT v2](https://huggingface.co/pdelobelle/robbert-v2-dutch-base) model.

Using  this model with the same training settings (except the nr of epochs) gives these results:
```
Results:
- F1-score (micro) 0.9257
- F1-score (macro) 0.9264
```

Why does the multilingual model work better than the monolingual one?
Is it just because of the size?

**Comment by alanakbik** [comment]
Very good question, @stefan-it and I ran similar experiments with monolingual models and also found that XLM-R works better. It might be because of the huge model size.

**Comment by schelv** [comment]
I've tested if the score difference is due to model size, by using the XLM-roberta-base model:
```
Results:
- F1-score (micro) 0.9278
- F1-score (macro) 0.9276
```
It appears the model size explains ~0.022 score difference. 

The XLM-roberta-base model results are still better than the results of the same settings 
RobBERT-base model:
```
Results:
- F1-score (micro) 0.9189
- F1-score (macro) 0.9185
```

That leaves 0.09 score difference.

In the MISC and ORG types the multilingual model is better.
The dutch model is better in recognizing PERSON's.
LOCATION there is not much difference.

The remaining factors that could explain the difference between the mono- and multilingual models could be:
- training methods (xlm training method?) & training data (the amount?)
- tokenization (e.g. size of token vocubulary, and data used to make the tokenizer)

I think the tokenization could explain the difference for the MISC and ORG types.
The RobBERT model has 40k tokens, the XLM models has 250k. Both types often contain somewhat rare tokens.
Retraining the RobBERT model with the XLM tokenizer (or vice versa) could show the effect.

But for now I have been distracted long enough 😂
Thanks for the help and keep up the good work!
