### ISSUE TITLE
Please do not use post releases to fix bugs

### ISSUE THREAD

**Issue by schelv** [flairNLP/flair#2143]
A while ago I encountered a strange error while building a docker container.

It was caused by a post release of flair causing a dependency version conflict.

Please do not use post releases to fix bugs. It is [bad](https://www.python.org/dev/peps/pep-0440/#post-releases), mmkay

**Comment by alanakbik** [comment]
Oha thanks for the pointer - didn't realize this!

**Comment by schelv** [comment]
No problem =)
