### ISSUE TITLE
Can we finetune a XLM-Roberta on a 2080Ti GPU?

### ISSUE THREAD

**Issue by huchinlp** [flairNLP/flair#2157]
I tried to reproduce the latest NER model with your [code](https://huggingface.co/flair/ner-english-large) on a 2080Ti GPU but got an error——CUDA out of memory.

I also tried to use FP16 by setting `use_amp=True`, but it didn't work.

Can you share the GPU memory usage during training?

**Comment by stefan-it** [comment]
Hi @huchinlp ,

unfortunately, 11GB of RAM are not enough for a fine-tuning with a XLM-R Large model.

We used a V100 with 16GB for our experiments.

**Comment by huchinlp** [comment]
Got it, thank you!

**Comment by nineTailsKurama** [comment]
Hey I am not able to fine-tune the model on an RTX 6000? Give me an OOM Cuda error
