### ISSUE TITLE
how i can get  only the values of the token without the word Token

### ISSUE THREAD

**Issue by nnadine25** [flairNLP/flair#2167]
hi,
i use flair for chunking and i need to use only the values of token but the result is <class 'flair.data.Token'> type like this:

Token: 1 Which
Token: 2 architect
Token: 3 of
Token: 4 Marine
Token: 5 Corps
Token: 6 Air
Token: 7 Station
Token: 8 Kaneohe
Token: 9 Bay
Token: 10 was
Token: 11 also
Token: 12 tenant
Token: 13 of
Token: 14 New
Token: 15 Sanno
Token: 16 hotel
Token: 17 ?
<class 'flair.data.Token'>

how i can  remove the "Token" word ? and get only teh values of the token ie ( Sanno for example)

**Comment by smatrix017** [comment]
Hi @nnadine25, Token class has field text  which can provide you the text of each token. 
e.g.: If your token variable name is token_var, you can get  the text by using token_var.text
