### ISSUE TITLE
Few Shots TARS for NER

### ISSUE THREAD

**Issue by ashokxnarang** [flairNLP/flair#2173]
The Few Shots TARS implementation for Text Classification is immensely useful and works quite well. 
This is a Feature Request for Few Shots TARS implementation for NER.

It should prove immensely useful for custom NER training and tagging in conditions of limited labelled dataset availability.

**Comment by alanakbik** [comment]
Hi @ashokxnarang yes in fact we have one that is almost ready to be added. We're currently running experiments with it and will add it as soon as it's ready.

**Comment by ashokxnarang** [comment]
Hi Alan,

This is wonderful news !! Will eagerly wait for the release.

Thanks a ton.

Regards
Ashok
