### ISSUE TITLE
The output layer in case of not using CRF

### ISSUE THREAD

**Issue by afi1289** [flairNLP/flair#2177]
Hello,
When using flair for NER, it is possible to use CRF layer as output layer. If CRF layer is not used, what is the output layer? Is softmax function will be used?
Thank you

**Comment by bfuchs-cloudflight** [comment]
Hello @afi1289 
softmax is used as last activation, no matter if it uses crf or not.
the crf is basically a linear layer + learned transitions, if you deactivate it, you will have only the linear layer left
