### ISSUE TITLE
Nested Named Entity Recognition with Flair

### ISSUE THREAD

**Issue by matirojasg** [flairNLP/flair#2183]
Sorry for the number of issues published today.

I have a general question.  There is a task in NLP called Nested NER that has advanced a lot of interest lately. https://paperswithcode.com/task/nested-named-entity-recognition.

The thing is that there are corpora such as GENIA and ACE2004/ACE2005 that have entities nested inside others as the following example: The bank of China (where **bank of China** is an Organization and **China** a Location). This means that a token can be associated with more than one tag.

There is some way to combine a Flair model to solve this task?

Thanks

**Comment by bfuchs-cloudflight** [comment]
Hello @matirojasg,
my approach to do Nested NER is to train multiple models - one per entity type - and then use the [Multitagger](https://github.com/flairNLP/flair/blob/master/flair/models/sequence_tagger_model.py#L1306) to have all models use shared embeddings.
Notice that each model has to have their own unique `tag_type` set.
