### ISSUE TITLE
Size of corpus different from when upgrading from 0.7 to 0.8.0.post1

### ISSUE THREAD

**Issue by albertovilla** [flairNLP/flair#2186]
**Describe the bug**
The number of values in training / test corpus is different when upgrading from 0.7 to 0.8.0.post1 version of Flair library.

**To Reproduce**
When using the version 0.7 of Flair library for training there were 14632 values in training corpus and 4314 values in the test one. However, after upgrading the version to 0.8.0.post1 using the same code 364 values are detected in training corpus and 827 in the testing one.

**Expected behavior**
I would expect the same number of values identified in both versions

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Redhat 7
 - Version [e.g. flair-0.3.2]: flair 0.7 / flair 0.8.0.post1

**Additional context**
Unfortunately,  I cannot share the train and test BIOES files I'm using but my best guess is that something has changed in the code which process these files and with the later version the data reader is assuming the file has "ended" before reaching the real end of the file.

I can share the code I'm using but I guess the problem is somewhere else because I'm executing the same code with the same data just the change of the library version is causing the issue.

```python
from pathlib import Path

from flair.data import Corpus
from flair.datasets import ColumnCorpus, DataLoader
from flair.models import SequenceTagger

# Folder where training and test files are located
data_folder = 'data'

# Filenames of the training and testing files
filepath_train = 'train.bioes'
filepath_test = 'test.bioes'

# Definition of columns for the ColumnCorpus
columns = {0: 'text', 1: 'ner'}

# Initializing the corpus
corpus: Corpus = ColumnCorpus(data_folder, 
                              columns, 
                              train_file = filepath_train, 
                              test_file = filepath_test)

# Make tag dictionary
tag_type = 'ner'
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)

print(f'We have {len(corpus.train)} values in training corpus and {len(corpus.test)} in testing corpus')

MODEL_FOLDER = 'resources/taggers/distilbert-l2-g-ner'

# load best model from the corresponding model folder
tagger: SequenceTagger = SequenceTagger.load(Path(MODEL_FOLDER) / 'best-model.pt')

# create DataLoader using corpus.test
validation_data_loader = DataLoader(corpus.test, batch_size=32)

# run evaluation procedure
result, score = tagger.evaluate(validation_data_loader.dataset, out_path=f"predictions.txt")

# print detailed results
print(result.detailed_results)
```

**Comment by albertovilla** [comment]
Hi again, I've been trying to debug the `ColumnDataset` read part, which it is in the constructor, and although I haven't yet identified what is the issue in the code I have identified when in the training corpus the file reading is stopped. In line 198 a new sentence is created and in the following line the the `sentence` variable is checked:

```python
while True:
      sentence = self._convert_lines_to_sentence(self._read_next_sentence(file))
      if not sentence: break
      sentence._previous_sentence = previous_sentence
``` 

In the training file the `not sentence` evaluates to `True` when I have the following text:

```
Inc. O

   
   
 
 
 
       
            
          O








Good O
morning O
All O
```
The sentence which starts with "Good" is not reached as the reading process stops before that. Maybe my file is not fully compliant with the BIOES format, it is the result of converting other types of file but it was working in a previous version of Flair. 

I guess the problem may be when in tthe function `_convert_lines_to_sentence` the length of the sentence is checked: 

`if len(sentence) > 0: return sentence`

**Comment by albertovilla** [comment]
I have solved the issue by making a couple of changes to the training and test corpus, in particular:

1) Removal of all lines which contained only whitespace followed by `O` for that I used a regular expression `r'^\s+O'`
2) Removal of more than one consecutive new lines

I don't know if this is a bug or not although the behaviour was different compared to previous version. In any case, from my side I consider it closed as with the two actions above I have managed to make it work as it was before.

**Comment by alanakbik** [comment]
Hello @albertovilla thanks for reporting this and sharing your solution! Data loading should be more robust at least to multiple new lines. Next time we look at the loaders, I'll try to fix this!
