### ISSUE TITLE
pip install error on Google colab

### ISSUE THREAD

**Issue by hongchangbao** [flairNLP/flair#2192]
**Describe the bug**
When I performed **pip install flair** in google colab, I got the following errors:

ERROR: torchvision 0.9.0+cu101 has requirement torch==1.8.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: torchtext 0.9.0 has requirement torch==1.8.0, but you'll have torch 1.7.1 which is incompatible.
ERROR: google-colab 1.0.0 has requirement requests~=2.23.0, but you'll have requests 2.25.1 which is incompatible.
ERROR: datascience 0.10.6 has requirement folium==0.2.1, but you'll have folium 0.8.3 which is incompatible.

**Comment by alanakbik** [comment]
Hello @hongchangbao this error happens because colab has some libraries installed that require a different torch version. But flair will function normally regardless, so you can ignore these error messages.

**Comment by hongchangbao** [comment]
Thanks!
