### ISSUE TITLE
How to use FLERT models?

### ISSUE THREAD

**Issue by b2m** [flairNLP/flair#2193]
Reading #2015 and #2116 I expected to be able to use the new FLERT models by using the `large` model types.

Copying from the model's [demo section](https://huggingface.co/flair/ner-english-large) and using the basic *Paris* example I expected *Paris* to get recognized as a person.

```python
from flair.data import Sentence
from flair.models import SequenceTagger

# load tagger
tagger = SequenceTagger.load("flair/ner-english-large")

# make example sentence
sentence = Sentence("I like Paris. She is nice.")

# predict NER tags
tagger.predict(sentence)

# print sentence
print(sentence)

# print predicted NER spans
print('The following NER tags are found:')
# iterate over entities and print
for entity in sentence.get_spans('ner'):
    print(entity)
```

But the output is:
> Sentence: "I love Paris . She is nice ."   [− Tokens: 8  − Token-Labels: "I love Paris &lt;S-LOC&gt; . She is nice ."]
> The following NER tags are found:
> Span [3]: "Paris"   [− Labels: LOC (1.0)]

I reproduced this using a fresh python 3.8 docker container with `flair=0.8.0.post1`.

As I expect that there is something wrong with my expectation or usage of flairNLP I categorized this issue as *question*.

So how can I use the new FLERT models with flairNLP?

Is there some configuration or parameter, expected input or different model to load?

Or is the uploaded model on HF not updated yet?

**Comment by alanakbik** [comment]
Hello @b2m you're using it correctly - for the release I trained another model and I guess here this example is not working. On average, the FLERT models (suffixed with "-large" on the HF hub) are much better than our previous ones, but they still make some mistakes.

**Comment by b2m** [comment]
Thank you @alanakbik for your comment.

I actually was using the example

> I like Paris. She is nice.

from your Keynote at Qurator 2021 and from the [FLERT paper](https://arxiv.org/abs/2011.06993).
Ok, in the paper the ambiguity is resolved in favor of Paris as the city... =)

Motivated by your feedback I was trying other phrases and was successfull e.g. with

> I love XYZ. We have been married for 20 years.

which resulted in _XYZ_ getting classified as _Person_.

Without the additional information in the second sentence _XYZ_ was classified as "nothing" with the [english model](https://huggingface.co/flair/ner-english-large) and as _Organisation_ with the [german model](https://huggingface.co/flair/ner-german-large) - both v 0.8.0).

It still is a bit unsatisfiying that the ambiguity of Paris is currently not resolved, as this is also the example you are using in your paper and therefore one of the first things anybody will try.

Hopefully this issue will help others stumpling upon similar problems.
