### ISSUE TITLE
Sentiment Value

### ISSUE THREAD

**Issue by atanasoff-yordan** [flairNLP/flair#2220]
Hi
I need to get the sentiment value for a text instead of the label, by sentiment value I mean <0 for negative, 0 for neutral and >0 for positive. Is this possible?

Also, can is it possible to add a neutral label type to the TextClassifier?

thx.

**Comment by MLiebald** [comment]
Hi, I have exactly the same question and would highly appreciate any insights on the topic.
Cheers,
Marius
