### ISSUE TITLE
Classification using Transformer Document Embeddings

### ISSUE THREAD

**Issue by nowhash** [flairNLP/flair#2251]
Hi all,

Can i pass Stack Embedding parameter along with other transformer model to TransformerDocumentEmbeddings?
For example.

```
label_dict = corpus.make_label_dictionary()
stacked_embeddings = StackedEmbeddings([
                                        WordEmbeddings('glove'),
                                        FlairEmbeddings('news-forward'),
                                        FlairEmbeddings('news-backward'),
                                        ELMoEmbeddings('original')
                                       ])
document_embeddings=TransformerDocumentEmbeddings('bert-base-uncased' ,stacked_embeddings )

classifier = TextClassifier(document_embeddings, label_dictionary=label_dict, multi_label=False)
```
In above code segment, i pass StackedEmbeddings with Bert Model into TransformerDocumentEmbeddings.
**Is TransformerDocumentEmbeddings use both to embed my documents?**

Thank You!

**Comment by wilmerhenao** [comment]
Did you figure out how to do this?

**Comment by nowhash** [comment]
> Did you figure out how to do this?
Actually, TransformerDocumentEmbeddings are trained for the transformer model only.
It's not possible to pass stacked embedding to them.
We can pass stacked embedding into document RNN Embedding or other embeddings.
