### ISSUE TITLE
How to deploy this trained model into AWS lambda function

### ISSUE THREAD

**Issue by varunraj14** [flairNLP/flair#2252]
Hi,
flair internally uses torch library which is of 2.2Gb and AWS lambda function has a limitation of 250mb. Is there a way to use this flair model as a service in aws lambda function ?

**Comment by BastianZim** [comment]
You can export torch to AWS EFS and then add that as an import path in your python function.

https://aws.amazon.com/blogs/compute/using-amazon-efs-for-aws-lambda-in-your-serverless-applications/

**Comment by jrpresta** [comment]
The EFS workaround worked for me.

I'm curious if you have an idea for running TARSClassifier.load in Lambda. The model loading eventually tries to cache some transformer work, and in doing so it tries to write to the root directory.

**Comment by BastianZim** [comment]
Not really, unfortunately. Maybe there's an env variable that can specify the location? But that's probably better answered by a maintainer.
