### ISSUE TITLE
Make some dependencies optional

### ISSUE THREAD

**Issue by schelv** [flairNLP/flair#2265]
**Is your enhancement request related to a problem? Please describe.**
I've been asked to reduce the size of a docker image containing flair.
Some of the dependencies of flair take up quite some space.

One example is the janome package, which takes up 176M of space in the final image. 

**Describe the solution you'd like**
Would it be possible to group dependencies and then make this group of dependencies optional?

I think it should be possible with something like [this](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies).

**Comment by schelv** [comment]
I think its still relevant

**Comment by schelv** [comment]
Why did it close the issue?

**Comment by alanakbik** [comment]
Not sure, I guess stalebot closes automatically even if someone comments. I'll reopen to keep this issue on the list.
