### ISSUE TITLE
Unable to Load models

### ISSUE THREAD

**Issue by jaypal17** [flairNLP/flair#2270]
**Describe the bug**
I am trying to run a simple example just to test out however I cannot load the model. The error I see is:
requests.exceptions.SSLError: HTTPSConnectionPool(host='nlp.informatik.hu-berlin.de', port=443): Max retries exceeded with url: /resources/models/sentiment-curated-distilbert/sentiment-en-mix-distillbert_4.pt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

**To Reproduce**
My code:
from flair.models import TextClassifier
from flair.data import Sentence
classifier = TextClassifier.load('en-sentiment')
sentence = Sentence('Flair is pretty neat!')
classifier.predict(sentence)

print('Sentence above is: ', sentence.labels)

**Expected behavior**
A positive or negative score

**Environment (please complete the following information):**
Windows 10
Flair 0.8
Python 3.9.5

**Additional context**
I saw in similar issues you can download the models directly however, the links I tried below do not work. Where can I go to download the models?
https://alan-nlp.s3.eu-central-1.amazonaws.com/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt

**Comment by alexisbenichoux** [comment]
just a wild guess; pip install openssl ?

**Comment by Aatlantise** [comment]
I have the same issue, and `apt-get install openssl` didn't work. The models can be downloaded at "https://nlp.informatik.hu-berlin.de/resources/models" though.

**Comment by Aatlantise** [comment]
In my case, it looks like a firewall is blocking the connection. I am able to circumvent the problem by manually downloading, using `wget https://website.com/path/to/file/location --no-check-certificate` at `/root/.flair/datasets` or `/root/.flair/embeddings`.

The file locations are specified in your error message, in @jaypal17 's case: https://nlp.informatik.hu-berlin.de/resources/models/sentiment-curated-distilbert/sentiment-en-mix-distillbert_4.pt

**Comment by franciskinyuru** [comment]
I am also experincing this error even after installing the openssl library.

I am tring to send a post request which must pass via proxy.

This is the error i am getting
Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)'))
