### ISSUE TITLE
Amazon bucket seems to be down

### ISSUE THREAD

**Issue by priyankmodiPM** [flairNLP/flair#2283]
I'm unable to access embeddings through flair. The code has been working since the last two months but suddenly started throwing errors.

OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/glove.gensim.vectors.npy with status code 404

To Reproduce

from flair.embeddings import WordEmbeddings
glove_embedding = WordEmbeddings('glove')

I would appreciate your help,
Thank you !

**Comment by alanakbik** [comment]
Hi @pranaychandekar we don't use the amazon buckets anymore. Update to the newest Flair version, then it should work!
