### ISSUE TITLE
Batch inference

### ISSUE THREAD

**Issue by gevezex** [flairNLP/flair#2285]
Is there a way to give documents in batches instead of serving it document by document as on the main page example (example with sentence="...").

**Comment by bfuchs-cloudflight** [comment]
just provide a list of sentences: `tagger.predict(sentences)`

**Comment by zixiliuUSC** [comment]
![image](https://user-images.githubusercontent.com/49173327/123240567-fdda4580-d512-11eb-9605-e900d32fc831.png)
batch inference is even slower than inference one by one. In my case, inferencing per sentence in a batch cost only about 58 min
