### ISSUE TITLE
Obtaining all labels (not only predicted one) when using text classification

### ISSUE THREAD

**Issue by ignacioct** [flairNLP/flair#2287]
Hi! I would like to know if there is a way to obtain all labels and their predicted probability when using Flair to do sentyment analysis or offensive language detection. Im running this script:

```python

import rubrix as rb

from flair.models import TextClassifier
from flair.data import Sentence

# Load our pre-trained TARS model for English
classifier = TextClassifier.load('de-offensive-language')

sentence = Sentence('Du erzählst immer Quatsch.') #something like: "You are always narrating silliness."

# Make the prediction
classifier.predict(sentence)

# Print the prediction
print('Sentence above is: ', sentence.labels)

```

Which returns `Sentence above is:  [OTHER (0.7237)]`. I would like to know if there is a way to obtain the whole list of possible labels and the probability that the model calculated, even though they were not the predicted label. Thank you!

**Comment by yosipk** [comment]
Set argument `multi_class_prob=True` in classifier's `predict` method call:
```
classifier.predict(sentence, multi_class_prob=True)
```

**Comment by ignacioct** [comment]
> Set argument `multi_class_prob=True` in classifier's `predict` method call:
> 
> ```python
> classifier.predict(sentence, multi_class_prob=True)
> ```

Thank you so much, works like a charm!
