### ISSUE TITLE
Spanish clinical flair embeddings

### ISSUE THREAD

**Issue by matirojasg** [flairNLP/flair#2292]
Hi, in the research group where I work ([http://pln.cmm.uchile.cl/grav/en](http://pln.cmm.uchile.cl/grav/en)), we have trained flair embeddings in Spanish in the clinical context. 

We have fine-tuned an existing LM (es-forward/es-backward provided by @iamyihwa), and we have trained (>1 week) on a Chilean clinical dataset (created by the same group) with around 50 million words. We have good perplexity values, and when generating random text, it generates text close to natural language.

We would like to know the steps to follow to upload these models to the site. Do we have to test it on the NER task for some medical dataset in Spanish and show you the results?

To our knowledge, there is no flair embedding model in Spanish in the clinical context :)

If you want to know more about what this corpus is about, you can see the paper published last year: [https://www.aclweb.org/anthology/2020.clinicalnlp-1.32/](https://www.aclweb.org/anthology/2020.clinicalnlp-1.32/)

**Comment by alanakbik** [comment]
Hello @matirojasg thanks for offering to add the models, people would surely find this useful! 

The standard way would be to put the model on a server and do a pull request to add the auto-downloading functionality to the FlairEmbeddings class. If you like, I can put your models on our faculty server and also do the pull request (this is how we've been mostly doing it). Alternatively you can do the PR and/or put the models on your own server. Both great for me!

**Comment by matirojasg** [comment]
Thank you for the quick response.

"If you want, I can put your models on our faculty server and also do the pull request (that's how we've been doing it most of the time)." I prefer this option.

Do I share the files with you by drive? Which files do you need exactly?

**Comment by alanakbik** [comment]
Hello @matirojasg yes if you send me a mail with a link to a drive folder where models are, I can put them on our server! Thanks again!

**Comment by matirojasg** [comment]
Hello, here is the link to the clinical models in Spanish, let me know if any file is missing or you can't see the drive.

https://drive.google.com/drive/folders/1M1b5FzZqEebTF7B2l58GQvciF4SXP5dT?usp=sharing

Thanks!

Sent with a Spark

**Comment by matirojasg** [comment]
Here is the link to the clinical models in Spanish, let me know if any file is missing or you can't see the drive.

[https://drive.google.com/drive/folders/1M1b5FzZqEebTF7B2l58GQvciF4SXP5dT?usp=sharing](https://drive.google.com/drive/folders/1M1b5FzZqEebTF7B2l58GQvciF4SXP5dT?usp=sharing)

Thanks!

**Comment by alanakbik** [comment]
Hi @matirojasg I put then on our server: https://flair.informatik.hu-berlin.de/resources/embeddings/flair/ 

Would you like to do the PR for integration into Flair, or should I?

**Comment by matirojasg** [comment]
Could you do it, please? Thank you :)

**Comment by codemaster-22** [comment]
Hi @matirojasg  can you please suggest me size of Corpus for a language model 'news-forward' fine tuned on english tweets , I am currently thinking to follow 50 million words as mentioned by you. But will it be fine? please suggest me
