### ISSUE TITLE
Loading fine-tuned bert model

### ISSUE THREAD

**Issue by Ivowings** [flairNLP/flair#2301]
Hi All,

I just fine-tuned a bert model using the huggingface platform(https://huggingface.co/Ivo/emscad-skill-extraction/tree/main). I want to load this model into flair. However, when I try to load the model using: embedding = TransformerWordEmbeddings('Ivo/emscad-skill-extraction') i get an error saying that the weights cannot be loaded. How can i fix this? 

Thank you in advance.

**Comment by Ivowings** [comment]
I found the solution. I forgot to add the pytorch version of the model in the repo.

**Comment by alanakbik** [comment]
Thanks for sharing the solution!
