### ISSUE TITLE
TransformerWordEmbeddings - OverflowError: int too big to convert

### ISSUE THREAD

**Issue by mahak13** [flairNLP/flair#2305]
**The Issue**
When I try to embed any sentence using the BERT model "allenai/scibert_scivocab_uncased", I get this error where it shows Overflow Error: int too big to convert. I did some googling and ended up here #2181 . See below for steps to reproduce

**To Reproduce**
```
from flair.data import Sentence
from flair.embeddings import TransformerWordEmbeddings

embedding = TransformerWordEmbeddings("allenai/scibert_scivocab_uncased")
s = Sentence('This is a sentence')

embedding.embed(s)
```

The error:
`OverflowError: int too big to convert`

**Question**
I understand where the problem lies. When I use the normal huggingface library to check model_max_length, I get this.
```
>>> from transformers import AutoTokenizer
>>> tokenizer = AutoTokenizer.from_pretrained("allenai/scibert_scivocab_uncased")
>>> tokenizer.model_max_length
1000000000000000019884624838656

>>> tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
>>> tokenizer.model_max_length
512
```

Here the model_max_length is not set in the pretained model that I am using but if we use huggingface we can manually set it using 
``` tokenizer.model_max_length = 512 ``` 
but I was not able to find any way to manually set this attribute using flair's TransformerWordEmbeddings class. Is there any workaround to this? Any method to manually set the model_max_length in flair?

**Environment (please complete the following information):**
 - OS: Windows
 - Version:  0.8.0.post1

**Comment by dheerajiiitv** [comment]
@mahak13  This was also happening when i put the model path also for example - 
`from flair.data import Sentence
from flair.embeddings import TransformerWordEmbeddings

embedding = TransformerWordEmbeddings("path/to/bert-uncased-model")
s = Sentence('This is a sentence')

embedding.embed(s)`. ## int overflow error max_length is 1000000000000000019884624838656

**Comment by mcpavan** [comment]
It was happening to me either.

I turns out that the problem is in the class TransformerWordEmbeddings. Everything works fine when using the AutoTokenizer and AutoModel from transformers directly.

The solution I found is to change the value of these two variables inside the object instantiated from TransformerWordEmbeddings: max_subtokens_sequence_length and stride.

This way I didnt need to download anything separately.

```
#import
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence

#init embedding
bertimbau = "neuralmind/bert-base-portuguese-cased"
embedding = TransformerWordEmbeddings(bertimbau)

# repair value for max_subtokens_sequence_length and stride
embedding.max_subtokens_sequence_length = 512

# if allow_long_sentences parameter is True then stride should be 512 // 2 else just set to 0 (maintain the original class behavior)
embedding.stride = 512 // 2 #or 0

pt_sentence = "A grama é verde ."
sentence = Sentence(pt_sentence)

#embed words in sentence
sentence_emb = embedding.embed(sentence)
```
