### ISSUE TITLE
can't load transformer models

### ISSUE THREAD

**Issue by alilotfy** [flairNLP/flair#2310]
**Describe the bug**
model in this link can't be loaded 
https://huggingface.co/aubmindlab/bert-base-arabert

**To Reproduce**
put  >>>aubmindlab/bert-large-arabertv01>>> , for example, in the stacked embedding array

**Expected behavior**
It is worth mentioning that I used theses models before and they worked fine. For now, only aubmindlab/bert-base-arabertv01
works and the rest gives the following error:

 Can't load config for 'bert-large-arabertv02'. Make sure that:

- 'bert-large-arabertv02' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'bert-large-arabertv02' is the correct path to a directory containing a config.json file

**Comment by HallerPatrick** [comment]
Hey @alilotfy,

I think the error message is correct, by saying that the model is not listed by HugginFace

Here are all models:




Model | HuggingFace Model Name | Size (MB/Params) | Pre-Segmentation | DataSet
-- | -- | -- | -- | --
AraBERTv0.2-base | bert-base-arabertv02 | 543MB / 136M | No | 200M / 77GB / 8.6B
AraBERTv0.2-large | bert-large-arabertv02 | 1.38G 371M | No | 200M / 77GB / 8.6B
AraBERTv2-base | bert-base-arabertv2 | 543MB 136M | Yes | 200M / 77GB / 8.6B
AraBERTv2-large | bert-large-arabertv2 | 1.38G 371M | Yes | 200M / 77GB / 8.6B
AraBERTv0.1-base | bert-base-arabertv01 | 543MB 136M | No | 77M / 23GB / 2.7B
AraBERTv1-base | bert-base-arabert | 543MB 136M | Yes | 77M / 23GB / 2.7B

So you probably either mean `aubmindlab/bert-base-arabertv01` or `aubmindlab/bert-large-arabertv2` 😁

Hope this helps!

**Comment by alilotfy** [comment]
@HallerPatrick Thank you for your reply

I wrote the model name wrong in the issue above. anyways, This still doesn't work. the problem still holds

After using the model name you wrote above : aubmindlab/bert-large-arabertv2 ,
this error is raised 


################################################################################
OSError: Can't load config for 'aubmindlab/bert-large-arabertv2'. Make sure that:

- 'aubmindlab/bert-large-arabertv2' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'aubmindlab/bert-large-arabertv2' is the correct path to a directory containing a config.json file
################################################################################


Try this model it will not load 

only  aubmindlab/bert-base-arabertv01 works

**Comment by HallerPatrick** [comment]
This is weird, because for me it is working fine (its loading the embeddings).

My code:
```python
from flair.embeddings import TransformerWordEmbeddings

embedding = TransformerWordEmbeddings("aubmindlab/bert-large-arabertv2")
```

Is this different from yours @alilotfy ?

**Comment by dheerajiiitv** [comment]
@alilotfy I think this might be due to some network error. For example, in my case script was not able to download model due to some VPN error so i have to download the model manually and put the path of model files.
