### ISSUE TITLE
Slovene PoS tagger

### ISSUE THREAD

**Issue by tadejmagajna** [flairNLP/flair#2313]
I recently trained a Slovene PoS tagger using a stack of forward, backward and  FastText slovene embeddings that yielded decent results (F1-Score: 94,96).

I uploaded the model to Huggung Face (seems like the cleanest way to contribute at the moment) where its usage and reproducibility steps are documented in more detail. The model is available as `tadejmagajna/flair-sl-pos` at: https://huggingface.co/tadejmagajna/flair-sl-pos

I'm wondering if you'd want to add the model to Flair's set of supported models.
If yes, we'd probably want to move the model from `tadejmagajna/flair-sl-pos` -> to `flair/sl-pos`. But I'm not a member of the Flair org on Hugging Face so I can't do that myself at the moment.

There's definitely room for improvement and I'm sure I'd be able optimise the model a bit more with hyperparameter optimisation. But the score that I got now if actually pretty decent and better than anything you'll find elsewhere.

Once the model is in the right org, I'm happy to open a PR and update [the `huggingface_model_map` ](https://github.com/flairNLP/flair/blob/d5dd0a2818418fb5afac2c01f1e9d1cf5767a51f/flair/models/sequence_tagger_model.py#L1022) and all relevant READMEs.

**Comment by alanakbik** [comment]
Hello @tadejmagajna thanks a lot for contributing the model! 

Probably the easiest would be to update the model map so that "sl-pos" points to your repo. This way if you train a better model you can directly update it in the hub. So moving it to the flair repo is not necessary I would say. What do you think?
