### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by yananchen1989** [flairNLP/flair#2315]
flair version: 0.8.0.post1
torch: 1.7.1

when I try to load the ner model as below,
`tagger = SequenceTagger.load("ner-large")`

There comes the error:

> ----> 1 tagger = SequenceTagger.load("ner-large")
> 
> /usr/local/lib/python3.6/dist-packages/flair/nn.py in load(cls, model)
>      86             # see https://github.com/zalandoresearch/flair/issues/351
>      87             f = file_utils.load_big_file(str(model_file))
> ---> 88             state = torch.load(f, map_location='cpu')
>      89
>      90         model = cls._init_model_with_state_dict(state)
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
>     592                     opened_file.seek(orig_position)
>     593                     return torch.jit.load(opened_file)
> --> 594                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>     595         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>     596
> 
> /usr/local/lib/python3.6/dist-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
>     851     unpickler = pickle_module.Unpickler(data_file, **pickle_load_args)
>     852     unpickler.persistent_load = persistent_load
> --> 853     result = unpickler.load()
>     854
>     855     torch._utils._validate_loaded_sparse_tensors()
> 
> /usr/local/lib/python3.6/dist-packages/flair/embeddings/token.py in __setstate__(self, d)
>    1295
>    1296                 config=loaded_config,
> -> 1297                 state_dict=d["model_state_dict"],
>    1298             )
>    1299
> 
> /usr/local/lib/python3.6/dist-packages/flair/embeddings/token.py in __init__(self, model, layers, subtoken_pooling, layer_mean, fine_tune, allow_long_sentences, use_context, memory_effective_training, respect_document_boundaries, context_dropout, **kwargs)
>     854         # when initializing, embeddings are in eval mode by default
>     855         self.model.eval()
> --> 856         self.model.to(flair.device)
>     857
>     858         # embedding parameters
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in to(self, *args, **kwargs)
>     610             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
>     611
> --> 612         return self._apply(convert)
>     613
>     614     def register_backward_hook(
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
>     357     def _apply(self, fn):
>     358         for module in self.children():
> --> 359             module._apply(fn)
>     360
>     361         def compute_should_use_set_data(tensor, tensor_applied):
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
>     357     def _apply(self, fn):
>     358         for module in self.children():
> --> 359             module._apply(fn)
>     360
>     361         def compute_should_use_set_data(tensor, tensor_applied):
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _apply(self, fn)
>     379                 # `with torch.no_grad():`
>     380                 with torch.no_grad():
> --> 381                     param_applied = fn(param)
>     382                 should_use_set_data = compute_should_use_set_data(param, param_applied)
>     383                 if should_use_set_data:
> 
> /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in convert(t)
>     608             if convert_to_format is not None and t.dim() == 4:
>     609                 return t.to(device, dtype if t.is_floating_point() else None, non_blocking, memory_format=convert_to_format)
> --> 610             return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
>     611
>     612         return self._apply(convert)
> 
> RuntimeError: CUDA error: device-side assert triggered

**Comment by HallerPatrick** [comment]
This seems to be a known problem:
- https://stackoverflow.com/questions/51691563/cuda-runtime-error-59-device-side-assert-triggered
- https://github.com/huggingface/transformers/issues/5611#issuecomment-666231984

This is more or less a Pytorch/CUDA problem. Maybe run your code with `CUDA_LAUNCH_BLOCKING=1` will give you a better stack trace, like:

`CUDA_LAUNCH_BLOCKING=1 python script.py`

Hope this helps for now.
