### ISSUE TITLE
Is HunFlair NER inference slower on GPU compared to CPU?

### ISSUE THREAD

**Issue by dummynov1** [flairNLP/flair#2321]
Is Hunflair inference optimized for GPU ?, since while tagging Diseases ('hunflair-disease model') using "flair.device = torch.device('cpu')"  runs twice as as fast as "flair.device = torch.device('cuda:0') "

Using the following code:

#### load biomedical tagger
tagger = MultiTagger.load("hunflair-disease")
#### tag sentence
tagger.predict(sentence)

**Comment by mariosaenger** [comment]
Hi @dummynov1 ,

unfortunately I can't reproduce the issue you mentioned. In my environment running the following experiment with GPU support (i.e. by setting CUDA_VISIBLE_DEVICES=0) is 100 times faster than without  (i.e. by setting CUDA_VISIBLE_DEVICES=). 

```python

import time
from datasets import CELL_FINDER
from models import MultiTagger

tagger = MultiTagger.load("hunflair-disease")
corpus = CELL_FINDER()

print("Start predicting")
start = time.process_time()

result = tagger.predict(corpus.train)

duration = time.process_time() - start
print("Finished prediction after: " + str(duration))
``` 
For the experiment I used a NVIDIA Tesla T4 card. Can you elaborate a bit more about your hardware environment and how you run prediction?

**Comment by dummynov1** [comment]
> Hi @dummynov1 ,
> 
> unfortunately I can't reproduce the issue you mentioned. In my environment running the following experiment with GPU support (i.e. by setting CUDA_VISIBLE_DEVICES=0) is 100 times faster than without (i.e. by setting CUDA_VISIBLE_DEVICES=).
> 
> ```python
> import time
> from datasets import CELL_FINDER
> from models import MultiTagger
> 
> tagger = MultiTagger.load("hunflair-disease")
> corpus = CELL_FINDER()
> 
> print("Start predicting")
> start = time.process_time()
> 
> result = tagger.predict(corpus.train)
> 
> duration = time.process_time() - start
> print("Finished prediction after: " + str(duration))
> ```
> 
> For the experiment I used a NVIDIA Tesla T4 card. Can you elaborate a bit more about your hardware environment and how you run prediction?

Thanks for the response. So i'm using AWS instance (type P3.16x - large) which has 8 x  Tesla V100-SXM2-16GB GPU

I have a flair-ner-model loaded in GPU(0), and i'm trying to load the Hunflair model as well to the same device(0).

Could you let me know how should i use "CUDA_VISIBLE_DEVICES=0" within Hunflair when i'm using Multi-GPU system loaded with multiple models? My prediction code is as below:

#### Import statements
import flair, torch
flair.device = torch.device('cuda:2') 
from flair.data import Sentence
from flair.models import MultiTagger
from flair.tokenization import SciSpacyTokenizer
file_path= "/models/hunflair-disease-full-v1.0.pt"
tagger = MultiTagger.load(file_path)

text = "He was suffering from Cancer"    # example text

diseases = [ ]
sentence = Sentence(text,use_tokenizer=SciSpacyTokenizer())
tagger.predict(sentence)
for entity in sentence.get_spans():
    diseases.append(entity.text)

**Comment by mariosaenger** [comment]
Seems sound to me. How many documents / sentences do you process in your pipeline? Do you build the sentence objects for all of your sentences / documents before running prediction or in-between?

**Comment by dummynov1** [comment]
> Seems sound to me. How many documents / sentences do you process in your pipeline? Do you build the sentence objects for all of your sentences / documents before running prediction or in-between? And can you provide runtime figures for running with and without GPUs?

1. So i have a dataframe with a column containing Medical text , with each text item/cell as a single sentence of max length 20 words. So my above Sentence(for tokenization) and Tagger (for prediction) code is running in a loop for each of the text element/sentence.

2. On the runtime aspect, i'm surprised that even to extract the Disease 'Cancer' from the text :-"He was suffering from Cancer", the code takes 3-4 seconds on CPU and 5-8 seconds on GPU (by enabling "flair.device = torch.device('cuda:2') ). I rechecked the same code on Google Collab(GPU enabled), still took 3-6 seconds on Flair.cuda device

While my "flair-ner-english" model on the same GPU(cuda:2) works extremely fast compared to CPU.

Is this normal, or is the Tokenizer function `Sentence(text,use_tokenizer=SciSpacyTokenizer())` the culprit here? Do i really need to use the Sentence with Scispacy tokenizer function for text length upto 25 words?

**Comment by mariosaenger** [comment]
Hi @dummynov1 ,

thanks for the info. You can also use the default (Whitespace) tokenizer. If you only want to extract diseases, this should not have a major impact on the prediction quality (I would guess). For entities of other types, such as chemicals or proteins, it is much more important to have tokenizer's trained on scientific or biomedical texts. Accordingly, just take a look at the predictions (with the default tokenizer) and see if there are any major problems.

**Comment by dummynov1** [comment]
> Hi @dummynov1 ,
> 
> thanks for the info. You can also use the default (Whitespace) tokenizer. If you only want to extract diseases, this should not have a major impact on the prediction quality (I would guess). For entities of other types, such as chemicals or proteins, it is much more important to have tokenizer's trained on scientific or biomedical texts. Accordingly, just take a look at the predictions (with the default tokenizer) and see if there are any major problems.

Yes. with default tokenizer, it processes the text way faster, but there are many Multi-word Disease names getting missed or split incorrectly. So, I still have to use `SciSpacyTokenizer` and live with with slow processing times for now, until we have this optimized. :-(

**Comment by mariosaenger** [comment]
I would assume that the long runtime comes from loading the SciSpacy models. Do you cache the tokenizer? For example:` 
```python
scispacy_tok = SciSpacyTokenizer()

sentences = [Sentence(text, use_tokenizer=scispacy_tok) for text in data_frame["text_col"]]

tagger = MultiTagger.load("hunflair-disease")
tagger.predict(sentences)
```

**Comment by dummynov1** [comment]
> I would assume that the long runtime comes from loading the SciSpacy models. Do you cache the tokenizer? For example:`
> 
> ```python
> scispacy_tok = SciSpacyTokenizer()
> 
> sentences = [Sentence(text, use_tokenizer=scispacy_tok) for text in data_frame["text_col"]]
> 
> tagger = MultiTagger.load("hunflair-disease")
> tagger.predict(sentences)
> ```

That solved the problem. I was not caching/storing the `SciSpacyTokenizer()`to a variable, instead i was just following the Hunflair code as mentioned in the Readme : `sentence = Sentence(text,use_tokenizer=SciSpacyTokenizer())`. Didn't know we could cache the SciSpacyTokenizer . I think it would be great to add this in the Hunflair Readme.

Thanks @mariosaenger for the resolution. Now all Disease extraction is done instantly. Will try running in a List Comprehension for the entire column of Medical Text and see how significantly the overall  execution time will reduce.
