### ISSUE TITLE
How to distill Flair model

### ISSUE THREAD

**Issue by codemaster-22** [flairNLP/flair#2332]
Hey @stefan-it can you please tell how can I distill flair Language model , I want to distill news-forward model ? Any ideas or suggestions to get started ?

**Comment by stefan-it** [comment]
Hi @codemaster-22 ,

unfortunately, I'm not aware of any implementation -> for distilling flair embeddings.

But I've seen a implementation of distillation during downstream task training, e.g.:

https://github.com/Alibaba-NLP/ACE/blob/main/flair/trainers/distillation_trainer.py

but I'm not sure, if the implementation is working 😅

Maybe you can adjust training details (such as loss function) from the DistilBERT implementation:

https://github.com/huggingface/transformers/tree/master/examples/research_projects/distillation
