### ISSUE TITLE
using Bilstm for NER

### ISSUE THREAD

**Issue by Phd-Student2018** [flairNLP/flair#2336]
Hi
My question:
 With NER task, when using RNN=[true] that's mean using BiLSTM? If yes what is the difference when using rnn_type="LSTM" ?
Thanks

**Comment by philfuchs** [comment]
Are you using the SequenceTagger? If so, this code section seems like it answers your question: https://github.com/flairNLP/flair/blob/master/flair/models/sequence_tagger_model.py#L176

**Comment by alanakbik** [comment]
Closing, but feel free to reopen if you have more questions.
