### ISSUE TITLE
please update flair for torch 1.8

### ISSUE THREAD

**Issue by ksmultiacc3** [flairNLP/flair#2339]
please update flair for torch 1.8

**Comment by muellerzr** [comment]
In the interim I have my own fork here of master using torch 1.8. So far I haven't seen any breaking changes, at least in my use cases: https://github.com/muellerzr/flair

You can pip install via `pip install git+https://github.com/muellerzr/flair`

**Comment by alanakbik** [comment]
Hi all, was just updated to 1.9 in master branch!

**Comment by muellerzr** [comment]
Thanks so much!
