### ISSUE TITLE
Open Positions for PhD Candidates at HU Berlin

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#2342]
Hi all, 

my group at HU-Berlin is now growing quickly, and we're looking for persons interested in doing NLP/ML research and pursuing a PhD! The first is open now, in a joint project with NLP-startup [deepset](https://www.deepset.ai/) who do lots of open source ML work. 

![deepsetwanted-01](https://user-images.githubusercontent.com/18665324/126036970-a4551d01-c48a-4727-8266-1460d9753053.png)

So if you:
- love NLP / deep learning research
- enjoy contributing to open source ML projects like Flair and [Haystack](https://github.com/deepset-ai/haystack), or creating your own
- do serious coding in Python
- have completed a master's degree in CS (M.Sc.)

Consider joining us at HU-Berlin! Application deadline is 23.07. More information on this position in the [job ad here](https://www.personalabteilung.hu-berlin.de/de/stellenausschreibungen/wissenschaftliche-r-mitarbeiter-in-m-w-d-mit-vorauss-vollzeit-e-13-tv-l-hu-drittmittelfinanzierung-befristet-bis-30-06-2023) (in German). 

Cheers, 
Alan

**Comment by myrainbowandsky** [comment]
Hi, do you have any postdocs from 23.07?

**Comment by sefeoglu** [comment]
Hello, 
Is the phd position still available for self-funded candidates as well?
Thanks 😊

**Comment by alanakbik** [comment]
Hi @myrainbowandsky no open PostDoc positions currently, but perhaps next year there may be some. 

Hi @sefeoglu best shoot me a mail to discuss. We have more positions like this one coming very soon.

**Comment by NilakshanKunananthaseelan** [comment]
@alanakbik Is this position still available?

**Comment by alanakbik** [comment]
Deadline is passed but more are coming (I will post new openings here)

**Comment by NilakshanKunananthaseelan** [comment]
Thanks, @alanakbik. Looking forward!

**Comment by alanakbik** [comment]
Three new positions are coming up, see #2446!
