### ISSUE TITLE
Unable to read in TARS model on AWS Lambda

### ISSUE THREAD

**Issue by jrpresta** [flairNLP/flair#2344]
**Describe the bug**

Using the `from flair.models.text_classification_model import TARSClassifier` sub-package:

One of my DS interns built a great Flair model, and we'd like to put it into use. Our runtime system works well with AWS Lambda, so I've been working to get her work onto a Lambda. When calling `TARSClassifier.load()` on the model's file path, I'm met with the following error: `OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'`

In the Lambda, I only have write permission to the `/tmp` directory. From what I can tell, there is no way to specify where the model is being cached, and so the model eventually calls `os.makedir` in a directory where it doesn't have access.

I'll post the entire error log at the bottom of this.

**To Reproduce**
Call `TARSClassifier.load()` on a pre-trained model in AWS Lambda.

**Expected behavior**
I would like the API to have the ability to specify the directory, so that the model values can be cached in the `/tmp` directory.

**Screenshots**
![Screen Shot 2021-07-19 at 5 40 55 PM](https://user-images.githubusercontent.com/40158959/126245006-f685009f-553c-40b1-aefe-f4883b36532c.png)

**Environment (please complete the following information):**
 - AWS Lambda (Ubuntu?)
 - Version 0.8.0.post1

**Additional context**
I haven't 100% ruled out that the model is unexpectedly downloading some model file from the internet. However, the model is all pre-trained by my intern and should be all that is needed to set up inference.

**Comment by kishaloyhalder** [comment]
Hi @jrpresta 

Thanks for posting the issue!

The main issue here is flair serializes only the weight parameters inside the `.pt` file. When we try to load the model back, it looks for some additional files (such as vocabulary etc) in the default cache location first, if not found it tries to download them from the internet and saves them in the cache. By default the cache is `~/.cache/huggingface/transformers/` which does not have write permission in your case probably.

I would suggest to try the following in your AWS lambda code.

```
import os

# Let's change the default cache location to somewhere with write permission enabled
os.environ['TRANSFORMERS_CACHE'] = '/tmp/huggingface/transformers/' 

# then do the usual stuff
from flair.models.text_classification_model import TARSClassifier

tars = TARSClassifier.load('path/to/pretrained/model.pt')
```

Hope this helps!

with regards,
Kishaloy

**Comment by jrpresta** [comment]
This did the trick!!

I did try setting the TRANFORMERS_CACHE env variable at first, let me document was I was doing incorrectly.

I was setting the os.env variable after importing Flair, but once I set the variables before import Flair, things worked! I appreciate your wisdom, thank you!
