### ISSUE TITLE
How to save and load finetuned TransformerWordEmbeddings for a downstream task?

### ISSUE THREAD

**Issue by ritwikmishra** [flairNLP/flair#2345]
[The page](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md#fine-tuneable-or-not) mentions a way to fine-tune the TransformerWordEmbeddings. But how to save it?

I suppose one might say to use `torch.save()` and `torch.load()` method on the `embedding` object. But then the `fine_tune` parameter will be set to `True` always. Isn't it?

**Comment by whoisjones** [comment]
Hi @ritwikmishra you can save transformer embeddings according to the [huggingface]((https://huggingface.co/transformers/main_classes/model.html)) documentation, look for search_pretrained. But your way also works.

Regarding your question: You can adjust the instance variable `fine_tune` any time you want, so you can also adjust it to `false` later.
