### ISSUE TITLE
How state of the Art model can be so wrong ?

### ISSUE THREAD

**Issue by saitej123** [flairNLP/flair#2357]
from flair.models import TextClassifier
from flair.data import Sentence
classifier = TextClassifier.load('en-sentiment')

text 1= ''' I had to make a claim on the 8/6 as I had had an attempted break-in at my home, with my front door damaged  '''

s1 = Sentence(text 1)
classifier.predict(s1)
s1.labels  --- > gives  [NEGATIVE (0.7764)]
-------------------------------------------------------------------------------------------

text 2= ''' I had to make a claim on the 8/6 as I had had an attempted break-in at my home, with my front door damaged. '''

s1 = Sentence(text 2)
classifier.predict(s1)
s1.labels  --- > gives  [POSITIVE (0.8858)]
------------------------------------------------------------------------------------------

How " . " can change the sentiment of the sentence?

Please explain

**Comment by saitej123** [comment]
Some text cleaning method implemented in distilbert model training , please review that

**Comment by whoisjones** [comment]
Hi @saitej123, if you correct your sentence (you have 2x 'had' in it) then both predictions - with or without '.' - become positive. The model is probably confused by incorrect sentences.

**Comment by saitej123** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">so as we don&#39;t train models without special characters, and now all special characters have specific weights towards positivity and negativity. <a href="https://t.co/1LM05J4abQ">pic.twitter.com/1LM05J4abQ</a></p>&mdash; shyambhu mukherjee (@shyambhumukher1) <a href="https://twitter.com/shyambhumukher1/status/1420831080463036419?ref_src=twsrc%5Etfw">July 29, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by saitej123** [comment]
'.' has sentiment value 
![image](https://user-images.githubusercontent.com/18657211/128629127-8c14534a-c887-4423-ad52-7dac0c1ba630.png)
