### ISSUE TITLE
Is it possible that only using the CRF as the sequence tagger?

### ISSUE THREAD

**Issue by BrambleXu** [flairNLP/flair#2358]
A clear and concise description of what you want to know.
I want to train a sequence tagger without GPU to speed up the training time.
So I want to just use the CRF without BiLSTM.
Is it possible to do this in a easy way by using the flair?

**Comment by whoisjones** [comment]
Hi @BrambleXu, there'll be a PR for that soon. The Sequence Tagger will be refactored into separate modules - one of them is a CRF class which you can then use in your model.

**Comment by whoisjones** [comment]
@BrambleXu, you might wanna follow #2360.

**Comment by BrambleXu** [comment]
@whoisjones 
Thanks.  I will close this and follow the #2360
