### ISSUE TITLE
Refactoring of Sequence Tagger Class

### ISSUE THREAD

**Issue by whoisjones** [flairNLP/flair#2360]
**Is your feature/enhancement request related to a problem? Please describe.**
Cleaned-up version of the Sequence Tagger class with separate classes for Viterbi and CRF. Adapted to the new Classifier interface.

**Describe the solution you'd like**
-

**Comment by BrambleXu** [comment]
I am looking forward to use the independent CRF model.
Is there any update? I saw that the PR #2361 is still open.
