### ISSUE TITLE
Support for torch 1.8

### ISSUE THREAD

**Issue by ksmultiacc3** [flairNLP/flair#2370]
Can you please add support for torch 1.8? 
In requirements.txt, you have explicitly excluded support for this: torch>=1.5.0,!=1.8

**Comment by alanakbik** [comment]
The new Flair release (released yesterday) supports torch 1.9.

Torch 1.8 is still excluded since there is a problem with de-serializing models that use RNNs in torch 1.8. But if you don't want to use any of the pre-trained models that use RNNs, you could use Flair with torch 1.8 anyway.
