### ISSUE TITLE
Current documentation not aligned with current release 0.8: Wrong strings for downloading FlairEmbedding LMs

### ISSUE THREAD

**Issue by repodiac** [flairNLP/flair#2374]
**Describe the bug**
In `token.py` there are the static URL strings for downloading `FlairEmbedding`-based language models. However, the [documentation](https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/FLAIR_EMBEDDINGS.md) states at least in the case of `multi-X-fast` that this is the proper string.

I always got an error that the model did not exist or could not be retrieved. By having a glimpse into the current release's version, I found this:

```
"multi-v0-forward-fast": f"{hu_path}/lm-multi-forward-fast-v0.1.pt",
"multi-v0-backward-fast": f"{hu_path}/lm-multi-backward-fast-v0.1.pt",
```

So, your documentation seems to be aligned to the current branch/master but not to the current release (0.8)! Sorry, but this is highly annoying for anyone simply wanting to use your framework and not fiddling with it via git etc.

**Environment (please complete the following information):**
 - flair 0.8 (pypi)

**Comment by alanakbik** [comment]
Hello @repodiac this was fixed in #2150 - we will release 0.9 soon and it will include this fix.
