### ISSUE TITLE
Flair not working with torch -1.8

### ISSUE THREAD

**Issue by Harshit1011** [flairNLP/flair#2381]
Please add support for torch 1.8

**Comment by alanakbik** [comment]
The new Flair release (released yesterday) supports torch 1.9. 

Torch 1.8 is still excluded since there is a problem with de-serializing models that use RNNs in torch 1.8. But if you don't want to use any of the pre-trained models that use RNNs, you could use Flair with torch 1.8 anyway.

**Comment by gitclem** [comment]
> The new Flair release (released yesterday) supports torch 1.9.
> 
> Torch 1.8 is still excluded since there is a problem with de-serializing models that use RNNs in torch 1.8. But if you don't want to use any of the pre-trained models that use RNNs, you could use Flair with torch 1.8 anyway.

This note is for the record, as I don't expect it to get fixed...

I'm trying to do a bake off between BERT and flair.  What I found is BERT (transformers 4.6.0) has a problem with torch 1.9.

However, you can run flair 0.9 with torch 1.8 but you'll need to `pip install torch==1.8` after you install flair 0.9.
