### ISSUE TITLE
Is it possible to manually boost or reclassify words or phrases for text classification in best-model.pt

### ISSUE THREAD

**Issue by christophjones** [flairNLP/flair#2399]
I'm working on a text classification project to assign 1 of ~25 categories to a business based on the business description.
For example:
Sunglass Hut is an international retailer of sunglasses and sunglass accessories founded in Miami:  Retail
On The Border Mexican Grill & Cantina is a chain of Tex-Mex food casual dining restaurants:  Food & Beverage

The prediction model is working well but there are some instances I'd like to alter.  For instance, any time the description contains the word "hostel", I would like it to categorize as Travel.

Questions:
Is there a way to manually alter the existing .pt file to make that happen?
If not, do you have other suggestions to alter the prediction for given words or phrases?

Thanks

**Comment by christophjones** [comment]
Thanks - I'll check those out.

**Comment by alanakbik** [comment]
@christophjones you could also try the new zero-shot / few-shot NER tagger that ships with the new Flair 0.9 release: 

https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_10_TRAINING_ZERO_SHOT_MODEL.md#use-case-2-zero-shot-named-entity-recognition-ner-with-tars 

It (sometimes) works without training data. If you have some training data, you could try loading this model and continuing to train it with your data.

**Comment by christophjones** [comment]
Thanks for the guidance.  Will I have better results if I lemmatize the training and prediction data prior to use or does the model consider word lemmas as part of the prediction process?

**Comment by gitclem** [comment]
> Thanks for the guidance. Will I have better results if I lemmatize the training and prediction data prior to use or does the model consider word lemmas as part of the prediction process?

That I don't know.  I would try it both ways as see.  Let us know what you find out!
