### ISSUE TITLE
What label should I put in the label_type parameter?

### ISSUE THREAD

**Issue by nowhash** [flairNLP/flair#2406]
Sorry for this very noob question.
However, in the latest flair version, we need to initialize the label_type parameter.
I'm using this framework for a binary classification problem.
I'm confused what label should I put in the label_type parameter?

**Comment by alanakbik** [comment]
Hi @nowhash it depends on what dataset you are loading. When you use `make_label_dictionary` and pass a wrong `label_type` it will output a list of all label types in the corpus so you know what the options are.

**Comment by nowhash** [comment]
@alanakbik  Thanks for your reply.
Consider I have two labels: X and Y and I need prediction for the Y label.
So I need to put Y in label_type?
does my concept is right?

**Comment by alanakbik** [comment]
Yes that's correct.

**Comment by nowhash** [comment]
Thank you so much.
I was so confused about this parameter.
