### ISSUE TITLE
Few Shots TARS with NER

### ISSUE THREAD

**Issue by ashokxnarang** [flairNLP/flair#2408]
1. Would like to confirm if the Few Shots Tars with NER is supported in the Release 0.9. The Release Notes and Tutorial 10 indicate only support for Zero Shot Tars for NER. But example in [#2260 ](Zero-shot Named Entity Recognition (NER) with TARS) is for Few Shots TARS for NER. I do understand the example only for desired funtionality.
2. Would request a enhancement of Tutorial 10 for Few Shots Tars with NER with custom tags in the case this is supported.

**Comment by alanakbik** [comment]
Hello @ashokxnarang yes both are supported. The example in the tutorial is for zero-shot. But you can also load the base NER model and continue training it with some training data for the few-shot scenario. 

Here is example code on how to load the TARS NER model and train it for another task (few shot WNUT 2020): 

```python
import torch

import flair
from flair.datasets import NER_ENGLISH_WNUT_2020
from flair.models import TARSTagger, FewshotClassifier
from flair.trainers import ModelTrainer

flair.set_seed(123)

# load your corpus (example is for WNUT 2020, downsampled to 1% of data)
corpus = NER_ENGLISH_WNUT_2020().downsample(0.01)
dictionary = corpus.make_label_dictionary('ner')
print(dictionary)

# init the TARS sequence tagger
tars_tagger: FewshotClassifier = TARSTagger.load('tars-ner')

# add a new task
tars_tagger.add_and_switch_to_new_task(task_name="lab report NER",
                                       label_dictionary=dictionary,
                                       label_type="ner")

# train the model
trainer = ModelTrainer(tars_tagger, corpus, optimizer=torch.optim.AdamW)

trainer.train(
    f'resources/taggers/few-shot-sequence-tagger-wnut2020',
    learning_rate=5e-6,
    mini_batch_size=2, # set this higher if you have a big GPU
    max_epochs=10,
    embeddings_storage_mode="none",
    weight_decay=0.,
)
```

Note though that the model is not yet optimized for speed.
