### ISSUE TITLE
Document Relation Extraction and Entity Linking

### ISSUE THREAD

**Issue by BastianZim** [flairNLP/flair#2409]
Hi,

I was wondering if there are some docs somewhere for Relation Extraction and Entity Linking. 
I managed to get Relation Extraction going from the description in the release notes but a small hint on where to start with the Entity Linking would be great, thanks!

`print(corpus.train[3])` just prints `Sentence: "The First Purge - Official Poster"   [− Tokens: 6  − Token-Labels: "The <B-The_First_Purge> First <I-The_First_Purge> Purge <I-The_First_Purge> - Official Poster"]`.

Thanks!

**Comment by alanakbik** [comment]
Hello @BastianZim, 

here is an example script to train your own Entity Linking model. 

```python
threshold = 1

import torch

import flair
from flair.datasets import NEL_ENGLISH_REDDIT
from flair.models import EntityLinker
from flair.embeddings import TransformerWordEmbeddings
from flair.trainers import ModelTrainer
from torch.optim.lr_scheduler import OneCycleLR

flair.set_seed(123)

# get corpus
corpus = NEL_ENGLISH_REDDIT().downsample(0.1)
print(corpus)

# make a label dictionary
label_dict = corpus.make_entity_dict(threshold=threshold)

# initialize embeddings (use larger transformer model if you have the resources)
embeddings = TransformerWordEmbeddings(
    model='distilbert-base-uncased',
    layers="-1",
    fine_tune=True,
)

# initialize model
linker = EntityLinker(embeddings, label_dictionary=label_dict, pooling_operation='first&last')


# train the model
trainer = ModelTrainer(linker, corpus, optimizer=torch.optim.AdamW)

trainer.train('resources/taggers/entity_linker',
              learning_rate=5e-05,
              mini_batch_size=2,
              max_epochs=1,
              scheduler=OneCycleLR,
              embeddings_storage_mode='none',
              weight_decay=0.,
              main_evaluation_metric=("macro avg", 'f1-score'),
              gold_label_dictionary_for_eval=label_dict,
              )
```

Just beware that this is still in beta and there may be a few changes between this version and the flair 1.0 release. Please also let us know if you have any feedback.

**Comment by BastianZim** [comment]
Thanks for the example @alanakbik!

I tried the example and got the error `AttributeError: partially initialized module 'flair' has no attribute 'nn' (most likely due to a circular import)` like in #500 but I'll see if I can debug it myself.

**Comment by alanakbik** [comment]
Hm this script works in the setups I've tested (local and fresh CoLab notebook). 1 epoch is of course not enough, that number should be 10 or so.

**Comment by BastianZim** [comment]
Just recreated the conda environment and now it works, not sure why. But I tested the script and everything works as intended, thanks!

**Comment by alejandrojcastaneira** [comment]
Hello everyone, can you share a similar snippet for how to train a Relation Extraction model and in which format should be the training data?

**Comment by ivankrstev7** [comment]
@alejandrojcastaneira This is an example from the test file from the RE_ENGLISH_SEMEVAL2010 dataset:

# global.columns = id form ner
# text = The most common audits were about waste and recycling .
# sentence_id = 8001
# relations = 4;4;7;7;Message-Topic(e1,e2)
1	The	O
2	most	O
3	common	O
4	audits	B-E1
5	were	O
6	about	O
7	waste	B-E2
8	and	O
9	recycling	O
10	.	O

# text = The company fabricates plastic chairs .
# sentence_id = 8002
# relations = 2;2;5;5;Product-Producer(e2,e1)
1	The	O
2	company	B-E1
3	fabricates	O
4	plastic	O
5	chairs	B-E2
6	.	O

Each document is separated with a blank line, relations are represented with the spans of the entity and the relation label.

**Comment by alejandrojcastaneira** [comment]
Hi @ivankrstev7 thanks for the support! I was able to make a training code and formatted data, that works based on my custom relationships
