### ISSUE TITLE
Czech Named Entity Corpus

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#241]
Hi :)

I'm currently training language models for Czech and I found a nice NER corpus for Czech, the Czech Named Entity Corpus (CNEC). The corpus comes in the followiing formats: plain text, simple xml, treex and html. For `flair` the text format would be the most accurate one, e.g. a sentence looks like:

```bash
Zasáhli u pořadu z <P<pf Františka> <ps Halase>> <oa Naše paní <P<pf Božena> <ps Němcová>>> , což bylo v dobách prehistorie souboru .
```

The tagset is huge and also fine-grained:

![grafik](https://user-images.githubusercontent.com/20651387/48962178-d0a11180-ef7c-11e8-8a5f-c96f3d9d5fc1.png)

So I would like to ask, if we should support this format (new `datafetcher`) to parse this dataset? I guess a good option would be to enable/disable fine-grained tags.

E.g. the category "personal names" has "first names" and "second names" as sub categories.

Or should we use the scripts from [this repository](https://github.com/strakova/ner_tsd2016) to convert the treex format to a conll-like format? I tried the `treex2conll2003.pl` script and the output is:

```bash
Zasáhli zasáhnout VpMP---XR-AA--- _ O
u u-1 RR--2---------- _ O
pořadu pořad NNIS2-----A---- _ O
z z-1 RR--2---------- _ O
Františka František_;Y NNMS2-----A---- _ I-pf
Halase Halas_;S NNMS4-----A---- _ I-ps
Naše můj_^(přivlast.) PSHS1-P1------- _ I-oa
paní paní NNFS1-----A---- _ I-oa
Božena Božena_;Y NNFS1-----A---- _ I-oa
Němcová Němcová_;S NNFS1-----A---- _ I-oa
, , Z:------------- _ O
což což-1 PE--1---------- _ O
bylo být VpNS---XR-AA--- _ O
v v-1 RR--6---------- _ O
dobách doba NNFP6-----A---- _ O
prehistorie prehistorie NNFS2-----A---- _ O
souboru soubor NNIS2-----A---- _ O
. . Z:------------- _ O
```

🤔

Relevant paper: <http://ufal.mff.cuni.cz/~straka/papers/2016-tsd_ner.pdf>. Unfortunately, the conll-based corpus, named "CoNLL-based Extended CNEC 2.0" in the paper, is no longer available under <http://home.zcu.cz/~konkol/cnec2.0.php>  😣

**Comment by tabergma** [comment]
@stefan-it Thanks for providing the Czech models. They will be available in the next release.

We are very interested in adding the possibility for hierarchical tags. However, this will not be part of the next release. We hope to add this kind of feature in the release afterwards. We will keep you posted.
