### ISSUE TITLE
How to get F1 score for specific class instead of average calculation

### ISSUE THREAD

**Issue by nowhash** [flairNLP/flair#2411]
The main_evaluation_metric is the micro average F1 score.
Is it possible to calculate the F1 score for a specific class instead of an average calculation?
More precisely, is there any way to use the pos_label parameter of scikit-learn in the flair framework?
I just looking for something like that:
`f1_score(testLabelGold, testLabelPredicted, pos_label='Desired Label'))`
Any code snippet regarding this would be a great help.
Thank you

**Comment by alanakbik** [comment]
@nowhash the result overview at the end contains a breakdown by class, maybe this is what you're looking for? Or do you during training already want to ignore all other classes?

**Comment by nowhash** [comment]
@alanakbik I want to ignore all other classes during training. But I don't understand how to do it.

**Comment by alanakbik** [comment]
You could map all other classes to 'O' - then they will be ignored during training. Here is an example snippet for loading the corpus with all labels and loading the corpus with some labels excluded:

```python
# WNUT 2017 corpus will all labels
corpus = WNUT_17()
dictionary = corpus.make_label_dictionary('ner')
print(dictionary)

# WNUT 2017 corpus will labels "creative-work", "product" and "group" excluded
corpus_fewer_labels = WNUT_17(label_name_map={"creative-work": "O",
                                              "product": "O",
                                              "group": "O",
                                              }
                              )
dictionary = corpus_fewer_labels.make_label_dictionary('ner')
print(dictionary)
```
