### ISSUE TITLE
Can we download a model before running code?

### ISSUE THREAD

**Issue by demongolem-biz** [flairNLP/flair#2413]
I have a line code as such `tagger = SequenceTagger.load('ner-ontonotes-fast)` and under normal execution the model will be downloaded when the line is execute and things go as expected.

My question is can I download the model in a separate step such that when the code is run the download step is skipped.  I would like to download the model to a specific place beforehand and then load it from there, so basically have a little more control over the download process of models.

**Comment by alanakbik** [comment]
Hello @demongolem-biz you can change the default path where everything is stored like this: 

```python
import flair
# set a different root folder for all downloads
flair.cache_root = Path("datasets")
```

The download is only triggered the first time a model is loaded. Perhaps you could trigger all downloads once in the beginning so that later there are no interruptions due to download calls.
