### ISSUE TITLE
TextRegressor, AttributeError: 'list' object has no attribute 'labels'

### ISSUE THREAD

**Issue by vwoloszyn** [flairNLP/flair#2422]
from flair.datasets import WASSA_JOY
corpus = WASSA_JOY()

embeddings = DocumentPoolEmbeddings([WordEmbeddings('glove')], fine_tune_mode='linear')

model = TextRegressor(embeddings, label_name='happiness')

output_folder = 'resources/taggers/regression_test/'

trainer = ModelTrainer(model, corpus)
trainer.train(
    output_folder,
    mini_batch_size=16,
    max_epochs=10,
)

model = TextRegressor.load(output_folder + 'best-model.pt')

sentence = Sentence('I am so happy')
model.predict(sentence)

print(sentence)

########################
got the following error

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-17-b98a96006f68> in <module>()
     17     output_folder,
     18     mini_batch_size=16,
---> 19     max_epochs=10,
     20 )
     21 

4 frames
/usr/local/lib/python3.7/dist-packages/flair/models/text_regression_model.py in <listcomp>(.0)
     36                 [float(label.value) for label in sentence.labels], dtype=torch.float
     37             )
---> 38             for sentence in sentences
     39         ]
     40 

AttributeError: 'list' object has no attribute 'labels'

**Comment by alanakbik** [comment]
@vwoloszyn thanks for reporting this! This is an error caused by the refactoring for flair release 0.9. I just merged a PR that fixes this issue in the master branch. You can install from master through pip by doing: 

```
pip install --upgrade git+https://github.com/flairNLP/flair.git 
```

We'll also do a bugfix release soon (flair 0.9.1) which will include this fix.

**Comment by vwoloszyn** [comment]
Hi @alanakbik, thank you very much for your quick reply. It's all working fine now ;)
