### ISSUE TITLE
Evaluation Error

### ISSUE THREAD

**Issue by Phd-Student2018** [flairNLP/flair#2423]
A clear and concise description of what you want to know.
Hello
I use the following code for evaluation and it worked fine
"tagger: SequenceTagger = SequenceTagger.load('resources/taggers/example-pos/final-model.pt')

result, score = tagger.evaluate(corpus_test.test, mini_batch_size=1, out_path=f"predictions.txt")
print(result.detailed_results)"

 Today it does not work and I get this error: 
TypeError                                 Traceback (most recent call last)
<ipython-input-14-c57cf34e4368> in <module>
      
----> 6 result, score = tagger.evaluate(corpus.test, mini_batch_size=1, out_path=f"predictions.txt")
      7 print(result.detailed_results)

TypeError: evaluate() missing 1 required positional argument: 'gold_label_type'

could help me, please?

**Comment by alanakbik** [comment]
Hi @Phd-Student2018 many corpora have multiple layers of annotation. For instance, a corpus might have 'pos' tags and 'ner' (named entity recognition) tags. For this reason, you need to tell the evaluate method which tag should be evaluated. 

In Flair 0.9, the snippet should look like this: 

```python
tagger: SequenceTagger = SequenceTagger.load('resources/taggers/example-pos/final-model.pt')

result = tagger.evaluate(corpus_test.test, gold_label_type='pos', mini_batch_size=1, out_path=f"predictions.txt")
print(result)
```

You could also consider setting `mini_batch_size` to a higher number to increase speed.

**Comment by Phd-Student2018** [comment]
Thanks a lot it works.
I have another question pleas, If I have just 2 dataset files one for training and one for evaluation. what shoud I do in training with these2 options (making them true or false ) :
train_with_test 
train_with_dev

**Comment by alanakbik** [comment]
The default is to leave then as `False`. In this case, a dev split will be automatically sampled from the training split.
