### ISSUE TITLE
No more predictions confidences in the case of a multi-label TARSClassifier ?

### ISSUE THREAD

**Issue by qanastek** [flairNLP/flair#2426]
Hi,

I am using Flair 0.8.0.post1 for a while and after upgrading to the version 0.9.0, I was no more able to define the multi_label and multi_label_threshold parameters for the TARSClassifier like follow.

```
tars = TARSClassifier.load(args.model_path)
tars.add_and_switch_to_new_task(
  task_name = "demo_task",
  multi_label = True,
  multi_label_threshold = 0.0
)
```

or

```
tars = TARSClassifier.load(args.model_path)
tars.multi_label = True
tars.multi_label_threshold = 0.0
```

I have looked to the code and saw some outdated comments about it. at the L.183 in `models/tars_model.py`

```
:param multi_label: auto-detect if a corpus label dictionary is provided. Defaults to True otherwise
:param multi_label_threshold: If multi-label you can set the threshold to make predictions
```

What does we need to do to get the predictions confidences in the case of a multi-label TARS classifier like in the 0.8.0 ?

`
'label': [label_1 (1.0), label_2 (0.0), label_3 (0.0), label_4 (0.0), label_5 (0.0001), label_6 (0.0), label_7 (0.0)]
`

Thank you for your help.

Best regards,
Yanis Labrak

**Comment by qanastek** [comment]
I also saw a incompatibility between old and new models.  The error `KeyError: 'batch_size'` occur when I tried to load a 0.9 model with a script in version 0.8.

**Comment by alanakbik** [comment]
@qanastek thanks for reporting this! The functionality for setting different label thresholds unfortunately got lost in the refactoring to flair 0.9, but I'll upload a patch shortly that adds this feature back in. Then you have access to it from master branch, and we're also planning a 0.9.1 release to fix this and other issues soon.

Regarding the second issue, that's unfortunately not fixable: models trained with earlier versions of flair should still work in newer versions, but the other direction is not always possible.

**Comment by qanastek** [comment]
Ok, thank you for your fast anwser, I will wait until the next update.

**Comment by alanakbik** [comment]
@qanastek I've just merged a PR for this. 

You can test this by installing directly from master through pip: 

```
pip install --upgrade git+https://github.com/flairNLP/flair.git
```

Then, you can tell the predict method whether you want `multi_label` prediction or not and what the confidence threshold is: 

```python
from flair.models import TARSClassifier
from flair.data import Sentence

# 1. Load our pre-trained TARS model for English
tars: TARSClassifier = TARSClassifier.load('tars-base')

# switch to a multi-label task (emotion detection)
tars.switch_to_task('GO_EMOTIONS')

# sentence with two emotions
sentence = Sentence("I am happy and sad")

# predict normally
tars.predict(sentence)
print(sentence)

# predict with lower label threshold (you can set this to 0. to get all labels)
tars.predict(sentence, label_threshold=0.01)
print(sentence)

# predict and enforce a single-label prediction
tars.predict(sentence, label_threshold=0.01, multi_label=False)
print(sentence)
```

Let me know if that works for you. As mentioned, we'll also do a release soon so users get it if installing regularly through pip.

**Comment by qanastek** [comment]
@alanakbik  I have check and it's looking to be working well.

Your example works perfectly and its the same for mine.

```
tars.predict(res, label_threshold=0.0, multi_label=True
$> [− Tokens: 401  − Sentence-Labels: {'task_v': [Treatment (1.0), Mechanism (0.0), Prevention (0.0), Case Report (0.0), Diagnosis (0.9157), Transmission (0.0), Epidemic Forecasting (0.0)]}]
```

Let me know when you will update the pip package.

Thank you again for your very fast response time.
