### ISSUE TITLE
Can Hunflair detect unseen Disease name?

### ISSUE THREAD

**Issue by mennatallah644** [flairNLP/flair#2432]
A clear and concise description of what you want to know.

**Comment by mariosaenger** [comment]
Hi @mennatallah644 ,

sure, HunFlair can detect disease names even if the model hasn't seen the exact disease during training. Have you noticed a missing annotation in your texts?

**Comment by mennatallah644** [comment]
Hi @mariosaenger 
i tested the model with corona virus and Covid-19 and it didn't recognized them
How can i improve the performance of the Hunflair model? i have list of diseases i want the model to recognize but i don't have dataset i just have the labels ? also how can i optimize the speed of Hunflair?

**Comment by mariosaenger** [comment]
Hi @mennatallah644 ,

on which kind of text do you apply the model? Note that HunFlair is focused on scientific biomedical literature. Furthermore, the prediction quality depends on the context and the surface form of the disease mention. For example, running the following snippet
```python
from flair.data import Sentence
from flair.models import MultiTagger
from flair.tokenization import SciSpacyTokenizer

hunflair_tagger = MultiTagger.load("hunflair")

tokenizer = SciSpacyTokenizer()
sentences = [
    Sentence("In this study, we are investigating 19 patients with SARS-CoV-2.", use_tokenizer=tokenizer),
    Sentence("In this study, we are investigating 19 patients suffering COVID-19.", use_tokenizer=tokenizer),
    Sentence("In this study, we are investigating 19 patients suffering Covid.", use_tokenizer=tokenizer),
]
hunflair_tagger.predict(sentences)

for sentence in sentences:
    print(sentence.to_original_text())
    print(sentence.get_spans("hunflair-disease"))
```
... leads to:
```
In this study, we are investigating 19 patients with SARS-CoV-2.
[<Disease-span (11,12,13): "SARS - CoV-2">]

In this study, we are investigating 19 patients suffering COVID-19.
[<Disease-span (11): "COVID-19">]

In this study, we are investigating 19 patients suffering covid.
[]
```
Unfortunately, there is no simple way to add a list of new diseases to the model (without having a data set with annotated texts). Ad-hoc, I would recommend you to do an additional post-processing step via (approximate) string matching.

>> also how can i optimize the speed of Hunflair?

Can you elaborate a bit more about your computing environment (cpu/gpu?, memory?) and how you run the model? For the latter, do you predict multiple sentences at once and re-use the tokenizer (both - as shown in the snippet above)?

**Comment by mennatallah644** [comment]
Hello @mariosaenger ,
I tried to provide all sentences at once and it actually speedup the prediction, but 
sentences = [
    Sentence("In this study, we are investigating 19 patients with SARS-CoV-2.", use_tokenizer=tokenizer),
    Sentence("In this study, we are investigating 19 patients suffering COVID-19.", use_tokenizer=tokenizer),
    Sentence("In this study, we are investigating 19 patients suffering Covid.", use_tokenizer=tokenizer),
   # more sentences ...
] 
these lines of code actually i do it in for loop as i am reading text from file so i do it as

for i in test_list:
    sent = Sentence( i , use_tokenizer=tokenizer)
    sentences.append(sent)

and it takes too much time when it loops for more sentences is there a way to optimize it so that i can provide all the sentences without looping

**Comment by dumblob** [comment]
Maybe some parallelization could leverage the Colab HW better?

**Comment by dumblob** [comment]
I am still interested in this - maybe remove the stale bot here?

**Comment by dumblob** [comment]
Still interested...

**Comment by dumblob** [comment]
I am just interested in the optimization of speed - if the bottle neck is reading from a file then I would welcome an end-to-end example how to approach it :wink:.

Otherwise yes, the question has been thoroughly answered and I am thankful for that! Thanks @mariosaenger !

**Comment by dumblob** [comment]
Anyone with an end-to-end example how to avoid/suppress the bottle-neck of reading a file?
