### ISSUE TITLE
Multi-label issues

### ISSUE THREAD

**Issue by Doug-Hatfield** [flairNLP/flair#2437]
In v0.8 the multi_label=True and multi_label_threshold=0.0 could be set on the model at inference to get comprehensive and consistent output. In v0.9 it can be set on the label_dict but that does nothing. Inspection of the source appears to confirm that this is a bug. 

Aside: an arbitrary threshold of 0.5 for acceptance of a label is illogical to me. Inconsistent outputs are vastly harder to handle downstream and thresholding is trivial for the user. IMO, this is throwing away information to pander to the ignorance of the least knowledgeable user.

**Reproducing**
label_dict.multi_label = True
label_dict.multi_label_threshold = 0.0

tars.add_and_switch_to_new_task(TASK_NAME, 
                                label_dictionary=label_dict, 
                                label_type = 'XYZ')

Output
'XYZ': {'label_dictionary': <flair.data.Dictionary object at 0x7f2b8a9d1a60>, 'label_type': 'XYZ}

**Expected behavior**
'XYZ': {'label_dictionary': <flair.data.Dictionary object at 0x7f2b7f53dee0>, 'multi_label': True, 'multi_label_threshold': 0.0, 'label_type': 'XYZ', 'beta': 1.0}

**Environment**
 - Databricks notebook
 - flair==0.9:

**Comment by alanakbik** [comment]
Hello @Doug-Hatfield I believe this is a duplicate of #2426 and if so it is fixed in master branch (though the syntax is slightly changed from earlier, see below). 

You can test this by installing directly from master through pip: 

```
pip install --upgrade git+https://github.com/flairNLP/flair.git
```

Then, you can tell the predict method whether you want `multi_label` prediction or not and what the confidence threshold is: 

```python
from flair.models import TARSClassifier
from flair.data import Sentence

# 1. Load our pre-trained TARS model for English
tars: TARSClassifier = TARSClassifier.load('tars-base')

# switch to a multi-label task (emotion detection)
tars.switch_to_task('GO_EMOTIONS')

# sentence with two emotions
sentence = Sentence("I am happy and sad")

# predict normally
tars.predict(sentence)
print(sentence)

# predict with lower label threshold (you can set this to 0. to get all labels)
tars.predict(sentence, label_threshold=0.01)
print(sentence)

# predict and enforce a single-label prediction
tars.predict(sentence, label_threshold=0.01, multi_label=False)
print(sentence)
```

Let me know if that works for you. We'll also do a release soon so users get it if installing regularly through pip.

**Comment by Doug-Hatfield** [comment]
Thanks! Apparently my Search-foo failed me and yes, it worked once I uninstalled the flair library, restarted and installed with !pip install... I'm still not convinced that 'pretending' that a multi-label stack of binary models is anything else. People who cannot threshold or argmax as appropriate should not be allowed near this much power, but great work - thanks again!
