### ISSUE TITLE
Predict measurent unit

### ISSUE THREAD

**Issue by PeaceDeveloper** [flairNLP/flair#2441]
Hi,

I have a lot of sentences that describe products with unity measurement like:

1. Product A 1000ML marca X CX12
2. Product A marca Y C/ 12 1000 ML
3. Product A 1L CX 12
4. Product A 100ML
5. Product B 1000ML marca X CX12

There are a lot of sentenceces like this. I Dont't know how many products are. But I want same products with same unit measurement. So, the five sentences above has three groups. Group 1 (Sentence 1, Sentence 2 and Sentence 3), group 2(Sentence 4) and group 3 (Sentence 5): for example.
I have created a flair embedding model to this specific domain and calculate a cossine similarity to make this groups. But I want much more precision.

There are a better strategy? Trainning a flair ner model to this specific domain could help me more to calculate the cossine similarity or fed a cluster algorithim?

**Comment by helpmefindaname** [comment]
Hello @PeaceDeveloper
I don't think cosine similarity or clustering are the right approach to it.
From your examples it seems like you can use a regex to extract the amount + unit, then convert all units to a base unit to get a standardized number. You can also use a regex for the product, so at the end you have extracted:

1. ("Product A", 1000, "ML")
2. ("Product A", 1000, "ML")
3. ("Product A", 1000, "ML")
4. ("Product A", 100, "ML")
5. ("Product B", 1000, "ML")

and you just need to check if the tuples are the same

**Comment by PeaceDeveloper** [comment]
Hello @helpmefindaname,

Thank's by your response. It is good! Maybe I have to use this idea to prepare the corpus first.

The great problem is that this sentences don't have a pattern. So, a product and a unity measurente can be write and combined to a lot of way.
