### ISSUE TITLE
Compiling flair model into an AWS Neuron optimized TorchScript

### ISSUE THREAD

**Issue by itaim** [flairNLP/flair#2443]
Hi,
I am looking for a way to utilize aws neuron inference with flair.
So looking for a way to compile flair model into neuron optimized torchscript.
Similar to what is described here for BERT model:
https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.html
Is it doable and is there a guide on how to achieve this?

**Comment by DevBey** [comment]
+1

**Comment by DevBey** [comment]
Hi@itaim ,

did you try tracing the model, I have deployed numerous other PyTorch model on neuron yet to try this one.. 

I will update if able to do !!

**Comment by EdenAnteby** [comment]
Hey @itaim, I'm also interested,
have you made any progress in using AWS neuron with flair?

**Comment by helpmefindaname** [comment]
Hello,
I made a PR which should make it possible to use `torch.jit.trace` and therefore also aws neuron, can you take a look at https://github.com/flairNLP/flair/pull/2739/files#diff-12961c27a5afbdccd88c22a4678b771edbe9a64e512fd5db7b3ac4df4fa4234b and see if that works?
