### ISSUE TITLE
Index 0 is out of bounds for dimension 0 with size 0

### ISSUE THREAD

**Issue by megantosh** [flairNLP/flair#2450]
A clear and concise description of what you want to know.
Hello,

I am training two NER models (one dataset per model) using the same parameters, tagset (41 tags) and embedding stack, among which one embedding is transformer-based. 

Both datasets (identical portion of Arabic OntoNotes) are of identical text, except that one of them is diacritized (i.e. vocalization marks 'ِ ُ  ٌ  ' included) and the other is not.

The diacritized version runs through all epochs to produce a model. The **un**diacritized version does not complete an epoch and produces this error. If I remove the [transformer embedding](https://huggingface.co/aubmindlab/bert-base-arabertv2) from the stack, the training runs smoothly. 

This is probably not related to  #2144. Anyone here encountered a similar issue?

![Screenshot 2021-09-24 at 02 17 45](https://user-images.githubusercontent.com/4587828/134600079-6755d432-8e7c-4e9a-8c47-072fa41a2040.png) ![Screenshot 2021-09-24 at 02 18 27](https://user-images.githubusercontent.com/4587828/134600081-91024311-13e6-4003-b168-473370ca7483.png)

![Screenshot 2021-09-24 at 02 02 01](https://user-images.githubusercontent.com/4587828/134600302-56d4cc73-242a-44f8-acce-5a0898433876.png)

This is probably not related to  #2144. Anyone here encountered a similar issue?

Steps to reproduce error:
```python
 embedding_types = [
        WordEmbeddings('ar'),
        FlairEmbeddings('ar-forward'),
        FlairEmbeddings('ar-backward'),
# removing this would make the training run
        TransformerWordEmbeddings('aubmindlab/bert-base-arabertv2',
                                 layers="all", pooling_operation="first",
                                 fine_tune=False, allow_long_sentences=False,
                                 use_scalar_mix=True)
    embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=embedding_types)

    tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                            embeddings=embeddings,
                                            tag_dictionary=tag_dictionary,
                                            tag_type=tag_type,
                                            use_crf=True)

    trainer: ModelTrainer = ModelTrainer(tagger, downsampled_corpus)

    trainer.train('/mymodel',
                  learning_rate=0.1,
                  mini_batch_size=16,
                  max_epochs=150
                  )

**Comment by alanakbik** [comment]
If you are on 0.9 this may be fixed in master branch. Could you check?

**Comment by megantosh** [comment]
Thank you, just did and now the error stack got much longer, but is more indicative:

```
Token indices sequence length is longer than the specified maximum sequence length for this model (74 > 512).
 Running this sequence through the model will result in indexing errors.
```

I'll spare the error stack here, but it comes down to a 
```
CUDA out of memory. Tried to allocate xxxMiB (GPU0; ...)
```

According to [Huggingface Transformers](https://github.com/huggingface/transformers/issues/1791) there is a way to circumvent the sequence encoding in HF directly by defining a tokenizer. The Flair TransformerWordEmbeddings method only allows these arguments:
<img width="577" alt="Screenshot 2021-09-27 at 21 57 50" src="https://user-images.githubusercontent.com/4587828/134976549-91852619-3d1c-43a6-bdb2-9cec16279f11.png">
  
Is there a possibility to bypass this without the need of using different embeddings?
Help much appreciated!
