### ISSUE TITLE
Cuda out of memory issue

### ISSUE THREAD

**Issue by debjyoti003** [flairNLP/flair#2460]
I have a list of text files on which I want to extract named entities. I am using SequenceTagger.load('ner-ontonotes-fast'). ​After running for few files I am getting the error "RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 15.90 GiB total capacity; 14.81 GiB already allocated; 29.75 MiB free; 14.96 GiB reserved in total by PyTorch)".  Someone, please suggest how to solve this issue.

**Comment by sadakmed** [comment]
After each file, you can simply empty the cuda memory with `torch.cuda.empty_cache()`
