### ISSUE TITLE
LayoutLM support

### ISSUE THREAD

**Issue by fracav** [flairNLP/flair#2465]
are you going to support algorithms that also consider layout information and possibly also the image (Document AI)? These algorithms can be very useful in document analysis. A very interesting example is LayoutLM also present on hugginface. Thanks in advance

**Comment by helpmefindaname** [comment]
Hi @fracav 
I added support at [This PR](https://github.com/flairNLP/flair/pull/2980)
In case that you are still working with layoutlm, could you please try this out?
