### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by MelaniaNitu** [flairNLP/flair#2476]
**Describe the bug**
I'm using flair to import existing embedding from Huggingface to train BERTopic as described [here](https://maartengr.github.io/BERTopic/tutorial/embeddings/embeddings.html#flair). As per documentation, we should be able to select any transformer model available on [huggingface](https://huggingface.co/models). For some of the pre-trained models I get this error: **"OverflowError: int too big to convert"**.

**To Reproduce**
```
from flair.embeddings import TransformerDocumentEmbeddings
robert = TransformerDocumentEmbeddings('readerbench/RoBERT-base')
model = BERTopic(embedding_model=robert,verbose=True) 
docs = df.text.to_list()
topics, probabilities = model.fit_transform(docs)
```
Output:
```
0it [00:00, ?it/s]
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-17-4da31a0e0fc5> in <module>()
      9 
     10 #train model
---> 11 topics, probabilities = model.fit_transform(docs)

10 frames
/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_fast.py in set_truncation_and_padding(self, padding_strategy, truncation_strategy, max_length, stride, pad_to_multiple_of)
    352             target = {"max_length": max_length, "stride": stride, "strategy": truncation_strategy.value}
    353             if _truncation != target:
--> 354                 self._tokenizer.enable_truncation(**target)
    355 
    356         if padding_strategy == PaddingStrategy.DO_NOT_PAD:

**OverflowError: int too big to convert**
```

**Expected behavior**

Similar issue was reported for TransformerWordEmbeddings. Solution for that one is described here: https://githubmemory.com/repo/flairNLP/flair/issues/2210 

class TransformerWordEmbeddings(TokenEmbeddings):
--->    NO_MAX_SEQ_LENGTH_MODELS=[XLNetModel, TransfoXLModel, **BertModel**]

**Environment**
Google Colab (Jupyter Notebook)

**Additional context**
Similar issue was reported for **TransformerWordEmbedding** for XLNet model which was fixed by @tiagokv. It looks like the PR fix made by @tiagokv is needed as well for the other transformers models besides XLNet so TransformerWordEmbeddings can work properly. 

Now, in the case of **TransformerDocumentEmbeddings**, I guess we would have to "port" that fix to make it work with TransformerDocumentEmbeddings as well.

Any help with publishing this fix is highly appreciated, at least for a multilingual model such as 'bert-base-multilingual-cased' as this will cover 100+ languages.

**Comment by whoisjones** [comment]
hi @MelaniaNitu,

when loading the model, set `model_max_length=512` and it should work. This issue comes up because the config.json of the tokenizer does not contain any default value. See also gh-2500.

**Comment by MelaniaNitu** [comment]
Hi @whoisjones, thanks for the details and for the workaround. It indeed works adding model_max_length=512.
