### ISSUE TITLE
Updating New entity

### ISSUE THREAD

**Issue by paviarun** [flairNLP/flair#2477]
Hi, 

I want to use existing NER model and add my custom entities to it. 
Like: Date,Person,Customent1,Customent2 etc

I tried using custom training as mentioned in Tutorial and https://github.com/flairNLP/flair/issues/1540, but it only takes new entities. I am not getting entities from pretrained model. Is there a way? any help would be much appreciated. 

Thanks.

**Comment by helpmefindaname** [comment]
Have you considered simply using two models?
Like you can use a pretrained model and create a custom one for the new types.
