### ISSUE TITLE
Automatic truncation of long input sequences for ColumnCorpus

### ISSUE THREAD

**Issue by philfuchs** [flairNLP/flair#2482]
I'm using context windows extracted from my documents for NER. When using the recommended combination of transformer (TransformerWordEmbeddings) with finetuning and a simple SequenceTagger (rnn and crf set to false) I get the following warning:

"Token indices sequence length is longer than the specified maximum sequence length for this model (514 > 512). Running this sequence through the model will result in indexing errors."

I haven't seen a way to do automatic truncation, is there a parameter I have missed?

Flair version: 0.8.0.post1
Model: distilbert-base-german-cased

**Comment by philfuchs** [comment]
Version 0.9, with an input sequence length of 200, and standard parameters:

```python
Token indices sequence length is longer than the specified maximum sequence length for this model (584 > 512). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "train_transformer.py", line 61, in <module>
    trainer.train(
  File "/home/philfuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/trainers/trainer.py", line 423, in train
    loss = self.model.forward_loss(batch_step)
  File "/home/philfuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 399, in forward_loss
    features = self.forward(data_points)
  File "/home/philfuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py", line 404, in forward
    self.embeddings.embed(sentences)
  File "/home/philfuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/embeddings/base.py", line 60, in embed
    self._add_embeddings_internal(sentences)
  File "/home/philfuchs/anaconda3/envs/flairtest/lib/python3.8/site-packages/flair/embeddings/token.py", line 1091, in _add_embeddings_internal
    final_embedding: torch.FloatTensor = current_embeddings[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0
```

**Comment by alanakbik** [comment]
Strange, how are you instantiating the embeddings? Could you provide a minimal example with a single sentence that causes this error?

**Comment by philfuchs** [comment]
I'm not working with natural language data  (in the sense of well formed sentences, documents, etc.) but with sections extracted from CVs (for NER), hence it contains sensitive information that I can't share. However, when I take an arbitrary datapoint from the set that exceeds a certain length I get the error.

At the moment I need to set the length manually ('at most X tokens long') in order to avoid the aforementioned error. I suspect that it's due to the BPE tokeniser, but I haven't found a way to constrain the resulting input sequence.

This is my code so far (almost identical to the tutorial on here):

```python
# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(
    model_config.data_folder, columns,
    train_file="train3.txt", # <-- tiny debug data set with ~300 lines
    test_file="test.txt",
    dev_file="dev.txt",
    in_memory=False,
)

print(corpus)
tag_type = "ner"
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
print("Tag Dictionary: ", tag_dictionary)

# 4. initialize fine-tuneable transformer embeddings WITH document context
embeddings = TransformerWordEmbeddings(
    model="distilbert-base-german-cased",
    layers="-1",
    subtoken_pooling="first",
    fine_tune=True,
    use_context=False,
    allow_long_sentences=True # <-- seems to have no effect with either option
)

# 5. initialize bare-bones sequence tagger (no CRF, no RNN, no reprojection)
tagger = SequenceTagger(
    hidden_size=512,
    embeddings=embeddings,
    tag_dictionary=tag_dictionary,
    tag_type='ner',
    use_crf=False,
    use_rnn=False,
    reproject_embeddings=False,
)

# 6. initialize trainer with AdamW optimizer
trainer = ModelTrainer(tagger, corpus, optimizer=torch.optim.AdamW)

# 7. run training with XLM parameters (20 epochs, small LR, one-cycle learning rate scheduling)
trainer.train(
    output_path,
    learning_rate=5.0e-6,
    mini_batch_size=4,
    max_epochs=2,  # 10 is also good
    scheduler=OneCycleLR,
    embeddings_storage_mode='none',
    weight_decay=0.,
    checkpoint=True
)
```

**Comment by iliaNecrov** [comment]
I have the same issue. My task is finding sensitive data in text. Even though I deleted long sentences (more than 200 tokens) I still get the warning about token indices. 
@philfuchs Have you managed to solve this problem?

**Comment by philfuchs** [comment]
@iliaNecrov No, I haven't solved it. The project is finished as well (I ended up not using `TransformerWordEmbeddings` due to this error), so I'm not working on it anymore either.
