### ISSUE TITLE
Multitask Learning in flair

### ISSUE THREAD

**Issue by whoisjones** [flairNLP/flair#2508]
We would like to enhance flair with multitask learning, e.g. combine various models and share specific layers across several tasks.

**Is your feature/enhancement request related to a problem? Please describe.**
New feature.

**Describe the solution you'd like**
A modular, easy-to-use multitask framework solution.

**Comment by djstrong** [comment]
I would be interested in multitask training NER and relation extraction using the same dataset. So it should compute embeddings once for both heads. I guess it would be complicated to implement?
