### ISSUE TITLE
Torch version

### ISSUE THREAD

**Issue by david-waterworth** [flairNLP/flair#2511]
I'm new to flairNLP. I noticed that the `requirements.txt` for torch has a minimum version of torch>=1.5.0 and a specific exclusion for 1.8

Is this deliberate, i.e. torch 1.9 and 1.10 have been released, I have cuda 1.11 installed and based on the available torch wheels from https://download.pytorch.org/whl/torch_stable.html I need to use torch 1.8 or higher, which means 1.9 (or perhaps 1.8.1 but I think !=1.8 excludes 1.8.1)

Is this compatible?

**Comment by helpmefindaname** [comment]
hey @david-waterworth as the requirements state 1.8 is excluded. This only refers to 1.8.0. 1.8.1 is possible again. If you want to read up the context of why 1.8.0 is bad, I would refer to this: https://github.com/pytorch/pytorch/pull/57558 which is the fix to the problem.

**Comment by david-waterworth** [comment]
thanks @helpmefindaname - I ended up installing 1.9.1
