### ISSUE TITLE
Confusing loss_forward in sequence_tagger_model.py and trainer.py 

### ISSUE THREAD

**Issue by 73minerva** [flairNLP/flair#2514]
Hi.
As defined in abstract Flair.Model class, forward_loss methed should return a torch tensor. Although in implemented sequence_tagger_model, type of forward_loss hints at torch tensor, it seems it does not happen.
https://github.com/flairNLP/flair/blob/94393aa82444f28c5a1da6057b8ff57b3cb390e6/flair/models/sequence_tagger_model.py#L391-L395
https://github.com/flairNLP/flair/blob/94393aa82444f28c5a1da6057b8ff57b3cb390e6/flair/models/sequence_tagger_model.py#L510-L512

In trainer.py, calculating train_loss is really complicated and confusing. Only train_loss is divided by average_over based on leghts of sequence. But eval_loss is reported without any division. I think that following type hints and dividing loss by average_over in forward_loss Is a better solution.

**Comment by alanakbik** [comment]
Hello @73minerva yes good points. We need to adapt the method signature of forward_loss. But the loss returned by the evaluate method is already averaged so the eval_loss should be consistent.
