### ISSUE TITLE
missing 1 required positional argument: 'label_type'

### ISSUE THREAD

**Issue by cjing1** [flairNLP/flair#2526]
Thank you for this amazing package for NLP. I am new to flair, and I am trying to use flair to build a text classification model. I tried multiple tutorials from various sources, however, I always got the same error reported. May I ask how to fix it? Or would you mind pointing me to some helpful resources? 

https://towardsdatascience.com/text-classification-with-state-of-the-art-nlp-library-flair-b541d7add21f
https://www.geeksforgeeks.org/flair-a-framework-for-nlp/

**Describe the bug**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-53-8af13eee6597> in <module>
         9 
        10 # create a label dictionary
---> 11 label_Dictionary = corpus.make_label_dictionary()
        12 
        13 # list of word embeddings to be used

TypeError: make_label_dictionary() missing 1 required positional argument: 'label_type'

**To Reproduce**

```python
from flair.data import Corpus
from flair.datasets import TREC_6
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentRNNEmbeddings
from flair.models import TextClassifier
from flair.trainers import ModelTrainer
  

corpus = TREC_6()
  
label_Dictionary = corpus.make_label_dictionary()
  
word_embeddings = [WordEmbeddings('glove'),FlairEmbeddings('news-forward-fast')]
  
doc_embeddings = DocumentRNNEmbeddings(word_embeddings,hidden_size = 250)
  
text_classifier = TextClassifier(doc_embeddings,label_dictionary = label_Dictionary)
  
model_trainer = ModelTrainer(text_classifier,corpus)
  
model_trainer.train('resources/taggers/trec',learning_rate=0.1,mini_batch_size=40,anneal_factor=0.5,patience=5,max_epochs=200)
```

**Comment by cjing1** [comment]
I think my question is what/ how to write custom label_type. I know there are given label_type from the package such as 'question_class', 'ner', etc. How should I construct a custom label_type? For example, if I want to label the sentiment of sentences with 'positive' or 'negative', how should I write the label_type line? 

label_type = 'question_class'
label_dict = corpus.make_label_dictionary(label_type=label_type)

Thank you

**Comment by alanakbik** [comment]
Hello @cjing1 we changed the syntax so that you should pass the name of the label type to the method. If you pass the wrong label type, the method will print all label types in the corpus that are available. 

For instance, if you run the following: 

```python
corpus = TREC_6()

label_Dictionary = corpus.make_label_dictionary(label_type='help me')
```

it will print: 

~~~
Corpus contains the labels: question_class (#4907)
~~~

meaning this corpus contains only the label type `question_class` (4907 times).

**Comment by cjing1** [comment]
Thank you for the feedback. Sorry for my naive question. But do we still need to modify the data similar to fastText input format?  ex, 'text'__label__'labelcategory' 

Or do we need to use .add_label() function now?

**Comment by cjing1** [comment]
Thank you for your feedback. 

I am still a little lost. What should we put in make_label_dictionary()? If I am labeling a sentence with either Yes or NO. Should I put make_label_dictionary('Yes')? And make sure the data input is in the fasttext format ex: text(underline)label(underline)Yes?

**Comment by cjing1** [comment]
FYI, I think in tutorial 6, the 'Reading a Text Classification Dataset' part also does not work because of the change of syntax.

**Comment by alanakbik** [comment]
Hello @cjing1, you set the label name when you load the corpus. So when you load your corpus using `ClassificationCorpus` you choose yourself how to call the label. Check out the following example:

```python
from flair.data import Corpus
from flair.datasets import ClassificationCorpus

# this is the folder in which train, test and dev files reside
data_folder = 'tests/resources/tasks/ag_news'

# load corpus containing training, test and dev data
corpus: Corpus = ClassificationCorpus(data_folder,
                                      test_file='test.txt',
                                      dev_file='dev.txt',
                                      train_file='train.txt',                                       
                                      label_type='topic', # here you give a name to the label
                                      )

print(corpus)

dictionary = corpus.make_label_dictionary(label_type='topic') # use the name again to create dictionary

print(dictionary)
```

So when loading the corpus, you use `label_type` to give a name to the label (here I used 'topic' but in your case you could call it 'sentiment' or 'positivity' or whatever you think is best). Use the same string to then create the dictionary.

Hope this clarifies!

**Comment by paulommaia** [comment]
I'm facing a similar issue @alanakbik 

`
from flair.datasets import ClassificationCorpus
from flair.data import Corpus
from flair.embeddings import WordEmbeddings, FlairEmbeddings, DocumentRNNEmbeddings
from flair.models import TextClassifier
from flair.trainers import ModelTrainer
from pathlib import Path

corpus: Corpus = ClassificationCorpus(
    Path('./flair_spam/'),
    test_file='test.csv', 
    dev_file='dev.csv', 
    train_file='train.csv', 
    label_type='label')

word_embeddings = [
    WordEmbeddings('glove'), 
    FlairEmbeddings('news-forward-fast'), 
    FlairEmbeddings('news-backward-fast')
]

document_embeddings = DocumentRNNEmbeddings(
    word_embeddings, 
    hidden_size=512, 
    reproject_words=True, 
    reproject_words_dimension=256)
`

This returns:
`2021-11-24 12:22:43,389 Reading data from flair_spam
2021-11-24 12:22:43,391 Train: flair_spam/train.csv
2021-11-24 12:22:43,392 Dev: flair_spam/dev.csv
2021-11-24 12:22:43,392 Test: flair_spam/test.csv
2021-11-24 12:22:45,779 Initialized corpus flair_spam (label type name is 'label')
`

However, when writing `dictionary = corpus.make_label_dictionary('label')` I see the following messages:

`2021-11-24 12:22:58,383 Computing label dictionary. Progress:

0it [00:00, ?it/s]

2021-11-24 12:22:59,121 Corpus contains only the labels: 
2021-11-24 12:22:59,122 You specified as label_type='label' which is not in this dataset!
`

**Comment by paulommaia** [comment]
My issue is probably related to the loader not supporting .csv files, I got it working using the  `CSVClassificationCorpus` but the error is not really explicit.

Maybe this can also help @cjing1 ? 

```
corpus: Corpus = CSVClassificationCorpus(
    Path('./flair_spam/'),
    test_file='test.csv', 
    dev_file='dev.csv', 
    train_file='train.csv',
    delimiter=';',
    column_name_map={0: 'text', 1: 'label'},
    label_type='label')
```

**Comment by alanakbik** [comment]
Ah yes, perhaps we can make this more clear in the tutorial? We support two corpus types, "FastText"-formatted and CSV, each with a different loader.

**Comment by paulommaia** [comment]
Yup, that would be my suggestion, as a new user :) Or verify the file type within each corpus and give an explicit message

Thank you!

**Comment by cjing1** [comment]
Thank you both for your help. 

I got the CSVClassificationCorpus running smoothly.
<img width="1276" alt="Screen Shot 2021-11-24 at 9 00 31 AM" src="https://user-images.githubusercontent.com/31779053/143252503-7b3e607e-c00b-4993-8671-62a1bf79123e.png">

However, when I am running the  make_label_dictionary function, I still got the following error. 
<img width="1277" alt="Screen Shot 2021-11-24 at 9 00 42 AM" src="https://user-images.githubusercontent.com/31779053/143252624-299f38c7-0267-4439-b897-c97f536bc2f3.png">

**Comment by cjing1** [comment]
And my data train test dev csv look like this
<img width="561" alt="Screen Shot 2021-11-24 at 9 07 36 AM" src="https://user-images.githubusercontent.com/31779053/143253512-74d79f5e-b408-4483-8da5-9d090cc59c5c.png">

**Comment by cjing1** [comment]
Thank you both for your help. The function works perfectly now. I really appreciate it. 

I do have one additional question. My label only contains Yes, No. But when I am running make_label_dictionary, I got an additional <unk>. How should I remove it? 

<img width="1267" alt="Screen Shot 2021-11-24 at 10 45 15 AM" src="https://user-images.githubusercontent.com/31779053/143270150-9c8a5c5e-41a7-4b34-9f2b-88bdd2814a4e.png">

**Comment by AhmedIdr** [comment]
Hey, I'm also getting an additional label <unk>. Did you figure out why is it happening?

**Comment by cjing1** [comment]
> Hey, I'm also getting an additional label . Did you figure out why is it happening?

I haven't figured it out... But seems when I apply the model, it will not predict <unk>

**Comment by AhmedIdr** [comment]
Okay, thank you for the feedback.

**Comment by junxiant** [comment]
> 

Hi, so the <unk> tags doesn't matter? Although in the decoder layer the out_features=3 when printing out the full architecture.

**Comment by ChessMateK** [comment]
> My issue is probably related to the loader not supporting .csv files and thus not being able to load any row. I got it working using the `CSVClassificationCorpus` but the error is not really explicit.
> 
> Maybe this can also help @cjing1 ?
> 
> ```
> corpus: Corpus = CSVClassificationCorpus(
>     Path('./flair_spam/'),
>     test_file='test.csv', 
>     dev_file='dev.csv', 
>     train_file='train.csv',
>     delimiter=';',
>     column_name_map={0: 'text', 1: 'label'},
>     label_type='label')
> ```

Hello! How did you solve? Using flair-0.9 on Google Colab I obtain a corpus without labels as yours, hence the advice "You specified as label_type='label' which is not in this dataset!". I'm using 'CSVClassificationCorpus', path to files on GDrive. Any suggestion? Thank you in advance.
