### ISSUE TITLE
Use flair sequence tagger ('pos') as feature extractor?

### ISSUE THREAD

**Issue by peppocola** [flairNLP/flair#2527]
Is there a simple way to extract the embeddings before the classification layer of sequence tagger?
I would like to have the embeddings extracted by your net that are used for classification, in order to combine them with other kinds of embeddings and build a new classifier. Is that possible?

**Comment by peppocola** [comment]
is [`sentence_tensor`](https://github.com/flairNLP/flair/blob/master/flair/models/sequence_tagger_model.py#L473) the answer?

**Comment by whoisjones** [comment]
If I understood correctly, that you need the output of the RNN or LSTM, then yes `sentence_tensor` would be the one you need.

**Comment by peppocola** [comment]
thanks a lot
