### ISSUE TITLE
Requirements.txt need updates?

### ISSUE THREAD

**Issue by whoisjones** [flairNLP/flair#2529]
**Describe the bug**
Requirements.txt is missing some packages. pip install -r requirements.txt aborts since following packages are not installed.

- six
- appdirs
- packaging
- ordered_set

**Environment (please complete the following information):**
 - Python 3.6
 - pip 20.3

**Comment by sadakmed** [comment]
try to upgrade pip with `pip install --upgrade pip`, as these packages normally are installed automatically since they are dependencies of other packages that are already listed in `requirements.txt`
haggingface-hub -> packaging
gdown -> six ...

**Comment by whoisjones** [comment]
@sadakmed ah cool good to know. observed this issue on our servers but on local machines it works. will check that.

**Comment by marcelmmm** [comment]
I encountered the same error when initializing my virtual environment with `venv` (`python3 -m venv [environment_name]`). 
But then when using `virutalenv` to create the environment  (`virtualenv --python=python3 [environment_name]`). Im not exactly sure wheres the difference, maybe because `virutalenv` already comes with the latest version of `pip`. But nevertheless it fixed the problem for me.

**Comment by whoisjones** [comment]
Remark from my side: pip install --upgrade pip does not solve the issue for me.

**Comment by helpmefindaname** [comment]
did you try it with creating new python environments from scratch?
for me (using conda environment; pip for installing) both installing flair from pypi and installing the requirements.txt works for newly created environments.

**Comment by sadakmed** [comment]
@whoisjones as @helpmefindaname  noted creating a new env will not have the issue. However, could you please add more info, and also verify if pip is pointing to python3 (pip -V), as if you have both python2 and 3, pip will use python2 interpreter

**Comment by avihaybar** [comment]
is there a reason the required version of `gdown` is pinned down to an old version? this clashes with many other packages I use (i.e - PyABSA)

**Comment by alanakbik** [comment]
@avihaybar `gdown` was updated in a recent PR (#2757), will be part of next release!
