### ISSUE TITLE
Improved CI-CD / contribution-setup

### ISSUE THREAD

**Issue by helpmefindaname** [flairNLP/flair#2534]
Currently, there are some parts of the contribution & CI-CD part that I think are improvable:

- travis: afaik travis was used previously, but then got replaced with GitHub actions. However, the [travis.yml](https://github.com/flairNLP/flair/blob/master/.travis.yml) file still exists. I think it should be removed.
- code formatting: There is a pre-commit-hook using black for code formating, however the CI-CD doesn't check for formatting and there isn't any documentation (anymore) about the usage of the pre-commit-hook. I think black should be explicitely mentioned in the [Contribution.md](https://github.com/flairNLP/flair/blob/master/CONTRIBUTING.md) and the CI-CD should also install [pytest-flake8](https://github.com/tholo/pytest-flake8) and [flake8-black](https://github.com/peterjc/flake8-black)
- type checking: Similar to code formatting, the CI-CD also doesn't check mypy types, but as this repository uses a lot of typing, I'd also want the CI-CD to use [pytest-mypy](https://github.com/dbader/pytest-mypy)
- test-speed: I'd consider using [pytest-xdist](https://github.com/pytest-dev/pytest-xdist) to run tests in parallel, this might fail due to high memory needs if several models are loaded at once, but if it works, it would surely benefit the testing speed. Testing currently takes ~20 minutes on CI-CD, which is a lot imo.
- pytest warnings: Currently running the tests in CI-CD yields 181 warnings. Most warnings indicate that something is not used the right way, others (e.g. deprecation warnings) are usually pointless and should be ignored (via [pyproject.toml](https://github.com/flairNLP/flair/blob/master/pyproject.toml)) in general, I'd recommend using the `-Werror` flag to display all warnings as errors, so people are forced to read the warning and to decide if they fix it or actively ignore it via the settings.
- unify the CI-CD requirements and the def requirements by creating a `requirements-dev.txt`

**Comment by helpmefindaname** [comment]
Some learnings I had from looking at the warnings:

* The dataloader might use more processes than available, which would lead to slow-downs, I implemented a clamping to the maximum usable cpus, hence low resource usage is possible too (likely only interesting for the CI-CD part)
* `training.log` would not be closed, if the training failed, possibly disturbing specific processes
* using `trainer.resume` might warn about an existing `best-model.pt` and deletes it, IMO it should actually continue using the best model and the best score instead.

**Comment by helpmefindaname** [comment]
Learnings from fixing Mypy:

there were plenty (~800) mypy errors most of them were not relevant (type redefinition, like ```if type(base_path) is str: base_path: Path = Path(base_path)```, but I also noticed some crucial inconsistencies:
Over all embeddings and Models, the functions switched between `Sentence` and `DataType` without clear distinction which one is used. Theoretically, mypy would allow passing a `Image` to the `TextPairClassifier` which then would have failed at the `DocumentEmbedding` to overgo this issue, I made the base classes Generic (for any supertype of `DataType`) and let each model and embedding specify for what datatype they are built.

**Comment by helpmefindaname** [comment]
Also plenty of small typing errors are fixed like https://github.com/flairNLP/flair/issues/2506 and https://github.com/flairNLP/flair/issues/2505

**Comment by kieron-guinamard-privitar** [comment]
Out of interest, why was SentenceDataset renamed?
