### ISSUE TITLE
Relation Extraction: IndexError in the middle of training

### ISSUE THREAD

**Issue by ivankrstev7** [flairNLP/flair#2541]
Hi,

I am using the new Relation Extraction model (on custom data) and try to compare it with SpaCy's RE component. Training was going fine until the 39th epoch, when `IndexError: list index out of range` showed up. 

![image](https://user-images.githubusercontent.com/48191509/144832529-a89f32fa-1822-468f-a18a-596a2e7f06a1.png)

If there was a problem with the dataset, shouldn't this error occur earlier in the training?

**Comment by whoisjones** [comment]
Hi @ivankrstev7, can you share your training script for further investigation?

**Comment by ivankrstev7** [comment]
@whoisjones sorry for the late reply
Here is my training script:

`label_dict = corpus.make_label_dictionary("relation")

    classifier = RelationExtractor(embeddings,
                                   label_dictionary=label_dict,
                                   entity_label_type="ner",
                                   label_type="relation",
                                   train_on_gold_pairs_only=True,
                                   )
    
    trainer = ModelTrainer(classifier, corpus)
    trainer.train(
        model_path,
        learning_rate=lr,
        mini_batch_size=16,
        mini_batch_chunk_size=4,  
        max_epochs=max_epochs,
        monitor_test=True,
        train_with_dev=False,
        embeddings_storage_mode='gpu',
        patience=2
    )`

And this is how I load the corpus:

` corpus = CoNLLUCorpus(data_folder=data_folder,
                        train_file='relations_train_conllu.txt',
                        dev_file='relations_dev_conllu.txt',
                        test_file='relations_test_conllu.txt',
                        token_annotation_fields = ["id", "form", "ner"])`

I managed to find a workaround and training works fine now, but every now and then I get something like this, although I do not have an empty sentence in my dataset:
![image](https://user-images.githubusercontent.com/48191509/146910977-bfe0e978-196c-4231-bb95-0300d6d0aab2.png)

Anyway, I just skip it.
