### ISSUE TITLE
Sentiment Analysis for non-english Texts

### ISSUE THREAD

**Issue by hadisd5** [flairNLP/flair#2542]
Is there a pre-trained German sentiment analyzer in flair?

I'm currently looking at a sentiment analysis task on text messages in German. The Flair library have a pretty powerful pre-trained model for English, but I can't find any comprehensive answer to whether it also contains a similar thing in German and also attempted exchanging

`flair.models.TextClassifier.load('en-sentiment')`

for

`flair.models.TextClassifier.load('de-sentiment')`

But unfortunately it didn't work. Is there a solution to this case?

**Comment by whoisjones** [comment]
hi @hadisd5, currently we do not provide a pretrained model for german sentiment analysis. However, we have a pretrained model for german offensive language based on GermEval 2018 data which you can use with `'de-offensive-language'`. Another option would be to train a model based on our tutorial with german sentiment data.
