### ISSUE TITLE
Language Model Parameters used . . ?

### ISSUE THREAD

**Issue by i4meta** [flairNLP/flair#2546]
Hello,

I was hoping to clarify some parameters mentioned in **Tutorial 9: "Training your own Flair Embeddings"** for performance comparison:

	1.  Model - Is the Tutorial referring to the following model in the parameters it mentions?

		news-forward-0.4.1.pt/news-backward-0.4.1.pt which is dated 2020-08-28 14:03 on the download server

	2.  GPU - You mention using a very powerful GPU . . . could you share which model with how much Memory?
	3.  Hidden Size  - Which size was used? 1024 or 2048?
	4.  Sequence Length  - Was the length 250?
	5.  Mini-batch - Was the size 100?
	6.  Nlayers - Was nlayers 1?
	7.  Epochs - How many epochs did it run?

Best Regards,

Christopher

**Comment by whoisjones** [comment]
hi @i4meta, check out section 3.2. in the respective paper: https://alanakbik.github.io/papers/coling2018.pdf.
Regarding GPUs, you might wanna google it, NVIDIA Tesla or GeForce RTX are a good reference.

**Comment by i4meta** [comment]
Hi @whoisjones,
Thanks for pointing the paper out - very helpful.
As to the GPU, I was hoping to size out the Ram needed (and CUDA score) - unfortunately, Tesla or GeForce RTX each come in a range difference sizes. So even a guess would be welcome =)
