### ISSUE TITLE
Privacy of data

### ISSUE THREAD

**Issue by Sharing-Sam-Work** [flairNLP/flair#2549]
Hello,
I am currently looking into using Flair for a project involving private data. 
I wanted to know if I should take any steps regarding the use of Flair in that regards. 
For instance, ensuring that instantiating a corpus (column corpus in my case) object or using a model is done locally. 
Is it already the default behavior?

Thanks!

**Comment by alanakbik** [comment]
Hello @Sharing-Sam-Work Flair does not upload anything at the moment, so if you instantiate a corpus that would be local. Flair does download resources though, for instance models from our servers or from the hugginface hub.

**Comment by Sharing-Sam-Work** [comment]
Thanks!

**Comment by Sharing-Sam-Work** [comment]
Thanks!
