### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by Astudnew** [flairNLP/flair#2551]
Hello

I want to train the entire dataset(train file) without split it to dev and test and 
to train the entire train file  I used "corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.dat',sample_missing_splits=False, autofind_splits=False"
.
.
.
.
in training I used :
"trainer: ModelTrainer = ModelTrainer(tagger,corpus)

trainer.train('resources/taggers/example-pos',
               learning_rate=0.1,
              train_with_dev=False,
             
              embeddings_storage_mode = 'gpu',
              mini_batch_chunk_size=32, # set this if you get OOM errors
              max_epochs=150, # very few epochs of fine-tuning
        
             # patience = 3
              )

plotter = Plotter()
But after one epoch, I get this error:
--------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-14-c5216f0764b3> in <module>
     12               embeddings_storage_mode = 'gpu',
     13               mini_batch_chunk_size=32, # set this if you get OOM errors
---> 14               max_epochs=150, # very few epochs of fine-tuning
     15               #shuffle=False,
     16               #train_with_test = True,

/opt/conda/lib/python3.7/site-packages/flair/trainers/trainer.py in train(self, base_path, learning_rate, mini_batch_size, mini_batch_chunk_size, max_epochs, train_with_dev, train_with_test, monitor_train, monitor_test, main_evaluation_metric, scheduler, anneal_factor, patience, min_learning_rate, initial_extra_patience, optimizer, cycle_momentum, warmup_fraction, embeddings_storage_mode, checkpoint, save_final_model, anneal_with_restarts, anneal_with_prestarts, anneal_against_dev_loss, batch_growth_annealing, shuffle, param_selection_mode, write_weights, num_workers, sampler, use_amp, amp_opt_level, eval_on_train_fraction, eval_on_train_shuffle, save_model_each_k_epochs, tensorboard_comment, use_swa, use_final_model_for_eval, gold_label_dictionary_for_eval, create_file_logs, create_loss_file, epoch, use_tensorboard, tensorboard_log_dir, metrics_for_tensorboard, optimizer_state_dict, scheduler_state_dict, save_optimizer_state, **kwargs)
    630                 # default mode: anneal against dev score
    631                 if not train_with_dev and not anneal_against_dev_loss:
--> 632                     if dev_score > best_validation_score:
    633                         current_epoch_has_best_model_so_far = True
    634                         best_validation_score = dev_score

UnboundLocalError: local variable 'dev_score' referenced before assignment

**Comment by cpoyatos1** [comment]
It's probably a bug in version `> 0.9`: [v0.8...v0.9 flair/trainers/trainer.py line 593](https://github.com/flairNLP/flair/compare/v0.8...v0.9#diff-0655ce7b41d0c6b779de071cbaadc7df32d2a11025203bfd2c188cf6f904fd6dR593)

`train_with_dev` is `False` by default, but `dev_score` seems to be assigned only if [`train_with_dev` is `True`](https://github.com/flairNLP/flair/compare/v0.8...v0.9#diff-0655ce7b41d0c6b779de071cbaadc7df32d2a11025203bfd2c188cf6f904fd6dR544).

**Comment by Phd-Student2018** [comment]
> It's probably a bug in version `> 0.9`: [v0.8...v0.9 flair/trainers/trainer.py line 593](https://github.com/flairNLP/flair/compare/v0.8...v0.9#diff-0655ce7b41d0c6b779de071cbaadc7df32d2a11025203bfd2c188cf6f904fd6dR593)
> 
> `train_with_dev` is `False` by default, but `dev_score` seems to be assigned only if [`train_with_dev` is `True`](https://github.com/flairNLP/flair/compare/v0.8...v0.9#diff-0655ce7b41d0c6b779de071cbaadc7df32d2a11025203bfd2c188cf6f904fd6dR544).
> 
> Version `0.8` works for me.

I work on Kaggle how I can install flair version 8?? also, should I write " train_with_dev=True," in trainer >

**Comment by Phd-Student2018** [comment]
> It's probably a bug in version `> 0.9`: [v0.8...v0.9 flair/trainers/trainer.py line 593](https://github.com/flairNLP/flair/compare/v0.8...v0.9#diff-0655ce7b41d0c6b779de071cbaadc7df32d2a11025203bfd2c188cf6f904fd6dR593)
> 
> `train_with_dev` is `False` by default, but `dev_score` seems to be assigned only if [`train_with_dev` is `True`](https://github.com/flairNLP/flair/compare/v0.8...v0.9#diff-0655ce7b41d0c6b779de071cbaadc7df32d2a11025203bfd2c188cf6f904fd6dR544).
> 
> Version `0.8` works for me.

Thanks for reply, the training work with flair v08 but I got error it testing part with this code: 
tagger: SequenceTagger = SequenceTagger.load('resources/taggers/example-pos/best-model.pt')
result = tagger.evaluate(corpus_test.test, gold_label_type='ner', mini_batch_size=32, out_path=f"predictions.txt")
print(result)
I got this error:
--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-21-a6b4b5ec7b78> in <module>
      6 # run evaluation procedure
      7 # run evaluation procedure
----> 8 result = tagger.evaluate(corpus_test.test, gold_label_type='ner', mini_batch_size=32, out_path=f"predictions.txt")
      9 print(result)
     10 #result, score = tagger.evaluate(corpus_test.test, mini_batch_size=1, out_path=f"predictions.txt")

TypeError: evaluate() got an unexpected keyword argument 'gold_label_type'
