### ISSUE TITLE
How to get ner type tags?

### ISSUE THREAD

**Issue by Idomingog** [flairNLP/flair#2552]
I'm working to use Flair like a external recognizer, and I need to find how to get the NER type tags like "PER", "LOC", MISC", ORG".

When I look in the tag_dictionary, I get the detected tags and I haven't find any method that give me NER type tags in return. 

Thanks for your help.

model = SequenceTagger.load("flair/ner-spanish-large")
model.tag_dictionary.get_items()
['<unk>',
 'O',
 'S-LOC',
 'S-ORG',
 'B-PER',
 'I-PER',
 'E-PER',
 'S-MISC',
 'B-ORG',
 'E-ORG',
 'S-PER',
 'I-ORG',
 'B-LOC',
 'E-LOC',
 'B-MISC',
 'E-MISC',
 'I-MISC',
 'I-LOC',
 '<START>',
 '<STOP>']

**Comment by whoisjones** [comment]
hi @Idomingog, do you need the annotated sentence without start and stop information or do you need the tag dictionaries without the start and stop information? So the plain dictionary?

**Comment by Idomingog** [comment]
I need to get supported entities in order to select what entities are identified.

For example, if I would like to identify only PER entity and do not identify LOC identities.
I know I can have the E-LOC, or S-LOC, after the identified word, and with get_spans('ner'), I have the generic tags.

model = SequenceTagger.load("flair/ner-spanish-large")
sentence = Sentence('George Washington fue a Washington.')
model.predict(sentence)
print(sentence.to_tagged_string())
print(sentence.get_spans('ner'))

George <B-PER> Washington <E-PER> fue a Washington <S-ORG> .
[<PER-span (1,2): "George Washington">, <ORG-span (5): "Washington">]

But I try to have the texto only with "PER" info. In fact I would like to know if it is possible to pass this parameter to Flair.
I don't know if it is possible to do it.

Thanks for your help in advance.

**Comment by MichSteczko** [comment]
@Idomingog try this:
`my_ents = [<PER-span (1,2): "George Washington">, <ORG-span (5): "Washington">]`
`[ent.text for ent in my_ents if  entity.tag == 'PER' ]`
For future problems, please use `help()` function to see methods on the specific object.

**Comment by Idomingog** [comment]
Thanks for your help, But clearly I didn't explain my problem correctly. 

What are you propousing is a filter after the detecction, not a way to pass a parameter to flair with the list of entities are needed to detect. 

In any case, I apreciate you time to check on it.
