### ISSUE TITLE
Error :module 'flair' has no attribute 'nn'

### ISSUE THREAD

**Issue by Astudnew** [flairNLP/flair#2557]
I'm working on kaggel and  flair works fine but suddenly today I got this error " "AttributeError: module 'flair' has no attribute 'nn'
 " with the following  :

from flair.data import Sentence
from flair.embeddings import FlairEmbeddings, TransformerWordEmbeddings

from flair.data import Corpus
from flair.datasets import ColumnCorpus
from flair.embeddings import TransformerWordEmbeddings, TokenEmbeddings, StackedEmbeddings, BertEmbeddings, CharacterEmbeddings, BytePairEmbeddings, WordEmbeddings
#from flair.visual.training_curves import Plotter
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer
from typing import List
from torch.optim.adam import Adam
import sys
import flair, torch
flair.set_seed(42)

**Comment by whoisjones** [comment]
hi @Phd-Student2018, can you provide more information - which flair and python version you are using? imports work for me

**Comment by Phd-Student2018** [comment]
Thanks for your reply
It works today.!!!!!!!!!!!!!!!!
 I work on Kaggle and I use this command " !pip install Flair" ==> this is installing the last version of Flair??
the python version is python3.9

**Comment by ergodiclife** [comment]
I'm also having this issue on Google Colab with:

- Python `3.7.13`
- Flair `0.11.3`

I get `AttributeError: module 'flair' has no attribute 'nn'` when I try to import `SequenceTagger` from `flair.models`.

**Comment by despallier** [comment]
I also get the error : AttributeError: module 'flair' has no attribute 'nn' when I try to import SequenceTagger from flair.models.
Python 3.10.4, Flair 0.11.3

As I had problems installing flair , I installed it '- pip install flair --no-deps' and then installed all other packages 
- pip install : torch , transformers, deprecated, segtok, ftfy, conlu, gdown, gensim, bpemb, pptree
