### ISSUE TITLE
Larger NER is giving 2 different results for same text

### ISSUE THREAD

**Issue by UdiBhaskar** [flairNLP/flair#2566]
**Describe the bug**

If we give only one sentence("Amazon settles with fired tech workers who criticized company"), it was predicting Amazon as ORG. If we give the batch input( ["Amazon settles with fired tech workers who criticized company", "I am working at Google"]), it was predictiong amazon as LOC.

**To Reproduce**
```
from flair.data import Sentence
from flair.models import SequenceTagger
tagger = SequenceTagger.load("flair/ner-english-large")
basic_text1 = "Amazon settles with fired tech workers who criticized company"
print('With only one sentence -->')
sent1 = Sentence(basic_text1)
tagger.predict(sent1)
print(sent1.get_spans('ner'))
basic_text1 = "Amazon settles with fired tech workers who criticized company"
basic_text2 = "I am working at Google"
print()
print('With 2 sents sentence -->')
sents = [Sentence(text) for text in [basic_text1, basic_text2]]
tagger.predict(sents)
print(sents[0].get_spans('ner'))
print(sents[1].get_spans('ner'))
```

```
With only one sentence -->
[<ORG-span (1): "Amazon">]

With 2 sents sentence -->
[<LOC-span (1): "Amazon">]
[<ORG-span (5): "Google">]
```

**Expected behavior**
In the both cases, amazon has to be ORG

**Environment (please complete the following information):**
 - OS: Linux
 - Version : 0.10

**Comment by SnichOne** [comment]
If you pass a list of sentences this way to the `ner-large` model, each sentence will be enriched by information from previous and next sentence. This happens to any model with `TransformerWordEmbeddings` (not only pretrained `ner-large`).

**Comment by UdiBhaskar** [comment]
@SnichOne is there any way to do inference in batchmode other than this?

**Comment by SnichOne** [comment]
@UdiBhaskar, this should work with your example
```python
for sent in sents:
    setattr(sent, "_previous_sentence", None)
    setattr(sent, "_next_sentence", None)
tagger.predict(sents)
```

**Comment by SnichOne** [comment]
I am not sure why `.predict` behaves like that, and why it does not support batch prediction of non related sentences without clutches like the one above.

**Comment by UdiBhaskar** [comment]
@SnichOne it worked after that. Thanks.
