### ISSUE TITLE
GPU memory persists after del and empty_cache

### ISSUE THREAD

**Issue by waynemystir** [flairNLP/flair#2569]
Hi, I am unable to fully remove the flair model (or data?) from the GPU. Here is my code:

```
flair.device = torch.device("cuda")
flair_tagger = SequenceTagger.load("flair/ner-english-ontonotes-large")
sentence = Sentence(txt)
flair_tagger.predict(sentence)
del flair_tagger
torch.cuda.empty_cache()
```

The last two lines significantly reduce the amount the GPU memory used by flair. But they don't completely remove flair from GPU memory. Using nvidia-smi, I can see that about 1.1GB of flair stuff remains in GPU memory.

Am I doing something wrong? What are the correct steps to completely remove flair from GPU memory?

Thank you.

**Comment by whoisjones** [comment]
hi @waynemystir, are you sure that nothing else is running on the GPU? Have tried the following which is completely removing all things on GPU memory:

```
import flair

from flair.models import SequenceTagger
from flair.data import Sentence
import torch

device = 3
flair.device = f"cuda:{device}"

def main():
    txt = "Washington was a president in United States."
    print(current_memory())
    flair_tagger = SequenceTagger.load("flair/ner-english-ontonotes-large")
    print(current_memory())
    sentence = Sentence(txt)
    print(current_memory())
    flair_tagger.predict(sentence)
    print(current_memory())
    del flair_tagger
    print(current_memory())
    torch.cuda.empty_cache()
    print(current_memory())

def current_memory():
    return torch.cuda.memory_allocated(device) / 1024 / 1024 / 1024

if __name__ == "__main__":
    main()
```

**Comment by waynemystir** [comment]
Thank you @whoisjones. I ran this and the last two calls to `current_memory()` show zero torch usage. But when I put a breakpoint after the last call to `current_memory()` and then look at `nvidia-smi`, I see that python is still taking up 1.1GB of GPU memory. From this simple program, I cannot imagine anything besides flair or torch is responsible for that 1.1GB.

Do you see something similar? Is it possible that the remaining 1.1GB is comprised of some non-flair, non-torch python objects?

**Comment by whoisjones** [comment]
Then something is probably still referenced which is why it is not collected by the garbage collector. I'll check as well.

**Comment by helpmefindaname** [comment]
This is standard behaivour of pytorch, see https://github.com/pytorch/pytorch/issues/12873#issuecomment-482916237

**Comment by waynemystir** [comment]
Great, thank you @helpmefindaname 

And thanks again @whoisjones 

Much appreciate!!
