### ISSUE TITLE
FLair

### ISSUE THREAD

**Issue by Phd-Student2018** [flairNLP/flair#2570]
what is the difference between Flair embedding and BERT? what is the benefit from combining Falir embedding and BERT for tasks such as NER and POS?
Thnaks

**Comment by whoisjones** [comment]
You might wanna read the papers. But in general tasks such as sequence labeling benefit from character-level information (flair) and from large, pretrained models (BERT).

**Comment by Phd-Student2018** [comment]
Thanks for your replay
Please ? Can you suggest papers that concateing bert and flair embedding
for sequence labelling tasks

**Comment by lukasgarbas** [comment]
Here is ACE: https://arxiv.org/abs/2010.05006 where they combined multiple embedding types for sequence labeling (multilingual BERT and Flair are also in the mix). I can't find any papers where only flair and bert are combined. From my own experiments, I would suggest trying two setups:

1. Bert (feature-based), flair, glove.
2. Bert (fine-tuned), flair. A transformer is first fine-tuned and only then combined with other embeddings.

**Comment by Phd-Student2018** [comment]
Thank you very much
But how we can fine tune BERT and then concatenateing it  with flair
embedding?

**Comment by whoisjones** [comment]
Check out our `StackedEmbeddings`
