### ISSUE TITLE
Upgrade Segtok to Syntok (Segtok 2.0) . . ?

### ISSUE THREAD

**Issue by i4meta** [flairNLP/flair#2587]
Curious if Flair will be upgrading **Segtok** to **Syntok**, given the author of both libraries considers Syntok to be the equivalent of **Segtok 2.0**.

Please see - https://github.com/fnl/syntok

**Comment by alanakbik** [comment]
God point about syntok, but last time I tried (see https://github.com/flairNLP/flair/issues/876#issuecomment-511868122) it was giving some bad results for simple sentences. That was quite a while ago though so maybe it improved in the meantime?
