### ISSUE TITLE
Training with `SequenceTagger(beta=2.0)` does not seem to use f2 but always f1

### ISSUE THREAD

**Issue by ciaochiaociao** [flairNLP/flair#2588]
I have tried to use beta=2 to adopt f2, which should allow me to select model using f2 score. But from the source code, it seems to always use f1 (either micro or macro) as the `main_evaluation_metric`.

After taking a look at your source code, I found it is because the calling of the sklearn API `classification_report()` from your `Classifier.evaluate()` does not allow passing argument to propagate to its low-level function `precision_recall_fscore_support()`'s `beta` argument. 

see https://github.com/flairNLP/flair/blob/master/flair/nn/model.py#L354-L359

**To Reproduce**
```
...
tagger: SequenceTagger = SequenceTagger(...beta=2.0,...)

# initialize trainer
trainer: ModelTrainer = ModelTrainer(tagger, corpus)

trainer.train(output_dir)
```
At the end of the training, it shows

By class:
              precision    recall  f1-score   support

           O     0.9617    0.9888    0.9750     21651
.....

without using beta=2.0

**Comment by ciaochiaociao** [comment]
Another note: 
`TextClassifier` actually does use `beta` since it calls `fbeta_score()` from `sklearn` directly so as to avoid this issue, where in `SequenceTagger` I believe you had followed the same way before, but at some point you decided to use `classification_report()` function instead

**Comment by ciaochiaociao** [comment]
https://github.com/flairNLP/flair/blob/master/flair/nn/model.py#L354-L359

**Comment by alanakbik** [comment]
Are you working on master branch or the last release? There is a refactoring underway to refactor out the `beta` parameter from the models, since this parameter more properly belongs to the `ModelTrainer` (the trainer decides how to train/evaluate, the model should just know its own model parameters).

**Comment by ciaochiaociao** [comment]
> Are you working on master branch or the last release? There is a refactoring underway to refactor out the `beta` parameter from the models, since this parameter more properly belongs to the `ModelTrainer` (the trainer decides how to train/evaluate, the model should just know its own model parameters).

I am working on the latest release: v0.10.
