### ISSUE TITLE
What is the value of label_type variable  for binary classification?

### ISSUE THREAD

**Issue by azizcu** [flairNLP/flair#2589]
label_type="binary" or
label_type="class"?
or what?

**Comment by helpmefindaname** [comment]
it is whatever you dataset is mapped to (which you can decide that yourself)

if you load your data like this:
```
corpus = CSVClassificationCorpus("my_path", column_name_map={0:"text", 1: "label"}, label_type="my_fancy_label_type")
```
You just have to ensure that you create a classifier with the argument `label_type="my_fancy_label_type"`.
