### ISSUE TITLE
zero shot classification when using TARSClassifier bug

### ISSUE THREAD

**Issue by yananchen1989** [flairNLP/flair#2595]
```
from flair.models import TARSClassifier
from flair.data import Sentence

# 1. Load our pre-trained TARS model for English
tars = TARSClassifier.load('tars-base')
```

Error message:

> ImportError                               Traceback (most recent call last)
> <ipython-input-1-aab449690509> in <module>
> ----> 1 from flair.models import TARSClassifier
>       2 from flair.data import Sentence
>       3
>       4 # 1. Load our pre-trained TARS model for English
>       5 tars = TARSClassifier.load('tars-base')
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/__init__.py in <module>
>      18
>      19 from . import data
> ---> 20 from . import models
>      21 from . import visual
>      22 from . import trainers
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/models/__init__.py in <module>
> ----> 1 from .sequence_tagger_model import SequenceTagger, MultiTagger
>       2 from .language_model import LanguageModel
>       3 from .text_classification_model import TextClassifier
>       4 from .pairwise_classification_model import TextPairClassifier
>       5 from .relation_extractor_model import RelationExtractor
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/models/sequence_tagger_model.py in <module>
>      18 from flair.data import Dictionary, Sentence, Label
>      19 from flair.datasets import SentenceDataset, DataLoader
> ---> 20 from flair.embeddings import TokenEmbeddings, StackedEmbeddings, Embeddings
>      21 from flair.file_utils import cached_path, unzip_file
>      22 from flair.training_utils import store_embeddings
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/embeddings/__init__.py in <module>
>       4
>       5 # Expose token embedding classes
> ----> 6 from .token import TokenEmbeddings
>       7 from .token import StackedEmbeddings
>       8 from .token import WordEmbeddings
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/embeddings/token.py in <module>
>      15 from gensim.models import KeyedVectors
>      16 from torch import nn
> ---> 17 from transformers import AutoTokenizer, AutoConfig, AutoModel, CONFIG_MAPPING, PreTrainedTokenizer, XLNetModel, \
>      18     TransfoXLModel
>      19
> 
> ImportError: cannot import name 'AutoModel' from 'transformers' (unknown location)

transformers version: 4.8.2
flair version: 0.10

**Comment by whoisjones** [comment]
can't reproduce this with the given information. can you do `conda list` or resp. `conda list -n [venv]` and confirm that you have the packages installed?

**Comment by yananchen1989** [comment]
@whoisjones Hi, thanks for your feedback.

I upgrade the huggingface transformers from 4.8.2 to 4.15.0, this error disappears.
