### ISSUE TITLE
Can not load .pt model even when already download it .

### ISSUE THREAD

**Issue by yananchen1989** [flairNLP/flair#2596]
My server can not fetch models directly from huggingface transformers and flair. Therefore I scp the pt model from my mac to the server, stored at /root/.flair/models/tars-base-v8.pt.

Then I excute:
```
from flair.models import TARSClassifier
from flair.data import Sentence
tars = TARSClassifier.load('tars-base')
```
However, It still can not load the model. From the error message, I guess that it tries to load a tokenizer from transformers. As my server can not fetch model from transformers, it failed.

> 2022-01-16 18:27:59,314 loading file /root/.flair/models/tars-base-v8.pt
> ---------------------------------------------------------------------------
> ConnectionRefusedError                    Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py in _new_conn(self)
>     168         try:
> --> 169             conn = connection.create_connection(
>     170                 (self._dns_host, self.port), self.timeout, **extra_kw
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
>      95     if err is not None:
> ---> 96         raise err
>      97
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
>      85                 sock.bind(source_address)
> ---> 86             sock.connect(sa)
>      87             return sock
> 
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> NewConnectionError                        Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     698             # Make the request on the httplib connection object.
> --> 699             httplib_response = self._make_request(
>     700                 conn,
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     381         try:
> --> 382             self._validate_conn(conn)
>     383         except (SocketTimeout, BaseSSLError) as e:
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
>    1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
> -> 1010             conn.connect()
>    1011
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py in connect(self)
>     352         # Add certificate verification
> --> 353         conn = self._new_conn()
>     354         hostname = self.host
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py in _new_conn(self)
>     180         except SocketError as e:
> --> 181             raise NewConnectionError(
>     182                 self, "Failed to establish a new connection: %s" % e
> 
> NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7febbb113100>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> MaxRetryError                             Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     438             if not chunked:
> --> 439                 resp = conn.urlopen(
>     440                     method=request.method,
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     754
> --> 755             retries = retries.increment(
>     756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
>     573         if new_retry.is_exhausted():
> --> 574             raise MaxRetryError(_pool, url, error or ResponseError(cause))
>     575
> 
> MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7febbb113100>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> ConnectionError                           Traceback (most recent call last)
> <ipython-input-7-4d69123e8cab> in <module>
> ----> 1 tars = TARSClassifier.load('tars-base')
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/nn/model.py in load(cls, model)
>     131             # see https://github.com/zalandoresearch/flair/issues/351
>     132             f = file_utils.load_big_file(str(model_file))
> --> 133             state = torch.load(f, map_location='cpu')
>     134
>     135         model = cls._init_model_with_state_dict(state)
> 
> ~/anaconda3/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
>     605                     opened_file.seek(orig_position)
>     606                     return torch.jit.load(opened_file)
> --> 607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>     608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>     609
> 
> ~/anaconda3/lib/python3.8/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
>     880     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
>     881     unpickler.persistent_load = persistent_load
> --> 882     result = unpickler.load()
>     883
>     884     torch._utils._validate_loaded_sparse_tensors()
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/embeddings/document.py in __setstate__(self, d)
>     246
>     247             # re-initialize transformer word embeddings with constructor arguments
> --> 248             embedding = TransformerDocumentEmbeddings(
>     249                 model=self.__dict__['base_model_name'],
>     250                 fine_tune=self.__dict__['fine_tune'],
> 
> ~/anaconda3/lib/python3.8/site-packages/flair/embeddings/document.py in __init__(self, model, fine_tune, layers, layer_mean, pooling, **kwargs)
>      67
>      68         # load tokenizer and transformer model
> ---> 69         self.tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(model, **kwargs)
>      70         if self.tokenizer.model_max_length > 1000000000:
>      71             self.tokenizer.model_max_length = 512
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
>     548             tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
>     549             if tokenizer_class_fast and (use_fast or tokenizer_class_py is None):
> --> 550                 return tokenizer_class_fast.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
>     551             else:
>     552                 if tokenizer_class_py is not None:
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in from_pretrained(cls, pretrained_model_name_or_path, *init_inputs, **kwargs)
>    1652         else:
>    1653             # At this point pretrained_model_name_or_path is either a directory or a model identifier name
> -> 1654             fast_tokenizer_file = get_fast_tokenizer_file(
>    1655                 pretrained_model_name_or_path,
>    1656                 revision=revision,
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in get_fast_tokenizer_file(path_or_repo, revision, use_auth_token, local_files_only)
>    3484     """
>    3485     # Inspect all files from the repo/folder.
> -> 3486     all_files = get_list_of_files(
>    3487         path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
>    3488     )
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/file_utils.py in get_list_of_files(path_or_repo, revision, use_auth_token, local_files_only)
>    2101     else:
>    2102         token = None
> -> 2103     return list_repo_files(path_or_repo, revision=revision, token=token)
>    2104
>    2105
> 
> ~/anaconda3/lib/python3.8/site-packages/huggingface_hub/hf_api.py in list_repo_files(self, repo_id, revision, repo_type, token, timeout)
>     882         """
>     883         if repo_type is None:
> --> 884             info = self.model_info(
>     885                 repo_id, revision=revision, token=token, timeout=timeout
>     886             )
> 
> ~/anaconda3/lib/python3.8/site-packages/huggingface_hub/hf_api.py in model_info(self, repo_id, revision, token, timeout)
>     865         )
>     866         headers = {"authorization": f"Bearer {token}"} if token is not None else None
> --> 867         r = requests.get(path, headers=headers, timeout=timeout)
>     868         r.raise_for_status()
>     869         d = r.json()
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/api.py in get(url, params, **kwargs)
>      74
>      75     kwargs.setdefault('allow_redirects', True)
> ---> 76     return request('get', url, params=params, **kwargs)
>      77
>      78
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/api.py in request(method, url, **kwargs)
>      59     # cases, and look like a memory leak in others.
>      60     with sessions.Session() as session:
> ---> 61         return session.request(method=method, url=url, **kwargs)
>      62
>      63
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     540         }
>     541         send_kwargs.update(settings)
> --> 542         resp = self.send(prep, **send_kwargs)
>     543
>     544         return resp
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/sessions.py in send(self, request, **kwargs)
>     653
>     654         # Send the request
> --> 655         r = adapter.send(request, **kwargs)
>     656
>     657         # Total elapsed time of the request (approximately)
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     514                 raise SSLError(e, request=request)
>     515
> --> 516             raise ConnectionError(e, request=request)
>     517
>     518         except ClosedPoolError as e:
> 
> ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7febbb113100>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 

Transformers ver: 4.15.0
flair ver: 0.10

Any other method to do this on my server?
Thanks.

**Comment by Benedikt-Fuchs-Crayon** [comment]
Hello @yananchen1989 I recently updated the transformers logic, can you try installing the master branch `git+ssh://git@github.com:flairNLP/flair.git` and see if that solves your problem?

**Comment by yananchen1989** [comment]
> Hello @yananchen1989 I recently updated the transformers logic, can you try installing the master branch `git+ssh://git@github.com:flairNLP/flair.git` and see if that solves your problem?

Thanks.

I use `pip install -e . ` to install the updated repo of flair.

> Installing collected packages: pptree, flair
>   Attempting uninstall: flair
>     Found existing installation: flair 0.10
>     Uninstalling flair-0.10:
>       Successfully uninstalled flair-0.10
>   Running setup.py develop for flair
> Successfully installed flair pptree-3.1


The error is the same:

> ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fad0fd210a0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by yananchen1989** [comment]
@Benedikt-Fuchs-Crayon Usually, when I use models of transformers huggingface, I also scp them from local mac to server.
and load it locally on the server,
like this:
```
from transformers import GPT2Tokenizer, GPT2LMHeadModel 
tokenizer_gpt2 = GPT2Tokenizer.from_pretrained('gpt2', cache_dir="./cache", local_files_only=True)
```

**Comment by yananchen1989** [comment]
![image](https://user-images.githubusercontent.com/26405281/149833581-3311f8e0-0892-4f74-9437-b3be0c208df5.png)

**Comment by yananchen1989** [comment]
I think the argument `local_files_only=True` is critical when loading local files in `from_pretrained`
as it prevents the server to try to fetch models remotely.

**Comment by Benedikt-Fuchs-Crayon** [comment]
I'm sorry, I told you incomplete instructions.

The new behavior stores more information when you save a model, however it cannot infer information without internet in the old models.

```
from flair.models import TARSClassifier

def download_from_internet():
    tars = TARSClassifier.load("tars-base")
    tars.save("my-tars.pt")

def load_without_internet():
   tars = TARSClassifier.load("my-tars.pt")
```
The methods above should do the trick.

**Comment by yananchen1989** [comment]
> 

@Benedikt-Fuchs-Crayon Hi Benedikt, thanks.

I try to reload the following the code `tars = TARSClassifier.load("my-tars.pt")`
on my server.

but there comes the error message:

> ---------------------------------------------------------------------------
> ConnectionRefusedError                    Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py in _new_conn(self)
>     168         try:
> --> 169             conn = connection.create_connection(
>     170                 (self._dns_host, self.port), self.timeout, **extra_kw
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
>      95     if err is not None:
> ---> 96         raise err
>      97
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
>      85                 sock.bind(source_address)
> ---> 86             sock.connect(sa)
>      87             return sock
> 
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> NewConnectionError                        Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     698             # Make the request on the httplib connection object.
> --> 699             httplib_response = self._make_request(
>     700                 conn,
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
>     381         try:
> --> 382             self._validate_conn(conn)
>     383         except (SocketTimeout, BaseSSLError) as e:
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
>    1009         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
> -> 1010             conn.connect()
>    1011
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py in connect(self)
>     352         # Add certificate verification
> --> 353         conn = self._new_conn()
>     354         hostname = self.host
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connection.py in _new_conn(self)
>     180         except SocketError as e:
> --> 181             raise NewConnectionError(
>     182                 self, "Failed to establish a new connection: %s" % e
> 
> NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f0ab1954d00>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> MaxRetryError                             Traceback (most recent call last)
> ~/anaconda3/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     438             if not chunked:
> --> 439                 resp = conn.urlopen(
>     440                     method=request.method,
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
>     754
> --> 755             retries = retries.increment(
>     756                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
> 
> ~/anaconda3/lib/python3.8/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
>     573         if new_retry.is_exhausted():
> --> 574             raise MaxRetryError(_pool, url, error or ResponseError(cause))
>     575
> 
> MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0ab1954d00>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> ConnectionError                           Traceback (most recent call last)
> <ipython-input-2-94151fedc474> in <module>
> ----> 1 tars = TARSClassifier.load("my-tars.pt")
> 
> /home/yanan/flair/flair/nn/model.py in load(cls, model_path)
>     140             # see https://github.com/zalandoresearch/flair/issues/351
>     141             f = file_utils.load_big_file(str(model_file))
> --> 142             state = torch.load(f, map_location="cpu")
>     143
>     144         model = cls._init_model_with_state_dict(state)
> 
> ~/anaconda3/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
>     605                     opened_file.seek(orig_position)
>     606                     return torch.jit.load(opened_file)
> --> 607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>     608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>     609
> 
> ~/anaconda3/lib/python3.8/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
>     880     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
>     881     unpickler.persistent_load = persistent_load
> --> 882     result = unpickler.load()
>     883
>     884     torch._utils._validate_loaded_sparse_tensors()
> 
> /home/yanan/flair/flair/embeddings/base.py in __setstate__(self, state)
>     443             config = config_class.from_dict(config_state_dict)
>     444
> --> 445         embedding = self.create_from_state(saved_config=config, **state)
>     446
>     447         # copy values from new embedding
> 
> /home/yanan/flair/flair/embeddings/document.py in create_from_state(cls, **state)
>      56         # this parameter is fixed
>      57         del state["is_document_embedding"]
> ---> 58         return cls(**state)
>      59
>      60
> 
> /home/yanan/flair/flair/embeddings/document.py in __init__(self, model, layers, layer_mean, is_token_embedding, **kwargs)
>      42         :param fine_tune: If True, allows transformers to be fine-tuned during training
>      43         """
> ---> 44         TransformerEmbedding.__init__(
>      45             self,
>      46             model=model,
> 
> /home/yanan/flair/flair/embeddings/base.py in __init__(self, model, fine_tune, layers, layer_mean, subtoken_pooling, cls_pooling, is_token_embedding, is_document_embedding, allow_long_sentences, use_context, respect_document_boundaries, context_dropout, saved_config, tokenizer_data, name, **kwargs)
>     205         if tokenizer_data is None:
>     206             # load tokenizer and transformer model
> --> 207             self.tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(model, **kwargs)
>     208         else:
>     209             # load tokenizer from inmemory zip-file
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
>     486         if config_tokenizer_class is None:
>     487             if not isinstance(config, PretrainedConfig):
> --> 488                 config = AutoConfig.from_pretrained(
>     489                     pretrained_model_name_or_path, trust_remote_code=trust_remote_code, **kwargs
>     490                 )
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
>     580         kwargs["name_or_path"] = pretrained_model_name_or_path
>     581         trust_remote_code = kwargs.pop("trust_remote_code", False)
> --> 582         config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
>     583         if "auto_map" in config_dict and "AutoConfig" in config_dict["auto_map"]:
>     584             if not trust_remote_code:
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
>     550             config_file = pretrained_model_name_or_path
>     551         else:
> --> 552             configuration_file = get_configuration_file(
>     553                 pretrained_model_name_or_path,
>     554                 revision=revision,
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py in get_configuration_file(path_or_repo, revision, use_auth_token, local_files_only)
>     841     """
>     842     # Inspect all files from the repo/folder.
> --> 843     all_files = get_list_of_files(
>     844         path_or_repo, revision=revision, use_auth_token=use_auth_token, local_files_only=local_files_only
>     845     )
> 
> ~/anaconda3/lib/python3.8/site-packages/transformers/file_utils.py in get_list_of_files(path_or_repo, revision, use_auth_token, local_files_only)
>    2101     else:
>    2102         token = None
> -> 2103     return list_repo_files(path_or_repo, revision=revision, token=token)
>    2104
>    2105
> 
> ~/anaconda3/lib/python3.8/site-packages/huggingface_hub/hf_api.py in list_repo_files(self, repo_id, revision, repo_type, token, timeout)
>     882         """
>     883         if repo_type is None:
> --> 884             info = self.model_info(
>     885                 repo_id, revision=revision, token=token, timeout=timeout
>     886             )
> 
> ~/anaconda3/lib/python3.8/site-packages/huggingface_hub/hf_api.py in model_info(self, repo_id, revision, token, timeout)
>     865         )
>     866         headers = {"authorization": f"Bearer {token}"} if token is not None else None
> --> 867         r = requests.get(path, headers=headers, timeout=timeout)
>     868         r.raise_for_status()
>     869         d = r.json()
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/api.py in get(url, params, **kwargs)
>      74
>      75     kwargs.setdefault('allow_redirects', True)
> ---> 76     return request('get', url, params=params, **kwargs)
>      77
>      78
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/api.py in request(method, url, **kwargs)
>      59     # cases, and look like a memory leak in others.
>      60     with sessions.Session() as session:
> ---> 61         return session.request(method=method, url=url, **kwargs)
>      62
>      63
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
>     540         }
>     541         send_kwargs.update(settings)
> --> 542         resp = self.send(prep, **send_kwargs)
>     543
>     544         return resp
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/sessions.py in send(self, request, **kwargs)
>     653
>     654         # Send the request
> --> 655         r = adapter.send(request, **kwargs)
>     656
>     657         # Total elapsed time of the request (approximately)
> 
> ~/anaconda3/lib/python3.8/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
>     514                 raise SSLError(e, request=request)
>     515
> --> 516             raise ConnectionError(e, request=request)
>     517
>     518         except ClosedPoolError as e:
> 
> ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/bert-base-uncased (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0ab1954d00>: Failed to establish a new connection: [Errno 111] Connection refused'))



The versions of transformers and flair are the same both on my mac and the remote server.

**Comment by yananchen1989** [comment]
The saving part works fine on my mac. After this, I just scp it to the server.

```
    tars = TARSClassifier.load("tars-base")
    tars.save("my-tars.pt")
```

**Comment by helpmefindaname** [comment]
just to be sure, as you seem to have two environments: did you also use the master branch for downloading?

we see in the stack trace here, that it didn't find in memory data:
```
205 if tokenizer_data is None:
206 # load tokenizer and transformer model
--> 207 self.tokenizer: PreTrainedTokenizer = AutoTokenizer.from_pretrained(model, **kwargs)
208 else:
209 # load tokenizer from inmemory zip-file
```
I just tested loading again and verified that it did work for me.

if you already used the master branch for downloading, I'd like to get your model for debugging purpose

**Comment by yananchen1989** [comment]
Hi, I can not use the command: `pip install git+ssh://git@github.com:flairNLP/flair.git`

> Collecting git+ssh://****@github.com:flairNLP/flair.git
>   Cloning ssh://****@github.com:flairNLP/flair.git to /private/var/folders/dw/pnd1dfhx5z9frctm55wqfyhc0000gn/T/pip-req-build-zex7yhft
>   Running command git clone --filter=blob:none -q 'ssh://****@github.com:flairNLP/flair.git' /private/var/folders/dw/pnd1dfhx5z9frctm55wqfyhc0000gn/T/pip-req-build-zex7yhft
>   ssh: Could not resolve hostname github.com:flairNLP: nodename nor servname provided, or not known
>   fatal: Could not read from remote repository.
> 
>   Please make sure you have the correct access rights
>   and the repository exists.
> WARNING: Discarding git+ssh://****@github.com:flairNLP/flair.git. Command errored out with exit status 128: git clone --filter=blob:none -q 'ssh://****@github.com:flairNLP/flair.git' /private/var/folders/dw/pnd1dfhx5z9frctm55wqfyhc0000gn/T/pip-req-build-zex7yhft Check the logs for full command output.
> ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q 'ssh://****@github.com:flairNLP/flair.git' /private/var/folders/dw/pnd1dfhx5z9frctm55wqfyhc0000gn/T/pip-req-build-zex7yhft Check the logs for full command output.


Therefore, I git clone the repo of flair, it is on master branch.
then I excute `pip install -e .` in the flair folder. and it succeed: 
`Successfully installed flair-0.10 pptree-3.1`

Is that OK?

@Benedikt-Fuchs-Crayon

**Comment by yananchen1989** [comment]
@Benedikt-Fuchs-Crayon It works. with this installation on master branch.
Thanks a lot.

Will the tars classification automatic use GPU ? Or I need to assign GPU explicityly.

**Comment by yananchen1989** [comment]
@Benedikt-Fuchs-Crayon  It works. with this installation on master branch.
Thanks a lot.

By the way, I find that if the confidence score of all candidate labels are below 0.5, I guess, there will be no prediction of label.

My I ask how to return the full list of candidate labels, with their confidence scores ?

I just want to sort them according to the scores, and get the top 1 as the final prediction.
thanks.

**Comment by rishab-32** [comment]
@helpmefindaname @Benedikt-Fuchs-Crayon , with the new changes in master, I see `get_spans` for the Sentence object in data.py seems to be removed, any specific reason for change in functionality. And is there any new module added which can replicate the behavior of get_spans for sequence tagger sentence module?
