### ISSUE TITLE
TARS NER KeyError during Training

### ISSUE THREAD

**Issue by arda-vianai** [flairNLP/flair#2602]
Hi,
I am new to flair, but I have experience with NLP and NER. I can train a custom NER model with Sequence Tagger with a corpus I created which has custom NER labels.

When I try the same task with TarsTagger I get a KeyError for one of my custom labels. I also add the label name map to give you an idea about my labels. 

Please see the code below. I also upload the corpus files.
```
from flair.data import Corpus
from flair.datasets import ColumnCorpus
from flair.models import TARSTagger, FewshotClassifier
from flair.trainers import ModelTrainer

# label_name_map = {'SUPPLY_CHAIN_ISSUE': 'an entity that describes a problem about supply chains',
#                   'ECONOMIC_TERM': 'an entity that describes an economic term',
#                   'SUPPLIER': 'an entity that supplies a resource',
#                   'RESOURCE': 'an entity that is either a product, service, or a resource to complete a task',
#                   'ORGANIZATION': 'an entity that refers to an organization',
#                   'DATE_OR_TIME': 'an entity that mentions a date or a time',
#                   'ROOT_CAUSE':'an entity that describes the root cause of a problem',
#                   'PERSON':'an entity that refers to a person',
#                   'ALLEVIATES':'an action that describes an alleviating relationship',
#                   'CAUSES':'an action that describes a causing relationship',
#                   'SEVERES':'an action that describes a severing relationship',
#                   'WHERE':'an entity that describes the location of the action or resource',
#                   'CONSUMER':'an entity that describes the consumer of a resource',
#                   'HOW':'a phrase that describes how an action has happened',
#                   'MONETARY':'an entity that describes a monetary value',
#                   'PRODUCT':'an entity that refers to a person',
#                   'LOCATION':'an entity that refers to a location name'
#                   }
# define columns
columns = {0: 'text', 1: 'ner'}

# this is the folder in which train, test and dev files reside
data_folder = '/content/flair_ner_dataset'

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus = ColumnCorpus(data_folder, columns,
                              train_file='flair_ner_train.txt',
                              test_file='flair_ner_test.txt'
  #                            label_name_map=label_name_map
                      )

label_type = 'ner'

label_dict = corpus.make_label_dictionary(label_type)

#print(label_dict.get_items())

#init the TARS sequence tagger
tars_tagger_supply: FewshotClassifier() = TARSTagger(embeddings="bert-base-uncased",label_dictionary=label_dict, label_type=label_type, task_name="MY_NER_SUPPLY")




# train the model
trainer = ModelTrainer(tars_tagger_supply, corpus)

trainer.train(
    f'resources/taggers/few-shot-tagger',
    learning_rate=5e-6,
    mini_batch_size=2, # set this higher if you have a big GPU
    max_epochs=10,
    embeddings_storage_mode="none",
    weight_decay=0.,
)
```

The following is the output of the code block and the error I get: 

2022-01-20 14:55:09,202 Reading data from /content/flair_ner_dataset
2022-01-20 14:55:09,205 Train: /content/flair_ner_dataset/flair_ner_train.txt
2022-01-20 14:55:09,206 Dev: None
2022-01-20 14:55:09,206 Test: /content/flair_ner_dataset/flair_ner_test.txt
2022-01-20 14:55:09,338 Computing label dictionary. Progress:
100%|██████████| 212/212 [00:00<00:00, 7890.05it/s]2022-01-20 14:55:09,374 Corpus contains the labels: ner (#6330)
2022-01-20 14:55:09,375 Created (for label 'ner') Dictionary with 68 tags: <unk>, U-SUPPLIER, O, U-SUPPLY_CHAIN_ISSUE, B-RESOURCES, L-RESOURCES, U-ROOT_CAUSE, U-RESOURCES, B-PERSON, L-PERSON, B-ORGANIZATION, L-ORGANIZATION, B-SUPPLY_CHAIN_ISSUE, I-SUPPLY_CHAIN_ISSUE, L-SUPPLY_CHAIN_ISSUE, B-ALLEVIATES, L-ALLEVIATES, B-ROOT_CAUSE, I-ROOT_CAUSE, L-ROOT_CAUSE, U-ORGANIZATION, U-ECONOMIC_TERMS, B-ECONOMIC_TERMS, L-ECONOMIC_TERMS, I-ORGANIZATION, U-WHERE, U-PERSON, B-CAUSES, L-CAUSES, B-DATE_OR_TIME, I-DATE_OR_TIME, L-DATE_OR_TIME, B-SUPPLIER, L-SUPPLIER, U-AL
LEVIATES, U-SEVERES, U-DATE_OR_TIME, B-WHERE, I-WHERE, L-WHERE, U-CAUSES, I-RESOURCES, U-LOCATION, I-ECONOMIC_TERMS, U-CONSUMER, B-LOCATION, L-LOCATION, B-HOW, L-HOW, I-HOW

2022-01-20 14:55:21,713 ----------------------------------------------------------------------------------------------------
2022-01-20 14:55:21,
718 Model: "TARSTagger(
  (tars_model): SequenceTagger(
    (embeddings): TransformerWordEmbeddings(
      (model): BertModel(
        (embeddings): BertEmbeddings(
          (word_embeddings): Embedding(30522, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (token_type_embeddings): Embedding(2, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (encoder): BertEncoder(
          (layer): ModuleList(
            (0): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (1): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (2): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (3): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (4): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (5): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (6): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (7): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (8): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (9): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (10): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
            (11): BertLayer(
              (attention): BertAttention(
                (self): BertSelfAttention(
                  (query): Linear(in_features=768, out_features=768, bias=True)
                  (key): Linear(in_features=768, out_features=768, bias=True)
                  (value): Linear(in_features=768, out_features=768, bias=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
                (output): BertSelfOutput(
                  (dense): Linear(in_features=768, out_features=768, bias=True)
                  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                  (dropout): Dropout(p=0.1, inplace=False)
                )
              )
              (intermediate): BertIntermediate(
                (dense): Linear(in_features=768, out_features=3072, bias=True)
              )
              (output): BertOutput(
                (dense): Linear(in_features=3072, out_features=768, bias=True)
                (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
                (dropout): Dropout(p=0.1, inplace=False)
              )
            )
          )
        )
        (pooler): BertPooler(
          (dense): Linear(in_features=768, out_features=768, bias=True)
          (activation): Tanh()
        )
      )
    )
    (word_dropout): WordDropout(p=0.05)
    (locked_dropout): LockedDropout(p=0.5)
    (linear): Linear(in_features=768, out_features=5, bias=True)
  )
)"
2022-01-20 14:55:21,721 ----------------------------------------------------------------------------------------------------
2022-01-20 14:55:21,723 Corpus: "Corpus: 212 train + 24 dev + 59 test sentences"
2022-01-20 14:55:21,724 ----------------------------------------------------------------------------------------------------
2022-01-20 14:55:21,726 Parameters:
2022-01-20 14:55:21,734  - learning_rate: "5e-06"
2022-01-20 14:55:21,736  - mini_batch_size: "2"
2022-01-20 14:55:21,738  - patience: "3"
2022-01-20 14:55:21,740  - anneal_factor: "0.5"
2022-01-20 14:55:21,742  - max_epochs: "10"
2022-01-20 14:55:21,743  - shuffle: "True"
2022-01-20 14:55:21,744  - train_with_dev: "False"
2022-01-20 14:55:21,746  - batch_growth_annealing: "False"
2022-01-20 14:55:21,747 ----------------------------------------------------------------------------------------------------
2022-01-20 14:55:21,748 Model training base path: "resources/taggers/few-shot-tagger"
2022-01-20 14:55:21,751 ----------------------------------------------------------------------------------------------------
2022-01-20 14:55:21,753 Device: cpu
2022-01-20 14:55:21,756 ----------------------------------------------------------------------------------------------------
2022-01-20 14:55:21,757 Embeddings storage mode: none
2022-01-20 14:55:21,761 ----------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-08b5e55d3f5e> in <module>()
     56     max_epochs=10,
     57     embeddings_storage_mode="none",
---> 58     weight_decay=0.,
     59 )

3 frames
/usr/local/lib/python3.7/dist-packages/flair/models/tars_model.py in _get_nearest_labels_for(self, labels)
     92             plausible_labels = []
     93             plausible_label_probabilities = []
---> 94             for plausible_label in self.label_nearest_map[label]:
     95                 if plausible_label in already_sampled_negative_labels or plausible_label in labels:
     96                     continue

KeyError: 'U-SUPPLIER'

**Comment by arda-vianai** [comment]
I add the training and test files here.
[flair_ner_test.txt](https://github.com/flairNLP/flair/files/7906236/flair_ner_test.txt)
[flair_ner_train.txt](https://github.com/flairNLP/flair/files/7906237/flair_ner_train.txt)

**Comment by arda-vianai** [comment]
@alanakbik @kishaloyhalder Could you help me with this problem?

**Comment by alanakbik** [comment]
@whoisjones can you take a look?

**Comment by whoisjones** [comment]
Yeah i currently look into it anyway, I observe an issue when combining with multitask training. @arda-vianai I keep you updated.

**Comment by whoisjones** [comment]
@arda-vianai can please pull current master version? we changed some logic with our labels and try again?

**Comment by arda-vianai** [comment]
Sorry for the late reply, @whoisjones. I was on a vacation.

The error I get now id the following:

KeyError                                  Traceback (most recent call last)
<ipython-input-14-8c32ed943406> in <module>
     54 trainer = ModelTrainer(tars_tagger_supply, corpus)
     55 
---> 56 trainer.train(
     57     f'resources/taggers/few-shot-tagger',
     58     learning_rate=5e-6,

~/opt/miniconda3/lib/python3.8/site-packages/flair/trainers/trainer.py in train(self, base_path, learning_rate, mini_batch_size, eval_batch_size, mini_batch_chunk_size, max_epochs, train_with_dev, train_with_test, monitor_train, monitor_test, main_evaluation_metric, scheduler, anneal_factor, patience, min_learning_rate, initial_extra_patience, optimizer, cycle_momentum, warmup_fraction, embeddings_storage_mode, checkpoint, save_final_model, anneal_with_restarts, anneal_with_prestarts, anneal_against_dev_loss, batch_growth_annealing, shuffle, param_selection_mode, write_weights, num_workers, sampler, use_amp, amp_opt_level, eval_on_train_fraction, eval_on_train_shuffle, save_model_each_k_epochs, tensorboard_comment, use_swa, use_final_model_for_eval, gold_label_dictionary_for_eval, create_file_logs, create_loss_file, epoch, use_tensorboard, tensorboard_log_dir, metrics_for_tensorboard, optimizer_state_dict, scheduler_state_dict, save_optimizer_state, **kwargs)
    481 
    482                         # forward pass
--> 483                         loss = self.model.forward_loss(batch_step)
    484 
    485                         if isinstance(loss, tuple):

~/opt/miniconda3/lib/python3.8/site-packages/flair/models/tars_model.py in forward_loss(self, data_points)
     43 
     44         # Transform input data into TARS format
---> 45         sentences = self._get_tars_formatted_sentences(data_points)
     46 
     47         loss = self.tars_model.forward_loss(sentences)

~/opt/miniconda3/lib/python3.8/site-packages/flair/models/tars_model.py in _get_tars_formatted_sentences(self, sentences)
     66                 )
     67 
---> 68                 sampled_negative_labels = self._get_nearest_labels_for(positive_labels)
     69 
     70                 for label in positive_labels:

~/opt/miniconda3/lib/python3.8/site-packages/flair/models/tars_model.py in _get_nearest_labels_for(self, labels)
     97             plausible_labels = []
     98             plausible_label_probabilities = []
---> 99             for plausible_label in self.label_nearest_map[label]:
    100                 if plausible_label in already_sampled_negative_labels or plausible_label in labels:
    101                     continue

KeyError: 'O'

**Comment by arda-vianai** [comment]
@whoisjones  Just to verify - this is the upgrade command I used. Please let me know if it is not correct.

pip install --upgrade git+git://github.com/flairNLP/flair

**Comment by whoisjones** [comment]
Hi @arda-vianai, I am not sure whether this really pulled the current master version or just updated to the latest release. I try tomorrow to rerun your script with your example data and let you know.

**Comment by arda-vianai** [comment]
@whoisjones  Thanks for the update. Looking forward to your next update. Thank you!

**Comment by arda-vianai** [comment]
@whoisjones Any updates? Thank you!

**Comment by whoisjones** [comment]
Hi @arda-vianai your issue arises from the data format you use. Please use IOB formatted files for sequence tagging tasks in flair. Prefixes such as `L-` or `U-` wont work.
