### ISSUE TITLE
UnknownExtra: requests 2.20.0 has no such extra feature 'socks'

### ISSUE THREAD

**Issue by YoussefSultan** [flairNLP/flair#2603]
When loading a sequence tagger an unknown extra error occurs.

**To Reproduce**
Python 3.9
```from flair.models import SequenceTagger

tagger = SequenceTagger.load("flair/ner-english")```

**Comment by ldmtwo** [comment]
Another version of the error.

UnknownExtra: requests 2.24.0 has no such extra feature 'socks'

import flair
...
~/anaconda3/lib/python3.8/site-packages/flair/datasets/relation_extraction.py in <module>
     10 
     11 import conllu
---> 12 import gdown

**Comment by pashna** [comment]
I have the same issue
