### ISSUE TITLE
How do I submit the models and LM I've trained?

### ISSUE THREAD

**Issue by dchaplinsky** [flairNLP/flair#2604]
I've trained both, LM models for Ukrainian on 19GB texts in Ukrainian and models for NER that uses those LM's and custom trained fasttext embeddings. How do I submit those?

**Comment by dchaplinsky** [comment]
@alanakbik maybe? I've read `CONTRIBUTING.MD` and glimpsed through the documentation, but found not answer.

**Comment by alanakbik** [comment]
Hello @dchaplinsky we'd be happy to add these models to Flair! There's two questions. 

Do you want to host the model yourself or should we do it? The models should be hosted somewhere where they can be downloaded. Typically we put them on our university server, in that case you can send them to me and I place them there. Alternatively, you can also host the model yourself. 

Do you want to do the PR or should we do it? After the models have an URL from which they can be downloaded, a PR needs to be created that looks like this one:  #2323 or #1872 If you do the PR yourself, github will list you as contributor. But if you prefer, we can also do the PR.

**Comment by dchaplinsky** [comment]
No problems, I'll host them and do the PR.

One more question on the data. Last night I suddenly realized that LMs were
trained on a tokenized version of the corpus, and tokenization (made by
another developer) dropped all the punctuation. Does it affect the quality
of the model? Or should I retrain?

**Comment by alanakbik** [comment]
Great! Punctuation is typically good signal, so retraining might improve performance on downstream tasks.
