### ISSUE TITLE
Can i save best model during fine tuning?

### ISSUE THREAD

**Issue by azizcu** [flairNLP/flair#2610]
trainer.fine_tune('resources/taggers/sota-ner-flert',
                  learning_rate=5.0e-6,
                  mini_batch_size=4,)

In this case, I observed that the best model is not saved. But "trainer.train()" this best model is saved per epoch when the current model is best. I want to save the best model during fine-tuning like train().
If possible, please tell me.

**Comment by lukasgarbas** [comment]
You can set ```use_final_model_for_eval=False```:

```python
trainer.fine_tune('resources/taggers/sota-ner-flert',
                  learning_rate=5.0e-6,
                  mini_batch_size=4,
                  use_final_model_for_eval=False,
                  )
```

This saves both the best and final models and evaluates using the best model.

**Comment by azizcu** [comment]
@lukasgarbas Thanks for your answer.
