### ISSUE TITLE
Language-Agnostic SEntence Representations

### ISSUE THREAD

**Issue by oterrier** [flairNLP/flair#2613]
Hi
The new release 1.1.2 of [LASER](https://github.com/yannvgn/laserembeddings) has removed the dependencies to non python packages so maybe we could reconsider its integration ?
What do you think?

Best regards
Olivier Terrier

_Originally posted by @oterrier in https://github.com/flairNLP/flair/issues/427#issuecomment-1026655122_

**Comment by alanakbik** [comment]
@oterrier looks interesting! Interested in doing a PR for this?

**Comment by oterrier** [comment]
Hi Alan
I'm pretty busy right now... Maybe during the summer...
@stefan-it could be interested ?

Best regards
Olivier

**Comment by stefan-it** [comment]
Hi @oterrier ,

if you're interested I could implement it, so it can be used like sentence embeddings/S-BERT:

https://github.com/flairNLP/flair/blob/9697dc29c03ba7e5513be5a0c4f9902626917616/flair/embeddings/document.py#L473-L485

So they can be used e.g. for classification tasks :thinking:

**Comment by oterrier** [comment]
Hi @stefan-it, sure it would be great and definitively a plus for mutlilingual classification projects
+1

Thx
