### ISSUE TITLE
Train custom NER for street Address Extraction

### ISSUE THREAD

**Issue by debjyoti003** [flairNLP/flair#2621]
I want to train a custom NER model which can extract street addresses from the text. As we know street address will contain spaces and as we know that we need to annotate text in 'BIO' scheme. But annotation of address is not same as annotation of Pople Name or company names. Can someone please guide me how can I do the annotation for the extraction of street addresses?

**Comment by helpmefindaname** [comment]
Hello @debjyoti003 ,
I am not sure if I agree with `But annotation of address is not same as annotation of Pople Name or company names`, or maybe I don't understand what you meant.

For example the sentence:
`The German Parlament is at Niederkirchnerstraße 5, 10117 Berlin, Germany`
could be annotated with 2 entities, "German Parlament" as ORG and "Niederkirchnerstraße 5, 10117 Berlin, Germany" as ADDR

assuming space tokenization, you'd create the tagging

| | | | | | | | | | |
| - | - | - | - | - | - | - | - | - | - |
| The | German | Parlament | is | at | Niederkirchnerstraße | 5, | 10117 | Berlin, | Germany |
| O | B-ORG | I-ORG | O | O | B-ADDR | I-ADDR | I-ADDR | I-ADDR | I-ADDR |

**Comment by debjyoti003** [comment]
Also wanted to ask, what do you think at least how many should I annotate to get a decent result, cause I tried training it on 10 documents (approximately 5-6 sentences for each document) and when I did inferencing using that model, it gave me worst result, so if you can tell me an approximate number.

**Comment by iliaNecrov** [comment]
@debjyoti003, hello I have the same task as you right now :)
I was using a lot of open source address data and generated context for them. 
I have about 110k sentences in my train dataset. 
It works pretty well for trivial text, but It depends on what area you will be using your model in.

Therefore, if you know in which area you will use your trained neural network, you need to improve your model through experimentation.

**Comment by debjyoti003** [comment]
Hi @iliaNecrov , good to know that we are working on the same task. Will keep exchanging information!!!
Also yeah agree with your point that I need to do more experimentation, but currently I am focussing more on gathering more data and annotating them, as the current corpus size that i have is pretty less, so once i can train it on enough data, then I can play with hyperparamters further to improve the model results. .. :)

**Comment by iliaNecrov** [comment]
@debjyoti003, As for the experiment, I meant adding/removing data from the training set. Playing with hyperparameters is cool, but hard enough to do when training time is 12+ hours. In any case, good luck and let me know the results, I'm new to NLP and would be interested in exchanging the information.

**Comment by helpmefindaname** [comment]
I think you'll get far already by using the `https://github.com/flairNLP/flair/blob/master/flair/models/regexp_tagger.py#L43` and handcrafting a good regex.
