### ISSUE TITLE
Given and found data, got "RuntimeError: No data provided when initializing corpus object."

### ISSUE THREAD

**Issue by ChessMateK** [flairNLP/flair#2624]
**PLEASE NOTE**: This issue is strictly related to flair-0.10. Using flair-0.9 this problem is solved, but #2526 arise (see my post).

**Describe the bug**
Although the data is provided and found as reported by the print embedded in the code with the path to the data, the following error is returned "RuntimeError: No data provided when initializing corpus object."

**To Reproduce**
from flair.data import Corpus
from flair.datasets import CSVClassificationCorpus

data_folder = '/path/to/folder/train_dev_test'
column_name_map = {0: "Original Index", 1:"Labelset", 2: "Text", 3: "Label1", 4: "Label2"} 
corpus: Corpus = CSVClassificationCorpus(data_folder, column_name_map, skip_header=True, delimiter=",", label_type="Label1") 

**Expected behavior**
Corpus correctly loaded.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/48825535/152822452-9f5bfd12-fe7e-4fbb-89d2-63c0b0eff3bf.png)

**Environment:**
 - OS: Google Colab
 - Version: flair-0.10

**Additional context**
Data are loaded from Google Drive.

**Comment by alanakbik** [comment]
@MaxDall can you check this error and see if you can help? 

@ChessMateK can you provide a minimal txt file with some data to reproduce the error?

**Comment by ChessMateK** [comment]
> @MaxDall can you check this error and see if you can help?
> 
> @ChessMateK can you provide a minimal txt file with some data to reproduce the error?

Just the header with the first element for each file:
[dev_sample.csv](https://github.com/flairNLP/flair/files/8031425/dev_sample.csv)
[test_sample.csv](https://github.com/flairNLP/flair/files/8031426/test_sample.csv)
[train_sample.csv](https://github.com/flairNLP/flair/files/8031427/train_sample.csv)

Hereafter the code I used:
```
from flair.data import Corpus
from flair.datasets import CSVClassificationCorpus

data_folder = '/path/to/folder/train_dev_test'
column_name_map = {0: "Original Index", 1:"Labelset", 2: "Text", 3: "Deceptiveness", 4: "Polarity"}  
label_type = "Deceptiveness" 
corpus: Corpus = CSVClassificationCorpus(data_folder, column_name_map, skip_header=True, delimiter=",", label_type=label_type)
```

Hope it helps. Thank you.

**Comment by setegonz** [comment]
I am facing this same issue with flair` 0.11.3`. Any ideas?
