### ISSUE TITLE
Check if NER models are copies

### ISSUE THREAD

**Issue by amtam0** [flairNLP/flair#2629]
Hi,

we prepared a small  Camp where each Team is using Flair to build a NER tagger, and upload it for final evaluation.
The model architectures may be similar but training data is different (in length and content).

Is there a way to check if models are duplicates (apart from file size, model architecture...)?
Using `tagger.state_dict()` for comparison could be an option ?

Thanks

**Comment by alanakbik** [comment]
Interesting project, would be interested to hear about your results! 

If you want to check whether two models are exact copies, probably comparing their state dictionaries is the best idea.

**Comment by amtam0** [comment]
By converting OrderedDicts to string, this workaround seems to work in my case :
```
#Find the index of duplicate elements in list
list_state_dicts_str = [str(el) for el in list_state_dicts]
[idx for idx, item in enumerate(list_state_dicts_str) if item in list_state_dicts_str[:idx]]
```
