### ISSUE TITLE
TARS Classifier batch predict / efficiency

### ISSUE THREAD

**Issue by adriensas** [flairNLP/flair#2639]
To be removed, once it is done: enhancement

**Is your feature/enhancement request related to a problem? Please describe.**
I've been using the TARS model and I've noticed that it wasn't faster to predict by batch.
Once I've took a look on the code I've noticed that actually there is a loop for each sentence in a batch before each prediction which seems to kill the goal of batches.

**Describe the solution you'd like**
Even if TARS is a particular model I'm confident that it should be possible to batch predict for each label.
If it's needed to loop for each sentence it can be done before the prediction and after the prediction. It would be more efficient.

**Additional context**
I may try to solve the problem, I'll keep you in touch ! And thank you for this amazing project !

**Comment by alanakbik** [comment]
@adriensas great! Just a heads-up that we are still in the process of making some changes to TARS, so it probably makes sense to wait until the latest changes are merged.
