### ISSUE TITLE
Model push to Hugging Face, Torch Error

### ISSUE THREAD

**Issue by amtam0** [flairNLP/flair#2652]
**Describe the bug**
widget showing : No module named 'torch.torch_version'

**To Reproduce**
Click compute to test example on widget

**Expected behavior**
Should show NER tags when computing the widget

**Screenshots**
![widget](https://user-images.githubusercontent.com/17755198/156541954-182d3778-49f7-4d11-8c7f-48f161c5f09f.png)

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: ubuntu 20.04.03
 - Version [e.g. flair-0.3.2]: torch-1.10.0+cu102, flair-0.10

**Additional context**
model link in HF :  https://huggingface.co/amtam0/timer-ner-fr

**Comment by irg1008** [comment]
Hi! How were you able to solve it and use flair model in hugging face?? I am going crazy

Thanks
