### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by thomashallam** [flairNLP/flair#2655]
**Describe the bug**
Broken link on line 108 in the file https://github.com/flairNLP/flair/tree/master/examples/ner
references paper 
[FLERT](ttps://arxiv.org/abs/2011.06993) paper.

**To Reproduce**
Open page Github or Vscode or R can see the link is broken

**Expected behavior**
Link to correct page: https://arxiv.org/abs/2011.06993

**Comment by rishvantsingh** [comment]
I have corrected the above and raised a PR. @thomashallam

**Comment by alanakbik** [comment]
Closed via PR!
