### ISSUE TITLE
Clearer Instructions For Reporting Vulnerabilites

### ISSUE THREAD

**Issue by whokilleddb** [flairNLP/flair#2656]
Hey, can we have a better reporting mechanism? The form mentioned in `Security Policy` doesn't lead to an actual form, rather just a webpage with a bunch of corporate mails while the repository doesn't collaborate with [huntr.dev](https://huntr.dev/) for easier bug tracking and CVE requests. Please update the reporting channels as I would love to report some security vulnerabilities I've found.

**Comment by whokilleddb** [comment]
Hey @stefan-it can you please update the vulnerability reporting mechanism so that the appropriate steps can be taken? The link mentioned in the `Security Policy` seems broken and this repository isn't a part of `huntr.dev` either

**Comment by stefan-it** [comment]
Hi @whokilleddb ,

thanks for reporting it! I'm currently discussing it with @alanakbik - and yeah the form is outdated (leftover from Zalando repo) and we should find a new solution. Will report back soon!

**Comment by whokilleddb** [comment]
> Hi @whokilleddb ,
> 
> thanks for reporting it! I'm currently discussing it with @alanakbik - and yeah the form is outdated (leftover from Zalando repo) and we should find a new solution. Will report back soon!

Thanks! It would be great if you guys open upto `huntr.dev` as it makes the reporting and fixing process along with the CVE assignment issue way easier 😄

**Comment by whokilleddb** [comment]
Hi @stefan-it @alanakbik any updates on the Security Policy? I want to report a minor bug :)
