### ISSUE TITLE
503 WordEmbeddings error

### ISSUE THREAD

**Issue by laura-barkauskaite** [flairNLP/flair#2660]
I am trying to load embeddings and I keep getting the following error:

  File "/root/.local/lib/python3.7/site-packages/trainer/train.py", line 194, in <module>
    embedding = WordEmbeddings('en')
  File "/root/.local/lib/python3.7/site-packages/flair/embeddings/token.py", line 163, in __init__
    cached_path(f"{hu_path}/en-fasttext-news-300d-1M.vectors.npy", cache_dir=cache_dir)
  File "/root/.local/lib/python3.7/site-packages/flair/file_utils.py", line 91, in cached_path
    return get_from_cache(url_or_filename, dataset_cache)
  File "/root/.local/lib/python3.7/site-packages/flair/file_utils.py", line 220, in get_from_cache
    f"HEAD request failed for url {url} with status code {response.status_code}."
OSError: HEAD request failed for url https://flair.informatik.hu-berlin.de/resources/embeddings/token/en-fasttext-news-300d-1M.vectors.npy with status code 503.

When I try to manually reach https://nlp.informatik.hu-berlin.de/resources/ I also get 503.

**Comment by edloginova** [comment]
Same. For me it is: `OSError: HEAD request failed for url https://flair.informatik.hu-berlin.de/resources/embeddings/token/nl-wiki-fasttext-300d-1M.vectors.npy with status code 503.` Tried from several networks.

**Comment by thekeshavgoel** [comment]
Similar issue #2661

**Comment by kunaldesai97** [comment]
Yes, facing the same issue for all the embeddings. It's a major problem as we are unable to load embeddings or train models. Please take a look at this, thanks.

**Comment by rcdilorenzo** [comment]
For those looking for a workaround who have downloaded these embeddings perhaps on a different machine, they are stored by flair in the cache directory ~/.flair/embeddings. Copy the files to the appropriate machine as a workaround until the server is available again.

**Comment by alanakbik** [comment]
Hello all, we are looking into this. Looks like the university server is unreachable. Hopefully can be fixed tomorrow!

**Comment by alanakbik** [comment]
Should be fixed now!
