### ISSUE TITLE
ModelTrainer doesn't seem to be supporting tensorboard

### ISSUE THREAD

**Issue by tanujjain** [flairNLP/flair#2668]
**Describe the bug**
`ModelTrainer` should be able to support tensorboard through parameters: `use_tensorboard` and `tensorboard_log_dir`, but trying to use these parameters throws a `TypeError: __init__() got an unexpected keyword argument 'use_tensorboard' `error. Looking at https://github.com/flairNLP/flair/blob/04901216e817e9df77adc92d4c37a2fffd398c73/flair/trainers/trainer.py#L119 I expect these parameters to be supported.

**To Reproduce**
```
from flair.trainers import ModelTrainer
## initialize tagger and corpus

trainer: ModelTrainer = ModelTrainer(tagger, corpus)
trainer.train(use_tensorboard=True, tensorboard_log_dir='path/to/dir')
```

**Expected behavior**
The training runs through and tensorboard is accessible with `tensorboard --logdir=tensorboard_log_dir`

**Environment (please complete the following information):**
 - OS : macOS Catalina
 - Version: flair==0.9

Any other way to include tensorboard logging with ModelTrainer?

**Comment by alanakbik** [comment]
@tanujjain thanks for reporting this! @lukasgarbas can you take a look?

**Comment by tanujjain** [comment]
Seems like using the tensorboard parameters in `ModelTrainer` constructor does the job instead of passing it to the `ModelTrainer.train` call, which is confusing given the parameters are supposed to be passed to the `ModelTrainer.train`  call here: https://github.com/flairNLP/flair/blob/04901216e817e9df77adc92d4c37a2fffd398c73/flair/trainers/trainer.py#L119

**Comment by lukasgarbas** [comment]
Hi @tanujjain, you are probably referencing the code from the current version but using Flair 0.9 https://github.com/flairNLP/flair/tree/v0.9. 

`use_tensorboard` and `tensorboard_log_dir` parameters were moved from the constructor to `ModelTrainer.train` in the latest version.
