### ISSUE TITLE
Cannot load TransformerWordEmbeddings as part of StackedEmbeddings

### ISSUE THREAD

**Issue by why-in-Shanghaitech** [flairNLP/flair#2670]
**Describe the bug**
Everything is fine unless I load the model from `best-model.pt`. The result is totally different from what I've seen during training (the model behaves like it is never ever trained).
In my case, any model built with a `StackedEmbeddings` embedding containing `TransformerWordEmbeddings` and any other unstatic embeddings will cause the bug.

**To Reproduce**
This bug is only related to embeddings. Create the embeddings using this code:

```python
word_embedding = WordEmbeddings(...)
character_embedding = CharacterEmbeddings(...)
trans_embedding = TransformerWordEmbeddings(model = "roberta-large")
embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=[word_embedding, character_embedding ,trans_embedding])
```

Then train with any model you like. The final result would just like the result from a randomly initialized model.

**Expected behavior**
The final result should at least look like it is trained...

**Screenshots**
Ask me to provide a screenshot if needed.

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux
 - Version [e.g. flair-0.3.2]: flair-0.8.0.post1, flair-0.10

**Additional context**
I think the problem lies in the codes here:

https://github.com/flairNLP/flair/blob/da7c12b08f377f7e66e9593af7b740351819d7d0/flair/embeddings/base.py#L449

The name of this embedding is overridden unexpectedly. In `StackedEmbeddings`, we rename all the child embeddings by adding a number in front of it.

I'm not sure whether this is fixed in the main branch. I fixed this bug just by adding this line of code:

```python
if key != 'name':
    self.__dict__[key] = embedding.__dict__[key]
```

**Comment by alanakbik** [comment]
Thanks for reporting this! I think the problem of ordering embeddings in `StackedEmbeddings` may already be fixed in master branch, but I'm not so sure. @plonerma can you take a look at this problem?

**Comment by plonerma** [comment]
Hey @why-in-Shanghaitech , thanks for the info! I will take a look and then get back to you!

**Comment by plonerma** [comment]
@why-in-Shanghaitech , I am struggling to reproduce the behavior you described. It would be great, if you could provide some more context:
- How are you loading the model?
- How are you verifying that the loaded model has not be trained?

The way you describe the issue, it sounds like there is an issue with saving/loading the model. I tested the saving and loading on the versions you referenced (flair-0.8.0.post1, flair-0.10, commit [da7c12b](https://github.com/flairNLP/flair/commit/da7c12b08f377f7e66e9593af7b740351819d7d0) ) and could not find an issue.

Maybe you could execute [this file](https://gist.github.com/plonerma/75f92d1b5e2372c81e8362e3d8d5a9b9) in your environment and see if the assertion is successful.

**Comment by why-in-Shanghaitech** [comment]
Hi, @plonerma ! Glad to see your reply!

I tried your code in flair-0.8.0.post1. Could you please add 3 lines of codes at the very end of your script:

```python
    ...
    original_result, original_loss = original_tagger.evaluate(corpus.test)
    loaded_result, loaded_loss = loaded_model.evaluate(corpus.test)
    print(original_loss, loaded_loss)
```

And this is the output from my side:

```
...
All parameters equal.
tensor(2512.8352, device='cuda:0') tensor(2110.5010, device='cuda:0')
```

Sure the model parameters are the same. Actually, when I create an identical model and load the parameters from the saved files, the behaviour is normal. But if the model is loaded from scratch, the predictions are totally different from expected.

Answers to your questions:
- In my project, I load the model with `tagger.load`. It should call the same function as yours.
- I observe bad evaluation results. I believe that the model is trained but something goes wrong in loading.

See if this help. I haven't tested on flair-0.10 or the master branch.

**Comment by plonerma** [comment]
> I'll try to work out a reproducible script, but it may take a few days. Sorry for that...

Perfect.

Are you by any chance saving and loading the models on different machine (i.e. one windows and one unix machine)? Then you might want to upgrade to 0.10 and see if the problem persists.

**Comment by why-in-Shanghaitech** [comment]
No, saving and loading take place in one single script... so absolutely in one machine. Thanks for the advice.

**Comment by why-in-Shanghaitech** [comment]
Change the embedding to:

```python
    embeddings: StackedEmbeddings = StackedEmbeddings(embeddings=[
        WordEmbeddings('glove'),
        TransformerWordEmbeddings(model="distilbert-base-uncased"),
        CharacterEmbeddings(),
    ])
```

And add these codes to the very end of your original script:

```python
    original_tagger.eval()
    original_result, original_loss = original_tagger.evaluate(corpus.test)
    loaded_result, loaded_loss = loaded_model.evaluate(corpus.test)
    print(original_loss, loaded_loss)
    print(original_result.main_score, loaded_result.main_score)
```

This is the output from my side:

```
...
tensor(1248.7329, device='cuda:0') tensor(1341.2733, device='cuda:0')
0.0249 0.005
```

I remembered that the order of the embedding doesn't matter but now it seems that I was wrong about this. See if this help.

**Comment by plonerma** [comment]
Hey @why-in-Shanghaitech , thanks for the additional information. I can reproduce the issue now. It's quite peculiar. The issue is fixed in the master branch, but it does exist in version 0.10. Since it won't be an issue in the upcoming version, I did not investigate it more deeply, but it is related to the naming, as you mentioned. When the model is loaded, the transformer embedding does not receive the expected prefix. 

There is an additional workaround to yours which does not involve a change in the flair-source code:
After loading you can adjust the names to include the required prefix as following:

``` python
for i, e in enumerate(loaded_model.embeddings.embeddings):
    prefix = f"{str(i)}-"
    if not e.name.startswith(prefix):
        e.name = prefix + e.name
```

To test whether this works for you, you can use [this file](https://gist.github.com/plonerma/75f92d1b5e2372c81e8362e3d8d5a9b9).

**Comment by why-in-Shanghaitech** [comment]
Thanks for the help! Happy to know that the bug is fixed.

I'm currently using a wrapper class of `TransformerWordEmbeddings`:

```python
class FixedTransformerWordEmbeddings(TransformerWordEmbeddings):
    
    # A fix to the flair transformer word embeddings.
    # See details: https://github.com/flairNLP/flair/issues/2670
    def __setstate__(self, d):

        name = d['name']
        super().__setstate__(d)
        self.name = name
```

So that we can use the embeddings as usual.

Since the problem has been solved, I'm closing this issue.
