### ISSUE TITLE
Span to BIO ColumnCorpus for transformer tokenization

### ISSUE THREAD

**Issue by Sharing-Sam-Work** [flairNLP/flair#2678]
#### Problem

I have ner annotated data stored in a json file, with a format that is similar to the format output by the to_dict method of the sentence class, where an annotation is characterized by the index of its start and end characters.

        sentence.to_dict(tag_type='ner')
            
        {'text': 'George Washington went to Washington.',
            'entities': [
                {'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'type': 'PER', 'confidence': 0.999},
                {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'type': 'LOC', 'confidence': 0.998}
            ]}

To train an algorithm using flair, I had to do manually convert the data into the BIO formatted txt files expected by the ColumnCorpus method.

                  Flight O
                  phase O
                  and O
                  location O
                  not B-NEG
                  indicated O
                  . O

I used my own tokenizer (space and punctuation based delimitation), at the cost of losing the opportunity to use more sophisticated tokenizers. 

#### Questions -
Suppose I want to use a transformer embedding, is there any built-in functions to convert span-based annotations to BIO formatted text files in flair using transformer tokenizer? 

If not, does this mean that I will obtain sub-optimal result for transformer embeddings when using my own tokenizer?

I hope my question is clear.

**Comment by helpmefindaname** [comment]
Hey @Sharing-Sam-Work if you checkout the master (it isn't yet in the latest release), you can use the [JsonlCorpus](https://github.com/flairNLP/flair/blob/master/flair/datasets/sequence_labeling.py#L103) that does the internal mapping using the default flair tokenizer.

In general:
You can use whatever tokenizer you want and the transformer subtokens will be mapped to those. The tokenizer you are using basically defines the output space, if you use a tokenizer that splits `I live in vienna.` to `["I", "live", "in", "vienna."]` Hence you will never result into `vienna` as it will only be able to return `vienna.`.
If you use standard bert embeddings, flair will embed the embeddings for `["I", "live", "in", "v", "##ien", "##na", "."]` and map those tho the actual tokens based on the `subtoken_pooling` parameter (the options are `"first", "last", "first_last", "mean"`)

I would advise you to stay with the syntoc tokenizer (flari default) and if you see a mismatch between labeling and tokenization, to then implement your own tokenizer

**Comment by Sharing-Sam-Work** [comment]
Thank you!
