### ISSUE TITLE
Multi-label or overlapping annotations predictions

### ISSUE THREAD

**Issue by agademic** [flairNLP/flair#2679]
Is it possible to train a Flair NER-sequence-tagger on overlapping annotations?

I found that you introduced multi-label predictions in 2021 but I am not sure whether that fits my problem. Unfortunately, I didn't find any documentation pointing to that use case.

What I'm thinking of is to train a tagger to predict multiple labels for certain tokens, like:

`Span [1,2]: "George Washington"   [− Labels: PER (0.9968), PRES (0.9734)]`
`Span [5]: "Washington"   [− Labels: LOC (0.9994)]`

Is that possible with a single Flair without the use of multiple taggers?

**Comment by alanakbik** [comment]
Hello @agademic not currently (the `SequenceTagger` predicts one label per word), but @susannaruecker is currently working on a "span tagger" that will be able to do overlapping annotations and will likely be added soon.

**Comment by agademic** [comment]
Hi @alanakbik! Thank you for your quick response and the clarification. That's great to hear also, I cannot wait to try the new span tagger!

**Comment by gabriel-frickh** [comment]
@alanakbik I have not found whether the above mentioned feature concerning a "span tagger" so that overlapping annotations are possible has been implemented yet in the end? Do you know/is there any updates concerning that matter?

**Comment by alanakbik** [comment]
HEllo @gabriel-frickh the SpanTagger currently lives in this branch: https://github.com/flairNLP/flair/tree/span_tagger_fast - however, it will not be part of the upcoming release. It works though, so if you're interested in testing it, let me know and I will paste an example script.
