### ISSUE TITLE
Replace print with logging in model training

### ISSUE THREAD

**Issue by HallerPatrick** [flairNLP/flair#2686]
**Is your feature/enhancement request related to a problem? Please describe.**

When using the ModelTrainer, everything is printed out through a logger, except for when the learning rate is reduced. This is just a normal print to stdout. See picture:

<img width="983" alt="Screenshot 2022-03-23 at 20 22 46" src="https://user-images.githubusercontent.com/22773355/159779701-29d24393-c28e-41c2-92eb-5b2724177610.png">

**Describe the solution you'd like**
For consistency, I would replace the print call with a logging call. For this the logger has to be passed from the `ModelTrainer` to the `AnnealOnPlateu` object or just use the global `flair` logger.

If this is enough for a PR, then I would assign myself to this

Greetings,
Patrick

**Comment by alanakbik** [comment]
@HallerPatrick this should be fixed in master branch -> https://github.com/flairNLP/flair/pull/2665
