### ISSUE TITLE
HunFlair: Difference between "smallish" and "allcorpora" model

### ISSUE THREAD

**Issue by pirwlan** [flairNLP/flair#2688]
Hello everyone, 

I have a question regarding the individual HunFlair Models. For each entity but `Cell Line`, there seems to be two different models, one `smallish` and one `allcorpora`. I could not find any explanation of how these models are different, or any metric comparison. Could some explain the difference between the models?

**Comment by leonweber** [comment]
Hey @pirwlan,

the `smallish` versions of the models are those we used to produce the results in the [HunFlair paper](https://academic.oup.com/bioinformatics/article/37/17/2792/6122692). These were not trained on any of the evaluation corpora CRAFT, BioNLP2013 CG and PDR. The training set of the default (non-smallish) models also includes these corpora. Does that answer your question?

**Comment by pirwlan** [comment]
Hey  @leonweber,

Yes, that answers my question. Thanks a lot for getting back!
