### ISSUE TITLE
Sharing Flair model in HuggingFace: "Distant resource does not have an ETag" error

### ISSUE THREAD

**Issue by lirondos** [flairNLP/flair#2691]
Hi!
I'm trying to upload a Flair model to HuggingFace model hub. When I try the model via the inference API console I get the following error:
`Distant resource does not have an ETag, we won't be able to reliably ensure reproducibility.`

I noticed that that same error happens in other Flair models on the HF model hub (for instance, [this one](https://huggingface.co/qanastek/pos-french-camembert-flair?)).

Here is [the model](https://huggingface.co/lirondos/anglicisms-spanish-flair-cs) that I want to share. 

Any idea on how can I solve this? Thank you!

**Comment by alanakbik** [comment]
@lirondos thanks for reporting this. @MaxDall can you take a look?

**Comment by lirondos** [comment]
Hi @MaxDall!
The issue seems to have been solved on its own and the inference API is now working fine. No idea what happened ¯\_(ツ)_/¯ 

Thanks anyway! :)
