### ISSUE TITLE
OneHotEmbeddings - RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by shabnam-b** [flairNLP/flair#2692]
**Describe the bug**
After the first epoch of training, when trying to save the model, the code crashes with the following error:

> 2022-03-29 14:42:36,561 EPOCH 1 done: loss 2.2471 - lr 0.1000000
2022-03-29 14:42:47,611 DEV : loss 0.8668829202651978 - f1-score (micro avg)  0.7597
2022-03-29 14:42:47,665 BAD EPOCHS (no improvement): 0
2022-03-29 14:42:47,666 saving best model
Traceback (most recent call last):
  File "my_main.py", line 271, in <module>
    train(tag=opts.tag, tag2=opts.tag2, corpus=opts.corpus)
  File "my_main.py", line 164, in train
    max_epochs=100)
  File "/lib/python3.7/site-packages/flair/trainers/trainer.py", line 672, in train
    self.model.save(base_path / "best-model.pt")
  File "/lib/python3.7/site-packages/flair/nn/model.py", line 85, in save
    torch.save(model_state, str(model_file), pickle_protocol=4)
  File "/lib/python3.7/site-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/lib/python3.7/site-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
  File "/lib/python3.7/site-packages/torch/serialization.py", line 467, in persistent_id
    if torch.is_storage(obj):
RecursionError: maximum recursion depth exceeded

**The issue seems to be with OneHotEmbeddings, alone or stacked...both cause issues. When I remove OneHotEmbeddings, it works fine.**

**To Reproduce**

My code is very similar to the tutorial on training a model:

```
# 4. initialize embeddings
    embeddings_1 = TransformerWordEmbeddings('roberta-large')
    embeddings_2 = OneHotEmbeddings(corpus=corpus, field='xml', embedding_length=8)

    embedding_types = [
        embeddings_1,
        embeddings_2
    ]

    embeddings = StackedEmbeddings(embeddings=embedding_types)

    # 5. initialize sequence tagger
    tagger = SequenceTagger(hidden_size=256,
                            embeddings=embeddings,
                            tag_dictionary=tag_dictionary,
                            tag_type=tag_type,
                            use_crf=True,
                            use_rnn=True)

    # 6. initialize trainer
    trainer = ModelTrainer(tagger, corpus)

    # 7. start training
    trainer.train('trained_taggers/v1-march28/',
                  learning_rate=0.1,
                  mini_batch_size=32,
                  max_epochs=100)
```

**Expected behavior**
Save the checkpoint, continue training

**Environment:**
 - OS: Linux
 - python3.7
 - Lib version:
 flair: 0.9
 torch: 1.10.0
transformers: 4.17.0

**Comment by alanakbik** [comment]
Thanks for reporting this! @stw2 can you take a look if this error still occurs in master branch? I think it might be fixed already.

@shabnam-b can you provide a minimal example to reproduce? I.e. some small data with which to test the OneHotEmbeddings for field 'xml'?

**Comment by shabnam-b** [comment]
Sure, the data looks like [this](https://drive.google.com/file/d/1Jha7SeKskSuWTJI5NE3nNLQAtZmBBXfW/view?usp=sharing).

**Comment by stw2** [comment]
@alanakbik  there is no error in the master branch when including `OneHotEmbeddings` and running the [Tutorials](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md). also when using the data provided by @shabnam-b. I tried to reproduce the error in the environment in question, i.e, `flair`: 0.9, `torch`: 1.10.0,  `transformers`: 4.17.0, however everything worked fine for me given the data provided. @shabnam-b can you provide the full code that you are using? I could then check it again.

**Comment by shabnam-b** [comment]
I see. Thanks for looking into this. I think data size might also matter...I tried now and I don't get the error when running on a very small train/dev/test sets. Unfortunately, I can't put all the training set online because some parts of it that are under a different license. But here is more info:
Corpus: "Corpus: 7255 train + 826 dev + 877 test sentences"
and the training code:

```
def train(tag="xpos", tag2="xml", corpus="gu"):

    # define columns
    columns = {0: "text", 1: "pos", 3: "xml"}
    data_folder = "data" + os.sep + "flair_inputs" + os.sep

    corpus: Corpus = ColumnCorpus(
        data_folder, columns,
        train_file=corpus + "_" + tag + "_train.txt",
        test_file=corpus + "_" + tag + "_test.txt",
        dev_file=corpus + "_" + tag + "_dev.txt",
    )

    # 2. what tag do we want to predict?
    tag_type = 'pos'

    # 3. make the tag dictionary from the corpus
    tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
    print(tag_dictionary)

    # 4. initialize embeddings
    embeddings_1 = TransformerWordEmbeddings('roberta-large')
    embeddings_2 = OneHotEmbeddings(corpus=corpus, field='xml', embedding_length=8)

    embedding_types = [
        embeddings_1,
        embeddings_2
    ]

    embeddings = StackedEmbeddings(embeddings=embedding_types)

    # 5. initialize sequence tagger
    tagger = SequenceTagger(hidden_size=256,
                            embeddings=embeddings,
                            tag_dictionary=tag_dictionary,
                            tag_type=tag_type,
                            use_crf=True,
                            use_rnn=True)

    # 6. initialize trainer
    trainer = ModelTrainer(tagger, corpus)

    # 7. start training
    trainer.train('trained_taggers/v1/',
                  learning_rate=0.1,
                  mini_batch_size=32,
                  max_epochs=100)
```

Hope this helps!

**Comment by shabnam-b** [comment]
I see...
I didn't know about `OneHotEmbeddings.from_corpus(...)` on master. I'll try it, thanks so much!
