### ISSUE TITLE
If trained with StackedEmbeddings, NER performance very poor after reload the model

### ISSUE THREAD

**Issue by eric890006** [flairNLP/flair#2696]
Hello,

Thanks for all the efforts in developing flair. Recently, I find that when I use `StackedEmbeddings` in training NER models, the performance is very poor **after** reload the model (no problem when using 1 embedding). Below is my code for training CONLL 2003 NER dataset with 2 embeddings (singbert-lite-sg and distilbert-base-uncased) stacked:

```
from flair.datasets import CONLL_03
from flair.embeddings import TransformerWordEmbeddings, StackedEmbeddings
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer
from torch.optim.lr_scheduler import OneCycleLR

corpus = CONLL_03('data/conll2003')
embedding_types = [TransformerWordEmbeddings('zanelim/singbert-lite-sg'), TransformerWordEmbeddings('distilbert-base-uncased')]
embeddings = StackedEmbeddings(embeddings=embedding_types)
tag_type = 'ner'
tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
tagger: SequenceTagger = SequenceTagger(hidden_size=256, embeddings=embeddings, tag_dictionary=tag_dictionary, tag_type=tag_type)
trainer = ModelTrainer(tagger, corpus)

trainer.train('result',
              learning_rate=5.0e-6,
              mini_batch_size=1,
              mini_batch_chunk_size=1,
              max_epochs=3,
              scheduler=OneCycleLR,
              embeddings_storage_mode='none',
              weight_decay=0.,
              monitor_test=True,
              train_with_dev=True,
              optimizer=torch.optim.AdamW,
              )
```

The final performance is acceptable since I only trained for 3 epochs:

```
Results:
- F-score (micro) 0.7698
- F-score (macro) 0.7508
- Accuracy 0.677
```

Then I reload the model and evaluate on the test data again:

```
tagger_reload = SequenceTagger.load('result/final-model.pt')
tagger_result = tagger_reload.evaluate(corpus.test, gold_label_type="ner")
print(tagger_result.detailed_results)
```

The performance become very poor (micro from 0.7698 --> 0.0278):

```
Results:
- F-score (micro) 0.0278
- F-score (macro) 0.0202
- Accuracy 0.0145
```

Not sure if I used the correct way to reload and re-evaluate the test data

The detailed experiment can be found in the colab:
https://colab.research.google.com/drive/1TUeeG06GmlQYB_7WVWzagrT_aQhS_aXr#scrollTo=W6GY4qmm3Y1vA 

Thanks.

**Comment by alanakbik** [comment]
I believe this may be a duplicate of #2670 and if so this is fixed in master branch. You can install from master by doing 
~~~
pip install git+https://github.com/flairNLP/flair.git
~~~

in a fresh environment (make sure flair is not already there otherwise it might not install it). Could you test if the error occurs if you use the master branch? We will release the new version very soon.

**Comment by eric890006** [comment]
Hi @alanakbik,

Thanks for your help. Just tested with `git+https://github.com/flairNLP/flair.git` and now the performance looks nice. The performance output from training:

```
Results:
- F-score (micro) 0.8889
- F-score (macro) 0.8711
- Accuracy 0.8326
``` 

And the performance after reload the model:

```
Results:
- F-score (micro) 0.8889
- F-score (macro) 0.8711
- Accuracy 0.8326
```

Thanks :)
