### ISSUE TITLE
Scale Model Training with LightningLite

### ISSUE THREAD

**Issue by aniketmaurya** [flairNLP/flair#2697]
**Is your feature/enhancement request related to a problem? Please describe.**
Hi, love this project 💜!
[Trainer](https://github.com/flairNLP/flair/blob/master/flair/trainers/language_model_trainer.py#L160) can be enhanced with support for multiple hardwares and distributed training when training with large dataset or model.

**Describe the solution you'd like**
We have been developing [LightningLite](https://pytorch-lightning.readthedocs.io/en/latest/starter/lightning_lite.html) which  enables you to leverage all the capabilities of PyTorch Lightning Accelerators without any refactoring to your training loop.
You can check out our blog post about it here: [Scale your PyTorch code with LightningLite](https://devblog.pytorchlightning.ai/scale-your-pytorch-code-with-lightninglite-d5692a303f00).

**Additional context**
Overall if you are fine with it I am happy to draft a PR with a suggested change to verify in place the impact. Feel free to get in touch and let me know what you think about this.
Thanks! 😄

**Comment by alanakbik** [comment]
@aniketmaurya sounds interesting and we'd be happy to check out a draft PR! 

There are two trainer classes currently, the `LanguageModelTrainer` you linked to is to train language models, and the `Trainer` class is to train all other models (NER, text classification, etc.). Let me know if you have any questions!

**Comment by aniketmaurya** [comment]
Thanks for response @alanakbik, I see both are of type `torch.nn.Module` so we can scale both of these. I will raise a draft PR soon.

**Comment by Borda** [comment]
Very nice! :purple_heart: Would love to see how PL could help here! :rabbit:

**Comment by aniketmaurya** [comment]
lets keep it open
