### ISSUE TITLE
UnboundLocalError: local variable 'dev_score' referenced before assignment

### ISSUE THREAD

**Issue by githubmilind** [flairNLP/flair#2701]
**Describe the bug**
I am creating the classifier with own corpus and when I train the model, after 1st epoch get the error.

**To Reproduce**
from flair.trainers import ModelTrainer
trainer = ModelTrainer(clf2, corpus_fst)

trainer.train('data_fst/',max_epochs=2)

**Expected behavior**
expected to training to complete successfully but getting error
UnboundLocalError: local variable 'dev_score' referenced before assignment

**Screenshots**

![image](https://user-images.githubusercontent.com/925481/161447834-dd8a43fd-38e7-4f59-b0d7-da357aadbe7e.png)

**Environment (please complete the following information):**
windows, using in Google Colab

**Additional context**

**Comment by demsking** [comment]
I have the same issue:

```sh
Traceback (most recent call last):
  File "~/test/ner.py", line 46, in <module>
    trainer.train(
  File "~/test/dependencies/lib/python3.9/site-packages/flair/trainers/trainer.py", line 747, in train
    if dev_score > best_validation_score:
UnboundLocalError: local variable 'dev_score' referenced before assignment
```

**Comment by nvenkat94** [comment]
Add "train_with_dev" arguement with trainet.train(). Refer below snippet for reference
```
trainer: ModelTrainer = ModelTrainer(tagger, corpus)

trainer.train('resources/taggers/example-ner',
              learning_rate=0.1,
              mini_batch_size=32,
              max_epochs=10,
             train_with_dev=True)
```
