### ISSUE TITLE
corpus.make_tag_dictionary(tag_type=tag_type) NOT working when trying to train custom Dataset

### ISSUE THREAD

**Issue by hmiche** [flairNLP/flair#2706]
**Describe the bug**
my code was working fine before but now when i try ti execute the command corpus.make_tag_dictionary(tag_type=tag_type) i got an error says  :  1522         for sentence in _iter_dataset(self.get_all_sentences()):
   1523             for token in sentence.tokens:
-> 1524                 tag_dictionary.add_item(token.get_tag(tag_type).value)
   1525         tag_dictionary.add_item("<START>")
   1526         tag_dictionary.add_item("<STOP>")

AttributeError: 'Token' object has no attribute 'get_tag'

**To Reproduce**
I'm trying to train flair with my custom Dataset

**Expected behavior**
the command should work like before without any problem

**Screenshots**
![image](https://user-images.githubusercontent.com/63804608/161970484-b519d949-8e32-44ce-8a1a-b2c1c29bf61d.png)

**Environment (please complete the following information):**
 - OS [ Colab]:
 - Version [e.g. flair-0.3.2]:

**Comment by alanakbik** [comment]
@hmiche the `make_tag_dictionary` function is deprecated since flair 0.8. Can you try `make_label_dictionary` instead?
