### ISSUE TITLE
Deprecate Python 3.6 ?

### ISSUE THREAD

**Issue by aniketmaurya** [flairNLP/flair#2707]
**Is your feature/enhancement request related to a problem? Please describe.**
Python 3.6 is [out of life now](https://www.python.org/downloads/release/python-368/). Maybe consider upgrading to Python 3.7?

**Describe the solution you'd like**
The current CI test only runs for Python 3.6. My suggestion is to test on multiple Python version [like here](https://github.com/gradsflow/chitra/blob/master/.github/workflows/main.yml#L16).

**Additional context**
If you decide to upgrade, I would be happy to make a contribution for this 😄 

Thanks

**Comment by alanakbik** [comment]
@aniketmaurya good point! I think we should deprecate it for the next Flair release!

**Comment by aniketmaurya** [comment]
closing this since CI is already running with 3.7
