### ISSUE TITLE
Certificate for domain that hosts pre-trained models expired

### ISSUE THREAD

**Issue by tadejmagajna** [flairNLP/flair#2716]
**Describe the bug**

A number of pre-trained models and embeddings in Flair are hosted on https://flair.informatik.hu-berlin.de/ and when we try to use them for the first time, Flair will try to download it from that URL. However, this URL needs a valid SSL certificate. Otherwise Python (requests package) will refuse to download.

The SSL certificate for https://flair.informatik.hu-berlin.de/  expired on 9 April 2022 at 17:35:09 CEST

Until this is resolved, flair's pre-trained models and embeddings (such Flair `news-forward` embeddings) hosted on https://flair.informatik.hu-berlin.de/  will be unavailable and Python will crash trying to fetch them.

**To Reproduce**

```python
from flair.embeddings import FlairEmbeddings

flair_embedding_forward = FlairEmbeddings('news-forward')
```
which results in
```
SSLError: HTTPSConnectionPool(host='flair.informatik.hu-berlin.de', port=443): Max retries exceeded with url: /resources/embeddings/flair/news-forward-0.4.1.pt (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired
```

Needs to be executed in a new environment where there are no locally-cached models of course

**Comment by famasya** [comment]
Confirmed. In the meantime, we can use this snippet

```python
import requests, os
session = requests.Session()
session.verify = False
session.trust_env = False
os.environ['CURL_CA_BUNDLE']="" # or whaever other is interfering with 
```

Credit: [StackOverflow](https://stackoverflow.com/questions/15445981/how-do-i-disable-the-security-certificate-check-in-python-requests)

**Comment by alanakbik** [comment]
Hi all, should be fixed now!

**Comment by alanakbik** [comment]
Closing, but feel free to reopen if issues remain!
