### ISSUE TITLE
Makes to_plain_string method robust to consecutive spaces

### ISSUE THREAD

**Issue by mauryaland** [flairNLP/flair#2720]
**Is your feature/enhancement request related to a problem? Please describe.**
When dealing with a text with consecutive spaces, the to_plain_string method is unusable because the parameter whitespace_after is a boolean. We can still use the to_original_text method to keep the consecutive spaces, but when dealing with a long text split in several Sentence objects which keep the index of the original text, we got some performance issues.

**Describe the solution you'd like**
Change the whitespace_after parameter of the Token object from a boolean to an integer referring to the number of whitespaces after the token.
The method to_plain_string will then become something like:

```python
def to_plain_string(self):
        plain = ""
        for token in self.tokens:
            plain += token.text
            if token.whitespace_after > 0:
                plain += token.whitespace_after * " "
        return plain.rstrip()
```

If you are ok with this, I can work on a quick PR. Thanks.

**Comment by alanakbik** [comment]
@mauryaland sure, would appreciate a PR! But what do you mean by performance issues for the to_original_text method?

**Comment by mauryaland** [comment]
It is very specific to my use case. We deal with some very long text that we split into Sentence objects where we keep the original index for postprocessing purposes. Because of that, when using to_original_text_method, we've got some very long text sentences with a lot of whitespaces at the beginning that we need to strip. This takes way much time than using to_plain_string method.

I will work on a PR, thanks for the quick return!
