### ISSUE TITLE
start_pos and end_pos is None when using tokenized input to a Sentence

### ISSUE THREAD

**Issue by igormis** [flairNLP/flair#2723]
A clear and concise description of what you want to know.
I am using flair for ner task and I have issues when passing tokenized input to the Sentence class, like this:

```
sentence = Sentence(tokenized_sentence)
model.predict(sentence)
predict_dict=sentence.to_dict(tag_type='ner')
entities = predict_dict['entities']
```
The start_pos and end_pos of each entity is a None. However, when I use the text with the default SegTok word_tokenizer like this:
`sentence = Sentence(text, use_tokenizer = True)`
I get the correct start_pos and end_pos.
What should I change in order to get the start and end position?
I am using flair==0.9

**Comment by alanakbik** [comment]
@igormis could you try updating to flair 0.11 to see if the issue still persists?

**Comment by igormis** [comment]
I tried, but when I tried to get the prediction with the following code:
model.predict(sentences)
```
predict_dict=sentence.to_dict(tag_type='ner')
entities = predict_dict['ner']
```
for entities I have the following output:
`[{'value': 'location', 'confidence': 0.9968255758285522}, {'value': 'financial_topic', 'confidence': 0.9872051477432251}, {'value': 'event', 'confidence': 0.9997718930244446}, {'value': 'company', 'confidence': 0.9781048893928528}, {'value': 'location', 'confidence': 0.9991999268531799}, {'value': 'event', 'confidence': 0.6657628268003464}]`
which is quite different from the previous format in 0.9 when using:
```
predict_dict=sentence.to_dict(tag_type='ner')
entities = predict_dict['entities']
```
I had something like this:
`[{'text': 'Ireland', 'start_pos': 0, 'end_pos': 7, 'labels': [location (0.9968)]}, {'text': 'watchdog', 'start_pos': 8, 'end_pos': 16, 'labels': [financial_topic (0.9872)]}, {'text': 'fines', 'start_pos': 17, 'end_pos': 22, 'labels': [event (0.9998)]}, {'text': 'WhatsApp', 'start_pos': 23, 'end_pos': 31, 'labels': [company (0.9781)]}, {'text': 'EU', 'start_pos': 58, 'end_pos': 60, 'labels': [location (0.9992)]}, {'text': 'data rules', 'start_pos': 61, 'end_pos': 71, 'labels': [event (0.6658)]}]`

So I am missing start and end position and the text in the flair 0.11

**Comment by igormis** [comment]
@alanakbik any idea on how to get the output with the start_pos and end_pos in flair 0.11? something similar to the output in 0.9:

**Comment by alanakbik** [comment]
Hi @igormis yes we have an example and explanations in our updated tutorial here: https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md#getting-annotated-spans

```python
# iterate over each entity
for entity in sentence.get_spans('ner'):
    
    # print entity text, start_position and end_position
    print(f'entity.text is: "{entity.text}"')
    print(f'entity.start_position is: "{entity.start_position}"')
    print(f'entity.end_position is: "{entity.end_position}"')
    
    # also print the value and score of its "ner"-label
    print(f'entity "ner"-label value is: "{entity.get_label("ner").value}"')
    print(f'entity "ner"-label score is: "{entity.get_label("ner").score}"\n')
```

You can directly access this information on each entity.
