### ISSUE TITLE
Flair Sequence Tagger provide local path to load xlm-roberta-large

### ISSUE THREAD

**Issue by SaratM34** [flairNLP/flair#2725]
Hi,

I am using sequence tagger as below.

```python
from flair.data import Sentence
from flair.models import SequenceTagger

tagger = SequenceTagger.load('/users/user/flair/ner-english-ontonotes-large/pytorch_model.bin')

sentence = Sentence("sample text")
tagger.predict(sentence)
```
Seems like SequenceTagger is downloading `xlm-roberta-large` internally to initialize `TransformerWordembeddings`. I wanted to check if there is a way to provide a local path to load `xlm-roberta-large` instead of downloading from internet.

**Comment by katreparitosh** [comment]
Hi, any advice on this? If I have a locally downloaded model then which path should I move it too?

**Comment by helpmefindaname** [comment]
You need to do the following steps:
* use flair version 0.1
* download the model
* load it and save it again to ensure the latest version is used.

After that, the flair_model also stores the transformers tokenizer and therefore won't need to download it.
