### ISSUE TITLE
Finding hyperparameters with fine_tune=False 

### ISSUE THREAD

**Issue by athleticalex195** [flairNLP/flair#2727]
Hi! 

I'm currently doing my bachelor and I am using flair as a framework for creating an text classifier. I use DocumnetTransformerEmbedding and wish to find the best hyperparameters when training my classifier. However I do **not** wish to fine-tune the transformer model. I only wish to find the best hyperparameters to train the classifier. Is this something that is common? I can't seem to find any mentions of it online, I only find that hyperparameter optimizations is done when wanting to fine-tune the transformer model.

**Comment by bogdankjastrzebski** [comment]
Hi!

I assume you are using TextClassifierParamSelector to find the TextClassifier hyperparameters, correct me if I'm wrong. Maybe you are following [this](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md#selecting-hyperparameters-for-text-classification) example from the tutorials. In this case, the transformer is being fine-tuned.

It is very common not to fine-tune the transformer model, especially when we have a small dataset for our classification task. In this case, we don't have enough information to efficiently estimate a large number of parameters, so we optimize only the last part of the classifier, hoping that the information needed to classify samples is already in the embedding. In general, having a large dataset, it is recommended to fine-tune the model, as it will probably improve its performance. Fine-tuning will be especially effective, when our data distribution is different from the distribution of the data the transformer was trained on, or when our task is to find subtle differences between documents.

When setting the fine_tune to False, the algorithm will find the best hyperparameters (the ones added and predefined [here](https://github.com/flairNLP/flair/blob/master/flair/hyperparameter/parameter.py)) for the TextClassifier, trained on raw TransformerDocumentEmbeddings embeddings. Be careful, though, fine-tuning can improve the model's performance by a lot.

If you want additional resources, [here](https://www.youtube.com/watch?v=yofjFQddwHE) is a short explanation of common practices in transfer learning from the famous deeplearning.ai course, it applies to NLP as well. If you have any further questions, feel free to ask.

**Comment by athleticalex195** [comment]
Thank you for the awnser it was very good! 

When you say " In general, having a large dataset, it is recommended to fine-tune the model" how big are we talking? And how big in comparison to the "original" dataset that the model was pre-trained on?
