### ISSUE TITLE
Loss of Label/Score for NER in tokens

### ISSUE THREAD

**Issue by jenortonfirstam** [flairNLP/flair#2728]
I'm not sure if this was intentional or a bug, but as of 0.11, tokens no longer have NER labels (meaning we are losing the BIOES labels) and scores assigned to tokens in a span. Our usage was dependent on having NER labels and scores in the tokens.

It must be an omission because I can see in the code that you are assigning Omit tags.

**To Reproduce**
Run any NER model and inspect the tokens in the span for labels or scores. The labels were not inserted by the prediction method into the tokens (details and fix outlined below)

**Expected behavior**
The NER label with BIOES tag and score should be added to tokens in the span.

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux
 - Version [e.g. flair-0.3.2]: flair >= 0.11

**Additional context**
The lost functionality (or error) can be traced into the predict function for the sequence tagger. Take a look starting at line 504 of https://github.com/flairNLP/flair/blob/master/flair/models/sequence_tagger_model.py. If this block were written as follows, the lost functionality would be restored.

```python
                for sentence, sentence_predictions in zip(batch, predictions):

                    # BIOES-labels need to be converted to spans
                    if self.predict_spans:
                            begin_index = predicted_span[0][0]
                            end_index = predicted_span[0][-1]+1
                            span_token_tags = sentence_tags[begin_index: end_index]
                            span_token_scores = sentence_scores[begin_index: end_index]
                            span: Span = sentence[begin_index: end_index]
                            span.add_label(label_name, value=predicted_span[2], score=predicted_span[1])
                            for span_token, token_tag, token_score in zip(span.tokens, span_token_tags, span_token_scores):
                                    span_token.add_label(label_name, token_tag, token_score)
```

**Comment by alanakbik** [comment]
Hello @jenortonfirstam yes we changed the abstraction such that NER taggers now directly label `Span` objects instead of BIOES labels on the `Tokens`. So you can get the NER labels by doing: 

```python
tagger = SequenceTagger.load('ner-fast')

sentence = Sentence("George Washington lives in New York")

tagger.predict(sentence)

# print entities
for entity in sentence.get_spans('ner'):
    print(entity) 
```

You can access lots of fields on the `Span` object, check the tutorial [here](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_2_TAGGING.md#getting-annotated-spans). 

If you want to have `Token` annotations, you could transfer the labels to the Token level with this code: 

```python
tagger = SequenceTagger.load('ner-fast')

sentence = Sentence("George Washington lives in New York")

tagger.predict(sentence)

# transfer entity labels to token level
for entity in sentence.get_spans('ner'):
    prefix = 'B-'
    for token in entity:
        token.set_label('ner-bio', prefix + entity.tag, entity.score)
        prefix = 'I-'

# now go through all tokens and print label
for token in sentence:
    print(token)
```
