### ISSUE TITLE
Flair unable to detect dates of any format on custom dataset

### ISSUE THREAD

**Issue by Newlearner012** [flairNLP/flair#2738]
I'm working on training an ner model on custom dataset. I've tried training the model following the steps mentioned in this [link](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-sequence-labeling-model). BytePairEmbeddings was used to train the model. 

My dataset has date formats of all kinds along with other ner tags. It so happens that the flair's performance on validation data isn't very bad. In the test data, it isn't able to pick any of the dates from text

Below is an example for a random data containing date. 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/42976791/164759969-84c37bef-06ed-4810-8caf-c5a57c8b407c.png">

Kindly advice on what could be done in this regard

**Comment by helpmefindaname** [comment]
Hey @Newlearner012 
For dates I would consider using the [regex tagger](https://github.com/flairNLP/flair/blob/master/flair/models/regexp_tagger.py#L44) crafting a few regexes should be usefull to cover 99% of cases
