### ISSUE TITLE
StackedEmbeddings with PooledFlairEmbeddings returning TypeError

### ISSUE THREAD

**Issue by Nuveyla** [flairNLP/flair#2742]
**Describe the bug**
While running the given code for the best configuration for CONLL-03 NER on English at the following page: [link](https://github.com/flairNLP/flair/blob/b3797096742699997e77d12a66c82310361990a4/resources/docs/EXPERIMENTS.md) I get a TypeError (see screenshot). I have tested out several embeddings (Word and Flair) and saw that this TypeError is only occurring when running with PooledFlair. I have controlled the source code where the error is (token.py), but could not come up with a possible solution.

**Screenshots**
![image](https://user-images.githubusercontent.com/37611243/165096669-942b2c80-7454-4198-a2a4-e22f76535fc1.png)
![image](https://user-images.githubusercontent.com/37611243/165096805-345579fb-c965-4d44-8da9-fde66773db4a.png)

**Environment:**
 - Windows
 - python 3.10
 - flair -0.11

**Comment by alanakbik** [comment]
@Nuveyla thanks for reporting this. @susannaruecker can you take a look?

**Comment by alanakbik** [comment]
Fixed in PR #2744
