### ISSUE TITLE
Loading models saved with flair < 0.11 fails with flair 0.11

### ISSUE THREAD

**Issue by yosipk** [flairNLP/flair#2745]
**Describe the bug**
The [` TextClassifier`](https://github.com/flairNLP/flair/blob/master/flair/models/text_classification_model.py#L15) model that uses [`TransformerDocumentEmbeddings`](https://github.com/flairNLP/flair/blob/master/flair/embeddings/document.py#L26) trained and saved with Flair 0.10 can not be loaded with Flair 0.11.

**To Reproduce**
Save the `TextClassifier` that uses `TransformerDocumentEmbeddings` with Flair 0.10 and load with Flair 0.11.

**Expected behavior**
Model loading should be backward compatible.

**Environment (please complete the following information):**
 - OS: Linux
 - Version: flair 0.11.1 / flair 0.10

**Additional context**
The bug is caused by renaming the argument of the `TransformerDocumentEmbeddings` from [`pooling`](https://github.com/flairNLP/flair/blob/45700cb61869b25c9c08c06a26298b805c0c66dc/flair/embeddings/document.py#L40) to [`cls_pooling`](https://github.com/flairNLP/flair/blob/d20c3fd07474e6103780fbe2b65302871f8db33d/flair/embeddings/document.py#L40). As a result the Flair 0.10 model is serialized with `pooling`, which is not getting recognized by Flair 0.11, and `pooling` gets propagated all the way to Transformers model constructor causing error.

Possible fix is to detect in deserialization if the state dict of model to be loaded contains the key `pooling` instead of `cls_pooling` and rename the key from `pooling` to `cls_pooling`, so the `TransformerDocumentEmbeddings` constructor can be called with the correct argument name.

**Comment by helpmefindaname** [comment]
Hello, I think this is due to a typo in [this line](https://github.com/flairNLP/flair/blob/master/flair/embeddings/base.py#L435) which should be `if "operation" in state:`

**Comment by alanakbik** [comment]
@helpmefindaname ah yes that could be the problem!
