### ISSUE TITLE
How to get  IOB NER tags from model predictions?

### ISSUE THREAD

**Issue by elazzouzi1080** [flairNLP/flair#2746]
hello , is it possible, for each token to have the corresponding iob tag 
 
![image](https://user-images.githubusercontent.com/81225479/165768257-4ffeb2ef-d1e1-427c-adb1-1b8bb8f88392.png)
for exemple :

![image](https://user-images.githubusercontent.com/81225479/165768401-f29b206a-e965-48ac-a6ce-6fb25ee1f1a4.png)

**Comment by alanakbik** [comment]
Hello @elazzouzi1080 yes we just merged PR #2750 that adds this feature to the sequence tagger, and will do a release very soon.

After the release, you need to set `force_token_predictions=True`, i.e.
```python
# predict but force Token-level predictions
tagger.predict(sentence, force_token_predictions=True)
```

If you want this feature now, you could run this code: 

```python
tagger = SequenceTagger.load('ner-fast')

sentence = Sentence("George Washington lives in New York")

tagger.predict(sentence)

# transfer entity labels to token level
for entity in sentence.get_spans('ner'):
    prefix = 'B-'
    for token in entity:
        token.set_label('ner-bio', prefix + entity.tag, entity.score)
        prefix = 'I-'

# now go through all tokens and print label
for token in sentence:
    print(token)
```
