### ISSUE TITLE
[Hunflair evaluation] ImportError: cannot import name 'Metric' from 'flair.training_utils'

### ISSUE THREAD

**Issue by minstar** [flairNLP/flair#2756]
Thank you for your commendable efforts to share this nice project! Really nice work so far. 

I'm currently working on evaluating the out-of-domain evaluation using Hunflair codes.

While processing ```evaluate_ann.py``` on this URL (https://github.com/hu-ner/hunflair-experiments)
In my version, I could not import 'Metric' in flair.training_utils.py
My flair version is 0.11.2.

Could you help me to find the correct flair version?
or perhaps help me to evaluate by importing 'Metric'?

**Comment by alanakbik** [comment]
Hello @minstar I think these scripts were written for earlier versions of Flair since the signatures have changed a bit. You could either use an older version of Flair, or perhaps @leonweber @mariosaenger could update the scripts?

**Comment by minstar** [comment]
When I use flair==0.6.1 version (with gensim==3.8.3), I could derive what I wanted!
Thanks for your reply.
