### ISSUE TITLE
All settings the same, but using "make_label_dictionary" and "make_tag_dictionary" to create "tag_dictionary" for NER model give completely different results.

### ISSUE THREAD

**Issue by lixiu911** [flairNLP/flair#2762]
All other settings are the same (same data, same code etc), but using "make_label_dictionary" and "make_tag_dictionary" to create "tag_dictionary" for NER model give completely different results. 

I am training a Swedish NER model, I first trained the model using  "make_tag_dictionary" and got the results but then noticed that "make_tag_dictionary" will be deprecated and it is recommended to use "make_label_dictionary" so I changed to "make_label_dictionary". B-U-T they output completely different results. 
The code and output are as below. Is it a bug or is it something I missunderstand? Thanks!

With "make_tag_dictionary":
![8FC7240F-B2DF-4409-A8B9-D3909612287D](https://user-images.githubusercontent.com/16153200/168145401-45af2921-39f7-476b-a855-d9e0777c5579.png)

Results:
- F-score (micro) 0.4605
- F-score (macro) 0.4535
- Accuracy 0.3011

By class:
              precision    recall  f1-score   support

           B     0.5789    0.3894    0.4656       999
           I     0.6849    0.3257    0.4415       307

   micro avg     0.5978    0.3744    0.4605      1306
   macro avg     0.6319    0.3576    0.4535      1306
weighted avg     0.6038    0.3744    0.4599      1306
 samples avg     0.3011    0.3011    0.3011      1306

With "make_label_dictionary":
![5D0A5C6E-1370-410D-855C-626032F8BEB6](https://user-images.githubusercontent.com/16153200/168145670-0b6fba1a-4852-44ca-9bda-49d91dc4631c.png)

Results:
- F-score (micro) 0.0302
- F-score (macro) 0.2986
- Accuracy 0.0156

By class:
              precision    recall  f1-score   support

       <unk>     0.0000    0.0000    0.0000         0
           B     0.4382    0.4965    0.4655       999
           I     0.5000    0.3779    0.4304       307

   micro avg     0.0156    0.4686    0.0302      1306
   macro avg     0.3127    0.2914    0.2986      1306
weighted avg     0.4527    0.4686    0.4573      1306

**Comment by alanakbik** [comment]
Hello @lixiu911 thanks for reporting this - this looks to be the same problem as in #2761 reported by @NicolasVautier. 

Could one of you provide some minimal sample data + script so we can reproduce this issue? On my datasets it seems to not appear.

**Comment by lixiu911** [comment]
Thanks for your reply Alan. How much data do u need? my data is actually commercial. If you test my data, I have to send you some samples not in the public way. 
(Swedish language, total 26149 sentences. 25% sentences are annotated with some NER. 70%, 20%, 10% for training, validation and test. )

**Comment by alanakbik** [comment]
Thanks @lixiu911 even a very small amount of data would be enough if we can reproduce the error with it. Or different public data that shows the error. We just need to somehow reproduce so we can debug.

**Comment by i4meta** [comment]
@alanakbik - Hi Alan. I wanted to confirm that this ticket is still awaiting some **sample data** for replicating the issue. If it is, I am happy to put some data together and post it to **a location** you all can pull it from - but please specify.

**Comment by i4meta** [comment]
Hi @alanakbik,

Thanks for the answers - some follow-on questions below:

1. **START/STOP Tags** - You mentioned that the < START > and < STOP > tags are used by the CRF layer only. Should we be adding them? Or is Flair injecting them as needed?

2. **Sample Data** - the sample data I have is Connll-03 converted to have inverted IOB tags (position after entity type, e.g.  LOC-B, LOC-I). It helped me understand my issue, but may not be so useful for you. if you confirm you still want it, I'll hit the send button.

3. **Detected NER Tag Format** - Just as food for thought, if might be prudent to log, as part of process, the Detected NER Tag Format and what it is being converted to. Might help avoid some future tickets by informing the user.

**Comment by helpmefindaname** [comment]
about **4.**: there is [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4331690/) and more generally [this](https://arxiv.org/pdf/1603.01360.pdf) 

about **1.**: this is done by the tagger itself, you don't need to add it.
