### ISSUE TITLE
Transformers Update

### ISSUE THREAD

**Issue by hmiche** [flairNLP/flair#2765]
When trying to call 👍 
from flair.data import Sentence
from flair.models import SequenceTagger

got this Error

Failed to import transformers.models.transfo_xl.tokenization_transfo_xl because of the following error (look up to see its traceback):
No module named 'sacremoses'

Quick Solution : Use pip install transformers==4.18.0

**Comment by PartGi** [comment]
Hi @hmiche. I encountered today the same problem and solved it by "pip install sacremoses". 
I got then another one error (module 'flair' has no attribute 'nn'), which did not happen throughout the last two weeks where I used daily the flair framework.

**Comment by hmiche** [comment]
Yeah i got the same problem so i  used an Old version of flair pip install flair==0.11.1

**Comment by alanakbik** [comment]
Strangely, if you install sacremoses first you can install the current version of Flair (just tested on a fresh colab notebook): 
~~~
pip install sacremoses
pip install flair
~~~
I have no idea why it does not work the other way around but am investigating now.
