### ISSUE TITLE
How to move transformer embeddings to from GPU to CPU?

### ISSUE THREAD

**Issue by iliaNecrov** [flairNLP/flair#2766]
As I figured out my **6GB** GPU can't even run [train ner with transformers](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-named-entity-recognition-ner-model-with-transformers) script. I needed it because i wanted to add additional corpus to conll-2003, so I could get better NER results.

After a little research I found out that uploading `TransformerWordEmbeddings` takes **3GB** of my GPU:

```
from flair.embeddings import TransformerWordEmbeddings

xlm= TransformerWordEmbeddings(model='xlm-roberta-large',
                                       layers='-1',
                                       subtoken_pooling="first",
                                       fine_tune=False,
                                       use_context=True,
                                       layer_mean=True #False
                                       )
```
![image](https://user-images.githubusercontent.com/96539972/168394883-f6d3fcfb-06ce-4e82-9633-b4ec6f8d4afa.png)

But if I disable cuda, it doesn't take any space:

```
import os
os.environ["CUDA_VISIBLE_DEVICES"]=""

from flair.embeddings import TransformerWordEmbeddings

xlm= TransformerWordEmbeddings(model='xlm-roberta-large',
                                       layers='-1',
                                       subtoken_pooling="first",
                                       fine_tune=False,
                                       use_context=True,
                                       layer_mean=True #False
                                       )
```
![image](https://user-images.githubusercontent.com/96539972/168395065-97fbe10d-3094-472d-9d15-98fdd4aa96a2.png)

**My question**: is there an opportunity to move embedding model to CPU, so I could use more GPU storage for training?

_P.S. I tried .to_cpu(), .to('cpu') methods. The future usage of embeddings didn't work :(_

**Comment by alanakbik** [comment]
Hello @iliaNecrov, the XLM-R model is very large, especially in combination with `in_context=True` the model requires a large amount of GPU memory. 

You can tell Flair to use only CPU by setting

```python
import flair
flair.device = 'cpu'
```

at the beginning of your code, but this would make everything extremely slow as XLM-R without GPU is not really feasible. 

Possible options are: 
- set a smaller context by setting `use_context=32` 
- setting `mini_batch_chunk_size=1` if you haven't already
- use a different transformer model

**Comment by iliaNecrov** [comment]
@alanakbik thanks a lot!
