### ISSUE TITLE
[Details of Hunflair training]

### ISSUE THREAD

**Issue by minstar** [flairNLP/flair#2771]
In supplementary section 1.2 (Gold Standard NER pre-training), 
the authors described that the training sets are built by taking **the union of the HUNER train and test splits of each data set**.
And also, the validation sets are given by **the union of all HUNER validation splits**.

In HUNER, the authors randomly divided each corpus into three disjoint subsets;
60% of the samples were used for training, 10% as the dev set for the training methods, and 30% for the final evaluation.

Was the training set in HUNFLAIR created by combining the train and test splits in HUNER?
(i.e., Training: 60%+30% = 90%, Validation: 10%)

**Comment by leonweber** [comment]
Hey @minstar,
thank you for your question!
Yes, the training set in HunFlair was created by combining the train and test splits of HUNER. Note, that we did this only for the model which we evaluated in the cross corpus experiments and the final model that we released as the HunFlair tagger. For the pretraining/finetuning experiments (Section 4 in the HunFlair supplement), we only trained on the training splits. Does that help?

**Comment by minstar** [comment]
Hi @leonweber,
thank you for your prompt response!

**Comment by minstar** [comment]
Sorry for reopening the issue.

I want to reproduce an in-domain evaluation (Table 2) of Hunflair paper.
Which model do I have to use it?

**Comment by leonweber** [comment]
Hey @minstar, 

the results should, in principle, be reproducible with the following script. However you would need to retrain a version of HunFlair with the evaluation corpora excluded (information on how to retrain HunFlair is here https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md#training-hunflair-from-scratch). Additionally, you would have to use these word embeddings instead of the `PubMed` ones: https://ftp.ncbi.nlm.nih.gov/pub/lu/Suppl/BioSentVec/BioWordVec_PubMed_ MIMICIII_d200.vec.bin

```python
    import os
    
    from flair.datasets import biomedical
    from flair.models import SequenceTagger
    from flair.trainers import ModelTrainer

    corpus = biomedical.BIOBERT_DISEASE_NCBI()
    base_path = os.path.join(results_path, corpus.__class__.__name__.lower())

    tagger: SequenceTagger = SequenceTagger.load(PATH_TO_RETRAINED_HUNFLAIR)
    trainer: ModelTrainer = ModelTrainer(tagger, corpus)
    trainer.train(base_path=base_path, train_with_dev=False, max_epochs=200,
                  learning_rate=0.1, mini_batch_size=32)


    trainer: ModelTrainer = ModelTrainer(tagger, corpus)

    trainer.train(base_path=base_path, train_with_dev=train_with_dev, max_epochs=200,
                  learning_rate=0.1, mini_batch_size=32)
```
