### ISSUE TITLE
get_embedding() error

### ISSUE THREAD

**Issue by nareshchadoop** [flairNLP/flair#2772]
Getting this below error while using the flair on sample spam.csv. Could you please help me to resolve this issue.

File ~\anaconda3\envs\text_classifier\lib\site-packages\flair\models\text_classification_model.py:66, in <listcomp>(.0)
     64 # make tensor for all embedded sentences in batch
     65 embedding_names = self.document_embeddings.get_names()
---> 66 text_embedding_list = [sentence.get_embedding(embedding_names).unsqueeze(0) for sentence in sentences]
     67 text_embedding_tensor = torch.cat(text_embedding_list, 0).to(flair.device)
     69 labels: List[List[str]] = []
TypeError: get_embedding() takes 1 positional argument but 2 were given.

**Comment by alanakbik** [comment]
@nareshchadoop could you provide a minimal example to reproduce this error?
