### ISSUE TITLE
How and where to add add_unk = True

### ISSUE THREAD

**Issue by fmafelipe** [flairNLP/flair#2777]
Hello, I am training a ner model, apparently I have a wrong tag in my training corpus because during the training process I get this error. 
![errorner](https://user-images.githubusercontent.com/50722626/168899243-e104d09c-a177-4a81-8a70-7f90938c9426.png)

I already checked the corpus several times and I can't find the error, so I want to do what the problem tells me to add add_unk = True, but I don't know where to add it, in what part of the code.
The code I am using is the following

```
from flair.data import Corpus
from flair.datasets import ColumnCorpus
from flair.embeddings import TransformerWordEmbeddings
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer
with tf.device('/device:GPU:0'):


  # 1. get the corpus
  columns = {0:'text',1:'ner'}
  data_folder = '/content/drive/MyDrive/corpus de prueba/entrenamiento1'

  corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='dev.txt')

  print(len(corpus.train))

  # 2. what label do we want to predict?
  label_type = 'ner'

  # 3. make the label dictionary from the corpus
  label_dict = corpus.make_label_dictionary(label_type=label_type)
  print("el diccionario de mi corpus contiene las etiquetas: ",label_dict)

  # 4. initialize fine-tuneable transformer embeddings WITH document context
  embeddings = TransformerWordEmbeddings(model='bert-base-multilingual-cased',
                                       layers="-1",
                                       subtoken_pooling="first",
                                       fine_tune=True,
                                       use_context=True,
                                       )

  # 5. initialize bare-bones sequence tagger (no CRF, no RNN, no reprojection)
  tagger = SequenceTagger(hidden_size=256,
                        embeddings=embeddings,
                        tag_dictionary=label_dict,
                        tag_type='ner',
                        use_crf=False,
                        use_rnn=False,
                        reproject_embeddings=False,
                        )

  # 6. initialize trainer
  trainer = ModelTrainer(tagger, corpus)

  # 7. run fine-tuning
  trainer.fine_tune('resources/taggers/pruebatest',
                  learning_rate=5.0e-3,
                  mini_batch_size=2,
                  max_epochs=5,
                  #mini_batch_chunk_size=1,  # remove this parameter to speed up computation if you have a big GPU
                  )
```

Thanks

**Comment by alanakbik** [comment]
@fmafelipe what Flair version are you on?

**Comment by fmafelipe** [comment]
@alanakbik I am using Colab, it shows that the version "flair-0.11.2" is installed, although to use TransformerWordEmbeddings it had an error and I had to specify the installation of transformers==4.18.0

**Comment by alanakbik** [comment]
We are on Flair 0.11.3 now, perhaps you could test with this version? If the error persists, could you supply a minimal working example with data to reproduce this error?

**Comment by AlphaBit95** [comment]
@alanakbik 

I’m still facing this issue on the version 0.11.3. 

Logs:
2023-01-28 21:58:59,809 The string 'B-' is not in dictionary! Dictionary contains only: ['O', 'S-INNOVATION', 'B-INNOVATION', 'E-INNOVATION', 'I-INNOVATION', 'S-UTILIZATION', 'B-UTILIZATION', 'E-UTILIZATION', 'I-UTILIZATION', 'S-MATERIAL', 'B-MATERIAL', 'E-MATERIAL', 'I-MATERIAL', '<START>', '<STOP>']
2023-01-28 21:58:59,810 You can create a Dictionary that handles unknown items with an <unk>-key by setting add_unk = True in the construction.
  0%| 

I also tried adding the argument explicitly as follows:

tag_dictionary = corpus.make_label_dictionary("ner", add_unk=True)

<img width="616" alt="Screenshot 2023-01-28 at 23 13 36" src="https://user-images.githubusercontent.com/95974539/215293512-38c66ccd-7215-4843-9a91-fad7609c53fe.png">

But it does not seem to be recognised as the get the following error:
    tag_dictionary = corpus.make_label_dictionary("ner", add_unk=True)
TypeError: make_label_dictionary() got an unexpected keyword argument 'add_unk'
