### ISSUE TITLE
Combining BERT and other types of embeddings

### ISSUE THREAD

**Issue by AliHaiderAhmad001** [flairNLP/flair#2782]
A while ago I was upset with the embed merging process and suddenly this amazing library pops up.
You are great!
-------------------------
My question:
The flair model can give a representation of any word (it can handle the OOV problem), while the BERT model splits the unknown word into several sub-words.

For example, the word "hjik" will have one vector represented in flair, while in BERT it will be divided into several words (because it's OOV) and therefore we will have several vectors for each sub word. So from flair we'll have one vector while from BERT we might have two or more vectors.

The question here is how did you handle this case?

**Comment by alanakbik** [comment]
Hello @AliHaiderAhmad001 thanks for using Flair! The `TransformerWordEmbeddings` class has default handling for words split into multiple subwords which you control with the `subtoken_pooling` parameter (your choices are "first", "last", "first_last" and "mean"), see the info here: https://github.com/flairNLP/flair/blob/master/resources/docs/embeddings/TRANSFORMER_EMBEDDINGS.md#pooling-operation

**Comment by AliHaiderAhmad001** [comment]
Thank you very much,
I also thought taking the sum would be fine too, right?
