### ISSUE TITLE
POS span returns empty list on Colab

### ISSUE THREAD

**Issue by PhilWicke** [flairNLP/flair#2783]
Thank you for your dedicated work.
I've been trying to run the POS example from [HuggingFace](https://huggingface.co/flair/pos-english) in a Google Colab. Yet, I cannot retrieve the spans for POS. I've tried various different things, but it always seems to return an empty list and I have used the exact same code as in your tutorial.

I've set up a colab with my issue:
https://colab.research.google.com/drive/1K1NvP8Qg6nM8mVmDr_vNZdE5fQ7aZGdj?usp=sharing

**Comment by alanakbik** [comment]
Hello @PhilWicke - POS tags are saved at the individual Tokens of a sentence and are no Spans. You can access them by doing 

```python
for entity in sentence.get_labels('pos'):
    print(entity)
```

I guess we should either fix the example on Huggingface or restore the functionality that get_spans also returns Token-level annotations.

**Comment by PhilWicke** [comment]
Wow! That was super fast! Thanks a lot.
