### ISSUE TITLE
BIO tag format crashes with IndexError

### ISSUE THREAD

**Issue by cpalenmichel** [flairNLP/flair#2784]
**Describe the bug**
Training an NER model with tag_format="BIO" fails with `The string 'S-ORG' is not in dictionary! Dictionary contains only: ['O', 'B-DATE', 'I-DATE', 'B-LOC', 'I-LOC', 'B-ORG', 'I-ORG', 'B-PER', 'I-PER']` and an IndexError.
It looks like the issue comes from `_get_gold_labels` only converting to BIOES. 

**To Reproduce**
I'm using conll03 English data and my tagger is setup as follows 
```
embeddings = TransformerWordEmbeddings(
                "xlm-roberta-base",
                layers="-1",
                layer_mean=False,
                fine_tune=True
            )
tagger: SequenceTagger = SequenceTagger(
        embeddings=embeddings,
        tag_dictionary=tag_dictionary,
        tag_type=tag_type,
        reproject_embeddings=True,
        use_crf=False,
        use_rnn=False,
        word_dropout=0.0,
        locked_dropout=0.0,
        tag_format="BIO"
    )

```

**Expected behavior**
I expect it to train a model using BIO tags without crashing.

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Linux 5.4.0-100-generic x86_64
 - Version [e.g. flair-0.3.2]: flair==0.11.2

**Additional context**

**Comment by bashayerm** [comment]
I have the same problem, looking for a solution

**Comment by kaliaanup** [comment]
I am having the same issues when I enable tag_format="BIO". It basically gives the following error.

2022-05-25 16:20:11,118 The string 'E-ORG' is not in dictionary! Dictionary contains only: ['O', 'B-LOC', 'I-LOC', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-OTHER', 'I-OTHER', '<START>', '<STOP>']

For now I am bypassing the issue by disabling it. The predictions will be based on spans and BIOES format. Spans or BIOES format can be converted into BIO format.

https://github.com/flairNLP/flair/issues/2790

**Comment by alanakbik** [comment]
@kaliaanup this will be fixed in PR https://github.com/flairNLP/flair/pull/2787

**Comment by salohnana2018** [comment]
I have the same issue, but what is PR?
