### ISSUE TITLE
Mac GPU Utilization Support

### ISSUE THREAD

**Issue by josebarross** [flairNLP/flair#2789]
Torch has just released MAC M1 support using mps device. I want to know if flair will support it. I tried setting the flair.device manually to mps but it failed when running. Thank you in advance

**Comment by alanakbik** [comment]
Thanks for raising this issue @josebarross!

@whoisjones can you check if this works?

**Comment by gojefferson** [comment]
I've run into the same issue as @deakkon. This is still a problem.

**Comment by mileszim** [comment]
@gojefferson just tried to figure this out--with the merge of #3350 I am able to leverage torch with m1 by setting

```python
import flair
import torch

mps_device = torch.device("mps")
flair.device = 'mps:0'
```

then run your code like normal

```python
from flair.data import Sentence
from flair.nn import Classifier

# uses apple GPU
tagger = Classifier.load('ner')

sentence = Sentence("Hello there!")

tagger.predict(sentence)
```
 it works as-is!

**Comment by aburns27** [comment]
### Changes to Enable Flair on MPS (Apple Silicon)

I was working to train/test on data using flair for a project and wanted to use MPS/GPU on Apple Silicon to run it. Example code:

```python
# Move model to MPS device and ensure float32 precision
tagger.to(flair.device)

# Make all model parameters are in float32
for param in tagger.parameters():
    param.data = param.data.float()

# Make all gradients are also calculated in float32
for param in tagger.parameters():
    if param.grad is not None:
        param.grad.data = param.grad.data.float()

# 6. Initialize the trainer
trainer = ModelTrainer(tagger, corpus)

# 7. Train the model without AMP
trainer.train(
    f'resources/taggers/{runname}_mps',
    learning_rate=0.05,
    mini_batch_size=16,
    save_model_each_k_epochs=2,
    monitor_test=True,
    max_epochs=5,
    use_amp=False,
)
```
Here are the changes I had to make:

#### 1. trainer.py
**Location:** `flair/trainers/trainer.py`

**Issue:** `torch.autocast` is used even when AMP was manually disabled (`use_amp=False`), causing a `RuntimeError` on MPS devices.

**Fix:** Made `autocast` only applied when AMP is enabled.

```python
# Original Code:
with torch.autocast(device_type=flair.device.type, enabled=use_amp):
    loss, datapoint_count = self.model.forward_loss(batch_step)

# Modified Code:
if use_amp:
    with torch.autocast(device_type=flair.device.type):
        loss, datapoint_count = self.model.forward_loss(batch_step)
else:
    loss, datapoint_count = self.model.forward_loss(batch_step)
```

#### 2. training_utils.py

**Location:** `flair/training_utils.py`

**Issue:** The `store_embeddings` function tried to pin memory on MPS, causing a NotImplementedError.

**Fix:** Only pin memory for CUDA devices.

```python

# Original Code:
pin_memory = str(flair.device) != "cpu"

# Modified Code:
pin_memory = str(flair.device) == "cuda"
```

**Comment by aditya-malani** [comment]
@aburns27 

I am seeing this error after making the changes you suggested.
RuntimeError: The expanded size of the tensor (2) must match the existing size (24) at non-singleton dimension 0.  Target sizes: [2].  Tensor sizes: [24]
