### ISSUE TITLE
Train with flair==0.11 cause Tensor RuntimeError

### ISSUE THREAD

**Issue by asm-cygu** [flairNLP/flair#2791]
Hello !

**Describe the bug**
I'm trying to reproduce experiments from 
- https://huggingface.co/flair/ner-english-ontonotes-large#training-script-to-train-this-model
- https://github.com/flairNLP/flair/blob/master/resources/docs/EXPERIMENTS.md#ontonotes-named-entity-recognition-english

**To Reproduce**
download official archive from LDC, etc ... and launch the training script

**Expected behavior**
I expected than everythings running, and finally produce my model

**Screenshots**
but I have...
RuntimeError: The expanded size of the tensor (570) must match the existing size (514) at non-singleton dimension 1. ​
Target sizes: [4, 570]. Tensor sizes: [1, 514]​

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Oracle Linux 7
 - Version [e.g. flair-0.3.2]: Flair == 0.11

I can complete informations if needed

**Comment by nunziaBa** [comment]
I repeated the same experiment with the same error. 
The experiment works with version 0.10.
