### ISSUE TITLE
Sequence tagger for ner  

### ISSUE THREAD

**Issue by bashayerm** [flairNLP/flair#2792]
Hi, 

I have a problem regarding the Sequence tagger 

I used to get the  output in this form before 2 months, Entity with BIO tag format
![M1](https://user-images.githubusercontent.com/47773165/170421400-84aa86fc-1f65-4f4f-945c-213d10d65f3f.png)

but Now in the new flair release, I got the output without the BIO format 
![M2](https://user-images.githubusercontent.com/47773165/170421561-64dd5d25-4808-449d-a68b-8e78b1853cda.png)

How can I fix this in my code to get the entity in BIO format?

**Comment by alanakbik** [comment]
You need to set `force_token_predictions=True` to get token level tags in the newest Flair version. See #2790
