### ISSUE TITLE
How can I custom train my data in flair? and get the NER for my data using my labels.

### ISSUE THREAD

**Issue by krutik0204** [flairNLP/flair#2794]
I am currently working on an NLP project. It has news articles data that is unlabeled. So using the Flair Library of NLP, I need to perform NER on it. I couldn't find any help regarding how to train it using custom data in Flair Library. Actually, I have a news article dataset and I need to use the Flair Library of NLP for NER because it's giving an F1 score of 93%. So how can I custom train my data or modify flair library to annotate some more data so that it is able to recognize them and improve?
Can you help me? I have gone through the Train a TARS model tutorial but couldn't train it with my data.

Also when I am training the data, but it's not providing the entity for the labels, you can refer to the screenshots attached here.
![Screenshot from 2022-05-27 15-25-06](https://user-images.githubusercontent.com/72077012/170677851-636d54ab-66c5-4895-99be-a04d43069ae7.png)
![Screenshot from 2022-05-27 15-25-18](https://user-images.githubusercontent.com/72077012/170677857-3e6ce2f0-7d6f-4db4-8089-4edf6068d981.png)

**Comment by stefan-it** [comment]
Hi  @krutik0204 ,

could you post an example of your training data and the `columns` array?
