### ISSUE TITLE
Zero Shot Classification with different TARS-base and Stacked Word Embbedings from transformers

### ISSUE THREAD

**Issue by rafaeloliveirabd** [flairNLP/flair#2795]
Hello! I'm trying to find a good zero-shot classifier and flair + transformers seem to be the way to go. The zero-shot classification I'm trying to achieve should be done through several languages (10-20+), hence I'd like to use models such as these:

"MoritzLaurer/mDeBERTa-v3-base-mnli-xnli"

which have zero-shot-classification purposes itself (https://huggingface.co/MoritzLaurer/mDeBERTa-v3-base-mnli-xnli). I would also like to try "bert-multilanguage-uncased" but I don't think the purpose of that model is for zero-shot classification.

With this being said, is there a way to stack several word embeddings and then use them with the base TARS model from flair? 

I currently have something like this, but I don't know if the `tars-base` is multilanguage or not. The goal is to get the model to predict between 3-5 classes (such as positive and negative and in between)

```



# 1. Load our pre-trained TARS model for English
analyzer = TARSClassifier.load('tars-base')

#Multilanguage embedding 
#QUESTION: how could one integrate other embeddings from Transformers and apply the TARSclassifier?
embed = TransformerWordEmbeddings('MoritzLaurer/mDeBERTa-v3-base-mnli-xnli') 

# 2. Prepare a test sentence
sentence = Sentence("I am so glad you liked it!")

classes = ["positive", "neutral", "negative"]

analyzer.predict_zero_shot(sentence, classes)

print(sentence)

def inp_file(cleanedCol):
    """ 
    Reading the data 
    
    Parameters
    ----------
    : string
        Adress where the data is located
    
    Returns
    -------
    data: dataframe
        Loaded data with encoding format
    """
    analyzer = TARSClassifier.load('tars-base')

    file = input('Enter a file path for the file to be processed (xlsx): ')
    try:
        data = pd.DataFrame(pd.read_excel(file))
        data = data[['Sentiment',cleanedCol]]
    except:
        print(f'\nNo {file} found. Is this the correct path?\n')
    list_result = []
    for index in tqdm(data.index):
        result = analyzer.predict_zero_shot(data.loc[index,cleanedCol], classes)
        #del result["compound"]
        {k:v for k,v in result.items() if v == max(result.values())}
        list_result.extend([k for k,v in result.items() if v== max(result.values())])
    data['Predicted Sentiment'] = list_result

    file_name = input("What is the name of the file you want to save? ")
    path_dir = input("What is the path to save the file with the predicted sentiment? ")
    path_dir = r"{}".format(path_dir)
    isFile = os.path.isdir(path_dir)
    while isFile == False:
        print("Directory doesn't exist. Try again")
        path_dir = input("What is the path to save the file with the predicted sentiment? ")
    else:
        data.to_excel(r'{}\{}.xlsx'.format(path_dir,file_name))
    return data
```
Thank you in advance!

**Comment by nlproc-007** [comment]
tars-base model is not multilingual. tars-base model is BERT model fine-tuned on 9 text classification English datasets under binary classification settings. You can refer this link https://nlp.informatik.hu-berlin.de/resources/models/tars-base/ for more details. @rafaeloliveirabd
