### ISSUE TITLE
Unable to load dynamically quantized zero shot NER model

### ISSUE THREAD

**Issue by shreyassks** [flairNLP/flair#2798]
I wanted to benchmark the latency by quantizing the NER model using Pytorch's Dynamic Quantization. I am able to successfully quantize the model to INT8 precision which reduced the model size from 1.4 GB to 520 MB. But when I save the model and try to load it I am getting below error (Missing Keys in state dict). Can anyone pls help me figure out how to resolve this issue

```
# Loading TARS NER pretrained model
tars = TARSTagger.load('tars-ner')

# Pytorch's Dynamic Quantization on Linear Layers
quantized = torch.quantization.quantize_dynamic(tars, {torch.nn.LSTM, torch.nn.Linear}, dtype=torch.qint8)

# Storing the quantized model's state dictionary
torch.save(quantized.state_dict(), "quantized_model/best-model.pt")

# Loading the quantized model from stored directory
quant_model = TARSTagger.load("quantized_model/best-model.pt")
```

[
<img width="1275" alt="Screenshot 2022-05-31 at 4 28 37 PM" src="https://user-images.githubusercontent.com/44189581/171158610-5a01262a-f899-40f0-9739-60590dd87b94.png">
](url)

**Comment by helpmefindaname** [comment]
Hi @shreyassks 

at first I want to point out that `torch.save(quantized.state_dict(), "quantized_model/best-model.pt")` will never let you load a model via `TARSTagger.load()` the connected function of `TARSTagger.load()` is `tars.save()` and for `torch.save(model.state_dict())` it is `model.load_state_dict(torch.load(...))` the latter is a pytorch build-in and will only save the weights, while the `tars.save()` stores all necessary information to build the model (hyperparameters, embeddings type, weights, etc.)

About your question:
Flair currently doesn't support quantization, as it pickels the embeddings and creates a new model assuming that it is not quantized.
What I used to do is store the model normally, but quantize it directly after loading, so you still get the speed up in inference time, however if you do the quantization mainly for using less disk space, that won't work. For that you could create a new tars model with random weights, quantize it and then load the weights via the `model.load_state_dict(torch.load(...))` option.
Another option could be to check out my recend [pull request](https://github.com/flairNLP/flair/pull/2739) there you can transform the model to ONNX format, quantize via onnx (which is generally recommended, as it also quantizes the embedding layer) and use the flair load/save capabilities like intended.

**Comment by shreyassks** [comment]
Hi @helpmefindaname 
I just tried to export the TARS NER model to ONNX and later I was able to quantise the model as well which brought down the artifact size from 1.4 GB to 340 MB. But I was not able to use the model in ONNX Inference Session. I see the output is token embeddings! How to get the NER tags out of it? Can you share a sample script for reference. This would help me a lot. Thanks in advance

**Comment by helpmefindaname** [comment]
if you have exported the onnx-model via
```
tars.tars_model.embeddings =  tars.tars_model.embeddings.export_onnx("tars-embeddings.onnx", sentences, providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
```
you should be able to just use `tars.save(...)` as usual, with having less memory size. You will have to handle both files, the `.pt` and the `.onnx`

**Comment by shreyassks** [comment]
Thanks for that! I was able to achieve 14x speed up compared to CPU.  Now it's taking 25ms/sentence (GPU+ONNX) and 360 ms/ sentence (CPU)

I also tried to inference on quanitzed model but didn't yield any speedup. I'm using Nvidia A10G GPU which has INT8 tensor cores. Can you suggest what more can be done to speed up further?

**Comment by helpmefindaname** [comment]
CUDA itself doesn't support the operations required for quantization. That is why torch supports it CPU only and ONNX CUDARuntime will be as slow as CPURuntime. You can try out the [TensorRT](https://onnxruntime.ai/docs/execution-providers/TensorRT-ExecutionProvider.html) from NVIDIA, and see if you can get that running.
