### ISSUE TITLE
RuntimeError: The expanded size of the tensor (514) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [8, 514].  Tensor sizes: [1, 512]

### ISSUE THREAD

**Issue by elazzouzi1080** [flairNLP/flair#2801]
Hello, 
Can someone help me to solve this problem I am trying to train a ner model with BERT and BiLSTM+CRF 
![image](https://user-images.githubusercontent.com/81225479/171873123-718cfa66-28f0-484c-a9a6-232a9bca282e.png)

**Comment by kaliaanup** [comment]
I am having similar issues with Flair.

**Comment by stefan-it** [comment]
Hi @elazzouzi1080 and @kaliaanup ,

could you provide an example code snippet for the fine-tuning? I guess RoBERTa is used as model :thinking:

**Comment by kaliaanup** [comment]
Hey @stefan-it I was using a custom pretrain model based on google/rembert. For some odd reasons in self.tokenizer.model_max_length was coming larger than LARGE_INTEGER. This resulted in making self.truncate = False. Hence, the issue. So I kind of hacked it to fix self.tokenizer.model_max_length=256 [or any number less than LARGE_INTEGER. This solved the issue.

**Comment by stefan-it** [comment]
Hi @kaliaanup,

thanks for the explanation! I'm currently trying to reproduce it and:

```
In [1]: from transformers import AutoTokenizer

In [2]: tokenizer = AutoTokenizer.from_pretrained("google/rembert")
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 263/263 [00:00<00:00, 136kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.48M/4.48M [00:00<00:00, 41.7MB/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8.31M/8.31M [00:01<00:00, 6.80MB/s]

Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [00:00<00:00, 95.0kB/s]

In [3]: 

In [3]: 

In [3]: tokenizer.model_max_length
Out[3]: 256
```

correctly outputs 256, and the current Flair code also uses the `model_max_length`:

https://github.com/flairNLP/flair/blob/3ba253cd7b81ecdd5d023c17b9c0d9ca1bd27219/flair/embeddings/base.py#L217

Are you using the latest master version of Flair?

**Comment by kaliaanup** [comment]
Yes I am using the latest version and also I guess the error came from creating a custom pre-training model using the Rembert architecture.

**Comment by elazzouzi1080** [comment]
But with TransformerWordEmbeddings I have this error
![image](https://user-images.githubusercontent.com/81225479/175048809-000d1a9b-611e-40a7-b64b-537af9a1dc9b.png)

**Comment by PanosBn** [comment]
Hi, I have the same problem when trying to finetune a dutch RoBERTa model (https://huggingface.co/pdelobelle/robbert-v2-dutch-base) for NER. Using a custom tokenizer and setting a max_length doesn't seem to help.

**Comment by bijeanghafouri** [comment]
> When I manually uploaded the model
> 
> ![image](https://user-images.githubusercontent.com/81225479/175056443-a3673076-83a2-4968-8500-f59c62e45a09.png)

Any update on this issue? I have the same problem.

**Comment by Guust-Franssens** [comment]
I also ran across this issue whilst using camembert. I believe the reason for this issue is that Camembert's tokenizer config specifies "model_max_len" and not "model_max_length" as Flair expects it.

By passing model_max_length as argument to the TransformerWordEmbeddings, the error dissapears.

```python
embeddings = TransformerWordEmbeddings(
    "path/to/model",
    layers="-1",
    subtoken_pooling="first",
    fine_tune=True,
    use_context=True,
    allow_long_sentences=True,
    model_max_length=512
)
```

This also makes it so that the following warning no longer appears:
```python
>>> No model_max_length in Tokenizer's config.json - setting it to 512. Specify desired model_max_length by passing it as attribute to embedding instance.
```

**Comment by lxw0109** [comment]
> model_max_length

I came across the same problem

**Comment by lxw0109** [comment]
> Hi, I have the same problem when trying to finetune a dutch RoBERTa model (https://huggingface.co/pdelobelle/robbert-v2-dutch-base) for NER. Using a custom tokenizer and setting a max_length doesn't seem to help.

I came across the same problem, did you figure it out?

**Comment by Bourhano** [comment]
> > When I manually uploaded the model
> > ![image](https://user-images.githubusercontent.com/81225479/175056443-a3673076-83a2-4968-8500-f59c62e45a09.png)
> 
> Any update on this issue? I have the same problem.

you can simply do:
`tokenizer.model_max_length = 512  #  or model.config.max_position_embeddings`

**Comment by stefan-it** [comment]
Additionally: `model_max_length=512` is also working :hugs:

**Comment by Guust-Franssens** [comment]
@lxw0109 As I have mentioned previously, simply pass model_max_length as an argument 
> By passing model_max_length as argument to the TransformerWordEmbeddings, the error dissapeared for me.
> 
> ```python
> embeddings = TransformerWordEmbeddings(
>     "path/to/model",
>     layers="-1",
>     subtoken_pooling="first",
>     fine_tune=True,
>     use_context=True,
>     allow_long_sentences=True,
>     model_max_length=512  # pass length
> )
> ```
> 
> This also makes it so that the following warning no longer appears:
> 
> ```python
> >>> No model_max_length in Tokenizer's config.json - setting it to 512. Specify desired model_max_length by passing it as attribute to embedding instance.
> ```

**Comment by helpmefindaname** [comment]
@YanJiangJerry for which model?

**Comment by MohamadSobhi** [comment]
i have the same issue and i solved it by considering both padding and truncation, like this:
`tokenizer(examples["text"],  padding='max_length', truncation=True, max_length=122)`

**Comment by ftmthb** [comment]
I encountered this issue and then figured out it's because I set truncation = False and return_overflowing_tokens = True because I didn't want to lose any data or information. As a result, the tokenized sentences or documents didn't have the same length; some exceeded 512 tokens, which is the maximum for most models, which justifies why the expected size is different from the received size. So in my case, I decided to truncate some of the data by setting truncation = True, and it solved this issue, but does not include working with the whole data.

**Comment by heukirne** [comment]
It works for me:

```
embeddings = TransformerWordEmbeddings(model='path/to/model',
                           layers="all",
                           subtoken_pooling="first",
                           fine_tune=True,
                           use_context=True, 
                           transformers_tokenizer_kwargs={'model_max_length': 512}  ## tokenizer params
                           )
```
