### ISSUE TITLE
Is the final model the best model?

### ISSUE THREAD

**Issue by MattesR** [flairNLP/flair#2810]
Hi,
When using the ModelTrainer and calling `trainer.fine_tune` with max_epochs, only a `final-model.pt` is stored, no best model. Is that final model the best model or is it the model which was created after the last epoch, regardless of whether there were better models during previous epochs? If so, how to get the best model?

**Comment by MattesR** [comment]
I feel inclined to bump this question, as I can't figure it out.
Was the naming/storing of the model changed in 0.11? It is still referred to in the description of release 0.10.

**Comment by stefan-it** [comment]
Hi @MattesR ,

could you try to use the latest version of Flair and post the complete `fine_tune()` call :thinking: 

Here's an example call that I've used in my experiments:

https://github.com/dbmdz/clef-hipe/blob/main/experiments/clef-hipe-2022/flair-fine-tuner.py#L104-L113

When you set `use_final_model_for_eval=False` a best model is stored and it is also used for the evaluation at the end. In this setup, "best-model.pt" is "really" the best model, whereas "final-model.pt" is the model after the last epoch of fine-tuning, which is not always the best one.

**Comment by MattesR** [comment]
Hi @stefan-it, 
thanks for clearing this up! 
I indeed did not set `use_final_model_for_eval=False`. The model accordingly just used the final model for evaluation. 
I'm really glad for the clarification. Alas, I got to rerun a few experiments :grin: 
Kind Regard
