### ISSUE TITLE
Annotaion Scheme of CRAFT and BIONLP13CG dataset

### ISSUE THREAD

**Issue by possible1402** [flairNLP/flair#2818]
The list in [https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_CORPORA.md](url) shows the entity types of CRAFT and BIONLP13CG datasets include “Species”. While I check the original paper, there is no "Speicies" category, insead, the "cell line" category is included. So I wanna ask if there is any reference for the annotation entity type for the list.

**Comment by mariosaenger** [comment]
Hi @possible1402 

sorry for the late response. For the training of HunFlair on multiple corpora we have to normalize corpus-specifiy entity types resp. type names to a unified form. This mapping was done manually. Unfortunately, you can find this mapping only in the source code in the respective entity type specific version of the corpora (e.g. HUNER_SPECIES_CRAFT_V4 or HUNER_SPECIES_BIONLP2013_CG, etc). For example, for CRAFT_V4 we use the "ncbitaxon" annotations for species:

https://github.com/flairNLP/flair/blob/f53a85dd0b6d83d941585d8d1001d075c3b163bf/flair/datasets/biomedical.py#L4795

For BIONLO2013_CG we use "Organism":

https://github.com/flairNLP/flair/blob/f53a85dd0b6d83d941585d8d1001d075c3b163bf/flair/datasets/biomedical.py#L4883
  
Best,
Mario

**Comment by possible1402** [comment]
Hi @mariosaenger 

Thanks for your response. I understand that for species, you do the entity type mapping. If so, I saw that there are "cell line" type in the original CRAFT and "cell" type in BIONLP13CG dataset. So I'm wondering that since HunFlair covers the cell line entity type, why the "cell line" entities in CRAFT and BIONLP13CG dataset are not included. 

Best,
Liangping

**Comment by mariosaenger** [comment]
Hi @possible1402 ,

oh - I'm afraid I misunderstood your question. For CRAFT, we excluded the CL annotations, because they "only" contain cells but not cell lines (see description [here](https://github.com/UCDenver-ccp/CRAFT/tree/master/concept-annotation)). For BioNLP13CG, we were not aware that the corpus also holds cell annotations. But again, here one has to check whether the annotations are targeting cells or cell lines.

Best,
Mario

**Comment by possible1402** [comment]
Hi @mariosaenger ,

Thanks for your explanation. All clear!

Best,
Liangping
