### ISSUE TITLE
Can't export ner-large to pth

### ISSUE THREAD

**Issue by ledniy** [flairNLP/flair#2830]
**Describe the bug**
Can't export `ner-large` model to pth, getting small file (19mb), but when I'm doing the same with `ner` model I'm getting 400+ mb pth file

**To Reproduce**
```
from flair.models import SequenceTagger
import torch

# Will download the model with pre-trained weights
model = SequenceTagger.load('ner-large')

# Saving the model to disk
torch.save(model, "flair_model_large.pth")
```

**Expected behavior**
pth file with size ~2gb

**Environment (please complete the following information):**
 - OS: Amazon Linux , ml.c4.4xlarge
 - Version: flair-0.11.3

**Additional context**
I'm doing it for deploying the model to SageMaker, I wasn't able to find an up-to-date guide, so mb there are some other options to do it?

**Comment by helpmefindaname** [comment]
hey @ledniy have you tried `model.save(...)`?
