### ISSUE TITLE
Can't download biomedical abstracts of HunFlair

### ISSUE THREAD

**Issue by possible1402** [flairNLP/flair#2836]
Dear Flair developers,

I try to process the biomedical NER datasets used in HunFlair and I use the code from flair/datasets/biomedical.py. While downloading the datasets, some requsts errors occur. I'm wondering if you can share the dataset directly in a google drive maybe?

Thanks  for your help!

**Comment by whoisjones** [comment]
hi @possible1402, can you specify please datasets used + error you get?
