### ISSUE TITLE
Questions on TARS data set-up and prediction scores

### ISSUE THREAD

**Issue by isaac-kelleher-unger** [flairNLP/flair#2852]
Hi there,

**Background:**
I am using a few-shot TARS model to label sentence sentiment as one of 3 possible classes: class_a, class_b, or class_c.

**Questions 1:**
If my sentences are multiple lines long (e.g. _"This is a sentence. And this is another sentences related to the first sentence. This is my final sentence."_) what is the best way to format this for few-shot TARS? Can the entire phrase be passed as a sentence object? Or should each sentence be separated and made into its own sentence object?

**Question 2:**
I am finding that many of my sentences are being labelled with 2 labels and the associated probabilities e.g. "_class_a (0.7000), class_b (0.3000)_". However, when sentences are labelled like this, they are reported as a mismatch in the `dev.tsv` and `test.tsv` output files. 

I have a hack-ey work around where I: (1) load the final model, (2) run `model.predict` (3)  extract the `get_label().value` and `get_label().score` for each sentence, (4) select the label with the highest probability, and (5) recalculate metric.

I wanted to know though: can the predict function be run such that it only considers the label with the highest probability?"

Thanks!

**Comment by helpmefindaname** [comment]
About Question 1:
A `Sentence` is more representing a textual unit which you want to classify. The length does not matter, as long as you are not over the subtoken limit of the underlying transformer model (usually 512).

About Question 2:
It sounds to me like you want to use `tarsmodel.predict_zero_shot(sentence, label_candidates, multi_label=False)`
