### ISSUE TITLE
error: Microsoft Visual C++ 14.0 or greater is required

### ISSUE THREAD

**Issue by QuiteHorn** [flairNLP/flair#2854]
I'm trying to install Flair in my venv in PyCharm, but it tells me to download Visual C++. I have already installed the ditributives of 14.32.31332 version but it still throws the mistake. I also downloaded Visual Studio Build Tools 2019, but it didn't help me too.
![error](https://user-images.githubusercontent.com/63408009/177660173-618a7967-8a70-4144-9c4b-50795052c65c.PNG)
![с++](https://user-images.githubusercontent.com/63408009/177660234-203e965b-f0cf-4b5e-a8c6-25df28c13ea1.PNG)

**Comment by sbwiecko** [comment]
There is an issue with the current version 0.11.3 and this should be solved with version 0.12 in a few weeks, see the details [there](https://github.com/flairNLP/flair/issues/2833#issue-1282620313).
For the time being, you can install the patched version from the Master/Main branch `pip install git+https://github.com/flairNLP/flair`
