### ISSUE TITLE
module 'conllu' has no attribute TokenList

### ISSUE THREAD

**Issue by yash-rathore** [flairNLP/flair#2859]
![image](https://user-images.githubusercontent.com/63536277/178562229-5b6595c0-218b-4db9-978b-fafbfd1508ed.png)

This did not happen till today . I have been using this basic code for 6 months and this bug is new and did not appear anytime before today. 
Please resolve quickly

**Comment by helpmefindaname** [comment]
Hey @yash-rathore, looking at the conllu [release notes](https://pypi.org/project/conllu/#history) it looks like they released a new version that seems to change the structure.
I suppose you can fix your issue by pinning the version `conllu<=4.4.2` to ensure that you install a version that is still compatible.

**Comment by hbailla** [comment]
I have the same issue. The strange thing is I have this error when I run the code on Google Colab , while it works fine on my local machine

**Comment by hbailla** [comment]
> Hey @yash-rathore, looking at the conllu [release notes](https://pypi.org/project/conllu/#history) it looks like they released a new version that seems to change the structure. I suppose you can fix your issue by pinning the version `conllu<=4.4.2` to ensure that you install a version that is still compatible.

This works just fine. Thank you SO MUCH

**Comment by yash-rathore** [comment]
> conllu<=4.4.2

This works absolutely fine . Thankyou for resolving this issue

**Comment by pallashadow** [comment]
another option: add these 2 lines before import flair
`
import conllu
conllu.TokenList = conllu.models.TokenList
`

**Comment by EmilStenstrom** [comment]
Thank you for reporting. I just released 4.5.1 which makes TokenList available as an import directly from conllu, and declares the public API via `__all__`.

**Comment by helpmefindaname** [comment]
Thank you @EmilStenstrom,
yes this fixes the issue!

**Comment by alanakbik** [comment]
Awesome @EmilStenstrom thanks for fixing this so quickly! And thanks @helpmefindaname for testing!

**Comment by EmilStenstrom** [comment]
This issue can be closed, as it has been fixed in conllu 6 months ago.
