### ISSUE TITLE
Can I use TransformerDocumentEmbeddings to generate embeddings of publications abstracts ?

### ISSUE THREAD

**Issue by pruthvi-hegde** [flairNLP/flair#2867]
I am working on a usecase where I need to generate document embeddings of abstracts of few articles.
I am using TransformerDocumentEmbeddings to instantiate PubMedBert model. And, it generates 768 dimensional vector per document. Since, flair documentation says that the input to TransformerDocumentEmbeddings is a sentence, is it fair to feed in paragraph of multiple sentences  and obtain embeddings this way ?

**Comment by whoisjones** [comment]
Yes you can obtain your embeddings this way, flair's Sentence object does not necessarily end with "."

**Comment by pruthvi-hegde** [comment]
Thank you @whoisjones 

Is there any documentation that I can refer to understand the internal working of 'TransformerDocumentEmbeddings' class ?
Basically I want to know how 'TransformerDocumentEmbeddings' calculates embedding for a given paragraph.

Thanks in advance!
