### ISSUE TITLE
Trouble loading in Sentiment140 dataset (UnincodeEncodeError)

### ISSUE THREAD

**Issue by Datagits** [flairNLP/flair#2868]
`corpus = flair.datasets.SENTIMENT_140()`

--------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
Input In [62], in <cell line: 1>()
----> 1 corpus = flair.datasets.SENTIMENT_140()

File ~\Anaconda3\lib\site-packages\flair\datasets\document_classification.py:1075, in SENTIMENT_140.__init__(self, label_name_map, tokenizer, memory_mode, **corpusargs)
   1073             label = row[0]
   1074             text = row[5]
-> 1075             train_file.write(f"__label__{label} {text}\n")
   1077 # create test.txt file from CSV
   1078 with open(data_folder / "test.txt", "w") as train_file:

File ~\Anaconda3\lib\encodings\cp1252.py:19, in IncrementalEncoder.encode(self, input, final)
     18 def encode(self, input, final=False):
---> 19     return codecs.charmap_encode(input,self.errors,encoding_table)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\x9a' in position 12: character maps to <undefined>

**Comment by whoisjones** [comment]
can you specify further information such as os, environment, etc. as required in the template? otherwise I can't reproduce it
