### ISSUE TITLE
🎓 New position for PhD candidate available at HU Berlin!

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#2874]
Hello all, 

we now have another **position for a PhD candidate** available! It is a full-time and fully paid research associate position in my group, intended for persons with a master degree in computer science that aim to pursue a PhD in machine learning or NLP. 

**The project:** This is the first of multiple positions in a big project in which we aim to create powerful language models a la BERT and GPT-3 - but with the difference that our models should only require a fraction of the computational resources and data to train. We will therefore take a deep look at the internals of language models and pursue algorithmic improvements of training objectives and internal representations.

**To apply:** If you're looking to pursue a PhD in this topic, consider applying! You should: 

- have an M.Sc. degree (or be close to graduating) in computer science or computational linguistics  with a focus on ML and NLP
- already have relevant experience in deep learning research, for instance gathered as part of your M.Sc.
- strong coding skills, especially in deep learning frameworks such as PyTorch
- ideally have your first publications
- love open source
- love NLP ;)

(Note that the M.Sc. is a mandatory requirement, as otherwise we cannot initiate the formal hiring process.)

The link to the job ad is [here](https://www.personalabteilung.hu-berlin.de/de/stellenausschreibungen/wiss-mitarbeiter-in-m-w-d-mit-vorauss-vollzeit-e-13-tv-l-hu-drittmittelfinanzierung-befristet-bis-30-06-2024) (in German) - applications can be in English, as the working language of our research group is English. **Consider applying**, and contact me in case of interest! 

Cheers, 
Alan

**Comment by Dashulkin** [comment]
@alanakbik Dear Alan, 
thank you for posting this news. Is there a place available?

**Comment by alanakbik** [comment]
@Dashulkin the deadline has already passed, sorry! But more positions will be posted next year!
