### ISSUE TITLE
Error resuming training of a NER model

### ISSUE THREAD

**Issue by fmafelipe** [flairNLP/flair#2886]
I want to resume training a NER model as shown in the tutorials, loading the model checkpoint but running it with :

`trainer.resume(trained_model,
               base_path=path + '-resume',
               max_epochs=25,
               )`

It simply shows me the metrics of the loaded model and does not perform any training.

**Comment by helpmefindaname** [comment]
hi @fmafelipe ,
setting `max_epochs=25` means that the model will be trained for a total of 25 epochs, not for additional 25 epochs.
if you have already trained the model for 25 epochs, then the model will be trained for 0 epochs (e.g. not at all).

**Comment by fmafelipe** [comment]
Hi @helpmefindaname 
So following this example, if I want to train the model for an additional 25 epochs, do I need to set `max_epochs=50` ?
Thanks for the help

**Comment by helpmefindaname** [comment]
assuming that you trained for 25 epochs, yes.


If you are using the latest master branch, (where https://github.com/flairNLP/flair/pull/2895 is merged) you can also use `additional_epochs=25` instead.

**Comment by fmafelipe** [comment]
Thank you so much 👍👌
