### ISSUE TITLE
Loading a model creates warning; its annoying.

### ISSUE THREAD

**Issue by tbachlechner** [flairNLP/flair#2890]
In version `flair == 0.11.3` and `huggingface_hub == 0.8.1` loading a HuggingFace model creates a warning. To reproduce:
```
>>> from flair.models import MultiTagger
>>> models = ["flair/chunk-english"]
>>> MultiTagger.load(models)
/home/ubuntu/.local/lib/python3.9/site-packages/huggingface_hub/file_download.py:560: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
...
```
This is because `flair.models.sequence_tagger_model` caches models using `from huggingface_hub import hf_hub_download, hf_hub_url`. This is not recommended as of `huggingface_hub == 0.8.1`, see https://github.com/huggingface/huggingface_hub/releases. Warning is annoying.

**Comment by helpmefindaname** [comment]
Hi @tbachlechner, have you checked it that warning still comes on the main branch? afaik this is already fixed but not released

**Comment by tbachlechner** [comment]
@helpmefindaname I see PR #2842 that was closed and is not on master. What's the "main" branch? Is there a separate branch that goes to releases? I do see that PR is identical to mine :)

**Comment by helpmefindaname** [comment]
sorry I meant the master branch.
the PR you mentioned was closed, because https://github.com/flairNLP/flair/pull/2837 got merged.
can you try out the master and see if the problem still occours?

**Comment by tbachlechner** [comment]
oh yeah all good, master is identical to my PR :D sorry about that. can't wait for that release
