### ISSUE TITLE
Conll_03 Corpus

### ISSUE THREAD

**Issue by taghreed34** [flairNLP/flair#2894]
When I try to create an instance of Conll_03 corpus the following error shows up:

No such file or directory: '/root/.flair/datasets/conll_03'

**Comment by Carlee003** [comment]
Hi, have you resolved this problem?

**Comment by Wapiti08** [comment]
> Hi, have you resolved this problem?

There should be a warning that tells you where the system is looking for the dataset. The link should be there as well. You just need to build a folder and download the dataset into that folder.

```
WARNING: CoNLL-03 dataset not found at "/xxx/.flair/datasets/conll_03".
 Instructions for obtaining the data can be found here: https://www.clips.uantwerpen.be/conll2003/ner/"
```
