### ISSUE TITLE
How can I assure the best model is saved?

### ISSUE THREAD

**Issue by Flowhill** [flairNLP/flair#2924]
I'm confused by the parameters given in https://github.com/flairNLP/flair/blob/493b61fc07f83d412928301571b0e3abe780348f/flair/trainers/trainer.py#L74
and the conditions shown in https://github.com/flairNLP/flair/blob/493b61fc07f83d412928301571b0e3abe780348f/flair/trainers/trainer.py#L796
`               if (
                    (not train_with_dev or anneal_with_restarts or anneal_with_prestarts)
                    and not param_selection_mode
                    and current_epoch_has_best_model_so_far
                    and not use_final_model_for_eval
                ):
                     log.info("saving best model")
                     self.model.save(base_path / "best-model.pt", checkpoint=save_optimizer_state)`

It seems that by default a best-model.pt should be saved, however I can only find a final-model.pt in my output folder
My fine_tune arguments are:

`    trainer.fine_tune(
        classifier_save_path,
        learning_rate=0.05,
        mini_batch_size=4,
        mini_batch_chunk_size=None,
        max_epochs=1,
        train_with_dev=False,
        checkpoint=False,
        embeddings_storage_mode='none',
        **kwargs
    )`

As I am training large models I'm currently only testing with max_epochs=1, but I don't think that should prevent the best-model.pt from being saved?

**Comment by alanakbik** [comment]
@Flowhill try setting `use_final_model_for_eval=False`. The default setting of `fine_tune` currently uses the final model for evaluation, though this should likely be changed.

**Comment by Flowhill** [comment]
That should do the trick. Thank you.
I'll update if it worked.
