### ISSUE TITLE
Flair Question - Transformer Document Embeddings

### ISSUE THREAD

**Issue by brianferrell787** [flairNLP/flair#2925]
I know you can do something like this: 
``` python
from flair.embeddings import TransformerDocumentEmbeddings

init embedding
embedding = TransformerDocumentEmbeddings('roberta-base')

create a sentence
sentence = Sentence('The grass is green .')

embed the sentence
embedding.embed(sentence)
```

Which pulls whatever model from the HuggingFace Library. Can the part that says "roberta-base" be from a local file as well? The company I work for, their firewall does not allow us to do that and we have to download files manually from HuggingFace website. And I really wanted to use this functionality for a NLP project. Maybe if not, you know of a work around for doing it. I know that transformers have a local_files_only capability but I was not sure if this applied to this package. 
Thanks!

**Comment by lukasgarbas** [comment]
Yes, you can load a model from your local directory as well. I am doing it as follows:

```
# Download a model from HuggingFace Hub
# git lfs install
# git clone https://huggingface.co/google/electra-small-discriminator local_models/electra
```

```python3
from flair.embeddings import TransformerDocumentEmbeddings
from flair.data import Sentence

# load a model from your local directory
embedding = TransformerDocumentEmbeddings('local_models/electra')

# create a sentence
sentence = Sentence('The grass is green .')

# embed the sentence
embedding.embed(sentence)
```

Let me know if this works for you!

**Comment by brianferrell787** [comment]
Works!
