### ISSUE TITLE
Change in representation of to_tagged_string() function in flair NER Task

### ISSUE THREAD

**Issue by Akarsh1** [flairNLP/flair#2929]
The sample code for the NER is as follows:

model = SequenceTagger.load('ner-large')
s = Sentence("RTI response reveals 18 lakh ration card application pending UP 56 8 request rejected India News Firstpost")
model.predict(s)
print(s.to_tagged_string())

**Actual Output(Now):**
 Sentence: "RTI response reveals 18 lakh ration card application pending UP 56 8 request rejected India News Firstpost" → ["RTI"/ORG, "UP"/ORG, "India News Firstpost"/ORG]

**Expected Output(Earlier):** 
RTI <S-ORG> response reveals 18 lakh ration card application pending UP <S-ORG> 56 8 request rejected India <B-ORG> News <I-ORG> Firstpost <E-ORG>

**Do you have any updates on this change in the representation of the outputs?**

**Comment by surferfelix** [comment]
Same problem here. Also with to_dict.

**Comment by alanakbik** [comment]
Hello @Akarsh1 we refactored the printouts for Flair release 0.11 (see the [release notes](https://github.com/flairNLP/flair/releases/tag/v0.11) under "Major Refactorings"). Our goal is to make the printouts easier to read - feedback welcome!

**Comment by helpmefindaname** [comment]
Notice there are several text methods, depending on what exactly you want:
```
# Sentence: "RTI response reveals 18 lakh ration card application pending UP 56 8 request rejected India News Firstpost" → ["RTI"/ORG, "UP"/ORG, "India News Firstpost"/ORG]
print(s.to_tagged_string())

# RTI response reveals 18 lakh ration card application pending UP 56 8 request rejected India News Firstpost
print(s.to_original_text()) # or print(s.text)
# reconstructs the original text as good as possible (recreates the correct amount of spaces between tokens, no matter if 0 or 20)

# RTI response reveals 18 lakh ration card application pending UP 56 8 request rejected India News Firstpost
print(s.to_tokenized_string())
# puts exactly 1 space between each token

# RTI response reveals 18 lakh ration card application pending UP 56 8 request rejected India News Firstpost
print(s.to_plain_string())
# same as `s.to_original_text()` but removes leading spaces of the sentence.
```

maybe one of the other sentences is more suitable for your use case
