### ISSUE TITLE
Error while loading a Flair model

### ISSUE THREAD

**Issue by Madhu000** [flairNLP/flair#2935]
I am getting this error when loading a trained model by SequenceTagger.load() function:

TypeError: __init__() got an unexpected keyword argument 'force_max_length'

![error](https://user-images.githubusercontent.com/42236983/188659328-b7bc5a8e-dd29-42fc-b2d5-e2208c68ab60.jpg)

**Comment by agademic** [comment]
Can you please provide any solution as I am getting the same error?
