### ISSUE TITLE
Doubts around NER

### ISSUE THREAD

**Issue by NiteshMethani** [flairNLP/flair#2942]
Hi,

I have pre-trained FastText as well as bert-base-uncased on custom corpus.
How can I use it for NER training?

Specifically, is something like this possible in flair:
```
embedding_types = [
    WordEmbeddings('path to custom fasttext vectors'), # .txt file generated from fasttext
    FlairEmbeddings('path to custom flair-forward vectors'),
    FlairEmbeddings('path to custom flair-backward vectors'),
]
```

Furthermore, 
When we use this as embedder, what happens behind the scenes?
```
embeddings = TransformerWordEmbeddings(model='xlm-roberta-large',
                                       layers="-1",
                                       subtoken_pooling="first",
                                       fine_tune=True,
                                       use_context=True,
                                       )
```
- Is it simply taking the token embeddings from 'xlm-roberta-large' and puts a linear layer for NER on top of it? 
- Where exactly FLERT's functionalities are used? Are they automatically handled behind the scenes?
    - If yes, how can I turn off FLERT's features so that I can compare the gains we are getting before and after using FLERT
- I have pre-trained "bert-base-uncased" on custom dataset. How should I use this instead of "xlm-roberta-large"?
- Any suggestions on whether or not we should use CRF layer on top of bert embeddings for NER tasks
- The flag "use_rnn" what exactly it does? If I switch it off, what does it do? Will it switch off char-rnn layer or word-rnn layer?

I know these are lot of questions but simplicity of Flair enabled me to quickly run experiments and hence the curiosity :)

-Nitesh

**Comment by lukasgarbas** [comment]
I'll try to answer your bullet points on transformers and NER:

- Yes, when fine-tuning a transformer, a linear layer is added on top. This happens in the SequenceTagger class and not in TransformerWordEmbeddings. To fine-tune your transformer and a tagger, disable RNN and CRF, which leaves only a linear layer ([docs on how to tune a transformer](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-named-entity-recognition-ner-model-with-transformers)). 

```python
tagger = SequenceTagger(hidden_size=256,
                        embeddings=embeddings,
                        tag_dictionary=label_dict,
                        tag_type='ner',
                        use_crf=False,
                        use_rnn=False,
                        reproject_embeddings=False,
                        )
```
- FLERT (i.e. document-level features for NER) can be used by setting use_context to true/false: ```TransformerWordEmbeddings(use_context=True)```
- You can load your pre-trained transformer model from a local directory. Maybe this will help #2925 
- If you are fine-tuning a transformer, CRF layer usually does not improve scores by much. However, if you are using a frozen model (`fine_tune=False`), you should add the RNN-CRF model on top. I'm referring to some tables in the [FLERT paper](https://arxiv.org/pdf/2011.06993.pdf).
- `use_rnn` adds RNN layer on top of your word embeddings. Any kind of word embedding class will assign each word an embedding (keeping in mind that with transformers we usually take the first sub-word `subword_pooling='first'` to represent a word). So I would say that the top RNN in sequence tagger is word-level.

I hope this answers some of your questions!

**Comment by NiteshMethani** [comment]
Thank you so much for the detailed response. It clears my doubts.
I will try to replicate the results on conll2003 dataset and share for future references.
