### ISSUE TITLE
getting "Runtime Error: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! "

### ISSUE THREAD

**Issue by KINJALMARU16** [flairNLP/flair#2946]
Hi, 
I have trained a custom Sequence2Serquence model for NER on CPU. and When I am using the model on inference data I a getting below error.
However, for the inference , I am using GPU environment. 
Do you know how to train a Flair NER model which can be used in both CPU & GPU ? 

![image](https://user-images.githubusercontent.com/17974502/191610980-a367722b-f0ab-4b29-9d6a-dd6939618e91.png)

**Comment by KINJALMARU16** [comment]
Hi,
Does anyone have any idea about this?

**Comment by alanakbik** [comment]
Could you provide more details on this? What Flair model class did you train?

**Comment by KINJALMARU16** [comment]
I have Trained Seq2Seq NER model with max epoch - 40 on CPU environment.
Please find below image of how I have trained the model
![image](https://user-images.githubusercontent.com/17974502/197828922-c7ea5788-bb6e-4b97-bfa9-40f10db3b6f1.png)

But when I am using the trained model text it is giving me error which is mentioned in question 
while using GPU environment.

**Comment by KINJALMARU16** [comment]
Hi Alan, 

thanks for responding. 
I am converting the model to joblib first and then using predict function.

```python
tagger: SequenceTagger = joblib.load(file_obj)

sentence: Sentence = Sentence('keyboard not working')
tagger.predict(sentence)
```

On this I am getting below error.
![image](https://user-images.githubusercontent.com/17974502/198499999-4251b9c2-519e-4de6-b905-358deea73262.png)

**Comment by KINJALMARU16** [comment]
Hi @alanakbik , Sorry for the trouble , there was some problem in converting the joblib. It worked on different model which I trained already. 

Thanks :)

**Comment by alanakbik** [comment]
No problem! I am not familiar with `joblib` - if I may ask: what advantages does it give you if you use it with Flair?

**Comment by KINJALMARU16** [comment]
Nothing as such , We just wanted to standardize all the models in production.
