### ISSUE TITLE
How to change the cuda:0

### ISSUE THREAD

**Issue by yaoysyao** [flairNLP/flair#2952]
I found that the default is 'cuda:0', now I want to modify to a different graphics card,such as '6,7,8' how do I set it?
![image](https://user-images.githubusercontent.com/38513384/193173773-d82e75d5-9063-4f68-8bf2-f2e45e52a4cf.png)

**Comment by alanakbik** [comment]
At the beginning of your code, set the global variable: 

```python
import flair

flair.device = torch.device("cuda:6")
```

**Comment by yaoysyao** [comment]
> At the beginning of your code, set the global variable:
> 
> ```python
> import flair
> 
> flair.device = torch.device("cuda:6")
> ```

Thanks very much
