### ISSUE TITLE
Export ONNX failed

### ISSUE THREAD

**Issue by ZeusFSX** [flairNLP/flair#2959]
**Describe the bug**
I try export NER model by the [tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_13_TRANSFORMERS_PRODUCTION.md)  and it failed with error 
`TypeError: TransformerEmbeddings.forward() missing 1 required positional argument: 'lengths'`

**To Reproduce**
[tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_13_TRANSFORMERS_PRODUCTION.md)

**Environment (please complete the following information):**
 - OS : Ubuntu 22.04
 - Python: 3.10.7
 - Version flair: 0.11.3

**Additional context**
I've installed flair from GitHub. Because if you install via pip, it will rise the exception `AttributeError: TransformerWordEmbeddings object has no attribute 'export_onnx'`

**Comment by helpmefindaname** [comment]
closing as this was fixed by https://github.com/flairNLP/flair/pull/3041
