### ISSUE TITLE
Can't reproduce export_onnx example from TUTORIAL_13

### ISSUE THREAD

**Issue by klimentij** [flairNLP/flair#2964]
**Describe the bug**
When I try to export `ner-large` transformer embeddings to ONNX, I see an error `TypeError: forward() missing 1 required positional argument: 'lengths'`

**To Reproduce**

1. Install Flair==0.11.3 from git repo: `pip install git+https://github.com/flairNLP/flair.git` (`TransformerOnnxEmbeddings` class is not available when installed from pip)
2. Run code from the tutorial 13 with my own sentences:  
```
from flair.models import SequenceTagger
from flair.embeddings import TransformerWordEmbeddings, TransformerDocumentEmbeddings

model = SequenceTagger.load("ner-large")
assert isinstance(model.embeddings, (TransformerWordEmbeddings, TransformerDocumentEmbeddings))


sentences = [Sentence(s) for s in ['short sentence', 'this is very long sentence']]
model = SequenceTagger.load("ner-large")
model.embeddings = model.embeddings.export_onnx("flert-embeddings.onnx", sentences, providers=["CUDAExecutionProvider", "CPUExecutionProvider"])
```
3. I get the error `TypeError: forward() missing 1 required positional argument: 'lengths'`

**Expected behavior**
This creates a file `flert-embeddings.onnx` which stores the exported Onnx Model.

**Screenshots**
<img width="689" alt="image" src="https://user-images.githubusercontent.com/3247669/196463874-61339c71-08f9-4524-921e-92dc59f7a3e2.png">

**Environment (please complete the following information):**
 - Deep Learning AMI GPU PyTorch 1.12.1 (Amazon Linux 2) 
 - NVIDIA driver version: 510.73.08
 - CUDA version: 11.6 
 - Flair 0.11.3
 - onnx 1.12.0
 - onnxruntime 1.12.1
 - Pytorch 1.12.1.post201

**Comment by valeriosofi** [comment]
Hi @klimentij, please try to uninstall it and then install it again with `pip install git+https://github.com/valeriosofi/flair.git@nebullvm`, you were missing the branch info in your command ;)

**Comment by klimentij** [comment]
@valeriosofi re-tried with the branch info, the same error

**Comment by valeriosofi** [comment]
@klimentij ok I think that you are using pytorch>=1.12, you can solve the error by installing and using pytorch 1.11. It looks like that from 1.12 they changed the input format of the input data in the function torch.onnx.export. You should change this part in the file `/flair/flair/embeddings/transformer.py`
```
torch.onnx.export(
    embedding,
    [example_tensors],
    path,
    input_names=list(example_tensors.keys()),
    output_names=output_names,
    dynamic_axes=dynamic_axes,
    opset_version=opset_version,
)
```
like this:
```
torch.onnx.export(
    embedding,
    example_tensors,
    path,
    input_names=list(example_tensors.keys()),
    output_names=output_names,
    dynamic_axes=dynamic_axes,
    opset_version=opset_version,
)
```
Unfortunately, this will fail because the new versions of pytorch have a bug in the onnx export function with this flair model, I opened an issue here and I think they will fix it for the next pytorch release: https://github.com/pytorch/pytorch/issues/84365.

**Comment by klimentij** [comment]
True, I’ve tried all versions down to 1.09 - this error is gone, but
there’s a different error

**Comment by valeriosofi** [comment]
@klimentij I've just tried on two different systems with pytorch 1.11 and it works for me

**Comment by helpmefindaname** [comment]
Closed due to MR above fixing the problem
