### ISSUE TITLE
Fine-tune on specific domain

### ISSUE THREAD

**Issue by shahafp** [flairNLP/flair#2966]
Hi,
We chose to use Flair for our domain-specific NER model.
So far we got excellent results!

There is something that I would like to clarify, We are tagging data all the time, which means that every couple of weeks we get another batch of labeled data.

For the first batch, we used TransformerWordEmbeddings with "allenai/longformer-base-4096" because we have long sentences data and then fine_tune the "SequenceTagger"
After the first training, we wanted to train our model on the new batch of data
What would be better in this case?
load our current SequenceTagger model with `SequenceTagger.load()` and use fine_tune again?
or load our current SequenceTagger model with `SequenceTagger.load()` and use train function?
or maybe train all the data together on a new SequenceTagger with TransformerWordEmbeddings?

One more problem I had, when I tried to load my model and use fine_tune again I ran into a CUDA OUT OF MEMORY error
while when I used all the data together and train a new SequenceTagger the train finished successfully 
any ideas why?

We use AWS sageMaker instance type: ml.p3.2xlarge
Thanks ahead for any help

This is my code for the loading and training

```
# 4. initialize fine-tuneable transformer embeddings
embeddings = TransformerWordEmbeddings(model="allenai/longformer-base-4096",
                                       layers="-1",
                                       subtoken_pooling="first",
                                       fine_tune=True,
                                       use_context=True,
                                       allow_long_sentences=True
                                       )
embeddings.max_subtokens_sequence_length = 4096

# 5. initialize bare-bones sequence tagger (no CRF, no RNN, no reprojection)
new_model = False
if new_model:
    tagger = SequenceTagger(hidden_size=256,
                            embeddings=embeddings,
                            tag_dictionary=label_dict,
                            tag_type='ner',
                            use_crf=False,
                            use_rnn=False,
                            reproject_embeddings=False,
                      )
else:
    tagger = SequenceTagger.load('round_7_full_address_fine_tune/final-model.pt')
    tagger.embeddings.max_subtokens_sequence_length = 4096

# 6. initialize trainer
trainer = ModelTrainer(tagger, corpus)
model_path = f'round_{ROUND_NUMBER}_full_address{FINE_TUNED}_similars'
# 7. run fine-tuning
trainer.fine_tune(model_path,
                  learning_rate=1.0e-5,
                  mini_batch_size=2,
                  write_weights = True,
                  mini_batch_chunk_size=4,  # remove this parameter to speed up computation if you have a big GPU
                  embeddings_storage_mode='none'
                 )
```

**Comment by shahafp** [comment]
Thanks for your response!!
Do you have any idea regarding the OOM issue?
I tried to use the filter_long_sentences but sometimes it didn't help

**Comment by alanakbik** [comment]
Hello @shahafp it could be because in your code you are first loading the embeddings, then loading the trained model which includes another instance of the embeddings. So you're loading the embeddings twice which probably fills up a lot of GPU memory.

Try moving the `embeddings = TransformerWordEmbeddings` part into the `if new_model:` statement so they don't get loaded when you load an already trained model.

**Comment by shahafp** [comment]
Hey @alanakbik , actually I don’t execute the load embedding cell, to avoid what you just said
