### ISSUE TITLE
Get original text after tokenizer in flair 0.11

### ISSUE THREAD

**Issue by rafgonlop1** [flairNLP/flair#2972]
Hi guys! I am rewrting code that previously used flair 0.10 to flair 0.11 and I'm running into some issues. It originally took an OCR phrase, instantiated a Sentence object, and predicted a topic using a torch model. So far everything perfect in both versions.

To see the different topics of the sentence, in flair 0.10 I had to access the "entities" while in 0.11 I access the "labels" (which in 0.10 appear as empty). The main problemthat I am not able to solve is that in flair 0.10 in each entity I could access not only the tokenized text but also the original text, which I am unable to do in flair 0.11. Can someone tell me if there is any way to do it?

**Comment by alanakbik** [comment]
Hello @rafgonlop1 thanks for pointing this out. 

If I understand correctly, this snippet reproduces your problem:

```python
model = SequenceTagger.load('ner-fast')

sentence = Sentence("George   Washington was here")

model.predict(sentence)

for entity in sentence.get_spans('ner'):
    print(entity)
    print(entity.text)
```

Where `print(entity.text)` prints `George Washington` instead of <code>George&nbsp;&nbsp;&nbsp;Washington</code>(with extra whitespace). 

Is this correct? If so, we could put in PR that fixes this so that `entity.text` will print out the original text instead of the joined tokens.

**Comment by alanakbik** [comment]
Ok! Could you modify my snippet to illustrate how you're currently using `get_labels()` and where you'd like a `to_original_text` method?

**Comment by rafgonlop1** [comment]
Of course, @alanakbik. I'm doing somethin like:

```python
model = SequenceTagger.load('ner-fast')

sentence = Sentence("ANDANA LAND CORPORA1@N PTY LTD SELLS HOUSES")

model.predict(sentence)

for entity in sentence.get_labels():
    print(entity) 
    print(entity.text)
```

In this case, `entity.text` is `'ANDANA LAND CORPORA1 @ N PTY LTD` and the orginial text would be `'ANDANA LAND CORPORA1@N PTY LTD`

**Comment by alanakbik** [comment]
Thanks! Is `entity.text` printing something for you here? The Label class should not have a text field.

**Comment by rafgonlop1** [comment]
You're absolutely correct. I meant `entity.data_point.text`. I think I'm understanding more the way you proceeded before.

**Comment by alanakbik** [comment]
Got it, thanks! Will put in a PR!

**Comment by rafgonlop1** [comment]
Thank you @alanakbik, I tried to use just the same method flair has in Sentence class and works perfectly in the data_point :)
