### ISSUE TITLE
flair is not a package

### ISSUE THREAD

**Issue by mghasemizade** [flairNLP/flair#2973]
**Describe the bug**
After trying to run examples of the Doc Word Embedding in the docs, this is what I get:
ModuleNotFoundError: No module named 'flair.embeddings'; 'flair' is not a package

**To Reproduce**
from flair.embeddings import TransformerDocumentEmbeddings

# init embedding
embedding = TransformerDocumentEmbeddings('bert-base-uncased')

# create a sentence
sentence = Sentence('The grass is green .')

# embed the sentence
embedding.embed(sentence)**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/74173811/198111529-30238cc8-60e1-4e5c-866e-a830cd658736.png)

**Environment (please complete the following information):**
Ubuntu 20.04.05 LTS
Python 3.8.10

**Additional context**
I have tried on Ubuntu 22, 20, 18, and 16.  I couldn't install flair in Ubuntu 22 and 18, though the default python version of ubuntu 18 is 3.6. I made a python 3.6 environment in ubuntu 16 like mentioned in the README.md file but I still failed to run anything with flair.
I have tried installing pytorch before running, changing the environment, updating the pip and also this new comment I found in here:
 https://github.com/flairNLP/flair/issues/2969#issuecomment-1290778864

**Comment by dobbersc** [comment]
The file you are trying to execute, `flair.py`, overlaps with the namespace of the actual flair package. Try re-naming your python script to something else, e.g. `flair_test.py`.

**Comment by mghasemizade** [comment]
> The file you are trying to execute, `flair.py`, overlaps with the namespace of the actual flair package. Try re-naming your python script to something else, e.g. `flair_test.py`.

That fixed my problem! Thanks
