### ISSUE TITLE
No BIO tags when loading external dataset (eg., Conll2003)

### ISSUE THREAD

**Issue by aoezdemir** [flairNLP/flair#2977]
Hello,

when I load the Conll2003 dataset (NER tags are in BIO-Format) manually, the BIO tags disappear. 
My Implementation:
```
# define columns
columns = {0: 'text', 3:'ner'}

# this is the folder in which train, test and dev files reside
data_folder = '/data/conll2003NER/'

# init a corpus using column format, data folder and the names of the train, dev and test files
corpus: Corpus = ColumnCorpus(data_folder, columns,
                              train_file='train.txt',
                              test_file='test.txt',
                              dev_file='valid.txt',
                              )
```
and when I do this:

`print(corpus.train[0].to_tagged_string('ner'))`

which only outputs:
`Sentence: "EU rejects German call to boycott British lamb ." → ["EU"/ORG, "German"/MISC, "British"/MISC]`

Instead it should be like this:
`Sentence: "EU rejects German call to boycott British lamb ." → ["EU"/B-ORG, "German"/B-MISC, "British"/B-MISC]`

**Why are the BIO tags missing? I really need help. 
Thanks in advance!**

**Comment by helpmefindaname** [comment]
Hi @aoezdemir 
Flair 0.11 uses internally a span format, this gets more visible, when you have tagging for entities with more than 1 Token. 
E.g. `WNUT_17().train[0]` gives 
`Sentence[27]: "@paulwalk It 's the view from where I 'm living for two weeks . Empire State Building = ESB . Pretty bad storm here last evening ." → ["Empire State Building"/location, "ESB"/location]`

Here "Empire State Building" has 3 Tokens, but is printed as a single span.

**Comment by aoezdemir** [comment]
Hi @helpmefindaname,

does this mean that I cannot use BIO tags in my training and later on in my classification report? Or is there a possibility to train the model with BIO tags? 

Thanks in advance for your help!

**Comment by helpmefindaname** [comment]
The model is trained on BIOIES tags per default, you can use BIO tags by using `tagger = SequenceTagger(..., tag_format="BIO")`.

It is not considerd a good practice to evaluate on BIO tags, as it:
a)   is not really comparable to other models using different approaches (dictionary-matching, span-classification, generative models, tree-parsing, different tagging schemes, ...)
b)   evaluating on entity-level is more accurate in terms usage

For that reason, flair evaluates NER models the same way the [conll-eval](https://github.com/sighsmile/conlleval) or [seq-eval](https://github.com/chakki-works/seqeval) libraries do.
