### ISSUE TITLE
Adding link to result classes

### ISSUE THREAD

**Issue by 11Alexei11** [flairNLP/flair#2979]
This repository is great work but it would be better to add description or link to description of result classes(for ner and pos)

**Comment by alanakbik** [comment]
Hello @11Alexei11 thanks for the feedback! Could you specify? Do you mean the `Result` object returned by the `evaluate` method?

**Comment by 11Alexei11** [comment]
I mean that is i pass string = "I love Berlin" i will get some tags assigning to each part of sentence if i use pos model for instance. And I would like to know meaning of this tags
