### ISSUE TITLE
NER Evaluation mismatch

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#298]
Hi,

I manually evaluated a trained ner model on my own dataset. The evaluation output after the training was:

```bash
2018-12-11 00:22:48,261 Testing using best model ...
2018-12-11 00:22:57,390 MICRO_AVG: acc 0.8093 - f1-score 0.8094
2018-12-11 00:22:57,390 MARCO_AVG: acc 0.7782 - f1-score 0.829
2018-12-11 00:22:57,392 LOC        tp: 164 - fp: 32 - fn: 32 - tn: 164 - precision: 0.8367 - recall: 0.8367 - accuracy: 0.8367 - f1-score: 0.8367
2018-12-11 00:22:57,393 ORG        tp: 5 - fp: 1 - fn: 3 - tn: 5 - precision: 0.8333 - recall: 0.6250 - accuracy: 0.7143 - f1-score: 0.7143
2018-12-11 00:22:57,393 PER        tp: 143 - fp: 32 - fn: 47 - tn: 143 - precision: 0.8171 - recall: 0.7526 - accuracy: 0.7836 - f1-score: 0.7835
2018-12-11 00:22:57,393 ----------------------------------------------------------------------------------------------------
```

Then I used `final-model.pt`, made predictions and wrote it to a conll-based evaluation file. Then I used the official conll evaluation perl script and the output is:

```bash
processed 3781 tokens with 365 phrases; found: 359 phrases; correct: 298.
accuracy:  95.56%; precision:  83.01%; recall:  81.64%; FB1:  82.32
              LOC: precision:  84.41%; recall:  85.79%; FB1:  85.09  186
              ORG: precision:  83.33%; recall:  62.50%; FB1:  71.43  6
              PER: precision:  81.44%; recall:  78.16%; FB1:  79.77  167
```

The F-score differs so I just want to report this behavior before the upcoming 0.4 release :)

**Comment by alanakbik** [comment]
Hi @stefan-it, 

we understand this to be an error in the original CoNLL-03 evaluation script, which was not designed to handle BIOES tagged entities. When using BIOES tagged entities, there are a few edge cases in which the script will not detect an error. For instance, if there are two S- tagged entities that follow each other. Or an S- followed by a I- and -E. 

So, we created our own evaluation script that *should* be correct now from our tests. However, your numbers have me a bit worried since the difference between the two is over 1 F-score point. Would you have the time to look into the errors a bit more closely (maybe print a sample of error sentences) - just to make sure that our evaluation procedure is indeed correct?

**Comment by stefan-it** [comment]
I will post some example soon.

But can I simply convert the iobes output to iob like:

```bash
        if predicted_tag.startswith('S-'):
            predicted_tag = predicted_tag.replace('S-', 'B-')

        if predicted_tag.startswith('E-'):
            predicted_tag = predicted_tag.replace('E-', 'I-')
```

Then I used the conll script again and the output is:

```bash
processed 3781 tokens with 394 phrases; found: 377 phrases; correct: 312.
accuracy:  95.90%; precision:  82.76%; recall:  79.19%; FB1:  80.93
              LOC: precision:  83.67%; recall:  83.67%; FB1:  83.67  196
              ORG: precision:  83.33%; recall:  62.50%; FB1:  71.43  6
              PER: precision:  81.71%; recall:  75.26%; FB1:  78.36  175
```

That output is identical to the `flair` evaluation.

But for another experiment:

`flair` output:

```bash
Testing using best model ...
MICRO_AVG: acc 0.8314 - f1-score 0.8313
MARCO_AVG: acc 0.7929 - f1-score 0.8487
LOC        tp: 169 - fp: 24 - fn: 27 - tn: 169 - precision: 0.8756 - recall: 0.8622 - accuracy: 0.8689 - f1-score: 0.8688
ORG        tp: 5 - fp: 1 - fn: 3 - tn: 5 - precision: 0.8333 - recall: 0.6250 - accuracy: 0.7143 - f1-score: 0.7143
PER        tp: 144 - fp: 28 - fn: 46 - tn: 144 - precision: 0.8372 - recall: 0.7579 - accuracy: 0.7956 - f1-score: 0.7956
----------------------------------------------------------------------------------------------------
```

The conll evaluation script (with iob preprocessing):

``` bash
processed 3781 tokens with 394 phrases; found: 369 phrases; correct: 318.
accuracy:  96.64%; precision:  86.18%; recall:  80.71%; FB1:  83.36
              LOC: precision:  88.02%; recall:  86.22%; FB1:  87.11  192
              ORG: precision:  83.33%; recall:  62.50%; FB1:  71.43  6
              PER: precision:  84.21%; recall:  75.79%; FB1:  79.78  171
```

I would really to like to have another evaluation source/script because I want to report a reliable F-Score :)

**Comment by alanakbik** [comment]
Thank you for looking into this! The second may point to an error in our script. Could you help us find this error, i.e. identify those sentences where the two scripts disagree.

Alternatively, we could put the CoNLL evaluation script back in and use your method of making BIO tags out of BIOES before evaluating.

**Comment by stefan-it** [comment]
@alanakbik I found the error for the last example: I did the predictions with `final-model.pt`, but `flair` seems to evaluate after training with `best-model.pt`.

I used `final-model.pt` for predictions and used the same evaluation logic as in the `trainer` class. Now the results are identical to the conll script (with manually converting iobes to iob).

**Comment by alanakbik** [comment]
Ah great, thanks for checking up on this!

**Comment by stefan-it** [comment]
I'm not sure, if the old evaluation script should be integrated again, but maybe we could add a section to the new documentation (regarding publishing f-scores and double checking the results with conll script) :)

**Comment by alanakbik** [comment]
Yes, good idea!

**Comment by pandhir** [comment]
Sorry for reviving this old thread. I also have a question about conlleval scheme. Conlleval scheme includes the O class for reporting F score. Flair does not include O class. Am I correct in understanding this?

**Comment by ciaochiaociao** [comment]
@pandhir From what I understand, calculating the f1/precision/recall only involves the number of identified entities and the gold entities, meaning that tokens with O class do not matter in the score.
