### ISSUE TITLE
'TextClassifier' object has no attribute 'embeddings'

### ISSUE THREAD

**Issue by pranavan-rbg** [flairNLP/flair#2982]
TARSClassifier.load error 

AttributeError                            Traceback (most recent call last)
<ipython-input-13-710c2b4d40e4> in <module>
----> 1 tars = TARSClassifier.load('/content/drive/MyDrive/Text_classification/final-model.pt')

2 frames
/usr/local/lib/python3.7/dist-packages/flair/nn/model.py in load(cls, model_path)
    147             state = torch.load(f, map_location="cpu")
    148 
--> 149         model = cls._init_model_with_state_dict(state)
    150 
    151         if "model_card" in state:

/usr/local/lib/python3.7/dist-packages/flair/models/tars_model.py in _init_model_with_state_dict(cls, state, **kwargs)
    739             label_dictionary=state.get("label_dictionary"),
    740             label_type=state.get("label_type", "default_label"),
--> 741             embeddings=state.get("tars_model").embeddings,
    742             num_negative_labels_to_sample=state.get("num_negative_labels_to_sample"),
    743             **kwargs,

/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1206                 return modules[name]
   1207         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1208             type(self).__name__, name))
   1209 
   1210     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'TextClassifier' object has no attribute 'embeddings'

**Comment by alanakbik** [comment]
Which Flair version do you use?

**Comment by pranavan-rbg** [comment]
Flair version it's 0.11.3

**Comment by pranavan-rbg** [comment]
pip installed 

#
!pip install --upgrade git+https://github.com/flairNLP/flair.git
!pip install flair

**Comment by alanakbik** [comment]
@pranavan-rbg loading should work on master now. For the upcoming release we need to do more TARS testing to make sure the refactorings did not break anything.

**Comment by PranavanBupathy** [comment]
Confirming it's working now.
Appreciate your work
Thank you
