### ISSUE TITLE
Error When Loading in Fine-Tuned Tars Model

### ISSUE THREAD

**Issue by ajaklevs** [flairNLP/flair#2988]
Starting with the Tars classifier base, I fine tuned the tars model on my own dataset. At first the training loop was running smoothly, and a best-model.pt and final-model.pt were saved. However in the training loop, while calculating the final metrics, the line self.model.load_state_dict(self.model.load(base_path / "best-model.pt").state_dict()) errored. I had the same error occur when I tried to load in best-model.pt in a separate cell with the code model = TARSClassifier.load("output/tars/best-model.pt"). I am running locally through a Jupyter Notebook on a mac book pro, using Flair version 0.11.3.

The error message was as follows:

OSError: Can't load config for '/var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpprvqafzm'. Make sure that:

- '/var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpprvqafzm' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpprvqafzm' is the correct path to a directory containing a config.json file

The complete error message (the error message during the training loop) is copy and pasted below: 

OSError                                   Traceback (most recent call last)
/opt/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    379             # Load from URL or cache if already cached
--> 380             resolved_config_file = cached_path(
    381                 config_file,

/opt/anaconda3/lib/python3.8/site-packages/transformers/file_utils.py in cached_path(url_or_filename, cache_dir, force_download, proxies, resume_download, user_agent, extract_compressed_file, force_extract, local_files_only)
   1013         # File, but it doesn't exist.
-> 1014         raise EnvironmentError("file {} not found".format(url_or_filename))
   1015     else:

OSError: file /var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpul4gwhkc/config.json not found

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-12-48f70865afeb> in <module>
----> 1 trainer.train(base_path='./output/' + 'tars' ,  # path to store the model artifacts
      2                 learning_rate=0.02,  # use very small learning rate
      3                 mini_batch_size = 16,
      4                 mini_batch_chunk_size=1,  # optionally set this if transformer is too much for your machine
      5                 max_epochs= 1,  # terminate after 1 epoch

/opt/anaconda3/lib/python3.8/site-packages/flair/trainers/trainer.py in train(self, base_path, learning_rate, mini_batch_size, eval_batch_size, mini_batch_chunk_size, max_epochs, train_with_dev, train_with_test, monitor_train, monitor_test, main_evaluation_metric, scheduler, anneal_factor, patience, min_learning_rate, initial_extra_patience, optimizer, cycle_momentum, warmup_fraction, embeddings_storage_mode, checkpoint, save_final_model, anneal_with_restarts, anneal_with_prestarts, anneal_against_dev_loss, batch_growth_annealing, shuffle, param_selection_mode, write_weights, num_workers, sampler, use_amp, amp_opt_level, eval_on_train_fraction, eval_on_train_shuffle, save_model_each_k_epochs, tensorboard_comment, use_swa, use_final_model_for_eval, gold_label_dictionary_for_eval, create_file_logs, create_loss_file, epoch, use_tensorboard, tensorboard_log_dir, metrics_for_tensorboard, optimizer_state_dict, scheduler_state_dict, save_optimizer_state, **kwargs)
    829         # test best model if test data is present
    830         if self.corpus.test and not train_with_test:
--> 831             final_score = self.final_test(
    832                 base_path=base_path,
    833                 eval_mini_batch_size=eval_batch_size,

/opt/anaconda3/lib/python3.8/site-packages/flair/trainers/trainer.py in final_test(self, base_path, eval_mini_batch_size, main_evaluation_metric, num_workers, gold_label_dictionary_for_eval)
    920 
    921         if (base_path / "best-model.pt").exists():
--> 922             self.model.load_state_dict(self.model.load(base_path / "best-model.pt").state_dict())
    923         else:
    924             log.info("Testing using last state of model ...")

/opt/anaconda3/lib/python3.8/site-packages/flair/nn/model.py in load(cls, model_path)
    140             # see https://github.com/zalandoresearch/flair/issues/351
    141             f = file_utils.load_big_file(str(model_file))
--> 142             state = torch.load(f, map_location="cpu")
    143 
    144         model = cls._init_model_with_state_dict(state)

/opt/anaconda3/lib/python3.8/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    582                     opened_file.seek(orig_position)
    583                     return torch.jit.load(opened_file)
--> 584                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    585         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
    586 

/opt/anaconda3/lib/python3.8/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, **pickle_load_args)
    840     unpickler = pickle_module.Unpickler(data_file, **pickle_load_args)
    841     unpickler.persistent_load = persistent_load
--> 842     result = unpickler.load()
    843 
    844     return result

/opt/anaconda3/lib/python3.8/site-packages/flair/embeddings/base.py in __setstate__(self, state)
    443             config = config_class.from_dict(config_state_dict)
    444 
--> 445         embedding = self.create_from_state(saved_config=config, **state)
    446 
    447         # copy values from new embedding

/opt/anaconda3/lib/python3.8/site-packages/flair/embeddings/document.py in create_from_state(cls, **state)
     56         # this parameter is fixed
     57         del state["is_document_embedding"]
---> 58         return cls(**state)
     59 
     60 

/opt/anaconda3/lib/python3.8/site-packages/flair/embeddings/document.py in __init__(self, model, layers, layer_mean, is_token_embedding, **kwargs)
     42         :param fine_tune: If True, allows transformers to be fine-tuned during training
     43         """
---> 44         TransformerEmbedding.__init__(
     45             self,
     46             model=model,

/opt/anaconda3/lib/python3.8/site-packages/flair/embeddings/base.py in __init__(self, model, fine_tune, layers, layer_mean, subtoken_pooling, cls_pooling, is_token_embedding, is_document_embedding, allow_long_sentences, use_context, respect_document_boundaries, context_dropout, saved_config, tokenizer_data, name, **kwargs)
    205         else:
    206             # load tokenizer from inmemory zip-file
--> 207             self.tokenizer = self._tokenizer_from_bytes(tokenizer_data)
    208 
    209         if saved_config is None:

/opt/anaconda3/lib/python3.8/site-packages/flair/embeddings/base.py in _tokenizer_from_bytes(self, zip_data)
    337         with tempfile.TemporaryDirectory() as temp_dir:
    338             zip_obj.extractall(temp_dir)
--> 339             return AutoTokenizer.from_pretrained(temp_dir)
    340 
    341     def _tokenizer_bytes(self):

/opt/anaconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py in from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs)
    308         config = kwargs.pop("config", None)
    309         if not isinstance(config, PretrainedConfig):
--> 310             config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
    311 
    312         if "bert-base-japanese" in str(pretrained_model_name_or_path):

/opt/anaconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    339             {'foo': False}
    340         """
--> 341         config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    342 
    343         if "model_type" in config_dict:

/opt/anaconda3/lib/python3.8/site-packages/transformers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    396                 f"- or '{pretrained_model_name_or_path}' is the correct path to a directory containing a {CONFIG_NAME} file\n\n"
    397             )
--> 398             raise EnvironmentError(msg)
    399 
    400         except json.JSONDecodeError:

OSError: Can't load config for '/var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpul4gwhkc'. Make sure that:

- '/var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpul4gwhkc' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/var/folders/20/4p5k_m8d5kn_wp1xx1fy39rc80krp9/T/tmpul4gwhkc' is the correct path to a directory containing a config.json file

**Comment by alanakbik** [comment]
@ajaklevs could you print the training script you use so I can reproduce the error?

**Comment by ajaklevs** [comment]
@alanakbik I am doing this for my job which requires confidential data, but I was able to reproduce the problem with publicly available kaggle data and the same task. Attached is the data (sample_data.csv) and I've attached the script below:

`import numpy as np`

`import numpy as np
import pandas as pd
from flair.models import TARSClassifier
from flair.data import Sentence
from flair.data import Corpus
from flair.datasets import TREC_6
from flair.trainers import ModelTrainer

import torch

import string

#Preparing Data and train/test split
data = pd.read_csv('sample_data.csv')
n = data.shape[0]
train_shape = int(.7*n)

train_ids = set(np.random.choice(n,size = train_shape, replace=False))
test_ids = list(set(range(n)) - train_ids)

train_data = data.iloc[list(train_ids)]
test_data = data.iloc[test_ids]

topics = list(data.columns[1:])
topics

table = str.maketrans({key: None for key in string.punctuation})

table = str.maketrans({key: None for key in string.punctuation})


#Getting data ready for flair model
def generate_flair_sentence(data:pd.DataFrame,label_columns:list,target_column:str):
	"""
	Function which takes in the labeled text data in dataframe form and returns a list of flair sentences

	@input data: pandas dataframe with a column for the text, and a seperate column for each class which
	 take on the value of 1 when the row applies to that class and 0 otherwise

	 @input label_columns: a list of strings representing the class names

	 @input target_column: a string of the name of the column with text
	"""
    
    list_sent_ret = []
    flag = False

    for index, row in data.iterrows():
        
        
        text_tmp = str(row[target_column])
        
        if len(text_tmp) == 0:
            continue
            
        if len(text_tmp)>510:
            text_tmp = text_tmp.translate(table) 
            if len(text_tmp)>510:
                text_tmp = text_tmp[0:510]
                if len(text_tmp) >510:
                    flag = True
        sentence_tmp = Sentence(text_tmp)

        for tmp in label_columns:
            if row[tmp] == 1:
                sentence_tmp.add_label('topics',tmp)
        list_sent_ret.append(sentence_tmp)
    
    return list_sent_ret

#creating a list of flair sentence objects for both the train and test data
train_sentences = generate_flair_sentence(train_data,topics,'text',True)
test_sentences = generate_flair_sentence(test_data,topics,'text',True)

#Creating Flair corpus
corpus = Corpus(train = train_sentences, test = test_sentences)

#creating label dictionary
label_type = 'topics'
label_dict = corpus.make_label_dictionary(label_type=label_type)

#loading in base model
model = TARSClassifier.load("tars-base-v8.pt")

#switching to new task
model.add_and_switch_to_new_task(task_name="topic classification",
                                label_dictionary=label_dict,
                                label_type=label_type,
                                )
#creating trainer
trainer = ModelTrainer(model, corpus)

#training loop
trainer.train(base_path='output/tars',
                learning_rate=0.02,  # use very small learning rate
                mini_batch_size = 16,
                mini_batch_chunk_size=1,  # optionally set this if transformer is too much for your machine
                max_epochs= 1,  # terminate after 10 epochs
                )`

[sample_data.csv](https://github.com/flairNLP/flair/files/10035234/sample_data.csv)
e script adapted to work with the kaggle data, sample_data.csv
