### ISSUE TITLE
Building token embeddings from subtokens (subtoken_pooling)

### ISSUE THREAD

**Issue by kobiche** [flairNLP/flair#2991]
I have a question regarding how the (FLAIR) token embeddings are generated from the subtoken embeddings, which are the outputs of the TransformerWordEmbeddings. 
In the [docs ](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_7_TRAINING_A_MODEL.md#training-a-named-entity-recognition-ner-model-with-transformers) and [paper](https://arxiv.org/pdf/2011.06993.pdf) you recommend using the `subtoken_pooling="first"`.
However, I have found the following paper **[Subword Pooling Makes a Difference](https://aclanthology.org/2021.eacl-main.194.pdf)** that actually advises the opposite, that is using the "last" subtoken. This is proven by using an attention mechanism on the token level.
My question is, have you experimented with other subtokien_pooling policies?

**Comment by alanakbik** [comment]
Hello @kobiche - interesting. I tried out a few options (first and first_last), but never last alone. In my experiments, it never seemed to make much of a difference, but perhaps we should take a closer look at this.

**Comment by iliaNecrov** [comment]
@alanakbik but can we right now use "mean" embeddings when we fine-tune our transformer embeddings to NER task?
For example:

```
embeddings = TransformerWordEmbeddings(model='microsoft/mdeberta-v3-base',
                                       layers="-1",
                                       subtoken_pooling="mean",
                                       fine_tune=True,
                                       use_context=False,
                                       )
```

Asking this because paper says:

> When fine-tuning, you should also only use the topmost layer, so best set layers='-1'.
