### ISSUE TITLE
Import flair error 

### ISSUE THREAD

**Issue by ambuje** [flairNLP/flair#2999]
While importing flair receiving an error:-

cannot import name 'TransformerEmbedding' from 'flair.embeddings.base' (/home/ambuje/anaconda3/envs/tf-gpu1/lib/python3.8/site-packages/flair-0.11.3-py3.8.egg/flair/embeddings/base.py)

Not aware of how this folder is being built (flair-0.11.3-py3.8.egg)

**Comment by helpmefindaname** [comment]
Hi @ambuje 
`TransformerEmbedding` does not exist, there is only `TransformerEmbeddings`, besides that, I would recommend using `TransformerWordEmbeddings` or `TransformerDocumentEmbeddings` depending on your usecase. Idealy you want to import from `flair.embeddings` and not from the specific module, e.g.
`from flair.embeddings import TransformerWordEmbeddings` or `from flair.embeddings import TransformerDocumentEmbeddings`

**Comment by ambuje** [comment]
I am not manually importing this, when I import flair this error pops up. 

Is there any way to remove this error? I tried reinstalling flair but I get the same error

**Comment by anapaulagomes** [comment]
Hi, @ambuje. Could you share how you're importing it? Because I just had it installed (flair 0.11.3 and python 3.8) and I've managed to import `import flair` without any issues. Also, did you try a new virtual env or another one other than anaconda?
