### ISSUE TITLE
HUNFlAIR and IOB Format

### ISSUE THREAD

**Issue by nhabibi** [flairNLP/flair#3003]
Hi,

I have a tagged-sentence dataset, in IOB format. Is it possible to apply HUNFALIR on it?

What about training a model on it?

Thanks

**Comment by helpmefindaname** [comment]
Hi @nhabibi 
following [the tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md) you can train a HUNFLAIR like model with whatever dataset you like.

**Comment by nhabibi** [comment]
Many thanks @helpmefindaname!

**Comment by nhabibi** [comment]
Dear @helpmefindaname,

When I intend to load the **WordEmbeddings("pubmed")**, I get the following error:

**ValueError: cannot reshape array of size 131665828 into shape (1000000,200)**

What is the probable reason?

Thanks
