### ISSUE TITLE
How could I control the model size

### ISSUE THREAD

**Issue by HenryLiuPI** [flairNLP/flair#3004]
Right now I'm using tars-base as a base model to train a multi-label classification model. The whole dataset is around 1800 sentences with labels. After training, the output .pt file is around 460MB which is not small and when I use the model directly it takes 0.5 seconds for the model to return the result for one sentence. Is there a way to reduce the model size and increase the performance of the model? Thanks!

**Comment by helpmefindaname** [comment]
Hi @HenryLiuPI 
When you use a base model, you are limited to at least the amount of parameters that base model has. You can only have a reduced size by using smaller base models (such as [distillbert](https://huggingface.co/distilbert-base-uncased)) and train a tars model from scratch.

About the speed ups, you can take a look at [onnx exports](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_8_MODEL_OPTIMIZATION.md) which can speed up your model. Especially on the CPU, you can use quantization, which both speeds up the predictions and reduces the memory needed per parameter
