### ISSUE TITLE
Discrepancy when de-serializing TARSTagger in master branch vs last release

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#3017]
When de-serializing the tars-ner model, the word_dropout is missing from the model. In version 0.11.3, it is still there. 

To reproduce, execute the following code in `master` branch and in `v0.11.3`:

```python
tars: TARSTagger = TARSTagger.load('tars-ner')

tagger = tars.tars_model
print(tagger)
```

In `master`, it prints: 

```
    )
  )
  (locked_dropout): LockedDropout(p=0.5)
  (linear): Linear(in_features=1024, out_features=5, bias=True)
  (loss_function): CrossEntropyLoss()
)
```

In  `v0.11.3`, it prints: 

```
    )
  )
  (word_dropout): WordDropout(p=0.05)
  (locked_dropout): LockedDropout(p=0.5)
  (linear): Linear(in_features=1024, out_features=5, bias=True)
  (loss_function): CrossEntropyLoss()
)
```

@helpmefindaname can you take a look? This may have something to do with the changes in de-serialization logic.

**Comment by helpmefindaname** [comment]
Hi @alanakbik 
this is due to https://github.com/flairNLP/flair/blob/master/flair/models/sequence_tagger_model.py#L138 I would agure that word dropout doesn't make sense when there is no recurrent notion afterwards. It basically just removes training signal while keeping the computational needs.
