### ISSUE TITLE
Load own corpus and train task specific embedding

### ISSUE THREAD

**Issue by ChiaraBecht** [flairNLP/flair#3040]
Hi all, 

I have a corpus dataset, which contains text in the first column and a certainty label in the second column. I would like to customize a model that predicts the certainty labels. The data is already split in train, dev and test and all are located in the corpus folder as required. I have the files as csv and txt files. For both the separator is tab. As it worked for version 0.10 i tried the following:
```python
from flair.datasets import CSVClassificationCorpus

# this is the folder in which train, test and dev files reside
data_folder = '/path/to/corpus'

column_name_map = {0: "Text", 1:"certainty_Label"}  
label_type = "certainty_label" 

corpus: Corpus = CSVClassificationCorpus(data_folder, 
                                        column_name_map, 
                                        skip_header=True, 
                                        delimiter="\t", 
                                        label_type=label_type)
```
This however results in the following error:
[...]
-> 1209     raise RuntimeError("No data provided when initializing corpus object.")
   1211 # sample test data from train if none is provided
   1212 if test is None and sample_missing_splits and train and not sample_missing_splits == "only_dev":

RuntimeError: No data provided when initializing corpus object.

I would like to train a sentence classification model, that predicts the authors certainty for a written sentence. Therefore I want to train a model with specific embeddings for this use case. Any recommendation about fixing my error and alternative approaches to load my corpus, embed it and train the model are appreciated. Many thanks :)

P.S. a small example of the trainingdataset is attached
[example_trainingset.csv](https://github.com/flairNLP/flair/files/10322124/example_trainingset.csv)

Edit by @helpmefindaname : format code

**Comment by helpmefindaname** [comment]
Hi @ChiaraBecht 
Apparently the `column_name_map` is not well documented, it is expecting the following:
* `text` for a text column
* `pair` for all columns that are part of a text pair
* `label` for single labels
* any string starting with `label` (e.g. `label_0`, `label_1`, `label_2`, ...) for multiple labels.

So the loading of the file works by only changing one line from
`column_name_map = {0: "Text", 1:"certainty_Label"}`
to 
`column_name_map = {0: "text", 1:"label"}`

note, that you are providing the `label_type` so the label is stored the right way.

**Comment by ChiaraBecht** [comment]
Dear @helpmefindaname 
Thank you for your help. Is your suggestion for version 0.11.3? I managed to get it running when downgrading to version 0.9 and using '|' as separator for my dataset. However, I am now running into troubles with training a classifier. When fine tuning as suggested in the tutorials:

column_name_map = {0: "text", 1:"label"}  
label_type = "label" 

corpus: Corpus = CSVClassificationCorpus(data_folder, 
                                        column_name_map, 
                                        skip_header=True, 
                                        delimiter="|",
                                        #train_file= 'train.csv',
                                        dev_file= 'dev.csv',
                                        #test_file= 'test.csv', 
                                        label_type=label_type)

print(corpus.get_all_sentences()[0])

label_dict = corpus.make_label_dictionary(label_type = label_type)

# 4. initialize transformer document embeddings (many models are available)
document_embeddings = TransformerDocumentEmbeddings('distilbert-base-uncased', fine_tune=True)

# 5. create the text classifier
classifier = TextClassifier(document_embeddings, label_dictionary=label_dict, label_type=label_type)

# 6. initialize trainer
trainer = ModelTrainer(classifier, corpus)

# 7. run training with fine-tuning
trainer.fine_tune('resources/taggers/question-classification-with-transformer',
                  learning_rate=5.0e-5,
                  mini_batch_size=4,
                  max_epochs=10,
                  )

I am getting the follwowing error:
2023-01-09 14:53:53,169 Reading data from /students/2022-2023/master/spacey/chiara/Meta-knowledge_GENIA_corpus/corpus_pipe
2023-01-09 14:53:53,169 Train: /Meta-knowledge_GENIA_corpus/corpus_pipe/train.csv
2023-01-09 14:53:53,169 Dev: /Meta-knowledge_GENIA_corpus/corpus_pipe/dev.csv
2023-01-09 14:53:53,169 Test: /Meta-knowledge_GENIA_corpus/corpus_pipe/test.csv
Sentence: "When freshly isolated , highly enriched (> 98 %) T cells are examined for IFN-gamma responsiveness ; these cells can respond to IFN-gamma and express beta-chain ."   [− Tokens: 27  − Sentence-Labels: {'label': [L2 (1.0)]}]
2023-01-09 14:53:53,198 Computing label dictionary. Progress:
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2374/2374 [00:02<00:00, 876.70it/s]
2023-01-09 14:53:56,444 Corpus contains the labels: label (#2374)
2023-01-09 14:53:56,444 Created (for label 'label') Dictionary with 3 tags: L2, L1, L3
Traceback (most recent call last):

When using the train method I get to complete all epochs but then run into an error as well. Is this happening because I am using version 0.9 instead of version 0.11? would be very grateful for your input once more.

**Comment by helpmefindaname** [comment]
Hi @ChiaraBecht
the traceback is cut off, so I cannot tell you about the error. If you think this is due to 0.9, you could simply try out 0.11.3 and see if it works better there
