### ISSUE TITLE
does flairNLP support mypy

### ISSUE THREAD

**Issue by sillyquestion** [flairNLP/flair#3042]
I am using pycharm IDE and as such don't have tons of experience with python at present.

For this line:
```
from flair.data import Sentence
```

I get the following warning: 
Mypy: Skipping analyzing "flair.data": module is installed, but missing library stubs or py.typed marker

Is there a way to fix this error? Or flairNLP does not support mypy yet?

**Comment by helpmefindaname** [comment]
Hi @sillyquestion 
I think this should work, when using the latest master branch.
I suppose there wasn't a release since the `py.typed` file was added yet.
