### ISSUE TITLE
SequenceTagger.load error -> 'embeddings.model.embeddings.position_ids'

### ISSUE THREAD

**Issue by shahafp** [flairNLP/flair#3045]
Hi,

I have trained the NER model using SequenceTagger with longformer as an embedding 'allenai/longformer-base-4096'
The train was finished successfully on sageMaker (amazon Linux 2)

When I'm trying to load the model on a different machine I get the missing keys error 'embeddings.model.embeddings.position_ids'

Would you happen to know how I can prevent this?

This is the training script
`

    embeddings = TransformerWordEmbeddings(model='allenai/longformer-base-4096',
                                           layers="-1",
                                           subtoken_pooling="first",
                                           fine_tune=True,
                                           use_context=True,
                                           )
    
    # 5. initialize bare-bones sequence tagger (no CRF, no RNN, no projection)
    tagger = SequenceTagger(hidden_size=256,
                            embeddings=embeddings,
                            tag_dictionary=label_dict,
                            tag_type='ner',
                            use_crf=False,
                            use_rnn=False,
                            reproject_embeddings=False,
                            )

    torch.cuda.empty_cache()

    # 6. initialize trainer
    trainer = ModelTrainer(tagger, corpus)
    model_path = f'round_{round_num}_full_address'
    # 7. run fine-tuning
    trainer.fine_tune(model_path,
                      learning_rate=learning_rate,
                      mini_batch_size=batch_size,
                      mini_batch_chunk_size=1,  # remove this parameter to speed up computation if you have a big GPU
                      embeddings_storage_mode='gpu',
                      )
`

Thank you

**Comment by helpmefindaname** [comment]
Hi @shahafp ,
I cannot replicate your error on the current master branch of flair and transformer 4.23.1, can you check out if that one works for you?

**Comment by shahafp** [comment]
Hi,
Thank you for your comment
I figured out that it was because of the torch version, I hope I am not missing anything else.
