### ISSUE TITLE
Why Flair ner-english-large model is marked as unsafe in Huggingface?

### ISSUE THREAD

**Issue by minnotarize** [flairNLP/flair#3047]
I noticed the model is marked with security alert "This model has one file that has been marked as unsafe.". Is it still safe to download and use this model? Thanks!!

**Comment by helpmefindaname** [comment]
Hi @minnotarize 
Unlike the transformers which have separate files for weights and configuration, flair saves everything as a single file, using the pickle format.
Pickle can contain unsafe code,  which huggingface is warning about. You can look at the warning in the hub:
![image](https://user-images.githubusercontent.com/26192135/211309162-782a2f57-5aa6-458f-a98a-8351daa1752a.png)

Here we see their raiting of certain imports:
* `torch.LongStorage` is an example of something white-listed, as pytorch is 100% trusted. 
* `flair.data.Dictionary` and `flair.embeddings.token.TransformerWordEmbeddings` come from flair, in general flair is a trusted open source library, however it is external so there is no 100% trust (therefore orange).
* `unknown.FloatStorage` is not known and therefore untrusted, this one gives the warning. My assumption here is, that they have a bug in their scanning code, not detecting that it is supposed to be `torch.FloatStorage`

We are currently working on a way to reduce the amount of imports by flair at [this PR](https://github.com/flairNLP/flair/pull/3011) Maybe there will be a better judgement then.

For now I can assure you, that this model is actually safe.

**Comment by minnotarize** [comment]
@helpmefindaname great! thx a lot!!
