### ISSUE TITLE
Taking the more inference time for predicting the 10k rows

### ISSUE THREAD

**Issue by Jasheenshaik** [flairNLP/flair#3048]
I have been using the flair for the token classification task in order to predict a million of rows from the dataset  and i have trained  the model using the transformer (bert - small)

i have checked all the code in the flair for increase the speed of the model  and decrease  the inference time can you provide me any alternative code for that .

```
df = pd.read_csv('/kaggle/input/test-data-flair/fashion_color-2.csv')
test_sent = list(df['review'][0:1000])
# test_sent = [Sentence(text) for text in test_sent]
valid_data = token_Dataset(test_sent)
valid_dataloader = DataLoader(valid_data, batch_size=128)
tagger = tagger.to('cuda')
tagger.eval()
result = []
sent_list = []
for i in tqdm(valid_dataloader):
    tagger.compute_hidden_states = True
    tagger.predict(i,mini_batch_size=128)
    for sent in i:
        sent_list.append(sent.to_plain_string())
        lx = []
        for entity in sent.get_spans('tag'):
            lx.append([entity.text,entity.tag,entity.score])
        result.append(lx)
```

so far i am using the code can you help me to sort out this issue 

Thanks 
Jasheen shaik

Edit by @helpmefindaname to format the code

**Comment by helpmefindaname** [comment]
Hi @Jasheenshaik 

Do you have statistics about the time it requires and a target in mind? If so, it might be helpful to mention it.

First of all I want to notice that there is a lot of code that is redundant to the library behaivour and can be removed:
* `tagger.to('cuda')` is not required, as flair places models automatically on gpu if available.
* there is no need to create a dataset and iterate over it, as the `tagger.predict()` method does that anyways.
* tqdm can be activated by using `verbose=True`

With that, the code can be reduced to:
```
df = pd.read_csv('/kaggle/input/test-data-flair/fashion_color-2.csv')
test_sent = list(df['review'][0:1000])
sentences = [Sentence(text) for text in test_sent]
tagger.predict(sentences, mini_batch_size=128, verbose=True)

result = []
sent_list = []
for sent in i:
    sent_list.append(sent.to_plain_string())
    lx = []
    for entity in sent.get_spans('tag'):
        lx.append([entity.text,entity.tag,entity.score])
    result.append(lx)
```

This should already slightly speed up the predictions, as flair sorts the sentences by the lenght of the tokens to reduce the amount of padded tokens in each batch.

Another speedup can be achived by using half predicion for the transformers, assuming that you have only `TransformerWordEmbeddings` without any `StackedEmbeddings`, you can set that by using:
`tagger.embeddings.half()` or `tagger.token_embeddings.half()` depending on your version of flair.

When the gained speedup isn't large enough, you can play around with the `mini_batch_size`. While "larger is faster" is a common rule (meassuring the gpu memory usage), it can sometimes lead to a speedup when  you have a slightly lower batch size, depending on the token distribution of your texts.

**Comment by iliaNecrov** [comment]
> Hi @Jasheenshaik
> 
> Do you have statistics about the time it requires and a target in mind? If so, it might be helpful to mention it.
> 
> First of all I want to notice that there is a lot of code that is redundant to the library behaivour and can be removed:
> 
> * `tagger.to('cuda')` is not required, as flair places models automatically on gpu if available.
> * there is no need to create a dataset and iterate over it, as the `tagger.predict()` method does that anyways.
> * tqdm can be activated by using `verbose=True`
> 
> With that, the code can be reduced to:
> 
> ```
> df = pd.read_csv('/kaggle/input/test-data-flair/fashion_color-2.csv')
> test_sent = list(df['review'][0:1000])
> sentences = [Sentence(text) for text in test_sent]
> tagger.predict(sentences, mini_batch_size=128, verbose=True)
> 
> result = []
> sent_list = []
> for sent in i:
>     sent_list.append(sent.to_plain_string())
>     lx = []
>     for entity in sent.get_spans('tag'):
>         lx.append([entity.text,entity.tag,entity.score])
>     result.append(lx)
> ```
> 
> This should already slightly speed up the predictions, as flair sorts the sentences by the lenght of the tokens to reduce the amount of padded tokens in each batch.
> 
> Another speedup can be achived by using half predicion for the transformers, assuming that you have only `TransformerWordEmbeddings` without any `StackedEmbeddings`, you can set that by using: `tagger.embeddings.half()` or `tagger.token_embeddings.half()` depending on your version of flair.
> 
> When the gained speedup isn't large enough, you can play around with the `mini_batch_size`. While "larger is faster" is a common rule (meassuring the gpu memory usage), it can sometimes lead to a speedup when you have a slightly lower batch size, depending on the token distribution of your texts.

How correctly to use "half embeddings"?

```
tagger = SequenceTagger.load('models/deberta-v3-base_mean/final-model.pt')
tagger.embeddings.half()
s = Sentence('Hi')
tagger.embeddings.embed(s)
len(s.tokens[0].embedding)
```

```
tagger = SequenceTagger.load('models/deberta-v3-base_mean/final-model.pt')
s = Sentence('Hi')
tagger.embeddings.embed(s)
len(s.tokens[0].embedding)
```

```
s = Sentence('Hi')
tagger.embeddings.half().embed(s)
len(s.tokens[0].embedding)
```

In all of these examples output dimension is **768**.

**Comment by helpmefindaname** [comment]
> In all of these examples output dimension is **768**.

yes, `.half()` reduces the numeric precision and therefore makes the computation faster. It won't impact any dimensions.
