### ISSUE TITLE
[Feature]: Make konoha optional

### ISSUE THREAD

**Issue by marctorsoc** [flairNLP/flair#3059]
### Problem statement

I'm having a problem installing flair, since it **requires** https://github.com/flairNLP/flair/blob/master/requirements.txt#L20 `konoha<5.0.0,>=4.0.0`. This in turn makes this
```
  importlib-metadata<4.0.0,>=3.7.0 (from konoha==4.6.5->flair==0.11.3->my-repo (setup.py))
```

### Solution

I can see two solutions here, but lmk if there's another one (apart from pinning deps on my end, ofc):
* Given that most users (me included) won't use Japanese, make this an extra
* Fix `flair` to remove this pin and adapt to latest versions of `konoha`. I assume this is harder

**Comment by alanakbik** [comment]
Hello @marctorsoc good point and I would tend towards making konoha optional. This fits well with our general rule that libraries that are only needed for 1 feature should be optional.

**Comment by marctorsoc** [comment]
@alanakbik I'm happy to work on this one, if you explain how do you want to implement extras. At the moment I don't see any packages made optional

Shall I just remove `konoha` from `requirements.txt` and do something like this? https://github.com/globality-corp/globality-black/blob/master/setup.py#L45-L48

**Comment by alanakbik** [comment]
Normally, we do a check whether the library is installed and a printout with instructions for objects that use specific libraries. See for instance the SpacyTokenizer: https://github.com/flairNLP/flair/blob/15776018b150a3b8500e64a3a474e3c52674170c/flair/tokenization.py#L216 

I see we actually already have such a check implemented for konoha: https://github.com/flairNLP/flair/blob/15776018b150a3b8500e64a3a474e3c52674170c/flair/tokenization.py#L153 

So the easiest option would be to just remove it from the dependencies.

I haven't worked with optional dependencies yet, but a solution like you suggest for the option "japanese" could also be interesting.

**Comment by marctorsoc** [comment]
there you have it https://github.com/flairNLP/flair/pull/3060
