### ISSUE TITLE
Probability distribution for language model

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#306]
Hi,

I just found this nice blog post that shows how a language model can be visualized:

https://colinmorris.github.io/lm-sentences/#/

So I just want to ask how to get the probabilities for a next character from a trained language model with `flair`? I think such a visualization would be also great to include in `flair` :)

Thanks in advance :heart:

**Comment by bedapudi6788** [comment]
@stefan-it take a look at https://github.com/zalandoresearch/flair/issues/498
