### ISSUE TITLE
[Bug]: package training are 60 times slower

### ISSUE THREAD

**Issue by cjing1** [flairNLP/flair#3064]
### Describe the bug

I have been using the package for text classification a long time, and I noticed that since last Dec, the package is been much (60 times) slower than before. 

### To Reproduce

```python
document_embeddings = TransformerDocumentEmbeddings('vinai/bertweet-large', fine_tune=True)

clf = TextClassifier(document_embeddings, label_dictionary = label_dict_csv, label_type = 'labels')

trainer = ModelTrainer(clf,corpus)


trainer.train('data/',learning_rate=5.0e-5,
                 mini_batch_size=4,
                 max_epochs=50)
```

### Expected behaivor

I have been using the package for text classification for a long time, and I noticed that since last Dec, the package had been much (60 times) slower than before. I test the same training dataset and code on different devices. 

I am using version 0.11.3. 

The following are the logs for the training, one set of iter previous take less than 10 sec now take more than 10 mins. 

### Logs and Stack traces

```stacktrace
Before: 
2022-10-09 21:31:30,315 epoch 49 - iter 290/1459 - loss 0.10741235 - samples/sec: 62.43 - lr: 0.000025
2022-10-09 21:31:39,495 epoch 49 - iter 435/1459 - loss 0.10389860 - samples/sec: 63.60 - lr: 0.000025

Now: 

2023-01-01 18:04:44,396 epoch 9 - iter 290/1459 - loss 0.13797347 - samples/sec: 0.86 - lr: 0.000050
2023-01-01 18:15:55,733 epoch 9 - iter 435/1459 - loss 0.13327860 - samples/sec: 0.86 - lr: 0.000050
```

### Additional Context

Thank you so much for your help. 

##### Flair
0.11.3
##### Pytorch
1.13.1+cpu
##### Transformers
4.25.1
#### GPU
False

**Comment by alanakbik** [comment]
@cjing1 thanks for reporting this. To reproduce, could you name the last version for which it works for you?

**Comment by cjing1** [comment]
> @cjing1 thanks for reporting this. To reproduce, could you name the last version for which it works for you?

Thank you so much for your prompt reply. I don't think I update flair recently, so it should be the same version 0.11.3

**Comment by helpmefindaname** [comment]
Hi @cjing1 
I see that you are using a CPU and no GPU. Are you sure that this is the case also for the old training?
I would be very impressed if you managed to train 62.43 sentences/second on a bert-large model with the CPU, however I think it is more realistic that that was trained on the GPU.

**Comment by cjing1** [comment]
[training (9).log](https://github.com/flairNLP/flair/files/10520975/training.9.log)

Hi @helpmefindaname, 
Thank you for your reply. I think for my previous training, I am still using a CPU, the attachment is the full log from one of my previous training. 


> Hi @cjing1 I see that you are using a CPU and no GPU. Are you sure that this is the case also for the old training? I would be very impressed if you managed to train 62.43 sentences/second on a bert-large model with the CPU, however I think it is more realistic that that was trained on the GPU.

**Comment by helpmefindaname** [comment]
@cjing1 in your log file i see
```
2022-10-09 20:10:34,755 Model training base path: "data"
2022-10-09 20:10:34,756 ----------------------------------------------------------------------------------------------------
2022-10-09 20:10:34,756 Device: cuda:0
2022-10-09 20:10:34,757 ----------------------------------------------------------------------------------------------------
2022-10-09 20:10:34,757 Embeddings storage mode: cpu
```

the `Device: cuda:0` indicates that the training was ran on gpu and therefore it totally makes sense that it runs way faster.
You can install torch with cuda support again (for example using `pip install torch --extra-index-url https://download.pytorch.org/whl/cu116` or selecting the respective install command from [here](https://pytorch.org/).
Flair will use the gpu whenever it is available and compatible with your pytorch version.

**Comment by cjing1** [comment]
Hi @helpmefindaname, thank you so much for your help. I think you are right. I will double-check the setting.
