### ISSUE TITLE
[Question]: TUTORIAL_13 export_onnx model size and oom questions.

### ISSUE THREAD

**Issue by agademic** [flairNLP/flair#3065]
### Question

I am currently trying to reduce model size and memory consumption of a fine-tuned model. To this end I am following the TUTORIAL_13. To check out the changes in model size and consumption I am using the pre-trained `flair/ner-english-large` model which is 2135.899MB in size (disk space). To find out the size I am using this code snippet:

```
param_size = 0
for param in model.parameters():
    param_size += param.nelement() * param.element_size()
buffer_size = 0
for buffer in model.buffers():
    buffer_size += buffer.nelement() * buffer.element_size()

size_all_mb = (param_size + buffer_size) / 1024**2
print('model size: {:.3f}MB'.format(size_all_mb))
```

After calling `model.embeddings = model.embeddings.export_onnx("flert-embeddings.onnx", sentences, providers=["CUDAExecutionProvider", "CPUExecutionProvider"])` the model size reduces to 0.079MB which seems veeeeery odd to me. Calling `model.predict` here works fine though. Any ideas whether this is legit?

Another thing is that after calling 
```
model.embeddings.optimize_model(
            "flert-optimized-embeddings.onnx", opt_level=2, use_gpu=True, only_onnxruntime=True, use_external_data_format=True,
        )
```
and then
```
model.embeddings.quantize_model(
            "flert-quantized-embeddings.onnx", extra_options={"DisableShapeInference": True}, use_external_data_format=True
        )
```
my Colab runs oom. Which seems also odd to me, since I am trying to reduce memory consumption. Or does the quantization process itself takes a lot of memory but the embeddings have less consumption in the end?

Any hints to these points are highly appreciated!

**Comment by agademic** [comment]
Hi @helpmefindaname,
thank you so much for your reply!

What I now did is saving the model with:
```
model.save("temp.p")
print('Size (MB):', os.path.getsize("temp.p")/(1024*1024))
os.remove('temp.p')
```
with model being a `SequenceTagger` object.

Is this approach correct? I assume not since the file size is around 16MB. What does that `.save` method save then?

Instead, I guess you mean all the model.embeddings..., model.encoder.layer... and onnx files combined? If I don't save and load the model with the default flair methods, how would I load the onnx exported files?

Thank you in advance!

**Comment by helpmefindaname** [comment]
Hi again,
I don't think that fulfills 

> and looking at the size of *all created files*.
as you are only looking at one. The onnx model creates more files due to their limit of 2GB.
