### ISSUE TITLE
Spanish flair NER model for judical resolutions

### ISSUE THREAD

**Issue by jedzill4** [flairNLP/flair#3068]
Hi! We are [Collective AI team](https://collectiveai.io/), a group of machine learning engineers that works on several AI projects. In collaboration with [DataGénero](https://www.datagenero.org/), we have developed a NER model in Spanish for processing judicial resolutions. This model serves as the backbone of [AymurAI](https://www.aymurai.info/inicio) (the website is just in spanish for now), a software that will collaborate with criminal court officials in Argentina and Mexico in the tasks of generating and maintaining anonymized datasets for understanding gender-based violence against women and LGBTIQ+ people in Latin America.

We are opening the code, and we would like to contribute to Flair by integrating our model to your public hub. We believe this would be helpful for many other criminal court officials in Latin America and NLP researchers that work with Spanish corpus.

What are the steps to add the model to the library?

If you want to know more about the project, you can read the paper published last year [here](https://www.aymurai.info/nuestra-investigaci%C3%B3n) ([english](https://drive.google.com/file/d/1P-hW0JKXWZ44Fn94fDVIxQRTExkK6m4Y/view) and [spanish](https://drive.google.com/file/d/1wtQ6nhG-B4sUSjEIPAXHnqXeFIJlXH3o/view) versions).

**Comment by alanakbik** [comment]
Hello @jedzill4 thanks for letting us know about the project and great that you found Flair useful here! I could not access the paper - what does your model predict?

Contributing a model is quite easy and you have several options how to do it: 
- if your model is a `SequenceTagger`, you can push it to the Huggingface Hub. For instance like [this model](https://huggingface.co/megantosh/flair-arabic-multi-ner). Advantages are that you don't need to host yourself and there is an automatic online demo. However, I think (not sure) by using their hub you give some rights over your model to Huggingface so if that is problematic best clarify before. 
- alternatively, you can host the model on your own server and do a PR like [this one](https://github.com/flairNLP/flair/pull/2492). Essentially extend the fetch_model method of the model class with the URL where you host the model.
- alternatively, you can host the model on your server (or we host it on our university server) and someone in our team will do the PR for you

**Comment by jedzill4** [comment]
Hi @alanakbik! thanks for the fast answer!
> I could not access the paper - what does your model predict?

Sorry, I updated the links ([here](https://drive.google.com/file/d/1P-hW0JKXWZ44Fn94fDVIxQRTExkK6m4Y/view) is the English version of the paper). The model is on top of [BETO embeddings](https://huggingface.co/dccuchile/bert-base-spanish-wwm-cased) and finetuned on Argentinian court documents/resolutions to predict some common entities like names, locations, and important dates; also other important entities for our domain like broken laws, types of violence involved in the case, violent quotes and decisions or rulings made by the judge.

> Contributing a model is quite easy and you have several options how to do it:
> 
> * if your model is a `SequenceTagger`, you can push it to the Huggingface Hub. For instance like [this model](https://huggingface.co/megantosh/flair-arabic-multi-ner). Advantages are that you don't need to host yourself and there is an automatic online demo. However, I think (not sure) by using their hub you give some rights over your model to Huggingface so if that is problematic best clarify before.
> 
> * alternatively, you can host the model on your own server and do a PR like [this one](https://github.com/flairNLP/flair/pull/2492). Essentially extend the fetch_model method of the model class with the URL where you host the model.
> 
> * alternatively, you can host the model on your server (or we host it on our university server) and someone in our team will do the PR for you

Thanks. I think we are going to go with the huggingface alternative.

**Comment by alanakbik** [comment]
Thanks for the info! Let me know when the model is posted on HF - I'd be interested to try it out. 

Is the training data you used for the model public as well?
