### ISSUE TITLE
 [Question]:  Confidence scores for sequence tagger when crf layer is used

### ISSUE THREAD

**Issue by MarouaBoudabous** [flairNLP/flair#3070]
### Question

Hi,
In the sequence tagger implementation, the confidence scores are associated to the max of scores matrix . Isn't it more accurate to use the decoding process over the scores matrix to get the confidence score for each token?

Actually, I noticed in the results that the tags associated to the confidence scores are different from the ones in the all_tags matrix. Is it the expected way to compute the confidence scores ?

Any help is appreciated.

**Comment by alanakbik** [comment]
@MarouaBoudabous thanks for raising this question - @whoisjones can you take a look?

**Comment by whoisjones** [comment]
hi @MarouaBoudabous,

regarding your first question: since naming is sometimes different across functions, I try to be as precise as I can. If use use a CRF in flair, the `forward` method of the `SequenceTagger` will use the CRF in both, the `forward_loss` called during training, and `predict` during evaluation. So `scores` (in `forward_loss`) and `features` (in `predict`) are equal since we do not know at that time whether we are actually dealing with scores or features. If you use a CRF in `predict`, we use Viterbi Decoding for inference to assign the scores using the decoding process. In line 209 of the `viterbi.py`:

```
        scores = softmax(scores_upto_t, dim=2)
        confidences = torch.max(scores, dim=2)
```
should do exactly what you are asking for, right?

Regarding your second question, can you please provide a minimal example of how this occurs?

**Comment by MarouaBoudabous** [comment]
hi @whoisjones ,

Thanks for your response.

Exactly I am interested in the lines you mentioned above. I wonder why you associate the highest confidence score with the predicted tags. I thought that CRF finds the best tag sequence, which does not assume that the selected tag at each step is the most confident (actually, it depends also on the transitions score).

The mismatch can also be seen in the outputs of the `viterbi_decoder.decode` function. Hereafter an example of the results I obtained:

````
tags = [('o', 0.9924472570419312),

 ('o', 0.9755145907402039),

 ('o', 0.9918153882026672),

 ('o', 0.9741249680519104),

 ('o', 0.5291169285774231),

 ('o', 0.8400788307189941),

 ('o', 0.9923754334449768),

 ('o', 0.9985438585281372),

 ('o', 0.8875763416290283),

 ('o', 0.5794795751571655),

 ('o', 0.6552749276161194),

 ('o', 0.8611258268356323),...]
````

```
all_tags = [['Token[0]: "Je"'/'o' (0.9923999905586243), 

  'Token[0]: "Je"'/'b' (0.0027000000700354576),

  'Token[0]: "Je"'/'i' (0.0003000000142492354),

  'Token[0]: "Je"'/'<START>' (0.0),

  'Token[0]: "Je"'/'<STOP>' (0.004600000102072954)],

 ['Token[1]: "recommande"'/'o' (0.9754999876022339),

  'Token[1]: "recommande"'/'b' (0.004600000102072954),

  'Token[1]: "recommande"'/'i' (9.999999747378752e-05),

  'Token[1]: "recommande"'/'<START>' (0.0),

  'Token[1]: "recommande"'/'<STOP>' (0.01979999989271164)],

 ['Token[2]: "!"'/'o' (0.9918000102043152),

  'Token[2]: "!"'/'b' (0.0010999999940395355),

  'Token[2]: "!"'/'i' (0.0),

  'Token[2]: "!"'/'<START>' (0.0),

  'Token[2]: "!"'/'<STOP>' (0.0071000000461936)],

 ['Token[3]: "!"'/'o' (0.9740999937057495),

  'Token[3]: "!"'/'b' (0.007799999788403511),

  'Token[3]: "!"'/'i' (0.0),

  'Token[3]: "!"'/'<START>' (0.0),

  'Token[3]: "!"'/'<STOP>' (0.017999999225139618)],

 ['Token[4]: "Coque"'/'o' (0.32760000228881836),

  'Token[4]: "Coque"'/'b' (0.5291000008583069),

  'Token[4]: "Coque"'/'i' (0.0019000000320374966),

  'Token[4]: "Coque"'/'<START>' (0.0),

  'Token[4]: "Coque"'/'<STOP>' (0.1412999927997589)],

 ['Token[5]: "reçu"'/'o' (0.8400999903678894),

  'Token[5]: "reçu"'/'b' (0.052299998700618744),

  'Token[5]: "reçu"'/'i' (0.0575999990105629),

  'Token[5]: "reçu"'/'<START>' (0.0),

  'Token[5]: "reçu"'/'<STOP>' (0.05009999871253967)],

 ['Token[6]: "dans"'/'o' (0.9923999905586243),

  'Token[6]: "dans"'/'b' (0.0003000000142492354),

  'Token[6]: "dans"'/'i' (0.0020000000949949026),

  'Token[6]: "dans"'/'<START>' (0.0),

  'Token[6]: "dans"'/'<STOP>' (0.005200000014156103)],

 ['Token[7]: "les"'/'o' (0.9984999895095825),

  'Token[7]: "les"'/'b' (0.0),

  'Token[7]: "les"'/'i' (0.0),

  'Token[7]: "les"'/'<START>' (0.0),

  'Token[7]: "les"'/'<STOP>' (0.00139999995008111)],

 ['Token[8]: "temps"'/'o' (0.8876000046730042),

  'Token[8]: "temps"'/'b' (0.05820000171661377),

  'Token[8]: "temps"'/'i' (0.0003000000142492354),

  'Token[8]: "temps"'/'<START>' (0.0),

  'Token[8]: "temps"'/'<STOP>' (0.05400000140070915)],

 ['Token[9]: "superbe"'/'o' (0.5795000195503235),

  'Token[9]: "superbe"'/'b' (0.32359999418258667),

  'Token[9]: "superbe"'/'i' (0.004600000102072954),

  'Token[9]: "superbe"'/'<START>' (0.0),

  'Token[9]: "superbe"'/'<STOP>' (0.09229999780654907)],

 ['Token[10]: "finition"'/'o' (0.18950000405311584),

  'Token[10]: "finition"'/'b' (0.6553000211715698),

  'Token[10]: "finition"'/'i' (0.06340000033378601),

  'Token[10]: "finition"'/'<START>' (0.0),

  'Token[10]: "finition"'/'<STOP>' (0.09179999679327011)],

 ['Token[11]: "!"'/'o' (0.8611000180244446),

  'Token[11]: "!"'/'b' (0.05220000073313713),

  'Token[11]: "!"'/'i' (0.05000000074505806),

  'Token[11]: "!"'/'<START>' (0.0),

  'Token[11]: "!"'/'<STOP>' (0.03660000115633011)], ...]
```

At token 4, for example, the predicted tag is 'o' with a confidence score of '0.5291'. However, in the all_tags matrix, the confidence score '0.5291' is associated with the tag 'b'. Token 10 also shows a mismatch between tags and all_tags outputs.

**Comment by qingtao12138** [comment]
Hi,
i have the same question,  tags and all_tags mismatch in score 🤔
