### ISSUE TITLE
[Question]: Unicode error

### ISSUE THREAD

**Issue by Mitthat** [flairNLP/flair#3071]
### Question

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6173: character maps to <undefined> while install flair
pip install flair causes this error

**Comment by helpmefindaname** [comment]
Hi @Mitthat 
can you please add the full stacktrace for the context of where that Error happens exactly?

**Comment by Mitthat** [comment]
![image](https://user-images.githubusercontent.com/111500750/215710778-f2bc1a46-a698-43d2-96e8-5e5f3924258f.png)
This what it looks like when I run pip install flair

**Comment by frederick0291** [comment]
Having the same issue on Python 3.11
