### ISSUE TITLE
[Question]: Argument add_unk in corpus.corpus.make_label_dictionary not identified

### ISSUE THREAD

**Issue by AlphaBit95** [flairNLP/flair#3074]
### Question

@alanakbik 

I’m still facing this issue on the version 0.11.3. 

Logs:
2023-01-28 21:58:59,809 The string 'B-' is not in dictionary! Dictionary contains only: ['O', 'S-INNOVATION', 'B-INNOVATION', 'E-INNOVATION', 'I-INNOVATION', 'S-UTILIZATION', 'B-UTILIZATION', 'E-UTILIZATION', 'I-UTILIZATION', 'S-MATERIAL', 'B-MATERIAL', 'E-MATERIAL', 'I-MATERIAL', '<START>', '<STOP>']
2023-01-28 21:58:59,810 You can create a Dictionary that handles unknown items with an <unk>-key by setting add_unk = True in the construction.
  0%| 

I also tried adding the argument explicitly as follows:

tag_dictionary = corpus.make_label_dictionary("ner", add_unk=True)

<img width="616" alt="Screenshot 2023-01-28 at 23 13 36" src="https://user-images.githubusercontent.com/95974539/215293512-38c66ccd-7215-4843-9a91-fad7609c53fe.png">

But it does not seem to be recognised as I the get the following error:
    tag_dictionary = corpus.make_label_dictionary("ner", add_unk=True)
TypeError: make_label_dictionary() got an unexpected keyword argument 'add_unk'

(This is issue is related to the closed issue #2777, which was closed with no conclusion)

**Comment by helpmefindaname** [comment]
Hi @AlphaBit95 
assuming that your training data is private: can you narrow down to a sentence that causes this error and give a similar sentence causing the same error?

**Comment by alanakbik** [comment]
Hello @AlphaBit95, the tag dictionary you pass to the sequence tagger is different from the internal tags the tagger then predicts. 

For instance, your tag dictionary computed over the corpus might be [`INNOVATION`, `MATERIAL`]. The SequenceTagger will then compute BIOES tags for these labels, and will predict  [`B-INNOVATION`, `I-INNOVATION`,`E-INNOVATION`, `S-INNOVATION`] etc. 

The error message `The string 'B-' is not in dictionary!` means that for some reason, the tagger wants to predict a label without a label name. Is this error thrown during evaluation or during training? Can you share the logs?

**Comment by AlphaBit95** [comment]
Hey @helpmefindaname and @alanakbik. Thank you for your quick response. I went back and investigated the tags in my test file. The test file which I was using was an external one, which uses the BILOU format, while my model was trained with data using the BIOES format. This might have caused the issue. After I fixed my external test file, I do not face the issue anymore. Thank you! :)

But this still leaves me with the question of the add_unk argument. 

Firstly, when I pass the add_unk=True argument to the make_label_dictionary(), I get the following error. 
TypeError: make_label_dictionary() got an unexpected keyword argument 'add_unk'. I guess I was misled by this.

Secondly, shouldn't the add_unk argument handle the unknown labels? Or is my understanding wrong?

**Comment by helpmefindaname** [comment]
@AlphaBit95 the `add_unk` was introduced after `0.11.3` was released, so you can only use it if you install the master branch, however you don't need to set it to True, as that is the default behaivour.

For Named Entity Recognition, a new Dictionary is created with the respective BIOES or BIO tags: https://github.com/flairNLP/flair/blob/v0.11.3/flair/models/sequence_tagger_model.py#L88 Notice that you can configure this one by using `model = SequenceTager(..., allow_unk_predictions=True)`, however I would recommend you to rather fix the training data  format and keep that parameter to False.

We currently have plans to change the unk behaivour to make it more robust for such cases, but there is no implementation yet.

**Comment by AlphaBit95** [comment]
@helpmefindaname Thank you very much for the clarification! 👍🏼 :)

**Comment by xiulinyang** [comment]
> @AlphaBit95 the `add_unk` was introduced after `0.11.3` was released, so you can only use it if you install the master branch, however you don't need to set it to True, as that is the default behaivour.
> 
> For Named Entity Recognition, a new Dictionary is created with the respective BIOES or BIO tags: https://github.com/flairNLP/flair/blob/v0.11.3/flair/models/sequence_tagger_model.py#L88 Notice that you can configure this one by using `model = SequenceTager(..., allow_unk_predictions=True)`, however I would recommend you to rather fix the training data format and keep that parameter to False.
> 
> We currently have plans to change the unk behaivour to make it more robust for such cases, but there is no implementation yet.

Hi, thanks a lot for the detailed explanation. I was just wondering, why do you recommend to keep ```allow_unk_predictions``` to False? My BIO system is a bit complex so I'm expecting that the dev set might have unseen BIO tags in the train set.

**Comment by helpmefindaname** [comment]
@xiulinyang Because `<unk>` is no BIO tag, those start with either `B-` `I-` (`E-`, ...) or are `O`. Hence the decoding would be arbitrary but not exactly the way one would expect it.

For the case of having other tags in the dev/test-sets, I would recommend setting `add_dev_test=True`, see https://github.com/flairNLP/flair/blob/master/flair/data.py#L1545
**Notice:** that parameter is not available in flair 0.11.3, so you'd need to install the master branch of flair to use it or wait for the next release.

The unk logic is more for cases where you specify a `min_count` in text-classification or span-classification, so the train set has some examples to predict `<unk>` and tests that on the eval/test sets correctly.

**Comment by xiulinyang** [comment]
I see. It makes sense! Thanks. :)
