### ISSUE TITLE
[Bug]: How to get actually pos tags with Flair, solution inside 

### ISSUE THREAD

**Issue by Oxi84** [flairNLP/flair#3079]
### Describe the bug

If this is a pos tagger i expect that output is pos tags in easy to use form

### To Reproduce

```python
from flair.data import Sentence
    from flair.models import SequenceTagger  
    #load tagger
    tagger = SequenceTagger.load("flair/pos-english")
    # make example sentence
    sentence = Sentence("George Washington went to Washington.")
    # predict with both models
    tagger.predict(sentence)
    
    for label in sentence.get_labels('pos'):
        print(label)
```

### Expected behaivor

It is expected to print pos tags (or ner tags for ner). It outoputs text that contains pos tags and is not easy to extract from.

Token[0]: "George" → NNP (1.0)
Token[1]: "Washington" → NNP (1.0)
Token[2]: "went" → VBD (1.0)
Token[3]: "to" → IN (0.7628)
Token[4]: "Washington" → NNP (1.0)
Token[5]: "." → . (1.0)

### Environment

unix

**Comment by Oxi84** [comment]
Something like this is a solution. Non need that everyone parse the results:

     def calculate_tags(tagger,asent):
         sentence = Sentence("George Washington, went to Washington.")
         tagger.predict(sentence)
         m = sentence.to_tagged_string()
         sent1 = m.split("→ [")[1][:-1]
         tokens = [x.split("/")[0].replace('"','') for x in sent1.split()]
         poses = [x.split("/")[1] for x in sent1.split()]
         poses_0 = [x[:-1] for x in poses[:-1]] + [poses[-1]]
         atags = list(zip(tokens,poses_0))
         return atags

    import flair
    print("load the pos tagger")
    from flair.data import Sentence
    from flair.models import SequenceTagger  
    #load tagger
    tagger = SequenceTagger.load("flair/pos-english")
    
    asent = "George Washington, went to Washington."
    # make example sentence
    thetags = calculate_tags(tagger,asent)
    
    print("thetags",thetags)

**Comment by helpmefindaname** [comment]
Hi @Oxi84 
what you are looking for is the `value` attribute of the label:
```python
for label in sentence.get_labels('pos'):
    print(label.value)
```
prints 
```
NNP
NNP
VBD
IN
NNP
.
```

or

```python
for label in sentence.get_labels('pos'):
    print(label.value, label.score)
```
prints
```
NNP 0.999998927116394
NNP 1.0
VBD 0.9999998807907104
IN 0.7627835869789124
NNP 1.0
. 0.9999840259552002
```

**Comment by Oxi84** [comment]
Awesome, and how would i get token.
Because i need standard out for a tagger:
[[word1, pos1],[word2, pos2] ...]

**Comment by helpmefindaname** [comment]
@Oxi84 you can look this up in the [respective tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_1_BASICS.md#accessing-label-information)

**Comment by faustusdotbe** [comment]
@helpmefindaname 's link is dead, updated is https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_FLAIR_BASICS.md#accessing-label-information

**Comment by alanakbik** [comment]
We also now have updated tutorials on our new documentation website: 
- How to access label information: https://flairnlp.github.io/docs/tutorial-basics/how-predictions-work 
- Flair basics (really helps with everything): https://flairnlp.github.io/docs/tutorial-basics/basic-types

**Comment by dicleozturk** [comment]
> Awesome, and how would i get token. Because i need standard output for a tagger: [[word1, pos1],[word2, pos2] ...]

try token.text.
