### ISSUE TITLE
[Feature]: allow proxy parameter to load models/embeddings

### ISSUE THREAD

**Issue by Guust-Franssens** [flairNLP/flair#3080]
### Problem statement

At the time of writing, I don't see a way to download models when the machine is situated behind a Proxy Server.
This issue has been raised before (https://github.com/flairNLP/flair/issues/1249), however it was closed due to staleness (and not fixed).

### Solution

For methods that allow for a download, allow for a proxy configuration to be passed. This can then be passed to the method that handles downloading from URL.

I believe the following snippet handles the downloading, but correct me if I am wrong:

https://github.com/flairNLP/flair/blob/a22e70abf0d164cb199cf8f40a13f9eca428547e/flair/file_utils.py#L223-L269

Allowing for proxy can be done simply with requests. However the parameter for the proxy would need to be added to all methods that download over URL or be able to get set as a config in someway.

```python
http_proxy  = "http://10.10.1.10:3128"
https_proxy = "https://10.10.1.11:1080"
ftp_proxy   = "ftp://10.10.1.10:3128"

proxies = { 
              "http"  : http_proxy, 
              "https" : https_proxy, 
              "ftp"   : ftp_proxy
            }

r = requests.get(url, headers=headers, proxies=proxies)
```
source: https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module

I might try to contribute later if I have time.

**Comment by helpmefindaname** [comment]
Hi @Guust-Franssens I can see how this adds value, so I implemented a draft for it: https://github.com/flairNLP/flair/pull/3082 however I have no proxy setup so I cannot fully test it. Can you try it out?

**Comment by Guust-Franssens** [comment]
Hey @helpmefindaname, 

Tested it and it works! 
Code used for testing:

```python
def set_proxies(proxies: typing.Dict[str, str]) -> None:
    """
    Allows for data downloaded from urls to be forwarded to a proxy, see https://requests.readthedocs.io/en/latest/user/advanced/#proxies
    :param proxies: A dictionary of proxies according to the requests documentation.
    :return: None
    """
    global url_proxies
    url_proxies = proxies

set_proxies({"http": "...", "https": "..."})

# test on random flair embedding
req = requests.get("https://flair.informatik.hu-berlin.de/resources/embeddings/flair/lm-pt-forward.pt", stream=True, headers={"User-Agent": "Flair"}, proxies=url_proxies)

print(req)

>>> <Response [200]>
```
