### ISSUE TITLE
[Question]: Error when loading Camembert Embeddings

### ISSUE THREAD

**Issue by ellzx** [flairNLP/flair#3096]
### Question

Hello, 
I could not load the Camembert Embeddings. 

----> 1 embedding = CamembertEmbeddings()

File ~/venv-3.8/lib/python3.8/site-packages/deprecated/classic.py:285, in deprecated.<locals>.wrapper_function(wrapped_, instance_, args_, kwargs_)
    283 else:
    284     warnings.warn(msg, category=category, stacklevel=_routine_stacklevel)
--> 285 return wrapped_(*args_, **kwargs_)

File ~/venv-3.8/lib/python3.8/site-packages/flair/embeddings/legacy.py:690, in CamembertEmbeddings.__init__(self, pretrained_model_name_or_path, layers, pooling_operation, use_scalar_mix)
    687 self.use_scalar_mix = use_scalar_mix
    688 self.static_embeddings = True
--> 690 dummy_sentence: Sentence = Sentence()
    691 dummy_sentence.add_token(Token("hello"))
    692 embedded_dummy = self.embed(dummy_sentence)

TypeError: __init__() missing 1 required positional argument: 'text'

**Comment by helpmefindaname** [comment]
Hi @ellzx 
as a warning probably mentioned before the error: 
`CammenbertEmbeddings` are deprecated and no longer maintained. Use `TransformerWordEmbeddings("camembert-base")` instead.
