### ISSUE TITLE
[Question]: How to get str representation of Sentence to show multiple labels?

### ISSUE THREAD

**Issue by msummerfield** [flairNLP/flair#3110]
### Question

As per the excellent Flair tutorials, tagging a sentence with a pre-trained sequence tagger results in a Sentence object that, when printed, lists all of the labels and associated tokens, e.g.

```
>>> sentence = Sentence('George Washington went to Washington.')
>>> tagger.predict(sentence)
>>> print(sentence)
Sentence: "George Washington went to Washington ." → ["George Washington"/PER, "Washington"/LOC]
```
However, if I manually label a Sentence, I get a different result, e.g.

```
>>> sentence = Sentence(['The', 'grass', 'is', 'green', '.'])
>>> sentence[3].set_label('ner', 'color')
>>> print(sentence)
Sentence: "The grass is green ." → ["green"/color]
>>> sentence[1].set_label('ner', 'plant')
>>> print(sentence)
Sentence: "The grass is green ." → ["grass"/plant]
```

It appears that only the most recently added label is shown, although all are present in the Sentence:

```
>>> for t in sentence: print(t)
... 
Token[0]: "The"
Token[1]: "grass" → plant (1.0)
Token[2]: "is"
Token[3]: "green" → color (1.0)
Token[4]: "."
```

Is there something that I am failing to do here when labelling the Sentence in order to get the same behaviour as the one labelled by the sequence tagger?

Thanks for any pointers.

Mark

**Comment by alanakbik** [comment]
Hello @msummerfield what Flair version are you on? If I try this code in master branch it works: 

```python
sentence = Sentence(['The', 'grass', 'is', 'green', '.'])
sentence[3].set_label('ner', 'color')
print(sentence)
sentence[1].set_label('ner', 'plant')
print(sentence)
```

which prints: 
```console
Sentence[5]: "The grass is green ." → ["grass"/plant, "green"/color]
```

**Comment by msummerfield** [comment]
Thanks for responding. I'm on version 0.11.3.

Knowing this works properly on the master branch, I had a look at relatively recent commits to relevant parts of the code (implementations of `set_label` in `data.py`) and found it fixed by [Do not remove other labels of sentence for set_label on Token and Span](https://github.com/flairNLP/flair/commit/45e3b2dfaf1a23416d0858217a29564c9b08fa42).

I also found that the workaround, while staying on 0.11.3 for now, is to use add_label instead of set_label.
