### ISSUE TITLE
[Feature]: Lower-Cased Entity Linking ZELDA

### ISSUE THREAD

**Issue by Zoher15** [flairNLP/flair#3133]
### Problem statement

Flair does not detect lower cased entities. Severely limiting its use for real-world data because people never correctly capitalize their text.....

'The climate is good in new york.'
and
'The climate is good in New York.'

should yield the same result, but it does not. This is a major issue even for named entity recognition....

### Solution

There is a [paper](https://ojs.aaai.org/index.php/AAAI/article/view/6368) to address this which talks about mixing up the case of entities in training data.

**Comment by alanakbik** [comment]
@Zoher15 good point, perhaps for the next release we should include models that are trained over lowercased text as well.
