### ISSUE TITLE
[Question]: Is BIO Tag Scheme still supported in v0.12

### ISSUE THREAD

**Issue by None-Such** [flairNLP/flair#3136]
### Question

**Question**
If so how can if be utilized (presuming my data is in the BIO Tag Scheme)?

**Background** 
In the transition from v0.10 to v0.11.3 the default Tag Scheme changed from BIO to BIOES - which I was told was based on research that BIOES can provide slightly better F-scores. However, I have found that the roughly doubling in tags generated by the BIOES Scheme cuts in half the batch size that can fit in a given GPU. And thus roughly doubles the training time. As my model continues to grow, I am getting squeezed out of my GPU. At present I can only fit a batch size 4 =(

I was hoping to do some more experimentation on F-scores delta between BIO to BIOES. Happy to report back what I learn if I can just get it to work.

**Comment by alanakbik** [comment]
Hello @None-Such yes it is still supported. You can set the tag format when you initialize the SequenceTagger: 


```python
# initialize sequence tagger with BIO instead of BIOES
tagger = SequenceTagger(hidden_size=256,
                        embeddings=embeddings,
                        tag_dictionary=label_dict,
                        tag_type=label_type,
                        tag_format="BIO",
                        )
```
