### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility

### ISSUE THREAD

**Issue by kylemcq13** [flairNLP/flair#3141]
Hello, as of the most recent release I'm getting the following error importing Sentence and Classifier.

from flair.data import Sentence
from flair.nn import Classifier

Error: 
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Numpy version is 1.20.3

Any ideas? Thanks!

**Comment by sandeepgudla** [comment]
I am getting the same error

**Comment by aarif1996** [comment]
I'm also getting the same issue

**Comment by s6nlbeck** [comment]
I ran into the same issue. This can be fixed when you install another numpy version afterwards, like this:
%pip install flair
%pip install numpy==1.23.0

**Comment by rx2347** [comment]
> I ran into the same issue. This can be fixed when you install another numpy version afterwards, like this: %pip install flair %pip install numpy==1.23.0

Worked for me on Ubuntu 22.04 with Python 3.10.6 and the latest Flair version, thanks for the tipp.

**Comment by helpmefindaname** [comment]
Closing this, as I suppose that Numpy fixed this issue on their side. Atleast I don't see a reason that flair needs to be fixed in that regard.
