### ISSUE TITLE
[Feature]: Allow setting device through environment variable

### ISSUE THREAD

**Issue by HallerPatrick** [flairNLP/flair#3147]
### Problem statement

Flair uses per default "cuda:0" as device if cuda is available. To use a different available GPU one has to manually set the target device with `flair.device = "cuda:<target_id>"`. 

This requires a user implementation of setting the flair device manually through something like `argparse` before running any flair code.

### Solution

I would propose an environment variable that allows the user to set the target device before hand.
So running flair code with the e.g second GPU device would look something like following:

```bash
FLAIR_DEVICE=1 python flair_script.py
```

If no such device can be found during runtime `flair` would fall back to using `cuda:0` or the `cpu`.

### Additional Context

If you find this request acceptable, I would be happy to implement it.

**Comment by alanakbik** [comment]
Sounds useful, thanks for suggesting this. Would the current method with setting `flair.device` still work with your solution if this environment variable is not yet?

**Comment by HallerPatrick** [comment]
Yes. It would still work the same.

I have no full knowledge of the complete code base. But the flair device is set only in the `flair.__init__.py`. Therefore all subsequent changes to `flair.device` would overwrite the predefined target GPU set through the environment variable. This would ensure that current user code (that changes the device during runtime) still works as intended.

**Comment by alanakbik** [comment]
Yes, but wait until the new docs page comes online. We are moving the docs out of github to a separate doc page.

**Comment by helpmefindaname** [comment]
Hi @HallerPatrick 
in case you don't know: you can control which gpu devices are visible to pytorch/tf/etc. by setting the `CUDA_VISIBLE_DEVICES` environment variable.

Flair automatically chooses the first device, so you can control there which one is used:
```
CUDA_VISIBLE_DEVICES=1 python flair_script.py  # use gpu 1
CUDA_VISIBLE_DEVICES=none python flair_script.py  # use cpu
```

see [here](https://developer.nvidia.com/blog/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) for mor information.
