### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by larsbun** [flairNLP/flair#3151]
### Question

How can I create a custom evaluation metric for the SequenceTagger? I would like to use F05 and not F1-score.

I can't find any option to the trainer for alternative scoring during training.

**Comment by plonerma** [comment]
Hello @larsbun, it is currently not planned to enable custom scores in the trainer. However, you can derive the `SequenceTagger` class, overwrite the `evaluate` function, and compute custom metrics there.
