### ISSUE TITLE
Finetuning a pretrained model through trainer giving an error  

### ISSUE THREAD

**Issue by Meet1995** [flairNLP/flair#3153]
### Question

Hi, I am following the tutorial in [this](https://github.com/flairNLP/flair/blob/master/resources/docs/HUNFLAIR_TUTORIAL_2_TRAINING.md) link to understand the fine-tuning process in flair. But, loading the `best-model.pt` saved by trainer is giving me the following error:

```
RuntimeError: Error(s) in loading state_dict for SequenceTagger:
	Missing key(s) in state_dict: "embeddings.list_embedding_0.embedding.weight".
```

Following is my exact code:
```
# 1. load your target corpus
from flair.datasets import NCBI_DISEASE
corpus = NCBI_DISEASE()

# 2. load the pre-trained sequence tagger
from flair.models import SequenceTagger
tagger: SequenceTagger = SequenceTagger.load("hunflair-disease")

# 3. initialize trainer
from flair.trainers import ModelTrainer
trainer: ModelTrainer = ModelTrainer(tagger, corpus)

# 4. fine-tune on the target corpus
trainer.fine_tune(
    base_path="taggers/lstm-crf",
    train_with_dev=False,
    max_epochs=1,
    learning_rate=0.1,
    mini_batch_size=64
)
```

Screenshot of error:
![image](https://user-images.githubusercontent.com/41198480/225642619-9dfd5624-f40e-4f95-98b3-7dd6eea8383d.png)

Library versions:
![image](https://user-images.githubusercontent.com/41198480/225642912-4ebf6884-13f9-4d90-9952-97c3aa586cfa.png)

Did I use any training argument incorrectly? I would appreciate any help.

Thanks!

**Comment by Meet1995** [comment]
Thank you @helpmefindaname, it worked!

**Comment by marcglobality** [comment]
@Meet1995 @helpmefindaname can any of you explain why that magic line would work? 🙏
