### ISSUE TITLE
[Feature]: FlairNLP Pytorch 2.0 support

### ISSUE THREAD

**Issue by akkefa** [flairNLP/flair#3154]
### Problem statement

When will flairnlp get support for pytorch 2.0.

### Solution

Update all required packages which support pytorch 2.0

**Comment by helpmefindaname** [comment]
Hi @akkefa 
what is missing for pytorch 2.0 support? From what I heard, it is a drop-in replacement and should work out of the box?
Have you tried it out and it didn't work?

**Comment by helpmefindaname** [comment]
Hi @akkefa 
thanks for pointing out, transformer-smaller-training-vocab allows torch 2.0 now
