### ISSUE TITLE
[Question]: Best way to run a Flair NER model in parallel across different points in an application

### ISSUE THREAD

**Issue by rafgonlop1** [flairNLP/flair#3163]
### Question

Hello Flair team,

I am currently using a Named Entity Recognition (NER) model built with Flair in various points of my application. I would like to know the most efficient way to run this model in parallel. Is it necessary to load the model into memory at each point in the application where it is used? What is the recommended approach to achieve this?

Thank you in advance for your help!

**Comment by iliaNecrov** [comment]
I have the same question now. Please let me know if you have an answer.
