### ISSUE TITLE
[Question]: Cannot install flair on my Mac Air M1, how to fix this?

### ISSUE THREAD

**Issue by firdovsi9** [flairNLP/flair#3171]
### Question

ERROR: Cannot install flair==0.1.1, flair==0.10, flair==0.11, flair==0.11.1, flair==0.11.2, flair==0.11.3, flair==0.12, flair==0.12.1, flair==0.2.1, flair==0.3.0, flair==0.3.1, flair==0.3.2, flair==0.4.0, flair==0.4.1, flair==0.4.2, flair==0.4.3, flair==0.4.4, flair==0.4.5, flair==0.5, flair==0.5.1, flair==0.6, flair==0.6.0.post1, flair==0.6.1, flair==0.6.1.post1, flair==0.7, flair==0.8, flair==0.8.0.post1 and flair==0.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    flair 0.12.1 depends on torch!=1.8 and >=1.5.0
    flair 0.12 depends on torch!=1.8 and >=1.5.0
    flair 0.11.3 depends on torch!=1.8 and >=1.5.0
    flair 0.11.2 depends on torch!=1.8 and >=1.5.0
    flair 0.11.1 depends on torch!=1.8 and >=1.5.0
    flair 0.11 depends on torch!=1.8 and >=1.5.0
    flair 0.10 depends on torch!=1.8 and >=1.5.0
    flair 0.9 depends on torch!=1.8 and >=1.5.0
    flair 0.8.0.post1 depends on torch<=1.7.1 and >=1.5.0
    flair 0.8 depends on torch>=1.5.0
    flair 0.7 depends on torch>=1.1.0
    flair 0.6.1.post1 depends on torch>=1.1.0
    flair 0.6.1 depends on torch>=1.1.0
    flair 0.6.0.post1 depends on torch>=1.1.0
    flair 0.6 depends on torch>=1.1.0
    flair 0.5.1 depends on torch>=1.1.0
    flair 0.5 depends on torch>=1.1.0
    flair 0.4.5 depends on torch>=1.1.0
    flair 0.4.4 depends on torch>=1.1.0
    flair 0.4.3 depends on torch>=1.1.0
    flair 0.4.2 depends on torch>=1.0.0
    flair 0.4.1 depends on torch>=1.0.0
    flair 0.4.0 depends on torch==1.0.0
    flair 0.3.2 depends on torch==0.4.1
    flair 0.3.1 depends on torch==0.4.1
    flair 0.3.0 depends on torch==0.4.1
    flair 0.2.1 depends on torch==0.4.0
    flair 0.1.1 depends on torch==0.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by alanakbik** [comment]
Are you using Python 3.7+ locally?

**Comment by firdovsi9** [comment]
Nope, it is 3.12

**Comment by helpmefindaname** [comment]
Hi @firdovsi9 are there pytorch versions supporting python 3.12 already? I would suppose there aren't, as 3.12 is still in an alpha release

**Comment by firdovsi9** [comment]
Hi @helpmefindaname , I changed it to 3.8 and issues has been resolved. Thanks!
