### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'chunk'

### ISSUE THREAD

**Issue by michaelgoeggelmann** [flairNLP/flair#3186]
### Question

Hi! I can download and use all models as ever, but chunk. The files get downloaded, I can also find them in my .flair folder. But every time I want to load them into Classifier, the error message above appears. Other models like NER are working flawlessly.

I am using a Mac, if I can provide further information, don't hesitate to ask! Thank you in advance.

Any ideas?

**Comment by alanakbik** [comment]
Hello @michaelgoeggelmann thanks for spotting this error. I can reproduce, for 'chunk-fast' as well. 

The issue is that these models are from such an old flair version that they can no longer be loaded. I will push a newer version of these models today and let you know once it is fixed.

**Comment by michaelgoeggelmann** [comment]
That's great! Thank you so much!

**Comment by alanakbik** [comment]
@michaelgoeggelmann should work now! If not, feel free to reopen!
