### ISSUE TITLE
[Question]: How to fix the batch size for aws neuron?

### ISSUE THREAD

**Issue by Kinchkun** [flairNLP/flair#3188]
### Question

Hi,

I try to utilise awe neuron with our flair ner-german-large model. It somewhat works but I get the following error depending on the input text:

```
RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 0
```

I have to admit at this point: I have no clue about machine learning :D I assume this 5 and 4 at dimension 0 are the batch sizes? And the batch sizes are somehow calculated depending on the input? 

I always use `embeddings.force_max_length = True` and I am sure every sentence has always 512 tokens therefore I don't get why there should be different batch sizes.

Can I force flair somehow that it will always use the same batch size?

Note: There are some compiler flags for neuron, like `dynamic_batch_sizes` which won't work either because apparently if activated the output and input tensors must have the same shape which is not the case:

```
ValueError: Dynamic batching was enabled but all compiled batch inputs and outputs did not have the same dim 0 size:
Input #0 shape: [4 512 1024]
Input #1 shape: [4 1 1 512]
Output #0 shape: [25 4 512 1024]
``` 

Kind regards

**Comment by alanakbik** [comment]
Hello @Kinchkun does this error also occur outside of AWS neuron? Can you post a minimal script to reproduce?

**Comment by Kinchkun** [comment]
Hello @alanakbik and thank you,

No, this is very specific of aws neuron, because you compile the original model to a aws neuron model. The aws neuron model can only be used with input tensors with the exact same shape as during compilation.

Therefore I pad the inputs to 512 tokens to have a consistent input size. This is recommended in their documentation:
<img width="624" alt="image" src="https://user-images.githubusercontent.com/8901105/230085508-720ae09a-2b45-4b5b-bc01-53b1cfaa7ce4.png">

But it seems even if i pad the input to 512 the bucket size still differs depending on the text.

I can provide an minimal example, however you will ne a neuron model and a inferentia machine to reproduce. The model will be several GB in size and compilation takes up to 30 hours. I don't think this would be practical?

**Comment by alanakbik** [comment]
Thanks for the info (I haven't worked with neuron yet). I think the issue potentially lies in Flair's handling of long sentences when transformers are used. We essentially split up sentences that are longer than 512 subtokens and do a sliding window to generate embeddings for each word in long sentences. This leads to a larger mini-batch size since long sentences are effectively split into several overlapping sentences. 

To verify, could you try "ner-german" instead of "ner-german-large"? It was just fixed (#3187) so this model should now work with PyTorch 2.0

**Comment by Kinchkun** [comment]
Sure; I will gladly try ner-german and give feedback. Thank you

**Comment by Kinchkun** [comment]
Hi,

I need a little hint for `ner-german`.

I use this approach to trace the model for aws neuron: https://github.com/flairNLP/flair/issues/3021

The following code doesn't work with `ner-german` but with `ner-german-large`:

```
wrapper = JitWrapper(tagger.embeddings)
parameter_names, parameter_list = TransformerJitWordEmbeddings.parameter_to_list(
        tagger.embeddings,
        wrapper,
        sentences)
```

The problem is with `parameter_to_list`: https://github.com/flairNLP/flair/blob/master/flair/embeddings/transformer.py#L875

It has the following line:

```
tensors = embedding.prepare_tensors(sentences)
```

So: In `ner-german-large` this embedding is of TransformerEmbeddings, which has the method `prepare_tensors`. But in `ner-german` the embeddings are of `StackedEmbeddings` which doesn't have `prepare_tensors`.

I though I am clever and iterate over the embeddings within `StackedEmbeddings` and collect the result:

```
 parameter_names = []
 parameter_list = []
 for embedding in embeddings.embeddings:
            pam_names, pam_list = prepare_parameter(wrapper, embedding, sentences)
            parameter_names.extend(pam_names)
            parameter_list.extend(pam_list)
````

However :D StackedEmbeddings has `WordEmbeddings` which also doesn't have the method `prepare_tensors`.

I think I need those tensors at the end of the day from those embeddings. Do you have a hint how I get those?

**Comment by helpmefindaname** [comment]
Hi @Kinchkun 
sorry for the confusion, "ner-german" won't work, as it isn't using transformer embeddings and only those are supported.
You can debug this by creating a tagger with a smaller embedding, for example:
```
embeddings = TransformerWordEmbeddings("prajjwal1/bert-tiny")
embeddings.force_max_length = True
tagger = SequenceTagger(embeddings=embeddings, tag_dictionary=Dictionary(), tag_type="none")

# follow the remaining tutorial
...
```

That way, you are compiling a much smaller model, which hopefully is way faster and therefore makes it easier to debug.
 
The `embeddings.force_max_length = True` is doing the padding part, so I'd expect it to work without manual padding. Also, I don't fully understand how exactly you implemented that. Can you share what you mean by it?

I am sorry, we won't be able to debug this, as we don't have aws access, but if you share the code what exactly you did, we might be able to guess what the problem could be and help you on the debugging part

**Comment by alanakbik** [comment]
@Kinchkun sorry about that, as @helpmefindaname writes, the small models don't use transformers, so they cannot be used for testing. 

To verify whether our way of dealing with long sentences is the problem, you could load the german-large  tagger, but deactivate handling of sentences over 512 tokens: 

```python
# load tagger but disallow long sentences
tagger = SequenceTagger.load("flair/ner-german-large")
tagger.embeddings.allow_long_sentences = False
```

In this case, sentences that are too long will effectively get truncated at maximum length. Does this by chance fix the issue?
