### ISSUE TITLE
[Question]: The string 'O' is not in dictionary! but is set as the zero tag value

### ISSUE THREAD

**Issue by AylaRT** [flairNLP/flair#3190]
### Question

I have IOB-labelled data without unknown labels. The data is straightforward: one token with one label per line. I use the following code for the label dictionary:
```
tag_type = "iob"
label_dictionary = corpus.make_label_dictionary(tag_type, add_unk=False)
```

This works fine and Flair seems to recognise automatically that "O" is meant as the zero tag value. I get the following output when starting: 

`"Dictionary created for label 'io' with 2 values: B (seen 22834 times), I (seen 12292 times)".
`
The output it shows for example sentences also indicates that these are processed as intended.

However, once it starts to actually train the model, I get the following error message:
```
The string 'O' is not in dictionary! Dictionary contains only: ['B', 'I', '<START>', '<STOP>']
You can create a Dictionary that handles unknown items with an <unk>-key by setting add_unk = True in the construction.
```

I'm not sure whether this is a problem in my own code or whether this is an oversight of the Flair code. Does anyone know how I could best resolve this? Thank you!

**Comment by helpmefindaname** [comment]
Hi @AylaRT 
can you show the code how you constructed the corpus? I think the "O" tag should be in your dictionary if you have some tokens with that label.
Besides that, when using flair, you should gave the labels a name, e.g. "B-Mention", "I-Mention", etc.

**Comment by alanakbik** [comment]
Hello @AylaRT the problem likely lies in the way Flair auto-detects whether the corpus is BIO labeled. 

The best fix would be - as @helpmefindaname writes - to replace all "B" labels in your corpus with something like "B-entity" or "B-mention". Similarly for all "I" labels. That should immediately fix the problem. 

A quicker, but suboptimal solution would be to just add "O" to your label dictionary with this code:

```python
tag_type = "iob"
label_dictionary = corpus.make_label_dictionary(tag_type, add_unk=False)

# manually add 'O'
label_dictionary.add_item('O')
```
 
However, in the latter case, the evaluation will not be span-level F1 score as is standard. Instead, the model will think this is not a BIO problem and default to regular token-level F1, skewing the evaluation numbers. So the first solution is preferred.

**Comment by AylaRT** [comment]
Thank you @helpmefindaname and @alanakbik for the informative replies!
We will continue by adding a description to the I and O labels as suggested.

**Comment by AylaRT** [comment]
hi again,
we decided to try both types of evaluation to allow comparison with previous experiments where we had token-level evaluation (not span-level, despite the IOB-tags). We manually added the O-label as suggested, but in the final evaluation report we still only see the scores for the I-label (not for the O-label). If we work this way, should we simply give a different name to our labels to avoid any confusion with the IOB-labels as they are intended? Or can we force an evaluation report that includes O-labels? I remember that this is how I used to get results for a task with only I and O labels:

Results:
- F-score (micro): 0.9021
- F-score (macro): 0.8748
- Accuracy (incl. no class): 0.9021

By class:
              precision    recall  f1-score   support

           O     0.9232    0.9436    0.9333     40232
           I       0.8418    0.7926    0.8164     15235

    accuracy                         0.9021     55467
   macro avg     0.8825    0.8681    0.8748     55467
weighted avg     0.9008    0.9021    0.9012     55467

**Comment by alanakbik** [comment]
Hello @AylaRT, yes the O tag should be interpreted as "no label" by default, so changing the label name would probably address this issue. 

When loading your corpus, you can specify a `label_name_map` so you don't have to change the files themselves. For instance, to load CoNLL-03 and change some label names, do this: 

```python
corpus = CONLL_03(in_memory=True,
                  label_name_map={'PER': 'person',
                                  'LOC': 'location',
                                  'ORG': 'organization',
                                  'MISC': 'other entity'},
                  )
```

So you could pass a `label_name_map={'O': 'no entity'}` or similar to your corpus loading method.

**Comment by AylaRT** [comment]
Thank you very much, again, for the prompt and clear reply!
