### ISSUE TITLE
[Bug]: Broken links, weird link, lack of syntax highlighting

### ISSUE THREAD

**Issue by SolsticeProjekt** [flairNLP/flair#3209]
### Describe the bug

Thought I'd point these out. The fact that there even ARE tutorials here is greatly appreciated, btw.

"This is the entity tagging tutorial. It assumes that you're familiar with the [base types](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_1_BASICS.md) of this library."

It points to a 404, apparently everywhere it's linked.

I guess the actual link should be:
https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_FLAIR_BASICS.md

-----------------------------------------

In https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_TAGGING_LINKING.md

Or learn how to train your own sentiment analysis model in our [text classifier training tutorial]/resources/docs/TUTORIAL_TRAINING_TEXT_CLASSIFIER.md).

-----------------------------------------

https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_12_CLUSTERING.md

The code isn't coloured.

-----------------------------------------

### To Reproduce

```python
lol read your tutorials, I guess. :-)
```

### Expected behavior

... uh ...

### Environment

Your github.

**Comment by alanakbik** [comment]
Hello @SolsticeProjekt thanks for pointing this out. These tutorials are all in fact old and no longer maintained. We don't link them anymore from our project page. 

Now, the Flair docs are at: https://flairnlp.github.io/docs/intro 

Some examples for links to specific entries:
- Flair basics is here: https://flairnlp.github.io/docs/tutorial-basics/basic-types 
- Entity Linking here: https://flairnlp.github.io/docs/tutorial-basics/entity-linking 

I think to best avoid such confusion, I will replace these old tutorials with redirects to our documentation page.
