### ISSUE TITLE
[Question]: Accuracy vs. F-score (micro)

### ISSUE THREAD

**Issue by cjing1** [flairNLP/flair#3215]
### Question

Thank you for the great package. 

I am building text classifications with binary outcomes. I tried different methods including: Document LSTM Embeddings, Stacked Embeddings, Transformer Document Embeddings with different pre-trained language models such as BERT, roberta, distilbert, etc. 

I noticed for all the models I trained, the final model had the same accuracy and F-score (micro) evaluation. 
ex: 
- F-score (micro) 0.8585
- F-score (macro) 0.8535
- Accuracy 0.8585

Is there any reason why this is consistent across different methods? Is the flair package implement some special designs during the training process to achieve this? 

Thank you for any comments.

**Comment by helpmefindaname** [comment]
Hi @cjing1 
this is a result of using binary classification, where micro-F1, macro-F1 and accuracy are the same.
This has nothing to do with Flair, but with the math behind those metrics.

**Comment by cjing1** [comment]
> Hi @cjing1 this is a result of using binary classification, where micro-F1, macro-F1 and accuracy are the same. This has nothing to do with Flair, but with the math behind those metrics.

Thank you for your reply. But I don't think it is right, I did the math calculation. In binary classification, micro-F1 is equal to accuracy only when the true positive is equal to the true negative. However, I don't think that is the case for all binary classification outcomes. So I am wondering whether this is some optimization designed by Flair.

**Comment by cjing1** [comment]
> here

Thank you for sharing the blog, I understand why precision, recall and F-1 score (micro-avg) are the same since "if there is a false positive, there will always also be a false negative and vice versa, because always one class if predicted."  So, FN = FP. 

However, in order to have accuracy equal to F-1 score (micro-avg), we have to have the true positive equal to the true negative. 

Accuracy = (TP+TN)/(TP+TN+FN+FP)
F-1 score (micro-avg) = (2*TP)/(TP+TN+FN+FP)

I noticed there are comments in the blog you shared discussing the same situation but without an explanation.

**Comment by cjing1** [comment]
In addition, I also tried to replicate the accuracy and F-1 score (micro-avg) results by loading the final-model.pt and predicting on test.csv data. But the results are all very different. Any intuition why that is?

**Comment by helpmefindaname** [comment]
@cjing1 
You have 2 class classification, hence we can split this up further to:
TP1, TP2, TN1, TN2, ....
Notice: FN1 = FP2, FN2=FP1, TP1=TN2, TP2=TN1
Therefore TP = TP1 + TP2 = TN2 + TN1 = TN
And FP = FP1 + FP2 = FN2 + FN1 = FN
-> TP = TN & FP = FN

**Comment by cjing1** [comment]
> @cjing1 You have 2 class classification, hence we can split this up further to: TP1, TP2, TN1, TN2, .... Notice: FN1 = FP2, FN2=FP1, TP1=TN2, TP2=TN1 Therefore TP = TP1 + TP2 = TN2 + TN1 = TN And FP = FP1 + FP2 = FN2 + FN1 = FN -> TP = TN & FP = FN

If you split it up by class, you are actually calculating the macro F1 score.
