### ISSUE TITLE
[Question]: How to load the model faster? 

### ISSUE THREAD

**Issue by similang** [flairNLP/flair#3234]
### Question

I am using NER model (ner-ontonotes-large) to do NER or text classification on pandas column. Prediction part is alright but not the model loading part. On a PC with 64GB ram, it will take more than 15s just to load a model. Is there a way to reduce the timing? 

Here's the script for your preview: 

```
from transformers import pipeline, set_seed
from flair.data import Sentence
from flair.models import SequenceTagger

tagger = SequenceTagger.load('ner-ontonotes-large')

def get_entities(text):
    sentence = Sentence(text)
    tagger.predict(sentence)
    return sentence.get_spans('ner')
```

**Comment by helpmefindaname** [comment]
Hi @similang 
I figured out the following observations:

* the `ner-ontonotes-large` model uploaded in the hub is in the old format, where the embedding classes are stored directly using pickle. You can speed up the loading by simply saving the model locally (and therefore update the format, which just recreates the embeddings and apparently is faster.
* apparently the initialization of the layers takes quite some time and the initialization is unnecessary, as the parameters get overwritten with the saved parameters anyway. For transformer embeddings (like the ner-ontonotes-large uses), you can simply use the `transformers.modeling_utils.no_init_weights` context manager to get some speedup.
* even further, you could try to stop pytorch from initializing layers at all. (They still call initialization once for each parameter besides the transformer no_init_weights). However, this requires a hack and I wouldn't recommend it in any production environment.

I cannot assure you on the exact times as it might be different on different devices, but you can check it yourself using the following code:
```
import logging
import timeit

from flair.models import SequenceTagger

n = 5

logging.disable()

tagger = SequenceTagger.load("ner-ontonotes-large")
tagger.save("ontonotes.pt")

print(
    "loading ontonotes-plain:",
    timeit.timeit(
        "tagger = SequenceTagger.load('ner-ontonotes-large')", setup="from flair.models import SequenceTagger", number=n
    ) / n,
)


print(
    "loading ontonotes-converted:",
    timeit.timeit(
        "tagger = SequenceTagger.load('ontonotes.pt')", setup="from flair.models import SequenceTagger", number=n
    ) / n,
)

print(
    "loading ontonotes-no-init:",
    timeit.timeit(
        """
with no_init_weights():
    tagger = SequenceTagger.load('ner-ontonotes-large')
""",
        setup="from flair.models import SequenceTagger; from transformers.modeling_utils import no_init_weights",
        number=n,
    ) / n,
)

print(
    "loading ontonotes-converted-no-init:",
    timeit.timeit(
        """
with no_init_weights():
    tagger = SequenceTagger.load('ontonotes.pt')
""",
        setup="from flair.models import SequenceTagger; from transformers.modeling_utils import no_init_weights",
        number=n,
    ) / n,
)


print(
    "loading ontonotes-converted-no-init-torch-overwrite:",
    timeit.timeit(
        """
with no_init_weights():
    tagger = SequenceTagger.load('ontonotes.pt')
""",
        setup="""
from flair.models import SequenceTagger
from transformers.modeling_utils import no_init_weights
from torch import nn

class NonInitLinear(nn.Linear):
    def reset_parameters(self):
        pass

nn.Linear = NonInitLinear

class NonInitEmbedding(nn.Embedding):
    def reset_parameters(self):
        pass

nn.Embedding = NonInitEmbedding

""",
        number=n,
    ) / n,
)
```

running the script on my laptop gives the following output:
````
loading ontonotes-plain: 15.089217940000003
loading ontonotes-converted: 11.39636132
loading ontonotes-no-init: 9.149429759999999
loading ontonotes-converted-no-init: 7.096097199999997
loading ontonotes-converted-no-init-torch-overwrite: 3.9645593200000007
```

**Comment by similang** [comment]
Will this impact the prediction?

**Comment by similang** [comment]
@helpmefindaname 

Quick one: so within production environment, which one is the most recommended one?

**Comment by helpmefindaname** [comment]
I just don't recommend hacking the torch library in the prod environment, everything else is fine.

Actually, I would always recommend you to save the model locally and not use urls to models in prod, as this leads to the necessity of the model being downloaded to cache and the application possibly not working anymore if the model is updated and not compatible anymore.

I don't understand what you mean with "model in transformer"? There is a transformer as part of the model, not the other way around?
For compression, you can look into the [ONNX Tutorial](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_PRODUCTION_FASTER_TRANSFORMERS.md#transformeronnxembeddings)

**Comment by similang** [comment]
Ignore my 2nd question. I thinking huggingface has internal staffs to convert pre-trained models into huggingface style transformer models;

On the saved model - something is not right: 

![image](https://user-images.githubusercontent.com/7208012/236661952-6f839494-d5d4-4bf0-b16e-126214331c1b.png)

The loading part - it will attempt to re-download the model again?

**Comment by similang** [comment]
@helpmefindaname do let me know on the above - I think is some kind of bug.

**Comment by helpmefindaname** [comment]
I cannot reproduce your screenshot, if you think there is a bug please create a minimal reproducible example.

**Comment by similang** [comment]
> I cannot reproduce your screenshot, if you think there is a bug please create a minimal reproducible example.

I am just doing this (load the model and save locally). Problem is when loading my local model it attempts the re-download again: 

```
from transformers import pipeline, set_seed
from flair.data import Sentence
from flair.models import SequenceTagger

loc = local_dir
tagger = SequenceTagger.load("ner-ontonotes-large")
tagger.save("local_ontonotes.pt")
tagger = SequenceTagger.load(os.path.join(loc, 'local_ontonotes.pt'))
```

flair version I am using - 0.12.2

**Comment by helpmefindaname** [comment]
I don't think the error `NameError: name 'local_dir' is not defined` that you get when running that script is related to flair.
Please notice that I asked for a *reproducible* example, If I just do a similar script by removing everything that I think is wrong, I get a working solution.

**Comment by similang** [comment]
@helpmefindaname any thoughts on the above?

**Comment by similang** [comment]
@helpmefindaname  any help or tips?

**Comment by helpmefindaname** [comment]
I think you should focus on creating a minimal reproducible example that is actually reproducible. Like showing that you actually try to load from a path that exists and not running into the logic of not finding the path.

As long as there is no such example, I don't see how I can help you

**Comment by similang** [comment]
![image](https://github.com/flairNLP/flair/assets/7208012/1e6fec50-ca81-4653-a16b-4085aca5d5cc)

```
import logging
import timeit
import os

# from transformers import pipeline, set_seed
from flair.data import Sentence
from flair.models import SequenceTagger

import flair
flair.__version__
loc = r"D:\1_Data_Programming\Codes\\"

path = loc + 'local_ontonotes.pt'

print(os.path.exists(path))
```

tagger = SequenceTagger.load(path)


> I think you should focus on creating a minimal reproducible example that is actually reproducible. Like showing that you actually try to load from a path that exists and not running into the logic of not finding the path.
> 
> As long as there is no such example, I don't see how I can help you

Is this good enough - I am not sure what could be done already. Basically, it's just code you used above, to load the model that has been stored in .pt format.

**Comment by helpmefindaname** [comment]
Okay, I see now, this is a bug that is already fixed on master. 
I thought the bugfix is already released, I will see if we can release that soon.

To give some understanding, what happens:
the model is not downloaded again, but the transformer embeddings are. The embedding weights will then be discarded in favor of the model weights and therefore is totally unnecessary.
You can resolve this by either installing the master branch or to just download the `xlm-roberta-large` model once into cache.

**Comment by similang** [comment]
May I know which branch release was mained for resolving this? Maybe I just edit the scripts so I don't need to change things in the front end for now. Thanks!

**Comment by helpmefindaname** [comment]
https://github.com/flairNLP/flair/pull/3178 and https://github.com/flairNLP/flair/pull/3229 should do it

**Comment by similang** [comment]
> just download the `xlm-roberta-large` model once into cache.

Which cache are you referring this to?
