### ISSUE TITLE
[Question]: Uploading flair models in Elasticsearch

### ISSUE THREAD

**Issue by EzicJ** [flairNLP/flair#3235]
### Question

Hello,

I encountered a problem while trying to upload `flair/ner-german-large` in an Elasticsearch cluster. 

After following these instructions

[https://www.elastic.co/guide/en/elasticsearch/client/eland/current/machine-learning.html#ml-nlp-pytorch](instructions), 

the flair model is unable to be loaded by TransformerModel with the following error message:

```
OSError: flair/ner-german-large does not appear to have a file named config.json
```

Is there a possible workaround or a quick way for me to generate the config.json file and save it as a new model locally?

Thanks!

**Comment by helpmefindaname** [comment]
Hi @EzicJ 

reading their documentation, they say that they suppot transformers models, but didn't say anything about flair models. So I don't think they support it. 

If you want it to be supported, you shoud propably ask on [their issue page](https://github.com/elastic/elasticsearch/issues). And see if they will integrate it
