### ISSUE TITLE
[Question]: How to programmatically get the NER of a word?

### ISSUE THREAD

**Issue by AngledLuffa** [flairNLP/flair#3261]
### Question

In the sample NER, you suggest doing the following:

```
# make example sentence
# use_tokenizer means split on whitespace?
sentence = Sentence("George Washington went to Washington", use_tokenizer=False)

# predict NER tags
tagger.predict(sentence)

# print sentence
print(sentence)
```

Is there a good way to get the NER of a specific word, such as the first word, `George`?  The closest I can figure out is to look at the spans and their `tokens`, which have an `idx` field.  Still, it would be much easier to look at the members sentence, say `sentence[0]`, and somehow get the NER off it... `sentence[0].ner` does not exist, though

Thanks!

**Comment by AngledLuffa** [comment]
This is a `flair.data.Label`:

```
sentence[0].get_label('ner')
```

but it doesn't actually have anything on it

This is also a Label:

```
entity = sentence.get_spans('ner')[0]
entity.get_label('ner')
label.value    # this is PER
entity.tokens[0].idx    # this is 1, representing George, index in the array + 1
```

I think the NER documentation would benefit from an example of how to access it programmatically, and if there's an easier way, it would be good to hear about it.  Thanks!

**Comment by helpmefindaname** [comment]
Hi @AngledLuffa ,
we are currently restructuring our docs and try to set them up in a more complete way soon.
However in the specific case, you have the answer to your question documented [here](https://flairnlp.github.io/docs/tutorial-basics/how-predictions-work#getting-the-predictions)

**Comment by AngledLuffa** [comment]
Thanks!  That is definitely helpful.  Might also be worthwhile to mention
how to get the start and end indices of the words which were labeled.

**Comment by nikhilcms** [comment]
Hi,

Can you pls provide a solution how to get actual start and end indices such that using this indices I can extract detected entity like spacy ner model provides ?
