### ISSUE TITLE
[Question]: What transformer does ner-large use?

### ISSUE THREAD

**Issue by AngledLuffa** [flairNLP/flair#3262]
### Question

We are writing a paper about NER (saying nothing but nice things about Flair) and would like to be precise in our explanation of `ner` vs `ner-large`.  Which transformer architecture (or existing transformer model) does `ner-large` use?

Thanks!

**Comment by helpmefindaname** [comment]
Hi @AngledLuffa 

`ner` corresponds to the model from [Contextual String Embeddings for SequenceLabeling - ACL Anthology](https://aclanthology.org/C18-1139/), you can see the training script at [their modelcard](https://huggingface.co/flair/ner-english).
`ner-large` corresponds to the model from [FLERT: Document-Level Features for Named Entity Recognition](https://arxiv.org/abs/2011.06993), you can see the training script at [their modelcard](https://huggingface.co/flair/ner-english-large).

**Comment by AngledLuffa** [comment]
Perfect, thanks!
