### ISSUE TITLE
[Question]: sentence.to_dict(tag_type='ner') no longer have the 'entities' key 

### ISSUE THREAD

**Issue by javinator48** [flairNLP/flair#3265]
### Question

Currently I run the example shown here in a previous issues question. However I am unable to get the correct format for the sentence.to_dict(tag_type='ner') output. Currently I am expecting there to be an entities key but my out put doesn't have the key. I was wondering if there is a flag I have to set when calling the to_dict function. Why isn't it working the same as before? 
<img width="733" alt="Screen Shot 2023-06-13 at 3 01 39 PM" src="https://github.com/flairNLP/flair/assets/46199601/a0c69a2c-f96a-4abc-a6c0-1c2dbd947380">

<img width="1439" alt="Screen Shot 2023-06-13 at 3 04 50 PM" src="https://github.com/flairNLP/flair/assets/46199601/c67710a1-9f91-4a90-8aef-259fc90c0c8b">

**Comment by helpmefindaname** [comment]
Hi @javinator48 can you check if https://github.com/flairNLP/flair/pull/3271 fixes your issue?

**Comment by javinator48** [comment]
Hi @helpmefindaname , can you please explain how that is supposed to help me? Currently I am installing the package using `pip install flair`. However, the version installed is the latest version 0.12.2 which was from March 30, 2023. #3271 shows that you updated your code in the sentence.to_dict function to return the entities key as well. That is what I needed. 
Can you please explain what I should do at the moment to solve the issue? Currently I checked pypi and your code doesn't seem to be updated there.

**Comment by javinator48** [comment]
Thanks for the help. I managed to solve my issue by using the flair0.10 pip install flair==0.10.

**Comment by helpmefindaname** [comment]
> Hi @helpmefindaname , can you please explain a little bit more about what I should do now? Currently I am installing the package using `pip install flair`. However, the version installed is the latest version 0.12.2 which was from March 30, 2023. #3271 shows that you updated your code in the sentence.to_dict function to return the entities key as well. That is what I needed. I think #3271 should solve my issue. Can you please explain what I should do at the moment to solve the issue? Currently I checked PyPi and your code doesn't seem to be updated there. I see that you reverted some changes to the sentence.to_dict function. Do you know what was the pypi package version when you updated the sentence.to_dict function to not have the 'entities' key in the return?

I am asking you to pip install the branch, instead of the pypi repo. e.g. running `pip install git+https://github.com/flairNLP/flair.git@3265-question-sentenceto_dicttag_type=ner-no-longer-have-the-entities-key` and then try the code again
