### ISSUE TITLE
[Question]: Create Single-Label TARS Classifier with Multi-Label Dataset

### ISSUE THREAD

**Issue by Luciore95** [flairNLP/flair#3278]
### Question

Hi,

i am currently working on my masters thesis where the TARS model is the topic. I have a dataset containing "labels" and "text". Labels describe what the text is about eg. "machine learning", "collaboration" etc. I want to create TARS-models that predict only one of those labels, so that there is one model for each label in the dataset. 

i already implemented a working multi-label model, where all labels get predicted at once, but i struggle to create a single-label one. 
**my first approach**: i create a FlairDataPointSet where each label gets the same label_type resulting in following dictionary:

`Dictionary created for label 'slc_classes' with 10 values: labelX(seen 20 times), labelY(seen 13 times),  .... `

but with that, i dont know how to train a model that only predicts labelX. I would like to pass just one value  to the trainer, so that the model trains to give labelX to a sentence or not. 

**My second aproach:** if i create a FlairDataPointSet where each label gets its own label_type, i get the following, when creating a label_dict with only the label_type of the label i want to predict:

`Dictionary created for label 'labelX' with 2 values: labelX(seen 20 times)`
but if i then initialize the trainer with this, i get 

`ValueError: Sample larger than population or is negative`

how can i create a model that only predicts one of those values? My goal is to have one classifier for labelX, one for labelY and so on, because i want to compare single label TARS models to multi label models. 

I am to thankful for everyone trying to help me with this problem. Let me know if you need additional information.

**Comment by helpmefindaname** [comment]
Hi @Luciore95 
I think your aproach with 1 class per label_type is correct. however you then need to pass `num_negative_labels_to_sample=1` to the TARSClassifier, as otherwise it tries to sample more labels than exist

**Comment by Luciore95** [comment]
Hey @helpmefindaname,

thank you for your reply! The solution was indeed setting the `num_negative_labels_to_sample=1 or None`. I found this in the sourcecode the other day, gave it a go and it worked. Thanks for validating my approach, as i was not sure if i was doing the right thing with this parameter and the label_dictionary. 

Now im back on track, as i can create the single label classifiers (already tested!) 
Thanks again for your time.
