### ISSUE TITLE
[Question]: Error(s) in loading state_dict for TextClassifier

### ISSUE THREAD

**Issue by nowhash** [flairNLP/flair#3290]
### Question

Whenever I try to load the previously saved model encountered the following error:

```
RuntimeError: Error(s) in loading state_dict for TextClassifier:
	Unexpected key(s) in state_dict: "embeddings.embeddings.list_embedding_0.list_embedding_0.model.embeddings.position_ids", "embeddings.embeddings.list_embedding_0.list_embedding_1.model.embeddings.position_ids". 
```
How to solve the issue?

**Comment by mct-lrh** [comment]
Hey @nowhash , how did you resolve this?

**Comment by nowhash** [comment]
> Hey @nowhash , how did you resolve this?

So far I understand, the reason for getting this error is that I saved the model using flair 0.12. Later I tried to load the model using the updated flair version 0.12.2. To resolve this issue, I've installed Flair version 0.12 instead of the latest one.

**Comment by helpmefindaname** [comment]
For any future readers: this bug is handled here: https://github.com/flairNLP/flair/issues/3284
