### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by alexandraz2022** [flairNLP/flair#3299]
### Question

I am using flair 0.12.2 in a Windows 10 Pro machine and I have created a notebook on jupyter with python 3.11.3. My goal is to recognize entities in a Spanish corpus; I am trying to use the model flair/ner-spanish-large and I got this error:

RuntimeError: Error(s) in loading state_dict for XLMRobertaModel:
Unexpected key(s) in state_dict: "embeddings.position_ids". 

The complete trace is as follows:

_**RuntimeError                              Traceback (most recent call last)
Cell In[8], line 1
----> 1 tagger = SequenceTagger.load("flair/ner-spanish-large")

File C:\ProgramData\anaconda3\Lib\site-packages\flair\models\sequence_tagger_model.py:1035, in SequenceTagger.load(cls, model_path)
   1031 @classmethod
   1032 def load(cls, model_path: Union[str, Path, Dict[str, Any]]) -> "SequenceTagger":
   1033     from typing import cast
-> 1035     return cast("SequenceTagger", super().load(model_path=model_path))

File C:\ProgramData\anaconda3\Lib\site-packages\flair\nn\model.py:559, in Classifier.load(cls, model_path)
    555 @classmethod
    556 def load(cls, model_path: Union[str, Path, Dict[str, Any]]) -> "Classifier":
    557     from typing import cast
--> 559     return cast("Classifier", super().load(model_path=model_path))

File C:\ProgramData\anaconda3\Lib\site-packages\flair\nn\model.py:191, in Model.load(cls, model_path)
    189 if not isinstance(model_path, dict):
    190     model_file = cls._fetch_model(str(model_path))
--> 191     state = load_torch_state(model_file)
    192 else:
    193     state = model_path

File C:\ProgramData\anaconda3\Lib\site-packages\flair\file_utils.py:359, in load_torch_state(model_file)
    355 # load_big_file is a workaround byhttps://github.com/highway11git
    356 # to load models on some Mac/Windows setups
    357 # see https://github.com/zalandoresearch/flair/issues/351
    358 f = load_big_file(model_file)
--> 359 return torch.load(f, map_location="cpu")

File ~\AppData\Roaming\Python\Python311\site-packages\torch\serialization.py:809, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807             except RuntimeError as e:
    808                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810 if weights_only:
    811     try:

File ~\AppData\Roaming\Python\Python311\site-packages\torch\serialization.py:1172, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171 unpickler.persistent_load = persistent_load
-> 1172 result = unpickler.load()
   1174 torch._utils._validate_loaded_sparse_tensors()
   1176 return result

File C:\ProgramData\anaconda3\Lib\site-packages\flair\embeddings\transformer.py:1169, in TransformerEmbeddings.__setstate__(self, state)
   1166     self.__dict__[key] = embedding.__dict__[key]
   1168 if model_state_dict:
-> 1169     self.model.load_state_dict(model_state_dict)

File ~\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py:2041, in Module.load_state_dict(self, state_dict, strict)
   2036         error_msgs.insert(
   2037             0, 'Missing key(s) in state_dict: {}. '.format(
   2038                 ', '.join('"{}"'.format(k) for k in missing_keys)))
   2040 if len(error_msgs) > 0:
-> 2041     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
   2042                        self.__class__.__name__, "\n\t".join(error_msgs)))
   2043 return _IncompatibleKeys(missing_keys, unexpected_keys)

RuntimeError: Error(s) in loading state_dict for XLMRobertaModel:
	Unexpected key(s) in state_dict: "embeddings.position_ids".**_ 

Could you help me with this? Thanks

**Comment by helpmefindaname** [comment]
Hi @alexandraz2022 
you can find details about the bug (and how to solve it) here: https://github.com/flairNLP/flair/issues/3284
