### ISSUE TITLE
[Bug]: ColumnCorpus class is not properly loading conll format file

### ISSUE THREAD

**Issue by pjdrm-unbabel** [flairNLP/flair#3306]
### Describe the bug

Eg file:
```
Test	O

Load	O

Data	O

To	O

Corpus	O

Hi	O
John	NAME
```

Checking the "Johh" token in the 6th sentence the label is wrong, shows as "ME" instead of "NAME". Also, when checking the dictionary returned by `corpus.make_tag_dictionary` neither "ME" or "NAME" show up. When training a NER model with this corpus it only outputs the "O" tag as well.

### To Reproduce

```python
Instantiating as follows:

ColumnCorpus(
        corpus_dir,
        {0: 'text', 1: 'ner'},
        dev_file='dev.txt',
        train_file='train.txt',
        test_file='test.txt',
    )

Checking the tag dictionary as follows:

tag_dictionary = corpus.make_tag_dictionary(tag_type='ner')
```

### Expected behavior

- Token "John" should have the "NAME" label
- "NAME" label should appear in the tag dictionary

### Screenshots

![image](https://github.com/flairNLP/flair/assets/103999498/25e03ca4-628f-4108-92b3-ac98b79a1e69)
![image](https://github.com/flairNLP/flair/assets/103999498/3730eb87-6c62-43a3-a0d1-1601918c5f2b)

### Additional Context

Weirdly some simple changes make things work:

- Adding a sentence with any label other than "O" to the begin of the file.
- Removing any of the first sentences.

##### Flair
0.12.2
##### Pytorch
2.0.0
##### Transformers
4.26.0
#### GPU
False

**Comment by helpmefindaname** [comment]
Hi @pjdrm-unbabel 
as your labeling contains the `O` tag, it assumes that your data ist either labeled in the `BIO` or the `BIOES` format. Hence you'll get the label `Name` for the span, if you use `B-Name` or `S-Name` for the label of the token.
