### ISSUE TITLE
[Question]: Fail to install allennlp=0.9.0

### ISSUE THREAD

**Issue by nothingisfine** [flairNLP/flair#3307]
### Question

When I install allennlp without defining the version, elmo embedding does not work.
But when I install with allennlp 0.9.0 it cannot install successful in colab. 

Collecting spacy<2.2,>=2.1.0 (from allennlp==0.9.0)
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

**Comment by helpmefindaname** [comment]
Hi @nothingisfine 
If you would go to the [allennlp github](https://github.com/allenai/allennlp) and ask the question about them there, you would notice, that the project is archived and no longer supported. Hence the only solution is to not use elmo anymore
