### ISSUE TITLE
[Question]: i need only tag_dictionary for specific categories like PERSON,LOG,ORG

### ISSUE THREAD

**Issue by NandhakumarSL** [flairNLP/flair#3310]
### Question

because i'm using flair/ner-english-ontonotes-large model it's long time to process data that's why i need specific categories it will get fast process predict specific categories . 
it is possible or not 
give me answer .because i'm using 4 GB graphic not use full for this one

**Comment by helpmefindaname** [comment]
Hi @NandhakumarSL 

you can always ignore the entities that you don't need, however reducing entities won't really speed up the predictions.
It might be more usefull for you to use `flair/ner-english-ontonotes` (without -large) instead.
