### ISSUE TITLE
[Question]: is there any best pre trained model which can detect any location correctly 

### ISSUE THREAD

**Issue by sauravsinhaa** [flairNLP/flair#3341]
### Question

is there any best pre trained model which can detect any location correctly 
Thanks in advance

i am using
tagger = SequenceTagger.load("ner-fast")

**Comment by alanakbik** [comment]
Hello @sauravsinhaa - you could try our "ner-large" and "ner-ontonotes-large" models. They should be best for locations.

**Comment by sauravsinhaa** [comment]
Thank you for your reply
