### ISSUE TITLE
[Bug]: pip install flair causes UnicodeDecodeError

### ISSUE THREAD

**Issue by joshbrook** [flairNLP/flair#3344]
### Describe the bug

Using pip to install flair with Python 3.12 returns UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6173: character maps to <undefined>
Maybe its an issue with one of Flair's dependencies?

### To Reproduce

```python
!pip install flair
```

### Expected behavior

Flair should be installed

### Screenshots

![image](https://github.com/flairNLP/flair/assets/99391075/533c24e1-bdd1-4f9e-85cc-9e390dbcfd45)

### Environment

n/a, cannot install

**Comment by helpmefindaname** [comment]
Hi @joshbrook 
as torch is not compatible with python 3.12 yet, it is also not possible to install flair.
If you downgrade to python 3.11, it should work fine.
