### ISSUE TITLE
[Feature]: Add support for MobIE NER Dataset

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#3348]
### Problem statement

Hey,

in my latest [blog post](https://huggingface.co/blog/stefan-it/autotrain-flair-mobie) I used the MobIE NER Dataset to show how to fine-tune models with Flair.

I wrote a custom dataset loader for the MobIE NER Dataset:

The German MobIE Dataset was introduced in the [MobIE](https://aclanthology.org/2021.konvens-1.22/) paper by Hennig, Truong and Gabryszak (2021).

It's a German-language dataset that has been human-annotated with 20 coarse- and fine-grained entity types, and it includes entity linking information for geographically linkable entities. The dataset comprises 3,232 social media texts and traffic reports, totaling 91K tokens, with 20.5K annotated entities, of which 13.1K are linked to a knowledge base. In total, 20 different named entities are annotated.

### Solution

Add MobIE support into Flair directly - example class:

https://github.com/stefan-it/autotrain-flair-mobie/blob/main/mobie_dataset.py

It also has some unit tests:

https://github.com/stefan-it/autotrain-flair-mobie/blob/main/script.py#L11-L19

**Comment by alanakbik** [comment]
Closed in #3351 - thanks @stefan-it!
