### ISSUE TITLE
[Question]: FLAIR NER English works in Airgaped environment, However NER English Large doesn't

### ISSUE THREAD

**Issue by alexge233** [flairNLP/flair#3362]
### Question

For reasons I can't go into, I'm using FLAIR in an air gapped environment.
I've downloaded and manually set and loaded the `flair/ner-english` model by pointing the `Classifier.load(arg)` to the `pytorch_model.bin`. 

I want to try the larger version, since the smaller model still makes some errors. I've downloaded `flair/ner-english-large` and placed it in another directory, and pointed `Classifier.load(arg)` to that path.

However, I now get an error indicating that the code is trying to access `get_from_cache` and `get_file_from_repo` even though the model file is there. Am I missing some other config file? I can't see anything else on the huggingface repo.

**Comment by helpmefindaname** [comment]
Hi @alexge233 
can you test if this is still the case on the newly released [flair 0.13.0](https://pypi.org/project/flair/)?
And if it does, can you please add a propper bug report, including logs and stack traces using respective issue template?

**Comment by alexge233** [comment]
@helpmefindaname I just tried with version 0.13.0 and I've ended up with a similar error.
I cannot copy paste it, but I can describe where it originates from:

The code tries to download `/xlm-roberta-large/resolve/main/config.json` from huggingface.co (and clearly fails because this is an airgapped environment so there's no internet connections).

It seems to originate from `metadata = get_hf_file_metadata()` from `hf_hub_download` and basically it cascades from:

`flair/nn/model.py` line 555
`flair/nn/model.py` line 153
`flair/file_utils.py` line 352

I will try to debug locally before trying again in the isolated environment.
I suspect the file I have doesn't pass the if-else statements, and `AutoTokenizer.from_pretrained` is triggered.
If I understand this correctly, the `ner-english-large` is using another Tokenizer?

**Comment by helpmefindaname** [comment]
Hi @alexge233 

Looks like the ner-large model is still in an older format, that used to redownload the embeddings before using them.
You should be able to convert it to a new format in an environment that has internet by running:
```python
from flair.models import SequenceTagger
model = SequenceTagger.load("ner-large")
model.save("local_model.pt")
```
Then running `Classifier.load("local_model.pt")` should work without internet.

**Comment by alexge233** [comment]
Thanks a lot @helpmefindaname  this worked.
