### ISSUE TITLE
torch 1.0.0 and the GLIBC_2.14 in flair installation

### ISSUE THREAD

**Issue by nooralahzadeh** [flairNLP/flair#337]
**Describe the bug**
Since torch 1.0.0 in the system which has GLIBC <2.14 should be installed from the source and in Flair 0.4.4 installation it try to reinstall torch 1.0.0. 
It causes problem for the system which has GLIBC <2.14.
what is your advice? install from the source ?

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: LINUX CUDA 9
 - Version [e.g. flair-0.3.2]: flair 0.4.0

**Comment by alanakbik** [comment]
hi @nooralahzadeh - does this problem also occur if you install flair in a new virtual environment?

**Comment by nooralahzadeh** [comment]
I installed flair from source by excluding the torch reinstallation from setup.py!

**Comment by tabergma** [comment]
@nooralahzadeh Is it working for you? We recommend to install flair in a new virtual environment. Did you try that?

**Comment by Zoher15** [comment]
I have the same issue. I installed it in my work conda environment

**Comment by Zoher15** [comment]
I even created a new virtual environment with just flair. Still did not work

**Comment by alanakbik** [comment]
Hi @Zoher15 @nooralahzadeh did you manage to resolve these issues?

**Comment by Zoher15** [comment]
Hi @alanakbik nope I could not resolve this issue
