### ISSUE TITLE
[Question]: Difference Between `train` and `fine_tune` Methods in `ModelTrainer`

### ISSUE THREAD

**Issue by AAnirudh07** [flairNLP/flair#3377]
### Question

I noticed the [documentation](https://github.com/flairNLP/flair/blob/master/docs/tutorial/tutorial-training/train-vs-fine-tune.md) on the difference between the ModelTrainer's train() and fine_tune() methods is empty. Based on this [example](https://github.com/flairNLP/flair/blob/master/docs/tutorial/tutorial-training/how-to-train-sequence-tagger.md), it seems like train() is for FLAIR embeddings, and fine_tune() is for Transformer embeddings. Is this the only distinction, or are there other differences? Any insights would be much appreciated!

**Comment by helpmefindaname** [comment]
Hi @AAnirudh07 
exactly, the only difference is the set of default parameters. Train is usually used for a feature extraction method, where you have a frozen weight and some LSTM layers afterwards while fine_tune is used for fine_tuning the whole embeddings, (e.g. using transformers with finetune=True

**Comment by AAnirudh07** [comment]
Gotcha, thank you! I'll go ahead and close this issue now.
