### ISSUE TITLE
[Question]: Semantic Role Labelling Usage Instruction

### ISSUE THREAD

**Issue by Wapiti08** [flairNLP/flair#3399]
### Question

Dear authors,

I have checked the document regarding tutorial. I did not find any specific instructions on usage of SRL. But I found this tool has SRL as one of the labels. Please let me know where i can find instructions on that.

Thanks and kind regards

**Comment by alanakbik** [comment]
Hello @Wapiti08, the frame detection is part of the tutorial: https://flairnlp.github.io/docs/tutorial-basics/other-models#semantic-frame-detection 

Hope this helps! Closing this issue, but feel free to reopen if you have more questions.
