### ISSUE TITLE
[Bug]: Sentence.get_token() incorrectly returning None

### ISSUE THREAD

**Issue by SamSJackson** [flairNLP/flair#3407]
### Describe the bug

Sentence class contains method ```get_token```. 
The method ```get_token``` takes an integer argument and is intended to return the token corresponding to the integer.

For a sentence that contains at least one token, get_token(0) will still return None.
Similarly, for a token which is a member of a sentence, calling get_head() will return None.

### To Reproduce

```python
from flair.data import Sentence, Token

sentence = Sentence("I love Berlin.")

# Clearly shows that token at ID 0 exists.
for token in sentence:
    print(token)
    
# Assertion will fail 
assert type(sentence.get_token(0)) == Token, "Sentence not returning token for valid argument."
```

### Expected behavior

sentence.get_token(0) should return a Token. In this particular case, I would expect to get a token of "I".

##### Flair
0.13.1
##### Pytorch
2.1.1
##### Transformers
4.38.0.dev0
#### GPU
True

**Comment by helpmefindaname** [comment]
Hi @SamSJackson 

`sentence.get_token(0)` won't return a token as there is no token with idx 0. printing `[token.idx for token in sentence]` shows you the actual ids.

I suppose you are looking for list indexing, which you can do in the more pythonic way: `sentence[0]` to get the first token, no mather what index it got asigned.

**Comment by SamSJackson** [comment]
Apologies, I think I was misleading myself.

Why do the tokens have a number assigned to them?
Why does ```idx``` not correspond to the actual index? 
(John is Token[0] in the image below)

![image](https://github.com/flairNLP/flair/assets/86316114/b0f5b401-7f32-4bff-a357-45f8cdbfb612)
