### ISSUE TITLE
[Question]: Status of zappr integration

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#3427]
### Question

Hey,

zappr is an agent that enforces guidelines for your GitHub repositories. It was first added in #487.

At the moment, it seems that the connection with zappr is not working, e.g. #3423 has green CI and is approved, but the zappr status is:

![image](https://github.com/flairNLP/flair/assets/20651387/2a6ae16b-1879-44d9-b24a-7582cca2c63c)

-> `Expected — Waiting for status to be reported`

Maybe a new authorization is needed to get zappr working again :thinking:

**Comment by alanakbik** [comment]
Thanks for reminding us! We stopped using it a while a ago, so I guess the tool could be removed.

**Comment by helpmefindaname** [comment]
Hi @stefan-it 
thank you for pointing this out,
not only is zappr not working, but also everything it is supposed to do in this repo can be configured in github directly,
so we switched to the gh implementation.
https://github.com/flairNLP/flair/pull/3435 is here to cleanup the final artefacts.
