### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pritmanvar** [flairNLP/flair#3436]
### Describe the bug

I am trying to load flair embeddings and I keep getting the following error:

OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings/glove.gensim.vectors.npy with status code 301.

The status code indicates a permanent redirect.

I am working with google colab, so there is no network issues that I can think of.

The code that produces this issue for me :
```
embedding_types = [
    WordEmbeddings('glove'),
    FlairEmbeddings('news-forward'),
    FlairEmbeddings('news-backward'),
]
```

![image](https://github.com/flairNLP/flair/assets/77919675/0030949a-70aa-4d3d-8272-a2fcf26b0074)

But this doesn't work and throws the error, and I get similar errors for all the different embeddings.

Environment:
OS : linux (google colab)
Python: 3.10.12
Flair: 0.13.1 (have to use this version)

### To Reproduce

```python
import flair
from flair.embeddings import WordEmbeddings, StackedEmbeddings, FlairEmbeddings
embedding_types = [
    WordEmbeddings('en-glove'),
    FlairEmbeddings('news-forward'),
    FlairEmbeddings('news-backward'),
]
```

### Expected behavior

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-29-ba0a038daea3>](https://localhost:8080/#) in <cell line: 3>()
      1 from flair.embeddings import WordEmbeddings, StackedEmbeddings, FlairEmbeddings
      2 embedding_types = [
----> 3     WordEmbeddings('en-glove'),
      4     FlairEmbeddings('news-forward'),
      5     FlairEmbeddings('news-backward'),

3 frames
[/usr/local/lib/python3.10/dist-packages/flair/file_utils.py](https://localhost:8080/#) in get_from_cache(url, cache_dir)
    210     response = requests.head(url, headers={"User-Agent": "Flair"}, allow_redirects=True)
    211     if response.status_code != 200:
--> 212         raise OSError(f"HEAD request failed for url {url} with status code {response.status_code}.")
    213 
    214     # add ETag to filename if it exists

OSError: HEAD request failed for url https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy with status code 503.

### Screenshots

![image](https://github.com/flairNLP/flair/assets/77919675/84fa3972-1b74-4473-9993-d04cb25d3870)

##### Flair
0.13.1
##### Pytorch
2.2.1+cu121
##### Transformers
4.39.2
#### GPU
True

**Comment by alanakbik** [comment]
Hello @pritmanvar, the embeddings haven't been hosted on Amazon for many years. Are you sure you are using a current Flair version? 

I've tried the above code snippet and it is working for me.

**Comment by pritmanvar** [comment]
Hello @alanakbik , 
I have again tried the same code snippet and now it is working perfectly but yes I was using flair version 0.13.1
