### ISSUE TITLE
[Bug]: Sequence tagger with CRF gives wrong probabilities for all classes

### ISSUE THREAD

**Issue by petermartens1992** [flairNLP/flair#3469]
### Describe the bug

I have trained a sequence tagger with CRF and use the return_probabilities_for_all_classes flag when making the predictions.

The returned probabilities are wrong, ie the one selected label of the token is not the same as the label with the highest probability from the returned list.

This used to work fine in flair 0.10 but fails in 0.13.1

Also the probabilities for the spans are not available anymore via span.labels so currently I calculate them myself again from the tokens. Not sure if they are available in another way.

### To Reproduce

```python
-
```

### Expected behavior

-

### Environment

flair 0.13.1

**Comment by mauryaland** [comment]
Will be fixed with this pull request https://github.com/flairNLP/flair/pull/3455

**Comment by petermartens1992** [comment]
Hi @mauryaland, thanks for the pointer!

I patched it in my code base and can confirm it seems to work correctly now. Many thanks!

Any idea when it will be released as a new version?

**Comment by fkdosilovic** [comment]
@helpmefindaname Seems that this issue can be closed since https://github.com/flairNLP/flair/pull/3455 was merged.
