### ISSUE TITLE
[Bug]: JsonlDataset cannot pass tokenizer

### ISSUE THREAD

**Issue by david-waterworth** [flairNLP/flair#3476]
### Describe the bug

I'm trying to port an AllenNLP model to a framework that's still maintained so am considering `flair`. My original model is a character LSTM based tagger. It's character based because it consists of abbreviated sensor point names that are hard to reliably tokenize (i.e. "AHU-01-L2.ZnTSP" or "BLD2.LV3,VAV 01-02 DMPOS"). 

In particular whilst I've created custom huggingface tokenizers using various regexes etc it's not possible to ensure that any tokenizer other than a character based one always ensures a split before and after any entity I want to tag.

Also whitespace is important (or at least whitespace and punctuation are used interchangably and it doesn't make sense to drop whitespace and retain punctuation). For this reason I cannot use the standard CoNLL format as it doesn't allow for whitespace tokens as far as I know?

So I would generally use a spacy compatible jsonl format consisting of text and label_spans, which `JsonlDataset` supports, but there's no allowance for any tokenization other than the default, i.e.

https://github.com/flairNLP/flair/blob/ca1b90bff70fe322087618994500d8c5f8e91d17/flair/datasets/sequence_labeling.py#L215

Also the code to match character indices to token indicates returns the token index of the preceding token, not the actual matched token, i.e.

https://github.com/flairNLP/flair/blob/ca1b90bff70fe322087618994500d8c5f8e91d17/flair/datasets/sequence_labeling.py#L253

I think the conditions should be

```
            if token.start_position <= start < token.end_position and start_idx == -1:
            ...

            if token.start_position < end <= token.end_position and end_idx == -1:
```
### To Reproduce

```python
from flair.datasets.sequence_labeling import JsonlDataset

train = JsonlDataset("data/processed/train.jsonl", text_column_name="text", label_column_name="spans")
```

### Expected behavior

Sentences created by the JsonlDataset should accept the `use_tokenizer` parameter

### Environment

n/a

**Comment by david-waterworth** [comment]
This is my "patched" version

```
class JsonlDatasetEx(JsonlDataset):
    def __init__(
        self,
        path_to_jsonl_file: Union[str, Path],
        encoding: str = "utf-8",
        text_column_name: str = "text",
        label_column_name: str = "spans",
        metadata_column_name: str = "metadata",
        label_type: str = "ner",
        use_tokenizer: bool | Tokenizer = True,
    ) -> None:
        path_to_json_file = Path(path_to_jsonl_file)

        self.text_column_name = text_column_name
        self.label_column_name = label_column_name
        self.metadata_column_name = metadata_column_name
        self.label_type = label_type
        self.path_to_json_file = path_to_json_file

        self.sentences: list[Sentence] = []
        with path_to_json_file.open(encoding=encoding) as jsonl_fp:
            for line in jsonl_fp:
                current_line = json.loads(line)
                raw_text = current_line[text_column_name]
                current_labels = current_line[label_column_name]
                current_metadatas = current_line.get(self.metadata_column_name, [])
                current_sentence = Sentence(raw_text, use_tokenizer=use_tokenizer)

                self._add_labels_to_sentence(raw_text, current_sentence, current_labels)
                self._add_metadatas_to_sentence(current_sentence, current_metadatas)

                self.sentences.append(current_sentence)

    def _add_label_to_sentence(self, text: str, sentence: Sentence, start: int, end: int, label: str):
        # Search start and end token index for current span
        start_idx = -1
        end_idx = -1
        for token in sentence:
            if token.start_position <= start < token.end_position and start_idx == -1:
                start_idx = token.idx - 1

            if token.start_position < end <= token.end_position and end_idx == -1:
                end_idx = token.idx - 1

        # Throw error if indices are not valid
        if start_idx == -1 or start_idx > end_idx:
            raise ValueError(
                f"Could not create token span from char span.\n\
                    Sen: {sentence}\nStart: {start}, End: {end}, Label: {label}\n\
                        Ann: {text[start:end]}\nRaw: {text}\nCo: {start_idx}, {end_idx}"
            )

        sentence[start_idx : end_idx + 1].add_label(self.label_type, label)
```

tested with

```
class CharTokenizer(Tokenizer):
    def tokenize(self, text: str) -> list[str]:
        return list(text)
```

**Comment by helpmefindaname** [comment]
Hi @david-waterworth 
I agree that this would be a good feature extension to flair,
since you already invested some time, do you want to create a Pull request?

**Comment by david-waterworth** [comment]
@helpmefindaname - will do, I've update the code to a fork [here](https://github.com/david-waterworth/flair). Haven't had a chance to add tests yet.
