### ISSUE TITLE
[Question]: possible to export StackedEmbeddings as onnx?

### ISSUE THREAD

**Issue by joprice** [flairNLP/flair#3508]
### Question

Is it possible to export a POS model using StackedEmbeddings as onnx? When attempting to convert a model I get errors expecting a transformers based class for embeddings.

**Comment by helpmefindaname** [comment]
Hi @joprice 

short answer: No, it is not.

We have some support for exporting to ONNX, but it doesn't generically work with everything. So far you can mainly replace TransformerEmbeddings following [this tutorial](https://github.com/flairNLP/flair/blob/e17ab1234fcfed2b089d8ef02b99949d520382d2/resources/docs/TUTORIAL_PRODUCTION_FASTER_TRANSFORMERS.md?plain=1#L3)
