### ISSUE TITLE
[Bug]: Support metric is reported incorrectly for multi-class classifier model evaluation

### ISSUE THREAD

**Issue by MattGPT-ai** [flairNLP/flair#3509]
### Describe the bug

The classification report returned from running evaluate for a classifier model reports accuracy instead of support when it is not a multi-label classifier

### To Reproduce

```python
import flair

result = trainer.model.evaluate(test_set, gold_label_type=label_type)
print(result.classification_report['micro avg']['support'])
```

### Expected behavior

Support should report the integer number of samples 

##### Flair
0.13.1
##### Pytorch
2.3.1+cu121
##### Transformers
4.31.0
#### GPU
True

**Comment by fkdosilovic** [comment]
@alanakbik Looks like this bug can be closed.
