### ISSUE TITLE
[Bug]: dropout duplicated in serquence tagger

### ISSUE THREAD

**Issue by david-waterworth** [flairNLP/flair#3514]
### Describe the bug

Maybe this is deliberate, but dropout is performed twice in the forward method of 

https://github.com/flairNLP/flair/blob/e17ab1234fcfed2b089d8ef02b99949d520382d2/flair/models/sequence_tagger_model.py#L300

https://github.com/flairNLP/flair/blob/e17ab1234fcfed2b089d8ef02b99949d520382d2/flair/models/sequence_tagger_model.py#L315

### To Reproduce

```python
I'm studying the code, `sentence_tensor = self.dropout(sentence_tensor)` appears twice (as does `locked_dropout` but not `word_dropout`.
```

### Expected behavior

I would only expect to see dropout applied once in the forward pass.

### Environment

n/a

**Comment by alanakbik** [comment]
Hello @david-waterworth this is intended. Dropout can be placed between any layers in the forward pass. In our case, we do dropout before and after the RNN. When I first built the SequenceTagger, I evaluated some different dropout placements and found this to be a good setup.

**Comment by david-waterworth** [comment]
OK interesting - but if `self.use_rnn` and `self.reproject_embeddings` are false, and `self.use_dropout` is true it'll just do dropout twice with no intervening layer (i.e. if the embedder is a transformer). Not a big deal though.
