### ISSUE TITLE
[Question]: Are BertEmbeddings still a supported type?

### ISSUE THREAD

**Issue by mh-n** [flairNLP/flair#3529]
### Question

Labeled as question, because I'm not sure this is supported still. Trying to load ClinicalBERT using the approach described using BertEmbeddings in [issue 1085](https://github.com/flairNLP/flair/issues/1085)

However, I get an import error from: 
`from flair.embeddings import BertEmbeddings`

The error is: `ImportError: cannot import name 'BertEmbeddings' from 'flair.embeddings' (/miniconda3/lib/python3.12/site-packages/flair/embeddings/___init___.py/)` 

When I navigate to the ___init___.py document, I do not see BertEmbeddings here. I installed flair using: 
`conda install conda-forge::python-flair`

Is there an updated approach I should be using to load different embeddings? Thanks in advance for your time and help!

**Comment by stefan-it** [comment]
Hi @mh-n ,

`BertEmbeddings` was deprecated in Flair 0.5 (moved to `legacy.py` class). In In 0.14 it was completely removed with this PR: https://github.com/flairNLP/flair/pull/3295.

So I highly recommend to use e.g. `TransformerEmbeddings` :) Please let us know, if this is working with the ClinicalBERT model!

**Comment by mh-n** [comment]
Hi, thanks for the quick reply. 

I'm getting this error when using `TransformerEmbeddings` in place of `BertEmbeddings` following the previous method in [#1085](https://github.com/flairNLP/flair/issues/1085)

`test = TransformerEmbeddings('pretrained_bert_tf/clinicalbert-cased')`

where `pretrained_bert_tf/clinicalbert-cased` is the path where the embeddings were downloaded

The error is: 
`OSError: Can't load tokenizer for 'pretrained_bert_tf/clinicalbert-cased'. If you were trying to load it from ' https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'pretrained_bert_tf/clinicalbert-cased' is the correct path to a directory containing all relevant files for a AlbertTokenizerFast tokenizer.`

Is there something else I should try here?

**Comment by stefan-it** [comment]
Ah yes, you would need to pass the full path to the `TransformerWordEmbeddings` constructor, such as:

```bash
from flair.embeddings import TransformerWordEmbeddings

embeddings = TransformerWordEmbeddings("/home/stefan/Repositories/flair-3529/pretrained_bert_tf/bert-base-clinical-cased")
```

So when only passing `pretrained_bert_tf/clinicalbert-cased` the model itself will be search on HF Model Hub.

**Comment by mh-n** [comment]
Thanks so much for that clarification. 

When using the full path: 
`from flair.embeddings import TransformerWordEmbeddings`
`test = TransformerWordEmbeddings('/home/mnguye79/pretrained_bert_tf/clinicalbert-cased/')`

I get the same error as I listed above [OS tokenizer error]. Trying something else, if I remove the first backslash before home (`/home/` to `home/`), I get an incorrect path error. 

I've confirmed that the folders are in the directory as I'm expecting them to, and the contents that are within the full path are: 
![image](https://github.com/user-attachments/assets/5c4abb1c-4166-4a52-961e-850fceb05231)

I'm not sure if this looks as expected or if there is something missing from the contents that are causing the error. 

Thanks again for your help.

**Comment by stefan-it** [comment]
That is very interesting, because the error message is detecting an ALBERT model (where you need a SPM-like vocab, whereas ClinicalBERT has Wordpiece-based vocab.

Could you try out the following commands:

```python
from transformers import AutoModel

# Please adjust your full path name here
model = AutoModel.from_pretrained("/home/stefan/Repositories/flair-3529/pretrained_bert_tf/bert-base-clinical-cased/")

print(model.config)
```

This should output something like this:

```python
BertConfig {
  "_name_or_path": "/home/stefan/Repositories/flair-3529/pretrained_bert_tf/bert-base-clinical-cased/",
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}
```

**Comment by mh-n** [comment]
Yes, something is wrong with the config file that I have. It is showing an Albert model: 
```
AlbertConfig {
  "_name_or_path": "/home/mnguye79/pretrained_bert_tf/clinicalbert-cased/",
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 2,
  "classifier_dropout_prob": 0.1,
  "embedding_size": 128,
  "eos_token_id": 3,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "inner_group_num": 1,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "albert",
  "num_attention_heads": 12,
  "num_hidden_groups": 1,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.41.2",
  "type_vocab_size": 2,
  "vocab_size": 28996
}
```

**Comment by stefan-it** [comment]
So could you overwrite the `config.json` with:

```json
{
  "_name_or_path": "/home/stefan/Repositories/flair-3529/pretrained_bert_tf/bert-base-clinical-cased/",
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "transformers_version": "4.44.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 28996
}
```

then the model should be loaded :)

**Comment by mh-n** [comment]
Great, it worked! Thanks for all your help :)
