### ISSUE TITLE
[Question]: Is predict(sentence, multi_class_prob=True) for TextClassifier still supported?

### ISSUE THREAD

**Issue by mh-n** [flairNLP/flair#3545]
### Question - Is predict(sentence, multi_class_prob=True) for TextClassifier still supported?

**Describe the issue**
Marked as question, because I can no longer find the functionality to specify multi_class_prob in the text_classification_model.py as referenced in several other past issues [#1709 ](https://github.com/flairNLP/flair/issues/1709), [#2287 ](https://github.com/flairNLP/flair/issues/2287), [#2376 ](https://github.com/flairNLP/flair/issues/2376)

**To reproduce**
After initializing and training a TextClassifier that was set to `multi_label = True` and trying to run something like: `classifier.predict(sentence, multi_class_prob = True)` 

The error I receive is: `TypeError: DefaultClassifier.predict() got an unexpected keyword argument 'multi_class_prob'`

**Expected behavior**
There is no issue yielding a single label when I omit `multi_class_prob` from the function. Is there an alternative to this parameter that we should be using? 

**Environment**
Linux 3.10.0-1127.10.1.el7.x86_64, Python 3.12.2, Flair 0.13.1

Appreciate any help you can provide. Thank you!

**Comment by helpmefindaname** [comment]
Hi @mh-n the docs for that function can be found [here](https://flairnlp.github.io/flair/v0.14.0/api/flair.nn.html#flair.nn.DefaultClassifier.predict)
