### ISSUE TITLE
hunflair2 model is not found

### ISSUE THREAD

**Issue by YashotharaS** [flairNLP/flair#3547]
Dear all,
I'm encountering the error "ValueError: Could not find any model with name 'hunflair2'" when trying to run the code tagger = Classifier.load("hunflair2") as mentioned on the GitHub page. I'm using Flair version 0.14.0, and while hunflair v1 works without issues, the code is unable to find hunflair2. Could you please help me resolve this issue?

**Comment by helpmefindaname** [comment]
@sg-wbi @WangXII
it looks like https://huggingface.co/hunflair/hunflair2-ner has pickeled a PosixPath and therefore cannot be loaded in Windows.
The flair trainer doesn't save paths anymore, see https://github.com/flairNLP/flair/blob/master/flair/trainers/trainer.py#L894

Can one of you execute 
```python
model = Classifier.load("hunflair2")
model.model_card["training_parameters"]["base_path"] = str(model.model_card["training_parameters"]["base_path"])
model.save("pytorch_model.bin")
```
and commit the new model on the HF-Hub?

**Comment by WangXII** [comment]
Thanks @helpmefindaname, I've committed the new model according this to hf-hub!

**Comment by helpmefindaname** [comment]
@WangXII thank you,

@YashotharaS can you try out if it works now? You might have to delete the `%HOME%\.flair\models\hunflair2-ner` folder first, so that you download the right version

**Comment by YashotharaS** [comment]
Thanks a lot @WangXII and @helpmefindaname 

I tried it, and it works fine now. Thanks again for your help :)

**Comment by tecosaur** [comment]
I've just tried `Classifier.load("hunflair2")` (Linux, Python 3.12, Flair 0.14), and I'm seeing

```
ERROR: The key 'hunflair2' was neither found on the ModelHub nor is this a valid path to a file on your system!

ValueError: Could not find any model with name 'hunflair2'
```

I'd appreciate any help getting this working.

**Comment by WangXII** [comment]
I created a new conda environment with python==3.12.8 and only flair==0.14.0 installed via pip on openSUSE 15.5 and could not replicate the error.

Did you try out installing flair in a new environment and could you replicate the error? If yes, could you provide some information about your Linux version?

**Comment by tecosaur** [comment]
Well this is interesting, I'm running Python 3.12.8 on openSUSE Tumbleweed with a fresh environment.

I did install this in a conda environment, but that shouldn't make a difference should it?

**Comment by WangXII** [comment]
Hmm, yeah, this should not make any difference. Can you try out whether loading the model via its HuggingfacePath works?

`model = Classifier.load("hunflair/hunflair2-ner")` https://huggingface.co/hunflair/hunflair2-ner

**Comment by tecosaur** [comment]
Ok, this is a bit weird. I tried it and it worked once, but then calling it again I got the error??

Attempt 1:
```py
>>> Classifier.load("hunflair/hunflair2-ner")
2024-12-12 19:01:30,166 SequenceTagger predicts: Dictionary with 21 tags: O, S-Chemical, B-Chemical, E-Chemical, I-Chemical, S-Gene, B-Gene, E-Gene, I-Gene, S-Disease, B-Disease, E-Disease, I-Disease, S-Species, B-Species, E-Species, I-Species, S-CellLine, B-CellLine, E-CellLine, I-CellLine
Python:
```

Attempt 2:
```py
>>> Classifier.load("hunflair/hunflair2-ner")
2024-12-12 19:02:10,892 --------------------------------------------------------------------------------
2024-12-12 19:02:10,892 ERROR: The key 'hunflair/hunflair2-ner' was neither found on the ModelHub nor is this a valid path to a file on your system!
2024-12-12 19:02:10,892  -> Please check https://huggingface.co/models?filter=flair for all available models.
2024-12-12 19:02:10,892  -> Alternatively, point to a model file on your local drive.
2024-12-12 19:02:10,892 --------------------------------------------------------------------------------
```

This is without restarting the process in between.

**Comment by WangXII** [comment]
Indeed, sounds weird. I guess this is also why the default `"hunflair2"` model now returns the error. Can you check your flair model cache at `~/.flair/models` whether it stored any models successfully?

**Comment by WangXII** [comment]
Yeah, I guess so. Let's see whether @helpmefindaname knows something about this
