### ISSUE TITLE
[Bug]: IndexError: list index out of range

### ISSUE THREAD

**Issue by shin0727** [flairNLP/flair#3577]
### Describe the bug

I got error in 
"flair/lib/python3.10/site-packages/flair/gtf_to_bed.py", line 108, in <module>
    if blockcount > 1 and blockstarts[0] > blockstarts[1]:  # need to reverse exons"

IndexError: list index out of range

### To Reproduce

```python
flair collapse -g ${REF} --gtf ${EGAPX_GTF} -q ../../02_correct/${PREFIX}/${PREFIX}_all_corrected.bed -r ${FASTQ} --stringent --check_splice --generate_map --annotation_reliant generate --output ${PREFIX} --thread ${THREAD}
```

### Expected behavior

${PREFIX}_scaf.annotated_transcripts.bed 

### Logs and Stack traces

```stacktrace
Traceback (most recent call last):
  File "/home/junkim/tools/miniconda3/envs/flair/lib/python3.10/site-packages/flair/gtf_to_bed.py", line 108, in <module>
    if blockcount > 1 and blockstarts[0] > blockstarts[1]:  # need to reverse exons
IndexError: list index out of range
```

### Screenshots

![image](https://github.com/user-attachments/assets/cbd0c5a0-e4dd-4dc4-8459-c869f32a06bc)

### Additional Context

ModuleNotFoundError: No module named 'torch'

### Environment

ModuleNotFoundError: No module named 'torch'

**Comment by helpmefindaname** [comment]
Hi @shin0727 
it looks to me, like you are trying to use a different library that has the same name as ours.
I can ensure you that in our library:
* `flair collapse` isn't a valid command, as we are not providing any installable scripts.
* `flair/gtf_to_bed.py` doesn't exist.
* `torch` would be installed as a dependency when installing flair.

If you intend to use [flair-brookslab](https://pypi.org/project/flair-brookslab/) then you might be better off to contact the authors of that library.
