### ISSUE TITLE
[Question]: Get NER text and labels separately (and lack of API documentation)

### ISSUE THREAD

**Issue by alxgrh** [flairNLP/flair#3584]
### Question

Hello Flair team,
and thank you for your great project!

I'm trying to use Flair for named entity recognition task. I need to get text and associated label separately. Unfortunately documentation examples contain only code for printing entire NER. 
So far I've come to this solution
```
for entity in sentence.get_spans('ner'):
    text = ' '.join([token.text for token in entity.annotation_layers['ner'][0].data_point.tokens])
    label = entity.annotation_layers['ner'][0].value
    print(text, '->', label)
```

Is there some more elegant API usage option? Like in spacy-nlp for example
```
doc = nlp(text)
for ent in doc.ents:
    print(ent.text, '->', ent.label_)
```

**Comment by helpmefindaname** [comment]
Hi @alxgrh 
I think your question is answered in [this tutorial](https://flairnlp.github.io/flair/v0.15.0/tutorial/tutorial-basics/how-predictions-work.html) or by using [get_labels](https://flairnlp.github.io/flair/v0.15.0/api/generated/flair.data.Sentence.html#flair.data.Sentence.get_labels)
