### ISSUE TITLE
Discussion: Add GLUE benchmark support

### ISSUE THREAD

**Issue by alanakbik** [flairNLP/flair#359]
Discussion: We are thinking of adding more support to benchmarks such as GLUE to Flair. Ideally, this would allow users to train and evaluate models with different embeddings (Flair/BERT/ELMo) on this benchmark. 

This may also motivate more development of multi-task models in Flair (#119) and perhaps restart earlier discussions we've had with the community on creating comparable benchmarks for languages other than English, such as a German GLUE or SQuaD benchmark (#73).

To add GLUE, we would need: 

- Add GLUE datasets to the dataset downloader and corpus reader for convenient setup. 
- Add evaluation routines for the GLUE tasks
- Perhaps convenience methods for training/evaluating over the full set of GLUE tasks
- anything else?

**Comment by stefan-it** [comment]
Here's a nice script with download urls for the GLUE dataset:

https://gist.github.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e

Found that hint in `pytorch-pretrained-BERT`  😅
