### ISSUE TITLE
Create cache_dir parameter on BertEmbeddings init

### ISSUE THREAD

**Issue by orair** [flairNLP/flair#360]
When developing on environments where the default cache_dir for BertEmbeddings cannot be used I cannot change the cache_dir.

BertEmbeddings should have cache_directory exactly as FlairEmbeddings does.

On BertEmbeddings initialization (__init__) the cache_directory should be passed as cache_dir while initializing the tokenizer and model on from_pretrained commands.
self.tokenizer = BertTokenizer.from_pretrained(bert_model, cache_dir=cache_directory)
self.model = BertModel.from_pretrained(bert_model, cache_dir=cache_directory)

**Comment by alanakbik** [comment]
Hello @orair that's a good point, thanks for spotting this. 

We could even use the `.flair` folder that we use to store embeddings/models/datasets as default folder for caching this and allow users to change the folder like you mentioned. 

Care to do a pull request for this?
