### ISSUE TITLE
Google Universal Sentence Encoder

### ISSUE THREAD

**Issue by mvss80** [flairNLP/flair#378]
Is it possible to add Google's Transformer Model available at https://tfhub.dev/google/universal-sentence-encoder-large/3 as part of Document Embeddings within Flair? 

I couldn't find any pytorch port of that model and it would be very handy to be able to run comparisons.

**Comment by alanakbik** [comment]
Yes, that is a great idea. We would like to get more transformer architectures into Flair, for instance to train transformer-based LMs. 

I am not sure when we can get around to implementing this, so any help from the community would be greatly appreciated!

**Comment by stefan-it** [comment]
I think [InferSent](https://github.com/facebookresearch/InferSent) would be a good alternative and a PyTorch implementation exists :)

**Comment by franz101** [comment]
https://github.com/helloeve/universal-sentence-encoder-fine-tune/blob/master/universal_sentence_encoder_fine_tune.ipynb

Here is also a good example. Who would like to implement it with me?

**Comment by franz101** [comment]
Here is also the link for the pertained large english model: https://storage.googleapis.com/tfhub-modules/google/universal-sentence-encoder-large/3.tar.gz
