### ISSUE TITLE
Which tokenizer does Flair use?

### ISSUE THREAD

**Issue by Deep1994** [flairNLP/flair#394]
Hi, I want to tokenize my own text like what Flair does, so I want to know what tokenizer Flair uses? The length of my sentences is variable, does Flair embeddings have any special token considered as a padding token? Or how to process sentences which have variable length when I use Flair? Thanks!

**Comment by stefan-it** [comment]
A Padding example can be found [here](https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L648) :)

**Comment by Deep1994** [comment]
Thank you, what about word tokenization?

**Comment by alanakbik** [comment]
If you pass `use_tokenizer=True` the segtok library is used to tokenize a sentence. So initialize your sentence like this: 

```python
from flair.data import Sentence

# Make a sentence object by passing an untokenized string and the 'use_tokenizer' flag
sentence = Sentence('The grass is green.', use_tokenizer=True)

# Print the object to see what's in there
print(sentence)
```

As @stefan-it wrote, padding is already taken care of when you use our embedding classes, so you need not worry about special padding tokens. 

However, I should caution that `segtok` was built with English in mind. If you want to use a different tokenizer it may be better to first tokenize your text with this tokenizer and write out whitespace tokenized strings. Then read those in without `use_tokenizer=True`.

Hope this helps!

**Comment by stefan-it** [comment]
@alanakbik Do you think it is worth to add support for different tokenization libraries? E.g. it seems that everyone is using `spacy` now (here's an [overview](https://spacy.io/models/) of available models/languages). But I guess `spacy` is computationally not as cheap as `segtok` 🤔

**Comment by alanakbik** [comment]
Yes it would be good to add support for different tokenizers. I was thinking of a unified interface for all tokenizers so that users can easily switch them out. 

I am a bit hesitant of adding spacy since -- like allennlp -- this is a massive library with lots of subdependencies that would get installed by default. Since we try to keep Flair lightweight, we generally don't want to add too many dependencies. So I am not sure what the best way forward is on tokenization.

**Comment by stefan-it** [comment]
I would really like to have this kind of interface - I think we could make all dependencies like `spacy` optional (using `try-catch` statements like it is done with `allennlp` library when using the ELMo embeddings).

I currently use the BERT tokenizer code for simply tokenization :)

**Comment by alanakbik** [comment]
This functionality was added a while back
