### ISSUE TITLE
Using own CONLL format data for NER

### ISSUE THREAD

**Issue by prabhatM** [flairNLP/flair#431]
Hi,
1) I have a few files in CONLL format designed for customised NER.
The multiple files are named in the following format BMC_Anesthesiol_2001_Oct_22_1_1.nxml.txt.txt.nlp
How to use these files for customised NER in Flair?

2) After creating Stacked Embedding, can we export it to Gensim word2Vec format in a single file?

A little nudge will help.

Regards

Prabhat MOHANTY

[BMC_Anesthesiol_2001_Oct_22_1_1.nxml.txt.txt.txt](https://github.com/zalandoresearch/flair/files/2815491/BMC_Anesthesiol_2001_Oct_22_1_1.nxml.txt.txt.txt)

**Comment by alanakbik** [comment]
Hello @prabhatM - to read the corpus, you need to define your own column format and pass the filename to the data fetcher, like this: 

```python
corpus = NLPTaskDataFetcher.load_column_corpus(data_folder='path/to/your/data/folder',
                                               column_format={1: 'text', 2: 'pos', 3: 'ner', 4: 'lemma', 5: 'deprel'},
                                               train_file='BMC_Anesthesiol_2001_Oct_22_1_1.nxml.txt.txt.txt')

print(corpus.train[6])
for entity in corpus.train[6].get_spans('ner'):
    print(entity)
```

this should print: 
```python
Sentence: "In an RCT design , we investigated whether a dose of mivacurium 250 g/kg results in faster onset of action than 200 g/kg in infants under isoflurane anesthesia ." - 29 Tokens
NUMBER-span [13]: "250"
NUMBER-span [22]: "200"
```

By defining your column format, you can tell the reader which column means what. Please also check out the [data reading tutorial](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md) for more info!

**Comment by prabhatM** [comment]
I have a few hundreds of such files for NER. How do I split them for Train, Test and Dev ?
Sklearn has a built in method. Do we have anything of similar kind?

**Comment by alanakbik** [comment]
Currently, the data fetcher expects Train, Test and Dev files to be passed explicitly, meaning that you first have to define those splits yourself. You can also just define the Train split and it will sample Dev automatically. 

Since we are currently looking into refactoring the data loading part for larger datasets and multiprocessing, perhaps in the future we can also add more convenience methods to the data fetcher.

**Comment by prabhatM** [comment]
Thank you for your response.
As I see the model asks for specific train.txt and test.txt with content.
Does the program expect us combine the contents of multiple into a single file ? Can it read multiple files from different subdirectories like test, dev etc or is there any way to feed only number of files to the model like test=70, Dev=20 etc and it may pick up that many files from the data directory directly?

**Comment by alanakbik** [comment]
Yes the current way to prepare your data would be to combine your data into single files. One file for train, test and dev each. In the future, I hope we can add more helper classes to make data loading more convenient, such as the way you suggest.

**Comment by prabhatM** [comment]
Ah, I had come so close to using Flair in my application this evening itself and now the lotus just shifted away from me! :)
