### ISSUE TITLE
Introducing Attentional BiLSTM for Text Classification

### ISSUE THREAD

**Issue by 53X** [flairNLP/flair#460]
As per my understanding ,  Flair by default uses the **standard BiLSTM model** for text classification.

I guess introducing **Attentional BiLSTM** might improve this maybe?

An easy solution to this might be to just introduce a parameter named **attention** in the **TextClassifier** class that decides whether to use attention or not

**Comment by 53X** [comment]
If this issue is a go, I would love to take up the challenge

**Comment by alanakbik** [comment]
That's a great idea - we'd very much appreciate it if you added this! :)

**Comment by 53X** [comment]
@alanakbik , I am on it

**Comment by nickkimer** [comment]
@53X excited to see this implementation

**Comment by 53X** [comment]
`self.__embedding_length: int = hidden_size
        if self.bidirectional:
            self.__embedding_length *= 4`

Found this piece of code in `embeddings.py` in the `DocumentLSTMEmbeddings` class. 

@alanakbik , my question is whether `4` should be `2` in the last line. This is because in PyTorch the `hidden_size` changes to `num_directions*hidden_size` when `bidirectional` is set to` True`

**Comment by heukirne** [comment]
Here is an interesting approach implemented also in PyTorch that could be useful:
https://github.com/hantek/SelfAttentiveSentEmbed#third-party-implementations

**Comment by 53X** [comment]
@alanakbik,  can this be merged if this is working fine now

**Comment by alanakbik** [comment]
Ok, I've just put in a PR #582 to merge the branch into master. Could you double-check that everything looks OK from your side in the PR?

**Comment by 53X** [comment]
this looks ok @alanakbik

**Comment by HiyaToki** [comment]
Was this feature removed from later versions?
