### ISSUE TITLE
Stacked NER corpus like Stacked embedding

### ISSUE THREAD

**Issue by prabhatM** [flairNLP/flair#467]
Love the idea of stacked embedding.
Can we do similar stuff for NER?
CoNLL 2003 offers us Loc, Per and Org.
On the top of it we can stack our medical or any domain specific NER ( corpus in CoNLL format) !
Doable?

Regards

Prabhat MOHANTY

**Comment by alanakbik** [comment]
Not sure if I understand the idea correctly. Could you elaborate?

**Comment by prabhatM** [comment]
We mostly get NER like PER,LOC,ORG from CoNLL 2003.
We also have a corpus that gives us DISEASE/DISORDER, The corpus is in CoNLL format.
Now by stacking these two independent corpus(Like stacked embedding), we can get all 4 NER form the text through a single pass, can we?

Prabhat
