### ISSUE TITLE
Loading files from s3, not working

### ISSUE THREAD

**Issue by NeverInAsh** [flairNLP/flair#497]
A clear and concise description of what you want to know.
Hi All,
I am facing a very peculiar issue while using the text classifier function inside flair package.
While using this function
`corpus = NLPTaskDataFetcher.load_classification_corpus(path_to_write, test_file='test.csv', dev_file='validate.csv', train_file='train.csv')`

I am getting FileNotFoundError, digging more into the code i realize the line which can create error is 
![image](https://user-images.githubusercontent.com/7336367/52770902-64edb280-305a-11e9-9d5f-c241ad4aa2b5.png)
where path_to_write is the location of my s3 folder where my train.csv is present.

The surprising part is if i use pandas i am able to read the same file address being (path_to_write +'train.csv')

**Comment by alanakbik** [comment]
Hello @NeverInAsh have you managed to resolve this issue?
