### ISSUE TITLE
Support for Dilated RNN?

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#501]
Hi,

I just found the dilated rnn [implementation](https://github.com/zalandoresearch/pytorch-dilated-rnn) in the *zalandoresearch* group and I'm just wondering if this could also be useful for lm training in `flair`?

Has anyone tried it yet 🤔

**Comment by alanakbik** [comment]
:) Yes I tried it a long while back for training language models - if I remember correctly the training was much faster but it took more epochs to learn. At the time, I did not investigate the trade-off more closely and just defaulted to regular RNNs. 

We also never investigated how good representations from dilated RNN LMs are as embeddings for downstream tasks - might be interesting to find out!
