### ISSUE TITLE
Add support for biomedical NER datasets

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#510]
A great enhancement would be to have built-in dataset loaders for biomedical NER datasets.

A good resource are the datasets mentioned in the [BioBERT paper](https://arxiv.org/abs/1901.08746). The datasets can be downloaded form the [BioBERT](https://github.com/dmis-lab/biobert) repository.

Thus, the following datasets can be supported:

* NCBI disease
* BC5CDR (Disease and Drug/Chemical)
* BC4CHEMD
* BC2GM
* JNLPBA
* LINNAEUS
* Species-800

**Comment by alanakbik** [comment]
Yes that's a great idea! Together with the ELMo pubmed model (#502) and the Flair pubmed embeddings (#518) this could enable more research into biomedical data.

**Comment by stefan-it** [comment]
For now I'm going to write importers for the following datasets:

* JNLPBA
* NCBI-disease
* bc5cdr

Thanks to the `SciBERT` authors, these datasets are already preprocessed and can simply be fetched from their GitHub [repository](https://github.com/allenai/scibert) :)

**Comment by shreyashub** [comment]
@stefan-it Were you able to write importers for some of the datasets? If yes, could you reference the PR here?
If no, then I could help in that, along with the other medical NER datasets that were not in SciBERT.

**Comment by alanakbik** [comment]
There is a highly active branch currently in which my colleagues are adding a large amount of different biomedical datasets. See #1513. I think it will be merged soon!

**Comment by alanakbik** [comment]
Support for biomedical datasets was added in Flair 0.6. If any datasets are missing let us know!
