### ISSUE TITLE
How to use Flair for segmenting text

### ISSUE THREAD

**Issue by emrul** [flairNLP/flair#513]
Hi, I'd like to use Flair to experiment with putting paragraphs into text similar to http://aclweb.org/anthology/N18-2075 (I have some other segmentation problems to try but trying to begin with one where I can generate a lot of data with.)

However I'm unsure if the training format Flair needs supports this. I don't have to use the format used in the paper - I could for example produce a data file with one paragraph per line if necessary.

Any pointers would be appreciated.

**Comment by bedapudi6788** [comment]
You can train Flair's NER model for segmenting text and it works excellently well. Doing this will get you results similar to https://github.com/bedapudi6788/deepsegment/

**Comment by emrul** [comment]
Thanks @bedapudi6788 this looks perfect.  I didn't realise I could do it with a NER model but I will go try it this week!

**Comment by alanakbik** [comment]
@emrul great, we'd be interested to hear how well it works!

**Comment by bedapudi6788** [comment]
@alanakbik , I have a trained Flair model for english that does segmentation for punctuated and unpunctuated text excellently. If anyone is interested, I can provide a link for the checkpoints.

**Comment by alanakbik** [comment]
Oh that is great - we'd appreciate if you could share the models!

**Comment by krzynio** [comment]
@alanakbik 

I can provide polish model developed with the same method if there is a need for that.

**Comment by alanakbik** [comment]
@krzynio we'd appreciated it if you shared it!

**Comment by emrul** [comment]
I’d appreciate a link to these also - starting on my model work this week

**Comment by krzynio** [comment]
> @krzynio we'd appreciated it if you shared it!

https://drive.google.com/file/d/1CyCzM4lo--0_v6Ajzr-gndta1kUtjTcf/view?usp=sharing
