### ISSUE TITLE
Adding basic Seq2Seq model on top of Flair Embeddings. This is because in NMT context plays a important role.

### ISSUE THREAD

**Issue by 53X** [flairNLP/flair#560]
@alanakbik , if this issue is a go, I would love to make a PR.

**Comment by stefan-it** [comment]
Sounds very interesting (second "hobby" of mine is NMT) +:1 Do you plan to implement a seq-to-seq or do want to use e.g. fairseq + build a model/context ontop of it?

There's an interesting Sennrich paper, that uses several linguistic input features (https://arxiv.org/abs/1606.02892) - that would be a great start :)

**Comment by 53X** [comment]
Thanks for the heads up. I will look into this paper @stefan-it
