### ISSUE TITLE
About the BERT pretrained file

### ISSUE THREAD

**Issue by aslicedbread** [flairNLP/flair#562]
Hi~
When I use:
`embedding = BertEmbeddings('bert-base-chinese')`
what the console shows seems to be downloading the BERT pretained file ? and it's a bit slow.
So I would like to know whether we can load local BERT pretrained file instead of downloading from the Internet?
Thanks a lot.

**Comment by alanakbik** [comment]
Yes, as of Flair 0.4.1 you can pass the path to a local BERT model. See #526

**Comment by aslicedbread** [comment]
> Yes, as of Flair 0.4.1 you can pass the path to a local BERT model. See #526
Thanks a lot. Besides, if the NER dataset I use was tagged with BIOES Scheme, do I need to set anything extra?

**Comment by aslicedbread** [comment]
> Yes, as of Flair 0.4.1 you can pass the path to a local BERT model. See #526

Thanks a lot. Besides, If the  NER dataset I use was tagged with BIOES not BIO Scheme, do I need to set anything extra?
