### ISSUE TITLE
About the ValueError: Token indices sequence length is longer than the specified maximum sequence length

### ISSUE THREAD

**Issue by aslicedbread** [flairNLP/flair#575]
Hi~
I recently used Flair to tag the electronic chinese medical records. And every record is a long text but less than 1000 characters. I found that Flair based on BERT has a limit on the length of the input sequence:

> ValueError: Token indices sequence length is longer than the specified maximum  sequence length for this BERT model (613 > 512). Running this sequence through BERT will result in indexing errors.

Is there a solution?
Hope to get your reply, Thanks.

**Comment by bheinzerling** [comment]
Are you using ´bert-base-multilingual-cased` or `bert-base-chinese`? Monolingual models give better tokenization wtih longer subwords segments due to the limited WordPiece vocabulary size.

Other than that, up to 1000 Chinese characters is pretty long. Can you split the text into smaller units like sentences or paragraphs?

**Comment by aslicedbread** [comment]
> Are you using `bert-base-multilingual-cased` or `bert-base-chinese`? Monolingual models give better tokenization wtih longer subwords segments due to the limited WordPiece vocabulary size.
> 
> Other than that, up to 1000 Chinese characters is pretty long. Can you split the text into smaller units like sentences or paragraphs?

Hi~

Yes, I'm using bert-base-chinese.  Do you mean that 'bert-base-chinese' give better tokenization wtih longer subwords segments than 'bert-base-multilingual-cased' ? I‘m a bit confused about the Monolingual models, is it like BiLSTM-CRF model without bert ?

Yes, I split the text into smaller units later and it works.

**Comment by vabhishekprdxn** [comment]
Hi @aslicedbread I am also facing the same issue. Could you please show me how you have split the text and feeding to the model?
