### ISSUE TITLE
Another question about f1-score and tps, fps and fns

### ISSUE THREAD

**Issue by stbirc** [flairNLP/flair#580]
Hi,

I am training some NER models and part of the output of one of them was the following:
```
Testing using best model ...
loading file resources.d/taggers/ner/wikifr/cor-stringemb/best-model.pt
MICRO_AVG: acc 0.5514 - f1-score 0.7109
MACRO_AVG: acc 0.435 - f1-score 0.5754
amount     tp: 1217 - fp: 485 - fn: 499 - tn: 1217 - precision: 0.7150 - recall: 0.7092 - accuracy: 0.5529 - f1-score: 0.7121
```
If I use the `best-model.pt` in order to tag the test file and do a manual evaluation on the resulting data using the `conlleval` script I get the following scores (for the part/class shown above):
```processed 202842 tokens with 14555 phrases; found: 14364 phrases; correct: 10124.
accuracy:  94.64%; precision:  70.48%; recall:  69.56%; FB1:  70.02
           amount: precision:  70.49%; recall:  70.57%; FB1:  70.53  1718
```
and if I output the respective tp/fp/fn values I get the following:
```
'amount': tp=1211, fp=507, fn=505, prec=0.7048894062863795, rec=0.7057109557109557, fscore=0.7052999417588817
```

Am I doing something wrong or why tps/fps/fns and consecuently precision, recall and f1-score are different for the FLAIR output and the `conlleval` script output (in the case of all of my 32 NE labels)?

**Comment by alanakbik** [comment]
That is strange. Which tagging scheme do you use? The conlleval script cannot handle BILOES tagged entities - it only works for BIO tagged entities. If you want to use the conlleval script for BILOES tagged entities, you first need to convert them back into BIO.

**Comment by stbirc** [comment]
Hi @alanakbik, thanks for your immediate reply. The scheme we use is the BIO one. I also checked the tags again and could not find any inconsistencies. Basically, I don't think that I'm doing something wrong when tagging the test data with the `best-model.pt`, because of if I do the same with the `final-model.pt` I get a file with tags identical to the final `test.tsv` outputted after training.

**Comment by stbirc** [comment]
Hi @alanakbik, I did some further experiments on this and to me it seems that the better the tagger learns to predict the lower the disagreement between FLAIR information and `conlleval` scores.
Using a reduced tagging scheme, I trained two taggers, one with only `FlairEmbeddings` and another with an additional CRF layer, both for 50 epochs. Obviously, the model with the CRF layer reaches better results and the precision, recall and f1-score values outputted at the end of training are much closer to the respective `conlleval` scores than the ones generated in the case of the model without CRF.
#### Experimental training without CRF
Output FLAIR after 50 epochs:
```
MICRO_AVG: acc 0.4667 - f1-score 0.6364
MACRO_AVG: acc 0.4218 - f1-score 0.5614
amount     tp: 6 - fp: 6 - fn: 10 - tn: 6 - precision: 0.5000 - recall: 0.3750 - accuracy: 0.2727 - f1-score: 0.4286
func       tp: 12 - fp: 16 - fn: 12 - tn: 12 - precision: 0.4286 - recall: 0.5000 - accuracy: 0.3000 - f1-score: 0.4616
loc        tp: 24 - fp: 10 - fn: 10 - tn: 24 - precision: 0.7059 - recall: 0.7059 - accuracy: 0.5455 - f1-score: 0.7059
org        tp: 8 - fp: 4 - fn: 6 - tn: 8 - precision: 0.6667 - recall: 0.5714 - accuracy: 0.4444 - f1-score: 0.6154
pers       tp: 29 - fp: 5 - fn: 4 - tn: 29 - precision: 0.8529 - recall: 0.8788 - accuracy: 0.7632 - f1-score: 0.8657
prod       tp: 1 - fp: 5 - fn: 7 - tn: 1 - precision: 0.1667 - recall: 0.1250 - accuracy: 0.0769 - f1-score: 0.1429
time       tp: 11 - fp: 3 - fn: 6 - tn: 11 - precision: 0.7857 - recall: 0.6471 - accuracy: 0.5500 - f1-score: 0.7097
```
Output `conlleval` on the test data tagged with `best-model.pt`:
```
processed 2004 tokens with 146 phrases; found: 143 phrases; correct: 93.
accuracy:  93.81%; precision:  65.03%; recall:  63.70%; FB1:  64.36
           amount: precision:  50.00%; recall:  37.50%; FB1:  42.86  12
             func: precision:  46.43%; recall:  54.17%; FB1:  50.00  28
              loc: precision:  68.57%; recall:  70.59%; FB1:  69.57  35
              org: precision:  58.33%; recall:  50.00%; FB1:  53.85  12
             pers: precision:  86.11%; recall:  93.94%; FB1:  89.86  36
             prod: precision:  16.67%; recall:  12.50%; FB1:  14.29  6
             time: precision:  78.57%; recall:  64.71%; FB1:  70.97  14
```
#### Experimental training with CRF
Output FLAIR after 50 epochs:
```
MICRO_AVG: acc 0.5225 - f1-score 0.6864
MACRO_AVG: acc 0.4719 - f1-score 0.6256428571428572
amount     tp: 9 - fp: 2 - fn: 7 - tn: 9 - precision: 0.8182 - recall: 0.5625 - accuracy: 0.5000 - f1-score: 0.6667
func       tp: 11 - fp: 7 - fn: 13 - tn: 11 - precision: 0.6111 - recall: 0.4583 - accuracy: 0.3548 - f1-score: 0.5238
loc        tp: 24 - fp: 10 - fn: 10 - tn: 24 - precision: 0.7059 - recall: 0.7059 - accuracy: 0.5455 - f1-score: 0.7059
org        tp: 7 - fp: 3 - fn: 7 - tn: 7 - precision: 0.7000 - recall: 0.5000 - accuracy: 0.4118 - f1-score: 0.5833
pers       tp: 30 - fp: 6 - fn: 3 - tn: 30 - precision: 0.8333 - recall: 0.9091 - accuracy: 0.7692 - f1-score: 0.8696
prod       tp: 2 - fp: 1 - fn: 6 - tn: 2 - precision: 0.6667 - recall: 0.2500 - accuracy: 0.2222 - f1-score: 0.3636
time       tp: 10 - fp: 3 - fn: 7 - tn: 10 - precision: 0.7692 - recall: 0.5882 - accuracy: 0.5000 - f1-score: 0.6666
```
Output `conlleval` on the test data tagged with `best-model.pt`:
```
processed 2004 tokens with 146 phrases; found: 126 phrases; correct: 93.
accuracy:  93.56%; precision:  73.81%; recall:  63.70%; FB1:  68.38
           amount: precision:  81.82%; recall:  56.25%; FB1:  66.67  11
             func: precision:  61.11%; recall:  45.83%; FB1:  52.38  18
              loc: precision:  68.57%; recall:  70.59%; FB1:  69.57  35
              org: precision:  70.00%; recall:  50.00%; FB1:  58.33  10
             pers: precision:  83.33%; recall:  90.91%; FB1:  86.96  36
             prod: precision:  66.67%; recall:  25.00%; FB1:  36.36  3
             time: precision:  76.92%; recall:  58.82%; FB1:  66.67  13
```
This observations are confirmed by another training process which currently is in progress. Here, I have almost identical values for FLAIR scores (from `training.log`) and `conlleval` scores based on test data tagged with intermediate best models:
```
EPOCH	TIMESTAMP	...	TEST_PRECISION	TEST_RECALL	TEST_ACCURACY	TEST_F-SCORE
27	08:57:03	...	0.7624		0.689		0.5672		0.7238
```
```
processed 203345 tokens with 14555 phrases; found: 13155 phrases; correct: 10028.
accuracy:  94.37%; precision:  76.23%; recall:  68.90%; FB1:  72.38
```
```
EPOCH	TIMESTAMP	...	TEST_PRECISION	TEST_RECALL	TEST_ACCURACY	TEST_F-SCORE
29	10:53:35	...	0.7596		0.6921		0.5677		0.7243
```
```
processed 203370 tokens with 14559 phrases; found: 13266 phrases; correct: 10075.
accuracy:  94.37%; precision:  75.95%; recall:  69.20%; FB1:  72.42
```

**Comment by alanakbik** [comment]
Hello @stbirc thanks for looking into this! 

For us to reproduce the results could you share the final test.tsv that is generated by your model? Then we can run the connleval script and our eval routine over this file to compare the two!

**Comment by stbirc** [comment]
Hi @alanakbik, sure, here is the final file (as `.txt`, [test.txt](https://github.com/zalandoresearch/flair/files/2923243/test.txt)) from the model mentioned in the initial comment. I hope it isn't a problem if words are replaced by 'token' because of I'm not sure about up to what extent I'm allowed to share the data.

**Comment by alanakbik** [comment]
Thanks - we'll take a closer look!

**Comment by alanakbik** [comment]
Hello @stbirc thanks again for sharing the files - I think I know why the results are different. There are small differences in the way the CoNLL script determines spans from BIO tagged text vis-a-vis how Flair determines spans. These differences only occur in cases where the span tagging is nonsensical, i.e. something that should only occur early in the training. This is why the differences are large at first and begin to diminish as the tagger gets better. 

Here's an example. Consider the span: 

```console
token O O 
token B-prod.art B-prod.media
token I-prod.art I-prod.art 
token I-prod.art I-prod.art 
token O O 
```

Second column is gold, third column is predicted. As this example shows, the prediction is nonsensical: There is a **B**-tag for `prod.media` that is followed by an **I**-tag for a *different entity type* (`prod.art`), which should never happen. Either a new different entity begins, or I should be of same type as the preceding B. 

The CoNLL script will split this into two entities: One one-word entity of type `prod.media` and one two-word entity of type `prod.art`. Our heuristic instead favors the BIO information over the entity type information and thus creates one three word entity of the majority type, in this case `prod.art`. 

Since our method for making spans is used during prediction, the evaluation numbers currently reported are correct and accurately tell you how well the tagger works. However, if you want to compare against earlier approaches that reported their results using the CoNLL script, you should instead run this script over the results - otherwise the numbers might not be directly comparable. Hope this clarifies!

**Comment by stbirc** [comment]
Hi @alanakbik, thanks a lot for your explanations, this really accounts for the differences between the conlleval scores and the ones outputted by flair. So, just to play safe, the flair heuristic would rate the nonsensical prediction from the _prod.art_ example as **true positive** due to the accordance with respect to the BIO information (and largely conforming entity types)?

**Comment by alanakbik** [comment]
Hi @stbirc yes, the current heuristic would interpret the above example as a single span of `prod.art` during prediction - in this case this would result in the span being counted as a true positive since the gold is also a single span of `prod.art`.
