### ISSUE TITLE
Permission error after downloading models on Windows 10

### ISSUE THREAD

**Issue by kevin91nl** [flairNLP/flair#592]
**Describe the bug**
When downloading models/embeddings to disk on Windows 10, a PermissionError is thrown.

**To Reproduce**
Install FLAIR and Cython:
```
pip install Cython
pip install flair
```

Running the following code (in a Jupyter Lab environment):
```
from flair.embeddings import WordEmbeddings
glove_embedding = WordEmbeddings('glove')
```

**Expected behavior**
A successful download of the GloVe embeddings. However, it throws a PermissionError after downloading the file:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\my-username\\AppData\\Local\\Temp\\tmpdd72vob1'
```

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]: Windows
 - Version [e.g. flair-0.3.2]: 10

**Comment by seangrant82** [comment]
I get the same error using Flair 0.4.1

`>>> import pkg_resources`
`>>> pkg_resources.get_distribution("flair").version`
'0.4.1'

**Comment by alanakbik** [comment]
Hi @kevin91nl and @seangrant82 - could this be related to issue #548? If so, we pushed a fix into the master branch (but it is not yet part of a pip release). Could you try checking out the master branch to see if the error persists?

**Comment by seangrant82** [comment]
@alanakbik looks like same issue. I will test out and see

**Comment by andrew-veresov** [comment]
same issue here
