### ISSUE TITLE
Possible feature

### ISSUE THREAD

**Issue by jmlongriver12** [flairNLP/flair#603]
I wonder if Flair could support the task like relation extraction, which is a little different from text classifier since the input would be a sentence plus two entities, if not, any plan for it?

Thanks

**Comment by alanakbik** [comment]
Hi @jmlongriver12 relation extraction is something that we would really like to see implemented in Flair. OpenIE too :) 

However, we don't currently have plans to implement this in the near future - if someone from the community would be interested in looking at this, we'd greatly appreciate it!
