### ISSUE TITLE
Pretrained Embeddings for multiple languages.

### ISSUE THREAD

**Issue by nawabhussain** [flairNLP/flair#612]
Hello. I have been looking around to figure out the usage of pretrained embeddings for multiple languages. What I am trying to achieve is to have pretrained embeddings for multiple languages so that my ML model knows similar words across multiple languages. For example, "Good" in English is the same as "Gut" in German. Any help in this regard would be highly appreciated

**Comment by nawabhussain** [comment]
@stefan-it Thank you very much for replying so quickly. I will check the papers and vecmap library as you pointed out. I have a question about MUSE though. For instance, [German-English](https://dl.fbaipublicfiles.com/arrival/dictionaries/de-en.txt) there is an entry "mit with", would that mean that I can use the embeddings of with for mit, or vice versa, so that the similar words can be clustered?

**Comment by stefan-it** [comment]
I haven't tried it yet, but there's a nice Notebook that shows how to get nearest neighbors and even visualize bilingual embeddings:

![grafik](https://user-images.githubusercontent.com/20651387/54474379-3cd1aa80-47e4-11e9-903e-f7a9cc6ff54a.png)

See here:

https://github.com/facebookresearch/MUSE/blob/master/demo.ipynb
