### ISSUE TITLE
How to prepare Ontonotes data?

### ISSUE THREAD

**Issue by snie2012** [flairNLP/flair#615]
Hi, I try to run the experiment here: https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md#ontonotes-named-entity-recognition-english.

I have downloaded the Ontonotes data and processed it following the instructions from http://conll.cemantix.org/2012/data.html. So my data looks like this in the current stage:

![Screenshot from 2019-03-18 13-33-07](https://user-images.githubusercontent.com/10590504/54550528-8821bf80-4982-11e9-8184-8e16733d4d07.png)

My question is how to transform the data above to the following format required by Flair:

```
resources/tasks/onto-ner/eng.testa
resources/tasks/onto-ner/eng.testb
resources/tasks/onto-ner/eng.train
```

**Comment by alanakbik** [comment]
Hello @snie2012 you would now need to transform it into a CoNLL-03-style BIO1 labelled format by throwing away most of the information and keeping only the token text and its entity information. Unfortunately, I am not aware of any scripts for getting from Ontonotes to CoNLL-03-style BIO1 (and our own transformation method is part of a Java pipeline that we did not yet open source) so you would need to write your own.

Should you find a conversion script somewhere or write one please share it here - I'm sure others would be happy to get the instructions/scripts.

**Comment by snie2012** [comment]
Hi @alanakbik , I found a script here: https://github.com/yuchenlin/OntoNotes-5.0-NER-BIO. It works, although requires a bit modification.

**Comment by alanakbik** [comment]
@snie2012 great! Could you perhaps document/share the changes you made so that others can follow these steps as well to reproduce the Ontonotes NER experiments? 

Also, if its not too much work, could you perhaps do a pull request to add this information to the [Ontonotes experiment description](https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md#ontonotes-named-entity-recognition-english)?

**Comment by snie2012** [comment]
@alanakbik Sure, I'll do it soon.

**Comment by VDCN12593** [comment]
@snie2012 May I know what modification you did to the transformation script at https://github.com/yuchenlin/OntoNotes-5.0-NER-BIO ? I used their script to generate the train/dev/test.txt files, but flair's tagger (ner-ontonotes) has poor evaluation results on the test file (F1 ~ 0.82). I am wondering if there's something wrong with the preprocessing.

Thank you so much!

**Comment by snie2012** [comment]
Hi @VDCN12593, I am afraid I don't have the code anymore. Should have documented when I had it. Sorry about it.

**Comment by VDCN12593** [comment]
@snie2012  Thanks for the reply. Do you remember if it's a bug in their ontonotes processing code, or just some incompatibility with Flair models?

**Comment by snie2012** [comment]
@VDCN12593 If I recall correctly, it's just compatibility issues. Sorry that I cannot be more helpful.
