### ISSUE TITLE
Error when using allennlp fasttext

### ISSUE THREAD

**Issue by Cerebrock** [flairNLP/flair#621]
Error when downloading 'sp' fasttext spanish embeddings from google colab.

`OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/embeddings-v0.4/sp-wiki-fasttext-300d-1M.vectors.npy `

**Comment by alanakbik** [comment]
I think spanish is 'es'. Could you try this?
