### ISSUE TITLE
Documentation for FlairEmbedding training corpus format

### ISSUE THREAD

**Issue by andersfischernielsen** [flairNLP/flair#630]
I'm trying to train Flair embeddings as part of some Twitter NER research. I have been trying to follow Tutorial 9 from this repository, but I am missing an example of how the corpus training files need to be formatted. I currently have a decent corpus in the `.conll` format, but I'm unsure of what format Flair actually expects.   

Would it be possible to add a short subsection in Tutorial 9 of how the corpus needs to be formatted in order to train Flair embeddings?

**Comment by stefan-it** [comment]
@andersfischernielsen Just consider this data format:

```csv
1       Bare    bare    ADV
2       ikke    ikke    ADV
3       i       i       ADP
4       år      år      NOUN
5       ,       ,       PUNCT
6       advarer advare  VERB
7       lægerne læge    NOUN
```

To import it, you just need to specify what information is stored in each (tabulator) separated column.

```python
columns = {0: 'id', 1: 'text', 2: 'lemma', 3: 'pos'}
```

Then you can use the `read_column_data` method from ` NLPTaskDataFetcher` to import the dataset. `flair` would parse the dataset w.r.t the specified columns:

```python
sentences_train: List[Sentence] = NLPTaskDataFetcher.read_column_data(Path('train.conll'), column_name_map=columns)
sentences_dev: List[Sentence] = NLPTaskDataFetcher.read_column_data(Path('dev.conll'), column_name_map=columns)
sentences_test: List[Sentence] = NLPTaskDataFetcher.read_column_data(Path('test.conll'), column_name_map=columns)
```

Then build a corpus object:

```python
corpus: TaggedCorpus = TaggedCorpus(sentences_train, sentences_dev, sentences_test)
```

If you want to train on part-of-speech tags, just pass the name of column to the `make_tag_dictionary` method of the `corpus` object:

```python
tag_type = 'pos'

tag_dictionary = corpus.make_tag_dictionary(tag_type=tag_type)
```

`pos` corresponds to the `3: 'pos'` entry in your previously specified `columns` object.

Then you should be able to train on your own dataset.

You can of course use your own dataset format (often the `id` column is not needed...), as long as you correctly specify the format in a `columns` object :)

**Comment by andersfischernielsen** [comment]
Thanks! That's very helpful. :)

**Comment by niedakh** [comment]
The TaggedCorpus doesn't seem to be available anymore, how would I do the following line with the current version?

`corpus: TaggedCorpus = TaggedCorpus(sentences_train, sentences_dev, sentences_test)`

I've tried using the `Corpus` with List[Sentence] variables as train/dev/test and I'm getting:
```
>> corpus.make_tag_dictionary('ner')

AttributeError                            Traceback (most recent call last)
<ipython-input-265-d4ee103d0967> in <module>
----> 1 corpus.make_tag_dictionary('ner')

~/venv36/lib64/python3.6/site-packages/flair/data.py in make_tag_dictionary(self, tag_type)
    840         tag_dictionary.add_item("O")
    841         for sentence in self.get_all_sentences():
--> 842             for token in sentence.tokens:
    843                 tag_dictionary.add_item(token.get_tag(tag_type).value)
    844         tag_dictionary.add_item("<START>")

AttributeError: 'list' object has no attribute 'tokens'
```

Any hints please?

**Comment by stefan-it** [comment]
Hi @niedakh,

you can just use the following code - assuming that you have the same data format as in the second post (if not, you can easily adjust the `column` dictionary to your needs):

```python
from flair.data import Corpus
from flair.datasets import ColumnCorpus

# define columns
columns = {0: 'id', 1: 'token', 2: 'lemma', 3: 'pos'}

corpus: Corpus = ColumnCorpus(".", columns,
                              train_file='train.tsv',
                              test_file='test.tsv',
                              dev_file='dev.tsv')

print(corpus)
```

**Comment by alanakbik** [comment]
Hello @niedakh - if you have lists of `Sentence` objects and want to create a `Corpus` you can also do it like this:

```python
from flair.data import Sentence, Corpus
from flair.datasets import SentenceDataset

# your Sentence objects in three lists for train, dev, test
train = [Sentence('I love Berlin'), Sentence('Yes')]
dev = [Sentence('This is Dev')]
test = [Sentence('This is Test')]

# create Dataset objects
train_dataset = SentenceDataset(train)
dev_dataset = SentenceDataset(dev)
test_dataset = SentenceDataset(test)

# make a Corpus object
corpus = Corpus(train_dataset, dev_dataset, test_dataset)

print(corpus)

```

**Comment by BernierCR** [comment]
Hello @alanakbik . I tried to do this, but I got an error. 

Traceback (most recent call last):
  File "src/main.py", line 2, in <module>
    from flair.datasets import SentenceDataset
ImportError: cannot import name 'SentenceDataset'

This is weird, that class exists.

**Comment by stefan-it** [comment]
@BernierCR are you using the latest `flair` version from `master` branch (can be installed via `pip3 install git+https://github.com/zalandoresearch/flair.git`), because the `SentenceDataset`  is relatively new and was not available in the tagged and release *0.4.2* version of `flair`.

**Comment by alanakbik** [comment]
Ah oops yes sorry forgot to mention this. I think we'll do another incremental release soon (v 0.4.2) since so much has changed already. We have a few bigger PRs coming up after which we'll release the next version.

**Comment by BernierCR** [comment]
This still isn't working for me. Now I'm trying to import CSVClassificationCorpus, and it can't find it.

**Comment by xijianlim** [comment]
Im having an error pop up when installing via the git clone method:

prefix /private/var/folders/dc/g_60gjvd3v3_y2k53d79dphh0000gn/T/pip-build-env-tc953p56/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel" failed with error code 1 in None

I am installing this in  virtual environment though.
