### ISSUE TITLE
Use pre-trained model without Internet connection

### ISSUE THREAD

**Issue by zhh210** [flairNLP/flair#651]
My network admin blocked any connection to aws so downloading pre-trained embeddings/models will fail due to network error. Is it possible to let flair point to the local directory where the embeddings/models were downloaded? Thanks.

**Comment by alanakbik** [comment]
Hello @zhh210 - yes, you can pass the full model path to initialize most embeddings and taggers. For instance, if you have a tagging model downloaded to 'home/taggers/tagger.pt', you can initialize a SequenceTagger like this: 

```python
tagger = SequenceTagger.load_from_file('home/taggers/tagger.pt')
```

If you want to initialize embeddings with downloaded model, you can do this by passing the full path to the default constructor, e.g.: 

```python
FlairEmbeddings('path/to/downloaded/model.pt')
```

**Comment by zhh210** [comment]
The example I was trying to use is glove. The download from is failing to connect aws (alan-nlp/resources/embeddings/glove.gensim) so I created copy in my local folder and in python when I was loading:
`WordEmbeddings('/mydir/glove.gensim.vectors.npy')`

It got an error saying:

> UnpicklingError: STACK_GLOBAL requires str.

Similary when I point BytePairEmbeddings to a local folder containing en.wiki.bpe.vs100000.model, it gives error of:

> Unknown language identifier

**Comment by alanakbik** [comment]
Hi @zhh210 can you try loading with `WordEmbeddings('/mydir/glove.gensim')` instead?

**Comment by TorusHHH** [comment]
@zhh210 老哥，需要下载两个文件，一个是glove.gensim.vectors.npy，一个是glove.gensim，然后放在同意目录下，然后用WordEmbeddings('/mydir/glove.gensim.vectors.npy')就行。

**Comment by zwacm** [comment]
你好，@TorusHHH 这两个 glove.gensim.vectors.npy，和glove.gensim在哪里可以下载？

**Comment by builtfordeve** [comment]
@TorusHHH 同问，哪里才能下载到glove.gensim和glove.gensim.vectors.npy这两个文件啊？

**Comment by Carolyn95** [comment]
> 你好，@TorusHHH 这两个 glove.gensim.vectors.npy，和glove.gensim在哪里可以下载？可否给个链接

可以用一台可以access internet的电脑，用flair自动下载好了然后从`$HOME/.flair/embeddings`中复制过去。
