### ISSUE TITLE
Nested Named Entity Recognition Training Corpus

### ISSUE THREAD

**Issue by Amphagory** [flairNLP/flair#662]
Can I train Flair to predict nested named entity recognition?

If yes, how would the training corpus look like?

i.e. Alex Tam is going to Los Angele

an example of an IOB for this would be,

Alex B-PER
Tam I-PER
is O
going O
to O
Los B-LOC
Angeles I-LOC

What happens if we wanted label the two words "Alex Tam" with NAME or "Los Angeles" with CITY, wonder how to label the training data?

**Comment by stefan-it** [comment]
Hi @Amphagory I would be possible if you annotate outer and inner spans of your named entities. This was done e.g. for the GermEval [shared task](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxnZXJtZXZhbDIwMTRuZXJ8Z3g6OTg5Y2QwMGUyYmI5MGRk) (see table 3 for an example format). 

With `flair` you must then train two classifiers: one classifier for outer and one classifier for the inner spans :)
