### ISSUE TITLE
How to add FLAIR embeddings for finetuning to ANY Pytorch model?

### ISSUE THREAD

**Issue by JoaoLages** [flairNLP/flair#674]
I want to add FLAIR embeddings to my custom model, instead of using this package's trainer API (`ModelTrainer`). Am I able to load FLAIR's embeddings and backpropagate along with other Pytorch weights?

**Comment by alanakbik** [comment]
Hello @JoaoLages yes, the token and document embeddings are standard PyTorch tensors so you can use them in other architectures.

**Comment by JoaoLages** [comment]
The question is, if I am able make `FlairEmbeddings` or any other layer like `StackedEmbeddings`trainable, so that I can finetune it

**Comment by upmangaurav** [comment]
@JoaoLages : You can use the trained embeddings on some sample sentence-list like this:

    n = token.embedding.size()[0]   ##eg 400 for glove
    s = torch.zeros(0,n)
    for i in tqdm(range(len(someList))):
        # retrieve the text sentence
        sentence = Sentence(someList[i]['Sent_1'])
        # embed the sentences with our document embedding
        document_embeddings.embed(sentence)
        # Adding Document embeddings to list #
        s = torch.cat((s, sentence.view(-1,n)),0)

Now, S.numpy() is the input to any of your standard ML model.

Further, I wanted to quickly ask @alanakbik without possibly raising another ticket? :
Would it be possible to save the finetuned **DocumentRNNEmbeddings** embeddings from one system to another?
I see no default caching option but I want to be able to save them for later using without needing to retune them.

**Comment by JoaoLages** [comment]
That does not answer my question. I don't want to only 'use the trained embeddings'. I want to **update the character embeddings + LSTM weights** of FLAIR while training everything with my Pytorch model, end to end.

**Comment by alanakbik** [comment]
This feature was added a while back.
