### ISSUE TITLE
transformer models for language model training and tag prediction instead of LSTM's

### ISSUE THREAD

**Issue by mittalsuraj18** [flairNLP/flair#68]
I recently read the generative pretraining paper of openAI.
According to the benchmarks, fine-tuning the openAI model on a custom dataset takes a very less amount of time compared to a LSTM based approach.
Also the model has shown to improve SOTA in a lot of tasks.
So I was wondering if it is possible to replace the pipeline by a transformer based model implemented by OpenAI.

**Comment by alanakbik** [comment]
Great idea - we've been discussing this internally and really want to try it out, and compare the two approaches! Any help / pointers are appreciated :)

**Comment by mittalsuraj18** [comment]
```https://github.com/huggingface/pytorch-openai-transformer-lm``` has an implementation of transformer model in Pytorch and scripts to load openai transformer weights.
Will have a look at it this weekend and check out the complexity of the implementation.

**Comment by alanakbik** [comment]
Great, thanks! Perhaps this code can be the basis of new transformer-based `LanguageModel` and `LanguageModelTrainer` classes!

**Comment by stefan-it** [comment]
A deep Transformer model achieves state-of-the-art results also in language modeling now, see [this](https://arxiv.org/pdf/1808.04444.pdf) paper. So I think integrating such an architecture in `flair` would be awesome :heart: 

But don't look at the evaluation section in the paper mentioned above ;) I took more than 7 days on a single Cloud TPU :scream:

**Comment by tabergma** [comment]
Small update: We are going to add the BERT embeddings (see https://github.com/zalandoresearch/flair/issues/251) in the next release to flair. They are based on transformers.

We are still thinking of adding our own transformer model at one point. But not in the near future.

**Comment by mittalsuraj18** [comment]
alright 👍

**Comment by stefan-it** [comment]
@alanakbik and @tabergma : Here's another great paper about a Transformer-based LM: 

[Transformer-XL: Attentive Language Models Beyond a Fixed-Length Context](https://arxiv.org/abs/1901.02860)

-> Yesterday they provided both a TensorFlow and PyTorch implementation of the model. I'm going to play with the implementation now, maybe I find a way to get embeddings for a sentence (like it is done with FlairEmbeddings).

**Comment by alanakbik** [comment]
Wow this looks really interesting!

**Comment by stefan-it** [comment]
Two PR's from the `pytorch-pretrained-BERT` repositoy are very interesting:

* [OpenAI GPT support](https://github.com/huggingface/pytorch-pretrained-BERT/pull/183)
* [Transformer-XL support](https://github.com/huggingface/pytorch-pretrained-BERT/pull/200)

Once they're merged I would like to add them to `flair` :)

Training a Transformer-XL model is possible, but on one GPU I had to use a smaller Transformer model (but I'm currently do some experiments with it...)

**Comment by alanakbik** [comment]
Yeah that would be great! :) Also, we'd be very interested to hear about your experiments with Transformer-XL!

**Comment by stefan-it** [comment]
Version *0.5.0* is out now: https://github.com/huggingface/pytorch-pretrained-BERT/releases/tag/v0.5.0

I'll check the integration oft OpenAI GPT and the Transformer-XL now :)

**Comment by alanakbik** [comment]
Wow awesome!

**Comment by gccome** [comment]
Wow this is awesome. Really look forward to transformer-based models and fine-tuning-based models.

**Comment by stefan-it** [comment]
Two current caveats:

* OpenAI GPT needs two libraries to be installed (not covered by `pytorch-pretrained-BERT`s dependency management): `ftfy` and `spacy`. For `spacy` you also need to manually install the English model with: `python -m spacy download en`. Then it works fine, I was able to get embeddings of a sentence
* Transformer-XL: I wasn't able to get proper embeddings, a "nan" tensor was returned. But I opened an issue, see [here](https://github.com/huggingface/pytorch-pretrained-BERT/issues/270) :)

**Comment by alanakbik** [comment]
Ah thanks for the update - do you know why OpenAI requires spacy, and why the English models? Only for tokenization?

**Comment by thomwolf** [comment]
Hi guys, I've made some update and a new release for these stuff: https://github.com/huggingface/pytorch-pretrained-BERT/releases/tag/v0.5.1

Keep up with the good work on flair.

**Comment by stefan-it** [comment]
I've implemented an early draft of `TransformerXLEmbeddings` + I'm currently training on CoNLL 2003 dataset. I'll report the results here soon :)

**Comment by stefan-it** [comment]
Bzw: Second version of GPT is out: https://github.com/openai/gpt-2/blob/master/README.md

**Comment by gccome** [comment]
@stefan-it In my understanding, TransformerXLEmbeddings supports varied sentences length, so it won't have out-of-index issue from BertEmbedding, because Bert has fixed length of 512. Is it correct?

**Comment by alanakbik** [comment]
@stefan-it @thomwolf wow that's great - really looking forward to seeing this in action! And very interested to hear how well it does on CoNLL 03 and other tasks.

**Comment by stefan-it** [comment]
Here's another Transformer-based architecture, that uses a new approach for pretraining (cloze-style token reconstruction task is embedded during training):

https://arxiv.org/abs/1903.07785

It also achieves new SOTA on CoNLL-2003 NER: 93.5% (compared to flair: 93.18%)

**Comment by alanakbik** [comment]
Very impressive results - look forward to taking a closer look at this!

**Comment by stefan-it** [comment]
One major drawback is the ridiculous amount of training data. Unfortunately, there's currently no implementation/model available.

**Comment by stefan-it** [comment]
I just asked @michaelauli if they plan to release the code and model :)
