### ISSUE TITLE
Highlighting NER tags

### ISSUE THREAD

**Issue by azeevg** [flairNLP/flair#680]
Is it possible to generate HTML file where all found named entities would be highlighted and labeled (PERSON, ORG, etc)?

**Comment by alanakbik** [comment]
That would be a cool feature, but we do not have it yet. We always welcome contributions, so if you're interested in implementing this, please do :)

**Comment by xraycat123** [comment]
Maybe you can use displacy in spacy for this?

```from IPython.core.display import display, HTML
from spacy.strings import StringStore
from spacy.tokenizer import Tokenizer
nlp = spacy.blank('en') 

nlp.tokenizer = Tokenizer(nlp.vocab)
stringstore = StringStore([u'DISORDER'])  # Change DIS to ORG, PER etc.
disorder_hash = stringstore[u'DISORDER']
nlp.vocab.strings.add('DISORDER')

# Specify the color
options = {"ents": ["DISORDER"], "colors":  {"DISORDER": "yellow"}}

# predict NER tags
sentence = Sentence("patient has sinus rhythm. old inferior myocardial infarction is observed . furthermore , occasional ventricular premature beats is seen . compared to the previous tracing of _ date ectopy is absent . ")
tagger.predict(sentence)


# Spacy preserve double spaces
one_sentence = nlp(' '.join(sentence.to_original_text().split()))


for span in sentence.get_spans('ner'): 
    idx = [token.idx for token in span.tokens]
    span = Span(one_sentence, idx[0]-1, idx[-1], label=disorder_hash)  # Create a span in Spacy
    one_sentence.ents = list(one_sentence.ents) + [span]  # add span to doc.ents 
    
spacy.displacy.render(one_sentence, style='ent',options=options) # Use render in notebooks, or serve otherwise
```

    
![image](https://user-images.githubusercontent.com/15103668/56759661-bff9ff00-6799-11e9-8c97-355f5b5f4c43.png)

**Comment by alanakbik** [comment]
@xraycat123 this is really cool - thanks for posting this!

**Comment by Barath19** [comment]
Any progress on this feature?

**Comment by alanakbik** [comment]
Not from our side - we're currently prioritizing other features / enhancements / bug fixes over visualization options. But we would welcome contributions :)

**Comment by alanakbik** [comment]
PR merged a while back

**Comment by shern2** [comment]
Spacy's `displacy` supports manual inputs now.
Here's a snippet to use it

```py
from spacy import displacy
from flair.data import Sentence
from flair.models import SequenceTagger

tagger = SequenceTagger.load('ner')

text = "patient has sinus rhythm. old inferior myocardial infarction is observed . furthermore , occasional ventricular premature beats is seen . compared to the previous tracing of _ date ectopy is absent . "
sentece = Sentence(text)

tagger.predict(sentence)

dic_ents = {
    "text": text,
    "ents": [
        {"start": ent.start_position, "end": ent.end_position, "label": ent.labels[0].value}
            for ent in sentence.get_spans('ner')
    ],
    "title": None,
}

displacy.render(dic_ents, manual=True, style="ent")
```

**Comment by snehilsanyal** [comment]
Hey, I am still unable to find a specific tool just for the visualization of NER tags; the merged example only contains it for 4 classes, it seems. It would be really helpful for developers to have visualizers for different use cases.
In the case of Spacy, there is displaCy, but I don't want to import Spacy's visualizers to work with Flair.

**Comment by helpmefindaname** [comment]
@snehilsanyal it doesn't only support the 18 class ontonotes shema, but also any other. All you have to do is pass a `<label>: <color_code>` dict with the config you want as the `colors` parameter of `render_ner_html`
