### ISSUE TITLE
Cache miss for char-LM embedding will cause entire cache to be ignored

### ISSUE THREAD

**Issue by mattilyra** [flairNLP/flair#692]
My reading of this line (https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1106) is that the entire char-LM cache is ignored if one sentence (in a batch?) is not found. As that the char-LM embeddings are fairly costly to compute this seems a little aggressive to me, shouldn't we rather just set the flag to `False` and continue finding the embeddings for the remaining sentences.

Hypothetically if I happened to be unlucky and pass in a list of 10k sentences where only the first one wasn't in the cache, all of the remaining 9999 would also be recomputed?

**Comment by alanakbik** [comment]
A mini-batch size of 10k might be a bit high :) Generally we expect mini-batch sizes to be more around 32 or so, but still you are right that this triggers a recalculation of embeddings if there is as little as one unknown sentence in the mini batch. Perhaps it is a good idea to subselect only the unlabeled sentences and only add embeddings to those.
