### ISSUE TITLE
What is the best way to train character level seq2seq models in flair?

### ISSUE THREAD

**Issue by zeeshansayyed** [flairNLP/flair#708]
What is the best way to train character level seq2seq models using flair? In such a model, every character will be mapped to some class. For instance:

`"What are you doing" --> "0001 001 100 00001"`

From the documentation, I understand that a sentence is made of multiple tokens where a token represents a word. Flair allows us to associate a tag or multiple tags with a token. But what I am describing above is akin to being able to associate tags not only at the word level but at the character level.

Since flair LM works at the character level, I am hoping there would be an easy way to do this with flair. If it is not possible, I would like to write that code myself, So any pointers in that direction will also be appreciated.

Thank you for creating this awesome library.

**Comment by alanakbik** [comment]
Hello @zeeshansayyed that's an interesting question - you're right that the `Sentence` object currently is assumed to be composed of Tokens, i.e. words., but you could take a look at the `LanguageModel` code to get started. Perhaps you could build a layer directly on top of the LanguageModel class, which would have the advantage that you could use the pre-trained language models. 

For model training, you could also have a look at the `ModelTrainer` and `flair.nn.Model` classes currently in master branch (not yet released). The idea is that by implementing the `flair.nn.Model` interface, you can directly use the `ModelTrainer` to train a seq2seq problem. Though this is still experimental and we expect more changes to come to this interface. 

Let us know if you have more questions - I'd be very interested to see seq2seq in Flair!

**Comment by zeeshansayyed** [comment]
HI @alanakbik 
I have started working on this. I will let you know how I achieve something. I had one more question regarding this issue. To have any character level seq2seq, I would need access to the embeddings generated for the individual characters. In the tutorial, it is only shown how to access embeddings for individual tokens (which again are words). How can I do this?

**Comment by alanakbik** [comment]
Hello @zeeshansayyed you could take a look at how the `FlairEmbeddings` takes the hidden states from the `LanguageModel` to get embeddings. It calls the method `get_representation()`, here: 

https://github.com/zalandoresearch/flair/blob/b2230ecafecbcedbd9496795625a4cd0f932f397/flair/embeddings.py#L1150

`get_representation()` of a `LanguageModel` takes as input one string (or a list/batch of strings) and outputs all hidden states for all character positions in all strings.

**Comment by zeeshansayyed** [comment]
Thank you @alanakbik I think these are good starter points.

**Comment by abeermohamed1** [comment]
Any update on adding character level

**Comment by zeeshansayyed** [comment]
I chose to go with Transformer models instead of continuing this idea. Sorry.

**Comment by abeermohamed1** [comment]
> I chose to go with Transformer models instead of continuing this idea. Sorry.

Hi @zeeshansayyed thank you for your reply.
could you please le me know how
