### ISSUE TITLE
Get probability of a single word

### ISSUE THREAD

**Issue by styfeng** [flairNLP/flair#710]
Hi there. I am wondering what is the easiest and quickest way to get the probability of a word/token for a given language model (e.g. news-forward) using Flair. For example the probability of the word "hello". Thanks.

**Comment by alejandrojcastaneira** [comment]
I'm also interested on this subject, I'm working on a use case when I would like construct coherent sentences, and to measure the coherence of a simple sentence we could simply use its language model probability as the  product of probabilities of each word given the entire sentence.

It would be a way to express the probability for each word inside a sentence as a real value, using the Flair Language Models?
