### ISSUE TITLE
Perplexity calculation error for single character words ("a", "I")

### ISSUE THREAD

**Issue by styfeng** [flairNLP/flair#716]
For example, if I try to calculate the perplexity of a word like "a" or "I", I get the following error:

"Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAType instead"

However, this works for any words greater than one character in length. I am assuming this is because the perplexity requires at least 2 characters to be calculated? If somebody could confirm or give me a hint to fixing this, that would be awesome.

**Comment by alanakbik** [comment]
Thanks for reporting this. I can reproduce the error with: 

```python
lm = FlairEmbeddings("news-forward").lm

perplexity = lm.calculate_perplexity('a')
```

I'll add a bug label to this issue.
