### ISSUE TITLE
LM using flair embeddings with my own arabic corpus

### ISSUE THREAD

**Issue by fatimabs** [flairNLP/flair#717]
A clear and concise description of what you want to know.

**Comment by fatimabs** [comment]
Hi every body

can some one help me to generate a Language model for Arabic using Flair, by giving the different steps ?

**Comment by alanakbik** [comment]
Hello @fatimabs have a look at issue #179 which gives an overview of all the steps. Also we have a [tutorial](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_9_TRAINING_LM_EMBEDDINGS.md) online that you can check out that illustrates how to do this.
