### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by fatimabs** [flairNLP/flair#721]
i'm trying to train a LM with my arabic corpus but i have a problem with :

corpus = TextCorpus(Path('/content/drive/My Drive/arabic_corpus'),
                    dictionary,
                    is_forward_lm,
                    random_case_flip=False,
                    character_level=True)

UnicodeDecodeError                        Traceback (most recent call last)

<ipython-input-31-adf1fb23dd28> in <module>()
      6                     is_forward_lm,
      7                     random_case_flip=False,
----> 8                     character_level=True)

3 frames

/usr/lib/python3.6/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by alanakbik** [comment]
Hi @fatimabs could you provide a very small sample file to reproduce this error?

**Comment by fatimabs** [comment]
file from my Arabic corpus ?

**Comment by abeermohamed1** [comment]
Hi @alanakbik  and @fatimabs I have the same error when running the below embedding for Arabic. any update, please

WordEmbeddings(data_folder+'/model.bin'),

**Comment by SystemErrorWang** [comment]
got the same problem when trying to decode german:
```corpus: Corpus = CONLL_03_GERMAN(base_path='resources')```

**Comment by alanakbik** [comment]
@SystemErrorWang strange, maybe you have the corpus in a different encoding than UTF-8?
