### ISSUE TITLE
message  while loading the various embeddings in flair

### ISSUE THREAD

**Issue by leandadearaujo** [flairNLP/flair#728]
message while loading the various embeddings 2019-05-15 12:46:53,038 this function is deprecated, use smart_open.open instead

**Comment by Juanses** [comment]
Same here, with flair version 0.4.1

**Comment by alanakbik** [comment]
This seems to stem from gensim, see [this issue](https://github.com/RaRe-Technologies/smart_open/issues/319).

**Comment by leandadearaujo** [comment]
Hi Alan

Thank for the reply the  good work you have been doing a big fan ,

Actually i am able to load the model and but when i stack the embeddings
(elmo, word2vec, DocumentPoolEmbeddings) in flair and find the cosine
similarity i get a very bad result



can you please help me

Thank you
Leanda

**Comment by alanakbik** [comment]
Hello @leandadearaujo sorry for the late reply (been busy preparing/attending NAACL). Could you give more details on what you want to do with cosine distance and what you are comparing?

**Comment by leandadearaujo** [comment]
Actually I am comparing the two sentences if they are similar in meaning

so i split the entire doc in sentences and compare the reference sentence
with all the sentences in the doc ,so when i find the cosine similarity it
gives high cosine score for  other sentence, than the sentence that it is
actually similar in meaning to

Thank You
Leanda

**Comment by alanakbik** [comment]
Ah I see! So generally using simple cosine over pooled word embeddings in problematic for measuring the similarity of sentences. But there exist good unsupervised approaches to do this. For instance, there was a good paper on NAACL about this called [Alignment over Heterogeneous Embeddings for Question Answering](https://www.aclweb.org/anthology/N19-1274) that might be worth checking out. 

Also you could check out other approaches based on Word Mover's Distance. We don't yet implement these approaches in Flair, but this is something we'd like to add.

**Comment by leandadearaujo** [comment]
Thank you so much for quick response

Thank you for the knowledge
Will surely try it

Thank you
Leanda De Araujo
