### ISSUE TITLE
Classifying with cosine distance

### ISSUE THREAD

**Issue by timnoah** [flairNLP/flair#729]
Hi there,

I am building a text classifier to rate the topic of user comments.
In total there are 11 labels and a comment can have multiple topics at the same time.
Since we are starting from scratch, we don't have any data to train/test a model.

Therefore, my idea was to calculate the cosine distance between the WordVec of each label and the DocVec of the comment and pick whatever label has the biggest similarity, or respectively the labels which have a higher score than a certain threshold (Multi-Label Classification).

However, I am assuming that instead of taking the WordVec of the label a description of the label would be more precise. Now I am wondering how this description should look like.
Shall it be written like a dictionary entry? Shall it be a human-like description? Shall it be rather short (couple of words) or rather long (multiple sentences)? 

I'd be very grateful for any kind of feedback/advice!
Best, Noah. :)

**Comment by san7988** [comment]
Hi,

I believe, wordVec of the label will have the same effect as the wordVec of the label description.

The mapping of label to label description will always be constant. So, irrespective of you choose set of encoded labels or set of encoded label description, they should end up affecting the model in a same way, me think.

Maybe clustering the comment and updating the clusters as and when a new comment is added to the corpus would be a good way to segregate the data. The clusters can then be mapped to the label/label description.

**Comment by timnoah** [comment]
Hey San,

thanks for your response. I'll give you an example to empathise my issue:

One label is called "product", which refers to a user comment about our product.
From my understanding the WordVec of "product" is quite generic, since this can be almost anything in real world. However in our model this refers to our mobile application, the usability, layout, ...

So instead of having a WordVec "product" (generic), we have a DocVec with the description of product (specific). Something like: "Comments about the usability, layout, look and feel of the mobile application".

Hence, if a user then comments: "the layout of the app is great". The cosine distance of the comment and label description shall be high. Therefore it is not constant and would significantly differ from the cosine distance with the WordVec "product"..  right?

Clustering the comments would be a good starting point to find new, distinct labels for classification.. Thank you! :)

How can I change the issue label? 

Best, Noah

**Comment by san7988** [comment]
Agreed, cosine distance of "label description" and "comment" will not be a constant. But that distance being high or low may not be a good indicator of both them having a positive relationship i.e. the corresponding "comment" indeed belongs to the class of whose description was taken into account to get the cosine distance. I say this assuming, the cosine distance calculation was to segregate the user comments into different classes.
Sorry if my comments are confusing.

Regards

**Comment by timnoah** [comment]
Sorry, but I don't get your point. 

I get 11 cosine distances and select the ones which are above the threshold. See below an example. 
Please note that the labels correspond to the key value in the dictionary.

Coming back to my original question, I am wondering if this is a valid approach and if yes what is recommended to use for the label description? Keeping in mind that this approach is only considered since there is no training data available to train the model properly.

![Screenshot 2019-05-16 at 16 20 02](https://user-images.githubusercontent.com/50014243/57861620-34ebb200-77f7-11e9-9337-a9e8e6c91080.png)

**Comment by timnoah** [comment]
I tried to explain my approach in the following [Blog](https://medium.com/@medecindirect/unsupervised-text-classification-695392c6fac7), in case this is more understandable

**Comment by alanakbik** [comment]
Hello @timnoah cool blog post! If I understand correctly, you are doing the cosine distance between the document vectors computed for the comment and each of the class descriptions. One drawback is that the document vector is a simple average of the word embeddings, i.e. the word embeddings are not combined in a 'smart' way (unimportant words weigh as heavily as important words). 

You could look into other unsupervised approaches for measuring the similarity of text based on word embeddings. For instance, there was a good paper at NAACL on this: [Alignment over Heterogeneous Embeddings for Question Answering](https://www.aclweb.org/anthology/N19-1274). Also you could check out other approaches based on Word Mover's Distance. We don't yet implement these approaches in Flair, but this is something we'd like to add.
