### ISSUE TITLE
German Review corpus

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#73]
Hi :)

this is not directly related to `flair`, but I have a question/suggestion for a customer review corpus (comparable to the Amazon Review corpus) which is based on German customer reviews from the Zalando site?

Such a review corpus could be a great resource for sentiment analysis/text classification in German and would encourage researchers to develop models, because it would be the first large corpus for German in this domain. A kind of public leaderboard (like the [SQuAD](https://rajpurkar.github.io/SQuAD-explorer/) one) could also be introduced :)

What do you think about this idea and do you think it would be possible to build such a review corpus?

Thanks,

Stefan

**Comment by alanakbik** [comment]
I think this is really a great idea! We have a number of NLP projects currently running that - once completed - I could potentially see contributing tasks to a SQuaD-like setup for German (and other European languages). There are of course a number of practical/legal issues to keep in mind, so it might be a while to win approval and prepare data sets, but we will definitely keep this idea in mind as we develop the projects!
