### ISSUE TITLE
Why TP is always equal to TN in the final test?

### ISSUE THREAD

**Issue by honcharov-danylo** [flairNLP/flair#740]
Hi! I've seen that in the final test (evaluation of NER model after training) TP is always equal to the TN. Why does it happening? 
Thank you.

**Comment by ZouQunSheng** [comment]
I also encountered this problem, what is the reason?

**Comment by alipetiwala** [comment]
@stefan-it Even I have encountered the same thing for my case of a  very custom model. I had ignored it before assuming it to be a case of coincidence.

**Comment by alanakbik** [comment]
This is probably a bug in the way TNs are counted. We have a few open issues so will fix this hopefully soon!

**Comment by jantrienes** [comment]
I wonder how one would count TNs in an entity-level evaluation. They are essentially all possible entities which were not tagged. So I would argue that they are simply not defined. As NER systems are usually evaluated according to precision, recall, F1, the true negatives do not play a role.
