### ISSUE TITLE
scibert model embeddings in Flair

### ISSUE THREAD

**Issue by alipetiwala** [flairNLP/flair#744]
A pretrained BERT model for scientific texts is available here:
https://github.com/allenai/scibert

When will the Scibert embedding directly be supported in Flair?

**Comment by stefan-it** [comment]
As `flair` uses `pytorch-pretrained-BERT`, the `scibert` model can be used e.g. like:

```bash
$ cd /tmp
$ wget "https://s3-us-west-2.amazonaws.com/ai2-s2-research/scibert/pytorch_models/scibert_scivocab_uncased.tar" # Download recommended scibert model
$ tar -xf scibert_scivocab_uncased.tar
$ cd scibert_scivocab_uncased
$ tar -xzf weights.tar.gz
```

The the necessary  files are located under `/tmp/scibert_scivocab_uncased`:

* `vocab.txt` - includes BPE like vocab
* `bert_config.json` - BERT model configuration
* `pytorch_model.bin` - PyTorch BERT model

After that you can easily use `scibert` in `flair`:

```python
from flair.data import Sentence
from flair.embeddings import BertEmbeddings
embeddings = BertEmbeddings(bert_model_or_path="/tmp/scibert_scivocab_uncased")
s = Sentence("An example sentence .")
```
