### ISSUE TITLE
Problem During Execution

### ISSUE THREAD

**Issue by nagrechachirag8** [flairNLP/flair#748]
corpus: TaggedCorpus = NLPTaskDataFetcher.load_corpus(NLPTask.IMDB)
After this there is no further execution.

![Screenshot from 2019-05-24 04-01-18](https://user-images.githubusercontent.com/50979813/58306808-67f6fc80-7e1a-11e9-924c-dd5724a714e3.png)

OS- Linux

**Comment by alanakbik** [comment]
Hello @nagrechachirag8 this is probably because our current method for reading data reads everything into memory. We just pushed a PR into the master branch that lets you train over classification datasets without loading into memory. 

If you can work on the master branch, you could try: 

```python
from flair.datasets import IMDB

# read corpus
corpus = IMDB()
```
