### ISSUE TITLE
expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by JBE777** [flairNLP/flair#763]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (e.g. which model did you train? what parameters did you use? etc.).

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS [e.g. iOS, Linux]:
 - Version [e.g. flair-0.3.2]:

**Additional context**

**Comment by alanakbik** [comment]
@JBE777 could you add more details on this bug to allow us to reproduce?
