### ISSUE TITLE
Embeddings dimension for translation

### ISSUE THREAD

**Issue by valentinmace** [flairNLP/flair#765]
I want to use Flair Embeddings in my NMT experiments

Following your tutorials, you recommend to use `Stacked Embeddings` from` news-forward`, `news-backward` and standard word embeddings like `glove`

It sounds promising but such Stacked Embeddings have a dimension of 4196 which is big for a Transformer model

Do you have any recommendations for that ? I will certainly try multiple approaches but any advice would be appreciated

Thanks a lot

**Comment by stefan-it** [comment]
Hi @valentinmace,

I think you could use the `news-forward-fast` and `news-backward-fast`  Flair Embeddings. These embeddings have the half size (of dimensions) compared to the "normal" `news-forward` embeddings. These would reduce the dimensionality :)

**Comment by valentinmace** [comment]
Hi @stefan-it 

As you suggested I will start using smaller embeddings like `news-forward-fast` and then try with bigger ones, possibly stacked

Do you have any preference regarding where I should post my results ?

**Comment by alanakbik** [comment]
Hi @valentinmace we'd be very interested to hear how embeddings / stacked embedding influence NMT, so if you could post your results here (in this thread) that would be great!

**Comment by Icyzrw** [comment]
I've tried to change the size of the embedding2nn layer from embedding_length*embedding_length to embedding_length*(embedding_length/2), and the result didn't change much in NER task.
