### ISSUE TITLE
Farsi

### ISSUE THREAD

**Issue by reza1615** [flairNLP/flair#772]
please have a unification for Farsi in some part of the code and documentation. it is referred as Persian and we should use 'PA' or 'pa' [here](https://github.com/zalandoresearch/flair/search?q=PERSIAN&unscoped_q=PERSIAN) and [here](https://github.com/zalandoresearch/flair/search?q=%22pa%22&unscoped_q=%22pa%22) in some parts it is 'fa'.
The official abbreviation for Farsi/Persian language is 'fa' like http://fa.wikipedia.org

**Comment by alanakbik** [comment]
Hello @reza1615 thanks for pointing this out - you're right the language code should be 'fa' everywhere. Should we refer to the language as Farsi or Persian throughout the documentation?

**Comment by reza1615** [comment]
@alanakbik Thank you for your reply.
Base on [ISO6391](http://id.loc.gov/vocabulary/iso639-1/fa.html) Language name is `Persian` and code is `fa`. In some sites they use `Persian/Farsi` for the language and `fa` for code

**Comment by alanakbik** [comment]
This was fixed a while back.
