### ISSUE TITLE
BPE Embeddings

### ISSUE THREAD

**Issue by valentinmace** [flairNLP/flair#779]
Hi

I want to test Flair (and also Bert and ELMo) embeddings for NMT.

I currently use SentencePiece to segment my corpus as it significantly provides best performances over other methods

I can easily load and generate embeddings with flair, using various models, but I doubt it will be relevant for words that have been segmented with SentencePiece

For exemple, a typical sentence in my corpus would be:

> ▁Re ads ▁an ▁entire ▁file ▁into ▁an ▁array ▁.

Do you have any recommendations ?

**Comment by bheinzerling** [comment]
You don't have to segment your corpus. Flair will do this for you:
https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_3_WORD_EMBEDDING.md#new-byte-pair-embeddings

**Comment by valentinmace** [comment]
When I use BytePairEmbeddings from your example and print them it doesn't seem to segment my corpus, exactly one vector is computed by word

How does it work exactly ?

Also, which embedding algorithm is behind BytePairEmbeddings ?

**Comment by bheinzerling** [comment]
When you embed a word with BytePairEmbeddings, the word first gets split into subwords. E.g.:

myxomatosis -> _my xo mato osis

Then we look up embeddings for each subword. This gives us 4 vectors.

Now things can get a bit complicated, depending on what you want to do.
In machine translation and other applications where word boundaries may not be that important, people just use these 4 vectors.

In tasks where words matter more, e.g. in sequence tagging with word-based gold annotations, we somehow have to condense these 4 vectors into one. There is no single, best method to this, but people have tried a couple of ways:

The most simple way is to arbitrarily pick one, e.g. the first one, but this may lose some information.
Another way is to use a composition function, e.g. addition or an RNN, to combine these 4 vectors.
Flair uses yet another method: it concatenates the first and last vector, which is quite simple and works well.


And about the embedding algorithm: It's GloVe

**Comment by valentinmace** [comment]
Thanks for your complete answer

I already have a bpe model (using SentencePiece) which works well.

So for my translation task I just apply the bpe segmentation to my corpus and then feed it into my transformer, I let my transformer fine-tune embeddings.

What I wanted to do is to provide my model pretrained embeddings obtained with flair algorithm. But if I understand correctly flair embeddings are obtained regarding a context and if I use flair on my vocabulary which looks like:
```
▁,
▁the
▁.
▁of
▁and
ist
id
```
I won't get any relevant embeddings since 1) for each word there is no context, 2) words often contain that odd '▁' generated by BPE

**Comment by alanakbik** [comment]
Hello @valentinmace if I understand correctly, you would want to do something like this: 

```python
# init sentence with subwords already detected
sentence = Sentence('▁Re ads ▁an ▁entire ▁file')

# embed sentence with your favorite embeddings
embeddings.embed(sentence)

# go through each token (which now is a subword in this context)
for subword in sentence:
    print(subword)
   # print embedding vector
    print(subword.embedding)
```

which would print: 

```console
Token: 1 ▁Re
tensor([-0.0005,  0.0003 .... ])
Token: 2 ads
tensor([0.0020, 0.0001 .... ])
Token: 3 ▁a
tensor([1.8234e-03, 3.9095e-05 .... ])
Token: 4 ▁file
tensor([-6.1176e-04, -5.4184e-06 .... ])
```

where each `subword.embedding` should make sense. Is that correct?

**Comment by valentinmace** [comment]
Hello @alanakbik,

I want to do something similar to what you described, but the difference is that my file is a vocabulary file and has one word (or subword) per line

So there is no context for each word (or subword), my guess is that I will get an embedding but it won't be really relevant since it is obtained without context

Am I right or maybe I can still benefit for Flair's embeddings ?

**Comment by djstrong** [comment]
You are right.
