### ISSUE TITLE
Method to filter words after POS Tagging

### ISSUE THREAD

**Issue by amit8121** [flairNLP/flair#785]
Once POS tagging is performed, I want to be able to filter out those words from each sentence which has label for specific POS tag.

```
Ex:  say if sentence 'I live here' is tagged as , 

NNP-span [1]: "I" 
NNP-span [2]: "live" 
PRP$-span [3]: "here" 

```

I want to retrieve only those words who has tags 'NNP-span' ( from the above example ).

I have a list of sentences, `[ 'Sentence 1',  'Sentence 2',  'Sentence 3' .... ],` I want to iterate over each tagged sentence and eliminate certain words with certain POS tags.

 I tried looking in to `_flair.data.Span_` class but couldn't find relevant details. I also tried to use _to_dict_ method, but as I have list of sentences the output of `_Sequence Tagger_` came out to be list itself, which doesn't have to_dict option. 

Any help is appreciated.

Thanks

**Comment by alanakbik** [comment]
Hello @amit8121 you can build such a filter using the Token object fields. 

For instance: 

```python
sentence = Sentence('I live here')

pos: SequenceTagger = SequenceTagger.load('pos')

pos.predict(sentence)

# iterate over tokens (words) in the sentence
for token in sentence:
    # print the token object
    print(token)

    # get the predicted pos tag and print it
    pos_tag = token.get_tag('pos').value
    print(pos_tag)
```

This will print: 
```console
Token: 1 I
PRP
Token: 2 live
VBP
Token: 3 here
RB
```

Now, you could add a filter for the desired POS tag. Let's say you want to filter for 'VBP':

```python
# go through tokens (words) in sentence
for token in sentence:

    # if the predicted tag is VBP
    if token.get_tag('pos').value == 'VBP':
        # print the token object
        print(token)
```

Or if you want everything in one line that returns a list of all Tokens with this tag: 

```python
verbs = [token for token in sentence if token.get_tag('pos').value == 'VBP']
print(verbs)
```

Hope this helps!
