### ISSUE TITLE
Differences between BERT's paper and Flair's implementation

### ISSUE THREAD

**Issue by polars05** [flairNLP/flair#801]
In the BERT paper, single-sentence classification is done by using the embedding produced at the [CLS] token (i.e. the first token in a sentence); however it seems like Flair's implementation uses pooling / RNN / LSTM to combine the embeddings produced at each token in the sentence and then classify the sentence based on that - is my understanding correct? If so, why did Flair choose to do it this way?

Also, BERT uses BPE tokenization which converts the sentence "jim henson was a puppeteer." into {'[CLS]', 'jim', 'henson', 'was', 'a', 'puppet', '##eer', '.', '[SEP]'}. However, Flair's tokenization is via Segtok which gives {"jim', 'henson', 'was', 'a', 'puppeteer', '.'}; how does Flair produce the embedding for "puppeteer" in this case considering that it is technically made up of two tokens "puppet" and "##eer"?

**Comment by stefan-it** [comment]
Hi @polars05 

to answer your second question:

leading `[CLS]` and trailing `[SEP]` tokens are added before tokenization:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1389

`pytorch-pretrained-bert` is used to tokenize `puppeteer` into subwords:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1380

After that these subwords are converted to ids:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1380

which can be passed to the BERT model:

https://github.com/zalandoresearch/flair/blob/master/flair/embeddings.py#L1451

:)

**Comment by polars05** [comment]
Thanks for the reply! Also, is there a way to train a text classifier using BERT embeddings? When I pass the BERT embeddings into the document embedder, it throws an error saying that BERT is not iterable.

**Comment by alanakbik** [comment]
You need to pass a list of embeddings to DocumentEmbeddings, so you can put the embedding in a list containing just one item and it should work.

(For convenience, we'll add the possibility to pass just a single embedding in a future PR)
