### ISSUE TITLE
use BERT embedding in Flair to replicate CONLL03 NER result

### ISSUE THREAD

**Issue by zhaoxy92** [flairNLP/flair#805]
Has anyone had used BERT embedding provided in Flair to do NER task on Conll 2003 data. I tried to do this, but the result (overall F1) I got was only around 0.88. I'm wondering, if anyone has successfully done this, could you share  how to did that?

Note: I didn't use any RNN model on top of the embedding because that's how it was in the BERT paper. So, just the BERT embedding with a fully connected net on top.

**Comment by arunbg** [comment]
Haven't tried reproducing the results, but [this repo](https://github.com/kamalkraj/BERT-NER) appears to do so with the huggingface Pytorch library which is what Flair uses too.

**Comment by stefan-it** [comment]
@zhaoxy92 Just have a look at this issue: #308.

I made some experiments with BERT on CoNLL a few months ago only one run, using the default Flair parameters (`torch.cat` of the last 4 layers):

| Model | F-score
| -------- | ---------
| BERT (base-uncased) | 90.65% 
| BERT (base-cased) | 83.68% 
| BERT (large-uncased) | 90.06%
