### ISSUE TITLE
How are discontinuous annotations and overlapping annotations handled

### ISSUE THREAD

**Issue by pzalex** [flairNLP/flair#824]
How are multi-token terms handled in Flair sequence labeling models, in particular, the ones represented in text with discontinuous and with overlapping tokens? Here is one example. In phrase "potassium and magnesium replacement", I want the model to identify 2 terms "potassium replacement" and "magnesium replacement". Term "potassium replacement" is discontinuous and interrupted with tokens "and magnesium", and the token "replacement" although appears in the text once, is a part of both terms.
The questions I wanted to ask are:
 - Can Flair recognize a multi-token term that is marked with 'B-' and 'I-' prefix in CoNLL corpus file as a single term? 
"magnesium B-CONC1
replacement I-CONC1"
 - Does it recognize terms that are composed by discontinuous tokens:
"potassium B-CONC2
and O
magnesium O
replacement I-CONC2"
 - How can I represent overlapping terms in CoNLL file? Is there some alternative way of representing corpus with raw text and a list of start/end indices?

I posted this question on stackoverflow [https://stackoverflow.com/questions/56676804/can-python-flair-interpret-discontinuous-annotations] yesterday, but since there is no 'flair' tag on stackoverflow, I'm posting it here to make sure my question reaches the Flair team or people familiar with Flair.

**Comment by alanakbik** [comment]
Hello @pzalex we currently support standard CoNLL-03-style BIO and BIOES tags. So it is able to find entities that span several tokens, like this: 

```python
from flair.models import SequenceTagger

# load NER tagger
tagger = SequenceTagger.load('ner')

# example sentence
sentence = Sentence('George Washington went to Washington .')

# predict NER tags for example sentence
tagger.predict(sentence)

# print each NER span annotation
for entity in sentence.get_spans('ner'):
    print(entity)
```

This should print: 

```console
PER-span [1,2]: "George Washington"
LOC-span [5]: "Washington"
```

I.e. the span "George Washington" is detected as an entity, because George is tagged as B-PER and Washington as E-PER. 

However, we don't yet support discontinuous or overlapping annotations. Is there a good schema like CoNLL-03 for annotating such cases?

**Comment by ozborn** [comment]
Hi Alan,

I think there are a couple of good schemas, but there is no standard for this type of work. I know some NLP toolkits like [DKPro](https://dkpro.github.io/dkpro-core/releases/1.10.0/docs/format-reference.html) parse a bunch of different formats including CoNLL-03, but as you can see by that link there is quite the variety...

Nonetheless, I would suggest maybe using a SemEval format that supports dis-contiguous annotations. One example would be [SemEval 2015 - Task 14](http://alt.qcri.org/semeval2015/task14/index.php?id=data-and-tools) . They only give contiguous examples on that page, but if you download the data they just use commas to separate the spans like this:
```
09388-093839-DISCHARGE_SUMMARY.txt|30-36,40-51|C0040128|*no|*NULL|*patient|*NULL|*no|
*NULL|*false|*NULL| *unmarked|*NULL|severe|*NULL|*false|*NULL|C0040132|*NULL|
Before|*None|*NULL
```
No particular tokenization is assumed which is really nice. The format is basically **file name|offsets|some label 1 |some label 2....** I think something like this would be the way to go.

Another great format which supports lots of NLP shared tasks is [BRAT](https://brat.nlplab.org/)  .ann format, but the parser would be more elaborate although it is available in python and I think is open source... The project is finished/not active though, but it is still widely used

Hope this helps!

**Comment by alanakbik** [comment]
Hello @ozborn thanks for the info, we'll check out the semeval and brat formats!
