### ISSUE TITLE
How to make the predict (or sentence.labels) output the top-n labels?

### ISSUE THREAD

**Issue by ParthJawale1996** [flairNLP/flair#841]
Hey, I've been trying to make a recommender system for which I need the output as the top-5 predicted labels? How do I do this using the predict/sentence.labels functionality? Also, the sentence.labels outputs the label and it's probability. I just want to make a list of the labels that it has predicted. How do I do this?

**Comment by ParthJawale1996** [comment]
@alanakbik My data does NOT have multiple labels for a single data point, but I still want the labels and scores for the top 5. Any suggestions?

**Comment by stefan-it** [comment]
@ParthJawale1996 I think you can achieve this with:

```python
from flair.data import Sentence
from flair.models import TextClassifier

classifier = TextClassifier.load('en-sentiment')
sentence = Sentence('I like Munich .')

classifier.predict(sentence, multi_class_prob=True)
```

This should output:

```python
[POSITIVE (0.8669394850730896), NEGATIVE (0.13306047022342682)]
```

:)

**Comment by DecentMakeover** [comment]
@stefan-it Here how do i index only the score or only the labels?

Thanks in advance.

**Comment by DecentMakeover** [comment]
Got it, prediction.value and prediction.score.

Thanks anyways.
