### ISSUE TITLE
RuntimeError: CUDA error: initialization error 

### ISSUE THREAD

**Issue by rahul7iitk** [flairNLP/flair#844]
I am using BERT (pre-trained) embedding module for an NLP related task. I am using amazon AWS server,on which i have 4 GPUs. In my code, i set cuda device as 'gpu:0' . However whenever i start my training, I get 
`File "/home/code-base/tacotron2/my_project/lib/python3.6/site-packages/flair-0.4.2-py3.6.egg/flair/embeddings.py", line 1447, in _add_embeddings_internal
    flair.device
RuntimeError: CUDA error: initialization error`
The code only works if i set `flair.device = torch.device('cpu')`
Because of this, it is taking very long to produce word embeddings,so i want to switch to GPU. Please help urgently.

**Comment by stefan-it** [comment]
Hi @rahul7iitk,

currently, I don't have a multi-GPU setup. Could you please try the following (to use only one GPU).

Before running your training script, set this environment variable:

```bash
export CUDA_VISIBLE_DEVICES="0"
```

Now torch and flair will only "see" one GPU. After that execute your training script. Does this help?

**Comment by rahul7iitk** [comment]
Yes, tried that. It didn't help :( 
Also one more thing, i am able to use GPU when i run the code on ipython notebook (outside the main code) . So i guess there is some clash between gpu intialisation in my train.py file and flair/__init__.py file

**Comment by aleSuglia** [comment]
I'm having exactly the same issue. Could you please advise on this? The latest version seems still affected!

**Comment by vdraceil** [comment]
For anyone facing this issue with celery, setting `worker_pool = 'solo'` in celeryconfig would help.
With this setting, celery shall use "spawn" instead of "fork" to spin off workers

Alternatively, you can do the same via the CLI - _ex._ `celery -A app worker -Q queue-name -P solo`

**Comment by jivatneet** [comment]
Hi, I am facing the same issue as described by @aleSuglia and @rahul7iitk. Has anyone been able to find a fix? Thanks.
