### ISSUE TITLE
Model name 'bert-large-uncased' was not found in model name list

### ISSUE THREAD

**Issue by sunweiconfidence** [flairNLP/flair#845]
from flair.data import Sentence
from flair.embeddings import DocumentPoolEmbeddings,BertEmbeddings
embedding = BertEmbeddings('bert-large-uncased')
document_embeddings = DocumentPoolEmbeddings([embedding])
topk = 5
meet with below error:
A clear and concise description of what you want to know.
https://s3.amazonaws.com/models.huggingface.co/bert2019-06-28 11:04:39,796 Model name 'bert-large-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased-vocab.txt' was a path or url but couldn't find any file associated to this path or url.
2019-06-28 11:04:43,306 Model name 'bert-large-uncased' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'https://s3.amazonaws.com/models.huggingface.co/bert/bert-large-uncased.tar.gz' was a path or url but couldn't find any file associated to this path or url.

**Comment by stefan-it** [comment]
Hi @sunweiconfidence,

could you please try the latest version of `flair` (E,g, `pip install --upgrade flair`)? I'm pretty sure that we've fixed that bug a while ago :)

**Comment by sunweiconfidence** [comment]
i have using your command: pip install --upgrade flair, but can't work

**Comment by rahul7iitk** [comment]
Try this - pip3 install git+https://github.com/zalandoresearch/flair.git

**Comment by sunweiconfidence** [comment]
@rahul7iitk  still can't work

**Comment by SuitUp** [comment]
Updating flair (basic pip update) worked for me.
