### ISSUE TITLE
OpenAIGPTEmbeddings() initialization failure

### ISSUE THREAD

**Issue by yliu2018** [flairNLP/flair#854]
**Describe the bug**
When initializing OpenAIGPTEmbeddings() through
embeddings = OpenAIGPTEmbeddings()
,it failed with the following error message:
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**To Reproduce**
Steps to reproduce the behavior (e.g. which model did you train? what parameters did you use? etc.).
embeddings = OpenAIGPTEmbeddings()

**Expected behavior**
It should return the embeddings.

**Screenshots**

**Environment (please complete the following information):**
 - Version : flair-0.4.2

Full errors:
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<command-56669> in <module>()
----> 1 embeddings = get_embeddings(embedding_type)
      2 if document_level_embedding_type == "pooling":
      3   document_embeddings = DocumentPoolEmbeddings(embeddings)

<command-56666> in get_embeddings(embedding_option)
     17     'flair_glove': [FlairEmbeddings('news-forward-fast'), FlairEmbeddings('news-backward-fast'), WordEmbeddings('glove')],
     18     'transformer_xl':[TransformerXLEmbeddings()],
---> 19     'gpt':[OpenAIGPTEmbeddings()],
     20     }.get(embedding_option, [FlairEmbeddings('news-forward-fast'), FlairEmbeddings('news-backward-fast')])

/databricks/python/lib/python3.6/site-packages/flair/embeddings.py in __init__(self, model, pooling_operation)
    762             raise ValueError("Provided OpenAI GPT model is not available.")
    763 
--> 764         self.tokenizer = OpenAIGPTTokenizer.from_pretrained(model)
    765         self.model = OpenAIGPTModel.from_pretrained(model)
    766         self.name = model

/databricks/python/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization_openai.py in from_pretrained(cls, pretrained_model_name_or_path, cache_dir, *inputs, **kwargs)

**Comment by stefan-it** [comment]
This seems to be a `spacy` related problem. One question: did you install `spacy` + downloaded the `en` model? I did that a few days ago, but the error did not go away.

**Comment by stefan-it** [comment]
I'm planing to revise several embeddings, because the upcoming 0.7 release of `pytorch_pretrained_bert` will have a unified api for all models :)

**Comment by yliu2018** [comment]
> This seems to be a `spacy` related problem. One question: did you install `spacy` + downloaded the `en` > model? I did that a few days ago, but the error did not go away.

Thanks for the hint. After I imported spacy and downloaded 'en' model, this error went away.
