### ISSUE TITLE
Why POS tagger to slow compared to stanfordCoreNLP

### ISSUE THREAD

**Issue by pinkal08cece** [flairNLP/flair#858]
I used the simple code for pos tagging i.e. 

`import time`
`from flair.data import Sentence`
`from flair.models import SequenceTagger`
`tagger = SequenceTagger.load('pos-fast')`

`start=time.time()`
`sentence = Sentence("I love Berlin .")`
`tagger.predict(sentence)`
`print(sentence.to_tagged_string())`
`print("time: %s in ms---"%((time.time()-start)*1000))`

It takes average 62 ms and it is too high. StanfordCoreNLP takes only around 6 ms. 

How can you/I do fast POS tagging?

**Comment by alanakbik** [comment]
One way to speed up tagging is to always pass mini-batches of Sentences. For instance, we typically pass 32 sentences at the same time through the tagger though if you have a good GPU you can increase this number. See also #842.

**Comment by pinkal08cece** [comment]
In real time, we can't wait for the next 31 sentences, we need to pass only one sentence then what happens like the question-answering application? There is required one more function which handles a single sentence and it is faster too.

Can you provide any idea for this?
