### ISSUE TITLE
Is it possible to use BILUO dataformat to train a new pre trained NER model?

### ISSUE THREAD

**Issue by swicaksono** [flairNLP/flair#875]
Hey, I have a NER data set written in BILUO data format. I just see the tutorials 6 in load the dataset, and I guess in the train new model, the tutorial is using IOB format. So, if I want to try to train a new pre train NER model by using my BILUO dataset format, is it possible? 

Thank you in advance.

**Comment by alanakbik** [comment]
We current support BIO and BIOES, which is basically the same as BILUO. I think the easiest way would be to rename all L- to E- and all U- to S- in your data and you could directly use Flair as it is.

**Comment by swicaksono** [comment]
Wow, that's great. How about the pos tag, it is something required in the data? Or it is required as a feature when train the model?. My data only consist two coarse columns, the first column is the words/token and the second column is the BILUO-annotated NER tags.

**Comment by alanakbik** [comment]
POS tags are not required and in fact not used at all. The approach directly predicts tags from the surface forms of the words/tokens. You can use the `ColumnCorpus` object to read in your corpus, as described [here](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_6_CORPUS.md#reading-your-own-sequence-labeling-dataset). Just modify the columns to: 

```python
columns = {0: 'text', 1: 'ner'}
```

To indicate that the first column is the text and the second column the NER tag.

**Comment by swicaksono** [comment]
That's very amazing. Thank you!
