### ISSUE TITLE
Upgrade Sentence Tokenizer

### ISSUE THREAD

**Issue by amitbcp** [flairNLP/flair#876]
Currently the corpus for any problem is parsed through the Segtok which is not being maintained. The authors have upgraded it to a new Tokensizer Syntok (https://github.com/fnl/syntok) while having the functionality usage and en-points.

These apart from being very fast for large corpus, has also better tokenization for end of sentences.

**Comment by alanakbik** [comment]
Yes good point, we should do this update!

**Comment by alanakbik** [comment]
The library looks good, but I just tried it with some simple sentences and somehow segtok is giving me better results. Here is one example: 

```python
# difficult text to tokenize
text = "I didn't see Mr. Smith at 12 p.m. on Central Sq. which is approx. near there."

# first try segtok
from segtok.segmenter import split_single
from segtok.tokenizer import split_contractions, word_tokenizer

tokens = []
sentences = split_single(text)
for sentence in sentences:
    contractions = split_contractions(word_tokenizer(sentence))
    tokens.extend(contractions)
print('Segtok: ')
print(tokens)

# second try syntok
from syntok.tokenizer import Tokenizer
tok = Tokenizer()

tokens = []
for token in tok.tokenize(text):
    tokens.append(token.value)
print('Syntok: ')
print(tokens)
```

This prints: 

```console
Segtok: 
['I', 'did', "n't", 'see', 'Mr.', 'Smith', 'at', '12', 'p.m.', 'on', 'Central', 'Sq.', 'which', 'is', 'approx.', 'near', 'there', '.']
Syntok: 
['I', 'did', 'not', 'see', 'Mr', '.', 'Smith', 'at', '12', 'p.m', '.', 'on', 'Central', 'Sq', '.', 'which', 'is', 'approx', '.', 'near', 'there', '.']
```
Unless I am doing something wrong it looks to me like segtok is doing a better job?

**Comment by stefan-it** [comment]
E.g. `p.m.` to `p.m` and `.` should never happen, the output of `syntok` looks really weird. Maybe some parameter tuning is needed 🤔

**Comment by amitbcp** [comment]
This is apparently the design in syntok for some reason. 
If we see the test case file (https://github.com/fnl/syntok/blob/master/syntok/tokenizer_test.txt), it can be seen in the following lines :

- Line 15 & 16
- Line 25 & 26

The test case also highlights the hyphen & underscore splits . Line 9-10 & 11-12.

However this does not effect the sentence /document level interactios.

```python
import syntok.segmenter as segmenter

text = "I didn't see Mr. Smith at 12 p.m. on Central Sq. which is approx. near there.Can he come tommorrow ?"
for paragraph in segmenter.process(text):
    for sentence in paragraph:
        for token in sentence:
            # roughly reproduce the input,
            # except for hyphenated word-breaks
            # and replacing "n't" contractions with "not",
            # separating tokens by single spaces
            print(token.value, end=' ')
        print()  # print one sentence per line
    print()  # separate paragraphs with newlines 
```

This prints 
````
I did not see Mr . Smith at 12 p.m . on Central Sq . which is approx . near there . 
Can he come tomorrow ?

**Comment by alanakbik** [comment]
Hm strange, but in this case we should probably keep the existing segtok module for now. In the future, we want to refactor the tokenization part of Flair anyway so that arbitrary tokenizers can be used.

**Comment by alanakbik** [comment]
Setting tokenizers was added as a feature a while back.
