### ISSUE TITLE
[Errno 22] Invalid argument: 'best-model.pt'

### ISSUE THREAD

**Issue by ParthJawale1996** [flairNLP/flair#884]
After the first epoch, I'm getting this as the error message: 

OSError                                   Traceback (most recent call last)
<ipython-input-39-015b4d136bca> in <module>
----> 1 trainer.train('./', max_epochs = 50, learning_rate = 0.2)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\flair\trainers\trainer.py in train(self, base_path, evaluation_metric, learning_rate, mini_batch_size, eval_mini_batch_size, max_epochs, anneal_factor, patience, train_with_dev, monitor_train, monitor_test, embeddings_in_memory, checkpoint, save_final_model, anneal_with_restarts, shuffle, param_selection_mode, num_workers, **kwargs)
    335                     and current_score == scheduler.best
    336                 ):
--> 337                     self.model.save(base_path / "best-model.pt")
    338 
    339             # if we do not use dev data for model selection, save final model

~\AppData\Local\Continuum\anaconda3\lib\site-packages\flair\nn.py in save(self, model_file)
     66         model_state = self._get_state_dict()
     67 
---> 68         torch.save(model_state, str(model_file), pickle_protocol=4)
     69 
     70     def save_checkpoint(

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\serialization.py in save(obj, f, pickle_module, pickle_protocol)
    222         >>> torch.save(x, buffer)
    223     """
--> 224     return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
    225 
    226 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\serialization.py in _with_file_like(f, mode, body)
    145             (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
    146         new_fd = True
--> 147         f = open(f, mode)
    148     try:
    149         return body(f)

OSError: [Errno 22] Invalid argument: 'best-model.pt'

**Comment by alanakbik** [comment]
Hm strange, can you make sure that the base path exists when calling the trainer?
