### ISSUE TITLE
Any chance for sense2vec to be supported? 

### ISSUE THREAD

**Issue by Hellisotherpeople** [flairNLP/flair#887]
Hi all, I've thought that the idea of concatenating PoS tags and word embeddings together was a great idea. I learned recently about sense2vec, which creates embeddings on words+PoS tags. 

Will flair ever support sense2vec? What about a WordNet disambiguated word2vec model?

**Comment by alanakbik** [comment]
Hi @Hellisotherpeople - sense2vec looks really interesting so I can see us intergrating this. Of course community contributions are always welcome :)
