### ISSUE TITLE
Size Mismatch Error even after creating Document Embeddings

### ISSUE THREAD

**Issue by ParthJawale1996** [flairNLP/flair#895]
This is the structure of my model:
Model: "TextClassifier(
  (document_embeddings): DocumentPoolEmbeddings(
    fine_tune_mode=nonlinear, pooling=mean
    (embeddings): StackedEmbeddings(
      (list_embedding_0): WordEmbeddings('en-news')
    )
    (embedding_flex): Linear(in_features=300, out_features=300, bias=False)
    (embedding_flex_nonlinear): ReLU(inplace)
    (embedding_flex_nonlinear_map): Linear(in_features=300, out_features=300, bias=True)
  )
  (decoder): Linear(in_features=300, out_features=2591, bias=True)
  (loss_function): CrossEntropyLoss()
)"

I'm getting an error message that says "size mismatch, m1: [3 x 2348], m2: [300 x 300] at C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src\THC/generic/THCTensorMathBlas.cu:268"

Any ideas how to fix this?

**Comment by alanakbik** [comment]
Can you paste a minimal full code example to reproduce the error?

**Comment by saj1919** [comment]
@ParthJawale1996 Not sure what your code is, but do make sure to create new **Sentence()** to test every time you modify **DocumentPoolEmbeddings()** initialization. For me it throws the error in that case.
