### ISSUE TITLE
NER split causes train/test/dev to have only one sentence each

### ISSUE THREAD

**Issue by GeorgeG92** [flairNLP/flair#909]
Greetings, I am using the dataset from here (https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus) to train a NER model using Flair. I discarded the 'Sentence No' column, since I believe it is not used here (correct me if I am wrong), and renamed the columns to 'text', 'pos', 'ner'. On load, the data is already in the form of: 

Thousands | NNS | O
of | IN | O
demonstrators | NNS | O
have | VBP | O
marched | VBN | O
...

as I think it is expected, so I use ColumnCorpus to load it move on. Training failed (CUDA memory error) so I investigated a bit and realized all train/test/dev sets contain one sentence each (with all the tokens from all the sentences of the corpus). So:
len(corpus.train[0]) is 1,  and so on.
I believe it is a pre-processing step I am missing, possibly with full-stops, as apparently the code does not understand how to separate the data into lists of sentences. 
Keep in mind that there are full-stops in the data, e.g. test.csv starts like this:

They PRP O
were VBD O
successful JJ O
in IN O
getting VBG O
it PRP O
out IN O
of IN O
the DT O
plane NN O
and CC O
home NN O
. . O      <--
 
Please help me overcome this issue! I appreciate the help.

**Comment by alanakbik** [comment]
The reader expects there to be an empty line after each sentence. Something like this: 

```console
This PRP O
is VBD O
one JJ O
sentence NN O

This PRP O
is VBD O
another JJ O
sentence NN O
```

Is your data formatted in this way?

**Comment by amitbcp** [comment]
@GeorgeG92  I am also trying to train a model over the same data-set. 
One thing to keep in my is shuffling the data in sentences between splits ensuring that a single sentence is not spitted in different train/dev/test sets.

Though I have had some problem in creating the splits. If you are able to get a crack on it, kindly let me know as well/

**Comment by GeorgeG92** [comment]
> 
> 
> The reader expects there to be an empty line after each sentence. Something like this:
> 
> ```
> This PRP O
> is VBD O
> one JJ O
> sentence NN O
> 
> This PRP O
> is VBD O
> another JJ O
> sentence NN O
> ```
> 
> Is your data formatted in this way?

Thank you for the info, I was not aware of this! I did the processing so now my data looks like this:

![image](https://user-images.githubusercontent.com/33267892/61631270-39ff2e80-ac8a-11e9-8c1d-a0b3e8d58802.png)

After the processing, len(corpus.train[0]) is 38188, which sounds about right! Training still gets stuck at this forever though:

![image](https://user-images.githubusercontent.com/33267892/61631371-7763bc00-ac8a-11e9-8734-815e43965a6a.png)

 any advice?

> 
> 
> @GeorgeG92 I am also trying to train a model over the same data-set.
> One thing to keep in my is shuffling the data in sentences between splits ensuring that a single sentence is not spitted in different train/dev/test sets.
> 
> Though I have had some problem in creating the splits. If you are able to get a crack on it, kindly let me know as well/

I am getting there, will post any updates on this thread!

**Comment by alanakbik** [comment]
@GeorgeG92 maybe try with really simple embeddings first to see if that works? For instance, only train with GloVe embeddings?

**Comment by GeorgeG92** [comment]
> 
> 
> @GeorgeG92 I am also trying to train a model over the same data-set.
> One thing to keep in my is shuffling the data in sentences between splits ensuring that a single sentence is not spitted in different train/dev/test sets.
> 
> Though I have had some problem in creating the splits. If you are able to get a crack on it, kindly let me know as well/

I prepared some code that ensures train/test/dev splits end with whole sentences (thus one sentence cannot be split into two sets). 

trainstart = df.index[0]
tmpdf = df[int(len(df)*0.8):]                                                   
trainstop = tmpdf.loc[0:tmpdf['text'].gt('').idxmin(),:].index[-1] 
train sentence ends)
train = df.iloc[0:trainstop]

teststart = trainstop+1
tmpdf = df[int(len(df)*0.9):]
teststop = tmpdf.loc[int(len(df)*0.9):tmpdf['text'].gt('').idxmin(),:].index[-1]
test = df.iloc[teststart:teststop]

devstart = teststop+1
dev = df.iloc[valstart:]

Of course, it probably is not the most efficient (or nice) peace of code but it works. Also there is no shuffling of the sentences as this needs to be done beforehand, right after the data gets aggregated to a sentence level, but that should not be difficult to code.
Using Glove embeddings, I was able to train the model just fine, Bert embeddings do not work though.

**Comment by alanakbik** [comment]
Maybe try our [recommended embeddings setup](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md#recommended-flair-usage), it normally works pretty well.

**Comment by GeorgeG92** [comment]
> 
> 
> Maybe try our [recommended embeddings setup](https://github.com/zalandoresearch/flair/blob/master/resources/docs/TUTORIAL_4_ELMO_BERT_FLAIR_EMBEDDING.md#recommended-flair-usage), it normally works pretty well.

This setup (Stacked bi-directional Flair embeddings with Glove) works okay, any ideas why Bert embeddings don't work?

**Comment by alanakbik** [comment]
Do they not work at all or just don't give very good results?

**Comment by GeorgeG92** [comment]
> 
> 
> Do they not work at all or just don't give very good results?

It does not work. I have been running it on colab (exact same settings to the flair-glove embeddings combo) and it stays like this for at least 45 minutes (afterwards I stopped it):

![image](https://user-images.githubusercontent.com/33267892/61653759-5071ae00-acbb-11e9-9eda-f262fcc45959.png)

At some point I got a CUDA memory warning (it was close to its full 12gbs).
At some point I got a

**Comment by alanakbik** [comment]
Hm strange. Generally, BERT is slower than Flair embeddings and they have a maximum sequence length of 512 subtokens, but if you have a GPU it should not take this long.
