### ISSUE TITLE
Could not install version 0.4.2 with pip

### ISSUE THREAD

**Issue by maironcastro** [flairNLP/flair#912]
**Describe the bug**
I am trying to install the version `0.4.2` with pip, but I'm getting the following error.

```
Collecting flair==0.4.2 (from -r requirements-embeddings.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/0f/0e/1600bfbc2f5d95160532eb78edb2cd29840d005f9f8050bec62a98833d42/flair-0.4.2.tar.gz (94kB)
/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py:244: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ow3yfdtu/flair/setup.py", line 3, in <module>
        with open("requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ow3yfdtu/flair/
```

I downloaded the file `https://files.pythonhosted.org/packages/0f/0e/1600bfbc2f5d95160532eb78edb2cd29840d005f9f8050bec62a98833d42/flair-0.4.2.tar.gz` and the file `requirements.txt` actually doesn't exists. But there is a file with requirements inside `flair.egg-info/requires.txt`.

The problem is that inside `setup.py`, on line `3`, the setup is trying to get the `requirements.txt` file:

`with open("requirements.txt") as f:`

Im running the install with `pip install --no-cache-dir --compile --global-option=build_ext flair==0.4.2`

Is it really a bug with the deployed library? Or am I missing something?

**Environment**
 - OS [python:3.6-slim docker image]:
 - Version [flair-0.4.2]:

**Comment by alanakbik** [comment]
Hm I think most people can install directly with `pip install flair`. Do you maybe somehow have an old `pip` version or are not using Python 3.6+?

**Comment by maironcastro** [comment]
It seems like its the flags `--no-cache-dir --compile --global-option=build_ext ` I'm using in pip.
I have used the same flags in version `0.4.1` and it worked.
I think the version `0.4.2` might have some configuration problem when these flags are used.

**Comment by VDCN12593** [comment]
I am having the same problem with 0.4.5. I think this is a bug triggered by using the pip flag `--no-cache-dir` 

I am using bazel to build flair as a third-party library target, and there is no easy way for me to change the flags used by pip. So I would appreciate it if you can possibly fix around this. Thank yo very much!

**Comment by glittershark** [comment]
wow that's a bummer
