### ISSUE TITLE
Transfer Learning with NER Models

### ISSUE THREAD

**Issue by amitbcp** [flairNLP/flair#919]
Since transfer learning helps us start from a good start point, training a NER model from a pre-trained NER model will be helpful.

I was trying to stack/train a Sequence Tagger which was trained  on ner or ner-onnotes and re-train it for some more custome entities but was not able to find a straight forward way for the same.

Can you please guide for the same ?

Another question is that I have my data in the format that is printed by
``` python
print(sentence.to_dict(tag_type='ner'))
```
```
{'text': 'George Washington went to Washington .',
    'entities': [
        {'text': 'George Washington', 'start_pos': 0, 'end_pos': 17, 'type': 'PER', 'confidence': 0.999},
        {'text': 'Washington', 'start_pos': 26, 'end_pos': 36, 'type': 'LOC', 'confidence': 0.998}
    ]}
```

Is there any built-in parser that can convert this format to Flair input data format for NER or I have to got for a custom parser ?

**Comment by alanakbik** [comment]
Hi @amitbcp I guess the problem is that the output tag set would be different, so you could not reuse the CRF layer or the final projection layer () since it projects into tag space. You would probably be able to reuse everything until then, i.e. the embedding layer and the LSTM weights. One thing you could do is to initialize a new model and copy over the LSTM weights from the pre-trained model. It would be interesting to see if this helps training. 

There is not in-built method to output a sentence to a column based format, but it should be easy to write. You would need to iterate over all tokens of a sentence and for each token print out the token text and its NER tag.

**Comment by amitbcp** [comment]
Thanks @alanakbik .

Though for some reason I am not able to retrieve the pre-trained model architecture.
Sample Code :

```python
for module in tagger.named_modules():
    print(module)
```
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-da55d6628d11> in <module>()
      1 for module in tagger.named_modules():
----> 2     print(module)

c:\users\amit.agarwal\appdata\local\programs\python\python36\lib\site-packages\torch\nn\modules\module.py in __repr__(self)
   1031         child_lines = []
   1032         for key, module in self._modules.items():
-> 1033             mod_str = repr(module)
   1034             mod_str = _addindent(mod_str, 2)
   1035             child_lines.append('(' + key + '): ' + mod_str)

c:\users\amit.agarwal\appdata\local\programs\python\python36\lib\site-packages\torch\nn\modules\module.py in __repr__(self)
   1031         child_lines = []
   1032         for key, module in self._modules.items():
-> 1033             mod_str = repr(module)
   1034             mod_str = _addindent(mod_str, 2)
   1035             child_lines.append('(' + key + '): ' + mod_str)

c:\users\amit.agarwal\appdata\local\programs\python\python36\lib\site-packages\torch\nn\modules\module.py in __repr__(self)
   1025         # We treat the extra repr like the sub-module, one item per line
   1026         extra_lines = []
-> 1027         extra_repr = self.extra_repr()
   1028         # empty string will be split into list ['']
   1029         if extra_repr:

c:\users\amit.agarwal\appdata\local\programs\python\python36\lib\site-packages\flair\embeddings.py in extra_repr(self)
    343 
    344     def extra_repr(self):
--> 345         return f"'{self.embeddings}'"
    346 
    347 

c:\users\amit.agarwal\appdata\local\programs\python\python36\lib\site-packages\torch\nn\modules\module.py in __getattr__(self, name)
    533                 return modules[name]
    534         raise AttributeError("'{}' object has no attribute '{}'".format(
--> 535             type(self).__name__, name))
    536 
    537     def __setattr__(self, name, value):

AttributeError: 'WordEmbeddings' object has no attribute 'embeddings'
```

The error is consistent  modules(),named_modules(),named_children()

Though the named_parameters,parameters & state_dict() return the dictionary with weight.
One last thing I am getting confused to understand is the output of the below snippet.

```python
for child in tagger.children() :
    print(child)
```
```python
StackedEmbeddings [/home/aakbik/.flair/embeddings/glove.gensim,data/embeddings/news-forward--h2048-l1-d0.05-grow/epoch_8.pt,data/embeddings/news-backward--h2048-l1-d0.05-grow/epoch_8.pt]
WordDropout(p=0.05)
LockedDropout(p=0.5)
Linear(in_features=4196, out_features=4196, bias=True)
LSTM(4196, 256, bidirectional=True)
Linear(in_features=512, out_features=20, bias=True)
```

I am sorry for so many queries, but could you help me over here to  load new model with the pre-trained weights. I also went over the Pytorch Documentation but wasn't able to get through it.

**Comment by DecentMakeover** [comment]
@amitbcp hey were you able to get this working?

**Comment by amitbcp** [comment]
@DecentMakeover not yet. It is quiet still stuck with this and not able to move the weights.

**Comment by DecentMakeover** [comment]
okay ,please post if you make any progress, also wanted to know how is performance for NER on your task, for my task i am able to achieve 90 ,but struggling to get it above that

**Comment by desusai7** [comment]
@amitbcp  Hey did you completed doing this

**Comment by amitbcp** [comment]
@desusai7 No, I was not able to complete this. Are you looking to do the same ?

**Comment by desusai7** [comment]
@amitbcp  Yes,I am looking to do the same and achieved some progress in doing so and had some doubts regarding this and can we discuss this and solve it together

**Comment by abeermohamed1** [comment]
Hello @alanakbik 

I want to use custom predefine Arabic NER model. i am using the below code but i am not sure if it is correct or shall i fork flair for adding customization code.
Kindly note that the below code decreases the accuracy. thank you

tagger: SequenceTagger = SequenceTagger(hidden_size=256,
                                        embeddings=embeddings,
                                        tag_dictionary=tag_dictionary,
                                        tag_type=tag_type  ).load('/content/gdrive/My Drive/resources//final-modeltran.pt')
