### ISSUE TITLE
Custom sentiment analysis model

### ISSUE THREAD

**Issue by IsaDash** [flairNLP/flair#931]
Has anyone tried to build a custom sentiment analysis model using flair text classification? I know the built in sentiment analysis model has been pre-trained on movie reviews, but for my specific case I am training a sentiment model on tweets. 

With about 20,000 tweets, I am getting around 59% accuracy. I am using stacked embeddings with flair forward and backward embeddings, BERT, glove, and finally DocumentLSTM. 

Are there any other embeddings that could be helpful for sentiment analysis? Or any other ideas on how to improve accuracy other than using a larger dataset? Any help appreciated!

**Comment by alanakbik** [comment]
@IsaDash thanks for sharing the results. Is your dataset publicly available? If so, could you share the link?
