### ISSUE TITLE
Loss stuck （tagger training using my own training flair embedding)

### ISSUE THREAD

**Issue by songtaoshi** [flairNLP/flair#932]
Hello, I am wondering the tagger's initialization. When I train the tagger using my own training flair embedding, I can't get my loss decreased.
![image](https://user-images.githubusercontent.com/20240391/61991168-ee2ff900-b07e-11e9-803e-2189a5b5c473.png)
I think my own embedding is trained correctly
![image](https://user-images.githubusercontent.com/20240391/61991181-128bd580-b07f-11e9-9b1c-0c5cc95191d7.png)

**Comment by songtaoshi** [comment]
@alanakbik hello alan do you have some suggestions, i am really confused

**Comment by songtaoshi** [comment]
@alanakbik what is the initialization of sequence tagger when we create the model?

**Comment by alanakbik** [comment]
Hello @songtaoshi were you able to find out why loss is not going down faster? Generally, all neural layers in the SequenceTagger are standard PyTorch components so get I think random initialization and are then trained on the task. What embedding combination are you using here?

**Comment by songtaoshi** [comment]
sorry for the late reply, I train my own flair embedding. and only use the flair embedding. But I think the flair embedding is trained correctly

**Comment by marcelgwerder** [comment]
@songtaoshi Ever figured out why this happened? I have an issue and the output looks very similar to this so I'm wondering if it might be the same cause.
