### ISSUE TITLE
ColumnDataset sentence split rule overcomplicated

### ISSUE THREAD

**Issue by klasocki** [flairNLP/flair#953]
The line in ColumnDataset which decides whether the next token should be added to the current or new sentence:
`if line.strip().replace("﻿", "") == "":`
Is way too complicated. Finding out how the data is divided into Sentences is one of the main things when working with ColumnCorpus, but I found it difficult since there is nothing about it in the tutorial.
Should I make a pull request simplifying this if statement and adding the appropriate example to the tutorial?

**Comment by alanakbik** [comment]
@klasocki sure we always appreciate a PR. Generally though, the column format is fairly standard across most tasks (CoNLL-03, CoNLL-U etc.) so a newline to divide sentence is standard in this format.

**Comment by klasocki** [comment]
Ok, but I still added that to the tutorial in the PR. It'll make it easier for people (like me) who first came across the newline dividing sentence standard while using your framework :)

**Comment by alanakbik** [comment]
PR merged a while back
