### ISSUE TITLE
Embed sentences using multiple GPUs

### ISSUE THREAD

**Issue by jasminesjlee** [flairNLP/flair#964]
Is it possible to split the operation of embedding sentences across multiple GPUs? It looks like "flair.device" must be explicitly set to one device, which makes me think this is not possible, but wanted to make sure.

**Comment by alanakbik** [comment]
Hm good question. Do you have a very large dataset from which you would like to extract embeddings? One very simple way would be to split it into splits and then start separate embedding processes for each split.

**Comment by jasminesjlee** [comment]
Yes. Is it possible for me to do separate embedding processes for each split on different GPUs?
