### ISSUE TITLE
RFC: GitHub Project page and release cycle

### ISSUE THREAD

**Issue by stefan-it** [flairNLP/flair#969]
Hi,

it would be awesome to have the Project management functionaltity enabled here for the Flair repository :)

This would enable a nice tracking of features (their implementation state, backlog) or bug fixes for an upcoming version of Flair. Additionally, it would make it a lot easier to create a kind of changelog for a certain release. Here's a great example of such a Project page:

https://github.com/ProjectMirador/mirador/projects/1

Regarding to upcoming Flair release(s): do you think a regular release cycle (monthly, like the GitLab guys are doing) makes sense for Flair?

**Comment by alanakbik** [comment]
Yes I think we should definitely increase the speed of releases. After the last release I really wanted to start doing monthly releases but somehow this didn't materialize. I think too fixed a release cycle might hamper flexibility, but aiming for a release say on the first of every month might be a good idea.

**Comment by stefan-it** [comment]
I would really like to have this Project page here :) Would be great to track issues for upcoming releases 🤗

**Comment by alanakbik** [comment]
Yes, we could try this in the near future! Especially once my department grows we'll need to look into better tooling to assist the development workflow.
