### ISSUE TITLE
Backward Flair LM

### ISSUE THREAD

**Issue by jasminesjlee** [flairNLP/flair#975]
Hello,
I am training a backward Flair language model. I have done everything that is necessary, such as using is_forward_lm=False as a parameter in the LanguageModel and in the TextCorpus. However, when I feed this language model and corpus into my LanguageModelTrainer, the text generation looks something like the following: "< for > knu < six > knu < minutes > knu < can > knu < you > knu < play > knu < no > knu < hear > knu < someine > knu < girl >"
I feel like since <unk> is backwards, the words should also be backwards.. however as you see in this example, though the <unk> is backwards, the generated text is in the correct direction.

Is this normal? Thanks!

**Comment by alanakbik** [comment]
Yes the `generate_text()` automatically inverts the generated text if its a backwards language model so it remains readable.
