### ISSUE TITLE
Unable to import flair on OSX after latest pip install 

### ISSUE THREAD

**Issue by delip** [flairNLP/flair#992]
**Describe the bug**

I get this error when I import `flair`:
...
~/anaconda3/envs/cvtorchpy37/lib/python3.7/site-packages/apex/amp/lists/torch_overrides.py in <module>
     67          'baddbmm',
     68          'bmm']
---> 69 if utils.get_cuda_version() >= (9, 1, 0):
     70     FP16_FUNCS.extend(_bmms)
     71 else:

~/anaconda3/envs/cvtorchpy37/lib/python3.7/site-packages/apex/amp/utils.py in get_cuda_version()
      7
      8 def get_cuda_version():
----> 9     return tuple(int(x) for x in torch.version.cuda.split('.'))
     10
     11 def is_fp_tensor(x):

AttributeError: 'NoneType' object has no attribute 'split'
```

**To Reproduce**
Steps to reproduce the behavior (e.g. which model did you train? what parameters did you use? etc.).

```
pip install flair
python -m flair
```

**Environment (please complete the following information):**
```
 - OS: Darwin aiflaptop.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
 - Version: latest available via pip
```

**Comment by delip** [comment]
Update: seeing this in ubuntu too:
```
(delip_uniface) delip@aifdl1:~$ uname -a
Linux aifdl1 4.15.0-55-generic #60~16.04.2-Ubuntu SMP Thu Jul 4 09:03:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
(delip_uniface) delip@aifdl1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
(delip_uniface) delip@aifdl1:~$ 
```

**Comment by yosipk** [comment]
Hi @delip!

I have tried to reproduce bug. My setup is:
```
Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```
and I've installed Flair via pip (version 0.4.2) in fresh virtualenv:
```
virtualenv flair_test
source flair_test/bin/activate
pip install flair
```
the pip installs flair and depending packages
```
Successfully installed atomicwrites-1.3.0 attrs-19.1.0 boto-2.49.0 boto3-1.9.208 botocore-1.12.208 bpemb-0.3.0 certifi-2019.6.16 chardet-3.0.4 cycler-0.10.0 decorator-4.4.0 deprecated-1.2.6 docutils-0.14 flair-0.4.2 future-0.17.1 gensim-3.8.0 hyperopt-0.1.2 idna-2.8 importlib-metadata-0.19 jmespath-0.9.4 joblib-0.13.2 kiwisolver-1.1.0 matplotlib-3.1.1 more-itertools-7.2.0 mpld3-0.3 networkx-2.3 numpy-1.17.0 packaging-19.1 pluggy-0.12.0 py-1.8.0 pymongo-3.9.0 pyparsing-2.4.2 pytest-5.0.1 python-dateutil-2.8.0 pytorch-pretrained-bert-0.6.2 regex-2019.6.8 requests-2.22.0 s3transfer-0.2.1 scikit-learn-0.21.3 scipy-1.3.1 segtok-1.5.7 sentencepiece-0.1.82 six-1.12.0 sklearn-0.0 smart-open-1.8.4 sqlitedict-1.6.0 tabulate-0.8.3 torch-1.2.0 tqdm-4.33.0 urllib3-1.24.3 wcwidth-0.1.7 wrapt-1.11.2 zipp-0.5.2
```
and I can import flair from python:
```
python -c "import flair; print(f'{flair.__version__}')"
```
prints:
```
0.4.2.
```
Python version is 3.7.3.

The error you have is related to APEX which is in master branch, but not in 0.4.2, so that's strange.

**Comment by yosipk** [comment]
Looks like you have APEX installed, and when APEX is installed the package `pytorch_transformers` assumes that it can use it. The error occurs when APEX tries to get CUDA version via torch.version.cuda and gets None. APEX assumes that CUDA device exists.

The solution would be either to install Flair in a virtualenv without APEX.
