### ISSUE TITLE
How to reproduce the rusult of these papers mentioned?

### ISSUE THREAD

**Issue by zwacm** [flairNLP/flair#994]
Hi,
I want to reproduce the result of these papers, Contextual String Embeddings for Sequence Labeling, and Pooled Contextualized Embeddings for Named Entity Recognition. Besides, I am going to make an evaluation on my own datasets. However, I don't know how to make it?  

Any advice will be appreciated.

Thank you!

**Comment by stefan-it** [comment]
Hi @zwacm,

a good start would be the documentation section for experiments:

https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md

It provides code code examples and shows, what embeddings were used for certain datasets :)

**Comment by zwacm** [comment]
Thank you for response!
I am tring to run th example code of [https://github.com/zalandoresearch/flair/tree/v0.2.0](url)  and I follow as the EXPERIMENTS.md. However I got the ConnectError because of  network. 

Is there any advice in order to successfully run it?
Thank you.

**Comment by zwacm** [comment]
> Hi @zwacm,
> 
> a good start would be the documentation section for experiments:
> 
> https://github.com/zalandoresearch/flair/blob/master/resources/docs/EXPERIMENTS.md
> 
> It provides code code examples and shows, what embeddings were used for certain datasets :)

also meet with [https://github.com/zalandoresearch/flair/issues/995](url)
