### ISSUE TITLE
Convert Flair embeddings to gensim format

### ISSUE THREAD

**Issue by mustaszewski** [flairNLP/flair#998]
When initializing Flair embeddings with the following code

```
from flair.embeddings import FlairEmbeddings
emb_flair_bw = FlairEmbeddings('de-backward')
```
the file `lm-mix-german-backward-v0.2rc.pt` is downloaded to `/root/.flair/embeddings/`. Is it possible to convert this file to the Gensim format?

**Comment by BernierCR** [comment]
Flair embeddings are character-level. That's the whole reason they exist. Gensim only supports word-level embeddings. So impossible. 

What is your end goal here?
